### ISSUE TITLE
How can i do early stopping in optuna?

### ISSUE THREAD

**Issue by Alex-Lekov** [optuna/optuna#1001]
How can i do **early stopping** in optuna? I tried pruners, but they do not stop the optimization. just stop the training round. I would like to immediately stop the all optimization when the new best models have not appeared for a long time. Without waiting for the completion of all rounds or time...

**Comment by hvy** [comment]
Are you looking for something like https://github.com/optuna/optuna/issues/966 ?

**Comment by Alex-Lekov** [comment]
> Are you looking for something like #966 ?

Yes. I did not find how to stop the optimization entirely by the rule. I tried `raise  optuna.structs.TrialPruned()`, but it only skips the round.

**Comment by hvy** [comment]
There are no APIs dedicated for you're describing yet (see #966). However, such a feature has been asked for before and a workaround was also suggested https://github.com/optuna/optuna/issues/850#issuecomment-577018760. You'll probably have to modify the body of the callback function to iterate over previous trials (which are accessible through the `study`).

**Comment by Alex-Lekov** [comment]
Thanks for the answer! Here is my quick version of this functionality. Hope authors add this feature in upcoming versions?


```
OPTUNE_EARLY_STOPING = 10

class EarlyStoppingExceeded(optuna.exceptions.OptunaError):
    early_stop = OPTUNE_EARLY_STOPING
    early_stop_count = 0
    best_score = None

def early_stopping_opt(study, trial):
    if EarlyStoppingExceeded.best_score == None:
      EarlyStoppingExceeded.best_score = study.best_value

    if study.best_value < EarlyStoppingExceeded.best_score:
        EarlyStoppingExceeded.best_score = study.best_value
        EarlyStoppingExceeded.early_stop_count = 0
    else:
      if EarlyStoppingExceeded.early_stop_count > EarlyStoppingExceeded.early_stop:
            EarlyStoppingExceeded.early_stop_count = 0
            best_score = None
            raise EarlyStoppingExceeded()
      else:
            EarlyStoppingExceeded.early_stop_count=EarlyStoppingExceeded.early_stop_count+1
    #print(f'EarlyStop counter: {EarlyStoppingExceeded.early_stop_count}, Best score: {study.best_value} and {EarlyStoppingExceeded.best_score}')
    return

```

```
study = optuna.create_study()
try:
    study.optimize(objective, timeout=60, callbacks=[early_stopping_opt])
except EarlyStoppingExceeded:
    print(f'EarlyStopping Exceeded: No new best scores on iters {OPTUNE_EARLY_STOPING}')

```

[Colab Notebook](https://colab.research.google.com/drive/1I8abciKFXBxkoXrcwLiG7_BrYskLnV8k)

**Comment by hvy** [comment]
Thanks for sharing your code and generously a notebook on Colab. As you are not the first one to ask, future users will most likely find this useful as well. Let me close this issue for now as fixed and let us keep an eye on #966 to introduce a dedicated API.

**Comment by lefnire** [comment]
Indeed, this future user found this most valuable

**Comment by Y-oHr-N** [comment]
I have created a callback using the stop method. I'm sharing it as it might be useful for someone else.

```python
import operator

import numpy as np
import optuna


class EarlyStoppingCallback(object):
    """Early stopping callback for Optuna."""

    def __init__(self, early_stopping_rounds: int, direction: str = "minimize") -> None:
        self.early_stopping_rounds = early_stopping_rounds

        self._iter = 0

        if direction == "minimize":
            self._operator = operator.lt
            self._score = np.inf
        elif direction == "maximize":
            self._operator = operator.gt
            self._score = -np.inf
        else:
            ValueError(f"invalid direction: {direction}")

    def __call__(self, study: optuna.Study, trial: optuna.Trial) -> None:
        """Do early stopping."""
        if self._operator(study.best_value, self._score):
            self._iter = 0
            self._score = study.best_value
        else:
            self._iter += 1

        if self._iter >= self.early_stopping_rounds:
            study.stop()


def objective(trial: optuna.Trial) -> float:
    ....


direction = "maximize"
study = optuna.create_study(direction=direction)
early_stopping = EarlyStoppingCallback(10, direction=direction)

study.optimize(objective, callbacks=[early_stopping], timeout=3600)
```

**Comment by nzw0301** [comment]
Indeed, optuna has introduced early-stopping-ish as a pruner since v2.8.0.
Please see this page for more details -- https://optuna.readthedocs.io/en/stable/reference/generated/optuna.pruners.PatientPruner.html.

**Comment by Y-oHr-N** [comment]
@nzw0301 `PatientPruner` only stop a trial. What we want to do is stop the optimization itself.

**Comment by nzw0301** [comment]
Ah, thank you for your clarification. I misunderstood the meaning of early-stopping in this issue.

**Comment by AnuragAnalog** [comment]
I have created a callback using the @Y-oHr-N code for another use, such as stopping the optimization after reaching a particular threshold.

# Callbacks

class ThresholdReachedCallback():
    """Threshold Reached Callback for Optuna"""

    def __init__(self, threshold, direction: str = "minimize") -> None:
        self.direction = direction
        self.threshold = threshold
        self._callback_called = False

        if self.direction == "minimize":
            self._operator = operator.lt
            self._score = np.inf
        elif self.direction == "maximize":
            self._operator = operator.gt
            self._score = -np.inf
        else:
            raise ValueError(f"Expected direction value from ['minimize', 'maximize'], but got {self.direction}")

    def __str__(self) -> str:
        if self._callback_called:
            return f"Objective {self.direction}d and stopped after reaching a threshold value of {self.threshold}"

        return super().__str__()

    def __call__(self, study: optuna.Study, trial: optuna.Trial) -> None:
        """Stop the optimization when threshold value is crossed"""

        self._callback_called = True

        if self._operator(study.best_value, self.threshold):
            study.stop()

        return

**Comment by jeanfredericplante** [comment]
an alternative solution:
```python
 def early_stopping_check(study, trial, early_stopping_rounds=10):
      current_trial_number = trial.number
      best_trial_number = study.best_trial.number
      should_stop = (current_trial_number - best_trial_number) >= early_stopping_rounds
      if should_stop:
          logger.debug("early stopping detected: %s", should_stop)
          study.stop()
```
and as a callback add a partial 
```python
...,callbacks=[partial(early_stopping_check, early_stopping_rounds=early_stopping_rounds)],
```

**Comment by harshgits** [comment]
Hey, yeah, this feature please. Would make Optuna even more awesome and useful!!

**Comment by nzw0301** [comment]
Since Optuna is an open-source software, please feel free to send a pull request.

**Comment by jonaslandsgesell** [comment]
@jeanfredericplante thanks for your solution.
For others: please add the import ```from functools import partial ``` to be able to access partial.
> 
> ```python
>  def early_stopping_check(study, trial, early_stopping_rounds=10):
>       current_trial_number = trial.number
>       best_trial_number = study.best_trial.number
>       should_stop = (current_trial_number - best_trial_number) >= early_stopping_rounds
>       if should_stop:
>           logger.debug("early stopping detected: %s", should_stop)
>           study.stop()
> ```
> 
> and as a callback add a partial
> 
> ```python
> ...,callbacks=[partial(early_stopping_check, early_stopping_rounds=early_stopping_rounds)],
> ```

**Comment by marcelovca90** [comment]
> ```python
> best_score = None
> ```

Shouldn't it be `EarlyStoppingExceeded.best_score = None` instead of `best_score = None`?

**Comment by shadiakiki1986** [comment]
> an alternative solution:
> 
> ```python
>  def early_stopping_check(study, trial, early_stopping_rounds=10):
>       current_trial_number = trial.number
>       best_trial_number = study.best_trial.number
>       should_stop = (current_trial_number - best_trial_number) >= early_stopping_rounds
>       if should_stop:
>           logger.debug("early stopping detected: %s", should_stop)
>           study.stop()
> ```
> 
> and as a callback add a partial
> 
> ```python
> ...,callbacks=[partial(early_stopping_check, early_stopping_rounds=early_stopping_rounds)],
> ```

To use the optuna logger:

```
from optuna.logging import _get_library_root_logger
logger = _get_library_root_logger()
```
and the default logging level is "INFO", so it helps to change `logger.debug` to `logger.info`
