### ISSUE TITLE
`sklearn.utils.safe_indexing` will be removed in `scikit-learn==0.24`.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1004]
`sklearn.utils.safe_indexing` in `optuna.integration.sklearn.OptunaSearchCV` should be updated because it is deprecated and will be removed in 0.24.

https://github.com/scikit-learn/scikit-learn/blob/0.22.X/sklearn/utils/__init__.py#L292-L294

```python
@deprecated("safe_indexing is deprecated in version "
            "0.22 and will be removed in version 0.24.")
def safe_indexing(X, indices, axis=0):
```

Please see also https://github.com/optuna/optuna/pull/952#issuecomment-596311385.

**Comment by Ahanmr** [comment]
Hi, the necessary changes are already made in `optuna.integration.sklearn.OptunaSearchCV` for handling 0.22 and 0.24 versions of sklearn. Is there something still pending here in this issue?

**Comment by toshihikoyanase** [comment]
@Ahanmr I'm sorry for the delayed response. This issue was resolved by https://github.com/optuna/optuna/pull/1031 as you mentioned.
Thank you!
