### ISSUE TITLE
Order dependencies in `setup.py` alphabetically.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1005]
The libraries in `setup.py` are not arranged in alphabetical order. I think it would be helpful for developers if we fix it.

Examples:

https://github.com/optuna/optuna/blob/master/setup.py#L30-L41
```python
def get_install_requires() -> List[str]:

    return [
        'alembic',
        'cliff',
        'colorlog',
        'numpy',
        'scipy!=1.4.0',
        'sqlalchemy>=1.1.0',
        'tqdm',
        'joblib',
    ]
```

https://github.com/optuna/optuna/blob/master/setup.py#L61-L66
```python
        'doctest': [
            'pandas',
            'cma',
            'scikit-learn>=0.19.0',
            'plotly>=4.0.0',
        ],
```

**Comment by ghost2718** [comment]
Hello, I am newcomer can I fix this issue?

**Comment by c-bata** [comment]
Hi @ghost2718. It seems @VladSkripniuk worked on this issue.
