### ISSUE TITLE
How does the sampler (tpe) handle the different trial states?

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#1015]
Hi,
a trial can have different states:
```
    RUNNING = 0
    COMPLETE = 1
    PRUNED = 2
    FAIL = 3
    WAITING = 4
```

When the sampler (tpe) sees these trials in a database when a new trial starts - how does it handle them? It uses completed trials to get a signal on the fitness landscape to select the next parameter set. But how does it handle FAILed, PRUNED and RUNNING trials? Does it just ignore them?

This question is connected to this item: #913 

Thanks
Philip

**Comment by sile** [comment]
Thank you for your question.
Alghtough the behavior depends on sampler implementation, the default sampler (TPESampler) only considers trials that has COMPLETE or PRUNED state when it samples (suggests) new parameters (other trials are just ignored).

**Comment by sile** [comment]
The following list describes the behavior of other samplers:
- [RandomSampler](https://optuna.readthedocs.io/en/stable/reference/samplers.html#optuna.samplers.RandomSampler) and [GridSampler](https://optuna.readthedocs.io/en/stable/reference/samplers.html#optuna.samplers.GridSampler) ignore all trials
- [CmaEsSampler](https://optuna.readthedocs.io/en/stable/reference/integration.html#optuna.integration.CmaEsSampler) and [SkoptSampler](https://optuna.readthedocs.io/en/stable/reference/integration.html#optuna.integration.SkoptSampler) only consider COMPLETE trials and ignore other ones

**Comment by PhilipMay** [comment]
Ok. Thanks @sile 
How does TPU "see" a pruned trial? I mean when throwing the prune exception you do not provide a metric but only the information that the trial is "bad" with these parameters.

**Comment by sile** [comment]
@PhilipMay 

`TPESampler` ranks trials by using the last reached step as the primary key (higher is better) and the objective value at the step as the secondary key (i.e., pruned trials have worse rankings than complete trials). Then, the sampler uses the ranking information to sample next parameters. If a trial was pruned before reporting any values, it's regarded as a trial that has the worst rank.
The doc comment and implementation code of [optuna/samplers/tpe/sampler.py:_get_observation_pairs](https://github.com/optuna/optuna/blob/2d5f24b06eed56ece72b8dfa878135bb4bb63779/optuna/samplers/tpe/sampler.py#L545) function might help your understanding.

**Comment by PhilipMay** [comment]
@sile Thanks for this explanation. Now I understood.

Should we (I as a PR) put this explanation to the documentation here: https://optuna.readthedocs.io/en/latest/reference/samplers.html#optuna.samplers.TPESampler

What do you think?

**Comment by sile** [comment]
Sounds good!

**Comment by PhilipMay** [comment]
I will do a PR. Would like to keep the issue open until then.

**Comment by sile** [comment]
Some explanations were added to `TPESampler` by https://github.com/optuna/optuna/pull/1214. Do you still plan to write further documentation? > @PhilipMay

**Comment by PhilipMay** [comment]
No. This doc is ok I think.
