### ISSUE TITLE
MLflow integration

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#1017]
I am thinking of an [MLflow](https://mlflow.org) integration. What do you think about this? I would contribute but need someone who discusses with me on where to plug it in.

I saw the MLflow example here: https://github.com/optuna/optuna/tree/master/examples/mlflow

It should be able to automatically log everything that is written to the optuna DB also to MLflow.

What do you think?

**Comment by g-votte** [comment]
@PhilipMay 
I love this idea. It should make Optuna more visualizable especially when the user is familiar with MLFlow.

A possible design might be to provide a callback function/class under `optuna.integration.mlflow` like what is shown in [the example](https://github.com/optuna/optuna/tree/master/examples/mlflow), while I think there're some other ways to integrate the library.

What kind of implementation are you thinking of?

**Comment by PhilipMay** [comment]
I think I will build a callback implementation first.

**Comment by PhilipMay** [comment]
> What kind of implementation are you thinking of?

Well - see the PR here: #1028 Feedback welcome. :-)

**Comment by PhilipMay** [comment]
PR is merged. Closing this.
