### ISSUE TITLE
Pruner example code is missing training data

### ISSUE THREAD

**Issue by barneyhill** [optuna/optuna#1049]
When run, all pruner examples give:
`NameError: name 'X_train' is not defined`
Current documentation with faulty examples: https://optuna.readthedocs.io/en/stable/reference/pruners.html

**Comment by barneyhill** [comment]
Should I make a pull request so that all example code in the documentation includes a sklearn dataset such as that in https://optuna.readthedocs.io/en/latest/reference/integration.html#optuna.integration.OptunaSearchCV? I believe this would make the documentation more accessible

**Comment by toshihikoyanase** [comment]
Hi @barneyhill, thank you for proposal.

Currently, the examples employ a dummy dataset as follows:

```python
            import numpy as np
            from sklearn.model_selection import train_test_split

            np.random.seed(seed=0)
            X = np.random.randn(200).reshape(-1, 1)
            y = np.where(X[:, 0] < 0.5, 0, 1)
            X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)
            classes = np.unique(y)
```

If we show the above code, the example may lose focus. So we hide it into the setup code.
https://optuna.readthedocs.io/en/stable/_modules/optuna/pruners/median.html#MedianPruner

> I believe this would make the documentation more accessible

I agree with you. The self-contained examples will be more helpful for readers if we can keep the code simple. I feel `load_iris` in the [OptunaSearchCV document](https://optuna.readthedocs.io/en/latest/reference/integration.html#optuna.integration.OptunaSearchCV) is a good choice to prepare the dataset in a few lines as follows:

```python
            from sklearn.datasets import load_iris
            from sklearn.model_selection import train_test_split

            X, y = load_iris(return_X_y=True)
            X_train, X_test, y_train, y_test = train_test_split(X, y)
```

> Should I make a pull request

Yes, please. Your contribution is greatly appreciated!

**Comment by barneyhill** [comment]
Thank you @toshihikoyanase for your quick feedback.
I''ll attempt to add the training data to all relavant code examples by the end of today.

**Comment by hvy** [comment]
Discussion is ongoing at https://github.com/optuna/optuna/pull/1051#issuecomment-620337888.

**Comment by hvy** [comment]
Latest PR is ongoing at #1221.
