### ISSUE TITLE
[Proposal] Add Catalyst integration

### ISSUE THREAD

**Issue by VladSkripniuk** [optuna/optuna#1055]
## Motivation
Catalyst is a PyTorch framework for DL research and development. Overview from the projects [github](https://github.com/catalyst-team/catalyst):
> Catalyst helps you write compact but full-featured DL pipelines in a few lines of code. You get a training loop with metrics, early-stopping, model checkpointing and other features without the boilerplate.

It would be nice to add a custom module for Catalyst to allow for easy integration.
## Description
We can implement pruning using Catalysts support for custom callbacks.

**Comment by hvy** [comment]
PR is ongoing at https://github.com/optuna/optuna/pull/1056.

**Comment by VladSkripniuk** [comment]
I close this issue since PR #1056 was merged.
