### ISSUE TITLE
Add `duration` information into FrozenTrial and Dataframe.

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#1058]
## Motivation

We want to add `duration` information into both `FrozenTrial` and `Dataframe`, so that we can easily know how long it took for each trial.

## Description

We want to add `duration` information into [`optuna.structs.FrozenTrial`](https://github.com/optuna/optuna/blob/master/optuna/structs.py#L66) and it should be implemeted as a property method of `FrozenTrial`.

After the above implementation, we want to add `duration` information into `DataFrame`. The `DataFrame` are created from `FrozenTrial` [here](_create_record_and_aggregate_column).

**Comment by c-bata** [comment]
I prefer to implement it as a property method for consistency.

**Comment by ytsmiling** [comment]
Hi, I'll work on this issue.

**Comment by sile** [comment]
@ytsmiling Thanks! Please go for it.
