### ISSUE TITLE
Delete the argument `is_higher_better` from `TensorFlowPruningHook`.

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#1063]
## Motivation

Because the argument [`is_higher_better` is obsolete](https://github.com/optuna/optuna/blob/master/optuna/integration/tensorflow.py#L56-L61) in `TensorFlowPruningHook`, we can delete `is_higher_better`.

## Description

Same as above.

**Comment by himkt** [comment]
@keisuke-umezawa 
I think this issue has been resolved in #1083.

**Comment by hvy** [comment]
Thanks for pointing that out. You're absolutely right, let me close this ticket.
