### ISSUE TITLE
Drop Python 3.5 support

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1067]
Thread to discussion dropping Python 3.5 support.

See also [Drop Python 2 support. #713]( https://github.com/optuna/optuna/issues/713)

**Comment by hvy** [comment]
`scipy` which is an install requirement is dropping support for Python 3.5 in its next minor version upgrade 1.5.0.

**Comment by hvy** [comment]
Memo: `llvmlite` which is required by `numba` which is required by e.g.`dask_ml` in our examples has stopped providing wheels for Python 3.5 starting from 0.32.

**Comment by hvy** [comment]
Note that scipy 1.5.0 is already released, dopping 3.5. https://github.com/scipy/scipy/releases/tag/v1.5.0
PyTorch also dropped support for 3.5 in its recent 1.6 https://github.com/pytorch/pytorch/releases

**Comment by c-bata** [comment]
cmaes will drop Python 3.5 support from next minor release.

**Comment by hvy** [comment]
C.f. https://github.com/optuna/optuna/issues/711#issuecomment-683521987, when rewriting type hints.

**Comment by harupy** [comment]
FYI: https://docs.python.org/3/whatsnew/3.6.html

**Comment by hvy** [comment]
From our CI.
`DEPRECATION: Python 3.5 reached the end of its life on September 13th, 2020. Please upgrade your Python as Python 3.5 is no longer maintained. pip 21.0 will drop support for Python 3.5 in January 2021. pip 21.0 will remove support for this functionality.`

We should probably update the CI matrix and docs accordingly.

**Comment by hvy** [comment]
Python 3.5 dropped from CI in https://github.com/optuna/optuna/pull/1810

**Comment by hvy** [comment]
I think we can get rid of [`type_checking.py`](https://github.com/optuna/optuna/blob/master/optuna/type_checking.py) now.

**Comment by c-bata** [comment]
@hvy I open #2032 to deprecate `optuna.type_checking` module. Can I unpin this issue?

**Comment by hvy** [comment]
Thanks for the PR, I was considering creating it myself. I believe we can unpin it, but it's probably simpler to keep it pinned until we actually close it. It's not like we're having too many pinned tickets. Maybe I'm missing your point.

**Comment by c-bata** [comment]
> I believe we can unpin it, but it's probably simpler to keep it pinned until we actually close it. It's not like we're having too many pinned tickets.

OK, I see 👍
