### ISSUE TITLE
Separate `trial.py` into `trials/xxx_trial.py`.

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#1072]
The line number of `trial.py` becomes large. (1071L)
How about creating a directory `trials` and separating `trial.py` into `trials/base_trial.py`, `trials/trial.py` and `trials/fixed_trial`? (file names are just examples.)

**Comment by hvy** [comment]
I agree that `trial.py` is becoming somewhat bloated. If the bloating is the only reason, my suggestion is to keep the API unchanged (introducing `trials/` will change the API). However, rethinking the API might be of interest as well. I find it a bit strange that only `Trial` is exposed through `optuna.Trial` but e.g. `FrozenTrial` is exposed as `optuna.trial.FrozenTrial`. I'd like to hear what others think.

**Comment by hvy** [comment]
Might be related https://github.com/optuna/optuna/pull/1075.

**Comment by crcrpar** [comment]
Might be reference https://github.com/optuna/optuna/pull/681.
