### ISSUE TITLE
[Proposal] Add integration with allennlp training with jsonnet config files.

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#1078]
# Motivation

I propose a wrapper module for allennlp cli interface.
Many allennlp users train their model with configuration files written in jsonnet.
(example: [sentiment analysis](https://github.com/allenai/allennlp/blob/master/training_config/basic_stanford_sentiment_treebank.jsonnet))
Although I made the example of allennlp [here](https://github.com/optuna/optuna/pull/949),
it would be better that user can their configuration files directly.

# Description

I made [the example](https://github.com/himkt/optuna/tree/93a9bbf0ad7ef508d2782d608bf50d289be049ac/examples/allennlp) of hyperparameter search using allennlp cli.
It's relatively simple and allennlp users can utlize optuna functionalities
with small changes of an original allennlp jsonnet configuration file.

This example has room to improve.
(I'll make a module that wraps calling subprocess and retrieving a metrics.)
However, I think it would be useful for allennlp users because they can use various optuna functionalities.

**Comment by toshihikoyanase** [comment]
@himkt
https://github.com/optuna/optuna/pull/1086 has been merged into master.
Can we close the issue?

**Comment by himkt** [comment]
@toshihikoyanase Thank you for pointing out, yes, we can close this issue now.

**Comment by toshihikoyanase** [comment]
@himkt Thanks! Let me close this issue.
