### ISSUE TITLE
Is it possible to specify a starting point for the values suggested?

### ISSUE THREAD

**Issue by vmgustavo** [optuna/optuna#1080]
Instead of starting from a random point I would like to define a specific set of parameters to start the search. Lets say I have prior knowledge about the problem and I know a set of parameters that would perform well and it should try to improve from there, is it possible to specify this initial set? Or is it always random?

**Comment by hvy** [comment]
Hi @vmgustavo. You can "queue" parameter configurations before starting the optimizations using [`Study.enqueue_trial`](https://optuna.readthedocs.io/en/latest/reference/study.html?#optuna.study.Study.enqueue_trial). Would that work for you? Let me leave a reference to #417 as it sounds like a duplicate.

**Comment by vmgustavo** [comment]
It seems to be enough for me. Thanks, I will try to use it.

**Comment by hvy** [comment]
Let me close this ticket for now as resolved. Feel free to reopen as needed.

**Comment by turbotimon** [comment]
@hvy I had the same question and took my a while to find this answer. I would love to see this in the FAQ, would you agree or do you think it's too specific?

**Comment by hvy** [comment]
Makes sense to me. Thanks for the suggestion.
I just created a PR to start a discussion at https://github.com/optuna/optuna/pull/6157 . Would this have addressed your issue?

**Comment by turbotimon** [comment]
Perfect, thanks!
