### ISSUE TITLE
Race Condition For First Run

### ISSUE THREAD

**Issue by elbaro** [optuna/optuna#1092]
When spawning multiple studies with the same postgres backend,
the script crashes because each process tries to create the db table.

## Expected behavior

db lock, no crash.

## Environment

- Optuna version: 1.2.0
- Python version: 3.8

## Error messages, stack traces, or logs

```
..
sqlalchemy.exc.ProgrammingError: ... relation "alembic_version" already exists
..
sqlalchemy.exc.IntegrityError: ... duplicate key value violates unique constraint "pg_type_typename_nsp_index"
..
```

## Steps to reproduce

```
[delete optuna db tables]
python exp.py exp1 &
python exp.py exp2 &
python exp.py exp3 &
```

## Additional context (optional)
only tried postgres

**Comment by c-bata** [comment]
Hi @elbaro. To avoid this problem, you need to run database migrations before running `exp.py`.

1. Create a database from a command-line interface: `$ optuna create-study --storage ... --study-name ...`.
1. Load a study using [optuna.load_study()](https://optuna.readthedocs.io/en/latest/reference/study.html#optuna.study.load_study) on your python program.

There are no simple solutions to run database migrations on multiple workers. So I think it's better to document this concurrent problem. What do you think?

**Comment by donggu-prestolabs** [comment]
The `exp` above meant a study, not a trial. Each line does its own `optuna.study.create_study`.
Currently I run a small dummy study in advance.
```
python exp.py study=dummy  # db init
python exp.py study=study1 &
python exp.py study=study2 &
..
```
Should I run the migrate cmd for each study? Other than race conditions, `optuna.create_study` just works fine to init the database.

**Comment by elbaro** [comment]
The exp above meant a study, not a trial. Each line does its own optuna.study.create_study.
Currently I run a small dummy study in advance.

python exp.py study=dummy  # db init
python exp.py study=study1 &
python exp.py study=study2 &
..

Should I run the migrate cmd for each study? Other than race conditions, optuna.create_study just works fine to init the database.

**Comment by c-bata** [comment]
I see. I misunderstood.

> Should I run the migrate cmd for each study?

No. It's OK just migrate once. You can migrate your database by using `optuna storage upgrade --storage YOUR_DATABASE` without creating a study. So I think the following steps work as you expected.

```
$ optuna storage upgrade --storage "postgresql://scott:tiger@localhost:5432/mydatabase"
$ python exp.py exp1 &
$ python exp.py exp2 &
$ python exp.py exp3 &
```

**Comment by elbaro** [comment]
Thanks, it solved my problem.

**Comment by jkterry1** [comment]
@c-bata I'm encountering a similar seeming problem, however I don't quite follow the solution you proposed and as best I can tell the documentation for it hasn't been updated either. If you could please explain it in a little more detail I'd be happy to create a PR adding this to the documentation
