### ISSUE TITLE
Propose updating the output of FrozenTrial in first.rst

### ISSUE THREAD

**Issue by A03ki** [optuna/optuna#1096]
In [optuna/docs/source/tutorial/first.rst](https://github.com/optuna/optuna/blob/master/docs/source/tutorial/first.rst), the output of `FrozenTrial` is old.

It doesn't have  `distributions`.

---

According to History of structs.py, optuna added `distributions` after 2019.  
See [Add `distributions` properties to {Trial,FixedTrial,FrozenTrial}.](https://github.com/optuna/optuna/commit/ae2adbe90572b34ff6935672b07cc5e01033a7f6)(April 19, 2019).

In documentation, however, the output's date is May 9, 2018.

**[Optuna’s documentation](https://github.com/optuna/optuna/blob/master/docs/source/tutorial/first.rst#quadratic-function-example)**

```
study = optuna.create_study()
study.optimize(objective, n_trials=100)
```

Out:

```
[I 2018-05-09 10:03:22,469] Finished trial#0 resulted in value: 52.9345515866657. Current best value is 52.9345515866657 with parameters: {'x': -5.275613485244093}.
[I 2018-05-09 10:03:22,474] Finished trial#1 resulted in value: 32.82718929591965. Current best value is 32.82718929591965 with parameters: {'x': -3.7295016620924066}.
[I 2018-05-09 10:03:22,475] Finished trial#2 resulted in value: 46.89428737068025. Current best value is 32.82718929591965 with parameters: {'x': -3.7295016620924066}.
[I 2018-05-09 10:03:22,476] Finished trial#3 resulted in value: 100.99613064563654. Current best value is 32.82718929591965 with parameters: {'x': -3.7295016620924066}.
[I 2018-05-09 10:03:22,477] Finished trial#4 resulted in value: 110.56391159932272. Current best value is 32.82718929591965 with parameters: {'x': -3.7295016620924066}.
[I 2018-05-09 10:03:22,478] Finished trial#5 resulted in value: 42.486606942847395. Current best value is 32.82718929591965 with parameters: {'x': -3.7295016620924066}.
[I 2018-05-09 10:03:22,479] Finished trial#6 resulted in value: 1.130813338091735. Current best value is 1.130813338091735 with parameters: {'x': 3.063397074517198}.
...
[I 2018-05-09 10:03:23,431] Finished trial#99 resulted in value: 8.760381111220335. Current best value is 0.0026232243068543526 with parameters: {'x': 1.9487825780924659}.
```

So, `distributions` still doesn't seem to be reflected.

---

#### The difference between "Optuna’s documentation" and "Optuna1.3.0(My environment)"

**[Optuna’s documentation](https://github.com/optuna/optuna/blob/387fb2119110cd7d74c6f00e3896f168a3459115/docs/source/tutorial/first.rst#study-object)**

To get the best trial:

```python
study.best_trial
```

Out:

```python
FrozenTrial(number=26, state=<TrialState.COMPLETE: 1>, params={'x': 1.9926578647650126}, user_attrs={}, system_attrs={'_number': 26}, value=5.390694980884334e-05, intermediate_values={}, datetime_start=datetime.datetime(2018, 5, 9, 10, 23, 0, 87060), datetime_complete=datetime.datetime(2018, 5, 9, 10, 23, 0, 91010), trial_id=26)
```
`FrozenTrial` does't have `distributions`.

**Optuna 1.3.0(My environment)**

To get the best trial:

```python
study.best_trial
```

Out:

```python
FrozenTrial(number=61, value=5.034984991279155e-05, datetime_start=datetime.datetime(2020, 4, 6, 14, 51, 19, 112226), datetime_complete=datetime.datetime(2020, 4, 6, 14, 51, 19, 185593), params={'x': 2.0070957628140174}, distributions={'x': UniformDistribution(high=10, low=-10)}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=61, state=TrialState.COMPLETE)
```
`FrozenTrial` has `distributions`.

---

Also, optuna changed the order and TrialState instances in `FrozenTrial ` on December 5, 2019.  
Please see below.

> This PR converts TrialState instances to str to make the comparison easy. And also, I moved the state column to the last, so that users easily find both value and state when users print the dataframes.  
[Improving usability of `TrialState` in trials dataframes. #771](https://github.com/optuna/optuna/pull/771)

**Comment by hvy** [comment]
Thanks for pointing this out, `optuna/docs/source/tutorial/first.rst` indeed seems to have been forgotten. Let me label this as `contribution-welcome`. 

Additionally, the log format has been changes as well (https://github.com/optuna/optuna/pull/965) and should probably be updated.
