### ISSUE TITLE
Add a description about document location stored in CircleCI artifact.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1097]
Thanks to #1008, documents of the submitted PRs are automatically built in CircleCI jobs and are stored in the artifact. But, some developers say that they cannot access the artifact tabs.

So, how about documenting the URL to the built document?
For example, a URL of the document in the artifact is as follows;

https://34609-122299416-gh.circle-artifacts.com/0/docs/build/html/index.html

Here, `34609` matched with the CircleCI's job ID. So, I think the document can be accessed with the following URL format and the job ID.

`https://{ciecleci-job-id}-122299416-gh.circle-artifacts.com/0/docs/build/html/index.html`

It would be more helpful if we add a bot that shows the document URLs to the PRs automatically, but it may be overengineering.

**Comment by hvy** [comment]
Sounds good. I think a simple solution would suffice as we're planning to migrate from CircleCI to GitHub Actions.

**Comment by harupy** [comment]
@toshihikoyanase

> It would be more helpful if we add a bot that shows the document URLs to the PRs automatically, but it may be overengineering.

This GitHub Action automatically creates a link to the doc as a commit status.

https://github.com/larsoner/circleci-artifacts-redirector-action

I tried this aciton on my repo:

<img width="817" alt="Screen Shot 2020-05-01 at 14 09 00" src="https://user-images.githubusercontent.com/17039389/80783658-6fd82880-8bb5-11ea-8ae0-31d26628649a.png">

https://github.com/harupy/kernel-profiler/pull/57

**Comment by toshihikoyanase** [comment]
@harupy Thank you for your information. Sounds good!
It seems to be a third-party GitHub Action, and I'm a bit worried about stability.
Have you ever seen any problems with it on your repository?

**Comment by harupy** [comment]
So far, it seems to be working fine.

As reported in https://github.com/larsoner/circleci-artifacts-redirector-action/issues/7, this action does not seem to work when a PR source repo has CircleCI enabled.

**Comment by toshihikoyanase** [comment]
@harupy I'm sorry for the delayed response.

> As reported in larsoner/circleci-artifacts-redirector-action#7, this action does not seem to work when a PR source repo has CircleCI enabled.

Because we recommend turning off the CircleCI in the source (forked) repository, I think the issue does not affect Optuna repository.

It will be a great help to us if you send a PR to introduce this GitHub Action.

**Comment by harupy** [comment]
@toshihikoyanase Thanks for the comment. Yes, I'll submit a PR.

> It seems to be a third-party GitHub Action, and I'm a bit worried about stability.

I'm worried about this too. We could create our own action using https://github.com/actions/github-script. It should look like:

```yaml
# .github/workflows/add-doc-link.yml

name: Add doc link

on: [status]

jobs:
  add-doc-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          ... // write code in JavaScript
```

**Comment by toshihikoyanase** [comment]
@harupy Thank you for your suggestion.

I'm not sure but I guess the maintenance cost of the `github-script`-based action is high because it depends on both GitHub and CircleCI. If either one updates the APIs, we may need to fix the action by ourselves.

Since this action is optional, how about waiting for the update when the action fails?

**Comment by harupy** [comment]
@toshihikoyanase You're right. I'll use https://github.com/larsoner/circleci-artifacts-redirector-action.
