### ISSUE TITLE
Implement partial fixed sampler.

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#1117]
## Motivation

Sometimes, when we try an experiment again, we want to override some parameters by fixed values.

e.g. 

```
study = create_study(sampler=PartialFixedSampler({'lambda_l1': 0.1}, base_sampler=...))
```

## Description

I would like to propose `partial fixed sampler` to override some parameters by fixed values , because it is easy to run experiments with small code changes.

I want to discuss two points here:

1. `partial fixed sampler` is needed or not.
2. If it is needed, what is the api looks like?

**Comment by nzw0301** [comment]
We might implement this feature as a new class of `FixedTrial`. This is because `FixedTrial` has a similar API.

**Comment by nzw0301** [comment]
I think we can already perform this kind of setting by using [`Study.enqueue_trial`](https://optuna.readthedocs.io/en/latest/reference/study.html#optuna.study.Study.enqueue_trial).

For example, 

```python
import optuna
n_trials = 10

def objective(trial):
    x = trial.suggest_uniform('x', 0, 10)
    y = trial.suggest_uniform('y', 0, 10)
    return x ** 2 + y ** 2

study = optuna.create_study()
for _ in range(n_trials):
    study.enqueue_trial({'x': 5})

study.optimize(objective, n_trials=n_trials)

for t in study.trials:
    t.params['x'] == 5
```

**Comment by toshihikoyanase** [comment]
[FYI] Let me share a prototype of the partial fixed sampler:
https://colab.research.google.com/drive/1HagfZ1bAv6rT_TDuzgtInFq6g0BnzjO8?usp=sharing
It was created to answer the [question](https://gitter.im/optuna/optuna?at=5ee9ee940c34bc5cccb0cd76) in Gitter.

I think it follows @keisuke-umezawa's design, but this feature can be implemented using `Study.enqueue_trial` as @nzw0301 mentioned. Please try the notebook to compare usability.

**Comment by toshihikoyanase** [comment]
This is still an open issue. Maybe you can utilize my [prototypical implementation](https://colab.research.google.com/drive/1HagfZ1bAv6rT_TDuzgtInFq6g0BnzjO8?usp=sharing) to create a PR for it.
Your contribution is highly welcomed.

```python
class PartialFixedSampler:
    def __init__(self, fixed_params, base_sampler):
        self._fixed_params = fixed_params
        self._base_sampler = base_sampler

    def reseed_rng(self) -> None:

        self._base_sampler.reseed_rng()

    def infer_relative_search_space(self, study, trial):
        # type: (Study, FrozenTrial) -> Dict[str, BaseDistribution]

        search_space = self._base_sampler.infer_relative_search_space(study, trial)
        # Remove fixed params from relative search space to return fixed values.
        for name in self._fixed_params:
            if name in search_space:
                del search_space[name]
        return search_space

    def sample_independent(self, study, trial, param_name, param_distribution):
        # type: (Study, FrozenTrial, str, BaseDistribution) -> float

        # Fixed params will be sampled here.
        if param_name in self._fixed_params:
            return self._fixed_params[param_name]
    
        return self._base_sampler.sample_independent(study, trial, param_name, param_distribution)

    def sample_relative(self, study, trial, search_space):
        # type: (Study, FrozenTrial, Dict[str, BaseDistribution]) -> Dict[str, float]

        # Fixed params are never sampled here.
        return self._base_sampler.sample_relative(study, trial, search_space)
```

**Comment by norihitoishida** [comment]
Let me tackle this issue!

**Comment by norihitoishida** [comment]
Related PR : Reseed sampler's random seed generator in Study. #968

**Comment by norihitoishida** [comment]
WIP!
https://github.com/norihitoishida/optuna/blob/partial-fixed-sampler/optuna/samplers/_partialfixedsampler.py

**Comment by norihitoishida** [comment]
Hi @keisuke-umezawa 
If there seems to be no ploblem with #1892 , could you please close this issue?

**Comment by norihitoishida** [comment]
@toshihikoyanase 
Could you please close this issue?

**Comment by toshihikoyanase** [comment]
@norihitoishida Thank you for letting me know. I'll close this issue.

@keisuke-umezawa Please feel free to re-open it if you have further comments.
