### ISSUE TITLE
Implement a decorator to Indicate the date for deprecation.

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#1129]
## Motivation

We would like to implement a decorator to Indicate the date for deprecation to show when classes and functions are deprecated to users.

## Description

Implement a decorator to Indicate the date for deprecation, and annotate classes and functions which are deprecated.

**Comment by scouvreur** [comment]
Is anyone working on this - could I take a look at it ?

**Comment by keisuke-umezawa** [comment]
@scouvreur Of course! If you have any ambiguity, please tell about it.

**Comment by HideakiImamura** [comment]
Hello everyone, PR #1382, which introduces deprecation decorator is merged. So let me close this Issue. If there is any discussion, I will open this Issue again.
