### ISSUE TITLE
Add instructions for setting up RDB storage

### ISSUE THREAD

**Issue by smly** [optuna/optuna#1130]
## Motivation

There are few descriptions for RDB storage in the documentation. Adding the information required to set up the RDB will help users who use parallel execution.

## Description

At a minimum, it would be better to specify what permissions are expected of RDB users.

I tried Distributed computation with MySQL by allowing `SELECT`, `UPDATE`, and `INSERT` statements to any table in the database for Optuna. It is necessary to check whether this permission is sufficient. The following is the SQL code when I grant permission.

```sql
GRANT CREATE,INSERT,UPDATE,SELECT ON optuna_db.* TO 'optuna_user'@'localhost';
```

**Comment by sile** [comment]
Maybe related issue: https://github.com/optuna/optuna/issues/517

**Comment by toshihikoyanase** [comment]
This is still an open issue.

I think the instruction can be placed in the [reference of RDBStorage](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.storages.RDBStorage.html). As @smly implied, different RDB servers (e.g., PostgreSQL and MySQL) may require different permissions, so you can create a PR for each.
