### ISSUE TITLE
CI failure: torch==1.4.0+cpu not found

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#1133]
CI failed to install pytorch CPU 1.4.0 in https://github.com/optuna/optuna/pull/1086/commits/f52aebb2f11147e903d0014b7b384e705b631bc1's CI.

## Error messages, stack traces, or logs
[build_36874_step_103_container_0.txt](https://github.com/optuna/optuna/files/4495905/build_36874_step_103_container_0.txt)

CI: https://circleci.com/gh/optuna/optuna/36874?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

It might be due to the version specification introduced by #1118 and/or #1124.

CC: @hvy

**Comment by hvy** [comment]
I believe the failure is mitigated by merging the latests master branch. The latest CircleCI configuration must be used in conjunction with the latest `setup.py`.

**Comment by crcrpar** [comment]
Looks so, sorry for bothering you...
