### ISSUE TITLE
[RFC] Run GitHub Actions only on `optuna/optuna`.

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#1151]
GitHub Actions are running on forked repositories (for example, https://github.com/himkt/optuna/actions).
If an `example` CI fails on a forked repo, a user could receive an alert mail like the following.

```
Run failed for master (d6eb3a8)

Repository: himkt/optuna
Workflow: examples
Duration: 9 minutes and 51.0 seconds
Finished: 2020-04-13 15:12:06 UTC

View results: https://github.com/himkt/optuna/actions/runs/77229227

Jobs:
  * build (3.5) cancelled (2 annotations)
  * build (3.6) failed (1 annotation)
  * build (3.7) cancelled (2 annotations)
  * build (3.8) cancelled (2 annotations)
```

I think it doesn't need to run GitHub Actions `example` and `stale` on forked repositories.
I'm wondering we can stop them using [`jobs.<job_id>.if`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif).

ref. https://github.community/t5/GitHub-Actions/Stop-github-actions-running-on-a-fork/td-p/51499

**Comment by himkt** [comment]
On `himkt/optuna`, I tested behaviors of `if` and confirmed it works well.

### `if: github.repository == 'optuna/optuna'`
https://github.com/himkt/optuna/actions/runs/84853659
https://github.com/himkt/optuna/commit/a702192f1c6a980922633db4e6b5bd0fa39d7543

The job `example` was launched but all builds were skipped.

### `if: github.repository == 'himkt/optuna'`
https://github.com/himkt/optuna/actions/runs/84864873
https://github.com/himkt/optuna/commit/894949b2c3c697b6da9afe79adeeb6ee28b6a767

All of the builds have successfully run.

**Comment by sile** [comment]
> I think it doesn't need to run GitHub Actions `example` and `stale` on forked repositories.

I definitely agree with you.

**Comment by hvy** [comment]
Thanks, that makes sense. For a quick fix, you should also be able to disable the actions in the fork using GitHub's `Settings` --> `Actions` --> `Actions permissions` --> `Disable Actions for this repository`.

**Comment by himkt** [comment]
Thank you for reactions, I'll make a PR later.

@hvy 
Thank you for pointing out, you're right!
Let me note disabling email notification (`Settings` -> `Notifications` -> `GitHub Actions` and remove checks on `Email`) also works for a quick fix. (But this is the account-wide configuration)
(I also think it would be better to avoid making collaborators update their settings manually.)

**Comment by hvy** [comment]
> I'll make a PR later.

Thanks a lot!
