### ISSUE TITLE
Bibtex entry on optuna webpage misses a comma

### ISSUE THREAD

**Issue by towadroid** [optuna/optuna#1153]
The template Bibtex entry on [optuna webpage](https://optuna.org/#paper) misses a comma after the author field.

Wasn't sure were to put this minor "bug", hope this is the right place.

**Comment by toshihikoyanase** [comment]
@towadroid Thank you for pointing it out!
I fixed it. The new page will be deployed in a couple of days (hopefully).

![image](https://user-images.githubusercontent.com/3255979/79978938-b2c23e00-84db-11ea-9793-43a1394ddae7.png)
