### ISSUE TITLE
Show title in figure for contour plot.

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#1176]
I noticed `optuna.visualization.plot_contour` show a plot without its title.

<img width="913" alt="Screen Shot 2020-04-28 at 10 49 53" src="https://user-images.githubusercontent.com/5164000/80437965-01d5fc00-893e-11ea-896a-343b2e51bc90.png">

I think it's better to show a title to be consistent with other plot features such as `optuna.visualization.plot_optimization_history` and `optuna.visualization.plot_slice`.

We can reproduce this behavior in the [official quickstart](https://colab.research.google.com/github/optuna/optuna/blob/master/examples/quickstart.ipynb)

## Expected behavior

Show title of a figure in the contour plot.

## Environment

- Optuna version: 1.3.0
- Python version: 3.6.9
- OS: Ubuntu 18.04.3 LTS

## Steps to reproduce

Run notebook on [Google Colab](https://colab.research.google.com/github/optuna/optuna/blob/master/examples/quickstart.ipynb).

**Comment by harupy** [comment]
Can I work on this?

**Comment by himkt** [comment]
@harupy Sure, thank you for your interest!
