### ISSUE TITLE
Memory increase over trials

### ISSUE THREAD

**Issue by sebastianheinz** [optuna/optuna#1178]
Hi,

I am using Optuna to tune a larger neural network architecture. During optimization the memory consumption of my Python process increases with approx. 1 GB per trial. The process starts at ~2GB and terminates after 15 trials because of OOM (I have a 16GB machine). 

I've tried to replicate this behavior with a smaller model:

```
import optuna
import tensorflow as tf
from sklearn.datasets import make_classification
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split


def objective(trial):
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.InputLayer(input_shape=(100, )))
    model.add(tf.keras.layers.Dense(trial.suggest_int('dense_1', 16, 512), activation='relu'))
    model.add(tf.keras.layers.Dense(trial.suggest_int('dense_2', 16, 512), activation='relu'))
    model.add(tf.keras.layers.Dense(1, activation='sigmoid'))
    model.compile(optimizer=trial.suggest_categorical('optimizer', ['adam', 'sgd']), loss='binary_crossentropy')
    es = tf.keras.callbacks.EarlyStopping(patience=1)
    tb = tf.keras.callbacks.TensorBoard(log_dir='logs')
    ls = tf.keras.callbacks.ReduceLROnPlateau()
    model.fit(x_train, y_train, validation_split=0.2, epochs=10, batch_size=64, callbacks=[es, tb, ls])
    mse_test = model.evaluate(x_test, y_test)
    return mse_test


if __name__ == '__main__':

    x, y = make_classification(n_samples=10000, n_features=100)
    x_train, x_test, y_train, y_test = train_test_split(x, y)
    scaler = MinMaxScaler()
    x_train = scaler.fit_transform(x_train)
    x_test = scaler.transform(x_test)

    study = optuna.create_study(study_name='test', load_if_exists=True)
    study.optimize(objective, n_trials=100, n_jobs=1)
```

Can you share some info why memory usage increases strongly during optimization? Garbage collection is activated by default.

Thank you

**Comment by toshihikoyanase** [comment]
Hi @sebastianheinz ,

How about calling [`tf.keras.backend.clear_session`](https://www.tensorflow.org/api_docs/python/tf/keras/backend/clear_session) at the beginning of the objective function as can be seen in [this example](https://github.com/optuna/optuna/blob/master/examples/pruning/tfkeras_integration.py#L73-L75).

I had a similar problem when I was creating the Keras/tf.keras examples and found that TensorFlow's graph objects were not released automatically.

**Comment by sebastianheinz** [comment]
Perfect, solved the problem! Maybe it would make sense, to put this information somewhere. Thank you!

**Comment by toshihikoyanase** [comment]
> Maybe it would make sense, to put this information somewhere.

That's a good idea!
How about posting is issue to [Stackoverflow](https://stackoverflow.com/questions/tagged/optuna) with `optuna` tag?

In addition, if you change the issue title (e.g., "OOM errors during optimization of tf.keras" or something like that), the users can reach this issue via Google.
