### ISSUE TITLE
Is the pruner minimum?

### ISSUE THREAD

**Issue by yiyinying** [optuna/optuna#1198]
val_loss is minimum
val_acc is maximum

if set direction='maximize':
  pruner is val_loss or val_acc

**Comment by toshihikoyanase** [comment]
Thank you for your question.
The pruner uses the intermediate values reported in the objective function. So, please specify `val_acc` when you set `direction='maximize'`.
I think [this example](https://github.com/optuna/optuna/blob/master/examples/pruning/simple.py#L38-L39) will help you report the `val_acc` as intermediate values.

**Comment by toshihikoyanase** [comment]
Let me close this PR. Please feel free to re-open it or create a new PR if you have questions or comments.
