### ISSUE TITLE
Add support for group in learning to rank in lightgbm

### ISSUE THREAD

**Issue by gauthamzz** [optuna/optuna#1206]
```
import optuna.integration.lightgbm as lgb

params = {
    'objective': 'lambdarank',
    'metric': 'lambdarank',  # alias to ndcg.
    'eval_at': 3,
    'boosting_type': 'gbdt',
    
}

lgb.train(params,X_train, y_train, group=query_train,
        eval_set=[(X_val, y_val)], eval_group=[query_val], 
        eval_at=[3, 5])
```

the above throws an error

```
---> 33     auto_booster = LightGBMTuner(*args, **kwargs)
     34     booster = auto_booster.run()
     35     return booster

TypeError: __init__() got an unexpected keyword argument 'group'
```

grouping allows for keeping queries together.

**Comment by toshihikoyanase** [comment]
Hello @gauthamzz ,

Does `group` exsit in the arguments of the original `lightgbm.train`?
I couldn't find it in the [reference](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.train.html#lightgbm-train
), but [Dataset]( https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.Dataset.html#lightgbm.Dataset) seems to have the `group` argument.
If you can use it, I think we can leave the `LightGBMTuner` as it is.

**Comment by gauthamzz** [comment]
I was using the sklearn interface of lightgbm. Couldn't find any docs regarding it . 

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRanker.html


I tried this out based on this issue https://github.com/optuna/optuna/issues/960

Is there an example I can look into on how optuna works with this interface? 

I can take a look at that meanwhile.

**Comment by toshihikoyanase** [comment]
> I was using the sklearn interface of lightgbm.

I see. `LGBMRanker.fit` has the `group` argument.

https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRanker.html#lightgbm.LGBMRanker.fit

> Is there an example I can look into on how optuna works with this interface?

Currently, Optuna's `LightGBMTuner` supports only the Training API of LightGBM. https://github.com/optuna/optuna/pull/1018 will introduce the scikit-learn compatible interface, but it is under the review.

So, if you want to use scikit-learn API with Optuna, please write your objective function. I think [this example](https://github.com/optuna/optuna/blob/master/examples/lightgbm_simple.py) will help you write the objective function.

**Comment by toshihikoyanase** [comment]
@gauthamzz Let me close this issue. Please feel free to re-open it or create new PRs if you have further problems.
