### ISSUE TITLE
"auto" `{min,max}_resource` heuristic could yield different results on different processes.

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1220]
## Expected behavior

Estimated `min_resource` of the `SuccessiveHalvingPruner` and `max_resource` of `HyperbandPruner` using the `"auto"` argument, on different processes used under distributed optimization is expected to behave identically. As it's currently implemented, although it in practice might be rare (see reproduction steps), could lead to unexpected behaviors. See https://github.com/optuna/optuna/pull/1171#issuecomment-625604963.

## Steps to reproduce

1. Run distributed optimization with multiple processes with either of the two pruners given above using the `"auto"` resource argument. Make sure trials don't always run for the same number of steps (e.g. the number of epochs could be a hyperparameter).
2. Note that the pruners in different processes could end up with different resources, as those are computed based on the number of steps of the completed trial(s).

**Comment by hvy** [comment]
A possible fix might be to simply allow the first process computing the resource to mark the trial through `system_attr` and have following processes check this mark.

**Comment by hvy** [comment]
I noticed this issue isn't restricted to distributed optimization as it could also apply for resumed study optimization.

**Comment by hvy** [comment]
Maybe leaving a note in the documentation is fine for now.

**Comment by sile** [comment]
> I noticed this issue isn't restricted to distributed optimization as it could also apply for resumed study optimization.

Agree.
Besides, it might be applied even if there are no process restarts. For example, let's consider the following scenario (I assumes that there is only one worker and `HyperbandPruner(max_resource="auto")` is specified):
1. The first trial calls `trial.report(value, step=10)`
2. The second trial calls `trial.report(value, step=100)`
3. The following trials also call `trial.report(value, step=100)`

By the current logic, the pruner will determine `max_resource=10` but it seems better to set `max_resource=100` in this scenario. 
I think that the fundamental problem is there is a possibility that each trial in a study may, whether multiple workers execute it or not, report the final intermediate value at the different steps. 
Therefore, IMO, it's better to add a note comment like "if the step of the last intermediate value may change with each trial, please manually specify the maximum possible step to `max_resource`" to the doc.

**Comment by hvy** [comment]
Thanks for you input and example scenario. Yes actually just documenting it might be a reasonable decision, as doing a proper fix isn't trivial.

**Comment by HideakiImamura** [comment]
Thank you for the insightful issue and discussions!

I think that adding documentation for using the `auto` argument is reasonable. I made a PR #1252 to give it.

I think that we should raise a warning when `max_resource = "auto"` and the step of the last intermediate value changes with each trial. What do you think?

**Comment by hvy** [comment]
Thanks for #1252, I took a look and had it merged.

> I think that we should raise a warning when max_resource = "auto" and the step of the last intermediate value changes with each trial. What do you think?

That might be an option. At first, I was a bit concerned since having various number of steps between trials a valid use case. For instance, sampling learning rates is quite common and it's reasonable to vary the number of steps in the same way. However, with HB and "auto" combined it might be a viable option, if we can do it without any significant overhead. With a naive approach, we probably iterate over all trials (similar to `_try_initialization`) in each call to prune, and although it won't add to the time complexity as we're doing the same thing in ASHA, I'm not sure if it's worth just to raise a warning. I haven't done any benchmarks though.

**Comment by hvy** [comment]
Let me close this issue as there's no straight forward fix and it has been stale for a while. Feel free to reopen.
