### ISSUE TITLE
OOM with pytorch after a few trials initialized.

### ISSUE THREAD

**Issue by diff7** [optuna/optuna#1224]
Setting status of trial#28 as TrialState.FAIL because of the following error: RuntimeError('CUDA out of memory. Tried to allocate 88.00 MiB (GPU 0; 10.76 GiB total capacity; 9.77 GiB already allocated; 9.25 MiB free; 9.67 MiB cached)',)

**Comment by diff7** [comment]
Sorry, my bad, need to sleep more.

**Comment by amitness** [comment]
@diff7 I am facing the same issue with PyTorch. Did you find any solution?

**Comment by martinritchie** [comment]
I am also struggling with this issue. Does any one have any tips/advice?

**Comment by veritas9872** [comment]
@diff7 I am also facing the same problem. Could this issue please be reopened? Memory usage is more than 2 times what it should be.

**Comment by jdwillard19** [comment]
I am also dealing with this issue, even when I only specify 2 low-memory jobs it still errors.
