### ISSUE TITLE
[RFC] Stop multi-thread supports.

### ISSUE THREAD

**Issue by ytsmiling** [optuna/optuna#1232]
## Motivation
The current optuna supports multi-thread execution. However, it does not result in any speed gain in general use cases because of python GIL. Rather, the execution time can become longer when we specify n_jobs > 1.
The multi-thread support just complicates storage codes and causes hard-to-catch bugs. For example, I suspect the thread-safety relates to #820
Additionally, it forces storage classes to copy data here and there, which increases overhead even at single-thread execution.

## Proposal
~~I'd like to propose removing the whole multi-thread support and leave the n_job argument for future multi-process support.~~
I'd like to propose removing the whole multi-thread support and instead replace it with multi-process execution. It requires multi-process support by `InMemoryStorage` and some changes in `Study` logics e.g. `study.stop`

**Comment by ytsmiling** [comment]
This PR relates to #1170.

**Comment by c-bata** [comment]
> The current optuna supports multi-thread execution. However, it does not result in any speed gain in general use cases because of python GIL.

I once optimized a hyperparameters of [libffm](https://github.com/ycjuan/libffm) (a library for field-aware factorization machines). libffm does not provide official python binding. So I use Optuna via command line interface. In such a situation, multi-thread optimization is useful.

Although optuna is mainly designed for machine learning, we can use optuna for wide variety of projects as a black-box optimization framework. So I think there are advantages to keep multi-thread support.

**Comment by ytsmiling** [comment]
Thank you for sharing the experience.
Indeed, if you spawn a new process in each trial, the GIL won't be a problem and the multi-thread support can improve the overall execution time.

**Comment by ytsmiling** [comment]
I updated the proposal. Even though the updated proposal is already mentioned in #1170, I think this problem is worth having a dedicated issue to discuss.

**Comment by hvy** [comment]
Just for the record, joblib has been removed and Optuna now only supports multi threading https://github.com/optuna/optuna/pull/2269. I think we can extend this change to include multi processing by simply replacing the executor. However, supporting the in memory storage will remains a TODO.

**Comment by crcrpar** [comment]
https://github.com/optuna/optuna/pull/2428 add some description of n_jobs

**Comment by hvy** [comment]
This is still a reoccurring topic. Let me reopen this issue to avoid having it closed without a proper conclusion.
