### ISSUE TITLE
Enable `objective(study.best_trial)`

### ISSUE THREAD

**Issue by liori** [optuna/optuna#1251]
I find it useful to be able to re-run trials to investigate them further, e.g. with more debugging/data reporting enabled. I thought that it would be natural if I could manually run a trial from a study e.g. by:

    my_objective(my_study.best_trial, more_reporting=True)

but given that the objective function calls various `suggest_*` methods, I get `AttributeError: 'FrozenTrial' object has no attribute 'suggest_int'`. And instead I need to do:

    my_objective(optuna.trial.FixedTrial(my_study.best_trial.params, my_study.best_trial.number), more_reporting=True)

Making `my_objective(my_study.best_trial)` work would be a small, but useful improvement in my workflow.

**Comment by HideakiImamura** [comment]
Thanks for your proposal! I totally agree with your idea.
To realize the feature, we need to add some `suggest_*` methods for `FrozenTrial`. Let me give this issue the contribution-welcome label.

**Comment by HideakiImamura** [comment]
I think there is room for discussion on how to realize this feature.

1. Adding some `suggest_*` methods to `FrozenTrial`.
2. Internally, converting `FrozenTrial` to `FixedTrial`.

In my opinion, the first choice is preferable in terms of simplicity. Also, if we add the `suggest_*` methods to the `FrozenTrial`, I think that `FixedTrial` may be deprecated. I would like to discuss these points.

**Comment by hvy** [comment]
1 might be most simple from the user perspective but I'm wondering if it isn't a bit overkill for something that can be achieved quite easily `objective(optuna.trial.FixedTrial(study.best_trial.params))`. But I agree `objective(study.best_trial)` is ideal 🤔

**Comment by nzw0301** [comment]
I agree with @hvy. Option 1 is simpler but I suppose `FronzenTrial` and `FixedTrial` share many methods by adding `suggest_*` methods to `FronzenTrial`.  I also like the 2nd option, e.g.,`my_objective(best_trial.to_fixed_trial())`.

Let me put some my first impression of this proposal.  In my experience, it sounds a little bit similar to `refit` mode in [`sklearn.model_selection.GridSearchCV`](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html), where the model with the best hyper-parameters fits on the training data after determining the best hyper-parameters by performing CV. But it may not be necessary to solve this issue.

**Comment by nzw0301** [comment]
Could I commit this issue by creating PR? I consider adding `suggest_*` functions to `FrozenTrial` as in @HideakiImamura's option 1.  But it is almost same as `FixedTrial`, so I will add these functions to `FrozenTrial` by extending`BaseTrial` or `FixedTrial`.

**Comment by keisuke-umezawa** [comment]
> so I will add these functions to FrozenTrial by extendingBaseTrial

@nzw0301 Thank you for the comment. Internally, we also want to choose this solution. If you have time, could you try it?

**Comment by nzw0301** [comment]
@keisuke-umezawa Thank you for your reply! But I'm a little bit busy and not good health condition this July, so I create PR for this issue if this issue's priority is not so high... Is it okay?

**Comment by david-waterworth** [comment]
This would also allow simple forward/backward mapping between a trial and the hyperparameters when there is complex logic involved - i.e. #1459

**Comment by HideakiImamura** [comment]
Let me close this issue because this feature has been introduced in #1503.
