### ISSUE TITLE
Adapting lightgbm tuner for k8s usage

### ISSUE THREAD

**Issue by konradsemsch** [optuna/optuna#1258]
What would be required to adapt the following example to run on a k8s cluster: [link](https://github.com/optuna/optuna/blob/master/examples/lightgbm_tuner_simple.py), to perform iterative parameter tuning.

In the most basic example ([link](https://github.com/optuna/optuna/blob/master/examples/lightgbm_simple.py)) I noticed the CLI instructions at the top of the file:

> (2) Execute through CLI.
    $ STUDY_NAME=`optuna create-study --direction maximize --storage sqlite:///example.db`
    $ optuna study optimize lightgbm_simple.py objective --n-trials=100 --study $STUDY_NAME \
      --storage sqlite:///example.db

Would the same also apply for the advanced tuner I mentioned first? I'm also wondering how to best combine it with this k8s example: [link](https://github.com/optuna/optuna/tree/master/examples/distributed/kubernetes). 

Could you please provide some guidance?

**Comment by g-votte** [comment]
Though we haven’t provided such an example or guidance, it’s definitely worth doing. Let me put the `contribution-welcome` tag for this issue.

**Comment by toshihikoyanase** [comment]
This is still an open issue.

If you create an example, you can use the [`scikit-learn example`](https://github.com/optuna/optuna/tree/master/examples/kubernetes/simple) as a template. Please note that [`LightGBMTuner`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.integration.lightgbm.LightGBMTuner.html#optuna.integration.lightgbm.LightGBMTuner) accepts the `study` argument, and you can utilize the RDB as follows:

```python
if __name__ == "__main__":
    study = optuna.create_study(
        direction="minimize",
        study_name="kubernetes",
        storage="postgresql://{}:{}@postgres:5432/{}".format(
            os.environ["POSTGRES_USER"],
            os.environ["POSTGRES_PASSWORD"],
            os.environ["POSTGRES_DB"],
        ),
        load_if_exists=True,
    )

    params = {
        "objective": "binary",
        "metric": "binary_logloss",
        "verbosity": -1,
        "boosting_type": "gbdt",
    }

    model = lgb.train(
        params, dtrain, valid_sets=[dtrain, dval], verbose_eval=100, early_stopping_rounds=100,
        study=study
    )
```

**Comment by HideakiImamura** [comment]
I think this one should be moved into optuna-examples.

**Comment by HideakiImamura** [comment]
Let me close this issue.
