### ISSUE TITLE
`experimental` decorator breaks class documentation.

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1281]
The `experimental` decorator used on classes break documentation. This could be one manifestation but there is an issue with how the documentation including type hints are propagated to the decorated class. This does not apply for free functions.

See https://github.com/optuna/optuna/pull/1265#issuecomment-633195955 for how it may break.

## Expected behavior

Class documentation should not be altered by applying the experimental decorator.

## Steps to reproduce

1. Apply the experimental decorator to a class.
1. Build the document (`cd docs && make html`) 
1. Open the rendered documentation and note that the class signatures is broken.

## Additional context (optional)

- An issue regarding the indentation https://github.com/optuna/optuna/issues/1213.

**Comment by harupy** [comment]
@hvy I think the root cause of this issue is [_make_func_spec_str](https://github.com/optuna/optuna/blob/master/optuna/_experimental.py#L121) which does not seem to handle keyword-only arguments properly.

**Comment by harupy** [comment]
I found `wrapped_init` is not decorated by `functools.wraps`. This changes the signature of `__init__` to `(self, *args, **kwargs) -> None`.

https://github.com/optuna/optuna/blob/e48e4624a486a68484c4824fed243207df000361/optuna/_experimental.py#L104-L106

Decorating `wrapped_init` by  `functools.wraps` should solve this issue.

**Comment by harupy** [comment]
Decorating `wrapped_init` by `functools.wraps` and removing `func_spec_str` should solve this issue.

**Comment by harupy** [comment]
It looks fine.

<img width="709" alt="Screen Shot 2020-05-25 at 20 06 31" src="https://user-images.githubusercontent.com/17039389/82807774-6778c200-9ec3-11ea-8f9c-90409c32800a.png">

**Comment by hvy** [comment]
Thank you for the swift debugging. Looking forward to your PR.
