### ISSUE TITLE
[RFC] Should discrete distributions include `high`?

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1290]
Optuna has the following numerical distributions:

[Continuous]
- `UniformDistribution`
- `LogUniformDistribution`

[Discrete]
- `DiscreteUniformDistribution`
- `IntUniformDistribution`
- `IntLogUniformDistribution`

All of them have the range parameters `low` and `high`, but the inclusion of `high` is different.
The continuous distributions exclude `high`, but the discrete distributions include `high`.

I think Python users are familiar with such difference because the continuous and discrete distributions follow [`random.random`](https://docs.python.org/3/library/random.html#random.random) (`[0,1)`) and [`random.randint`](https://docs.python.org/3/library/random.html#random.randint) (`[low, high]`), respectively.

On the other hand, `numpy`'s random number generators exclude `high` when they sampler integers (see [Generators.integers](https://numpy.org/doc/1.18/reference/random/generated/numpy.random.Generator.integers.html#numpy.random.Generator.integers)). If Optuna also excludes `high` from discrete distributions, the definition may be simpler.

I think it may be difficult for us to change the definition since users have existing code, but we can make it in future versions (v3 or v4?). Please let me know if you have any comments.

**Comment by hvy** [comment]
This is a reoccurring topic, in my understanding. Let me reopen this issue to avoid having it closed without a proper conclusion.
