### ISSUE TITLE
Hyperparameter optimization on multiple machines

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [optuna/optuna#1300]
What is Optuna's standard way of performing simultaneous hyperparameter optimization on multiple machines, with different IPs?

**Comment by hvy** [comment]
Hi @VitorGuizilini-TRI, thanks for reaching out. Are you working under some specific network environments? Otherwise, the standard way is described here (although very briefly) https://optuna.readthedocs.io/en/stable/tutorial/distributed.html. 

What you need is an RDB that can be accessed from your machines. You can share your script containing the code with Optuna that works towards this RDB to your machines, and execute them all at once. Trials will then be scattered to your workers by Optuna.

**Comment by hvy** [comment]
Not sure if this has been solved for you but please let me close this issue. More than welcome to reopen as needed.

**Comment by VitorGuizilini-TRI** [comment]
Hi, I am trying to get back to this project and implement hyperparameter optimization as part of my codebase, and still haven't found a way to include multiple machines (I am using AWS machines). The closest I can do right now is creating a study that shares the optimization between GPUs in the same machine, using a database, but I don't know how to share the database between different machines, so they can read and update it accordingly. 

The link you provided does not work anymore, can you please help me with that? Many thanks!

**Comment by microprediction** [comment]
How about ...
https://pypi.org/project/embarrassingly/

**Comment by hvy** [comment]
Here's the new link to the same tutorial https://optuna.readthedocs.io/en/stable/tutorial/004_distributed.html

Could you perhaps provide details to what you're struggling with? I don't have a lot of experience with running distributed Optuna on AWS but it sounds like an issue with AWS and how you set up a database there that can be accessed from different machines. If you can create a database there, you should with Optuna only have to run the same Python script on multiple processes/machines, specify the correct storage URL when constructing the study in each of them.

```python
# Code executed in each process.
study = optuna.create_study(storage="mysql+pymsql://root@localhost/...", ...)
```

The suggestion provided by @microprediction seems interesting. It seems like a framework for running multi-process optimization. Maybe you could combine that as well but it's for single machine optimization in my understand.

**Comment by microprediction** [comment]
Hi Hiroyuki,
 
  Actually my intent was that one creates a “pre-objective” function with an extra argument. That argument could be used to send computation to server number k.

 Then, one converts it into a function (callable I should say, as it is a class) that doesn’t have the extra argument.

 
  Btw thanks for the excellent library. 
 
Peter

**Comment by VitorGuizilini-TRI** [comment]
Hi @hvy,

Thank you very much. I did some more digging and my issue boils down to exactly that (how to create a database that can be accessed from multiple machines). The way I have set up here there are multiple AWS machines sharing a partition with datasets, models and such, so it should be easy to create a database in said partition. This is how I am creating the study:

```
	name = 'study'
	path_study = '/data/optuna/{}.db'.format(name)

	study = optuna.create_study(
		study_name='optuna',
		storage='sqlite:///{}'.format(path_study),
		load_if_exists=True,
	)
```
However, I am getting this error when creating the study:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: disk I/O error
```

If I instead initialize the database on the same folder as my code this issue disappears and everything works fine (I cannot share that folder between machines though). I don't have much experience with databases, so I am probably missing something obvious. Do you have any suggestions or feedback? Once I have this sorted out the rest should be easy, this library seems very easy to use and will be very useful for my projects!

**Comment by hvy** [comment]
Are use using NFS when working with SQLite? I don't think you're missing anything obvious but I'd recommend you to consider alternatives such as RDS (relational databases such as MySQL or PostgreSQL) over SQLite. There are some notes at the bottom of the tutorial that I linked to above. 

> We do not recommend SQLite for large scale distributed optimizations because it may cause serious performance issues. Please consider to use another database engine like PostgreSQL or MySQL.

> Please avoid putting the SQLite database on NFS when running distributed optimizations. See also: https://www.sqlite.org/faq.html#q5

**Comment by sile** [comment]
Just FYI, but I implemented another Optuna storage named [optjournal](https://github.com/sile/optjournal) that uses file-system features and not depends on SQLite.
I'm not 100% sure but you might be able to use `optjournal` to execute distributed optimization on AWS.
The following is an example code:
```python
from optjournal import FileSystemDatabase
from optjournal import JournalStorage
import optuna


def objective(trial):
    x = trial.suggest_float('x', 0, 1)
    y = trial.suggest_float('y', 0, 1)
    return x * y

name = 'study'
storage = JournalStorage(FileSystemDatabase('/data/optuna/{}.db'.format(name))) 
study = optuna.create_study(study_name='foo', storage=storage, load_if_exists=True)
study.optimize(objective, n_trials=100)
```
Note that `optjournal` is an experimental library, so there could be some bugs.

**Comment by microprediction** [comment]
I will give it a try and let you know. 
Is that pushed?

**Comment by sile** [comment]
Thanks.
As `optjournal` hasn't been published to PyPI yet, you need to install it from the GitHub repository as follows:
```
pip install --user git+https://github.com/sile/optjournal.git
```

**Comment by VitorGuizilini-TRI** [comment]
I tried `optjournal` and I'm getting this error:

```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    study = optuna.create_study(study_name='foo', storage=storage, load_if_exists=True)
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 950, in create_study
    study_id = storage.create_new_study(study_name)
  File "/root/.local/lib/python3.6/site-packages/optjournal/_storage.py", line 46, in create_new_study
    study = self._db.create_study(study_name)
  File "/root/.local/lib/python3.6/site-packages/optjournal/_file_system.py", line 34, in create_study
    with WithFileLock(open(self._index_path(), "r+")) as f:
  File "/root/.local/lib/python3.6/site-packages/optjournal/_file_system.py", line 150, in __enter__
    fcntl.flock(self._file.fileno(), fcntl.LOCK_EX)
OSError: [Errno 38] Function not implemented
```

@hvy Is there any tutorial explaining how to set up MySQL with Optuna? I am having issues here, and I'm not too familiar with datasets to be able to debug them easily.  Thank you very much for you help!

**Comment by hvy** [comment]
```python
    fcntl.flock(self._file.fileno(), fcntl.LOCK_EX)
OSError: [Errno 38] Function not implemented
```

I'm not an expert on this but could be environment specific. Do you know if file locking is enabled in your AWS environment?

> @hvy Is there any tutorial explaining how to set up MySQL with Optuna?

We have some related tutorials. They aren't specific to MySQL but use SQLite. The difference in terms of how you use those databases from Optuna is basically only that you need to change the `storage` URL to yours for MySQL. I'm not sure what additional operations you need in order to set up an RDB/server on AWS though. Maybe this is what you're struggling with.

- https://optuna.readthedocs.io/en/stable/tutorial/004_distributed.html
- https://optuna.readthedocs.io/en/stable/tutorial/003_rdb.html?highlight=mysql

Also, you might want to check this out if you're more comfortable with dask and/or joblib https://github.com/optuna/optuna/issues/1766.

**Comment by sile** [comment]
> I tried `optjournal` and I'm getting this error:

Thank you for your feedback.
The file lock operation seems not supported by the AWS environment.
I'll try to modify `optjournal` to avoid the use of file lock when I have time.

**Comment by sile** [comment]
Hi @VitorGuizilini-TRI ,

I added `avoid_flock` option to `FileSystemDatabase`  (https://github.com/sile/optjournal/pull/2). 
If `avoid_flock=True` is specified (as the following example code), `FileSystemDatabase` uses another locking mechanism that doesn't rely on the flock.
I'm not sure that this option would work in your environment but, if you're interested in, please pull and install the master of `optjournal` and try the option.
```python
from optjournal import FileSystemDatabase
from optjournal import JournalStorage
import optuna

def objective(trial):
    x = trial.suggest_float('x', 0, 1)
    y = trial.suggest_float('y', 0, 1)
    return x * y

name = 'study'
storage = JournalStorage(FileSystemDatabase('/data/optuna/{}.db'.format(name), avoid_flock=True)) 
study = optuna.create_study(study_name='foo', storage=storage, load_if_exists=True)
study.optimize(objective, n_trials=100)
```

**Comment by VitorGuizilini-TRI** [comment]
Thanks @sile, I tried and I'm getting this error now:

```
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    study = optuna.create_study(study_name='foo', storage=storage, load_if_exists=True)
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 950, in create_study
    study_id = storage.create_new_study(study_name)
  File "/root/.local/lib/python3.6/site-packages/optjournal/_storage.py", line 46, in create_new_study
    study = self._db.create_study(study_name)
  File "/root/.local/lib/python3.6/site-packages/optjournal/_file_system.py", line 43, in create_study
    index = json.load(f)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

This is my code:

```
import os
import optuna
from optjournal import FileSystemDatabase
from optjournal import JournalStorage


def objective(trial):
	x = trial.suggest_uniform('x', -10, 10)
	return (x - 2) ** 2


if __name__ == '__main__':

	name = 'study4'
	path_study = '/data/optuna/{}.db'.format(name)

	dir_study = os.path.dirname(path_study)
	os.makedirs(dir_study, exist_ok=True)

	def objective(trial):
		x = trial.suggest_float('x', 0, 1)
		y = trial.suggest_float('y', 0, 1)
		return x * y

	name = 'study'
	storage = JournalStorage(FileSystemDatabase('/data/optuna/{}.db'.format(name), avoid_flock=True))
	study = optuna.create_study(study_name='foo', storage=storage, load_if_exists=True)
	study.optimize(objective, n_trials=100)
```

For context, `/data` is a shared partition between AWS instances (mapped to `/mnt/fsx`), this code works fine if I store the database locally. The goal is to have the database in a shared partition so other instances can work on the same optimization problem.

**Comment by sile** [comment]
> I tried and I'm getting this error now:

Thank you for sharing the error message.
It seems that a file content wrote by a `FileSystemDatabase` instance didn't reflect in the shared file correctly (so a JSON decoding error happened).
I tried adding `fsync` option to `FileSystemDatabase`. if this option is specified (i.e., `FileSystemDatabase(..., avoid_flock=True, fsync=True)`), after every write-operations, `os.fsync`, which forces the file-system to synchronize the file content, is invoked.

> For context, `/data` is a shared partition between AWS instances (mapped to `/mnt/fsx`),

I'm not familiar with FSX, but found [an AWS FSX doc](https://docs.aws.amazon.com/fsx/latest/LustreGuide/mount-fs-auto-mount-onreboot.html) explaining that FSX can enable flock operation by specifying `flock` field when mounting. 
I'm not sure but I guess if you can remount the shared partition with the `flock` option, you might be able to use the flock version of `optjournal` and SQLite.
(However, as @hvy wrote above, if you can set up any RDS, using it is the surest way I think)
