### ISSUE TITLE
Nan-handling in `BaseStorage.get_best_trial`.

### ISSUE THREAD

**Issue by ytsmiling** [optuna/optuna#1310]
In the current implementation, `BaseStorage.get_best_trial` raise `ValueError` when there are no trials completed, while returns arbitrary trial when all trials' values are `nan`. This behavior should be added to `BaseStorage` doc. Alternatively, we might better change the behavior to raise `ValueError` as well.

**Comment by hvy** [comment]
I don't think it's currently an issue since trials with `nan` are automatically failed with `TrialState.FAIL` and are therefore not counted as a completed trial. In other words, `ValueError` is raised consistently.

**Comment by hvy** [comment]
Let me close this ticket for the above reason. `ValueError` might not be the best type describing the state of missing completed trials, but it's somewhat outside the scope of this issue.
