### ISSUE TITLE
Add a Dirichlet distribution

### ISSUE THREAD

**Issue by reidswanson** [optuna/optuna#1311]
A Dirichlet distribution is not included in either Optuna or Hyperopt but would be useful for some applications.

## Motivation

There are cases when you need a set of parameters that sum to one. For example, creating a weighted average of values. In the case of only two values a simple uniform value works, but does not extend to 3 or more. In the past, I've simply generated as many values as I need and renormalized, but this obviously does not work very well.

## Description

A new distribution class that draws a set of values from a Dirichlet distribution.

**Comment by toshihikoyanase** [comment]
Thank you for your feature request.

> There are cases when you need a set of parameters that sum to one. For example, creating a weighted average of values.

Interesting! I think we can utilize the eager (define-by-run) interface of Optuna as an alternative approach. Suppose we have three hyperparameters (`x`, `y`, and `z`). We can use the value of `x` to suggest `y` and the values of `x` and `y` to suggest `z`.

```python
x = suggest_float('x', 0, 1)
y = suggest_float('y', 0, x)
# x + y + z = 1
z = 1 - x - y
```

Regarding the Dirichlet distribution, I can't find straightforward ways to implement it for samplers in Optuna. For example, `TPESampler` handles hyperparameters independently, but it should consider the relationship (or constraints) between hyperparameters (e.g., `x`, `y` and `z` in the above example). Do you have any ideas of optimization algorithms that handle such constraints?

**Comment by reidswanson** [comment]
Ah cool, thanks for the tip! I've been using hyperopt for a while, but just started testing out optuna. This is not possible in hyperopt so it didn't occur to me that it could be an alternative. Definitely works well enough for my purposes.

**Comment by tszumowski** [comment]
@reidswanson given [this clarifying post](https://github.com/optuna/optuna/issues/1311#issuecomment-1599201592), can I suggest this be re-opened?
