### ISSUE TITLE
Optimization starts from scratch after switching sampler from TPE to CMA-ES

### ISSUE THREAD

**Issue by danpolus** [optuna/optuna#1318]
The following code performs 500 optimization trials with TPE sampler and then another 500 optimization trials with CMA-ES sampler. Sometimes the optimization continues from the same point after the sampler switch and sometimes it starts from scratch. 

smp = optuna.samplers.TPESampler()
study = optuna.create_study(sampler=smp)
study.optimize(objective, n_trials=500)
study.sampler = optuna.integration.CmaEsSampler()
study.optimize(objective, n_trials=500)

![Figure_1 TPE CMA combined params 2](https://user-images.githubusercontent.com/28355894/83610866-cce64600-a588-11ea-9fe2-ffa7564bbd9e.png)

## Expected behavior

I expect the optimization process to take in account the optimization achievements so far, after switching the sampler

## Environment

- Optuna version: 1.2.0
- Python version: 3.7
- OS: windows 10

**Comment by toshihikoyanase** [comment]
Thank you for your report.

> Sometimes the optimization continues from the same point after the sampler switch and sometimes it starts from scratch.

Hmm, `optuna.integration.CmaEsSampler` does not keep any states between trials and uses the entire optimization history to suggest the next parameter values (c.f., https://github.com/optuna/optuna/blob/master/optuna/integration/cma.py#L213-L216). I created a notebook to check the behavior of `CmaEsSampler` with a simple quadratic function:
https://colab.research.google.com/drive/1VB5lUYtFKyaqG-Xz9iHYGdUSekbgAMaG#scrollTo=sj5BSMcAitHl

As shown in the following figure, the restarting strategy makes the variance of CMA-ES small. Please compare the trials 50-99 in the first figure with the trials 0-49 in the second figure. If CMA-ES does not use the optimization history of TPE, they should be similar plots.

TPE then CMA (fifty-fifty)
![image](https://user-images.githubusercontent.com/3255979/83621835-2c187a80-a5ca-11ea-913b-9e5ae7582ee3.png)

CMA only
![image](https://user-images.githubusercontent.com/3255979/83621951-510ced80-a5ca-11ea-9ef3-0dd459417ab4.png)

I guess the CMA-ES is not suitable for your objective function. Have you ever tried `optuna.integration.CmaEsSampler` without `TPESampler`?

**Comment by danpolus** [comment]
Thanks for your fast reply!
Indeed, there might be a problem with my error value. Many times it's NaN. I set it to np.inf or to a very large number (10 times bigger than the maximum possible error). So this is what the objective function returns.  Can you propose a better strategy?
Regarding using CMA only, sometimes it explores the entire parameter range and sometimes get "stacked" in a very narrow range. 
In general, my main problem is that I can't get a consistent optimization behaviour. Sometimes it works as expected and sometimes not.

**Comment by HideakiImamura** [comment]
Thanks for raising the Issue! 

In my experience, the CMA-ES algorithm, which is `CmaEsSampler` in Optuna, is vulnerable to the objective function with large variances. This behavior is observed in PR https://github.com/optuna/optuna/pull/1229. Here, the objective values of the pruned trials can be far away from the original values, so the variance is apparently large and the performance of `CmaEsSampler` degrades. Therefore, I do not recommend to use `CmaEsSampler` when the variance of the objective function is large.

In your case, it seems that the variance of the objective function is large because you set a very large value if the objective function produces `NaN`. So, I recommend you to re-try the evaluation of the objective function when the `NaN` is observed. (If the `NaN` is constantly observed for the parameter, then it is good to assign the very large objective value to the parameter. It does not lead to the large variance.)

**Comment by danpolus** [comment]
Interesting, I will try that.
Thanks

**Comment by HideakiImamura** [comment]
Hi @danpolus! Have you tried the above devising? I'm interested in the result. I'm very glad if you share your precious experience!

**Comment by danpolus** [comment]
Hi @HideakiImamura,

Currently I'm using CMA-ES only (without TPE before head) with initial conditions (x0) in the assumed desired range: between points of discontinuity that lead to NaNs. Since I gave up TPE, I'm not scanning the whole parameter range (perhaps missing better solutions), but letting CMA-ES explore around x0. At the objective function I replace NaN with Inf without pruning the trial. The algorithm converges all the time, but not to the same values every run (which I blame on a poor error formula).
Previously, I tried make TPE algorithm to converge, setting the objective function values to Inf / None / Prune / Very Large Number. Using Inf gave the best convergence results (which still failed from time to time due to points of discontinuity).

Given the scenarios above, what new scenarios are you interested in?

**Comment by HideakiImamura** [comment]
Thank you for your reply. Your scenario is very interesting to me. As for your objective function, the discontinuities in the domain seem to be important to the performance of the TPE. The fact that the TPE fails to converge is surprising to me. Can I ask you about the specific objective function and domain space?

**Comment by danpolus** [comment]
Hi @HideakiImamura,
I'm aiming to fit Neural Mass Model power spectrum to EEG power spectrum recorded from patients. The fitting is done by optimizing model's parameters. I use The Virtual Brain (TVB) toolbox for the simulation. TVB returns NaN when Neural Mass Model solution goes to infinity. 
Comparing spectra can be done in many ways, and this is the reason why I'm not sure in my error formula.
I'll be happy to dive into details in a zoom chat. If you are interested, please share your contact info and preferable time slots (I'm at GMT+3).
Best,
Daniel

**Comment by HideakiImamura** [comment]
Thank you for the proposal to share your precious experience! I and other core-development members hope to hear your works. So, could you send a DM on Twitter to me (@mamurai1208)? I would like to set a schedule.

**Comment by danpolus** [comment]
Unfortunately I don't use twitter. Please find my contacts on my website:
http://matlabsolutions.weebly.com/

**Comment by danpolus** [comment]
Hi Hideaki and Hiroyuki,

Here are the results for 3 different scenarios:
1. CMA-ES sampler with "inf" instead of NaN at the loss function
2. CMA-ES sampler with pruning instead of NaN at loss function
3. TPE with 200 independent startup trials
For each of the scenarios I generated a total of 800 trials (200 trials per optimized parameter). 
I didn't use a fixed random seed.

It seems like CMA-ES with "inf" gives the best behavior

1. CMA-ES with "inf" 
![eegsim_toy_1ch_allreg_CMA_fit](https://user-images.githubusercontent.com/28355894/89441539-fc1a5e80-d755-11ea-849e-28d1beff575b.png)

2. CMA-ES sampler with pruning 
![eegsim_toy_1ch_allreg_CMAprun_fit](https://user-images.githubusercontent.com/28355894/89441688-3683fb80-d756-11ea-9e45-82fe8d4cb831.png)

3. TPE with independent trials
![eegsim_toy_1ch_allreg_TPE200_fit](https://user-images.githubusercontent.com/28355894/89441745-4996cb80-d756-11ea-8241-7b2bca2dbfd3.png)

**Comment by faze-geek** [comment]
Hi @toshihikoyanase @HideakiImamura 
I am facing a similar issue in this [discussion](https://github.com/optuna/optuna/discussions/5711), would appreciate it if you could have a look and give your suggestions.
