### ISSUE TITLE
Optuna dashboard page shows up blank on localhost.

### ISSUE THREAD

**Issue by apiszcz** [optuna/optuna#1319]
Optuna 1.5.0, Python 3.7.7

The following command
`optuna dashboard  --storage "postgres://postgres@localhost:5444/optuna" --study-name test
`the http server starts up and the web page opens to a blank page. Refresh the page produces another blank page. Any ideas on where I should look to resolve the issue?

Thank you for a great package and documentation!

```
[W 2020-06-03 06:27:42,079] Optuna dashboard is still highly experimental. Please use with caution!
[I 2020-06-03 06:27:42,087] Starting Bokeh server version 2.0.2 (running on Tornado 6.0.4)
[I 2020-06-03 06:27:42,089] User authentication hooks NOT provided (default user enabled)
[I 2020-06-03 06:27:42,092] Bokeh app running at: http://localhost:5006/dashboard
[I 2020-06-03 06:27:42,093] Starting Bokeh server with process id: 31360
[I 2020-06-03 06:27:43,014] 200 GET /dashboard (::1) 117.69ms
[I 2020-06-03 06:27:43,670] 200 GET /static/js/bokeh.min.js?v=57d29d5936e494351385d736f792154c (::1) 612.41ms
[I 2020-06-03 06:27:43,684] 200 GET /static/js/bokeh-widgets.min.js?v=fdb1f42cceaade9062de57963cac654c (::1) 11.93ms
[I 2020-06-03 06:27:43,697] 200 GET /static/js/bokeh-tables.min.js?v=0a7f930d4b0805283dfba427bb3d0dae (::1) 24.89ms
[I 2020-06-03 06:27:43,702] 200 GET /static/js/bokeh-gl.min.js?v=c376f0736800259be44cb1aed39a6cc3 (::1) 28.89ms
[I 2020-06-03 06:27:43,787] 101 GET /dashboard/ws (::1) 0.00ms
[I 2020-06-03 06:27:43,788] WebSocket connection opened
[I 2020-06-03 06:27:43,790] ServerConnection created
[W 2020-06-03 06:27:43,798] 404 GET /favicon.ico (::1) 1.00ms
[I 2020-06-03 06:28:38,374] 200 GET /dashboard (::1) 3.96ms
[I 2020-06-03 06:28:38,381] WebSocket connection closed: code=1001, reason=None
[I 2020-06-03 06:28:38,510] 101 GET /dashboard/ws (::1) 1.00ms
[I 2020-06-03 06:28:38,510] WebSocket connection opened
[I 2020-06-03 06:28:38,511] ServerConnection created
```
![2020-06-03T093802_465_455](https://user-images.githubusercontent.com/1430861/83643384-f51c7780-a57d-11ea-9b0a-ab6ee0624afc.png)

![2020-06-03T093812_683_381](https://user-images.githubusercontent.com/1430861/83643416-fd74b280-a57d-11ea-981d-d1f7da5e2535.png)

**Comment by toshihikoyanase** [comment]
Sorry for the inconvenience of the dashboard, but it is still in beta and may be unstable.

> [I 2020-06-03 06:27:42,087] Starting Bokeh server version 2.0.2 (running on Tornado 6.0.4)

I think you're using `bokeh==2.0.2`. If so, it is a known issue reported in #1000. The dashboard does not work with `bokeh>=2.0.0`, and I can reproduce the error with `bokeh==2.0.2`. In my environment, the dashboard works with `bokeh==1.4.0`, so please downgrade it.

Although #1000 was closed by #998, it would be helpful to show error messages if users use `bokeh>=2.0.0`. I'll create a PR about it.

**Comment by apiszcz** [comment]
Thank you, the dashboard displays correctly with Bokeh 1.4.0.
I did not see any 'obvious' errors from 2.0.2, and am not sure where to look.
In the interim i have created a few SQL queries to produce results of interest. The database integration is excellent!
Thank you.

**Comment by toshihikoyanase** [comment]
> the dashboard displays correctly with Bokeh 1.4.0.

Great! I'm happy to help you.

> I did not see any 'obvious' errors from 2.0.2, and am not sure where to look.

I created a PR (#1326) to raise `ImportError` if the bokeh version is not supported. 

> In the interim i have created a few SQL queries to produce results of interest.

Just FYI, Optuna can export results as a [pandas DataFrames](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html). Please refer to [Study.trials_dataframe](https://optuna.readthedocs.io/en/stable/reference/study.html#optuna.study.Study.trials_dataframe). I think you can manipulate the result flexibly with it.

**Comment by apiszcz** [comment]
Thank you, using the dataframe option also.

**Comment by toshihikoyanase** [comment]
#1326 has been merged, and let me close this issue.
