### ISSUE TITLE
Dashboard to html option producing a bokeh error.

### ISSUE THREAD

**Issue by apiszcz** [optuna/optuna#1320]
Optuna 1.5.0, Python 3.7.7

`optuna dashboard  --storage "postgres://postgres@localhost:5444/optuna" --study-name test --out optunadashboard.html`

```
[W 2020-06-03 06:30:19,131] Optuna dashboard is still highly experimental. Please use with caution!
usage: bokeh [-h] [-v]
             {build,info,init,json,sampledata,secret,serve,static} ...
bokeh: error: invalid choice: 'html' (choose from 'build', 'info', 'init', 'json', 'sampledata', 'secret', 'serve', 'static')
```

**Comment by toshihikoyanase** [comment]
I confirmed that this error also occurred with `bokeh>=2.0.0`. I think the cause is the same as https://github.com/optuna/optuna/issues/1319#issuecomment-638780661. Please downgrade `bokeh` to `1.4.0`.

**Comment by toshihikoyanase** [comment]
#1326 has been merged, and let me close this issue.
