### ISSUE TITLE
Cannot build the docs with latest `sphinx` 3.1.1.

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1368]
## Expected behavior

Docs should be built properly without warnings/errors. Following warnings are raised by `sphinx`'s latests release `3.1.1`.

## Environment

- `sphinx==3.1.1`

## Error messages, stack traces, or logs

```
WARNING: Failed to update signature for <function MLflowCallback.__init__ at 0x7feea1b4e280>: parameter not found: 'args'
 
WARNING: Failed to update signature for <function GridSampler.__init__ at 0x7feeabb5edc0>: parameter not found: 'args'
 
WARNING: Failed to update signature for <function RedisStorage.__init__ at 0x7feeabb4ce50>: parameter not found: 'args'
 
WARNING: Failed to update signature for <function Study.enqueue_trial at 0x7feeabb4ec10>: parameter not found: 'kwargs'
```

## Steps to reproduce

1. `pip install sphinx -U`
2. `cd docs`
3. `make clean`
4. `make html`

**Comment by crcrpar** [comment]
Could you tell us the status of this issue?
Do we still see this problem? Do you just forget to close?

**Comment by hvy** [comment]
It's still an issue in the sense that we cannot build the docs with `3.1.1`. We could close this issue however if we make sure to support future releases of `sphinx`.
