### ISSUE TITLE
Joblib-spark as a possible alternative for Distributed Optimization

### ISSUE THREAD

**Issue by felipeeeantunes** [optuna/optuna#1381]
Since we are able to use Optuna with `joblib`, it seems possible to generalize the method using [`joblib-spark`](https://github.com/joblib/joblib-spark) to leverage a spark backend similar to HyperOpt SparkTrials(). Of course, the tradeoffs between parallelism and running should be considered here.

**Comment by toshihikoyanase** [comment]
Thank you for your proposal. I didn't know that HyperOpt uses Spark as a parallelization backend. 
I'm not familiar with `joblib-spark`, but I guess the current optuna can be used with it as far as I briefly checked the [example](https://github.com/joblib/joblib-spark) in `joblib-spark` README. 

If it doesn't work, I would appreciate it if you could tell us the missing features needed to support `joblib-spark`.

```python
import optuna
from joblibspark import register_spark

register_spark() # register spark backend

def objective(trial):
    ...
    score = ...
    return score

study = optuna.create_study(storage="some database")

n_jobs = 4
with parallel_backend('spark', n_jobs=n_jobs):
    study.optimize(objective, n_trials=100, n_jobs=n_jobs)
```

**Comment by felipeeeantunes** [comment]
@toshihikoyanase yes, since Optuna uses joblib, the straightforward utilization of joblib-spark works. I think the application to random search will work perfectly, but I'm not sure how it will behave when using TPE sampler since the algorithm is not straightforward parallelizable. In particular, I'm not sure if Asynchronous Successive Halving will behave as expected in the spark workers.

**Comment by toshihikoyanase** [comment]
@felipeeeantunes Thank you for your reply.

> I think the application to random search will work perfectly

I think so too. If you use the RDB backend, the parallel tuning works as expected. Please refer to the [tutorial](https://optuna.readthedocs.io/en/stable/tutorial/rdb.html) to use the RDB.

>  it will behave when using TPE sampler since the algorithm is not straightforward parallelizable.

I agree with your concern. TPE may sample similar points if we run many samplers in parallel. This issue is discussed in #892 and may be resolved Constant Liar method.

> Asynchronous Successive Halving 

We empirically evaluated the parallelization efficiency of the Asynchronous Successive Halving pruner in [this paper](https://arxiv.org/abs/1907.10902). Please see Fig 12, which shows that the pruner scales linearly with the number of workers. We just ran multiple processes independently, but I think you can see the similar performance in the joblib-spark environment.

**Comment by toshihikoyanase** [comment]
@felipeeeantunes This issue was labeled as `stale`, and I'm wondering how to proceed it.
What do you think if we create an example for joblib-spark and provide it in `optuna/examples`?

**Comment by felipeeeantunes** [comment]
@toshihikoyanase started this PR https://github.com/optuna/optuna/pull/1942. 

I have some doubts about it: the current version of `joblibspark` has a bug, fixed in this merge (https://github.com/joblib/joblib-spark/pull/21). I should figure out how to add it to the Dockerfile instead of using `pip`.

Also, I should figure out how to provide a `Dockerfile` and k8s' `YAML` with Spark to reproduce the example in minikube. Can you help with that?

**Comment by toshihikoyanase** [comment]
@felipeeeantunes  Thank you for your great PR!

> I should figure out how to add it to the Dockerfile instead of using `pip`.

How about installing it from the `master` branch of GitHub as follows:

```console
pip install git+https://github.com/joblib/joblib-spark.git
```

I hope `joblib-spark` authors release the new version soon.

>  I should figure out how to provide a Dockerfile and k8s' YAML with Spark to reproduce the example in minikube.

The PR #1942 provides those files in `examples/kubernetes/spark/`, and I think it is reasonable. I'll try the example and send feedback to the PR.

**Comment by HideakiImamura** [comment]
FYI: Optuna does not use `joblib` internally from https://github.com/optuna/optuna/pull/2269, but Optuna can still be used with `joblib` and `joblib-spark` as it is now.

**Comment by Leo-xh** [comment]
> Thank you for your proposal. I didn't know that HyperOpt uses Spark as a parallelization backend.
> I'm not familiar with `joblib-spark`, but I guess the current optuna can be used with it as far as I briefly checked the [example](https://github.com/joblib/joblib-spark) in `joblib-spark` README.
> 
> If it doesn't work, I would appreciate it if you could tell us the missing features needed to support `joblib-spark`.
> 
> ```python
> import optuna
> from joblibspark import register_spark
> 
> register_spark() # register spark backend
> 
> def objective(trial):
>     ...
>     score = ...
>     return score
> 
> study = optuna.create_study(storage="some database")
> 
> n_jobs = 4
> with parallel_backend('spark', n_jobs=n_jobs):
>     study.optimize(objective, n_trials=100, n_jobs=n_jobs)
> ```

I tried the example, but it seems the jobs were running alternatively. I am still wondering how to using joblib-spark within optuna.

**Comment by WaterKnight1998** [comment]
> FYI: Optuna does not use `joblib` internally from #2269, but Optuna can still be used with `joblib` and `joblib-spark` as it is now.

Could you share an example, please? @HideakiImamura

**Comment by PedroMartinez4** [comment]
> > FYI: Optuna does not use `joblib` internally from #2269, but Optuna can still be used with `joblib` and `joblib-spark` as it is now.
> 
> Could you share an example, please? Thanks in advance @HideakiImamura

+1 on sharing an example
