### ISSUE TITLE
Add `last-updated-time` to RDB schema.

### ISSUE THREAD

**Issue by ytsmiling** [optuna/optuna#1383]
This issue proposes to add a `last_updated_time` column to the RDB schema (`trials` table).

## Motivation

The current implementation of optuna RDB storage classes requires to perform O(trial) communication per each `get_all_trials` call. To reduce the communication cost to O(worker) on average (during the optimization process), each storage instance needs to know which trials are created/updated after the last `get_all_trials` call. Even though optuna's trial has `datetime_start` and `datetime_complete`, they are registered on the client-side and cannot be used for synchronization purposes.

## Description

Add `last_updated_time` column (naming may need discussion) to the `trials` table, and add the information to `alembic`. The `last_updated_time` needs to be updated using the server-side timestamp at least when the trial is created. Then, `get_all_trials` only need to fetch (running trials + trials created after the last `get_all_trials` call), which should be O(worker).

## Additional context

* This change requires schema change, and major release will be the right time for this change if optuna accepts this proposal.
* `#get_all_trials call` was reduced to O(1) from O(param) per trial by #1298, and thus the communication cost is not that problem compared to the past.
* The current O(trial) communications can be a problem when optuna support O(1) execution of random-sampler and cma-es sampler in the future, but currently they're not.

**Comment by hvy** [comment]
Please see #1405 and #1426 for why this issue has become stale. Let me label this as `needs-discussion`.

**Comment by hvy** [comment]
This issue has potential and I'd very much like to tackle it, but let me close it for now as it has become stale and I'm not confident I'll be able to tackle it in the near future. Let's reopen it as storage performance becomes relevant again.
