### ISSUE TITLE
Could we show bullet list of classes in ToC?

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#1388]
When I search the details of a class in a page, I would like to see the bullet list for classes to access the target class in the page without scrolling down the page or `Ctr-f`. 

For example, when we open [trial](https://optuna.readthedocs.io/en/latest/reference/trial.html) page, I would like to see the names of classes under the trial page:

```
...
Study
Trial
    [Trial](https://optuna.readthedocs.io/en/stable/reference/trial.html#optuna.trial.Trial)
    FixedTrial
    FrozenTrial
    TrialState
Visualization
...
```

Would you mind considering adding such information to the table of content?

**Comment by hvy** [comment]
Definitely agree. @keisuke-umezawa is currently working on https://github.com/optuna/optuna/pull/1357 ([preview](https://44751-122299416-gh.circle-artifacts.com/0/docs/build/html/reference/study.html)), maybe it addresses this issue?

**Comment by nzw0301** [comment]
@hvy Thank you for your comment! I think so! I'm really looking forward to merging the PR!
