### ISSUE TITLE
Remove description about `optuna study optimize` from examples and docs.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1394]
## Motivation

#1384 deprecated the `optuna study optimize` command, but many examples have descriptions about it at the top of the files. I think we can remove them for consistency.

## Description

Please remove the descriptions about `optuna study optimize` from example files.
- [ ] docs/source/faq.rst ([this section](https://optuna.readthedocs.io/en/latest/faq.html#how-can-i-use-two-gpus-for-evaluating-two-trials-simultaneously))
- [ ] docs/source/tutorial/cli.rst
- [ ] docs/source/tutorial/configurations.rst
- [x] examples/allennlp/allennlp_jsonnet.py
- [x] examples/allennlp/allennlp_simple.py
- [x] examples/catalyst_simple.py
- [x] examples/catboost_simple.py
- [x] examples/chainer_simple.py
- [x] examples/dask_ml_simple.py
- [x] examples/keras_simple.py
- [x] examples/lightgbm_simple.py
- [x] examples/lightgbm_tuner_cv.py
- [x] examples/lightgbm_tuner_simple.py
- [x] examples/mxnet_simple.py
- [x] examples/optuna_search_cv_simple.py
- [x] examples/pytorch_ignite_simple.py
- [x] examples/pytorch_lightning_simple.py
- [x] examples/pytorch_simple.py
- [x] examples/quadratic_simple.py
- [x] examples/skimage_lbp_simple.py
- [x] examples/sklearn_additional_args.py
- [x] examples/sklearn_simple.py
- [x] examples/tensorflow_eager_simple.py
- [x] examples/tensorflow_estimator_simple.py
- [x] examples/xgboost_simple.py

### Example

This is just an example of the fix. Please feel free to change it depending on the examples.

Before:
```python
We have the following two ways to execute this example:

(1) Execute this code directly.
    $ python quadratic_simple.py


(2) Execute through CLI.
    $ STUDY_NAME=`optuna create-study --storage sqlite:///example.db`
    $ optuna study optimize quadratic_simple.py objective --n-trials=100 --study-name $STUDY_NAME \
      --storage sqlite:///example.db

```

After:
```python
You can run this example as follows:
    $ python quadratic_simple.py

```

**Comment by ritvik1512** [comment]
I would like to try to tackle this. Thanks!

**Comment by ritvik1512** [comment]
I would like to confirm, as the command `optuna study optimize` itself is deprecated, should I also remove entire section related to optimzation through `study optimize`?

For example,  docs/source/tutorial/cli.rst has a section on optimization at the very end, does. that need to be removed too? Thank you

**Comment by himkt** [comment]
@ritvik1512

Thank you for your interest on the issue and really sorry for the late reply.
We'd like to work on this issue by the following steps:

1. Remove instructions for `optuna study optimize` in examples ← [now]
2. Remove the documentation for `optuna study optimize`
3. Update tutorial. In our documentation, it doesn't describe the usage of several commands in Optuna CLI commands: `storage update`, `studies`, `create study`, and `dashboard`. We need to create tutorials for them. Let me create another issue for this task.

So, for this issue, we can concentrate on removing descriptions for `optuna study optimize` from examples. Please focus on step #1 if you are still interested in this issue.

Thanks,

**Comment by ritvik1512** [comment]
Thank you for taking the time to list out the steps, I'll start with #1 for now.

**Comment by ritvik1512** [comment]
I have added PR #1566 that should address the removal of ``optuna study optimize`` from examples.

**Comment by toshihikoyanase** [comment]
#1566 removed the `optuna study optimize` from the examples. Thanks, @ritvik1512 !

The documents still contain the description of `optuna study optimize`. Please refer to [this comment](https://github.com/optuna/optuna/issues/1394#issuecomment-662485276) to find the details of the remaining tasks.

-  docs/source/faq.rst ([this section](https://optuna.readthedocs.io/en/latest/faq.html#how-can-i-use-two-gpus-for-evaluating-two-trials-simultaneously))
- docs/source/tutorial/cli.rst
- docs/source/tutorial/configurations.rst

**Comment by nzw0301** [comment]
I briefly re-organise https://github.com/optuna/optuna/issues/1394#issuecomment-668371166 to close this issue.


- [ ] docs/source/faq.rst ([this section](https://optuna.readthedocs.io/en/latest/faq.html#how-can-i-use-two-gpus-for-evaluating-two-trials-simultaneously)), resolved by https://github.com/optuna/optuna/pull/3364.
- [ ] tutorial/20_recipes/004_cli.py
- [x] tutorial/10_key_features/002_configurations.py: there is not `optuna study optimize` anymore

`tutorial/20_recipes/004_cli.py`'s main content is about this deprecated example, so I'm not sure how to change this tutorial...

**Comment by himkt** [comment]
[memo] In https://github.com/optuna/optuna/issues/3032, CLI tutorial is planned to be updated removing deprecated functionalities.
