### ISSUE TITLE
Occasional test failure with `ChainerMNStudy` with Python 3.5.

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1395]
## Expected behavior

Tests should pass.

## Error messages, stack traces, or logs

https://app.circleci.com/pipelines/github/optuna/optuna/1171/workflows/41e626df-8501-46ca-a724-9b1c27079253/jobs/45897

## Additional context (optional)

Seems to be specific to Python 3.5 and only happen randomly.

**Comment by himkt** [comment]
I also encountered the failure in Python 3.7.

https://app.circleci.com/pipelines/github/optuna/optuna/1195/workflows/eccc4813-e4b0-443f-acba-90992ac0b738/jobs/46106/steps

**Comment by hvy** [comment]
Also in Python 3.8. Python version seems to be irrelevant. https://app.circleci.com/pipelines/github/optuna/optuna/1202/workflows/77a93dea-69d5-48d1-a911-fcad5878609e/jobs/46167/steps

**Comment by harupy** [comment]
We can reproduce the error with:

```
docker run -v $(pwd):/workspaces -e OMP_NUM_THREADS=1 optuna/optuna:py3.7-dev mpirun -n 2 --allow-run-as-root -- pytest tests/integration_tests/test_chainermn.py -k test_failure -vv --showlocals
```

**Comment by hvy** [comment]
We should preferable deal with this as soon as possible and I tried several times but couldn't reproduce it locally. Did you encounter it frequently? 

Note: Some discussions offline that https://github.com/optuna/optuna/pull/1380 could be related but I'm not sure.

**Comment by harupy** [comment]
@hvy Can you fix `test_chainermn.py` as below and run the command again?

```diff
class TestChainerMNStudy(object):
    ...
    @staticmethod
+   @pytest.mark.parametrize("x", range(10))  # run this test 10 times
    @pytest.mark.parametrize("storage_mode", STORAGE_MODES)
-   def test_failure(storage_mode, comm):
+   def test_failure(storage_mode, x, comm):
        # type: (str, CommunicatorBase) -> None
        with MultiNodeStorageSupplier(storage_mode, comm) as storage:
```

**Comment by toshihikoyanase** [comment]
@harupy Thank you for sharing the command. I can reproduce the failure without the hack in https://github.com/optuna/optuna/issues/1395#issuecomment-647304646.

The actual error seems to be the last trial (Trial 20), which is still recognized as `RUNNING`.

```console
 FrozenTrial(number=20, value=None, datetime_start=datetime.datetime(2020, 6, 22, 11, 40, 58, 415896), datetime_complete=None, params={}, distributions={}, user_attrs={}, system_attrs={}, intermediate_values={}, trial_id=21, state=TrialState.RUNNING)]
```
