### ISSUE TITLE
enable visualization of best  trials (and not all trials)

### ISSUE THREAD

**Issue by kradant** [optuna/optuna#1402]
Please add a possibility to visualize only the best trials (or even enable some more advanced filtering) in the optuna.visualization functions. Currently I can only visualize the whole study. Then you have a few hundred trials in this study, the visualization is useless as I can't see the details. 

## Motivation

Enable better visualization out of the box for studies with a lot of trials. 

## Alternatives (optional)

Enable to create a new study object from an old study object with the possibility to give a list / numbering of the trials I want to include. This is maybe even the better way to go as it seems more general / modular. With the new study object,  I could visualize the relevant data without the need to change the API of the visualization funcitons. 

## Additional context (optional)

A detail of a contour plot with too much trials. It is not possible to interpret the data accurately. 

![newplot](https://user-images.githubusercontent.com/20926365/85226435-b8eb7280-b3d7-11ea-98e3-c6a15a97d377.png)

**Comment by HideakiImamura** [comment]
Thanks for the important suggestion! I agree with your idea to improve Optuna's visualization functions. I left the relevant recent PR (ongoing) for your alternative idea: https://github.com/optuna/optuna/pull/1335

**Comment by HideakiImamura** [comment]
Hi @kradant! In the current master branch, PR #1335 is merged. I hope you'll give it a try if you like.

**Comment by HideakiImamura** [comment]
The feature which we want to introduce in this feature is realized by the `optuna.study.Study.add_trial(trial)`, which is introduced in PR #1335. For example, we can plot top 10 trials of the optimized `study` in the contour plot as follows.

```python
N_ALL_TRIALS = 100
N_PLOTTED_TRIALS = 10
def objective(trial):
    ...

study = optuna.create_study()
study.optimize(objective, n_trials=N_ALL_TRIALS)

trials = study.trials
plotted_trials = sorted(trials, key=lambda t: t.value)[:N_PLOTTED_TRIALS]
plotted_study = optuna.create_study()
for trial in plotted_trials:
    plotted_study.add_trial(trial)

optuna.visualization.plot_contour(plotted_study)
```

Let me close this issue. If you have any comments or questions, please feel free to reopen this issue.

**Comment by elisa-aleman** [comment]
I want to add that on the plot_intermediate_values, when choosing the best trials, the trial number is lost during this transfer
