### ISSUE TITLE
Use a different color for argument names to differentiate them from type hints

### ISSUE THREAD

**Issue by harupy** [optuna/optuna#1429]
## Motivation

Currently, argument names and type hints in the documentation have the same font color, which makes it difficult to differentiate them, especially when a function or class has lots of arguments.

Current:

![Screen Shot 2020-06-25 at 14 02 44](https://user-images.githubusercontent.com/17039389/85657434-ff4d1400-b6ec-11ea-82cf-160283d8d300.png)

Using a different font color for argument names can solve this issue.

Proposed:

![Screen Shot 2020-06-25 at 14 03 05](https://user-images.githubusercontent.com/17039389/85657334-ddec2800-b6ec-11ea-84ea-a0b8b211d28a.png)

I think changing a font-style or font-weight should work too.

## Description

The `span` tags that hold argument names can be selected by `.sig-param > span:nth-child(1)` so adding the css below does the trick. 

```css
.sig-param > span:nth-child(1) {
  color: <color>;
}
```

**Comment by harupy** [comment]
I'll open a PR.

**Comment by hvy** [comment]
That'd be great!

**Comment by hvy** [comment]
@harupy should we close this issue now that https://github.com/optuna/optuna/pull/1436 is merged?

**Comment by harupy** [comment]
Looks like I used a wrong closing-issue keyword in #1436.
