### ISSUE TITLE
Optimize preprocessing pipeline

### ISSUE THREAD

**Issue by matheusbarroso** [optuna/optuna#1441]
Hi everyone, I've been using optuna without any problems for intance with xgboost. Nevertheless, I developed a simple sklearn pipeline where I would like to optimize some preprocessing transformers bud didn't succeed. I've tried ussing trial.suggest_categorical with some integer options but the pipeline crashes unexpectedly. It seems odd considering that when I set inside the optimization function new hard codes values it works fine. Is there a workaround this issue? Other thing that I wonder is there a way to use the choices of trial.suggest_categorical to sample transformers? I did get another error when attempting it.

Here is some  code snippet:

xgbrt_cox = xgb.XGBRegressor(
         objective='survival:cox',
         booster='gbtree',
         eval_metric='cox-nloglik',
        base_score=1,  
        reg_lambda=0,
        n_estimators=1000,
        max_depth = 2,
        nthread=4,
        random_state=123
)

def objective(trial):
    
     cardinality_n_cat = trial.suggest_categorical('card__n_categories', [4, 5, 7, 10])
 // #     trial.set_user_attr('card_n', cardinality_n_cat)
    
    
    params_pipeline = {
        'high_card__select_high_card__n_categories': 10,#trial.user_attrs['card_n'],
        'low_card__select_low_card__n_categories': 10,#trial.user_attrs['card_n']
         'high_card__collapse_features__frequency' : trial.suggest_uniform('cat_collapse', 0.8, 1.0),
        'numeric_cols__imputer_num': ['passthrough',
                                      CustomImputer(datatype='numeric', strategy='mean')][
            trial.suggest_categorical('impnum', [0,1])]
            
    }
    
    pipe.set_params(**params_pipeline)

    params_boost = {
        # some basic cfg par:
        'booster': 'gbtree',
        'objective': 'count:poisson',
        'base_score': 0.1,
        'nthread': 16,
        # model par:
        'n_estimators':1000,
        'max_depth': trial.suggest_int('max_depth', 1, 50),
        'lambda': trial.suggest_loguniform('lambda', 1e-8, 1.0),
        'alpha': trial.suggest_loguniform('alpha', 1e-8, 1.0),
        'subsample': trial.suggest_uniform('subsample', 0.5, 1.0), #[0.5, 1]            
        'max_depth': trial.suggest_int('max_depth', 1, 9),
        'eta': trial.suggest_loguniform('eta', 1e-8, 1.0),
        'gamma': trial.suggest_loguniform('gamma', 1e-8, 1.0),
        'grow_policy': trial.suggest_categorical('grow_policy', ['depthwise', 'lossguide'])
        
    }
    
    xgbrt = xgb.XGBRegressor(**params_boost)
    
    X_train = pipe.fit_transform(df_train)
    X_test = pipe.transform(df_test)
    
    xgbrt_cox.fit(X_train,
              y_train,
              eval_set=[(X_test,
                         y_test)],
              early_stopping_rounds=10)
    
    c_index = concordance_index(df_test.loc[:,'duration_adj'], 
                  -xgbrt_cox.predict(X_test,  ntree_limit=0),
                  y_test)
    return c_index

# Create a study object and optimize the objective function.
study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100, n_jobs=1, timeout=60*2)

**Comment by HideakiImamura** [comment]
Thanks for the question! Sorry for the late response. First, I would like to clarify your question.

> I've tried using trial.suggest_categorical with some integer options but the pipeline crashes unexpectedly.

Hmm, Optuna supports to suggest integer values by `suggest_categorical`. Is there any error message on it?

> Other thing that I wonder is there a way to use the choices of trial.suggest_categorical to sample transformers?

I'm not sure what the "transformer" is here. Could you explain it in more detail?

**Comment by matheusbarroso** [comment]
Hi Hideaki, my point is if there is a way to choose transformers (sklearn), think of it as optimizing a pipeline and not necessarily a model. If it was an issue of categorical encoding it could be to choose between one hot encoding or hash encoding for instance.

**Comment by HideakiImamura** [comment]
Thanks for the reply. I'm not sure what "transformer" means here, but Optuna supports conditional suggesting as follows.
```python
def objective(trial):
    which_transformer = trial.suggest_categorical("transformer", ["TransformerA", "TransformerB])
    if which_transformer == "TransformerA":
        # process transformer A
        ...
    elif which_transformer == "TransformerB":
        # process transformer B
        ...
```
Optuna users do not have to encode "categorical" variables into one-hot encoding or hash encoding. We can just pass the list or tuple of categorical variables to the `suggest` method.

**Comment by matheusbarroso** [comment]
Yes thanks, I suppose I can refactor the code in this fashion. Regards

Sent from my iPhone

On 6 Aug 2020, at 20:43, Hideaki Imamura <notifications@github.com> wrote:

﻿

Thanks for the reply. I'm not sure what "transformer" means here, but Optuna supports conditional suggesting as follows.

def objective(trial):
    which_transformer = trial.suggest_categorical("transformer", ["TransformerA", "TransformerB"])
    if which_transformer == "TransformerA":
        # process transformer A
        ...
    elif which_transformer == "TransformerB":
        # process transformer B
        ...

Optuna users do not have to encode "categorical" variables into one-hot encoding or hash encoding. We can just pass the list or tuple of categorical variables to the suggest method.
