### ISSUE TITLE
Assigning the layers as class variables (PyTorch requirement)?

### ISSUE THREAD

**Issue by arisliang** [optuna/optuna#1443]
In pytorch_lightning_simple example (https://github.com/optuna/optuna/blob/master/examples/pytorch_lightning_simple.py), it says 
>Assigning the layers as class variables (PyTorch requirement).

Is it possible to add more clarification to it, or perhaps point to a link where pytorch has this requirement?

**Comment by david-waterworth** [comment]
My understanding is for a PyTorch module when you call `parameters()` you get back a list of all parameters for all layers only if those layers are class variables. So if you assign a layer in the constructor and don't assign it to a local variable you won't be able to train the parameters of that layer.

**Comment by HideakiImamura** [comment]
Thanks for raising an Issue @arisliang and fast reply @david-waterworth. Sorry for the late response. The explanation given by @david-waterworth seems reasonable to me. I think we need to make the comments in the source code more descriptive. 

Let me create an Issue to fix comments in `pytorch_lightning_simple.py` based on your comments.

**Comment by arisliang** [comment]
Thanks all for the clarification and action. Closing this now.
