### ISSUE TITLE
Use `com2ann` to translate type comments into type annotations

### ISSUE THREAD

**Issue by harupy** [optuna/optuna#1445]
Related to https://github.com/optuna/optuna/issues/711.

I found this python package named `com2ann` which translates type comments into type annotations:

https://github.com/ilevkivskyi/com2ann

I'm testing this package on my local and it seems to be working fine so far. One adjustment that I had to make was prevent `com2ann` from translating type comments on variables into  [variable annotaions](https://www.python.org/dev/peps/pep-0526/) (introduced in Python 3.6) because Optuna still supports Pyhton 3.5. Here's the fixed version which preserves type comments on variables.

https://github.com/harupy/com2ann/tree/disable-variable-annotation

Can I give this a try?

**Comment by hvy** [comment]
Sounds amazing. I know @bigbird555 has been working on translating the type annotations so he might have a comment or two, but if we can automate it, I definitely think we should.

**Comment by bigbird555** [comment]
If translation of type annotation can be automated programmatically, that seems great!

**Comment by harupy** [comment]
@hvy @bigbird555 Awesome!

**Comment by harupy** [comment]
@hvy I have a branch where I've applied `com2ann` to all the files. Can I create a PR using this branch?

**Comment by hvy** [comment]
Given @bigbird555's comment, I believe you are more than welcome 🙂

**Comment by harupy** [comment]
I added a comment on #711 that explains how to use and install `com2ann` so I'll close this issue.
