### ISSUE TITLE
AllenNLP integration: Can't load configurations that expect ext_vars from environment variables

### ISSUE THREAD

**Issue by nickswalker** [optuna/optuna#1446]
Optuna's AllenNLP integration evaluates the jsonnet config that you give it, passing in the trial parameters as the `ext_vars`. AllenNLP's default behavior when loading a configuration is a little different, in that it also passes through environment variables: 

https://github.com/allenai/allennlp/blob/4de68a42a0df89df01a999ee48f361f24c8c19d4/allennlp/common/params.py#L488

So if you rely on specifying e.g. a path to a file as an environment variable, that configuration won't load as expected when using the integration

## Expected behavior

Optuna should pass environment variables through when the jsonnet is interpreted. Ideally, it'd just use the AllenNLP config loading code directly so that all behavior is identical, just overriding whatever the trial needs to override.

## Environment

- Optuna version: 1.5.0
- Python version: 3.6
- OS: Ubuntu 18.04.4
- (Optional) Other libraries and their versions: AllenNLP 1.0

## Error messages, stack traces, or logs

You'll get `RuntimeError: undefined external variable` during the interpretation of the jsonnet here:

https://github.com/optuna/optuna/blob/9f5c5cf5c36df1628567f0b4a9873892d148ad40/optuna/integration/allennlp.py#L108

## Steps to reproduce

1. Use a AllenNLP configuration that expects to be able to use an environment variable to fill an extVar

**Comment by himkt** [comment]
@nickswalker 

Thank you for trying our AllenNLP integration and raising the issue!
As you pointed out, in the current implementation, `AllenNLPExecutor` doesn't care for environment variables.
I made PR #1449 to fix this problem (loading environment variables is compatible with AllenNLP implementation. After loading environment variables, adding hyperparameters from Optuna to them).

**Comment by himkt** [comment]
@nickswalker 
Thank you for creating the issue, I fixed this bug in #1449.
Environment variables can be used from the next release of Optuna.
