### ISSUE TITLE
Optuna prunes too aggressively, when objective is jittery (early stopping patience needed)

### ISSUE THREAD

**Issue by turian** [optuna/optuna#1447]
Optuna Pruners should have a parameter `early_stopping_patience` (or `checks_patience`), which defaults to 1. If the objective hasn't improved over the last `early_stopping_patience` checks, then (early stopping) pruning occurs.

## Motivation

My objective function is jittery. So Optuna is very aggressive and prunes trials when the objective increases slightly due to jitter.

This means Optuna is **worse** than hand tuning, because it prefers only optimization paths that are not jittery and monotonically decrease, which aren't always the ones that converge to the lowest optimum. In some problem settings, it is unusable.

## Description

What would be better is an optional parameter that says how many checks must occur without improvement, in order for early stopping pruning to happen.

Optuna Pruners should have a parameter `early_stopping_patience` (or `checks_patience`), which defaults to 1. If the objective hasn't improved over the last `early_stopping_patience` checks, then (early stopping) pruning occurs.

More specifically, the objective at a particular check for the purposes of pruning, reporting, etc. should be the min (or max) objective observed over the last `early_stopping_patience` checks.

## Alternatives (optional)

I have tried `interval_steps=10` but it doesn't help. Because if the tenth step is the one that has jitter, it gets pruned.

## Additional context (optional)

Pytorch early stopping has a `patience` parameter that is similar to the one I propose.

**Comment by hvy** [comment]
Out of curiosity, what pruner(s) did you try? There are several and some are more aggressive than others. It might matter less in the case of jittery learning curves, though. The pruning timing logic is already quite complicated for many of the pruners so I'd personally like to be careful about introducing additional parameters to existing ones, but I also understand the need so would like to elaborate on details first.

As a workaround, you could simulate `patience` by conditionally calling `Trial.report` on your behalf. I also think that you could run several steps without reporting, average the result, then report the averaged value. Note that the `step` argument to `Trial.report` is just a metric/order used by the pruner, could be fictional and doesn't have to reflect actual iterations, epochs, etc.

**Comment by turian** [comment]
I have just started with Optuna and am trying to beat my hand-tuned baseline hyperparameters, which I cannot yet :(

I have only tried MedianPruner, and tried adjusting the settings to:

```
optuna.pruners.MedianPruner(n_warmup_steps=5, interval_steps=10)
```

What other pruners do you recommend, particularly less aggressive one? For a simple pruner like MedianPruner, the idea of using early stopping patience really makes sense to me. If I were just using Pytorch Lightning and were  to do early stopping with patience=1, that would be a really bad it.

I don't exactly understand the workaround. I am not using Trial.report. I use the `PyTorchLightningPruningCallback`. Should I modify my validation loss and just keep a moving average of it rather than the true validation loss? I guess it works but it's ugly, I'd prefer to try different Optuna pruners first.

```
        early_stop_callback=PyTorchLightningPruningCallback(trial, monitor="val_loss"),
```

**Comment by david-waterworth** [comment]
I've observed the same problem using pytorch-lightning with the default lightning `early_stop_callback`. My solution was to use the `min_epochs` parameter of the 'pl.Trainer' to ensure pruning doesn't occur until epoch 100 (for my problem). Basically the validation score would oscillate for a while before settling into the more conventional slow decline and as you've observed invokes early stopping too early. I found this to work better than `patience` (I didn't use the optuna MedianPruner as the current version isn't compatible with the latest lightning release although that's been fixed). I'm not sure how to replicate this using optuna itself.

**Comment by hvy** [comment]
Thanks for the insight. The author have seemingly utilized [`n_warmup_steps` of the `MedianPruner`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.pruners.MedianPruner.html) which seemingly has a similar meaning to `min_epochs` but if the learning curve has a similar tendency, then increasing it might help. Otherwise, I'd at least try the [`HyperbandPruner`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.pruners.HyperbandPruner.html). It's not know for handling jittery learning curves but it'll run trials with varying pruning intervals.

**Comment by hvy** [comment]
As for `early_stopping_patience`, if your learning curve increase/decrease with a relatively high variance between each step (iteration/epoch), would a `early_stopping_patience` really help? I was imagining `early_stopping_patience` to hold some sort of internal counter that's reset every time an improvement is observed with the patience number of steps. This is reset rather often in this case and cause pruning to happen. Please correct me if I'm wrong.

**Comment by david-waterworth** [comment]
I agree, in my case the curve was relatively smooth but "wave" like, i.e. slowly damped oscillations. The OP's issue sounds more like high frequency noise which I guess is a slightly different issue. In signal processing you might pass it through a low pass filter to remove the noise.

**Comment by HideakiImamura** [comment]
Thanks for raising an interesting issue! IMO, @turian's suggestion which is to introduce `early_stopping_patience` to pruners looks reasonable. I think it is good to implement the feature as another pruner, which can have existing pruner as follows.
```python
class PatientPruner(BasePruner):
    def __init__(self, early_stopping_patience, wrapped_pruner):
        self.early_stopping_patience = early_stopping_patience
        self.wrapped_pruner = wrapped_pruner
    
    def prune(self, study, trial):
        seen_values = trial.iintermediate_values.values()[-self.early_stopping_patience:]
        if the value in seen_values has not improved at all:
            self.wrapped_pruner.prune(study, trial)
        else:
            return False

wrapped_pruner = MedianPruner()
pruner = PatientPruner(early_stopping_patience=5, wrapped_pruner=wrapped_pruner)
study = optuna.create_study(pruner=pruner)
...
```

BTW, the `HyperbandPruner` can control the intensity of pruning, as long as we know. So, how about using the `HyperbandPruner` instead of the `MedianPruner`?

**Comment by turian** [comment]
@david-waterworth My curve is like yours, it is 'relatively smooth but "wave" like, i.e. slowly damped oscillations.'

@hvy However, the slowly damped oscillations continue through the entire training, even after 100 epochs.

In pytorch lightning, `min_epochs` is the wrong solution and `early_stopping_patience` is what allows it to actually find the optimum. Since the oscillations continue the whole time.

Similarly, in Optuna, `n_warmup_steps` is not really the right solution. It's more a patience parameter if there are these slowly damped oscillations, which you need to ride-out through the entire training regime.

**Comment by turian** [comment]
@HideakiImamura I am still not sure if `HyperbandPruner` is the right solution. It's a bit orthogonal.

If we use @david-waterworth's nice explanation that for some training problems, the curve is 'relatively smooth but "wave" like, i.e. slowly damped oscillations', the key feature is that there is some parameter that finds the optimum over the previous `k` checks, not just the current check which could be unlucky and at the top of the bump/wave.

**Comment by turian** [comment]
Here is my validation loss graph

![image](https://user-images.githubusercontent.com/65918/86272919-a93a0e00-bbcf-11ea-821a-a2b5790e3ae0.png)

Note that there are about 10 iterations per epoch, i.e. divide the x-axis value by 10 to get the epoch.

**Comment by turian** [comment]
Here is another training curving I have, that is more like what @david-waterworth describes

![image](https://user-images.githubusercontent.com/65918/86296900-3abe7580-bbfa-11ea-960f-e098585ae43b.png)

**Comment by hvy** [comment]
Sorry for the late reply. Implemented a pruner for Optuna which should behave similarly to the `EarlyStopping` callback in PyTorch Lightning with the "patience" that you mentioned earlier. I made it available in the following Google Colab notebook if you could try it out.

https://colab.research.google.com/drive/1uPUlBqpCWv5oFLkDAMSOJ1LRWOGD_c-i?usp=sharing

If this doesn't address your problem, then we might want to continue considering integrating this logic into other pruners as mentioned above by @HideakiImamura . However, this could be a first minimal/simple approach.

Just a note about the `MedianPruner`. You generally want to have a somewhat large number `n_startup_trials`. The pruning behavior is largely dependent on how the first few (`n_startup_trials`) turns out. If for instance the first trial happened to very good in the first few steps, and say you have `n_startup_trials=1`, then most of the following trials will be pruned at the first pruning check.

**Comment by hvy** [comment]
@turian, just curious if you have any updates on the pruner as the stale bot has run multiple rounds. I understand you're busy, though. Let me know if you have any comments on how we should proceed with this issue.

**Comment by hal-314** [comment]
Hi
I would want to remark that training curves for neuronal networks are typically jittery as posted by @turian .  For example, the training curve for EfficientNetLite-1 in ImageNet dataset is this:

![Screenshot 2020-10-02 at 13 40 41](https://user-images.githubusercontent.com/22135069/94919661-1f8f2a80-04b5-11eb-9b2e-b86221c70d62.png)

Here, a zoom:

![Screenshot 2020-10-02 at 13 40 46](https://user-images.githubusercontent.com/22135069/94919688-2a49bf80-04b5-11eb-96ad-78818923ae1f.png)

ImageNet is one of the most famous dataset to validate a new neuronal network.

As it has been said before, `EarlyStopping` callback in PyTorch Lightning with the "patience" to overcome this. So, @HideakiImamura pruner wrapper would be perfect. I prefer @HideakiImamura approach over @hvy as it could wrap any Optuna wrapper, is extremely simple and it doesn't existing pruners don't need to be changed. I think that @hvy wrapper is roughly equivalent to `wrapped_pruner = PatientPruner(patience=5, MedianPruner())` . It could be added as experimental feature to evaluate users feedback.

Another option is that pruners don't use directly `trial.intermediate_values` to recover trial intermediate values. Instead, they use a pruner method like `self.get_intermediate_values(trial)` that can be overridden. So, through mixins, user can define their custom smoothing values functions to avoid loss jittery without changing the pruner itself or their training code. For example, a user could return a running average of the trial intermediate values. So MedianPruner, HyperBandPruner, etc uses them. A rough code of concept:

```
class BasePruner(object, InstantIntermediateValuesMixin, metaclass=abc.ABCMeta): # Current optuna base class but with a default mixin
     ....

class PrunerIntermediateValuesMixin(ABC):
      @abstractmethod
      def get_intermediate_values(self, trial):
           pass # Here is where user can change the code

class InstantIntermediateValuesMixin(PrunerIntermediateValuesMixin):
      def get_intermediate_values(self, trial):
           return trial.intermediate_values

class AverageIntermediateValuesMixin(PrunerIntermediateValuesMixin):
       def get_intermediate_values(self, trial):
            # Here goes the running average for intermediate values
            pass

class AveragingMedianPruner(MedianPruner, AverageIntermediateValuesMixin): pass


```

I think that this option gives more freedom to users. You can easily make an exponential average, clipping values without changing the reported value, etc.  

Finally, both options can be used simultaneously. 

What do you think?

**Comment by turian** [comment]
@hal-314 thank you for your insight. @hvy I am still interested in this sort functionality (patience parameter).

**Comment by turian** [comment]
@hvy just to understand, is your suggestion to follow the colab and see if it works?

I nonetheless like the idea from  @HideakiImamura that this be natively supported in pruners, some sort of patience function. Your idea of adding smoothing is good too; just bear in mind that tuning a smoother can sometimes be more trickier than picking a patience epoch. This is because, depending upon your ML hyperparameters, you sometimes have much more rocky curves, and thus the smoothing strength really depends upon your choice of ML hyperparameters...

**Comment by turian** [comment]
@hvy I apologize for the delay. I am still quite interested in this feature.

I have reviewed your colab and I am not sure it is correct. Let me paste it here and add my comments:

```
class PatientPruner(optuna.pruners.BasePruner):
    def __init__(self, patience=3):
        self._patience = patience

    def prune(self, study, trial):
        intermediate_values = trial.intermediate_values

        steps = np.asarray(list(intermediate_values.keys()))

        # Do not prune if number of step to determine are insufficient.
        # jpt: looks good so far
        if steps.size < self._patience + 1:
            return False

        # Prune based on if the values are monotically decreasing/increasing.
        # jpt: keep only the last patience + 1 steps
        steps.sort()
        patience_steps = steps[-self._patience - 1 :]

        patience_values = np.asarray(list(intermediate_values[step] for step in patience_steps))

        # jpt: here we see if the diff between each step, the error appears to be that
        # jpt: that we don't care about step to step differences, but the overall patience
        diffs = np.diff(patience_values)

        direction = study.direction
        if direction == StudyDirection.MINIMIZE:
            promising_diffs = diffs <= 0
        elif direction == StudyDirection.MAXIMIZE:
            promising_diffs = diffs >= 0
        else:
            assert False

        return not promising_diffs.any()
```


Here is an example of value minimization with patience 3, where the above code would not work:
```
{0: 0.5, 1: 0.8, 2: 0.7, 3: 0.6}
```

So at step 3, we have score 0.6 and have not improved over step 0 with score 0.5.

However, your code appears to see that the score drops from step 1 to 2, and step 2 to 3, thus finding a promising diff and saying it's okay to continue.

Here is the lightning code https://pytorch-lightning.readthedocs.io/en/stable/_modules/pytorch_lightning/callbacks/early_stopping.html#EarlyStopping in method _run_early_stopping_check.

I think you want something more like this:

```
class PatientPruner(optuna.pruners.BasePruner):
    def __init__(self, patience=3, min_delta=0.00):
        self._patience = patience
        if patience <= 0:
            raise ValueError

    def prune(self, study, trial):
        intermediate_values = trial.intermediate_values

        steps = np.asarray(list(intermediate_values.keys()))

        # Do not prune if number of step to determine are insufficient.
        if steps.size < self._patience + 1:
            return False

        # Look at the last patience steps before this one
        steps.sort()
        patience_steps = steps[-self._patience - 1 : -1]
        intermediate_values[step]

        # jpt: here we see if the diff between each step, the error appears to be that
        # jpt: that we don't care about step to step differences, but the overall patience
        diffs = np.diff(patience_values)

        direction = study.direction
        if direction == StudyDirection.MINIMIZE:
            promising_diffs = diffs <= 0
        elif direction == StudyDirection.MAXIMIZE:
            promising_diffs = diffs >= 0
        else:
            assert False

        return not promising_diffs.any()
```

**Comment by turian** [comment]
https://colab.research.google.com/drive/1_5DJb5mdLIkQFqVvzNw-gWOr52USapA-?usp=sharing

**Comment by turian** [comment]
I have also added a min_delta parameter, like pytorch lightning. So you must improve by at least min_delta at one point in the last patience steps, versus all previous steps

**Comment by turian** [comment]
Here are some unit tests that pass in my code but didn't work in your version:

```
pp = PatientPruner(patience=3, min_delta=0.1)
trial = trials[-1]
# The last three trials are worse than the first one
trial.intermediate_values = {0: 0.5, 1: 0.8, 2: 0.7, 3: 0.6}
assert pp.prune(study, trial) == True

# The last three trials are the same as the first one, but haven't improved by
# min_delta 0.1
trial.intermediate_values = {0: 0.5, 1: 0.5, 2: 0.5, 3: 0.5}
assert pp.prune(study, trial) == True

# One of the last three trials improves by 0.1!!!
trial.intermediate_values = {0: 0.5, 1: 0.4, 2: 0.5, 3: 0.5}
assert pp.prune(study, trial) == False

# This is also fine, because in the last three steps we have found
# an optimum that is <= min_delta the optimum before the patience
# parameter
trial.intermediate_values = {0: 0.5, 1: 0.6, 2: 0.6, 3: 0.4, 4: 0.5}
assert pp.prune(study, trial) == False
```

You can see in my plot (see colab I pasted) that stopping occurs after three epochs that don't improve by min_delta:

![image](https://user-images.githubusercontent.com/65918/109406417-272a0100-7979-11eb-8ab9-4bdea439e4cb.png)

**Comment by turian** [comment]
One further thing I would like to comment about my implementation: It only implements patient pruning within the current trial.

I think more desirable behavior would be that it does patient pruning with respect to all trials. That is, it has patience steps to achieve min_delta better score versus the best score of ALL trials observed beforehand (at patience steps ago).

For example the blue curve in the graph above (the one at the top) stops once it hasn't improved by min_delta in patience steps *only compared to other points on the blue curve*. I think the best implementation, which I haven't implemented, is that it prunes earlier when it sees that it is not better than the purple curve (bottom curve in the plot above).

**Comment by turian** [comment]
@hvy let me know what you think about the above?

**Comment by turian** [comment]
@hvy let me know your thoughts, I might be able to give feedback or code

**Comment by hvy** [comment]
Thanks @turian for the interest and I'm very sorry for coming back late. I briefly discussed this with some other members. Is it the case that you have a working pruner at hand? I tried to open the URL provided but didn't have permission to open it. In any case, I think we can discuss introducing a wrapping pruner as suggested by @HideakiImamura to account for these learning curves as I think it's a quite common issue (e.g. neural nets as mentioned here). It'd be even greater if you could send a PR and am curious to find out if this is of any interest.

**Comment by turian** [comment]
@hvy I am still very interested in this feature and I think many other people are too :)

https://colab.research.google.com/drive/1_5DJb5mdLIkQFqVvzNw-gWOr52USapA-?usp=sharing

Please check the colab now?

But as I note, I don't think this PatientPruner by @HideakiImamura is the behavior you want. See the graphs at the end.

What this PatientPruner does is prune *within* a particular trial.

Whereas, instead, you want to prune against ALL the other trials, just with some patience if there is a little jitter.

I can't submit a PR right now, unfortunately, I have two papers in preparation :(

**Comment by nzw0301** [comment]
Hi @turian, I implemented a similar early-stopping before using Optuna, so I'm interested in this functionality for Optuna!  I might not fully understand all discussion in this thread, but let me leave my comments.

I'm a bit worried about the behaviour of `PatientPruner`. According to the Colab, all status of trials is `PRUNED`, not `COMPLETE `. In this case, a number of samplers do ignore such a `PRUNED` trial as mentioned in https://github.com/optuna/optuna/issues/1647 and we cannot get `best_trials` if all trial status is not `COMPLETE `.

Suppose a neural network training such that we minimise a validation loss. The validation loss curve might look like a noisy U-shape, so all trials are pruned by `PatientPruner`.

To avoid that, I returned the lowest validation loss among intermediate values rather than `raise optuna.TrialPruned` before:

```python
        if trial.should_prune():
            return min(trial.intermediate_values)
            # raise optuna.TrialPruned
```

But i'm not sure this is a good way for optuna's hyper-parameter search; poor trials will be also used in future hyperparameter search.

**Comment by turian** [comment]
@nzw0301 Thanks for the advice. I have tried @HideakiImamura 's idea with the wrapped pruner, and your idea.

However, now I see that now trials ever get pruned. Any idea why?

This extends @hvy 's original colab:

https://colab.research.google.com/drive/14CRJKXAPUCr9jtUM_RbMio-N759F2hqV?usp=sharing

**Comment by nzw0301** [comment]
@turian  Sure!  I think we need two modifications to perform pruning by a wrapped pruner.  

First, in `PatientPruner`, we need to return the pruning flag by `wrapped_pruner`:

```python
          if maybe_prune:
              # KN: we need to return the wrapped pruner's prune value to perform pruning
              return self.wrapped_pruner.prune(study, trial)
```

Second, we need to call `raise optuna.TrialPruned` if `trial.should_prune() == True`:

```python
        if trial.should_prune():
            print("Pruning trial")
            # KN: to raise pruning we need to use `raise optuna.TrialPruned`
            raise optuna.TrialPruned
```

Full codes are in [this colab notebook](https://colab.research.google.com/drive/1d-AWMfpnUEbSmJxJoxg12QKdKSas_fB7?usp=sharing). I also add my idea to return the lowest objective value in the steps rather than the final `y`.

**Comment by turian** [comment]
@nzw0301 This is looking much more like I would expect! Looks very nice

**Comment by turian** [comment]
What would it take to get this approach merged? Who would need to approve the proposal?

**Comment by nzw0301** [comment]
@turian Thank you for your quick check! We (@HideakiImamura, @hvy, and I) are on board with introducing this pruner as an experimental feature to Optuna!

**Comment by nzw0301** [comment]
@turian `PatiencePruner` is available on the master branch :)

**Comment by Umanskyt** [comment]
setting log_every_n_steps=1 in my pytorch_lightning Trainer solved this issue for me!
