### ISSUE TITLE
Initial Trial

### ISSUE THREAD

**Issue by david-waterworth** [optuna/optuna#1448]
Is it possible to specify `x0` - i.e. the first trial suggestion - for any sampler similar to hyperopt? The `CmaEsSampler` has an `x0` parameter but the `TPESampler` doesn't. It's useful because I'm training a lot of models using the same model specification but different training data. There is a default set of hyperparameters that seems to perform well so I'd like to try that first and then search for a fixed time to see if I can improve the initial guess.

**Comment by hvy** [comment]
Would it happen to be a duplicate of https://github.com/optuna/optuna/issues/1080 ?

**Comment by david-waterworth** [comment]
Thanks yes.
