### ISSUE TITLE
Study parallel jobs should use multiprocessing

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#1480]
When you do parallel execution in `study.optimize` (when `n_jobs=-1` for example). You say `with Parallel(n_jobs=n_jobs, prefer="threads") as parallel:`. See here:

https://github.com/optuna/optuna/blob/61c6a0acb22338789a83a02bb147326159f41d1e/optuna/study.py#L317

IMO this just opens (threading) which suffers from the Python Global Interpreter Lock. See here: https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html

This would not lead to real parallel execution and is useless with CPU bound problems. I suggest to use this: `with Parallel(n_jobs=n_jobs, backend="multiprocessing") as parallel:`

If you want to I can provide a PR.

**Comment by sile** [comment]
FYI: This issue seems relating to #1232 .
Your proposal sounds good but the most difficult point to enable this is we need to implement "multi-process support by InMemoryStorage " (quoted from #1232) I think.

**Comment by profPlum** [comment]
@sile 
Why don't you just keep the memory in main process then `map()` the parameter 'suggestions' to the worker processes for evaluation? I'm sure that for most people the evaluation process is extremely expensive, so IPC overhead will be trivial compared to evaluation cost (these are hyper-parameters after all, implication is long training/evaluation process for each trial).

Am I missing something? This seems like an obvious and easy solution to me.
IMO the current solution of using an SQL database is really complicated and error prone.

**Comment by sile** [comment]
@profPlum Your suggestion sounds somewhat interesting. However, this is an issue closed about a year ago and I'm not an active maintainer of Optuna now. So how about creating a new issue to discuss this topic with other Optuna developers and users instead?

**Comment by sile** [comment]
FYI. Optuna contributors are currently developing the v3 version, and there are storage/multi-process related topics (e.g., [Consider storage that can be easily used with multi-process](https://github.com/optuna/optuna/wiki/Optuna-V3-Roadmap#name-consider-storage-that-can-be-easily-used-with-multi-process-2950)). Thus, your feedback or opinion will be welcomed I think.

**Comment by profPlum** [comment]
@sile I see thanks
