### ISSUE TITLE
Request for shell script or Makefile for kubernetes examples

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#1493]
Currently, this repository has an example which demonstrates how to use Optuna on Kubernetes. In addition to this, I'm working on an example of how to use Optuna with MLflow on Kubernetes. Both of them have a handful of steps including Dockerfile build that might be a bit overwhelming for us to follow those steps one by one.

__UPDATE (2020-07-31)__: Now that we have kubernetes example with and without mlflow in https://github.com/optuna/optuna/tree/master/examples/kubernetes. Both of them have a handful of steps to run. So what I think helpful is `run.sh` or `start.sh` which does everything to run these examples.

**Comment by VamshiTeja** [comment]
Hello, I would like to tackle this.
