### ISSUE TITLE
How to modify the LightGBMTunerCV? E.g. change the number of n_trials?

### ISSUE THREAD

**Issue by konradsemsch** [optuna/optuna#1494]
Hello, 

I'm trying to adapt the following example: [link](https://github.com/optuna/optuna/blob/master/examples/lightgbm_tuner_cv.py), especially trying to reduce the number of trials or e.g. perhaps modify the pruner at some later stage. The reason to modify the number of trials is that right now I've implemented this optimization as part of a bigger ML package and I would like to test if it's working and not execute long-running optimization.

However, from the documentation it seems that the tuner doesn't accept `n_trials` as an input parameter. I've also tried wrapping it into a function and calling a study similar to this approach:

```python
if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
```

but it doesn't seem to work. Could you please advise how to modify that?

**Comment by toshihikoyanase** [comment]
@konradsemsch Thank you for your question.
Currently, `lightGBMTunerCV` does not receive `n_trials` from users as you mentioned. 

>  I would like to test if it's working and not execute long-running optimization.

For this purpose, I think you can use [`time_budget`](https://optuna.readthedocs.io/en/stable/reference/integration.html#optuna.integration.lightgbm_tuner.LightGBMTunerCV) to restrict the execution time. You can set a time limitation for parameter tuning in seconds with it.

The following is just an example of `time_budget`:

```python
    # Set the timeout to 5 seconds.
    tuner = lgb.LightGBMTunerCV(
        params, dtrain, verbose_eval=100, early_stopping_rounds=100, folds=KFold(n_splits=3), time_budget=5,
    )
```

**Comment by konradsemsch** [comment]
Thanks for a prompt response! I somehow missed that.

**Comment by balazsgonczy** [comment]
Is there a solution for this now? Can we somehow create an objective function with LightGBMTunerCV?
