### ISSUE TITLE
Retry insertion after deadlock when using RDB backend.

### ISSUE THREAD

**Issue by ytsmiling** [optuna/optuna#1496]
## Background
Some DBs can cause deadlock even when you try to insert a single row (see e.g., [MySQL InnoDB](https://dev.mysql.com/doc/refman/5.7/en/innodb-deadlocks-handling.html)). The documentation notes as follows.
```
Always be prepared to re-issue a transaction if it fails due to deadlock.
```
It seems that `sqlalchemy` does not automatically retry, and we need to handle the dead-lock like [these lines](https://github.com/optuna/optuna/pull/1490/files#diff-9aa9e205e3a2038ae9077f72d10abac1R467).

## Request
Add retry-codes for every code block which performs insertion. In the current `optuna` codebase, it will be safe to always retry them.

**Comment by hvy** [comment]
Might be a good idea to address this after https://github.com/optuna/optuna/pull/1628.
