### ISSUE TITLE
default importance evaluator

### ISSUE THREAD

**Issue by louisabraham** [optuna/optuna#1523]
get_param_importances uses fanova by default but the docs say it uses MRI.

(It might be interesting to say why one would not use the default)

**Comment by hvy** [comment]
Thanks for the report. Addressed it in #1524.

To be honest, it's not necessary clear when to use one over the other. MDI is simpler and also faster. It has its drawbacks however and is known for favoring high cardinality/continuous hyperparameters for instance. Unless speed is a concern (this can also be tweaked/traded-off against accuracy using the forest configuration parameters of the evaluators), you should likely stick to the default fANOVA. It's more robust with continuous and discrete hyperparameters and takes into account the search space that's given by the `Trial.suggest_*` method (MDI does not).
