### ISSUE TITLE
`allennlp_jsonnet.py` is failing on GitHub Actions.

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1526]
## Expected behavior

Daily example runs on GitHub Actions, in particular the `allennlp_jsonnet.py`, should not be be failing.

## Environment

- GitHub Actions

## Error messages, stack traces, or logs

https://github.com/optuna/optuna/runs/875801206?check_suite_focus=true

## Steps to reproduce

1. Wait for the daily example GitHub Action, in particular `allennlp_jsonnet.py` to run.
2. Notice the job failure.

## Additional context (optional)

It's currently failing due to OOM, given `##[error]Process completed with exit code 137.`. It's possible to reduce the memory usage by e.g. reducing the batch size. However, then it'll start to fail with exit code 120. To be precise, there seem to be two issues.

**Comment by himkt** [comment]
[memo]

I conducted some trials and found:

- Putting `sys.exit(0)`: CI still fails
  - https://docs.python.org/3/library/sys.html?highlight=sys%20exit#sys.exit
- Putting `os._exit(0)`: CI passes
  - https://docs.python.org/3/library/os.html?highlight=os%20_exit#os._exit

https://github.com/himkt/optuna/pull/2

In the documentation for `os._exit`:

> Exit the process with status n, without calling cleanup handlers, flushing stdio buffers, etc.

**Comment by himkt** [comment]
Let me close this issue, as `allennlp_jsonnet.py` is tested in the example CI now.
(https://github.com/optuna/optuna/pull/1915)
