### ISSUE TITLE
Matplotlib backend for visualization functions

### ISSUE THREAD

**Issue by g-votte** [optuna/optuna#1539]
This issue proposes to implement the [Matplotlib](https://matplotlib.org/) backend for the visualization functions.

## Motivation

While the current visualization backend, [Plotly](https://plotly.com/python/), provides rich and interactive interfaces, the setup is sometimes hard especially when exporting figures as static ones. Specifically, the installation steps of [Orca](https://github.com/plotly/orca) are complicated in some environments (see https://github.com/plotly/orca/issues/150 for example) or may restrict the way of package management as `plotly-orca` favors Conda installation.

Providing another backend such as Matpotlib may mitigate this problem, where the library does not require extra setup to output static figures and is pre-installed in some popular platforms such as [Anaconda](https://www.anaconda.com/).

## Alternatives

Plotly has supported [Kaleido backend](https://github.com/plotly/plotly.py#kaleido) for static export since Plotly 4.9. Thus, we could guide users to install this backend, although it restricts the Plotly version where Optuna supports `>= 4.0.0` currently.

**Comment by ytknzw** [comment]
@toshihikoyanase Thank you for your feedback! My idea above is a rough draft, so I appreciate your detailed thoughts. I agree with both points you mentioned. I'll work on it today and put a PR, then let's discuss further.

**Comment by hvy** [comment]
I'm wondering if we shouldn't start discussing the public part first (or sooner), including how to handle visualization functions that are missing implementations for some specific backends. Logic introduced is otherwise quite difficult to document and test.

**Comment by BenjaminBossan** [comment]
If I may make a proposal regarding the public API of the matplotlib plotting functions:

It would be really nice if as a user, I were allowed to pass the `ax` to the plotting function. This allows me to have a greater control about the final plot. E.g., right now I cannot change the plot size or make the plot part of a larger figure with several subplots. Here is an example how I could use this feature:

```python
...
import matplotlib.pyplot as plt
fig, axes = plt.subplots(1, 2, figsize=(20, 10))

# plot results on a big figure with 2 subplots
optuna.visualization.matplotlib.plot_edf(study, ax=axes[0])
optuna.visualization.matplotlib.plot_optimization_history(study, ax=axes[1])
```

The default argument for `ax` could be None, in which case the functions do exactly the same thing as they do right now. Inside the different functions, you just need to change the code to:

```python

def _get_edf_plot(studies: List[Study], ax: Optional[AxesSubplot] = None) -> "Axes":
    ...
    ax = ax or plt.subplots()[1]
```

I would also suggest not to set `plt.style.use("ggplot")` -- why not leave that up to the user?

**Comment by nzw0301** [comment]
Are there some to-do tasks for this issue?

**Comment by Crissman** [comment]
Matplotlib functionality has been added, so I'm closing this issue. If there a further tasks to be done please open a new issue.

@BenjaminBossan If you'd like to further discuss the public API, please open a separate issue.

Thanks,

**Comment by Crissman** [comment]
@nzw0301 To do list is being managed here: https://github.com/optuna/optuna/pull/1707
