### ISSUE TITLE
Is there any way to store customized results in each step?

### ISSUE THREAD

**Issue by deng-cy** [optuna/optuna#1549]
I want to train a GAN with two loss values. Although I will use their sum for `trial.report(loss, step)`, I want to keep them separately. I found that `trial` and `study` have attributes, then is there a similar feature to store customized results for each step?

**Comment by ytsmiling** [comment]
Unfortunately, optuna does not provide an interface to report custom results. So, please use `trial.set_user_attr` to save the results.
```python
trial.set_user_attr("loss-step-{}".format(i), {"generator": generator_loss, "discriminator": discriminator_loss})
```
Optuna provides multi-objective optimization, and when you are using it, you can report multiple metrics. This might serve as an alternative, but I'm not sure multi-objective optimization is suitable for training GANs.

**Comment by deng-cy** [comment]
Thanks for your reply. I just want to know. Hope this feature can be added in the future.
