### ISSUE TITLE
Make LightGBM Tuners number of trials per step parametrizable

### ISSUE THREAD

**Issue by Amyantis** [optuna/optuna#1550]
Hello,

The provided LightGBM tuners allow us to optimize LightGBM hyperparameters in a stepwise manner. Each step, defined as a method of [_LightGBMBaseTuner](https://github.com/optuna/optuna/blob/4fc8e5cd143a1ad8e5d9bd89e5bdb48a4713d3c8/optuna/integration/_lightgbm_tuner/optimize.py#L317), has a constant number of trials. The number of trials for each step is defined through the default values of the corresponding methods and thus are buried in the code.

The steps methods are called here, using default arguments:
https://github.com/optuna/optuna/blob/4fc8e5cd143a1ad8e5d9bd89e5bdb48a4713d3c8/optuna/integration/_lightgbm_tuner/optimize.py#L463
The default number of trials are set on each step method definition. For instance, 7 trials for _tune_feature_fraction_
https://github.com/optuna/optuna/blob/4fc8e5cd143a1ad8e5d9bd89e5bdb48a4713d3c8/optuna/integration/_lightgbm_tuner/optimize.py#L483

So far, we have:

- 7 trials for tune_feature_fraction
- 20 trials for tune_num_leaves
- 10 trials for tune_bagging
- 6 trials for tune_feature_fraction_stage2
- 20 trials for tune_regularization_factors

for a total of 63 optuna trials.

I would like, at least, to be able to parametrize that n=63 trials so that the number of trials at each step increases proportionally.

Thank you.

**Comment by toshihikoyanase** [comment]
Thank you for your feature request.

> I would like, at least, to be able to parametrize that n=63 trials so that the number of trials at each step increases proportionally.

Sounds good! I'm also thinking of the mechanism to customize the tuning steps of `LightGBMTuner`. It may be a good starting point to change the number of trials.

I think we have come choices to change the total number of trials.

1. Add an option to specify the total number of trials.
```python
LightGBMTuner(n_trials=63)  # the default
LightGBMTuner(n_trials=68)  # +1 trial / step
LightGBMTuner(n_trials=58)  # -1 trial / step

LightGBMTuner(n_trials=64)
```
This approach is straightforward, but it may not be obvious which step should acquire the additional step if uses specify `n_trials=64`.

2. Add an option to specify the number of additional trials per step.
```python
LightGBMTuner(n_additional_trials=0)  # the default
LightGBMTuner(n_additional_trials=1)  # +1 trial / step
LightGBMTuner(n_additional_trials=1)  # -1 trial / step
```

This approach may be less ambiguous than the first approach.  Which interface do you like?

**Comment by jbferdinand** [comment]
Hello,

What about using a multiplier ? 
```Python
LightGBMTuner(n_trials_multiplier=1) # default
LightGBMTuner(n_trials_multiplier=3) # For each step, n_trials is multiplied by 3
```
This makes it simple to increase the number of trials while also keeping the current distribution. 🙂
