### ISSUE TITLE
Can I set search condition based on number of trials?

### ISSUE THREAD

**Issue by JoshKoh** [optuna/optuna#1553]
Can I set search condition based on number of trials? For example, I want to explore certain value range for the first 5,000 trials, then change after 5,000 trials:

If trials <= 5,000:
    param1 = trial.suggest_int('param1', 0, 50)
    param2 = trial.suggest_int('param2', 0, 50)
elif trials > 5,000:
    param1 = trials.suggest_int('param1', 100, 200)
    param2 = trials.suggest_int('param2', 100, 200)

Is there a way to access the number of trials completed in the conditional statement?

**Comment by ytsmiling** [comment]
You can use [trial.number](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.number) for the purpose.
```python
def objective(trial):
    if trial.number < 5000:
        param1 = trial.suggest_int('param1', 0, 50)
        param2 = trial.suggest_int('param2', 0, 50)
    else:
        param1 = trial.suggest_int('param1', 100, 200)
        param2 = trial.suggest_int('param2', 100, 200)
    return 0.0
```
The `trial.number` includes not only `COMPLETED` trials but also `WAITING` trials,  `RUNNING` trials, `FAILED` trails, and `PRUNED` trials. So especially when you are using distributed optimization, the behavior might be different from what you expect. Currently, no methods are available to count `COMPLETED` trials exclusively.

**Comment by JoshKoh** [comment]
Thank you. I will try this out. You guys are doing an amazing work!

**Comment by JoshKoh** [comment]
If using distributed or n_jobs = -1, process hangs after 5000 trials. (when trial.number >= 5000)
However, if not using any distributed optimization, run continues until completion.

**Comment by ytsmiling** [comment]
Thank you for updates. The trial.number is expected to work under distributed environment as well, and it sounds like a bug. Would you provide us more details, preferably in codes?

**Comment by JoshKoh** [comment]
Did some further testing, definitely a bug. The script works sometimes and other times just hangs indefinitely, even for single core processing.

Some representative codes:

def objective(trial):
     if trial .number <= 1000:
            param1 = trial.suggest_int('param1', 0, 12)
     else:
            param1 = trial.suggest_int('param1', 13, 14)
     model = model(param1)   # example model function
     score = model.evaluate (x, y)   # returns R2
     return score

if __name__ == '__main__':
    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=2000)

The code sometimes execute and finishes for 2000 trials with behavior as expected but most of the time it just hangs with no exception or errors. For multi-core processing (n_jobs=-1), it will just hang at trial = 1000.

**Comment by AVR-PlantPhenomics** [comment]
Tried something different, still same issue, hangs after 1000 trials:

def objective(trial):
if trial.number <= 1000:
range = (0, 12)
else:
range = (13, 14)
param1 = trial.suggest('param1', range[0], range[1])
......the rest is same as above.

**Comment by hvy** [comment]
Thanks for the report and the investigation. Seems rather serious, likely some joblib-related issue if it only happens when `n_jobs != 1`? Are you able to pinpoint where in the code it hangs, e.g. if it's in the objective function, if so, if it's in `trial.suggest_*` or some other line? I can seemingly not reproduce the issue with a similar conditioned toy-example as describe above.

**Comment by AVR-PlantPhenomics** [comment]
The issue happens even if **n_jobs =1 (single core).** 

The code hangs in the objective function, in the conditional flow after 1000 trials: 
def objective(trial):
if trial .number <= 1000:
param1 = trial.suggest_int('param1', 0, 12)
**else:
param1 = trial.suggest_int('param1', 13, 14)**

To be more specific to my application, I am using param1 as index to slice a list of names:
selected_name = name_list[param_1]
 
I am using a threadripper 3970X (32 cores). Code was tested in PyCharm and Spyder IDE with conda virtual env. Win10-64bit.

**Comment by JoshKoh** [comment]
The issue happens even if n_jobs =1 (single core).

The code hangs in the objective function, in the conditional flow after 1000 trials:
def objective(trial):
if trial .number <= 1000:
param1 = trial.suggest_int('param1', 0, 12)
else:
param1 = trial.suggest_int('param1', 13, 14)

To be more specific to my application, I am using param1 as index to slice a list of names:
selected_name = name_list[param_1]

I am using a threadripper 3970X (32 cores). Code was tested in PyCharm and Spyder IDE with conda virtual env. Win10-64bit.

**Comment by hvy** [comment]
Thanks for the quick update. I have not investigated it yet but I'm wondering if gets stuck in some infinite loop, e.g. https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L392 assuming you're using the default `TPESampler`.

**Comment by ytsmiling** [comment]
I'm not sure how the loop in the TPE sampler relates to the distributed optimization, but the while-loop is a possible cause of the issue and also a source of inefficiency. I made a follow-up PR #1562.

**Comment by HideakiImamura** [comment]
The current Optuna default sampler (`TPESampler`) does not expect the range of parameters to change abruptly during optimization. If the range of the parameter changes, we need to solve an "extrapolation problem" to estimate the objective function. I'm not sure, but the optimization performance may be degraded. I think it's safe to give another condition a different name.

```python
def objective(trial):
    if trial .number <= 1000:
        param1 = trial.suggest_int('param1_in_cond1', 0, 12)
    else:
        param1 = trial.suggest_int('param1_in_cond2', 13, 14) 
```

**Comment by JoshKoh** [comment]
Hideaki san gets 100 points for this solving this issue. Giving the different condition another name solved it:

def objective(trial):
    if trial .number <= 1000:
        param1 = trial.suggest_int('param1_in_cond1', 0, 12)
    else:
        param1 = trial.suggest_int(**'param1_in_cond2**', 13, 14) 

Code ran fine with both n_jobs=1 and n_jobs=-1. 

I am using the default TPE sampler and as pointed out, I don't think it likes it when the range of the parameter changes. Thank you, you guys are simply amazing for such quick responses. Definitely the best experience that I've had interacting on GitHub.

**Comment by JoshKoh** [comment]
Looks like Hideaki san gets bonus points as well for this. I can confirm optimization performance for TPESampler degrades significantly when a different set of condition is used during the run. I wonder is this also expected for a different sampler like CMA-ES?

**Comment by ytsmiling** [comment]
The CMA-ES sampler uses random sampling as a fallback if different ranges are specified. Things are better when using the CMA-ES sampler than the TPE sampler in that it does an appropriate fallback, but the performance will also degrade with the CMA-ES sampler.
I think the support of the extrapolation is not easy and the feature won't be added into optuna in the near future. So it seems optuna should issue warnings when different ranges are used to suggest parameters.

**Comment by HideakiImamura** [comment]
> I wonder is this also expected for a different sampler like CMA-ES?

Yes, I think so. The performance of any other sampling algorithms may be degraded. As pointed out by @ytsmiling, the CMA-ES in Optuna turns into a user-specified independent sampler (a random sampler as default) when the parameter range changes. Raising a warning is a good idea, and I think another option is to implement a fallback to the random sampler for TPE when the parameter range changes.

**Comment by ytsmiling** [comment]
Surely, we need both:)

**Comment by JoshKoh** [comment]
Thank you, guys for your valuable feedback and insights. I think this issue can be closed. Agree with giving warning (also pointing out that the **different condition needs a different name**) and ensuring a proper fallback for the samplers in case of different ranges.
