### ISSUE TITLE
Create a list of pruning callbacks and link from the pruning tutorial.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1559]
See https://github.com/optuna/optuna/pull/1545#pullrequestreview-455262928.

**Comment by hvy** [comment]
I guess we could also just put a link to https://optuna.readthedocs.io/en/latest/reference/integration.html since most functionalities there are for pruning.

**Comment by crcrpar** [comment]
You might want to see https://github.com/optuna/optuna/pull/1543/commits/84a69064e330ed068d602089632a2235b7c2abd8.

**Comment by crcrpar** [comment]
@toshihikoyanase Now https://optuna.readthedocs.io/en/latest/tutorial/007_pruning.html#integration-modules-for-pruning has the link to the complete list of integration modules. Does it look cool, or need some refinement?

**Comment by toshihikoyanase** [comment]
@crcrpar Thank you for your contribution. As you suggested, https://github.com/optuna/optuna/commit/84a69064e330ed068d602089632a2235b7c2abd8 resolved this issue. I don't have any followup tasks, and let me close this issue.
