### ISSUE TITLE
[RFC] Which module do we use to check the library version?

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1560]
Optuna uses three modules to check the library versions, i.e., `packaging`, `pkg_resources` and `distutils`. As mentioned in #1551, `packaging` is not a standard library, and we need an additional dependency.

Currently, `packaging` is only used for the deprecation, and maybe we can replace it with `distutils` and reduce the number of dependencies.

See https://github.com/optuna/optuna/pull/1551#pullrequestreview-455262699 for further details.

**Comment by toshihikoyanase** [comment]
I summarised the pros and cons of the three libraries as follows:

### Pros
- `distutils`: a standard library
- `pkg_resources`: properly parses version based on PEP404 (see the [reference](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#parsing-utilities)), and is included in `setuptools`, and many users have already installed it.
- `packaging`: properly parses versions like `1.0.0rc2` or `1.0.0.post0`  based on PEP440 and has rich features such as separating the version number into `major`, `minor` and `micro`.

### Cons
- `distutils`: no (or little) official documents, and cannot compare some versions like `1.0.0rc2` and `1.0.0`.
- `pkg_resources`: increases the number of dependencies
- `packaging`: increases the number of dependencies

### Comments

Currently, `distutils.version.StrictVersion` is used to check the third party libraries such as `plotly` and `bokeh`, but it may cause errors, for example, if users the release candidate version (e.g., plotly==4.9.0rc1).

```console
>>> import optuna
Traceback (most recent call last):

...

  File "/Users/yanase/.pyenv/versions/3.7.7/Python.framework/Versions/3.7/lib/python3.7/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '4.9.0rc1'
```

I think it would be safe to use `pkg_resources` or `packaging`, which can parse such versions properly. They are third party libraries, but I think they are popular enough so that we can assume usual users have already installed them.

**Comment by hvy** [comment]
Thank you for the throughout investigation. I agree with introducing either `pkg_resources` or `packaging`, but don't have a stronger preference for either, since both seem very ubiquitous (license-wise, they also seem okay). Some argument for `packaing` could be that it's somewhat lighter and that `setuptools` could be overkill for this particular use case.

- https://pypi.org/project/setuptools/#files
- https://pypi.org/project/packaging/#files

**Comment by toshihikoyanase** [comment]
@hvy Sounds reasonable. I created a PR #1589 to replace the other modules with `packaging` and labeled it contribution-welcome.

**Comment by hvy** [comment]
Thanks for the separate issue. How about closing this RFC as resolved since we've come to a conclusion (possibly reopening it as needed)?

**Comment by toshihikoyanase** [comment]
@hvy Thank you for your suggestion. I'll close this issue.
