### ISSUE TITLE
[RFC] Clean up `setup.py`

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1576]
## Motivation

`setup.py` contains duplicated code and some Python version specific conditions that could be cleaned up.

What might also have to be discussed is the compatibility rules of the keys in the extras requirements, if we'd like to reduce or restructure them.

## Description

To refactor `setup.py`, making it less painful to maintain.

**Comment by hvy** [comment]
Partially addressed by https://github.com/optuna/optuna/pull/2105 using environment marker.

**Comment by not522** [comment]
#3517 is merged. Are there any other tasks related to this issue?

**Comment by himkt** [comment]
I think we can close this issue now. What do you think @hvy?

**Comment by hvy** [comment]
Sorry for the late response, yes sound good given #3517.
