### ISSUE TITLE
Update Kubernetes example of "simple" to avoid potential errors

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#1581]
https://github.com/optuna/optuna/blob/a5a55a6354b3c60dd7e3a08adcbc3818e90599f0/examples/kubernetes/simple/sklearn_distributed.py#L45-L54

Like https://github.com/optuna/optuna/pull/1536, we should create a study before running the script.

**Comment by Nishikoh** [comment]
Hi, I'd like to tackle that.

**Comment by crcrpar** [comment]
@Nishikoh 
Awesome! Should you have some questions, feel free to ping me 😃
