### ISSUE TITLE
Use `packaging` to check the library version

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1589]
## Motivation

Optuna uses several modules to check library versions such as `packaging ` and `distutils`.  We'd like to rewrite them using `packaging` as discussed in #1560.

## Description

Please update the version checking in the following files:

The following files use `distutils`:
- [x] optuna/dashboard.py
- [x] optuna/visualization/_plotly_imports.py

The following files use `pkg_resources`:
- [x] examples/allennlp/allennlp_jsonnet.py
- [x] examples/allennlp/allennlp_simple.py
- [x] examples/chainer_simple.py
- [x] examples/pruning/chainer_integration.py
- [x] examples/pytorch_lightning_simple.py
- [x] examples/tensorflow_eager_simple.py
- [x] tests/integration_tests/test_tfkeras.py

You can submit a PR for each of the files.

**Comment by VamshiTeja** [comment]
Hello, I would like to tackle this.

**Comment by toshihikoyanase** [comment]
Resolved by #1610. Let me close this issue.
Thank you for your contribution, @VamshiTeja !
