### ISSUE TITLE
Make source comments more descriptive in `examples/pytorch_lightning_simple.py`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#1590]
## Motivation

Based on discussions in https://github.com/optuna/optuna/issues/1443, we need to make source comments more descriptive in `examples/pytorch_lightning_simple.py`.

## TODO

Fixing ambiguous points like [here](https://github.com/optuna/optuna/blob/master/examples/pytorch_lightning_simple.py#L72) based on https://github.com/optuna/optuna/issues/1443#issuecomment-650851727.

**Comment by nzw0301** [comment]
This issue is supposed to be solved by #1878. Could @HideakiImamura close this issue?

**Comment by hvy** [comment]
Thanks @nzw0301 for the heads up. Let me close this issue. Cc. @HideakiImamura, let us know if you want it reopened.
