### ISSUE TITLE
Update tutorial for Optuna Command-Line interfaces

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#1592]
Apart from #1394.

Thanks to the great contributions of @ritvik1512, we removed mentions about `optuna study optimize` in examples.
After removing them in documents, we might update a tutorial for command-line interfaces.
https://github.com/optuna/optuna/blob/master/tutorial/005_cli.py

It would be helpful if the tutorial shows an example of the following subcommands: `storage update`, `studies`, `create study`, and `dashboard` (optional as it is beta).

**Comment by toshihikoyanase** [comment]
As mentioned in https://github.com/optuna/optuna/issues/782#issuecomment-675823139, @crcrpar will re-organize tutorials. We can revisit this issue after that.
