### ISSUE TITLE
not quite sure to classify as a bug 

### ISSUE THREAD

**Issue by ashraf-01** [optuna/optuna#1607]
anyway , am on Ubuntu machine 18.04 version with linux as OS , I just wanted to replicate an example witiin the github sample 
example folder  (sklearn_additional_args.py) as this version is faster , I wanted two arguments to be optimized in SVC with rbf kernel , the C AND THE LERNING RATE GAMMA , I have instead used my own data it is of time series observations  , the main dataset is called data , then , add[cols] to refer to feature , and target is  data['returns']  , all columns within the cols are actually float64  , except then my code becomes ( after importing the necessary libraries)

class Objective(object):

    def __init__(self, data):
        self.data = data

    def __call__(self, trial):
        x, y = self.data[cols], self.data['returns']

        classifier_name = trial.suggest_categorical("classifier", ["SVC", "RandomForest"])
        if classifier_name == "SVC":
            svc_c = trial.suggest_float("svc_c", 1e-10, 1e10, log=True)
            svc_gamma = trial.suggest_loguniform("svc_gamma",1e-5, 1e-2)
            classifier_obj = sklearn.svm.SVC(C=svc_c, gamma=svc_gamma)

        score = sklearn.model_selection.cross_val_score(classifier_obj, x, y, n_jobs=-1, cv=3)
        accuracy = score.mean()
        return accuracy   
'''
then in the next block as am doing my analysis on jupyter notebook

if __name__ == "__main__":
    # Load the dataset in advance for reusing it each trial execution
    data
    objective = Objective(data)
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

then am getting the error below 
ValueError: Unknown label type: 'continuous' 
UnboundLocalError: local variable 'classifier_obj' referenced before assignment
joblib.externals.loky.process_executor._RemoteTraceback: 
your input is highly appreciated

**Comment by toshihikoyanase** [comment]
@ashraf-01 Thank you for your question.

> UnboundLocalError: local variable 'classifier_obj' referenced before assignment

The cause of the error seems to be the following line:
```python
    classifier_name = trial.suggest_categorical("classifier", ["SVC", "RandomForest"])
```
The value of `classifier _name` can be `RandomForest`, but the code does not create the random forest classifier.
So, it should be removed, for example, as follows:

```python
def __call__(self, trial):
    x, y = self.data[cols], self.data['returns']

    svc_c = trial.suggest_float("svc_c", 1e-10, 1e10, log=True)
    svc_gamma = trial.suggest_loguniform("svc_gamma",1e-5, 1e-2)
    classifier_obj = sklearn.svm.SVC(C=svc_c, gamma=svc_gamma)

    score = sklearn.model_selection.cross_val_score(classifier_obj, x, y, n_jobs=-1, cv=3)
    accuracy = score.mean()
    return accuracy   
```

**Comment by ashraf-01** [comment]
thanks sir , for the prompt , concise answer , I wish how ever if i can access the graph which shows convergence and happens after how many iterations for each parameter , just for pure statistical studies purposes

**Comment by toshihikoyanase** [comment]
>  I wish how ever if i can access the graph which shows convergence and happens after how many iterations for each parameter ,

As you may already know, but I think the [visualization feature](https://optuna.readthedocs.io/en/stable/reference/visualization.html) can help you.

I'm not sure whether this `iteration` refers to the iteration of Optuna's trials or the iteration of SVM training, but, you may be able to use [`optuna.visualization.plot_optimization_history`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.visualization.plot_optimization_history.html#optuna.visualization.plot_optimization_history
) to show such a graph if you refer to the former one.

If you want to analyze the latter one (i.e., iteration of the training loop), you may need to report the intermediate values (objective value at each iteration), and use the [`optuna.visualization.plot_intermedicate_values`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.visualization.plot_intermediate_values.html#optuna.visualization.plot_intermediate_values).

**Comment by toshihikoyanase** [comment]
Let me close this issue since it was labeled as `stale`. Please feel free to re-open it or create a new one if you have further comments.
