### ISSUE TITLE
PercentilePruner raise RuntimeWarning: Mean of empty slice   return np.nanmean(a, axis, out=out, keepdims=keepdims)

### ISSUE THREAD

**Issue by chang19940513** [optuna/optuna#1608]
When use PercentilePruner, if all trails' step are small and a new trail's step may too big, then _get_percentile_intermediate_result_over_trials will return None. And raise RuntimeWarning: Mean of empty slice   return np.nanmean(a, axis, out=out, keepdims=keepdims).

## Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

## Error messages, stack traces, or logs

```
# error messages, stack traces, or logs
```

## Steps to reproduce

1.
2.
3.

## Reproducible examples (optional)

```python
# python code
```

**Comment by HideakiImamura** [comment]
Thanks for the report. Do you have any reproducible code example? It will help for debugging.

IMO, your suggestion is reasonable. Reporting objective value at the different steps is the basic behavior that Optuna should support.
