### ISSUE TITLE
Remove the document for `with_traceback` method of Optuna's exception classes

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1615]
Currently, Optuna's exception classes have the documentations of `with_traceback` method, which is inherited from `Exception`. I don't think it is informative for readers and it can be removed from the reference.

![image](https://user-images.githubusercontent.com/3255979/89862021-0a4afd80-dbe2-11ea-8f86-626d960b4255.png)

The following `Exception` has the `with_traceback` method.
- [ ] `optuna.exceptions.CLIUsageError`
- [ ] `optuna.exceptions.OptunaError`
- [ ] `optuna.exceptions.TrialPruned`
- [ ] `optuna.exceptions.CLIUsageError`
- [ ] `optuna.exceptions.StorageInternalError`
- [ ] `optuna.exceptions.DuplicatedStudyError`

CC @keisuke-umezawa Please let me know if you have any comments.

**Comment by i-am-jeetu** [comment]
Hi, I want to take it up.
A simple fix, in my view, is to edit sphinx config [file](https://github.com/optuna/optuna/blob/master/docs/source/conf.py)   to exclude all ``with_traceback`` method. Is this sounds fine?

**Comment by toshihikoyanase** [comment]
Thank you for your interest.

> to edit sphinx config file to exclude all `with_traceback` methods

It sounds reasonable since Optuna does not have `with_traceback` methods in any classes. I'm looking forward to your PR.

@keisuke-umezawa You may also be interested in the PR, so your feedback is more than welcome.
