### ISSUE TITLE
Show example directory more apparent in the docs

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#1617]
## Motivation
The current [Optuna example directory](https://github.com/optuna/optuna/tree/master/examples) can be accessed only from [GitHub page](https://github.com/optuna/optuna) or "optuna.org -> Code Examples -> Others -> See full example on GitHub". It is difficult for users to see an overview of example files. 

## Description
Add a link to the Optuna example directory in the docs. Making an "example" item in the left content column is a good idea. The text can be same as `examples/README.md`.

**Comment by HideakiImamura** [comment]
This issue will be addressed in #1625.

**Comment by keisuke-umezawa** [comment]
@HideakiImamura Do we need to do anything other than #1625 ? If not, we can close this issue.

**Comment by HideakiImamura** [comment]
Thanks for the notification. I will close this issue.
