### ISSUE TITLE
Provide a user-defined pruner example

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#1619]
## Motivation
In the current Optuna example, we already have a [user-defined sampler example](https://github.com/optuna/optuna/blob/master/examples/samplers/simulated_annealing_sampler.py). We also want a user-defined pruner example.

## Description
Providing a user-defined pruner example is highly welcomed. The logic of that pruner can be anything.

**Comment by not522** [comment]
Is it OK to close this issue?

**Comment by hvy** [comment]
This is not a strong opinion but we could keep it open for contribution fixing the remaining TODOs discussed in in #2140.

**Comment by nzw0301** [comment]
I think #2446 addressed all TODO tasks. Let me close this issue.
