### ISSUE TITLE
Add a tutorial entry to explain the usage of `ThresholdPruner`

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1620]
## Background

[`ThresholdPruner`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.pruners.ThresholdPruner.html) can prune the trials whose intermediate values exceed the user-defined threshold. The other pruners such as [`MedianPruner`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.pruners.MedianPruner.html)
 and [`HyperbandPruner`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.pruners.HyperbandPruner.html) compares the values with other trials, but `ThresholdPruner` doesn't. This characteristic is sometimes useful, for example, when the intermediate values are noisy and the other pruners don't work as expected. In this case, users may be able to save the optimization resource if they only prune the clearly unpromising trials based on the threshold.

## Document request

Please add a tutorial entry to explain the usage of `ThresholdPruner`.

**Comment by HideakiImamura** [comment]
I think this is should be added into optuna-examples. Let me close this issue.

**Comment by HideakiImamura** [comment]
Ops. i misunderstood. It it good to add this tutorial into the document.

**Comment by g-votte** [comment]
Since this issue has been open for a long time, let me close once. Feel free to reopen upon necessity.
