### ISSUE TITLE
Add a tutorial entry to explain how to accelerate your optimization.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1621]
Please add a tutorial entry that explains tips to speed up optimization.
We have multiple tips, for example, as follows:
- Use `InMemoryStorage` instead `RDBStorage` if you don't have to persist optimization results.
- Turn off the garbage collection if you use old version of Optuna.

**Comment by g-votte** [comment]
Since this issue has been open for a long time, let me close once. Feel free to reopen upon necessity.
