### ISSUE TITLE
Fix storage consistency for study creation log event

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1622]
## Motivation

Different concrete storages should behave similar. There is currently a logging behavior inconsistency when a study is being created and it should be fixed. More concretely [`RDBStorage` logs the event](https://github.com/optuna/optuna/blob/master/optuna/storages/_rdb/storage.py#L168), while `InMemoryStorage` and `RedisStorage` don't.

A PR author might also want to have a look at how the study creation method of the storage is called from `create_study` [here](https://github.com/optuna/optuna/blob/master/optuna/study.py#L787).

## Description

See above.

**Comment by toshihikoyanase** [comment]
@hvy I think #1629 resolved this issue. Can we close this issue?

**Comment by hvy** [comment]
You're right, let me close it.
