### ISSUE TITLE
[RFC] Customizable steps of `LightGBMTuner` and `LightGBMTunerCV`

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#1632]
## Motivation
The steps of `LightGBMTuner` are fixed, and users cannot add the parameters to tune. I saw users' demand to customize the steps.

For example,
- @Amyantis submitted a feature request to change the number of trials at each step in #1550, and
- @kdlin wants to tune additional parameters such as `max_depth` and `max_bin` in the [Gitter conversation](https://gitter.im/optuna/optuna?at=5f2c8857dca038052a51abbd).

I created this issue to aggregate such user needs, and I'd like to discuss the feasible and user-friendly implementation of customizable steps.

## Description

Currently, I do not have any ideas for API design, but let me share some existing attempts.

**Approach 1**
I tried to extend `LightGBMTuner` to add a step to tune `max_depth`. See https://colab.research.google.com/drive/1vBfktSi7qXc8T4X6x1ib3IeqIlqcOAOH?usp=sharing. 
It was a bit complicated because I needed to modify two classes, i.e., `LightGBMTuner` and `_OptunaObjective`. I don't think this is a convenient way to customize LightGBM tuner's step, and we may need major refactoring of `LightGBMTuner` and `_OptunaObjective`.

**Approach 2**
As mentioned in [this Gitter comment](https://gitter.im/optuna/optuna?at=5f2e78f2d4bc1a71bc88e05c), @jeffzi created a prototype of `StepwiseTuner`, which accepts a dictionary containing step information. It also enables us to create a stepwise tuner for other libraries such as XGBoost and CatBoost.

**Comment by kmedved** [comment]
A customizable stepwise tuner would be amazing functionality. The approach works incredibly well for LightGBM, and would be an even bigger boon to slower tuning libraries like Catboost or Ngboost (new probabilistic boosting library from Andrew Ng's team).

**Comment by jeffzi** [comment]
Some time ago I prototyped a `StepwiseTuner` class that accepts a list of named Steps in its init. 

It's essentially an abstraction of `LightGBMTuner` that needs to be specialized in a dedicated subclass. The shared logic of looping through the steps, along with keeping track of the global time and trial budgets across steps is implemented in `StepwiseTuner.tune()`.

This approach is flexible. The steps and their order can be customized, the time and trial budget per step as well.

Here is a draft of the base interfaces:
```python

from optuna import distributions, logging, pruners, samplers

class BaseStep(ABC):
    def __init__(
        self,
        sampler: samplers.BaseSampler = None,
        pruner: pruners.BasePruner = None,
        n_trials: int = None,
        timeout: int = None,
    ):
        self.sampler = sampler
        self.n_trials = n_trials
        self.pruner = pruner
        self.timeout = timeout

    @abstractmethod
    def suggest(self, trial: Trial) -> Dict[str, Any]:  
        raise NotImplementedError

class DistributionStep(BaseStep):
    def __init__(
        self,
        distributions: Dict[str, distributions.BaseDistribution],
        sampler: samplers.BaseSampler = None,
        pruner: pruners.BasePruner = None,
        n_trials: int = None,
        timeout: int = None,
    ):
    pass   


class GridStep(DistributionStep):
    def __init__(
        self,
        search_space: Dict[str, List[Union[str, float, int, bool, None]]],
        pruner: pruners.BasePruner = None,
        n_trials: int = None,
        timeout: int = None,
    ):
    pass

class StepwiseTuner:
    def __init__(
        self,
        steps: List[Tuple[str, BaseStep]],
        # objective accepts Trial and parameters
        objective: Callable[[optuna.Trial, Dict[str, Any]], float],
        direction: StudyDirection,
        n_trials: int = None,
        timeout: int = None,
        n_jobs: int = 1,
    ):
    pass

    def tune(
        self, storage: Union[None, str, storages.BaseStorage] = None,
    ) -> Tuple[Dict[str, Any], float]:
    # should support callbacks, catch, gc_after_trial arguments?
    pass
```
Internally, `StepwiseTuner.tune()` creates a study for each step and an objective function based on `Basestep.suggest()` (similar to `LightGBMTuner` implementation). `StepwiseTuner.tune()` returns the best params and best values but those should be class attributes to follow  `LightGBMTuner` interface. 

Usage example:
```python
...

params = {
    "seed": 42,
    "objective": "multi:softprob",
    "tree_method": "hist",
    "eta": 0.05,
    "max_depth": 12,
    "max_leaves": 4095,
    "min_child_weight": 1,
    "gamma": " 0",
    "colsample_bytree": 1,
    "subsample": 0.8,
    "colsample_bytree": 0.8,
    "colsample_bylevel": 0.5,
    "verbosity": 1,
    "nthread": 1,
    "num_class": ref_set.num_class,
}

steps = [
    (
        "max_depth and max_leaves",
        GridStep(
            {
                "max_depth": list(range(3, 13)),
                "max_leaves": [15, 31, 63, 127, 255, 511, 1023, 2047, 4095],
            }
        ),
    ),
    (
        "sampling",
        DistributionStep(
            {
                "subsample": DiscreteUniformDistribution(0.6, 1.0, 0.05),
                "colsample_bytree": DiscreteUniformDistribution(0.6, 1.0, 0.05),
                "colsample_bylevel": DiscreteUniformDistribution(0.5, 1.0, 0.05),
            }
        ),
    ),
]

tuner = XgboostTuner(
    params,
    dtrain,
    steps,
    obj=_forecast_avg_obj,
    feval=feval,
    n_jobs=-1,
    n_splits=5,
    num_boost_round=5000,
    early_stopping_rounds=25
)

best_params, best_value = tuner.optimize()
```

For convenience, default steps can be offered to the end-users. For example (xgboost):

```python
def create_xgb_major_step():
    return [
        (
            "max_depth and max_leaves",
            GridStep(
                {
                    "max_depth": list(range(3, 13)),
                    "max_leaves": [15, 31, 63, 127, 255, 511, 1023, 2047, 4095],
                }
            ),
        )
    ]

... 

# default for XGBoostTuner if no steps given
def create_xgb_comprehensive_steps():
    return [
        create_xgb_major_step(),
        create_xgb_sampling_step(),
        create_xgb_hessian_reg_step(),
        create_xgb_reg_step(),
    ]
```

**Comment by hal-314** [comment]
Any news regading a customizable stepwise tuner? It would be an amazing functionality. 

My case: currently, I want to optimize a neuronal network. To reduce the search space, I perform hyperparameter optimization by optimizing one ortwo hyperparameter every time. So, having a generic and customizable stepwise tuner would be perfect :D

**Comment by jeffzi** [comment]
There seems to be interest in this feature. I realize it's probably hard for people to give feedback based on the draft I outlined above. 

I can work on the PR of a customizable StepwiseTuner + a stab at reproducing the current LightGBMTuner with it. That should help to test the viability of the proposal and make it easier to give feedback.

**Comment by toshihikoyanase** [comment]
> I can work on the PR of a customizable StepwiseTuner + a stab at reproducing the current LightGBMTuner with it.

That's great! Currently, I'm focusing on the review of #1018 to introduce Scikit-learn interface of `LightGBMTuner`, and I'll be able to work on the review of your PR after that. Anyway, your PR is more than welcome.

**Comment by toshihikoyanase** [comment]
@jeffzi I found that this issue has been `stale`. If you have any problems, please let me know.

**Comment by jeffzi** [comment]
@toshihikoyanase Thanks for asking. 

I have a working `Stepwise` interface and rewrites of `LightGBMTuner` and `LightGBMTunerCV` leveraging this interface. I need to add some documentation and tests then I'll submit the PR over the weekend.

**Comment by jeffzi** [comment]
@toshihikoyanase I've submitted the PR.

**Comment by toshihikoyanase** [comment]
@jeffzi Thank you for your great PR. I'll check it.

**Comment by toshihikoyanase** [comment]
Let me reopen this issue since we are discussing in #1947 and #1997.
