### ISSUE TITLE
How to optimize on feval when using LightGBMTunerCV

### ISSUE THREAD

**Issue by rafmacalaba** [optuna/optuna#1636]
Hello,

I have a custom feval function for lightgbm which is basically f1_score, how do I optimize on that instead of the default binary_logloss metric? Thanks for this library!

**Comment by toshihikoyanase** [comment]
Hello, @rafmacalaba
Thank you for your question. Currently, `LightGBMTunerCV` does not support custom metrics as reported in #1351. #1522 tried to resolve the issue, but it has been suspended. If you are interested in taking over the development, please let us know.

**Comment by rafmacalaba** [comment]
@toshihikoyanase got it, I am referring to `feval` optimization not the `metric`. I have an idea how to get it done. Expect a PR from me regarding this. Thanks!

**Comment by toshihikoyanase** [comment]
@rafmacalaba Thank you! I'm looking forward to your PR.
