### ISSUE TITLE
Improve the search space of XGBoost example.

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#1683]
## Motivation

From following resources, the search space of `examples/xgboost_simple.py` seems not to be practical.

* https://www.analyticsvidhya.com/blog/2016/03/complete-guide-parameter-tuning-xgboost-with-codes-python/
* https://www.youtube.com/watch?v=VC8Jc9_lNoY
* https://www.amazon.co.jp/dp/B07YTDBC3Z/

## Description

Improve the search space of `examples/xgboost_simple.py`.

## Additional context (optional)

I once opened #1574, but I'm not familiar with XGBoost very much.
So I closed my pull request and opened this issue.

I think this ticket is good for first-time contributor.

**Comment by souravsingh** [comment]
@hvy I am interested in working on the issue.

**Comment by c-bata** [comment]
I assigned you to this issue 👍

**Comment by hvy** [comment]
That'd be great, looking forward to the PR 👍

**Comment by jeromepatel** [comment]
I am looking forward to work on this issue! Please assign it to me if possible

**Comment by hvy** [comment]
Sure, I think you can. It's been assigned but it's also been open for a while now. 👍

**Comment by hvy** [comment]
Let me close this issue as fixed by #2346.
