### ISSUE TITLE
Introduce isort to sort imports?

### ISSUE THREAD

**Issue by harupy** [optuna/optuna#1694]
## Motivation

It's a pain for both contributors and maintainers to sort imports. It'd be nice if we could automate this process.

## Solution

https://github.com/timothycrosley/isort

**Comment by HideakiImamura** [comment]
Thanks for proposing `isort`! I'm looking forward to using `isort` in Optuna. It will speed up the development of Optuna.

By the way, PR #1695 is ongoing, so let me label `no-stale` to this Issue.
