### ISSUE TITLE
Make `plot_contour` example more pedagogical

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1697]
## Motivation

Examples in the API reference should be pedagogical. The plot for the contour plot is not with somewhat poorly visible categorical parameter values.

![Screen Shot 2020-08-23 at 15 30 02](https://user-images.githubusercontent.com/5983694/90972686-4f621e80-e556-11ea-8344-e2112290a0a6.png)

## Description

The contour plot example could use a better suited objective function e.g. limited to floats. The following code was provided by @toshihikoyanase . Maybe we can modify it to only suggest 2 variables to keep it simple and use it here.

```python
def objective(trial):
    x = trial.suggest_float("x", 0, 1)
    y = trial.suggest_float("y", 0, 1)
    z = trial.suggest_float("z", 0, 1)
    return (x - 0.5) ** 2 + (y - 0.2) ** 2 + (z - 0.7) ** 2
```

1. Update example code.
2. Update example image generation script.
3. Run the script from 2. to generate a new image.

**Comment by HideakiImamura** [comment]
This problem now will be addressed in PR #1716.

**Comment by hvy** [comment]
#1716 is now merged. I think we can close this issue after https://github.com/optuna/optuna/pull/1758.

**Comment by hvy** [comment]
Let me close this issue as fixed (it's still an issue for matplotlib but it's experimental and was not within the scope of this PR).
