### ISSUE TITLE
doctest not excuting any tests

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1714]
## Motivation

doctest (`make doctest`) is run on CircleCI ([config.yml](https://github.com/optuna/optuna/blob/master/.circleci/config.yml)) but no tests are actually found/executed. Errors are therefore left undetected.

It seems like this started to occur after https://github.com/optuna/optuna/pull/1400.

#### Example

https://app.circleci.com/pipelines/github/optuna/optuna/2220/workflows/46d795b4-52dd-4ff5-b60c-8596c86a9ba1/jobs/54009

```
Doctest summary
===============
    0 tests
    0 failures in tests
    0 failures in setup code
    0 failures in cleanup code
build succeeded.
```

## Description

doctest should find and execute actual tests.

## Alternatives (optional)

If `make doctest` is run twice (or `make html` followed by `make doctest`) tests are found/executed. Looking up what `sphinx-build doctest` actually does might help.

**Comment by harupy** [comment]
Looks like `make doctest` doesn't seem to work properly without stub files genereated by `sphinx-autogen`.

**Comment by harupy** [comment]
> If make doctest is run twice (or make html followed by make doctest)

This is probably because the first `make doctest` generates stub files.
