### ISSUE TITLE
LightGBMTunerCV stepwise tuning got an error with lightgbm==3.0.0rc1

### ISSUE THREAD

**Issue by nyanhi** [optuna/optuna#1718]
`LightGBMTunerCV.run()` got LightGBMError after updating `lightgbm` version==`3.0.0rc1`. 
While it's performing stepwise tuning, `lightgbm.basic` raised below error message at the step of `min_data_in_leaf` and tuning is interrupted. 
A workaround seems to be adding `feature_pre_filter=false` like following as the error message suggests:
```
params = {
    "objective": "binary",
    "metric": "binary_logloss",
    "verbosity": -1,
    "boosting_type": "gbdt",
    "feature_pre_filter": False,
}
``` 
## Environment

- Optuna version: 2.0.0
- Python version: 3.7
- OS: linux/amd64 (Docker image: optuna/optuna:v2.0.0-py3.7)
- Lightgbm version: 3.0.0rc

## Error messages, stack traces, or logs

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/optuna/study.py", line 709, in _run_trial
    result = func(trial)
  File "/usr/local/lib/python3.6/dist-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 302, in __call__
    cv_results = lgb.cv(self.lgbm_params, self.train_set, **self.lgbm_kwargs)
  File "/usr/local/lib/python3.6/dist-packages/lightgbm/engine.py", line 554, in cv
    train_set._update_params(params) \
  File "/usr/local/lib/python3.6/dist-packages/lightgbm/basic.py", line 1436, in _update_params
    raise LightGBMError(decode_string(_LIB.LGBM_GetLastError()))
lightgbm.basic.LightGBMError: Reducing `min_data_in_leaf` with `feature_pre_filter=true` may cause unexpected behaviour for features that were pre-filtered by the larger `min_data_in_leaf`.
You need to set `feature_pre_filter=false` to dynamically change the `min_data_in_leaf`.
```

## Steps to reproduce

1. Update lightgbm to version==`3.0.0rc1`
2. Execute the example code in https://github.com/optuna/optuna/blob/master/examples/lightgbm_tuner_cv.py
3. The error occurs at 
https://github.com/optuna/optuna/blob/4680f36a470ffb9ead89abf65dcc7e7533fd789f/examples/lightgbm_tuner_cv.py#L24-L28

**Comment by toshihikoyanase** [comment]
The [reference of LightGBM 3.0](https://lightgbm.readthedocs.io/en/latest/Parameters.html#feature_pre_filter) suggests that we may need to turn `feature_pre_filter ` off when we tune `min_data_in_leaf`.

> you may need to set this to false when searching parameters with `min_data_in_leaf`, otherwise features are filtered by `min_data_in_leaf` firstly if you don’t reconstruct dataset object

It also suggests that we need to re-initialize the dataset objects if we turn on `feature_pre_filter`. I think it is difficult for `LightGBMTuner` to do it since they are initialized in the user code. So, IMO, `feature_pre_filter` should be turned off at the beginning of the LightGBM tuner procedure, for example, in the `LightGBMTuner.__init__`.

**Comment by mirekphd** [comment]
> It also suggests that we need to re-initialize the dataset objects if we turn on `feature_pre_filter`.

And @toshihikoyanase there are apparently more hyperparameteres that require following this suggestion - all so called "Dataset parameters" (e.g. `max_bin`). To quote StrikerRUS from [here](https://github.com/microsoft/LightGBM/issues/3346#issuecomment-687653696): "those parameters are stored in dataset object and cannot be changed in train/cv functions. You should create new dataset to change them."

**Comment by toshihikoyanase** [comment]
@mirekphd Thank you for your information about the dataset parameters. I read the [list](https://lightgbm.readthedocs.io/en/latest/Parameters.html#dataset-parameters) of them, but I'm not sure if they affect the tuning targets of `LightGBMTuner`. It tunes the following seven parameters, and do you think they are related to the dataset parameters?

- lambda_l1
- lambda_l2
- num_leaves
- feature_fraction
- bagging_fraction
- bagging_freq
- min_child_samples

**Comment by tangxianyu1988** [comment]
> The parameter "min_child_samples"'s another name is "min_data_in_leaf". So the error is that, if you want to tune the parameter "min_child_samples", you should  set feature_pre_filter=False
