### ISSUE TITLE
[Tracker] Improve Tutorial

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#1721]
This issue is not labeled "contribution-welcome", though, if you are interested in, don't be shy to contact me 😃

What I'm going to do in the next months as follows:

1. Align the contents of tutorials with the README's Key Features
2. Add https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html -ish thing
2. Add more contents as "Recipes". Some of the contents are
    - User-defined pruners
    - User-defined Optuna Callbacks
    - Human-in-the-loop optimization with Hyperparameter Importance
    - `enqueue_trial`
    - Introduction of multi-objective optimization

**Comment by crcrpar** [comment]
Follow up tasks

- merge https://github.com/crcrpar/optuna/tree/new-recipes once 1722 is landed.
- move this section https://optuna.readthedocs.io/en/stable/tutorial/002_configurations.html#note-on-the-number-of-parameters to somewhere like new "new to optuna" tutorials that might be the Englsih translation of @HideakiImamura 's great tutorials https://colab.research.google.com/github/pfnet-research/optuna-hands-on/blob/master/ja/01_Optuna_Quick_Start_ja.ipynb, https://colab.research.google.com/github/pfnet-research/optuna-hands-on/blob/master/ja/02_Optuna_Advanced_Tutorial_ja.ipynb.

**Comment by crcrpar** [comment]
Due to the unexpected ReadTheDocs build failure thanks to timeout or weird memory consumption, migrating to LightGbm https://github.com/optuna/optuna/pull/2076 tentatively but I wanna use some other platform such as GitHub Pages to host kind of "cool" PyTorch tutorial. The build time will not be problematic with GitHub Pages because we can make full use of cache in our GitHub Actions workflow.

**Comment by crcrpar** [comment]
There's one thing to do: Multi-objective. But I don't have any idea of better contents, except for using PyTorch.

**Comment by toshihikoyanase** [comment]
> There's one thing to do: Multi-objective.

I guess we can use LightGBM instead of PyTorch to mitigate the build time.

The following is just an example of multi-objective optimization for LightGBM. Some metrics like precision and recall show trade-off relationships. Then, we can apply multi-objective optimization to maximize both precision and recall simultaneously.
Practically, users may maximize the AUC and tune the threshold to valance the trade-off relationship, but I think it is simple and somewhat meaningful as an example.

What do you think?

![image](https://user-images.githubusercontent.com/3255979/105934153-fa8d7b80-6092-11eb-9d24-a239135d53d1.png)

https://colab.research.google.com/drive/1eTB_xGRErTExFngaS5jvJ04FH4MBX7Zl?usp=sharing#scrollTo=VpideloeI8JW

**Comment by toshihikoyanase** [comment]
I updated the mulit-objective optimization example using the [UCI Bank Marketing dataset](https://archive.ics.uci.edu/ml/datasets/Bank+Marketing).
It contains much more data samples than the breast cancer dataset, and it seems be more realistic. It takes about a minute to execute 40 trials in Google Colab. I think it fits RTD build time limitation.

```python
def conv_label(label):
    return int(label) - 1

data, target = datasets.fetch_openml("bank-marketing", return_X_y=True)
target = list(map(conv_label, target))
train_x, valid_x, train_y, valid_y = train_test_split(data, target, test_size=0.25)

def objective(trial):
    dtrain = lgb.Dataset(train_x, label=train_y)
    param = {
        "objective": "binary",
        "metric": "binary_logloss",
        "verbosity": -1,
        "boosting_type": "gbdt",
        "lambda_l1": trial.suggest_float("lambda_l1", 1e-8, 10.0, log=True),
        "lambda_l2": trial.suggest_float("lambda_l2", 1e-8, 10.0, log=True),
        "num_leaves": trial.suggest_int("num_leaves", 2, 256),
        "feature_fraction": trial.suggest_float("feature_fraction", 0.4, 1.0),
        "bagging_fraction": trial.suggest_float("bagging_fraction", 0.4, 1.0),
        "bagging_freq": trial.suggest_int("bagging_freq", 1, 7),
        "min_child_samples": trial.suggest_int("min_child_samples", 5, 100),
    }

    gbm = lgb.train(param, dtrain)
    preds = gbm.predict(valid_x)
    pred_labels = np.rint(preds)
    precision = precision_score(valid_y, pred_labels)
    recall = recall_score(valid_y, pred_labels)
    return precision, recall

study = optuna.create_study(directions=["maximize", "maximize"])
study.optimize(objective, n_trials=40)
```

https://colab.research.google.com/drive/1eTB_xGRErTExFngaS5jvJ04FH4MBX7Zl?usp=sharing

**Comment by crcrpar** [comment]
I added all I wanted, so close.
