### ISSUE TITLE
Does the optimization suggest_int consider best param and value on its optimization algorithm?

### ISSUE THREAD

**Issue by fsmosca** [optuna/optuna#1728]
Trying to optimize a chess queen value as a simple case using optuna's suggest_int. Basically one engine will take the optuna suggested param value call it optuna_engine and the other engine will take the available best param value call it best_engine. Then play some games and return the result from the point of view of optuna_engine. If optuna_engine wins or (score > 0.5), the best_param will be updated and will be used by best_engine for next trial. Optuna_engine will take new values from suggest_int. Then play some games again. See pseudo code below.

```python
best_param = {'queen': 200}
best_value = 0.25

def objective(trial):
    queen = trial.suggest_int('queen', 200, 1200)

    optuna_engine(queen)
    best_engine(best_param)

    # Returns match result from optuna engine perspective.
    # games = win + draw + loss
    # Result = (win + draw/2) / games
    result = match_engine(optuna_engine, best_engine, games=50)

    # If optuna_engine wins, above 50%, update the best_value and best_param.
    if result > 0.5:
        best_value = result
        best_param = queen

    return result

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=1000)
```

Sample tuning log:

### Trial 0 finished with value: 0.80 and parameters: {'Queen': 700}. Best is trial 0 with value: 0.80.

The optuna_engine won with 0.8 or 80% score. [optuna_engine(queen=700) vs best_engine(queen=200)]

At this point the best_engine will now use the best param queen=700, and not the initial 200.
Optuna suggested queen=800 for trial 1. Do the match and it won by a close margin, but above 50%.

### Trial 1 finished with value: 0.55 and parameters: {'Queen': 800}. Best is trial 0 with value: 0.80.

So optuna won again using queen=800, defeating best_engine using queen=700.
**The best param is now queen=800 with value 0.55.** But notice `Best is trial 0 with value 0.80.`

My question is does the optimizer consider queen=700 with value=0.80 as the best param and value on its optimization algorithm? Or the `Best is trial 0 with value 0.80` is just a message to the user?

Thank you for this great framework.

**Comment by toshihikoyanase** [comment]
Thank you for your question. It's an interesting application that optimizes the two-player game agents.

> My question is does the optimizer consider queen=700 with value=0.80 as the best param and value on its optimization algorithm?

Yes, Optuna treats `Trial 0` (queen=700 with value=0.80) as the best solution so far. In other words, Optuna considers `Trial 0` is better than `Trial 1`. This is because Optuna simply tries to maximize the returned values of the objective function, and the `Trial 0`'s value (0.80) is larger than `Trial 1`'s value (0.55).

IMO, Optuna requires a static objective function. For example, is it possible to use a fixed group of agents to evaluate the suggested agents? The following is just an example that maximizes the rate of winning against three agents (i.e., queen = (200, 600, 1200)):

```python
def objective(trial):
    queen = trial.suggest_int('queen', 200, 1200)

    optuna_engine(queen)
    results = []
    for benchmark_param in [200, 600, 1200]:
        best_engine(benchmark_param)
        result = match_engine(optuna_engine, best_engine, games=50)
        results.append(result)

    return np.mean(results)  # Return the mean of the rate of winning.
```

**Comment by fsmosca** [comment]
Thanks for your reply. Your suggestion of a static objective is indeed possible. One improvement could be to check the history of tuning on that particular param. Then choose those values which performed well in the past to become static.

Since the optimizer considers the high value, I thought of faking the result, that is from the given example at trial 0, instead of returning the correct result of 0.80 I will return 0.50 plus a small increment and remember this as best_value. Then at trial 1, if the optuna_engine wins again at say 0.55, I will return best_value plus increment. I could scale the increment based on the actual result. If the actual result is close to 1.0, its increment will be higher.

**Comment by fsmosca** [comment]
@HideakiImamura I plan to close this issue. Are you planning to do something about it?

**Comment by HideakiImamura** [comment]
@fsmosca It's OK to close this issue. Thanks.
