### ISSUE TITLE
trial.suggest_ordered_categorical

### ISSUE THREAD

**Issue by turian** [optuna/optuna#1736]
`trial.suggest_ordered_categorical` should allow you to sample over categoricals that have an ordering.

## Motivation

I have an optimization problem where there are a set of possible float values for one setting.
However, the distance between the points is not necessarily the floating point distance. Only the ranking is important (distance is monotonically increasing).

## Description

The following should work:

```
trial.suggest_ordered_categorical('floatvals', [0.0, 0.3, 0.7, 1.0])
```

And only categorical values should be suggested, but understanding that the order matters, but not the distance

## Alternatives (optional)

trial.suggest_float using the min and max.

trial.suggest_categorical but perhaps over 50 float values.

**Comment by hvy** [comment]
Thanks for your proposal. Wanting to suggest categoricals that are ordered makes sense but it would require some larger changes to the code base. The "suggest" methods combined with their arguments are defined by concrete `BaseDistrbution`s. In each sampler, for instance, we're conditioning based on which concrete `BaseDistribution` a parameter is to be suggested with. So with a naive approach, all samplers would have to be updated. If we are to proceed with this, it'll involve several design discussions first.

For your case, I assume that the distances between each categorical should be identical, but that the actual float values aren't distanced by the same step (if they were, you could use the `step` parameter of `suggest_float`). Could you perhaps use `suggest_int` to suggest indices to your sequence of choices instead?

**Comment by turian** [comment]
@hvy This is a good question. In my particular case, the distances between categories is actually unknown and might not correlate with the floating point distance. Just the rank order matters. I think what I actually want is `sample_ranked_list` and involve just the ranking.

**Comment by hvy** [comment]
Thanks for your quick reply. I'm unfortunately not that familiar with the practices of handling these types of ordinals and how it's done in other frameworks. If you have references, that would help a lot. Again, it sounds like `suggest_int` would do given the following, but I might be missing your point.

> distances between categories is actually unknown and might not correlate with the floating point distance. Just the rank order matters

**Comment by turian** [comment]
@hvy it appears that `suggest_int` (if you were to use it to suggest elements from a `sample_ranked_list`) would have the issue that it assumes there is a linear (or log) distance between each element.
