### ISSUE TITLE
import optuna.integration.lightgbm as lgb

### ISSUE THREAD

**Issue by Jie-Yuan** [optuna/optuna#1738]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-57-4d0f80b09927> in <module>
----> 1 import optuna.integration.lightgbm as lgb

~/anaconda3/lib/python3.7/site-packages/optuna/integration/lightgbm.py in <module>
      4 
      5 from optuna._imports import try_import
----> 6 from optuna.integration import _lightgbm_tuner as tuner
      7 
      8 

~/anaconda3/lib/python3.7/site-packages/optuna/integration/_lightgbm_tuner/__init__.py in <module>
      1 from typing import Any
      2 
----> 3 from optuna.integration._lightgbm_tuner.optimize import _imports as _imports
      4 from optuna.integration._lightgbm_tuner.optimize import LightGBMTuner
      5 from optuna.integration._lightgbm_tuner.optimize import LightGBMTunerCV  # NOQA

~/anaconda3/lib/python3.7/site-packages/optuna/integration/_lightgbm_tuner/optimize.py in <module>
    631 
    632 
--> 633 class LightGBMTuner(_LightGBMBaseTuner):
    634     """Hyperparameter tuner for LightGBM.
    635 

~/anaconda3/lib/python3.7/site-packages/optuna/integration/_lightgbm_tuner/optimize.py in LightGBMTuner()
    759         "1.4.0",
    760         text=(
--> 761             "Please get the best booster via "
    762             ":class:`~optuna.integration.lightgbm.LightGBMTuner.get_best_booster` instead."
    763         ),

~/anaconda3/lib/python3.7/site-packages/optuna/_deprecated.py in deprecated(deprecated_version, removed_version, name, text)
     75     _validate_version(deprecated_version)
     76     if removed_version is None:
---> 77         removed_version = _get_removed_version_from_deprecated_version(deprecated_version)
     78     _validate_version(removed_version)
     79     _validate_two_version(deprecated_version, removed_version)

~/anaconda3/lib/python3.7/site-packages/optuna/_deprecated.py in _get_removed_version_from_deprecated_version(deprecated_version)
     37     parsed_deprecated_version = version.parse(deprecated_version)
     38     assert isinstance(parsed_deprecated_version, version.Version)  # Required for mypy.
---> 39     return "{}.0.0".format(parsed_deprecated_version.major + 2)
     40 
     41 

AttributeError: 'Version' object has no attribute 'major'

**Comment by toshihikoyanase** [comment]
Hello @Jie-Yuan , thank you for your report.

> AttributeError: 'Version' object has no attribute 'major'

`packaging.version.Version.major` was included in `packaging>=20.0` https://github.com/pypa/packaging/pull/225, and I think you used an older version of `packaging` than `20.0`. 

Could you update the `packaging` library in your environment?

**Comment by Jie-Yuan** [comment]
thanks

**Comment by toshihikoyanase** [comment]
Let me close this issue since the problem has been resolved. Please feel free to reopen it or create a new issue if you have further problems.
