### ISSUE TITLE
Study and Trial for TensorFlow's MultiWorkerMirroredStrategy

### ISSUE THREAD

**Issue by sfujiwara** [optuna/optuna#1751]
## Motivation

It is useful for TensorFlow users if we have `DistributedTensorFlowStudy` and `DistributedTensorFlowTrial` like [`ChainerMNStudy`](https://github.com/optuna/optuna/blob/0b152e1774976ec056504f105aefeda9d674fc3b/optuna/integration/chainermn.py#L53) and [`ChainerMNTrial`](https://github.com/optuna/optuna/blob/0b152e1774976ec056504f105aefeda9d674fc3b/optuna/integration/chainermn.py#L143).

## Description

Distribute execution using TensorFlow + Horovod + MPI will be available when https://github.com/optuna/optuna/pull/1341 is merged.
However, TensorFlow has another official functional of [Distribute Strategies](https://www.tensorflow.org/guide/distributed_training).
As far as I investigated, using Optuna with TensorFlow's Distribute Strategies requires additional implementations.

### Why `MultiWorkerMirroredStrategy`

TensorFlow has some Distribute Strategies: https://www.tensorflow.org/guide/distributed_training#types_of_strategies
I think the main target is `MultiWorkerMirroredStrategy`.

- `MultiWorkerMirroredStrategy`
  - It handles multi workers and multi GPUs with All-Reduce like ChainerMN
- `MirroredStrategy` and `CentralStorageStrategy`
  - It assumes single worker and multi GPUs, that is, it does not require any additional implementations to use with Optuna
- `TPUStrategy`
  - It is quite unique and we need another issue if tackling the task
- `ParameterServerStrategy`
  - It is for multi worker training with parameter server
  - An implementation for `MultiWorkerMirroredStrategy` might work on it

### What to do

In `ChainerMNTrial` and `ChainerMNStudy`, they broadcast a value of rank 0 worker via MPI as:
https://github.com/optuna/optuna/blob/0b152e1774976ec056504f105aefeda9d674fc3b/optuna/integration/chainermn.py#L312-L326

**Because TensorFlow's distributed functionals are it own implementation and does not documented (it is not assumed to used by end users), we need to investigate the usage of them**.

For example, `broadcast_send` and `broadcast_recv` are here:
https://github.com/tensorflow/tensorflow/blob/eed8f6c0946cd229d9b749295dd02045271b066e/tensorflow/python/ops/collective_ops.py#L113-L120

### Related issues

- https://github.com/optuna/optuna/issues/1137

**Comment by toshihikoyanase** [comment]
Just FYI, but I think we have an alternative approach if we use `MirroredStorategy` instead of `MultiWorkerMirroredStrategy`. 

I read the [tutorial](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras), I found that the distributed part is wrapped with `with strategy.scope()`, but the other part seems to be executed sequentially.

I'm not familiar with TensorFlow distributed, I guess it focuses on the parallelization of forward-backward computation and we can reuse the sequential code for the other parts such as training loops and training callbacks.

If so, we can use Optuna without integration modules as follows:
```python
def objective(trial):
    n_hidden = trial.suggest_int("n_hidden", 32, 64)

    ...

    with strategy.scope():
        model = create_model(n_hidden)
        model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
                    optimizer=tf.keras.optimizers.Adam(),
                    metrics=['accuracy'])

    ...

    callbacks = [
        tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix,
                                        save_weights_only=True),
        optuna.integration.TFKerasPruningCallback(trial, "accuracy")
    ]

    model.fit(train_dataset, epochs=2, callbacks=callbacks)
    model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))
    eval_loss, eval_acc = model.evaluate(eval_dataset)
    return eval_acc

study = optuna.create_study()
study.optimize(objective, n_trials=100)
```

Keras example:
https://colab.research.google.com/drive/1YifYjA2HX9qO7JARsmKWI6OeIe0JIBJo?usp=sharing

Do you think if this approach is also applicable to `MultiWorkerMirroredStrategy`?

**Comment by toshihikoyanase** [comment]
I'm sorry for my carelessness, but I overlooked your comment.

> `MirroredStrategy` and `CentralStorageStrategy`
> It assumes single worker and multi GPUs, that is, it does not require any additional implementations to use with Optuna

https://github.com/optuna/optuna/issues/1751#issuecomment-683377269 confirmed that `MirroredStrategy' actually worked with Optuna without integration.
