### ISSUE TITLE
Add a summary of each module in the reference page.

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#1770]
# Motivation
If we add a summary of each module in [the reference page](https://optuna.readthedocs.io/en/latest/reference/index.html), readers will understand the concept of each module better. 

# What to do

It is better to add the following information:

1. [what] the definition of the module
    - e.g. The :mod:`~optuna.trial` module contains :class:`~optuna.trial.Trial` related classes and functions.
2. [why] the role of the module
    - e.g. so that Optuna users can define a custom objective function through the interfaces.
3. [how/where] how and where the module is used
    - e.g. This instance is passed to an objective function and provides interfaces to get parameter suggestion, manage the trial's state, and set/get user-defined attributes of the trial
4. [who/when] when Optuna users use the module
    - e.g. Basically, Optuna users only use it in their custom objective functions.

ref: [Add explanation for optuna.trial.](https://github.com/optuna/optuna/pull/1748/files)

Currently, there is no summary except the below checked module.

- [x] `optuna`
- [x] `optuna.cli`
- [x] `optuna.distributions`
- [x] `optuna.exceptions`
- [x] `optuna.importance`
- [x] `optuna.integration`
- [x] `optuna.logging`
- [ ] `optuna.multi_objective`
- [x] `optuna.pruners`
- [x] `optuna.samplers`
- [x] `optuna.storages`
- [x] `optuna.structs`
- [x] `optuna.study`
- [x] `optuna.trial`
- [x] `optuna.visualization`

**Comment by tktran** [comment]
Hi, I discovered this project while exploring potential projects for GSoC 2021 and made this first PR to try my hand at contributing. Looking forward to feedback. Thanks.

**Comment by toshihikoyanase** [comment]
The rest of the module is only `optuna.multi_objective`, but it will be deprecated from v2.4.0. So, I don't think it's necessary for us to update it. Let me close this issue.
