### ISSUE TITLE
Fix exception chaining all over the codebase

### ISSUE THREAD

**Issue by akihironitta** [optuna/optuna#1779]
I recently went over [PyTorch](https://github.com/pytorch/pytorch/pull/43836) and [Detectron2](https://github.com/facebookresearch/detectron2/pull/1945), suggesting a small fix in the way that Python 3's exception chaining is used.

As described in detail in [this article](https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with), exception chaining ([PEP 3134](https://www.python.org/dev/peps/pep-3134/)) can be used to make exceptions more user-friendly, and in that case, the syntax `raise new_exception from old_exception` needs to be used.

When `raise .. from ..` is used, there will be a line saying `The above exception was the direct cause of the following exception` between tracebacks. However, when implicitly chaining exceptions (meaning when `raise .. from ..` is not used), the message will be `During handling of the above exception, another exception occurred` which can confuse users.

Specifically, the following should be used in order to chain exceptions:
```python
try:
    something_which_raises_OldError
except OldError as e:
    raise NewError("A more user-friendly exception message.") from e 
```
instead of:
```python
try:
    something_which_raises_OldError
except OldError:
    raise NewError("A more user-friendly exception message.")
```

One example which needs to be fixed is:
https://github.com/optuna/optuna/blob/007336bd85e82222ac777564c7d208008379144e/optuna/pruners/_threshold.py#L14-L18

If this suggestion sounds good and reasonable, I'd be happy to PR! Let me know your thoughts on this!

**Comment by hvy** [comment]
Thanks for the suggestion, that sounds reasonable. PR is more than welcome!

Just for the record, we're using the `from ` in e.g. [`_imports.py`](https://github.com/optuna/optuna/blob/master/optuna/_imports.py#L86) so I believe it's a matter of consistency.

**Comment by akihironitta** [comment]
@hvy Just made #1781 ready for review. Could you have a look at the changes?

**Comment by hvy** [comment]
I'll have a look. Thanks for the very swift PR.
