### ISSUE TITLE
Silence optuna trial results

### ISSUE THREAD

**Issue by tyokota** [optuna/optuna#1789]
Is it possible to silence trial results and parameters? I'm not necessarily always interested in seeing the progress during training.

**Comment by toshihikoyanase** [comment]
Hi @tyokota!
You can suppress log by changing the verbosity level as follows:

```python
import optuna

optuna.logging.set_verbosity(optuna.logging.WARNING)
```

c.f., https://optuna.readthedocs.io/en/latest/faq.html#how-to-suppress-log-messages-of-optuna

**Comment by tyokota** [comment]
Mahalo!
