### ISSUE TITLE
How is the trial value calculated for RL jobs?

### ISSUE THREAD

**Issue by blurLake** [optuna/optuna#1792]
Hi, I have a question about how is the trial value (or perhaps the validation score) calculated, e.g., 
`
Trial 323 finished with value: 57.2591552734375 and parameters: {'gamma': 0.05, 'lr': 0.0002252244861681433, 'learning_starts': 100, 'batch_size': 100, 'buffer_size': 10000, 'train_freq': 1, 'tau': 0.1, 'policy_delay': 2, 'noise_type': 'ornstein-uhlenbeck', 'noise_std': 0.28100749015027093, 'net_arch': 'medium'}.
`
Especially, how is it calculated for an episodic RL job? Is there any document elaborating this? 

Thank you!

**Comment by hvy** [comment]
Thanks for reaching out. I'm not sure I've understood the question correctly, but the trial value is not calculated by Optuna. The value that Optuna logs, as in your example, is simply the value returned by the user-defined objective function. (This is what Optuna optimizes.) What this function returns is up to you, i.e. it could be the validation score of something else. 

I'm not that familiar with RL but my understanding is that you typically run several episodes within a single objective function evaluation. Perhaps, you're asking for how one should go about implementing the objective function with RL? There's an RL example https://github.com/optuna/optuna/tree/master/examples/rl that might shed some light.

**Comment by hvy** [comment]
Let me close this issue as resolved. Feel free to reopen as needed.
