### ISSUE TITLE
Hydra's plugin for Optuna sweeper

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#1799]
## Motivation

In optuna, the searched space of hyperparameters might be difficult to be changed from the command-line interface directly.
One solution is supposed to take both an upper bound and lower bound of hyperparameters from a CLI such as `argparse`. But, personally, I feel costly.

[Ax](https://ax.dev/) is a similar framework to Optuna, and it enables us to pass the range of searched space via [hydra](https://hydra.cc/)'s [ax sweeper](https://hydra.cc/docs/plugins/ax_sweeper/) plugin. Inspired this approach, I propose an Optuna's counterpart of ax sweeper.

## Description

I shall show an example of this proposed feature as follows. It is rough idea, so I'm happy to receive any feedback. The following example comes from [this tutorial](https://optuna.readthedocs.io/en/stable/tutorial/005_cli.html).

First, we define an optimised hyper-parameter, bounds, and a distribution in a YAML file, namely, `conf/config.yaml`.

```yaml
x:
    bounds: [-10, 10]
    distribution: uniform

# other hyper-parameters are also defined in the same file
```

This file is loaded as the hydra's config file. It might be great to define a pruning strategy, etc. in this config file.

---

Second, we define the objective function, namely, `objective.py`.

```python
def objective(sampled_hyper_params: Dict):
    x = sampled_hyper_params['x']
    return (x - 2) ** 2
```

`sampled_hyper_params` stores sampled values by using the previous config file.

---

Finally, we execute a command like `optuna study optimize` command (I'm not sure that this is a good way).

```bash
optuna hydra-study optimize objective.py conf/config.yaml # some option
```

Change searched space of `x` from CLI:

```bash
optuna hydra-study optimize objective.py conf/config.yaml x.bounds=1:2 x.distribution=log-uniform # -- some option
```

### Advantages of this feaure

In addition to the flexibility of change the searched space and distributions, hydra provides [multi-run](https://hydra.cc/docs/tutorials/basic/running_your_app/multi-run/#sweeper) feature that performs parallel optimisation per config. Thus it can make an optimisation faster if some hyper-parameters are sampled by using grid-search.

For example, when some user propose a new optimisation algorithm. In that case, the user compare the proposed algorithm and existing algorithms fairly. Thus the user only wants to sample hyper-parameters of each optimiser and selects optimiser by using grid-search instead of Optuna's sampling. 

## Alternatives (optional)

Hydra has a plugin directory, we can add optuna plugin there, not to optuna.

It might be too specifc usage, so it is unnecessary to support this proposed feature officially. Also, I think it is not necessary to use hydra framework to implement this feature; the essential of the feature request is to take hyperparameters's space from some config file and CLI.

I found a related issue (https://github.com/optuna/optuna/pull/475) that has been closed.

**Comment by toshihikoyanase** [comment]
Thank you for your interesting proposal.

> Ax is a similar framework to Optuna, and it enables us to pass the range of searched space via hydra's ax sweeper plugin. Inspired this approach, I propose an Optuna's counterpart of ax sweeper.

I just created a [demonstration of Optuna command-line interface](https://github.com/toshihikoyanase/hydra-optuna-sweeper). It employes a bit different approach from your proposal. Similarly to [`ax_sweeper`](https://hydra.cc/docs/plugins/ax_sweeper/) and [`nevergrad_sweeper`](https://hydra.cc/docs/plugins/nevergrad_sweeper), it implements Optuna sweeper as Hydra's sweeper plugin.

We can minimize a quadratic function

```python
from typing import Any

import hydra
from omegaconf import DictConfig


@hydra.main(config_path="conf", config_name="config")
def evaluate(cfg: DictConfig) -> Any:
    x = cfg.x
    y = cfg.y
    return (x - 2) ** 2 + y


if __name__ == "__main__":
    evaluate()
```

using the following command:

```console
python example/quadratic.py -m 'x=interval(-5.0, 5.0)' 'y=interval(1, 10)'
```


We may have some pros and cons to this approach:

Pros:
- Users can use Hydra sweeper's syntax to specify search space in both command-lines and YAML config files
- Code can be simple. It consists of only 153 lines. We can use many Hydra components such as command-line parser and experiment launcher

Cons:
- Needed to use private interface of `optuna.study.Study` (i.e., `Study._ask` and `Study._tell`)
- Maintenance of the plugin. It will be a separated repository from [`optuna/optuna`](https://github.com/optuna/optuna) like ax_sweeper and nevergrad_sweeper

This is just a prototype implementation and I'm not sure if it will actually help users. Please let me know if you have any comments and feedbacks.

**Comment by nzw0301** [comment]
@toshihikoyanase Awesome! Thank you for sharing your prototype implementation and your comment!  I agree with you. Someone needs to maintain `optuna_sweeper` under [`hydra/plugin`](https://github.com/facebookresearch/hydra/tree/master/plugins).

As you mentioned, this feature might not help optuna users. Users need to learn the usage of hydra as well. It requires additional cost to learning hydra has not been widely used by many users yet...

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for your comments. I just submitted a PR to the hydra repository. If you have any feedback, please let me know.
https://github.com/facebookresearch/hydra/pull/1132

**Comment by varun19299** [comment]
Does the older syntax of:

```
python example/quadratic.py -m 'x=-5.0:5.0 y=1:10
```

work here too?

**Comment by toshihikoyanase** [comment]
Thank you for your question. Unfortunately, it does not seem to support it. The command caused the following error. Do you have any difficulties to migrate the old syntax to the new one?

```console
$ python example/sphere.py --multirun x=-5.0:5.0 y=1:10 
Traceback (most recent call last):
  File "/Users/yanase/.pyenv/versions/hydra-optuna-sweeper/lib/python3.7/site-packages/hydra/_internal/utils.py", line 198, in run_and_report
    return func()
  File "/Users/yanase/.pyenv/versions/hydra-optuna-sweeper/lib/python3.7/site-packages/hydra/_internal/utils.py", line 358, in <lambda>
    overrides=args.overrides,
  File "/Users/yanase/.pyenv/versions/hydra-optuna-sweeper/lib/python3.7/site-packages/hydra/_internal/hydra.py", line 136, in multirun
    return sweeper.sweep(arguments=task_overrides)
  File "/Users/yanase/pfn/code/hydra/plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/optuna_sweeper.py", line 31, in sweep
    return self.sweeper.sweep(arguments)
  File "/Users/yanase/pfn/code/hydra/plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/_impl.py", line 178, in sweep
    trial._suggest(param_name, distribution)
  File "/Users/yanase/.pyenv/versions/hydra-optuna-sweeper/lib/python3.7/site-packages/optuna/trial/_trial.py", line 686, in _suggest
    elif distribution.single():
AttributeError: 'str' object has no attribute 'single'
```

**Comment by varun19299** [comment]
No, I currently don't have any issues with the new syntax. Sorry for not checking the updated docs or release notes: are there any advantages of the new syntax over the older one?

**Comment by toshihikoyanase** [comment]
> are there any advantages of the new syntax over the older one?

I'm not familiar with the old syntax, but I think the new syntax seems to be explicit and flexible. 

1. Explicitness
`1:10` might have ambiguity. For example, some users recognize it as `range(1, 10)` and the others may recognize it as `interval(1, 10)`. So, I prefer the new syntax, which explicitly specifies `range` or `interval`.

2. Flexibility
We can use tags to annotate metadata to customize the search space. For example, we can convert the parameter space to the log domain if we add the `log` tag like `tag(log, interval(1, 100))`.

For further information, please refer to the [hydra reference](https://hydra.cc/docs/next/advanced/override_grammar/extended/).

**Comment by varun19299** [comment]
Can the `load_if_exists` argument also be added to the implementation?

I think it goes in the `_impl.py` file.

**Comment by HideakiImamura** [comment]
[FYI] The Hydra Optuna sweeper plugin has been merged in Hydra and will be released in 1.0.5. https://pypi.org/project/hydra-optuna-sweeper/

**Comment by nzw0301** [comment]
Awesome! I really appreciate @toshihikoyanase  for your great work! Let me close this issue.

**Comment by omry** [comment]
Thanks for the awesome contribution @toshihikoyanase! I had no idea you are one of the core Optuna devs!

> Cons:
> Needed to use private interface of optuna.study.Study (i.e., Study._ask and Study._tell)

I think it's a small price to pay for an awesome integration.


> Maintenance of the plugin. It will be a separated repository from optuna/optuna like ax_sweeper and nevergrad_sweeper

You are very welcome to host it in the optuna reo if you like.
The downside is that it may be a bit less visible to Hydra users and that the Hydra team will not be able to make changes as Hydra evolves (which is the same difficulty you are now facing with _tell and _ask).
If you decide to go that way, I don't mind keeping the Optuna page in the Hydra website (as long as you can continue updating it :) ).

**Comment by toshihikoyanase** [comment]
@omry Thank you for your kind words!

>> Cons:
>> Needed to use private interface of optuna.study.Study (i.e., Study._ask and Study._tell)
>
>I think it's a small price to pay for an awesome integration.

Optuna v2.5.0 will make the ask-and-tell interface public, and I'll be able to resolve this issue. I'll send a PR after releasing v2.5.0.

> You are very welcome to host it in the optuna reo if you like.

Thanks.
Actually, I changed my mind, and I'd like to keep sending the PR to Hydra repository. I deeply appreciate your insightful code reviews, which significantly improved the plugin. It will be difficult for me to keep up with the evolution of Hydra without your help.

**Comment by omry** [comment]
> Optuna v2.5.0 will make the ask-and-tell interface public, and I'll be able to resolve this issue. I'll send a PR after releasing v2.5.0.

Sounds good!

> Actually, I changed my mind, and I'd like to keep sending the PR to Hydra repository. I deeply appreciate your insightful code reviews, which significantly improved the plugin. It will be difficult for me to keep up with the evolution of Hydra without your help.

Yeah, I think it makes sense. It's also great to have you on board with the plugin to keep it up to date with new development in Optuna (like multi-objective optimization)!
