### ISSUE TITLE
`visualization.plot_contour` with `suggest_categorical` that contains `None`

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#1834]
## Expected behavior

`visualization.plot_contour` shows an error if `params` contains a hyper-parameter that could be `None`.  But `choice` option of `suggest_categorical` can contain `None` as an element, so, I think users expect the plot functions perform in such a case.

I'm not sure that the other visualisation functions have a similar issue.

## Environment

- Optuna version: https://github.com/optuna/optuna/tree/a4237f087ec01bcd2c181d8a1a7d553d2292b7cf
- Python version: 3.8.3
- OS: MacOS 10.15.6

## Error messages, stack traces, or logs

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-c1f5a8612550> in <module>
     24 print(study.best_params, study.best_value)
     25 
---> 26 optuna.visualization.plot_contour(study, params=['l1_ratio', 'C'])

~/PycharmProjects/optuna/optuna/visualization/_contour.py in plot_contour(study, params)
     64 
     65     _imports.check()
---> 66     return _get_contour_plot(study, params)
     67 
     68 

~/PycharmProjects/optuna/optuna/visualization/_contour.py in _get_contour_plot(study, params)
     93     for p_name in sorted_params:
     94         values = [t.params[p_name] for t in trials if p_name in t.params]
---> 95         max_value = max(values)
     96         min_value = min(values)
     97         if _is_log_scale(trials, p_name):

TypeError: '>' not supported between instances of 'NoneType' and 'NoneType'
```

## Steps to reproduce

1. Run the following example

## Reproducible examples (optional)

```python
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

import optuna


rnd = np.random.RandomState(7)

X, y = load_iris(return_X_y=True)
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=rnd)

def objective(trial):
    l1_ratio = trial.suggest_categorical('l1_ratio', [None, 0.1])
    C = trial.suggest_float('C', 0., 7.)

    clf = LogisticRegression(l1_ratio=l1_ratio, C=C, random_state=0, solver="saga")
    clf.fit(X_train, y_train)
    return clf.score(X_valid, y_valid)

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=4)
print(study.best_params, study.best_value)

optuna.visualization.plot_contour(study, params=['l1_ratio', 'C'])
```

**Comment by HideakiImamura** [comment]
Thanks for raising an important issue! This is a critical bug. To address this issue, how about mapping the choices to its index arrays?

**Comment by nzw0301** [comment]
@HideakiImamura Thank you for your comment! It sounds great!

**Comment by nzw0301** [comment]
I guess this issue is not fixed yet. More precisely, the error message does not show anymore, but the plot looks broken.
I think #1929 fixes this issue, but the example code in this issue does not show any points on the plot now...
![Screenshot 2020-10-28 at 3 39 52](https://user-images.githubusercontent.com/7121753/97346796-403d7b00-18cf-11eb-952e-06cd5b89e01e.png)

**Comment by nzw0301** [comment]
I confirm this broken plot when I use plotly `4.9.0` and `4.12.0`. So it might not be related to https://github.com/optuna/optuna/issues/1967.

**Comment by nzw0301** [comment]
To show `None` in the y-axis of the example plot, we need to `figure.update_yaxes(type="category")` in 
https://github.com/optuna/optuna/blob/7a72d2ebe59bcad4aef67c879cc6e27aa2dc401e/optuna/visualization/_contour.py#L137-L140
But, https://github.com/optuna/optuna/blob/7a72d2ebe59bcad4aef67c879cc6e27aa2dc401e/optuna/visualization/_contour.py#L119 becomes `True` when all values are numerical. This is why `None` does not appear in the plot...

**Comment by nzw0301** [comment]
For example, if I replace the previous line with `update_category_axes[p_name] = any([str(v).isnumeric() or str(v) == "None" for v in set(values)])`, the example code outputs the following plot.

<img width="1013" alt="Screenshot 2020-10-28 at 16 17 48" src="https://user-images.githubusercontent.com/7121753/97404336-45cfab00-1939-11eb-9cce-d56a8ab92d05.png">

---
Note: Plotly version was `4.12.0`.

**Comment by nzw0301** [comment]
@crcrpar @HideakiImamura What do you think?

**Comment by toshihikoyanase** [comment]
I guess this is due to the use of `isnumeric` to detect numerical values.
According to the [reference](https://docs.python.org/3/library/stdtypes.html#str.isnumeric), `isnumeric` returns `False` if the string contain non-numeric characters such as `.` and `-`. In this case, `"0.1".isnumeric()` returns `False`.

> Return True if all characters in the string are numeric characters, and there is at least one character, False otherwise.

I checked alternative built-in functions but I couldn't find appropriate ones. How about checking if the value can be cast to float? When I used the following function, the plot was rendered as expected.

```python
def _is_numeric(s: str) -> bool:
    try:
        float(s)
        return True
    except ValueError:
        return False
```

![image](https://user-images.githubusercontent.com/3255979/97781713-94e33d80-1bd0-11eb-8ed7-3fcfb5c31d99.png)

**Comment by nzw0301** [comment]
@toshihikoyanase Looks great! Thank you for investigating the issue. I misunderstood the behaviour of `str.isnumerical` method... Could I send a PR to replace `isnumerical` in the plot function with `_is_numeric` suggested by you?

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for your comment. #1983 updates the same line, but it fixes the different issue which is introduced by plotly 4.12.0. So, I prefer a new PR to fix this issue so that we can trace the issue easily.
Your PR is more than welcome.

**Comment by nzw0301** [comment]
@toshihikoyanase I agree with you! I will create the PR after your PR (#1983) is merged!

**Comment by crcrpar** [comment]
Removed `stale` as this seems to be alive

**Comment by nzw0301** [comment]
Sorry, I'm busy nowadays. Could someone fix this issue instead of me?

Note that I'm not sure whether the related commit affects this issue or not.

**Comment by nzw0301** [comment]
I have checked this issue with the latest [optuna](https://github.com/optuna/optuna/tree/750ad3db162c139295434d90b458caeda76584aa) and `plotly==4.8.0`. The first code didn't output the same result due to the sampler, so I ran the following script:

```python
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

import optuna


rnd = np.random.RandomState(7)

X, y = load_iris(return_X_y=True)
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=rnd)

def objective(trial):
    l1_ratio = trial.suggest_categorical('l1_ratio', [None, 0.1])
    C = trial.suggest_float('C', 0., 7.)

    clf = LogisticRegression(l1_ratio=l1_ratio, C=C, random_state=0, solver="saga")
    clf.fit(X_train, y_train)
    return clf.score(X_valid, y_valid)

sampler = optuna.samplers.TPESampler(seed=9)
study = optuna.create_study(direction='maximize', sampler=sampler)
study.optimize(objective, n_trials=10)
print(study.best_params, study.best_value)

optuna.visualization.plot_contour(study, params=['l1_ratio', 'C'])
```

The plot has been still broken like https://github.com/optuna/optuna/issues/1834#issuecomment-717457537. 

However, the plot was good with `plotly==4.14.1`.

![newplot (1)](https://user-images.githubusercontent.com/7121753/101947621-1d271a80-3c34-11eb-9a89-9262fd2c35bf.png)
