### ISSUE TITLE
Is there anyway to disable the ExperimentalWarnings

### ISSUE THREAD

**Issue by Madman600** [optuna/optuna#1835]
I'm trying to output parameters for a multi objective study when a new best optimization is found but the ExperimentalWarnings are cluttering things up. Is there any way to turn these off whilst still keeping other log output?

**Comment by c-bata** [comment]
Hi @Madman600. I guess you can use `warnings.filterwarnings()` like:

```python
warnings.filterwarnings("ignore", category=ExperimentalWarnings, module="optuna.multi_objective")
```

https://docs.python.org/3/library/warnings.html#warnings.filterwarnings

**Comment by Madman600** [comment]
Thanks. How can I turn logging for optuna off completely?

**Comment by Madman600** [comment]
Never mind I figured it out, I was calling disable_default_handler in a method where I create my logger instead of when the module is executed initially.

**Comment by Lisimo0103** [comment]
> For others like me, you'll also need to add this `from optuna.exceptions import ExperimentalWarning`

But I meet the error: ModuleNotFoundError: No module named 'optuna.exceptions', why?

**Comment by nabenabe0928** [comment]
@Lisimo0103 
That's  because it's not a warning, but an error.
Could you provide your code to reproduce your issue?
