### ISSUE TITLE
How to resolve `error: Cannot assign to a type` in `mypy`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#1846]
In PR #1804, to address the `error: Cannot assign to a type` issue for `optuna/integration/chainer.py:13:`, I just add `# type: ignore`.
```python
if not _imports.is_successful():
    Extension = object  # type: ignore # NOQA
```
However, as pointed by @toshihikoyanase in #1804, there are the same substitutions in other places such as
```python
# In optuna/integration/keras.py
if not _imports.is_successful():
    Callback = object  # NOQA

# In optuna/integration/allennlp.py
if _imports.is_successful():
    import _jsonnet
else:
    EpochCallback = object  # NOQA
```
These substitutions do not raise any `mypy` errors.

## Expected behavior

There are two possibilities to addres
1. We can remove `# type: ignore` from `optuna/integration/chainer.py` by some fixes.
2. We have to add `#type: ignore` to `optuna/integration/{keras.py, allennlp.py}`, indeed.

We would like to clarify why the `mypy` error occurs in `optuna/integration/chainer.py` but does not in `optuna/integration/{keras.py, allennlp.py}`.

## Environment

- Optuna version: https://github.com/optuna/optuna/commit/5f4109020ef280eccf66db6db591892ae8aa2b2a and https://github.com/optuna/optuna/commit/ed661d57d450169cf45113d8463d3a65c56c19fe
- Python version: 3.8.5
- OS: macOS Catalina 10.15.6
- (Optional) Other libraries and their versions: mypy 0.782

## Error messages, stack traces, or logs
In https://github.com/optuna/optuna/commit/5f4109020ef280eccf66db6db591892ae8aa2b2a (before #1804 has been merged),

1. `git checkout 5f4109020ef280eccf66db6db591892ae8aa2b2a`
2. `pip install -e ".[testing]"`
3. `mypy .`
```
...
optuna/integration/chainer.py:13: error: Cannot assign to a type
...
Found 20 errors in 6 files (checked 190 source files)
```

In https://github.com/optuna/optuna/commit/ed661d57d450169cf45113d8463d3a65c56c19fe (after #1804 has been merged),

1. `git checkout ed661d57d450169cf45113d8463d3a65c56c19fe`
2. `pip install -e ".[testing]"`
3. `mypy .`
```
Success: no issues found in 202 source files
```

**Comment by junjunjunk** [comment]
> We would like to clarify why the mypy error occurs in optuna/integration/chainer.py but does not in optuna/integration/{keras.py, allennlp.py}.

Perhaps it's an implementation problem on the mypy side?
[mypy's issue 1152](https://github.com/python/mypy/issues/1152) seems to be related to this issue.
mypy's issue is still open. Sorry if I'm out of line.
