### ISSUE TITLE
CmaEsSampler support for direction='maximize'

### ISSUE THREAD

**Issue by brunofacca** [optuna/optuna#1848]
Thank you for this great library.

I may be missing something, but it seems that `optuna.samplers._cmaes.CmaEsSampler` lacks support for `direction='maximize'` and that that is not documented anywhere.

## Expected behavior

When `direction='maximize'` is passed to `optuna.create_study`, `CmaEsSampler` should try to maximize the objective.

## Environment

- Optuna version: 2.1.0
- Python version: 3.8.5
- OS: Ubuntu 20.04

## Steps to reproduce

1. Use the code below
2. Watch as TPESampler consistently improves (increases) the objective then, after the sampler is switched to  CmaEsSampler, watch it as it consistently worsens (decreases) the objective.

Maybe `direction='maximize'` is working properly in `CmaEsSampler` and it just didn't do well with my use case, but I'm using MCC as a metric and it consistently reduced the MCC up to the point of having a significant *negative* score, which indicates a negative correlation between the predictions and the actual labels of the validation data (it does not seem like a coincidence).

Additionally, I've looked at [the CmaEsSampler source](https://github.com/optuna/optuna/blob/master/optuna/samplers/_cmaes.py) and was unable to locate any code used to handle `direction='maximize'`. Maybe I've missed something, but I could clearly find such code in the [TPESampler source](https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L625). 

## Reproducible examples (optional)

```python
    study = optuna.create_study(sampler=TPESampler(), direction='maximize')
    study.optimize(
        objective_to_maximize,
        timeout=timeout_seconds*0.5,
        show_progress_bar=True,
        n_jobs=-1
    )

    study.sampler = CmaEsSampler(
        restart_strategy='ipop',
        consider_pruned_trials=True,
        independent_sampler=TPESampler(),
        warn_independent_sampling=False
    )
    study.optimize(
        objective_to_maximize,
        timeout=timeout_seconds*0.5, 
        show_progress_bar=True,
        n_jobs=1
    )

```

**Comment by c-bata** [comment]
Oh... Thank you. You are completely right.
I opened https://github.com/optuna/optuna/pull/1849 to fix this bug.
