### ISSUE TITLE
`warm_start` support for sklearn early stopping

### ISSUE THREAD

**Issue by Yard1** [optuna/optuna#1851]
## Motivation

Optuna sklearn integration (`OptunaSearchCV`) already provides support for early stopping if the estimator supports the `partial_fit` method. However, some estimators support `warm_start` param instead. If that param is set to True, subsequent calls to `fit` will reuse the results of previous `fit` as initialization, thus making it suitable for early stopping. This would expand the pool of sklearn estimators that can benefit from early stopping, speeding up tuning.

## Description

Support for this feature would involve adding detection of whether `warm_start` param is present and set to True (alternatively, `OptunaSearchCV` may set to to True itself if `early_stopping` is True. That may be a better solution), and then implementing similar early stopping logic as is already implemented for `partial_fit`.

I would be happy to work on this.

**Comment by toshihikoyanase** [comment]
Hi @Yard1 ,
Thank you for your suggestion. I've never know that some major estimators including [LogisticRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression), [`SGDClassifier`](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.SGDClassifier.html) and [`GradientBoostingClassifier`](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html#sklearn.ensemble.GradientBoostingClassifier) support `warm_start`.

Your idea to use the `warm_start` to accelerate the early stopping is interesting, but I guess we might have alternative approaches. For example, how about reusing the existing early stopping implementation?

Please take a look at the following example. I also created a [Colab notebook](https://colab.research.google.com/drive/1wWYe79PdgeXptBefZJ30jku9ECQIK_by?usp=sharing), so please try it. It trains a `SGDClassifier` model in 100 iterations. It executes the first ten iterations with the whole dataset and applies `OptunaSearch` to the rest of 90 iterations. I think this example is quite artificial, but we can find similar use cases if users have existing models and want to fine-tune them. 

Do you think this approach works for your use case?

```python
from sklearn.datasets import load_iris
from sklearn.linear_model import SGDClassifier
from sklearn.metrics import accuracy_score

import optuna


clf = SGDClassifier(warm_start=True, max_iter=10)

param_distributions = {
    "alpha": optuna.distributions.LogUniformDistribution(1e-9, 1e-1),
}

optuna_search = optuna.integration.OptunaSearchCV(
    clf, param_distributions, n_trials=100, timeout=600, verbose=2,
    enable_pruning=True, max_iter=90,
)

X, y = load_iris(return_X_y=True)
clf.fit(X, y)
preds = clf.predict(X)
print(accuracy_score(y, preds))

optuna_search.fit(X, y)

print("Best trial:")
trial = optuna_search.study_.best_trial

print("  Value: ", trial.value)
print("  Params: ")
for key, value in trial.params.items():
    print("    {}: {}".format(key, value))
```

**Comment by Yard1** [comment]
From what I can gather by reading the code, pruning is facilitated through calling `partial_fit` in estimators that support it. In almost every case, using `partial_fit` like that would be equivalent to using `fit` on warm start estimators. However, not every warm start estimator provides `partial_fit`. If Optuna was to check whether the estimator has the warm start param, it could prune those estimators. This behavior is also present in other tuning libraries, like tune-sklearn.

**Comment by toshihikoyanase** [comment]
Thank you for your comment. I understand. You would like to provide an early stopping feature to the estimators that do not support `partial_fit`. I'm sorry, but I completely missed the point in the previous comment.

So, the usage will be like this:

```python
    clf = LogisticRegression()

    param_distributions = {
        "C": optuna.distributions.LogUniformDistribution(1e-9, 1e-1),
    }

    optuna_search = optuna.integration.OptunaSearchCV(
        clf, param_distributions, n_trials=100, timeout=600, verbose=2,
        enable_pruning=True, max_iter=80,  # Note that LogisticRegression does not have `partial_fit`.
    )

    X, y = load_iris(return_X_y=True)
    optuna_search.fit(X, y)

    print("Best trial:")
    trial = optuna_search.study_.best_trial

    print("  Value: ", trial.value)
    print("  Params: ")
    for key, value in trial.params.items():
        print("    {}: {}".format(key, value))

```

I think the implementation is not so heavy. We can basically replace `partial_fit` in the `_partial_fit_and_score` method with an increment of `max_iter` and `fit`.

https://github.com/optuna/optuna/blob/1460301694ec41e9018f8518d3ea8a5350d585af/optuna/integration/sklearn.py#L311-L313

The following is the rough sketch of the implementation.

```python
        try:
            if hasattr(estimator, "warm_start"):
                estimator.set_params(warm_start=True, max_iter=previous+1)
                estimator.fit(X_train, y_train, **partial_fit_params)
            else:
                estimator.partial_fit(X_train, y_train, **partial_fit_params)

```

I think this feature is useful, and I'd like to hear the opinion of the other developers.
@Y-oHr-N Do you have any comments on this feature?

**Comment by Yard1** [comment]
Yes, this is precisely what I had in mind.

**Comment by Yard1** [comment]
@toshihikoyanase Additionally, for ensemble models, `n_estimators` could be used with `warm_start`.

**Comment by Y-oHr-N** [comment]
Sorry for late reply.

I also think this feature is useful.

I have listed estimators that have `partial_fit` or `warm_start` to see if @toshihikoyanase's  rough sketch can be realized.
His rough sketch can be applied to all estimators except `GaussianProcessClassifier` and `GaussianProcessRegressor`.

| class_name                                 | partial_fit | warm_start | max_iter | n_estimators |
|--------------------------------------------|-------------|------------|----------|--------------|
| cluster.Birch                              | x           |            |          |              |
| cluster.MiniBatchKMeans                    | x           |            | x        |              |
| decomposition.IncrementalPCA               | x           |            |          |              |
| decomposition.LatentDirichletAllocation    | x           |            | x        |              |
| decomposition.MiniBatchDictionaryLearning  | x           |            |          |              |
| ensemble.BaggingClassifier                 |             | x          |          | x            |
| ensemble.BaggingRegressor                  |             | x          |          | x            |
| ensemble.ExtraTreesClassifier              |             | x          |          | x            |
| ensemble.ExtraTreesRegressor               |             | x          |          | x            |
| ensemble.GradientBoostingClassifier        |             | x          |          | x            |
| ensemble.GradientBoostingRegressor         |             | x          |          | x            |
| ensemble.HistGradientBoostingClassifier    |             | x          | x        |              |
| ensemble.HistGradientBoostingRegressor     |             | x          | x        |              |
| ensemble.IsolationForest                   |             | x          |          | x            |
| ensemble.RandomForestClassifier            |             | x          |          | x            |
| ensemble.RandomForestRegressor             |             | x          |          | x            |
| ensemble.RandomTreesEmbedding              |             | x          |          | x            |
| feature_selection.SelectFromModel          | x           |            |          |              |
| gaussian_process.GaussianProcessClassifier |             | x          |          |              |
| gaussian_process.GaussianProcessRegressor  |             | x          |          |              |
| linear_model.ElasticNet                    |             | x          | x        |              |
| linear_model.GammaRegressor                |             | x          | x        |              |
| linear_model.HuberRegressor                |             | x          | x        |              |
| linear_model.Lasso                         |             | x          | x        |              |
| linear_model.LogisticRegression            |             | x          | x        |              |
| linear_model.MultiTaskElasticNet           |             | x          | x        |              |
| linear_model.MultiTaskLasso                |             | x          | x        |              |
| linear_model.PassiveAggressiveClassifier   | x           | x          | x        |              |
| linear_model.PassiveAggressiveRegressor    | x           | x          | x        |              |
| linear_model.Perceptron                    | x           | x          | x        |              |
| linear_model.PoissonRegressor              |             | x          | x        |              |
| linear_model.SGDClassifier                 | x           | x          | x        |              |
| linear_model.SGDClassifier                 | x           | x          | x        |              |
| linear_model.TweedieRegressor              |             | x          | x        |              |
| mixture.BayesianGaussianMixture            |             | x          | x        |              |
| mixture.GaussianMixture                    |             | x          | x        |              |
| multiclass.OneVsOneClassifier              | x           |            |          |              |
| multiclass.OneVsRestClassifier             | x           |            |          |              |
| multioutput.MultiOutputClassifier          | x           |            |          |              |
| multioutput.MultiOutputRegressor           | x           |            |          |              |
| naive_bayes.BernoulliNB                    | x           |            |          |              |
| naive_bayes.CategoricalNB                  | x           |            |          |              |
| naive_bayes.ComplementNB                   | x           |            |          |              |
| naive_bayes.GaussianNB                     | x           |            |          |              |
| naive_bayes.MultinomialNB                  | x           |            |          |              |
| neighbors.NeighborhoodComponentsAnalysis   |             | x          | x        |              |
| neural_network.MLPClassifier               | x           | x          | x        |              |
| neural_network.MLPRegressor                | x           | x          | x        |              |
| preprocessing.MaxAbsScaler                 | x           |            |          |              |
| preprocessing.MinMaxScaler                 | x           |            |          |              |
| preprocessing.StandardScaler               | x           |            |          |              |

**Comment by Yard1** [comment]
Furthermore, lightgbm, xgboost and Catboost can also be used in a similar manner by saving the fitted booster object and then using it as an init model for the next fit, with `n_estimators` increased.

**Comment by Y-oHr-N** [comment]
`LGBMClassifier` and `LGBMRegressor` construct a Dataset instance internally each time `fit` is called.
This process can be very time consuming if the dataset is very large, so it is better to use `LightGBMTunerCV`.
