### ISSUE TITLE
example for a custom wrapper on lightgbm.fit or .train with pruning

### ISSUE THREAD

**Issue by mirekphd** [optuna/optuna#1852]
I try to integrate Optuna pruners with our custom cross-validation function (a wrapper on `lightgbm.fit()`) to which I try to pass an `optuna.integration.LightGBMPruningCallback` instance via its `callbacks` argument, but then I get this error:

```
/opt/conda/lib/python3.8/site-packages/optuna/integration/lightgbm.py in __call__(self, env)
    118             return None
    119 
--> 120         raise ValueError(
    121             'The entry associated with the validation name "{}" and the metric name "{}" '
    122             "is not found in the evaluation result list {}.".format(

ValueError: The entry associated with the validation name "valid_0" and the metric name "auc" is not found in the evaluation result list [('oof', 'auc', 0.9398809523809524, True)].
```

The call sequence is: 
```
study.optimize(objective_instance) -> Objective_custom.__call__(self, trial) -> custom_wrapper(.. , callbacks=[lgbm_pruning_callback]) -> lightgbm.fit(callbacks=callbacks)
```

with `lgbm_pruning_callback = optuna.integration.LightGBMPruningCallback(trial, self.metric)` created inside `Objective_custom.__call__()` before the call to `custom_wrapper` .

Note it works fine without our wrapper (when passing callbacks directly to standard `lightgbm.cv`).

**Comment by toshihikoyanase** [comment]
Hi @mirekphd 

The following message suggests that you use the custom `valid_name` (i.e., `oof`).

> ValueError: The entry associated with the validation name "valid_0" and the metric name "auc" is not found in the evaluation result list [('oof', 'auc', 0.9398809523809524, True)].

I think the pruner can find the metric value if you specify it at `LightGBMPruningCallback.__init__`  as follows:

```python
lgbm_pruning_callback = LightGBMPruningCallback(trial, metric="auc", valid_name="oof")
```

**Comment by mirekphd** [comment]
Thank you so much for the answer! I went back to our custom objective function and added `valid_name` argument to the existing line `lgbm_pruning_callback = LightGBMPruningCallback(trial, metric=self.metric)`.

I set `valid_name` to the value reported in the above error message (i.e. `LightGBMPruningCallback(.., valid_name="oof"`) and then pruning ( `HyperbandPruner` to be more specific) started co-operating correctly with our custom cross-validation function!:) 

Metrics are similar to those obtained with benchmark CV function (`lightgbm.cv()`), and study completion times finally reduced too (without pruning study completion times for our custom CV function were several times slower than for the benchmark).

More info:
```
Training until validation scores don't improve for 45 rounds
[..]
[I 2020-09-23 09:50:46,919] Trial 1 pruned. Trial was pruned at iteration 10.
[..]
[I 2020-09-23 09:50:47,386] Trial 3 pruned. Trial was pruned at iteration 90.
[..]
[I 2020-09-23 09:50:47,669] Trial 6 pruned. Trial was pruned at iteration 10.
[..]
[I 2020-09-23 09:50:48,766] Trial 29 pruned. Trial was pruned at iteration 30.
```

**Comment by toshihikoyanase** [comment]
> pruning ( HyperbandPruner to be more specific) started co-operating correctly with our custom cross-validation function!

That's great! I'm glad that I could help.

I think your issue was resolved and could you close the issue?
If you have further questions, please feel free to re-open it or create a new one.

**Comment by mirekphd** [comment]
Sure, I will now close the issue, thank you again for excellent and quick answer! 

The "example" I mentioned in this Issue title I will try to add over the weekend as a PR to your extensive collection of examples, so that others with custom CV functions could benefit from it.

**Comment by bs1119** [comment]
can you post your custom CV functions? I'd like to do pruning on Pytorch-cross-validation. 

Thanks.

**Comment by bs1119** [comment]
@mirekphd: can you post your custom CV functions? I'd like to do pruning on Pytorch-cross-validation.

Thanks.

**Comment by mirekphd** [comment]
> post your custom CV functions? I'd like to do pruning on Pytorch-cross-validation.
Sorry to keep you waiting, can't post production code here, but will prepare a reproducible example for Optuna's examples library as soon as I find some time (this weekend is going to be more free than the last one...)
