### ISSUE TITLE
Metric MAPE direction should be reversed with reference to MAP

### ISSUE THREAD

**Issue by dileepbapat** [optuna/optuna#1858]
https://github.com/optuna/optuna/blob/9fc26c2277b347788d5554dad66dba81585716b2/optuna/integration/_lightgbm_tuner/optimize.py#L146

**Comment by toshihikoyanase** [comment]
Thank you for your question. `MAPE` stands for the mean absolute percentage error, and I think it is to be minimized  as can be seen in the LightGBM code:

https://github.com/microsoft/LightGBM/blob/2870490073c537eeb3648893257be8692b63148c/R-package/R/metrics.R#L13

>.METRICS_HIGHER_BETTER <- function() {
> ...
>         , "mape" = FALSE

Please let me know if I miss your point.

**Comment by di1** [comment]
Yes it is there in LGBM, however integration in optuna/optuna/integration/_lightgbm_tuner/optimize.py (146) has starts with in the if preventing mape based optimization. It tries to increase error when we optimize using tuner.

**Comment by toshihikoyanase** [comment]
@di1 Sorry for the delayed response.

> It tries to increase error when we optimize using tuner.

Could you share the log messages and reproducible code? I think the `LightGBMTuner` tried to minimize the error, but it failed for some reason.

**Comment by toshihikoyanase** [comment]
@dileepbapat @di1 
I'm sorry but I didn't get the point. Now, I find the cause and I submitted #1966 to fix this issue.
If you have any comments, please let me know.
