### ISSUE TITLE
Lightgbm tuner progress bar on jupyter lab

### ISSUE THREAD

**Issue by natthawute** [optuna/optuna#1859]
Hi,

I tried using optuna with the following code
```
params = {
        "objective": "binary",
        "metric": "binary_logloss",
        "verbosity": -1,
        "boosting_type": "gbdt",
}
model = lgb.train(params, dtrain, valid_sets=[dtrain, dval], verbose_eval=False, early_stopping_rounds=100)
```
and got the following progress bar result.
![image](https://user-images.githubusercontent.com/756351/94128388-17236800-fe95-11ea-94b4-a8f9dc4608df.png)

The progress bar seems to create a new line every time it gets updated.
Is this expected ? Should I look into other settings?

Also, can I use the html progress bar in jupyter lab like the following picture?
![image](https://user-images.githubusercontent.com/756351/94128843-96b13700-fe95-11ea-9240-8d835ccb4f72.png)

Best Regards,

**Comment by toshihikoyanase** [comment]
Thank you for your question.
I guess the logs of Optuna prevent `tqdm` from overwriting the progress bar. Could you suppress the Optuna logs by adding the `verbosity=0` option?

```python
model = lgb.train(
    params, dtrain,
    valid_sets=[dtrain, dval],
    early_stopping_rounds=100,
    verbose_eval=False,
    verbosity=0  # Add this option.
)

```

**Comment by natthawute** [comment]
Thank you for your reply. 
I tried that option but it doesn't seem to change.
I also tried `optuna.logging.set_verbosity(0)`, but it also didn't change the result.

Another thing I observed is that when run lgb.train multiple times the new line seems to keep growing.
![image](https://user-images.githubusercontent.com/756351/94224762-37533580-ff2e-11ea-9477-51656f1203ca.png)
I'm not sure if it should be considered as a bug though.

**Comment by toshihikoyanase** [comment]
Thank you for your quick reply.
Hmm, I've never heard of it. I guess these phenomena are environment-dependent.
Could you tell us the version of jupyterlab, lightgbm, and optuna?

**Comment by natthawute** [comment]
Sure. the versions are:
lightgbm==3.0.0
optuna==2.1.0
jupyterlab==1.2.17

**Comment by natthawute** [comment]
The problem seems to exist only when I interrupt the kernel during the execution.
If I restart the kernel and run the cell without normally, I can get the expected result.
![image](https://user-images.githubusercontent.com/756351/94226850-9d8e8700-ff33-11ea-988f-26a7fcd40f46.png)

So this will work for now. just want to confirm that the html progress bar isn't supported yet, correct?

**Comment by toshihikoyanase** [comment]
Thank you for your investigation.

> The problem seems to exist only when I interrupt the kernel during the execution.
> So this will work for now.

That's great. I still wondering why the irrelevant blank lines are added, but we have the workaround for the issue now.

> just want to confirm that the html progress bar isn't supported yet, correct?

You're right. The current LGBM tuner does not use jupyter integration, and I don't think it supports the HTML progress bar.

**Comment by natthawute** [comment]
I see. Thank you very much for your support!
