### ISSUE TITLE
how to save 'optuna.study'

### ISSUE THREAD

**Issue by Jie-Yuan** [optuna/optuna#1862]
I DO:
```
import joblib
joblib.dump(study, 'study.pkl')
```
BUT:
```
study = joblib.load('study.pkl'))
study.trials # error
```
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/IPython/core/formatters.py in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in pretty(self, obj)
    383                 if cls in self.type_pprinters:
    384                     # printer registered in self.type_pprinters
--> 385                     return self.type_pprinters[cls](obj, self, cycle)
    386                 else:
    387                     # deferred printer

/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in inner(obj, p, cycle)
    561                 p.text(',')
    562                 p.breakable()
--> 563             p.pretty(x)
    564         if len(obj) == 1 and type(obj) is tuple:
    565             # Special case for 1-item tuples.

/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in pretty(self, obj)
    400                         if cls is not object \
    401                                 and callable(cls.__dict__.get('__repr__')):
--> 402                             return _repr_pprint(obj, self, cycle)
    403 
    404             return _default_pprint(obj, self, cycle)

/usr/local/lib/python3.6/dist-packages/IPython/lib/pretty.py in _repr_pprint(obj, p, cycle)
    695     """A pprint that just redirects to the normal repr function."""
    696     # Find newlines and replace them with p.break_()
--> 697     output = repr(obj)
    698     for idx,output_line in enumerate(output.splitlines()):
    699         if idx:

/usr/local/lib/python3.6/dist-packages/optuna/trial/_frozen.py in __repr__(self)
    118                     value=repr(getattr(self, field)),
    119                 )
--> 120                 for field in self._ordered_fields
    121             ),
    122         )

/usr/local/lib/python3.6/dist-packages/optuna/trial/_frozen.py in <genexpr>(.0)
    118                     value=repr(getattr(self, field)),
    119                 )
--> 120                 for field in self._ordered_fields
    121             ),
    122         )

AttributeError: 'FrozenTrial' object has no attribute 'number'

**Comment by fsmosca** [comment]
In the [sample tutorial](https://optuna.readthedocs.io/en/stable/tutorial/003_rdb.html#rdb) you need to define `study_name`.

```
import optuna
study_name = 'example-study'  # Unique identifier of the study.
study = optuna.create_study(study_name=study_name, storage='sqlite:///example.db')
```

**Comment by tohmae** [comment]
We forgeted to set storage option in optuna.create_study and optimized several times.
After that if we want to save study and optimize, I think that it is better to do the following.

before:
```
import optuna
from optuna import trial

def objective(trial):
    ...
study = optuna.create_study()
study.optimize(objective, n_trials=10)
```

after:
```
save_study = optuna.create_study(study_name="example-study", storage="sqlite:///example.db'")
save_study.add_trials(study.trials)
# reload study
study = optuna.load_study(study_name="example-study", storage="sqlite:///example.db")
study.optimize(objective, n_trials=30)
```

**Comment by fsmosca** [comment]
In the [game parameter optimizer](https://github.com/fsmosca/Optuna-Game-Parameter-Tuner/blob/7227da41e63cad5bef87a10ac17cbad6dd02ff29/tuner.py#L733) that I did, I use the load_if_exist parameter.
