### ISSUE TITLE
Refererence missing :module:s

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#1871]
As in https://optuna.readthedocs.io/en/stable/reference/visualization.html, references to `module` directives like ``` :mod:`~optuna.visualization` ``` are not working in the current documentation.

The reason is that there are no `module` definitions in docs/source/reference/**/*.rst files (This change was made in #1400 with the conjunction of the introduction of autosummary).

Worse, CI has not detected this problem (I want CI to have told us this...).

**Comment by keisuke-umezawa** [comment]
I will work on it.
