### ISSUE TITLE
Improve ThresholdPruner example

### ISSUE THREAD

**Issue by fsmosca** [optuna/optuna#1874]
The variable `n_trial_step` in [Threshold Pruner](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.pruners.ThresholdPruner.html) is not used.

**Comment by hvy** [comment]
Good catch, we can remove the variable altogether. It must have slipped away when this comment was addressed https://github.com/optuna/optuna/pull/963#discussion_r390683096. Would you be interested in sending a PR? Let me label this as contribution welcome.
