### ISSUE TITLE
Pruning example for cross-validation using Pytorch 

### ISSUE THREAD

**Issue by bs1119** [optuna/optuna#1875]
I usually train models on n-fold CV, and use the averaged n-fold metrics as the objective value. 
So, I am wondering if there is an example to show how to use PruningCallback for cross-validation in Pytorch? Or, even a PruningCallback for Pytorch training? 

Thanks.

**Comment by hvy** [comment]
Do you mean any of the integration callback modules such as the one for PyTorch Lightning?

**Comment by bs1119** [comment]
> Do you mean any of the integration callback modules such as the one for PyTorch Lightning?
It would be good if there is an example of PruningCallback for n-fold CV example for Pytorch.   
The one for Pytorch Lightning seems not for n-fold CV.

Thanks.

**Comment by gaceladri** [comment]
I would like to use it with TimeSeriesSplit. It's the same logic than Kfold. Just replacing the object. Like LightGBMTunerCV but with Pytorch lightning.

**Comment by hvy** [comment]
I'm wondering if you cannot do something similar (in terms of constructing custom objective functions with pruning callbacks and iterating over folds) to this example for LightGBM https://github.com/optuna/optuna/pull/1896.
