### ISSUE TITLE
Complete list of logging level for `optuna.logging.set_verbosity`

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#1879]
When I read the page of [`optuna.logging.set_verbosity`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.logging.set_verbosity.html), I suppose that it is nicer to show the complete list of logging levels of optuna on the same page like [`optuna.logging.get_verbosity`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.logging.get_verbosity.html).

**Comment by HideakiImamura** [comment]
Looks very good to me. Would you mind to work on it?

**Comment by nzw0301** [comment]
I would not mind. Please give me a few days to sent PR.
