### ISSUE TITLE
`visualization.plot_contour` with `suggest_categorical` that contains `str`

### ISSUE THREAD

**Issue by haenry** [optuna/optuna#1881]
`plot_contour` does not support categorical string values and doesn't inform the user.

## Expected behavior

The user should be informed that string values from `trial.suggest_categorical` do not work in `plot_contour`. Or the plotting function should exclude string values. Or it should support them for plotting.

## Environment

- Optuna version: 2.1.0 
- Python version: 3.7.7
- OS: Linux
- (Optional) Other libraries and their versions:

## Error messages, stack traces, or logs

```
Traceback (most recent call last):
  File "/home/me/workspace/service_train/src/service_train/train2/test_bug.py", line 27, in <module>
    optuna.visualization.plot_contour(study)
  File "/home/me/.cache/pypoetry/virtualenvs/test-c2Tex7wS-py3.7/lib/python3.7/site-packages/optuna/visualization/_contour.py", line 66, in plot_contour
    return _get_contour_plot(study, params)
  File "/home/me/.cache/pypoetry/virtualenvs/test-c2Tex7wS-py3.7/lib/python3.7/site-packages/optuna/visualization/_contour.py", line 102, in _get_contour_plot
    padding = (max_value - min_value) * padding_ratio
TypeError: unsupported operand type(s) for -: 'str' and 'str'
```

## Steps to reproduce

1. create a study which uses `trial.suggest_categorical` with string values in the choice
2. call `plot_contour` for this study

## Reproducible examples (optional)

```python
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

import optuna


rnd = np.random.RandomState(7)

X, y = load_iris(return_X_y=True)
X_train, X_valid, y_train, y_valid = train_test_split(X, y, random_state=rnd)


def objective(trial):
    C = trial.suggest_float('C', 0., 7.)
    solver = trial.suggest_categorical("solver", ['newton-cg', 'lbfgs', 'liblinear', 'sag', 'saga'])
    clf = LogisticRegression(C=C, random_state=0, solver=solver)
    clf.fit(X_train, y_train)
    return clf.score(X_valid, y_valid)


study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=4)
print(study.best_params, study.best_value)

optuna.visualization.plot_contour(study)

```

**Comment by toshihikoyanase** [comment]
I think #1819 resolved this issue, but it has not been included in the release yet. Could you try the master branch (c.f., [installation](https://optuna.readthedocs.io/en/stable/installation.html))? Or, v2.2.0 which includes #1819 will be released next week so please give us some time.

**Comment by haenry** [comment]
Looking good on the master branch. Thanks!
![grafik](https://user-images.githubusercontent.com/15144498/94928165-8d425300-04c3-11eb-95fa-c803a3c637d1.png)

It's not really intuitive, that there's a smooth transition from one categorical value to the next one, but it does the job 👍

**Comment by toshihikoyanase** [comment]
Great!

> It's not really intuitive, that there's a smooth transition from one categorical value to the next one,

We use [plotly's countor plot](https://plotly.com/python/contour-plots/) as backend, and it assumes continuous space. So, contour lines may not be reliable as you mentioned.

**Comment by toshihikoyanase** [comment]
Let me close this issue since it has been resolved. Please feel free to re-open it or create a new one if you have further comments.
