### ISSUE TITLE
ValueError: All layers added to a Sequential model should have unique names.

### ISSUE THREAD

**Issue by tkmamidi** [optuna/optuna#1885]
I'm getting a value error "unique names" for only few trials and not all. 

`ValueError: All layers added to a Sequential model should have unique names. Name "dense" is already the name of a layer in this model. Update the 'name' argument to pass a unique name.
`

I am using a define-by-run search for tuning. Trying to create neurons and layers in a for loop. Below is an example.

```
n_layers = config.suggest_int('n_layers', 1, 50)
model = Sequential()
model.add(Dense(n_columns, input_shape=(n_columns,), activation=config.suggest_categorical("activation", ['tanh', 'softmax'])))
    for i in range(n_layers):
        num_hidden = config.suggest_int("n_units_l{}".format(i), 4, 200)
        model.add(Dense(num_hidden, name = "activation_l{}".format(i), activation=config.suggest_categorical("activation_l{}".format(i), ['tanh', 'softmax'])))
        model.add(Dropout( config.suggest_float("dropout_l{}".format(i), 0.0, 0.9), name = "dropout_l{}".format(i)))
model.add(Dense(units = 3, kernel_initializer=config.suggest_categorical("kernel_initializer",['uniform', 'lecun_uniform']),  activation = 'softmax'))
    model.compile(loss='categorical_crossentropy', optimizer=config.suggest_categorical("optimizer",['SGD', 'RMSprop']), metrics=['accuracy'])
model.summary()
```

Any help is much appreciated!
Thanks in advance!

**Comment by toshihikoyanase** [comment]
Hi @tkmamidi,
Thank you for your question.

Hmm, I can successfully run your code snippet in this [colab notebook](https://colab.research.google.com/drive/1ONufVw9Rh6LH9IBYG2wQZmK0kQx20EDK?usp=sharing).

I guess you use the name outside the snippet since any layers do not have the `name` argument with `dense`.

**Comment by tkmamidi** [comment]
Thanks for the response. Here's what my Traceback looks like:
```
W 2020-10-01 12:48:45,750] Trial 90 failed because of the following error: ValueError('All layers added to a Sequential model should have unique names. Name "dense" is already the name of a layer in this model. Update the `name` argument to pass a unique name.')
Traceback (most recent call last):
  File "/data/user/tmamidi/.conda/envs/testing/lib/python3.8/site-packages/optuna/study.py", line 778, in _run_trial
    result = func(trial)
  File "optuna-tpe.ipy", line 66, in tune_data
    model.add(Dense(units = 3, kernel_initializer=config.suggest_categorical("kernel_initializer",['uniform', 'lecun_uniform', 'normal', 'zero', 'glorot_normal', 'glorot_uniform', 'he_normal', 'he_uniform']),  activation = 'softmax'))
  File "/data/user/tmamidi/.conda/envs/testing/lib/python3.8/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/data/user/tmamidi/.conda/envs/testing/lib/python3.8/site-packages/tensorflow/python/keras/engine/sequential.py", line 186, in add
    raise ValueError('All layers added to a Sequential model '
ValueError: All layers added to a Sequential model should have unique names. Name "dense" is already the name of a layer in this model. Update the `name` argument to pass a unique name.

```

**Comment by tkmamidi** [comment]
Thanks for sharing the notebook. When I change the range of layers to 20 and change the compile snippet below. It recreates the same error.
`study.optimize(objective, n_trials=10, n_jobs = -1)`

Hopefully, you'll see it too.

**Comment by toshihikoyanase** [comment]
Thank you for your reply. 

> `n_jobs = -1`

I guess this option is the cause of the error. It enables uses to execute multiple trials with multi-threading, but the Keras's global state (i.e., the default graph of Tensorflow) can collide if we create multiple networks. So, could you remove the `n_jobs` argument?

If you are interested in the parallel optimization, please take a look at [this tutorial](https://optuna.readthedocs.io/en/stable/tutorial/004_distributed.html#distributed).

**Comment by tkmamidi** [comment]
Thanks for sharing the tutorial. I really didn't understand it. Do I have run the script multiple times?

**Comment by tkmamidi** [comment]
Okay. Looks like my first input layer and the last output layer doesn't have any name. Maybe that's the reason it conflicts. When I gave a name to the last layer, I don't see the error (at least in the colab notebook). I'll try it on my machine and update.

`model.add(Dense(units = 3, name = "dense_last", kernel_initializer = config.suggest_categorical ("kernel_initializer", ['uniform', 'lecun_uniform']),  activation = 'softmax'))
`

Thanks for helping me out!

**Comment by tkmamidi** [comment]
It worked! 
Giving a name to the last layer solved the problem. 
Thank you so much for helping me out!
