### ISSUE TITLE
Loading data in examples/tensorflow_eager_simple.py file

### ISSUE THREAD

**Issue by tkmamidi** [optuna/optuna#1887]
Hello, 
I was trying to use Tensorflow [example](https://github.com/optuna/optuna/blob/master/examples/tensorflow_eager_simple.py) for hyper parameter tuning. I see that `get_mnist` function is being called in the `objective` function. So when I run the study, each trail has to call the load function and has to load the data every time. Is there a way to give the dataset along with config so that study doesn't have to download/load data for each trial?

Please help!
Thanks in advance!

**Comment by nzw0301** [comment]
@tkmamidi Personally, I define the class such that it contains datasets as instance variables to avoid loading dataset at every trial like your case. The class looks like


```python
class Objective(object):
    def __init__(self, ):
        (x_train, y_train), (x_valid, y_valid) = mnist.load_data()
        self.min_x = min_x
        self.max_x = max_x
        self.training_data = (x_train, y_train
        self.valid_data = x_valid, y_valid

    def __call__(self, trial):
        
        X_train, y_train = self.training_data
        X_val, y_val = self.valid_data

        # sample hyper-parameter and return calculated loss
```

This approach is the almost same as https://optuna.readthedocs.io/en/stable/faq.html#how-to-define-objective-functions-that-have-own-arguments.

**Comment by tkmamidi** [comment]
This is helpful. Thanks!

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for your accurate answer. I'd like to slightly update the [FAQ](https://optuna.readthedocs.io/en/stable/faq.html#how-to-define-objective-functions-that-have-own-arguments) to guide users to the example, which reuses the dataset. I created a PR (#1903) and please feel free to add comments to improve the documentation.

**Comment by toshihikoyanase** [comment]
@tkmamidi 
I think the issue has been resolved, so could you close it?

**Comment by tkmamidi** [comment]
Thanks a bunch! I am closing it now :)
