### ISSUE TITLE
Use variable annotation syntax for Type Hints

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#1897]
## Motivation

After dropping Python 3.5 (#1067), we can use type hints with variable annotation syntax.

https://www.python.org/dev/peps/pep-0526/

## Description

Thank you @harupy for creating a script to detect type comments for variables!
https://github.com/optuna/optuna/issues/711#issuecomment-683521987

**Comment by harupy** [comment]
I have tested [com2ann](https://github.com/ilevkivskyi/com2ann) (which translates type comments into type annotations) and it worked.

Usage:

```bash
# install python 3.8 (com2ann doesn't work in python < 3.8)
pip install git+https://github.com/ilevkivskyi/com2ann.git

com2ann .
```

**Comment by hvy** [comment]
For the record, https://github.com/optuna/optuna/pull/1937/files#r509361516.

**Comment by c-bata** [comment]
I confirmed that all comment-style variable annotation are replaced at #1950.
