### ISSUE TITLE
Multiple studies sharing evaluations

### ISSUE THREAD

**Issue by parsiad** [optuna/optuna#1911]
Consider the case in which we have two objective functions of the form `f_1(x) = h_1(g(x))` and `f_2(x) = h_2(g(x))`. In particular, the function `g` is common to both. Moreover, **`g` is expensive to evaluate** while `h_i` is essentially free.

Suppose now that we have a study for each function. As a first attempt, we may write our objective functions as follows:

```python
def f_1(trial):
    x = trial.suggest_uniform(...)
    g_x = g(x)
    return h_1(g_x)

def f_2(trial):
    x = trial.suggest_uniform(...)
    g_x = g(x)
    return h_2(g_x)
```

This is, however, wasteful: the first study will ignore any evaluations of `g` performed by the second (and vice versa). It would be much better if the two studies could contribute to each other's databases.

Does such a feature exist in Optuna? If not, is there an easy way for me to monkey patch this behavior? Failing that, what would be the best place to start?

**Comment by y0z** [comment]
Hello.
I often use a simple wrapper with a cache like this for this purpose.

```python
class Function:
    def __init__(self, f):
        self.f = f
        self.cache = {}

    def __call__(self, x):
        if x in self.cache:
            return self.cache[x]
        else:
            v = f(x)
            self.cache[x] = v
            return v

def f(x):
    # your expensive function
    return x
    
g = Function(f)

g(0)
g(0)
```

**Comment by fsmosca** [comment]
There is a sample [multiobjectivestudy](https://optuna.readthedocs.io/en/stable/reference/multi_objective/generated/optuna.multi_objective.study.MultiObjectiveStudy.html#optuna.multi_objective.study.MultiObjectiveStudy).

I modified that sample to look like what you need.

```python
import optuna


def objective(trial):
    x = trial.suggest_float("x", 0, 5)

    g_x = 2 * x**3  # expensive

    f_1 = 4 * g_x**2
    f_2 = (g_x - 5) ** 2

    return f_1, f_2


study = optuna.multi_objective.create_study(["minimize", "minimize"])
study.optimize(objective, n_trials=10)
```

#### Result
```
[I 2020-10-11 15:18:50,297] Trial 0 finished with values: [2401.244877007397, 380.29872584552334] with parameters: {'x': 2.305257329073365}.
[I 2020-10-11 15:18:50,356] Trial 1 finished with values: [10601.430440969578, 2160.5413701875186] with parameters: {'x': 2.9526190282445617}.
[I 2020-10-11 15:18:50,403] Trial 2 finished with values: [29.92601963507222, 5.129165139073663] with parameters: {'x': 1.1099962093003461}.

...
```

**Comment by parsiad** [comment]
y0z: Thank you. Your approach works when optimizing with only a single process, but I'd like to parallelize my optimization.

fsmosca: Thank you. This is exactly what I need.
