### ISSUE TITLE
Fix type hints for `mypy == 0.790`

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1914]
See https://github.com/optuna/optuna/pull/1913. 

Some type hints are not complying to the latest `mypy == 0.790` and should be addressed.

**Comment by HideakiImamura** [comment]
Hi @himkt. Do you now work on this issue, right? Thanks for your contribution.

**Comment by himkt** [comment]
@HideakiImamura 

Ah, sorry for assigning without any comment.
I'll work on the issue if no one is addressing it, as this issue was related to my previous PR #1913. :eyes:
