### ISSUE TITLE
[RFC] Preferred string formatting with Python 3.6+

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#1916]
## Motivation

Part of https://github.com/optuna/optuna/issues/1067.

Since Python 3.5 has been dropped, "f-strings" ([PEP 498](https://www.python.org/dev/peps/pep-0498/)) can be used. We could agree on and document the preferred ways of formatting text in Optuna. 

Note that there's no such consensus for the time being.

If the preferred ways change, we should make sure that the code complies to it.

## Description

Discuss how text should be formatted and make sure that code complies to it.

**Comment by crcrpar** [comment]
I would say `format` is preferrable as it's more explicit when a line gets long.

**Comment by hvy** [comment]
I also find `format` to be preferable in certain cases where the string would become too long or when code/logic in f-strings are not particularly readable although this might be a matter of editor/IDE (a more exhaustive list of theoretical concerns are presented in the PEP). On the other hand, I don't see that this is enough to prohibit f-strings and I believe it's sensible to simply allow both.

**Comment by crcrpar** [comment]
I don't say we should not use f-strings, nor should we migrate to them hurriedly. My attitude toward what to use and what to prohibit, including f-strings and whatever, is basically everything is OK unless linters don't warn.

**Comment by hvy** [comment]
Agreed. Also checked with @c-bata, @keisuke-umezawa and other committers and it seemed okay allowing either. 

Let me close this issue as resolved. Thanks @crcrpar for the discussion.
