### ISSUE TITLE
divide by zero encountered in log for TPESampler(multivariate=True)

### ISSUE THREAD

**Issue by fsmosca** [optuna/optuna#1917]
## Expected behavior

No runtime warning.

## Environment

- Optuna version: v2.2.0
- Python version: 3.8.5
- OS: Win 10

## Error messages, stack traces, or logs

```
D:\param_tuner\Optuna-Game-Parameter-Tuner-master\venv\lib\site-packages\optuna\samplers\_tpe\multivariate_parzen_estimator.py:168: RuntimeWarning: divide by zero encountered in log
  log_pdf = np.log(cdf) - np.log(p_accept)
```

## Steps to reproduce

1. On windows 10, install python 3.8 or later
2. Create a folder param_tuner in c or d drive
3. Press Code->Download Zip in the repo https://github.com/fsmosca/Optuna-Game-Parameter-Tuner
4. Copy it in param_tuner folder
5. Unzip the Optuna-Game-Parameter-Tuner-master.zip onto Optuna-Game-Parameter-Tuner-master
6. Open powershell at folder Optuna-Game-Parameter-Tuner-master to get this
`D:\param_tuner\Optuna-Game-Parameter-Tuner-master>`
7. Create virtual environment venv
`PS D:\param_tuner\Optuna-Game-Parameter-Tuner-master> python -m venv venv`
8. Type `ls` and you should see this
```
PS D:\param_tuner\Optuna-Game-Parameter-Tuner-master> ls


    Directory: D:\param_tuner\Optuna-Game-Parameter-Tuner-master


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/10/2020   8:33 pm                engines
d-----        12/10/2020   8:33 pm                start_opening
d-----        12/10/2020   8:33 pm                tools
d-----        12/10/2020   8:33 pm                tourney_manager
d-----        12/10/2020  11:33 pm                venv
d-----        12/10/2020   8:33 pm                visuals
------        12/10/2020   8:33 pm           1865 .gitignore
------        12/10/2020   8:33 pm           1064 LICENSE
------        12/10/2020   8:33 pm          11202 README.md
------        12/10/2020   8:33 pm            636 requirements.txt
------        12/10/2020   8:33 pm          32886 tuner.py
```

9. Activate the virtual environment
`PS D:\param_tuner\Optuna-Game-Parameter-Tuner-master> .\venv\scripts\activate`

10. Install optuna
`(venv) PS D:\param_tuner\Optuna-Game-Parameter-Tuner-master> pip install optuna`

11. Run the command line below
* Notes:  
  * The sampler used `--sampler name=tpe multivariate=true`  
  * Concurrency is 6 `--concurrency 6`. There will be 6 threads to be used in game simulation. My pc has 8 threads.

```
(venv) PS D:\param_tuner\Optuna-Game-Parameter-Tuner-master> python -u tuner.py --sampler name=tpe multivariate=true --initial-best-value 0.52 --trials 200 --games-per-trial 20 --base-time-sec 120 --depth 6 --study-name mv_true --pgn-output mv_true_games.pgn --engine ./engines/stockfish-modern/stockfish.exe --hash 64 --concurrency 6 --opening-file ./start_opening/ogpt_chess_startpos.epd --input-param "{'KingAttackWeights[4]': {'default':44, 'min':0, 'max':148, 'step':4}, 'eMobilityBonus[0][2]': {'default':-31, 'min':-100, 'max':100, 'step':4}, 'eThreatByMinor[3]': {'default':56, 'min':0, 'max':100, 'step':4}, 'mThreatBySafePawn': {'default':173, 'min':0, 'max':248, 'step':4}, 'FutMargin': {'default':227, 'min':100, 'max':348, 'step':4}}" --threshold-pruner result=0.45
```

It triggers after trial 146 in this case.
```
2020-10-13 00:00:01,295 | INFO  | starting trial: 146 ...
2020-10-13 00:00:01,295 | INFO  | suggested param for test engine: {'FutMargin': 220, 'KingAttackWeights[4]': 28, 'eMobilityBonus[0][2]': 76, 'eThreatByMinor[3]': 4, 'mThreatBySafePawn': 120}
2020-10-13 00:00:01,295 | INFO  | param for base engine          : {'FutMargin': 152, 'KingAttackWeights[4]': 20, 'eMobilityBonus[0][2]': 40, 'eThreatByMinor[3]': 12, 'mThreatBySafePawn': 172}

2020-10-13 00:00:01,310 | INFO  | init param: {'FutMargin': 227, 'KingAttackWeights[4]': 44, 'eMobilityBonus[0][2]': -31, 'eThreatByMinor[3]': 56, 'mThreatBySafePawn': 173}
2020-10-13 00:00:01,310 | INFO  | init value: 0.52
2020-10-13 00:00:01,310 | INFO  | study best param: {'FutMargin': 152, 'KingAttackWeights[4]': 20, 'eMobilityBonus[0][2]': 40, 'eThreatByMinor[3]': 12, 'mThreatBySafePawn': 172}
2020-10-13 00:00:01,310 | INFO  | study best value: 0.5904687499999998

2020-10-13 00:00:01,310 | INFO  | games_to_play: 10
2020-10-13 00:00:03,218 | INFO  | played_games: 10, result: {intermediate: 0.65, average: 0.65}
2020-10-13 00:00:03,406 | INFO  | games_to_play: 10
2020-10-13 00:00:05,494 | INFO  | played_games: 20, result: {intermediate: 0.6, average: 0.625}
2020-10-13 00:00:05,603 | INFO  | Actual match result: 0.625, point of view: optimizer suggested values
2020-10-13 00:00:05,744 | INFO  | Trial 146 finished with value: 0.5921093749999997 and parameters: {'FutMargin': 220, 'KingAttackWeights[4]': 28, 'eMobilityBonus[0][2]': 76, 'eThreatByMinor[3]': 4, 'mThreatBySafePawn': 120}. Best is trial 146 with value: 0.5921093749999997.
D:\param_tuner\Optuna-Game-Parameter-Tuner-master\venv\lib\site-packages\optuna\samplers\_tpe\multivariate_parzen_estimator.py:168: RuntimeWarning: divide by zero encountered in log
  log_pdf = np.log(cdf) - np.log(p_accept)
```

## Reproducible examples (optional)

```python
# python code
```

## Additional context (optional)

```
```

**Comment by nzw0301** [comment]
Could you give a reproducible code example for your bug?

**Comment by fsmosca** [comment]
Updated the steps to reproduce.

**Comment by kstoneriv3** [comment]
I only looked at the code but I guess it can be avoided by adding a jitter 'EPS' to before taking the logarithm. Multivariate TPE sampler lacks some of the jitters that independent TPE sampler has. Not sure if it solves the issue but I will soon create a PR for adding jitters.

**Comment by fsmosca** [comment]
With that PR, I no longer encountered such warning.

I continue the optimization to see the difference between multivariate true/false at fixed depth 6 optimization of 200 trials with 500 games/trial on 5 stockfish parameters.

### Game test
This is the result at fixed depth 6, round-robin for 20k games each as validation.
```
   # PLAYER             :  RATING  ERROR   POINTS  PLAYED   (%)     W     D     L  D(%)  CFS(%)
   1 sf_tpe_mv_false    :       7      3  10218.0   20000  51.1  8884  2668  8448  13.3     100
   2 sf_default         :       0      3   9897.5   20000  49.5  8554  2687  8759  13.4      55
   3 sf_tpe_mv_true     :       0      3   9884.5   20000  49.4  8560  2649  8791  13.2     ---
```
At these specific optimization and game test conditions, multivariate=false appears to be superior.

**Comment by kstoneriv3** [comment]
Thank you so much for checking the effect of the PR!

Interesting result! It is possible that `multivariate=False` is superior to `multivariate=True` in some conditions, but we do not have enough practical insights as to when the `multivariate=True` actually helps. (So, the usage reports like this are quite valuable!)

**Comment by fsmosca** [comment]
Indeed, normally the optimization should have been done with time control as in most real application, engine matches are done with time control, but that takes a lot of time. We don't know which one will be superior unless of course if we do the optimization. So the result is only valid as per optimization and validation conditions.
