### ISSUE TITLE
Warm starting Optuna

### ISSUE THREAD

**Issue by FelixNeutatz** [optuna/optuna#1930]
Dear all,

I am looking for a way to warm start the optimization. That means that I would like to enter some trials manually before starting the actual optimization process. 

Thank you for your help.

Best regards,
Felix

**Comment by fsmosca** [comment]
One method that I can think of is to put your initial data in csv file. [Convert](https://pypi.org/project/csv-to-sqlite/) that csv file to sqlite database. You can then load that [database in a study](https://optuna.readthedocs.io/en/stable/tutorial/003_rdb.html#).

**Comment by FelixNeutatz** [comment]
Is there a more Pythonic way that does not require setting up a database?

**Comment by fsmosca** [comment]
Do you have any preferences in mind?

**Comment by FelixNeutatz** [comment]
I am looking probably for something like this

```
import optuna
import numpy as np
from optuna.samplers import TPESampler

def objective(trial):
    a = trial.suggest_categorical('a', [str(a) for a in range(1000)])
    b = trial.suggest_categorical('b', [str(b) for b in range(1000)])

    return np.square(int(a)-42) + np.square(int(b)-42)


objective_value = 0.0
try_these_parameters_first = [{'a': '42', 'b': '229'}, {'a': '176', 'b': '42'}]
study = optuna.create_study(sampler=MyCustomSampler(try_these_parameters_first))
study.optimize(objective, n_trials=2)

study.sampler=TPESampler()
study.optimize(objective, n_trials=1000)


print('The best value of the study: ' + str(study.best_value))
```
Do you know of any Sampler that can do something like this?

**Comment by fsmosca** [comment]
There is [enqueue_trial](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html?highlight=enqueue_trial#optuna.study.Study.enqueue_trial).

```python
import optuna
import numpy as np
from optuna.samplers import TPESampler


def objective(trial):
    a = trial.suggest_categorical('a', [str(a) for a in range(1000)])
    b = trial.suggest_categorical('b', [str(b) for b in range(1000)])

    return np.square(int(a)-42) + np.square(int(b)-42)


try_these_parameters_first = [{'a': '42', 'b': '229'}, {'a': '176', 'b': '42'}]

study = optuna.create_study(sampler=TPESampler())

study.enqueue_trial(try_these_parameters_first[0])
study.enqueue_trial(try_these_parameters_first[1])

study.optimize(objective, n_trials=10)

print('The best value of the study: ' + str(study.best_value))
```

**Comment by FelixNeutatz** [comment]
Amazing! Exactly what I was looking for! Thank you :)

**Comment by norihitoishida** [comment]
Hi @FelixNeutatz !
Similar feature`Partial Fixed Sampler` #1892 will be available on next release v2.4.0 .
`PFS` and `enqueue_trial` have pros & cons respectively.
In a scenario where you stop optimizing by `timeout` option (not `n_trials`), `PFS` might be more intuitive.
May the Optuna be with you :)

**Comment by FelixNeutatz** [comment]
Hi @norihitoishida,
great to hear! I will try it out :)

Best regards,
Felix

**Comment by AndreasGerken** [comment]
Hi,

i just found this nice trick and your explanation. Is it somewhere in the documentation yet?
I guess that more people would like to do this and don't find this thread.

Best, Andi

**Comment by csetzkorn** [comment]
Thanks for this. Works like a charm.
