### ISSUE TITLE
[FEATURE] Ability to choose study with perfect score value, not just direction.

### ISSUE THREAD

**Issue by pseudotensor** [optuna/optuna#1940]
Motivation is that there is no need to optimize further if perfect score is obtained.  This also allows someone to specify an upper or lower limit below which the optimization will stop.  E.g. One may want no better than AUC=0.99, but optuna will keep going even if AUC=1 exactly

**Comment by crcrpar** [comment]
Hi Jonathan,

We can implement that kind of feature by implementing a `Callback` callable that takes `Study` and `Trial` as its arguments and do what we want. 

So, for example, below is that callback which stops once Optuna finds a set of hyperparameters that achieves AUC >= 0.99.

```python

import optuna


class Callback:

    def __init__(self, auc_threshold: float = 0.99) -> None:
        self.auc_threshold = auc_threshold

    def __call__(self, study: optuna.study.Study, trial: optuna.trial.FrozenTrial):
        if study.best_value >= self.auc_threshold:
            study.stop()

AUC_THRESHOLD = 0.99

def objective(trial):
    # Assume all trials after a certain number of trials keep being pruned.
    if trial.number > 4:
        return AUC_THRESHOLD

    return trial.suggest_float("x", 0.1, 0.8)


if __name__ == "__main__":
    study = optuna.create_study(direction="maximize")
    study.optimize(
        objective, 
        n_trials=10,
        callbacks=[Callback(AUC_THRESHOLD)]
    )
```

Example Notebook: https://colab.research.google.com/drive/1v7Hf9DkdD3W3-0CQMMjJEaprbh4EYu_N?usp=sharing

https://github.com/optuna/optuna/issues/1672 may or may not be the reference.

**Comment by pseudotensor** [comment]
Sounds good yes, will a PR be made?

**Comment by crcrpar** [comment]
I personally don't think that gonna happen but the new tutorial that I'm working on will mention Optuna Callback things 😉 

ref: https://62151-122299416-gh.circle-artifacts.com/0/docs/build/html/tutorial/20_recipes/007_optuna_callback.html#sphx-glr-tutorial-20-recipes-007-optuna-callback-py

**Comment by crcrpar** [comment]
Let me close this as the original question looks solved.
