### ISSUE TITLE
Missing plots in the docs

### ISSUE THREAD

**Issue by dankal444** [optuna/optuna#1963]
There are missing plots in the docs, for example here:
https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_edf.html
![Screenshot from 2020-10-26 15-04-59](https://user-images.githubusercontent.com/24862989/97182378-c1e0bc00-179c-11eb-9afb-5beb85308156.png)

Tried on Chrome and Firefox, same story.

**Comment by nzw0301** [comment]
@dankal444 As a temporal solution to see the plots, you can check the latest document instead of the stable version.
For example https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.plot_edf.html

**Comment by HideakiImamura** [comment]
@dankal444 Thanks for raising an issue and @nzw0301 thanks for the comment. I agree with @nzw0301. This problem has been fixed in the master branch. Starting with the next release v2.3.0, plots in the documentation will be displayed properly.

**Comment by HideakiImamura** [comment]
Let me close this issue because the original problem is fixed in the master branch.
