### ISSUE TITLE
Strange contour plot is generated with latest `plotly`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#1967]
## Expected behavior
This bug is originally reported by @harupy in [here](https://github.com/optuna/optuna/pull/1944#issuecomment-716473083).

The example code in the documentation should generate the contour plot as follows.
<img width="1869" alt="スクリーンショット 2020-10-27 12 02 48" src="https://user-images.githubusercontent.com/38826298/97252000-581feb00-184c-11eb-948c-edae184e590b.png">

But, it generates as follows with the latest `plotly` of version 4.12.0.
<img width="1867" alt="スクリーンショット 2020-10-28 4 11 22" src="https://user-images.githubusercontent.com/38826298/97350100-aaf0b580-18d3-11eb-99be-a68c4e5eba17.png">

## Environment

- Optuna version: https://github.com/optuna/optuna/commit/fe9909a04cb343fcb346a9f4cbcf4c1d9efc066f
- Python version: 3.8
- Plotly version: 4.12.0

## Reproducible examples

```python
import optuna


def objective(trial):
    x = trial.suggest_uniform("x", -100, 100)
    y = trial.suggest_categorical("y", [-1, 0, 1])
    return x ** 2 + y


study = optuna.create_study()
study.optimize(objective, n_trials=30)

fig = optuna.visualization.plot_contour(study, params=["x", "y"])
print(fig)
fig.show()

```

## Additional context (optional)

With the `plotly` of version 4.9.0,  the above code generates the appropriate contour plot.

**Comment by hvy** [comment]
Let me close this issue as fixed by #1983.
