### ISSUE TITLE
How to use Optuna for autoencoder networks?

### ISSUE THREAD

**Issue by pranav6670** [optuna/optuna#1970]
I have a model architecture as shown below:
```
IMG_SIZE = 96
img_shape=Input(shape=(IMG_SIZE, IMG_SIZE, 1))

x = Conv2D(128, (3, 3), activation='relu' , padding='same')(input_img)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
x = MaxPooling2D((2, 2), padding='same')(x)
x = Conv2D(16, (3, 3), activation='relu', padding='same')(x)
encoded = MaxPooling2D((2, 2), padding='same')(x)

x = Conv2D(16, (3, 3), activation='relu', padding='same')(encoded)  
x = UpSampling2D((2, 2))(x)  
x = Conv2D(64, (3, 3), activation='relu', padding='same')(x)
x = UpSampling2D((2, 2))(x)
x = Conv2D(128, (3, 3), activation='relu', padding='same')(x)
x = UpSampling2D((2, 2))(x)
decoded = Conv2D(1, (3, 3), activation='sigmoid', padding='same')(x)

autoencoder = Model(input_img, decoded)
``` 
How can I use Optuna to work with these two networks(encoder and decoder)? Thank You!

**Comment by HideakiImamura** [comment]
Hi @pranav6670! Thanks for the question. To utilize Optuna, we need to define a "metric" to optimize hyperparameters. The metric should be a function whose input is hyperparameters and output is a float value.

In my understanding, such an objective function depends not only on the model (autoencoder network) but also on the problem which you want to solve. It depends on each use case. Do you have any metrics to optimize (e.g. classification error, regression error, or etc).?

I think [this tutorial](https://optuna.readthedocs.io/en/stable/tutorial/index.html) is best for you if you missing. If you have any trouble, please feel free to ask questions.

**Comment by pranav6670** [comment]
Hello, @HideakiImamura sensei, I have binary_crossentropy loss which I have to minimise and increase the reconstruction accuracy of the autoencoder. I didn't understand how do I code the model under the objective function.

**Comment by HideakiImamura** [comment]
Thanks for the reply. Hmm, I'm not sure I understand the model you have in mind. Again, we need some final performance score to optimize to use of Optuna. Is the autoencoder one of the components in a big model? In addition, what hyperparameters do you want to tune?
