### ISSUE TITLE
Is it possible to pass dataset to objective function but not call it inside?

### ISSUE THREAD

**Issue by diff7** [optuna/optuna#1971]
Hi, 
I went through documentation and did not fine any example how to do it. 

I optimize on several modifications of a datasets and to call datasets generation within objective function is not very convenient.  Right now I declare datasets as global variables but I do not like that pattern I prefer explicitly pass all variables I need. 

Any tips? 

Thank you in advance.

**Comment by HideakiImamura** [comment]
Hi @diff7! Thanks for the question. I think [this example](https://github.com/optuna/optuna/blob/master/examples/sklearn_additional_args.py) will help you. We can customize the objective function by defining it as a class.

**Comment by diff7** [comment]
Hi, got it, thanks!

By the way have you encountered any articles or resources regarding simultaneous  feature selection and HPO? I am grouping features into buckets and trying to find an optimal combination of buckets and hyperparams.  If you have not no problem! ))
And you can close the issue. Thanks again!

**Comment by HideakiImamura** [comment]
I don't know the specific example to conduct the feature selection and the hyperparameter optimization, but it can be done I think. Simply, we can conduct them separately. You can repeat the process of selecting the features and then performing the hyperparameter optimization.

To do them in light of the interrelationships, the multi-fidelity Bayesian optimization framework may be used. But, I don't know how we do it.

**Comment by diff7** [comment]
Got it, thanks! 
I will get familiarize with  multi-fidelity Bayesian optimization.
