### ISSUE TITLE
Avoid printing out password for database

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#1974]
## Note to the questioner

```python
from optuna import load_study

load_study('nerman-test', 'mysql://root:this_is_secret@localhost/optuna')
```

Currently, we pass a SQL URL (username+password+host+db_name) to `load_study`.
If `load_study` fails to load a study for some reason, a password for the database would be exposed in a traceback.

```
Traceback (most recent call last):
...
Traceback (most recent call last):
  File "load_test.py", line 4, in <module>
    load_study('nerman-test', 'mysql://root:this_is_secret@localhost/optuna')
...
```

I'm wondering if we can hide credentials from the log output.
For example, is there a way to set a password by the environment variable?

I think we can use `MYSQL_PWD` for this case.
It may be sufficient to add a reference to the following reference in our documentation.
https://dev.mysql.com/doc/refman/8.0/en/environment-variables.html

**Comment by hvy** [comment]
I'm wondering if this really issue an issue of Optuna. Is this not because the password is hardcoded in the user code in the first place?

**Comment by himkt** [comment]
Thank you for your opinion! I was just wondering if it is helpful to tell users that they can use environment variables when connecting to the database. But, as you said, it may be out of the scope of Optuna documentation.

So, let me close this issue.
