### ISSUE TITLE
Discuss the API design of Separable CMA-ES support.

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#1975]
## Motivation

sep-CMA-ES is an algorithm which constrains the covariance matrix to be diagonal.
Due to reduce the model complexity, the learning rate for the covariance matrix is increased. Consequently, this algorithm outperforms CMA-ES on separable functions. I once opened #1951 which supports sep-CMA-ES based on relative sampling. But I closed it because we seems to be able to support it as an independent sampler.

There are several approaches to implement sep-CMA-ES as an independent sampler. As @toshihikoyanase said, multivariate TPE is implemented in TPESampler(it only supports univariate TPE before).

> Before implementing the sampler, I think we can discuss the API design a little bit more. A possible alternative approach is to implement sep-CMA-ES as CmaEsSampler.sample_independent. The multivariate TPE sampler employed this approach. What do you think of it?
> https://github.com/optuna/optuna/pull/1951#issuecomment-718354751

In this issue I want to discuss its API design.

## Discussion

There are two approaches.

If we implement sep-CMA-ES in CmaEsSampler, we can reduce duplicated logic as possible as we can.
But it makes the implementation relatively complex.

On the other hand, if we add a new sampler (like SepCmaEsSampler), we able to keep the simple implementation.
But there are duplicated logic in constructor and constructor options. Note that some utility functions (e.g. `_to_optuna_param` , `_to_cma_param` and so on) are not duplicated. Because I will add `samplers/_cmaes` module like this:

* `samplers/_cmaes/cmaes.py`  - Define `CmaEsSampler`
* `samplers/_cmaes/sep_cmaes.py`  - Define `SepCmaEsSampler`
* `samplers/_cmaes/space.py`  - Define `_to_optuna_param` , `_to_cma_param` and so on.

I prefer the latter approach (simple is the best for me). But I know this is a controversial topic. So I'd like to hear the opinions from other developers (especially @hvy and @HideakiImamura, who reviewed multivariate TPE).

## Additional context (optional)

See https://github.com/optuna/optuna/pull/1951

**Comment by HideakiImamura** [comment]
Thanks for mentioning me. I think the latter approach is fine. I think separating the CMA-ES and the separable CMA-ES at the class level is the most straightforward approach for users. (But, I don't know the detail of the algorithm of the separable CMA-ES. I'd like to read your original code.)

**Comment by toshihikoyanase** [comment]
I agree with @HideakiImamura . I initially suggested `SepCmaEsSampler` because I'm not sure if users want to fallback the independent sampling to sep-CMA-ES when the search space is conditional. If we Users can easily combine `CmaEsSampler` with `SepCmaEsSampler` by using the argument of `CmaEsSampler.__init__`.

**Comment by c-bata** [comment]
Thank you for hearing your opinions!

I implemented a prototype of an optimizer for separable CMA-ES. But It makes the implementation complex because it requires non-trivial settings of the learning rate. So I decide to implement Sep-CMA-ES as the relative sampler :bow: 

Thanks again.
