### ISSUE TITLE
Enable `--diff` option for `blackdoc` if it supports the option

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#1976]
## Motivation

[Recently](https://github.com/optuna/optuna/pull/1958), the `blackdoc` is introduced into Optuna to verify the code format in the docs. The `black` which is used to format the code in Optuna supports the `--diff` option to show the difference before and after formatting. This option is enabled in the CI of Optuna. However, `blackdoc` does not support the option. If `blackdoc` supports the option, we should enable the option in the CI.

**Comment by hvy** [comment]
How about creating an issue in the main repository?

**Comment by keisuke-umezawa** [comment]
The functionality seems to be added! https://github.com/keewis/blackdoc/issues/53
