### ISSUE TITLE
allow change of user attributes even when trial is finished

### ISSUE THREAD

**Issue by jtdeng** [optuna/optuna#1986]
In some blackbox optimization, we need to set trial related user attributes even when it's finished, e.g. trial 2 is sampled around trial 1 (already finished), and when trial 2 is finished, we need to evaluate how good trial 2 can improve the objective, thus we will set a score (user attr) to trial 1.

in current implementation, when a trial is finished, there is a check to prevent any change after trial is finished, it would be good that optuna can allow the change on user defined attrs.

**Comment by hvy** [comment]
Thanks for bringing this up. I'm not entire sure I've understood your use case, but I assume it is not possible to store this information in the attribute of trial 2? If you have code, that might help. Just to clarify there are certain assumptions introduced around the behavior of how trials may be modified. E.g. in this case that a trial can only be modifies before it's completed, and that a trial is never modified from a different process that the one that first started it. It's mostly an implementation detail, though. To elaborate, Optuna internally uses a cached storage on top of the RDB storage. This cached storage caches trials that have been completed and assumes that those are fixed throughout. We'll have to reconsider this behavior as well if this is an issue.

**Comment by jtdeng** [comment]
> Thanks for bringing this up. I'm not entire sure I've understood your use case, but I assume it is not possible to store this information in the attribute of trial 2? If you have code, that might help. Just to clarify, there are certain assumptions introduced around the behavior of how trials may be modified. E.g. that a trial can only be modified before it's completed, and that a trial is never modified from a different process than the one that first started it. It's mostly an implementation detail, though. To elaborate, Optuna internally uses a cached storage on top of the RDB storage to reduce RDB access. This cached storage caches trials that have been completed and assumes that those are fixed throughout. We'll have to reconsider this behavior if this is an issue.

Hi hvy, thanks for your quick reply.
I understand the current design that no change is allowed when trial is finished, [_check_trial_is_updatable](https://github.com/optuna/optuna/blob/750456823d72b6fe7cf66717f3e3107a54c73307/optuna/storages/_cached_storage.py#L417), while in our sampler algorithm (WIP), we need to pick a trial (trial 1 mentioned above) from all completed trials and sample a candidate (say trial 2) around it, after evaluation of trial 2, we need to set some user defined attrs related to trial 1, thus all other distributed optimization processes could reuse this information in db to judge which trial could be picked in next iteration. these user attributes shall be trial related and can only be set after trial is completed.

In most case, I think it won't be necessary to change the trial state such as params and value(s), but for trial user defined attributes, whether and when it shall be updated shall be decided by the sampler algorithm, this will open the possibility for other distributed sampling algorithms like the one I am working on.
