### ISSUE TITLE
[RFC] Rename the name of `sample_relative`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#1996]
## Motivation 
Optuna calls it `sample_relative` to sample the variables in the search space, taking into account the correlations between them. However, the name `sample_"relative"` is a bit confusing because statistics calls the probability distribution of multiple variables a "joint distribution" rather than a "relative distribution". Shouldn't the name `sample_relative` be renamed?

One candidate is "sample_joint". All of your opinions are welcome.

## Description

Rename the `sample_relative` of all samplers, including `BaseSampler`. During the transition period, both the `sample_relative` and the renamed method name should coexist while two major versions are changed.

The pros / cons of renaming should be considered from the following perspectives, and if cost-effective, the renamed PR has been merged.

* Backward compatibility
* Justification of "sample_joint"
* Usability

## Alternatives (optional)
N/A

## Additional context (optional)
N/A

**Comment by toshihikoyanase** [comment]
Let me re-open this issue since it is a good opportunity to discuss it when we plan the next major release.

**Comment by HideakiImamura** [comment]
Let me close this issue since we do not work on this.
