### ISSUE TITLE
More in depth explanation of how to fix/set parameters to be tuned in lightGBM

### ISSUE THREAD

**Issue by Jakobhenningjensen** [optuna/optuna#2002]
In the docs for lightgbm (https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.train.html#optuna.integration.lightgbm.train) it is stated that "it tunes some important parameters", but it is rather difficult to figure out, what you define as important parameters, in what space they are tuned and what is not tuned? 

In the basic classifying example https://github.com/optuna/optuna/blob/master/examples/lightgbm_tuner_simple.py (which the docs refer to)  there is a param-dict

```  
params = {
        "objective": "binary",
        "metric": "binary_logloss",
        "verbosity": -1,
        "boosting_type": "gbdt" }
```

Is it so, that everything specified in that dict is fixed? If not, how do we fix parameters (e.g `num_leaves=5`) and how do we add parameters to be optimized in a space (e.g `num_leaves=[1,2,5,10]`)?

**Comment by toshihikoyanase** [comment]
@Jakobhenningjensen  Thank you for your question. 

> it is rather difficult to figure out, what you define as important parameters, in what space they are tuned and what is not tuned?

[This blog post](https://medium.com/optuna/lightgbm-tuner-new-optuna-integration-for-hyperparameter-optimization-8b7095e99258) explains the detailed algorithm and parameters to be tuned. So, please take a look at it.

> how do we fix parameters (e.g num_leaves=5) and how do we add parameters to be optimized in a space (e.g num_leaves=[1,2,5,10])?

The current `LightGBMTuner` does not allow users to change the target parameters, but we are discussing such a feature in #1947 and developing it in #1947 and #1997. If you have any feedback, please feel free to add comments to them.

**Comment by nickcorona** [comment]
Refer to the source code. It's in there.
