### ISSUE TITLE
Current example code of MOTPEMultiObjectiveSampler runs NSGAII algorithm.

### ISSUE THREAD

**Issue by TaskeHAMANO** [optuna/optuna#2006]
Hello, optuna development team!

Today, I run an [example code of MOTPE sample in the optuna docs](https://optuna.readthedocs.io/en/stable/reference/multi_objective/generated/optuna.multi_objective.samplers.MOTPEMultiObjectiveSampler.html#optuna.multi_objective.samplers.MOTPEMultiObjectiveSampler), it seems to success, but when I checked the sampled, it said NSGAII sampler.

```

seed = 128
num_variables = 9
n_startup_trials = 11 * num_variables - 1


def objective(trial):
    x = []
    for i in range(1, num_variables + 1):
        x.append(trial.suggest_float(f"x{i}", 0.0, 2.0 * i))
    return x


sampler = optuna.multi_objective.samplers.MOTPEMultiObjectiveSampler(
    n_startup_trials=n_startup_trials, n_ehvi_candidates=24, seed=seed
)
study = optuna.multi_objective.create_study(["minimize"] * num_variables)
study.optimize(objective, n_trials=5)
study.sampler
```
> <optuna.multi_objective.samplers._nsga2.NSGAIIMultiObjectiveSampler at 0x17dde1c0348>

Referencing [a PDF document](https://buildmedia.readthedocs.org/media/pdf/optuna/stable/optuna.pdf), initialization of `study` object suppose to be follows.

```
...
study = optuna.multi_objective.create_study(["minimize"] * num_variables, sampler=sampler)
...
```

**Comment by crcrpar** [comment]
You are right. Do you want to fix that?

**Comment by norihitoishida** [comment]
@TaskeHAMANO 
@crcrpar 
I'll work on this

**Comment by norihitoishida** [comment]
@TaskeHAMANO 
Thank you for your report!
