### ISSUE TITLE
Add tox.ini instead of checks.sh

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#2010]
## Motivation

I think tox is a better solution of [checks.sh](https://github.com/optuna/optuna/blob/master/checks.sh).
tox makes it easier to run tests and lint checks for newcomers because it is a widely accepted as a standard Python tool.

## Description

The setting file (tox.ini) of [optuna-dashboard](https://github.com/c-bata/optuna-dashboard) project is here:

```
[tox]
envlist =
    py36
    py37
    py38
    py39
    flake8
    black
    mypy

[testenv]
basepython = python3.9
commands = python -m unittest

[testenv:py36]
basepython = python3.6

[testenv:py37]
basepython = python3.7

[testenv:py38]
basepython = python3.8

[testenv:flake8]
deps = flake8
commands = flake8 .

[testenv:black]
deps = black
commands = black --check .

[testenv:mypy]
deps = mypy
commands = mypy .
```

Usage is like this:

```
$ pip install tox
$ tox -e ALL  # run all tests and lints
...
  py36: commands succeeded
  py37: commands succeeded
  py38: commands succeeded
  py39: commands succeeded
  flake8: commands succeeded
  black: commands succeeded
  mypy: commands succeeded
  congratulations :)
```

```
$ pip install tox
$ tox -e flake8 -e black -e mypy  # run lints
...
  flake8: commands succeeded
  black: commands succeeded
  mypy: commands succeeded
  congratulations :)
```

See the tox documentation for more details.

https://tox.readthedocs.io/en/latest/

**Comment by crcrpar** [comment]
Hi @c-bata,

It sounds cool to me and I have one question.
`checks.sh` has an option of `-u` with which the script fixes on behalf of us. Does tox have any equivalent options or settings?

**Comment by c-bata** [comment]
No, probably tox does not provide such an option. Code formatting is the out of responsibility of tox.

**Comment by crcrpar** [comment]
`checks.sh` mitigates the burden of following Optuna's guideline by providing formatting as well as code check and installing dependencies, which is enough to provide rather than tox.ini.

**Comment by c-bata** [comment]
OK. Thank you for your feedback.
I'm still not sure if we should still keeps `checks.sh` on repository root (In my opinion, it's enough just updates documentation about how to run auto-formatters). But for now, I opened #2024 without removing checks.sh.

**Comment by crcrpar** [comment]
> In my opinion, it's enough just updates documentation about how to run auto-formatters

Could you elaborate on this as I don't think https://github.com/optuna/optuna/blob/master/CONTRIBUTING.md#checking-the-format-coding-style-and-type-hints is up-to-date? :)

**Comment by c-bata** [comment]
I mean like this:

---

### Checking the Format, Coding Style, and Type Hints

Code is formatted with [black](https://github.com/psf/black),
and docstrings are formatted with [blackdoc](https://github.com/keewis/blackdoc).
Coding style is checked with [flake8](http://flake8.pycqa.org) and [isort](https://pycqa.github.io/isort/),
and additional conventions are described in the [Wiki](https://github.com/optuna/optuna/wiki/Coding-Style-Conventions).
Type hints, [PEP484](https://www.python.org/dev/peps/pep-0484/), are checked with [mypy](http://mypy-lang.org/).

You can check the format, coding style, and type hint via tox like below.

```
$ pip install tox
$ tox -e flake8 -e black -e blackdoc -e isort -e mypy
```

If you catch format errors, you can automatically fix them by auto-formatters.

```bash
# Install the tools for auto-format.
$ pip install .[checking]

$ black .     # Fix the format by black.
$ blackdoc .  # Fix the format of docstring by blackdoc.
$ isort .     # Fix the import order by isort.

```

**Comment by crcrpar** [comment]
@c-bata Do you want to add the change you suggest to CONTRIBUTING.md?

**Comment by c-bata** [comment]
Yes. I think it's better to update CONTRIBUTING.md.
