### ISSUE TITLE
Add other additional metrics / ... inside mlflow 

### ISSUE THREAD

**Issue by slamer59** [optuna/optuna#2016]
Objective function only return one metrics for optimizing.

## Motivation

It can be interesting for mlflow point of view to add other metrics / tags / etc. 

## Description

We could easily implement is passing to _trial.user_attrs_ addional info then passing them to _mlflow.log_***_

https://github.com/yqian4/optuna/blob/9291b0d0a990b0e66af978f2ca90f6883764afbd/optuna/integration/mlflow.py#L114

adding something like this:
```
            if "additional_metrics" in trial.user_attrs:
               mlflow.log_metrics(trial.user_attrs["additional_metrics"])

```

to
https://www.mlflow.org/docs/latest/python_api/mlflow.html#mlflow.log_metrics

adding something like this inside the obbjective function:
```
def objective(trial):
   additional_metrics = {}
   r2 = r2_score(y_test,y_pred) 
   additional_metrics['r2'] = r2
...    
   trial.set_user_attr('additional_metrics', additional_metrics)
```

**Comment by toshihikoyanase** [comment]
Sounds good!

The API will be something like follows:
```python
callback = MLflowCallback(tracking_uri="http://127.0.0.1", metric_name="accuracy", report_user_attrs=True)
```

or

```python
callback = MLflowCallback(tracking_uri="http://127.0.0.1", metric_name="accuracy", report_user_attrs=["r2", "loss"])
```

@harupy What do you think of it?
