### ISSUE TITLE
Support Python 3.9 with integration modules and optional dependencies

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#2034]
Monitor below libraries to keep tests-integration and examples ci up-to-date

"locally confirmed" means `docker run --rm python:3.9-buster bash -c "pip install <library>"` did not raise exceptions. I didn't check the PyPI or conda page.
I have NOT checked the corresponding examples run successfully or not.

Check means the corresponding example and integration if exists work and CI gets updated.

- [x] scikit-learn: locally confirmed
- [ ] PyTorch: v1.8.0 has been released. Once the currently supported python versions get v1.8.0, let's do this. rel: https://github.com/optuna/optuna/issues/2454
- [ ] TensorFlow: https://github.com/tensorflow/tensorflow/issues/44485 (trending toward TF2.5?)
- [ ] mxnet: I know nothing.
- [ ] catboost: https://github.com/catboost/catboost/issues/1491#issuecomment-729521190
- [ ] dask: locally confirmed
- [ ] lightgbm: locally confirmed
- [ ] xgboost: locally confirmed
- [ ] mlflow: locally confirmed
- [ ] plotly: Not in their `.circleci/config.yml`

Optuna itself can be installed: #1908

**Comment by hvy** [comment]
Updated the title to be a bit more specific.

**Comment by 0x41head** [comment]
Is anyone working on this issue currently ? If not I would like to pick it up.

**Comment by crcrpar** [comment]
No.
It's much more than appreciated ☺️

**Comment by 0x41head** [comment]
@crcrpar I was confused as to what I should do with packages like xgboost, which are already updated to the latest version and are supported python 3.9. Do I need to make any changes anywhere ?

**Comment by crcrpar** [comment]
In short, what we need to do is to update https://github.com/optuna/optuna/blob/master/.github/workflows/tests-integration.yml and https://github.com/optuna/optuna/blob/master/.github/workflows/examples.yml to assure that Optuna's integrations and examples work well on Python3.9

**Comment by nzw0301** [comment]
I believe that this PR has been resolved. Let me close this.
