### ISSUE TITLE
Start time is wrong when calculating trials added by `enqueue_trial`.

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#2036]
I have a study with 30 trials. I read this study with all trials and use `enqueue_trial` to create a new study and add the best 10 trials. Then I start optuna to calculate the results on all 10 trials of the new study.

I observe that the logged "datetime_start" of all 10 trials is the same (which is wrong since the runs need a significant amount of time). After the 10 enqued runs the time is logged correctly for trial 11 and so on.

I am using optuna 2.3.0 from pip.

**Comment by nzw0301** [comment]
Could you share your minimal example to reproduce your bug?

**Comment by PhilipMay** [comment]
I saw that the start time is set when the trial is enqued. IMO it should be set when the state changes from WAITING to RUNNING.

**Comment by PhilipMay** [comment]
> Could you share your minimal example to reproduce your bug?

Just take an optuna study with trials and enque them to an other study. You will see that starting time is set.
Starting time should be set when the state changes to running. Not when enqued (WAITING).

**Comment by nzw0301** [comment]
Like this?

```python
import optuna
import time

def objective(trial):
    x = trial.suggest_uniform("x", 0, 10)
    time.sleep(0.5)
    return x ** 2


study = optuna.create_study()

study.optimize(objective, n_trials=10)


new_study = optuna.create_study()
for frozen_trial in study.trials:
    
    new_study.enqueue_trial(frozen_trial.params)

new_study.optimize(objective, n_trials=20)
```

**Comment by nzw0301** [comment]
Thanks, so like this

```python
import optuna
import time


def objective(trial):
    x = trial.suggest_uniform("x", 0, 10)
    time.sleep(1)
    return x ** 2

study = optuna.create_study(study_name='example-study', storage='sqlite:///example.db')
study.optimize(objective, n_trials=10)


new_study = optuna.create_study(study_name='example-study', storage='sqlite:///example.db', load_if_exists=True)
for frozen_trial in study.trials:
    new_study.enqueue_trial(frozen_trial.params)

new_study.optimize(objective, n_trials=10)


print("show all `datetime_start`")
for i in range(len(new_study.trials)):
    print(new_study.trials[i].datetime_start)
```

Output:
```
show all `datetime_start`
2020-11-18 17:57:42.280086
2020-11-18 17:57:43.315864
2020-11-18 17:57:44.345529
2020-11-18 17:57:45.374185
2020-11-18 17:57:46.403691
2020-11-18 17:57:47.433724
2020-11-18 17:57:48.461977
2020-11-18 17:57:49.489054
2020-11-18 17:57:50.517336
2020-11-18 17:57:51.547932
2020-11-18 17:57:52.595424
2020-11-18 17:57:52.605769
2020-11-18 17:57:52.612032
2020-11-18 17:57:52.617892
2020-11-18 17:57:52.624796
2020-11-18 17:57:52.630669
2020-11-18 17:57:52.636577
2020-11-18 17:57:52.642492
2020-11-18 17:57:52.647706
2020-11-18 17:57:52.653105
```

Note that the optuna's version is [latest](https://github.com/optuna/optuna/tree/af7f15764bfce658c8caabdeff5067b9b0bc40bc).

**Comment by PhilipMay** [comment]
Mire like this:

```python
import optuna
import time

def objective(trial):
    x = trial.suggest_uniform("x", 0, 10)
    time.sleep(5)
    return x ** 2

study = optuna.create_study(study_name='example-study', storage='sqlite:///example.db')
study.optimize(objective, n_trials=10)

# quit and restart python

old_study = optuna.create_study(study_name='example-study', storage='sqlite:///example.db', load_if_exists=True)

trials = [t for t in old_study .get_trials() if t.value is not None]
trials = sorted(trials, key=lambda trial: trial.value, reverse=True)
trials = trials[:10]

del old_study 

new_study = optuna.create_study(study_name='example-study', storage='sqlite:///example.db', load_if_exists=True)
for frozen_trial in trials:
    new_study.enqueue_trial(frozen_trial.params)

# quit and restart python

new_study = optuna.create_study(study_name='example-study', storage='sqlite:///example.db', load_if_exists=True)
new_study.optimize(objective, n_trials=10)


print("show all `datetime_start`")
for i in range(len(new_study.trials)):
    print(new_study.trials[i].datetime_start)
```

**Comment by PhilipMay** [comment]
@nzw0301 have you been able to reproduce this?

**Comment by nzw0301** [comment]
> I observe that the logged "datetime_start" of all 10 trials is the same 

You mean `datetime_start` of all enqueued 10 trials are exact same value among them, do you? If so, I cannot reproduce that.

**Comment by c-bata** [comment]
Thank you @PhilipMay and @nzw0301 for your discussions.

As @PhilipMay observed, `datetime_start` is set the time when trials are enqueued, not the time when the state changed to `RUNNING`.

> I saw that the start time is set when the trial is enqued. IMO it should be set when the state changes from WAITING to RUNNING.

Thank you for your suggestion. I think it is worth considering to change the behavior though I have some concerns:

* It is a breaking change so we need to fix it carefully.
* How we keep the time when the trial is enqueued?
* It is required to change the [RDB schema](https://github.com/optuna/optuna/blob/2c23679b19695baf1256b76e0e59d426dd644144/optuna/storages/_rdb/models.py#L168).
* It is required to fix the calculation logic of `StudySummary.datetime_start`.

**Comment by PhilipMay** [comment]
Well - I should add that this issue also has the side-effect that Optunas calculation for the `duration` is wrong. Because duration is the difference of `datetime_complete` and `datetime_start`.

> How we keep the time when the trial is enqueued?

Just do not set the time when the trial is enqueued. Nobody cares of enqueue time...

**Comment by hvy** [comment]
Sounds like a reasonable change to me although I agree that we should proceed with some care, since the allowed states for the trial will be changed. As for the storage schema, I don't think that it needs to be altered. It should be enough to change the logic of `enque_trial`, `create_trial` and `FrozenTrial._validate` since the columns is already nullable.

**Comment by chenghuzi** [comment]
> Sounds like a reasonable change to me although I agree that we should proceed with some care, since the allowed states for the trial will be changed. As for the storage schema, I don't think that it needs to be altered. It should be enough to change the logic of `enque_trial`, `create_trial` and `FrozenTrial._validate` since the columns is already nullable.

Probably we need to change the storage part too? Because we may need to set the trial `datetime_start` in `_run_trial` or `_ask` since it's the moment right before evaluation. If that's the case, we also need to add a parameter in `_update_trial` to modify the `datetime_start `.

**Comment by chenghuzi** [comment]
So a simple way I can see to implement this is just modify the `set_trial_state` method: update the `datetime_start` whenever the state is `RUNNING`. Then call this method after `study._ask()` in `_run_trial`.
