### ISSUE TITLE
ChainerMN unit tests not accounted for in codecov

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#2038]
## Motivation

codecov is used to measure the unit test code coverage. However, the ChainerMN tests are seemingly not accounted. See https://github.com/optuna/optuna/pull/2027#discussion_r526573203.

## Description

ChainerMN tests should be taken into account by codecov.

**Comment by jeromepatel** [comment]
@hvy I am interested in working on this issue. if you could guide me on this, it would be helpful.

**Comment by hvy** [comment]
That'd be great. I have not yet surveyed how to go about doing this. Do you have any thoughts or ideas? I was briefly imagining creating multiple code coverage outputs and merge them to create the report.

**Comment by hvy** [comment]
> I am not that much familiar with GitHub Actions or code coverage but I have looked at previous workflow PRs and the progress of Codecov and understood how that works at the higher-level details, I'll let you know once I have a specific solution for the coverage in mind. 

Sounds great.

> But I would be more than happy to implement your approach if you could explain the details of your solution.

Again, I have not surveyed or tested this yet but was looking at https://docs.codecov.io/docs/merging-reports.

**Comment by jeromepatel** [comment]
@hvy I think I have found the solution, my approach is similar to yours, that is we can merge the coverage report of ChainerMN with the previous report. 
In brief, [this issue](https://github.com/codecov/codecov-node/issues/87) and [this doc](https://docs.codecov.io/docs/merging-reports) suggests that merging on codecov is automatically, so I think we don't need to worry about that part. 
For the pytest coverage XML report part for ChainerMN, I have found [here in docs](https://pytest-cov.readthedocs.io/en/latest/readme.html#coverage-data-file) that apparently they have `--cov-append` argument which appends the report to previous report, so I think this should work for ChainerMN:
`mpirun -n 2 -- pytest --cov-report=xml --cov-append tests/integration_tests/test_chainermn.py`
Your suggestions are most welcome, and please guide me on whether I should submit a PR for the same or not.

**Comment by hvy** [comment]
@jeromepatel, sorry for the delayed response. That sounds like a starting point to me. We probably have to make sure that works with `mpirun`. I can take a look if you could send a PR.

**Comment by hvy** [comment]
Let me close this issue. It was resolved by https://github.com/optuna/optuna/pull/2535 by @jeromepatel. Thanks!
