### ISSUE TITLE
Duplicate values in GridSampler with multiple machines

### ISSUE THREAD

**Issue by VitorGuizilini-TRI** [optuna/optuna#2039]
Hi, once again thanks for the great library. 

I am integrating Optuna with my codebase, including distributed training in multiple machines using MySQL in AWS. Everything seems to be working correctly, I can create one single database that is shared for different trials. However, when I use GridSampler each machine gets duplicated suggestions, is this expected?

**Comment by hvy** [comment]
Thanks for raising a ticket about this. What you're seeing is expected behavior. I see however that it's not very intuitive so I decided to leave a note in the documentation, at least, in #2040. What do you think?

**Comment by hvy** [comment]
On a separate note, there are some comments in the implementation addressing this behavior https://github.com/optuna/optuna/blob/master/optuna/samplers/_grid.py.

**Comment by VitorGuizilini-TRI** [comment]
Makes sense, thank you very much. Is there a way to shuffle the grid suggestions differently in each machine? Right now it seems like they are all suggesting in the same sequence, so all runs after the first iteration are duplicated.

**Comment by hvy** [comment]
Are you specifying random seeds somewhere in your code? [`GridSampler` currently uses Python's `random`](https://github.com/optuna/optuna/blob/master/optuna/samplers/_grid.py) so you could try to manual set the seed with `random.seed`.

**Comment by not522** [comment]
We can add feature to prioritize grids that are not yet running. It reduces duplicated trials during distributed optimization.
