### ISSUE TITLE
Issue/Question with TPESampler and HyperBandPruner

### ISSUE THREAD

**Issue by mhashas** [optuna/optuna#2046]
Hello,

I am using the optuna integration with trains (https://github.com/allegroai/trains) for hyper-parameter search optimization. Currently, I am using TPESampelr and HyperBandPruner. The issue that I have is that the same experiment is repeated multiple times (see picture below). We have set a fixed seed, so repeating an experiment always results in the same outcome, and as such inefficient. From the HyperBand documentation (https://optuna.readthedocs.io/en/latest/reference/generated/optuna.pruners.HyperbandPruner.html), I (half) understand that this is the expected behaviour. Is this true? If so, is there any way to prevent this or this is just how the pruning algorithm works? Lastly, any suggestions for pruners that I should use? 

Thanks :) 
 
![Screenshot 2020-11-25 at 09 38 06](https://user-images.githubusercontent.com/13119609/100203425-e0081c00-2f02-11eb-9e48-8be1d3d33d7b.png)

Maybe this is useful, these are the parameters with which the optuna optimizer is called. Just shooting in the dark here, but should the compute time limit be set?

![Screenshot 2020-11-25 at 09 53 07](https://user-images.githubusercontent.com/13119609/100204372-16926680-2f04-11eb-9271-d9a43bc3aa99.png)

**Comment by hvy** [comment]
I would generally expect an experiment to behave more or less deterministically if a seed is fixed. Are you able to use different seeds for different experiments? As for the compute time limit, I don't think you have to, if you're specifying `total_max_jobs` (looking at https://github.com/allegroai/trains/blob/master/trains/automation/optuna/optuna.py) since that should tell Optuna to stop after a certain number of trials. However, I'm not an expert on Allegro Trains so I could be wrong about this.

**Comment by mhashas** [comment]
Hi @hvy,

Thanks for responding so quickly. `total_max_jobs` is indeed specified. I have switched now to a median pruner and I still experience the same issue. Although there are a lot of different experiments in the beginning, towards the end the same experiment is being repeated. This probably means that the TPESampler is converging? Is that correct? 

The experiments behaves indetical if the seed is fixed, hence why running the same experiment twice is useless. We can use different seeds for different experiments, however we wouldl like to explore the search space a bit more. I guess we should just use an old fashioned random sampler then? 

Radu

**Comment by hvy** [comment]
Ah, seems like I misunderstood what you meant with an experiment. So you have several trials towards the end of a study which all suggest the same parameter configurations? If TPE would be converging, you'll likely be observing similar configurations, but is it the case that the configurations are completely identical? That sounds a bit unlikely with TPE unless your search space is complete discrete. And yes, with the random sampler, that shouldn't happen neither.

**Comment by mhashas** [comment]
Hi @hvy,

You were right, our search space was complete discrete. By making some variables continuous, now we don't experience the issue anymore. Thanks :)

**Comment by hvy** [comment]
Great, that's good to know 👍
