### ISSUE TITLE
Update `Dockerfile` of MLflow Kubernetes examples

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#2049]
Now Dockerfile of mlflow kubernetes example (https://github.com/optuna/optuna/blob/master/examples/kubernetes/mlflow/Dockerfile) gets outdated so I'd love it to be latest if possible 🙂 

If you update the Dockerfile, I'd like you to try `optuna/optuna:py3.7-dev` image as in the `NOTE` by me as `optuna/optuna:py3.7-dev` helps us maintain the Dockerfile.
If there's a need to update the `run.sh` to use `optuna/optuna:py3.7-dev`, feel free to do that.

**Comment by 0x41head** [comment]
Do I follow the same procedure as I did with #2375 ?

**Comment by crcrpar** [comment]
Thank you for finding this. I think just bumping up PyTorch suffices: https://github.com/optuna/optuna/blob/30161b238b33b32300aedfc8364ef511b5849543/examples/kubernetes/mlflow/Dockerfile#L8-L10
