### ISSUE TITLE
Update `Dockerfile` of Kubernetes simple example

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#2050]
As many projects stop the support of Python3.5, it's better to update the base image of https://github.com/optuna/optuna/blob/master/examples/kubernetes/simple/Dockerfile.

If possible, I'd love you to investigate whether `optuna/optuna:py3.7-dev` can be used as its base images since `optuna/optuna:py3.7-dev` will almost free us from maintaining `examples/kubernetes/simple/Dockerfile`.

**Comment by 0x41head** [comment]
@crcrpar I would love to look into this issue. However, I have no idea as to how I should go about it. Could you possibly guide me ?

**Comment by crcrpar** [comment]
I'd first try `optuna/optuna:py3.7-dev` as a base image of the mentioned Dockerfile and see whether that works or not.
To do this, I'll replace `FROM python:3.5-slim-buster` with `FROM optuna/optuna:py3.7-dev` and remove https://github.com/optuna/optuna/blob/master/examples/kubernetes/simple/Dockerfile#L5 before run the example.

If it's not working, investigate what's missing/wrong.

**Comment by 0x41head** [comment]
Everything seems to be working just fine. No issues in building the Dockerfile in my local environment.
Here are the changes in my local repo: https://github.com/0x41head/optuna/blob/kb_dockerfile/examples/kubernetes/simple/Dockerfile
If everything seems fine, I can start creating a PR.

**Comment by crcrpar** [comment]
Sounds good :+1:

If training also worked as well, I'd love you to create a pull request.

**Comment by 0x41head** [comment]
My PR took care of this issue . Could you please close it @crcrpar ?

**Comment by crcrpar** [comment]
Thanks for pinging me, and kudos to your work.
