### ISSUE TITLE
Color map is unexpectedly flipped in contour plot

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#2057]
In contour plots, the color map is flipped between stable and latest.

### Latest

https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.plot_contour.html

![Screen Shot 2020-12-01 at 22 16 20](https://user-images.githubusercontent.com/5164000/100745590-da3e9900-3422-11eb-9ee2-a7acd466eef5.jpg)

## Stable

https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_contour.html#optuna.visualization.plot_contour

![Screen Shot 2020-12-01 at 22 16 33](https://user-images.githubusercontent.com/5164000/100745646-f2161d00-3422-11eb-9d6c-c1ae6782512c.jpg)

If this change was introduced unintentionally, it would be better to make the color map the same as in the stable version.

===

Do we have to make color maps of plots consistent? For example, the high-value points become blue in the slice plot but the lines with the high objective values are plotted with white in the coordinate plot.

- slice plot: https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_slice.html#optuna.visualization.plot_slice
- coordinate plot: https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_parallel_coordinate.html

**Comment by GuidoBartoli** [comment]
Yes, I can confirm this behaviour. With the previous version I was looking for bright zones while using `direction=maximize`, while now the colormap is inverted and the zones with higher objective values are dark blue. That is functionally equivalent, but I think the previous visualization was much more visually intuitive.

**Comment by 0x41head** [comment]
If no one is working on this I would like to give it a shot.

**Comment by GuidoBartoli** [comment]
The optimal behaviour could be that the brighter areas are minimum/maximum according to optimization direction, so regardless of the settings, you always look for going from dark blue to white.

**Comment by himkt** [comment]
Resolved in https://github.com/optuna/optuna/pull/2291. Thank you @0x41head!

**Comment by fogx** [comment]
i'm still having this issue in 2.10:
```study = optuna.create_study( direction="minimize")
# output: <StudyDirection.MINIMIZE: 1>
# ...
fig = plot_contour(study, ["epochs", "adam_lr"])```

![image](https://user-images.githubusercontent.com/10303647/152178361-c65e8e76-8ff8-4576-b2a7-b66cc7810a17.png)

i tried to change the coloraxes with `fig.update_coloraxes(reversescale=True)` but had no luck. Am i doing something wrong, or is this still a bug?
