### ISSUE TITLE
The suggest_X methods should be agnostic of the Trial class

### ISSUE THREAD

**Issue by flipdazed** [optuna/optuna#2072]
The methods `suggest_` are more generic than the Trial class.
One should be able to call `suggest_` without needing a Trial instantiation and a study

## Motivation

I want to average the objective function over nearby parameters to avoid picking an anomalous parameter choice / fluke that is fitting noise rather than an underlying process driving the distribution of the model

https://stackoverflow.com/questions/65180851/averaging-an-optuna-objective-function-over-the-nearby-parameter-volume

## Description

Break away the `suggest_` methods from the Trial class such that they can be called as independent functions

## Alternatives (optional)

Could allow an instantiation of a Trial without a study but this conflates the existing code IMO

**Comment by toshihikoyanase** [comment]
Thank you for your feature request.

> One should be able to call `suggest_` without needing a Trial instantiation and a study

IMO, samplers basically use optimization history, and `study` is required at least.

> I want to average the objective function over nearby parameters to avoid picking an anomalous parameter choice / fluke that is fitting noise rather than an underlying process driving the distribution of the model

Interesting! I created a [notebook](https://colab.research.google.com/drive/15etyq8M_OI460s91DQunz1h37qysYml7?usp=sharing
) to confirm my understanding. I think this technique is useful if we can evaluate the objective function with small computational resources. 

The objective function has two peaks. The left peak is the global maxima, but it is sensitive to perturbations while the right peak is broad, but not the global maxima.

![image](https://user-images.githubusercontent.com/3255979/101442882-86224000-395f-11eb-949f-4fa39ac3a07d.png)

If we simply optimize it using Optuna, the left peak is returned as the best trial.

![image](https://user-images.githubusercontent.com/3255979/101443163-1d879300-3960-11eb-8ccb-05602e04e70b.png)

If we average ten objective values around the suggested point, the right peak is returned as the best trial as expected. 

![image](https://user-images.githubusercontent.com/3255979/101443195-2d9f7280-3960-11eb-88ac-a9537f1ce89e.png)

When I implement this notebook, I don't think trial-agnostic suggest API is mandatory. Could you tell me how do you plan to use it?

**Comment by flipdazed** [comment]
Hi Yanase-san,

Thanks for careful consideration.
I am experimenting to see if using optuna makes sense for fitting parameters of trading models. I have ended up creating an objective function where I do a Truncated Multivariate normal sampling across the dimensions of all int/float suggestions (keeping categorical unchanged).

I take 10 samples (sub trials) from say 5% of the optuna suggestion range and average over these. This seems to improve performance. It would be good to have within the optuna framework though as I don’t currently have the sub trials stored by optuna.
