### ISSUE TITLE
Option to print best trial's parameters at end of each trial

### ISSUE THREAD

**Issue by brethvoice** [optuna/optuna#2073]
Rather than just reporting the best trial number and its objective function score at the end of each trial, allow a verbosity increase to print out more information, including and especially the parameters of the best trial thus far if it was not just completed.

## Motivation

During days- or weeks-long study execution, hardware often fails.  In these cases it might be impossible to scroll far enough back to see the parameters of the best trial, especially when each trial involves training of a machine learning model for a variable number of epochs.

## Description

Add a verbosity level to the study which would allow the best trial's parameters to be printed at the end of any trial which was not the best one thus far, along with the best trial number and objective function score (which are already printed).

## Additional context (optional)

P.S. You might also include in this verbosity scheme the option to print out each trial's hyper-parameters before it begins.  I am currently doing this by collecting the chosen hyper-parameters into a dictionary and printing them to the screen before using the .fit() method of the model constructed and compiled using them.

**Comment by toshihikoyanase** [comment]
@brethvoice

Thank you for your feature request.

Optuna showed the current best parameters as can be seen in the past [reference](https://optuna.readthedocs.io/en/v0.19.0/tutorial/first.html), but we decided to change the log messages in terms of usability (#965). Instead, we introduced the `callbacks` argument to [Study.optimize](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize). It is called at the end of each trial, and you can show the detailed log message, for example, as follows:

```python
def print_best_callback(study, trial):
    print(f"Best value: {study.best_value}, Best params: {study.best_trial.params}")

study = optuna.create_study()
study.optimize(objective, n_trials=10, callbacks=[print_best_callback])
```

Do you think the `callbacks` argument resolves your issue?

> During days- or weeks-long study execution, hardware often fails. In these cases it might be impossible to scroll far enough

You may already know, but I recommend [`RDBStorage`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.storages.RDBStorage.html#optuna.storages.RDBStorage) to persist the optimization history. If we use it, we can retrieve the best trial even if the optimization processes fail.

**Comment by brethvoice** [comment]
> @brethvoice
> 
> Thank you for your feature request.
> 
> Optuna showed the current best parameters as can be seen in the past [reference](https://optuna.readthedocs.io/en/v0.19.0/tutorial/first.html), but we decided to change the log messages in terms of usability (#965). Instead, we introduced the `callbacks` argument to [Study.optimize](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize). It is called at the end of each trial, and you can show the detailed log message, for example, as follows:
> 
> ```python
> def print_best_callback(study, trial):
>     print(f"Best value: {study.best_value}, Best params: {study.best_trial.params}")
> 
> study = optuna.create_study()
> study.optimize(objective, n_trials=10, callbacks=[print_best_callback])
> ```
> 
> Do you think the `callbacks` argument resolves your issue?
> 
> > During days- or weeks-long study execution, hardware often fails. In these cases it might be impossible to scroll far enough
> 
> You may already know, but I recommend [`RDBStorage`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.storages.RDBStorage.html#optuna.storages.RDBStorage) to persist the optimization history. If we use it, we can retrieve the best trial even if the optimization processes fail.

@toshihikoyanase That is exactly what I was looking for!  Thank you for the help...sorry for the trouble.

**Comment by brethvoice** [comment]
Here is the code I finally used that worked:
```
def print_best_trial_so_far(study, trial):
    print('\nBest trial so far used the following hyper-parameters:')
    for key, value in study.best_trial.params.items():
        print('{}: {}'.format(key, value))
    print('to achieve objective function score of {}\n'.format(study.best_trial.value))
study.optimize(
    objective,
    n_trials=MAXIMUM_NUMBER_OF_TRIALS_TO_RUN,
    timeout=MAXIMUM_SECONDS_TO_CONTINUE_STUDY,
    gc_after_trial=True,
    callbacks=[print_best_trial_so_far],
    )

```

**Comment by brethvoice** [comment]
Also I use the following code at end of a study (in case it is helpful for anyone else) to see the history of improved trials, etc.
```
print('Study statistics:  ')
print('\n\nBest trial number was {}\n\n'.format(study.best_trial))
print('\n\nBest categorical accuracy was {}\n\n...'.format(study.best_trial.value))
print('\n\nParameters: ')
for key, value in study.best_trial.params.items():
    print('{}: {}'.format(key, value))
completed_trials = [
    t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE
]
print('Number of completed trials is {}'.format(len(completed_trials)))
pruned_trials = [
    t for t in study.trials if t.state == optuna.trial.TrialState.PRUNED
]
print('Number of pruned trials is {}'.format(len(pruned_trials)))
first_trial = study.trials[0]
best_score_so_far = first_trial.value
print('\n\nImproved scores after first trial:')
number_of_trials = len(study.trials)
for report_index in range(1, number_of_trials):
    trial_to_report = study.trials[report_index]
    score_of_trial_to_report = trial_to_report.value
    improved_score = (score_of_trial_to_report > best_score_so_far)
    if improved_score:
        best_score_so_far = score_of_trial_to_report
        print('\nTrial {}:'.format(trial_to_report.number), end=' ')
        print('began at {}.'.format(trial_to_report.datetime_start))
        print('Score was {},'.format(trial_to_report.value), end=' ')
        print('and its parameters were: {}\n'.format(trial_to_report.params))

```
It is partly based on tutorial examples but more verbose.
