### ISSUE TITLE
Update xgboost callback for xgboost 1.3.

### ISSUE THREAD

**Issue by trivialfis** [optuna/optuna#2077]
Hi all,

xgboost is about to make its 1.3 release, which has adopted a new callback interface.  Old callback is still supported but user will see a warning about deprecation notice.  I will submit a PR for supporting latest callback interface for xgboost next week.  This issue is for noticing users/developers here. ;-)

I don't know which category I should use for this issue and feature request seems by far closest.  Sorry if it's the wrong category.

**Comment by crcrpar** [comment]
Much appreciated!
