### ISSUE TITLE
multi_objectives stop function

### ISSUE THREAD

**Issue by guzuomuse** [optuna/optuna#2086]
just like single object the study has a **stop** method to exit the optimization but the multi_objective.study has no this feature

**Comment by HideakiImamura** [comment]
Thanks for the feature request! Currently, we plan to integrate the multi-objective module with the standard Optuna module. For your requested feature, PR #1994 will be merged soon. (It will be released in v2.4.0) The `Study.stop` for the multi-objective optimization will be available from v2.4.0.

**Comment by guzuomuse** [comment]
thanks
