### ISSUE TITLE
Implement `Study._has_multi_objective()` to check whether study has multiple objectives

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#2130]
## Motivation
For developers, it is useful to have a method to determine if a study has more than one objective, which is easy to understand. See https://github.com/optuna/optuna/pull/2117#pullrequestreview-556116066 for the detail.

The name of the method can be improved.

**Comment by himkt** [comment]
Resolved by #2142. (Thank you @nyanhi!)
