### ISSUE TITLE
Pruning unwanted results without dataset

### ISSUE THREAD

**Issue by aero-108** [optuna/optuna#2138]
Hi,
can anyone give me a help:
1. how to stop prune and automatically stop iterations let's say after 3rd trial ?
2. how to avoid same 'x' value ? (now it's running duplicate trials)
3. how to a gradually increase x ? (all trials should be in order 0, 1, 2, 3, 4, 5, 6, etc)

```
import optuna

def objective(trial: optuna.Trial):
    x = trial.suggest_int('x', 0, 100)
    return x

study = optuna.create_study(pruner=optuna.pruners.MedianPruner())
study.optimize(objective, n_trials=100)
```

any help is appreciated!

**Comment by nzw0301** [comment]
@aero-108  I would like to answer the first and third questions:

## 1
Use `n_startup_trials`:  `MedianPruner(n_startup_trials=3)`. You can find details on [`MedianPrunner` page](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.pruners.MedianPruner.html#optuna.pruners.MedianPruner).


## 3

Change the definition of the objective gradually for example, 

```python
import optuna

study = optuna.create_study(pruner=optuna.pruners.MedianPruner())
for i in range(1, 100):
    
    def objective(trial: optuna.Trial):
        x = trial.suggest_int('x', 0, i)
        return x
    
    study.optimize(objective, n_trials=2)
```

Another option is to define an objective function with arguments: See [this details](https://optuna.readthedocs.io/en/stable/faq.html#how-to-define-objective-functions-that-have-own-arguments) for details.

**Comment by aero-108** [comment]
> @aero-108 I would like to answer the first and third questions:
> 
> ## 1
> Use `n_startup_trials`: `MedianPruner(n_startup_trials=3)`. You can find details on [`MedianPrunner` page](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.pruners.MedianPruner.html#optuna.pruners.MedianPruner).
> 
> ## 3
> Change the definition of the objective gradually for example,
> 
> ```python
> import optuna
> 
> study = optuna.create_study(pruner=optuna.pruners.MedianPruner())
> 
> for i in range(1, 100):
>     
>     def objective(trial: optuna.Trial):
>         x = trial.suggest_int('x', 0, i)
>         return x
>     
>     study.optimize(objective, n_trials=2)
> ```
> 
> Another option is to define an objective function with arguments. Please see [this section](https://optuna.readthedocs.io/en/stable/faq.html#how-to-define-objective-functions-that-have-own-arguments) for details.

1. MediaPruner still doesn't work.
3. objective function with arguments doesn't help to gradually increase values, they are all random and many values duplicating.


```
class Objective(object):
    def __init__(self, min_x, max_x):
        self.min_x = min_x
        self.max_x = max_x

    def __call__(self, trial):
        print('x')
        x = trial.suggest_int('x', self.min_x, self.max_x)

        if trial.should_prune():
            raise optuna.TrialPruned()
        return x


study = optuna.create_study(pruner=optuna.pruners.MedianPruner(n_startup_trials=3))
study.optimize(Objective(0, 100), n_trials=100)
```

**Comment by nzw0301** [comment]
# 1

Interesting. I'm not sure why the parameter does not work...


# 3

How about this?

```python
import optuna

study = optuna.create_study(pruner=optuna.pruners.MedianPruner())

for i in range(100):
    
    def objective(trial: optuna.Trial):
        x = trial.suggest_int('x', i, i)
        return x
    
    study.optimize(objective, n_trials=1)
```

**Comment by nzw0301** [comment]
Related to `1`, you need to call `trial.report` function to prune your trial:

```python
class Objective(object):
    def __init__(self, min_x, max_x):
        self.min_x = min_x
        self.max_x = max_x

    def __call__(self, trial):
        print('x')
        x = trial.suggest_int('x', self.min_x, self.max_x)

        trial.report(x, 0)  # this line

        if trial.should_prune():
            raise optuna.TrialPruned()
        return x


study = optuna.create_study(pruner=optuna.pruners.MedianPruner(n_startup_trials=3))
study.optimize(Objective(0, 100), n_trials=100)
```

The output is like this

```
[I 2020-12-22 15:55:51,188] A new study created in memory with name: no-name-27aca0c1-b5a2-4280-80ea-55dbb1d24809
[I 2020-12-22 15:55:51,190] Trial 0 finished with value: 1.0 and parameters: {'x': 1}. Best is trial 0 with value: 1.0.
[I 2020-12-22 15:55:51,191] Trial 1 finished with value: 2.0 and parameters: {'x': 2}. Best is trial 0 with value: 1.0.
[I 2020-12-22 15:55:51,192] Trial 2 finished with value: 3.0 and parameters: {'x': 3}. Best is trial 0 with value: 1.0.
[I 2020-12-22 15:55:51,193] Trial 3 pruned. 
...
```

**Comment by nzw0301** [comment]
To avoid sampling the same value `x` and sampled `x`s have ordered, how about the following example?

```python
import optuna

study = optuna.create_study(pruner=optuna.pruners.MedianPruner(n_startup_trials=10, n_warmup_steps=0))

def objective(trial: optuna.Trial):
    x = trial.suggest_int('x', 0, 100)
    
    trial.report(x, 0)
    if trial.should_prune():
        raise optuna.TrialPruned()
        
    return x

for i in range(100):
    study.enqueue_trial({"x": i})
    
    
study.optimize(objective, n_trials=100)
```
