### ISSUE TITLE
Some questions about optimizing local model with optuna

### ISSUE THREAD

**Issue by ErikZhang-9762** [optuna/optuna#2139]
Hi,

First of all, thank you for developing optuna!!!
I want to optimize the local model with optuna,
But I don't know how to use optuna to optimize the local model（Random forest）
Here is my code. I hope I can get your guidance！

[Question.zip](https://github.com/optuna/optuna/files/5727510/Question.zip)

I am a novice in the code, hope to get your help！
Thanks in advance for your help,

Sincerely

**Comment by toshihikoyanase** [comment]
Hi @Mr-X9

Thank you for your question.
You share your example with a zip file, but it has a potential security risk such as malware infection. Is it possible to use [Gist](https://gist.github.com/) or GitHub repository instead?

**Comment by Mr-X9** [comment]
Hi @toshihikoyanase

Here is the gist link：
https://gist.github.com/Mr-X9/f39fe8f5b22de8d208502613f0e1b072
Hope to get your guidance

I uploaded one RF.pkl The model is in the zip file
[RF.zip](https://github.com/optuna/optuna/files/5728643/RF.zip)

If there are still potential security issues, you can use your RF model instead

I don't know why there are potential security issues with zip files
Sincerely sorry if it bothers you
