### ISSUE TITLE
Trying to resume study throws ValueError: No trials are completed yet

### ISSUE THREAD

**Issue by yonatansc97** [optuna/optuna#2151]
Hi All,

I created a study on a remote machine, which ran for a couple of trials before it crashed as a result of connectivity issues.
I tried to resume this sudy as described here, using the joblib and pickle library: https://optuna.readthedocs.io/en/stable/faq.html.
This throws the following error:
```
Traceback (most recent call last):
  File "/home/yonatan/Desktop/yonas_code/dcnn/main.py", line 99, in <module>
    optuna_study(resume='24-12-20 11 02 12study.pkl')
  File "/home/yonatan/Desktop/yonas_code/dcnn/main.py", line 48, in optuna_study
    print(' Value: ', study.best_trial.value)
  File "/home/yonatan/anaconda3/envs/yonatan_env/lib/python3.8/site-packages/optuna/study.py", line 72, in best_trial
    return copy.deepcopy(self._storage.get_best_trial(self._study_id))
  File "/home/yonatan/anaconda3/envs/yonatan_env/lib/python3.8/site-packages/optuna/storages/_in_memory.py", line 275, in get_best_trial
    raise ValueError("No trials are completed yet.")
ValueError: No trials are completed yet.
```

## Expected behavior

The expected behaviour is that optuna would resume the optimization of th ovjective function, and consider the previous trials as a part of the study.
Note: There has been already 3 trials that finished, I confirmed so by visualizing them in TensorBoard.
![image](https://user-images.githubusercontent.com/52149642/103081135-01caf080-45e0-11eb-9d77-09d4c492cb85.png)

## Environment

- Optuna version: 2.3.0
- Python version: 3.8.0
- OS: Ubuntu 18.04
- Pytorch: 1.7.1

## Code that I wrote

I have a feeling I'm not using optuna correctly, so I'm attaching the code I wrote for the main.py
Note that the first run was with ```resume=False```, and only then do I use the ```resume='24-12-20 ...'```.

```
def objective(trial):
    # PyTorch Lightning will try to restore model parameters from previous trials if checkpoint
    # filenames match. Therefore, the filenames for each trial must be made unique.
    checkpoint_callback = pl.callbacks.ModelCheckpoint(
        Path('./model_dirs') / f'trial_{trial.number}',
        monitor='val_acc',
    )

    dm = HoobariDataModule(trial=trial)

    trainer = pl.Trainer(
        log_every_n_steps=20,
        logger=TensorBoardLogger('optuna_241220_tb_logs',
                                 name='',
                                 version=f'trial_{trial.number}',
                                 default_hp_metric=False),
        checkpoint_callback=checkpoint_callback,
        max_epochs=3,
        num_sanity_val_steps=0,
        check_val_every_n_epoch=1,
        gpus=1 if torch.cuda.is_available() else None,
        # callbacks=[metrics_callback,
        #            PyTorchLightningPruningCallback(trial, monitor='val_acc')]
    )

    model = resnet.resnet34(trial=trial)
    trainer.fit(model, dm)

    return model.val_metrics_track[-1]["val_acc"].item()


def optuna_study(resume=False):
    if resume:
        study = joblib.load(resume)
        print('Best trial until now:')
        print(' Value: ', study.best_trial.value)
        print(' Params: ')
        for key, value in study.best_trial.params.items():
            print(f'    {key}: {value}')
    else:
        study = optuna.create_study(direction='maximize',
                                    pruner=optuna.pruners.MedianPruner())
        joblib.dump(study, datetime.now().strftime('%d-%m-%y %H %M %S') +
                    'study.pkl')
    study.optimize(objective, timeout=60 * 60 * 24)

    print("Number of finished trials: {}".format(len(study.trials)))

    print("Best trial:")
    trial = study.best_trial

    print("  Value: {}".format(trial.value))

    print("  Params: ")
    for key, value in trial.params.items():
        print("    {}: {}".format(key, value))


if __name__ == "__main__":
    optuna_study(resume='24-12-20 11 02 12study.pkl')
```

**Comment by hvy** [comment]
Could you try dumping the study after the call to `Study.optimize`? What you're seemingly doing is always writing an empty study to a file, then, optimizing the study.

By the way, if you expect optimization to throw, you could try-catch `Study.optimize` and dump in `finally` or perhaps even better make use of the [`catch` argument to `Study.optimize`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize).

**Comment by hvy** [comment]
Let me close this issue as I think it should be fixed by the comment above and it's been stale. Don't hesitate to reopen or comment if it's still an issue.
