### ISSUE TITLE
How to find out best n_trials value

### ISSUE THREAD

**Issue by aero-108** [optuna/optuna#2160]
Hi,
how to find out best n_trials value for simple hyperparameter optimization ?
And based on this simple example perhaps someone can suggest how to do correct prunning here ?
It's never prune.....

```python
import optuna

try_cnt = {'i': 0}

def objective(trial: optuna.Trial):
    try_cnt['i'] += 1
    
    x1 = trial.suggest_int("x1", 0, 1000)
    x2 = trial.suggest_int("x2", 0, 1000)

    if trial.should_prune():
        raise optuna.TrialPruned()

    result = x1 + x2

    trial.report(result, try_cnt['i'])

    return result


study = optuna.create_study(sampler=optuna.samplers.TPESampler(),
                            pruner=optuna.pruners.MedianPruner(),
                            direction='minimize')

study.optimize(objective, n_trials=10000, n_jobs=1, show_progress_bar=False)

print('BEST', study.best_params)
```

**Comment by crcrpar** [comment]
You should call `trial.should_prune` after `trial.report`.

Though, first of all, pruning features are basically for objectives that report scores multiple times like https://github.com/optuna/optuna/blob/master/examples/pytorch_simple.py.

**Comment by hvy** [comment]
As for the value of `n_trials`, there's no single answer. But with the TPE sampler, and especially a trivial objective function, 10000 trials sounds like quite a lot. The order of 100 would probably do. In general, I would play around with the visualization function such as [`plot_optimization_history`](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_optimization_history.html#optuna.visualization.plot_optimization_history) to look at the convergence rate. To take it one step further, you can also omit the `n_trials` argument altogether, run the optimization indefinitely, and stop based on some arbitrary condition using a callback to `Study.optimize` instead (you in the callback function call `Stop.stop()` when the condition is met).
