### ISSUE TITLE
Example of using catch parameter in optimize()

### ISSUE THREAD

**Issue by eafpres** [optuna/optuna#2163]
I'm trying to address a numpy warning:
```
__main__:1: RuntimeWarning: overflow encountered in exp
```
that sometimes can occur in my objective function.  However, I'm having trouble understanding the correct format and content of the tuple to be passed to catch: in optimize().
So far, I cannot find a concrete example.
An example would be most appreciated!

**Comment by crcrpar** [comment]
Hi @eafpres 

I'm not quite sure I get your question enough, but an example would be as follows.

```python
import optuna


def objective(trial: optuna.trial.Trial) -> float:

    x = trial.suggest_float("x", 0, 1)
    if x < 0.5:
        raise RuntimeWarning
    return x


def main():
    study = optuna.create_study()
    study.optimize(objective, n_trials=10, catch=(RuntimeWarning,))


if __name__ == '__main__':
    main()
```

Feel free to correct me if I'm wrong :)

**Comment by eafpres** [comment]
Thank you. I was unclear why the argument is a tuple, but you show the second element as empty so I see what is needed now.

**Comment by LeZhengThu** [comment]
Hi, I have the same problem. I'm using Optuna to optimize the hyperparams of lstm policy in stable baselines. The lstm gradient blows out and throws an InvalidArgumentError and I want to skip it. So I use the code ``` study.optimize(objective, n_trials=100, catch=(InvalidArgumentError,)) ``` . Then I get an error ``` NameError: name 'InvalidArgumentError' is not defined
```. I wonder how to achieve my goal.

**Comment by crcrpar** [comment]
Hi @LeZhengThu I think `InvalidArgumentError` is implemented in some third-party library that you're using because it's not a Python standard exception class as per https://docs.python.org/3.8/library/exceptions.html.
And Google search told me that that class is implemented in TensorFlow according to https://www.tensorflow.org/api_docs/python/tf/errors/InvalidArgumentError.

So could you try adding `from tf.errors import InvalidArgumentError` to your script?

@HideakiImamura @himkt @nzw0301 for visibility

**Comment by LeZhengThu** [comment]
@crcrpar Thank you very much. That solves my problem.

**Comment by crcrpar** [comment]
@nzw0301 told me this: https://github.com/optuna/optuna/issues/2815

**Comment by MoritzLaurer** [comment]
I just had the same issue, but it was solved thanks to your responses @crcrpar, thanks!
I feel like it's a bit unintuitive to add exeptions as tuples where the second element is simply empty (and has no purpose?). It could be useful to add a brief example for this in the documentation to clarify this

**Comment by nzw0301** [comment]
Maybe replacing the type with `Optional[Sequence[Type[Exception]], Type[Exception]]]` is what users want.

**Comment by MoritzLaurer** [comment]
agreed with @nzw0301, not having a tuple, but just a sequence of exceptions seems more intuitive

**Comment by nzw0301** [comment]
@MoritzLaurer Thank you for your comment. I've created such an issue, #3230.
