### ISSUE TITLE
How can I include the high value in suggest_uniform()?

### ISSUE THREAD

**Issue by Marmeladenbrot** [optuna/optuna#2185]
I have a LightGBM Regressor model I want to apply HPO to.

One parameter is "feature_fraction" - https://lightgbm.readthedocs.io/en/latest/Parameters.html#feature_fraction

In the LightGBM documentation it says: 
> default = 1.0
> constraints: 0.0 < feature_fraction <= 1.0

So the value can be 1.

But the Optuna documentation says:

> suggest_uniform(name, low, high)
> high is excluded from the range

So when I set my parameter search space like:
```
params = {
    ...
    "feature_fraction": trial.suggest_uniform("feature_fraction", 0.001, 1.0),
    ...
}
```
"feature_fraction" can never be 1, even if this may be the optimal value for this model. How can I solve this with Optuna?

**Comment by nickcorona** [comment]
```py
params = {
    ...
    "feature_fraction": trial.suggest_uniform("feature_fraction", 0.001, 1.0 + **1e-12**),
    ...
}
```

**Comment by crcrpar** [comment]
Optuna repository happens to have a similar code https://github.com/optuna/optuna/blob/77aee02b935de1f7bb1e962aa84aedf8b254bd1d/optuna/integration/_lightgbm_tuner/optimize.py#L219.

**Comment by HideakiImamura** [comment]
How about the following?
```python
params = {
    ...
    "feature_fraction": 1. - trial.suggest_uniform("one_minus_feature_fraction", 0., 1.),
    ...
}

**Comment by hvy** [comment]
There's an RFC issue about changing the behavior whether the upper bound should really be excluded or not. Feel free to leave comments if you have any. That'd  help move it forward. https://github.com/optuna/optuna/issues/2185
