### ISSUE TITLE
Trial pre processing

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#2189]
## Motivation

Trial post processing was recently introduced in #2134 . Similarly, we could introduce trial pre processing with something along `BaseSampler.before_trial`. 

Samplers that would benefit from this would include the `NSGAIISampler` and `GridSampler` which both do pre processing, right now using `BaseSampler.sample_relative`. Although this works fine in practice, it's not what  `BaseSampler.sample_relative` was intended for. Given that this method is a public API, and that we have multiple samplers that could make use of pre processing, we may introduce a new API for these sorts of operations.

## Description

Similar to the recent introduction of trial post processing, introduce trial pre processing.

## Alternatives (optional)

Make no changes. It's already working.

## Additional context (optional)

- Trial post processing, #2134
- Ask and tell interface, #2158

**Comment by hvy** [comment]
Labeled this contribution welcome. However, I believe that the interface such as what parameters to take and behaviors such as error handling is open for discussion. If someone would be interested to tackle this, it might be a good idea to discuss those details first.

**Comment by jeromepatel** [comment]
@hvy I am interested in working on this issue. IMO, we should first discuss in which samplers we have to implement <code>before_trial</code>, and then further discuss the approaches to implement this in details (including parameters, API etc). 
I am looking forward to everyone's opinions/ideas on this. Thank you.

**Comment by not522** [comment]
Ref: #4825 introduced `before_trial`.

**Comment by not522** [comment]
I think this issue was resolved by #4825, so I close it. If any tasks remain, feel free to reopen it.
