### ISSUE TITLE
Same Node Multiprocessing instead of Multithreading (Possible Feature)

### ISSUE THREAD

**Issue by safranchik** [optuna/optuna#2202]
Hello!

I have a single computer with one GPU but multiple cores. To make better use of my GPU memory, I would like to run studies on different processes on the same computer, rather than multiple threads. 

I noticed that when assigning the number of jobs to the optimizer

``study = optuna.create_study()``
``study.optimize(objective, n_trials=100, n_jobs=4)``

The jobs get created on multiple threads. The following block of code is subsequently called in line 89 of **optuna._optimize.py**:
 
``Parallel(n_jobs=n_jobs, prefer="threads") as parallel:``

One workaround to this issue was to replace ``prefer="threads"`` with ``prefer="processes"`` in **_optimize.py**. However, I was wondering if there is better way method to specify how jobs get launched on the same node. 

Thanks in advance!

**Comment by hvy** [comment]
I think you can wrap your call to `Study.optimize` with a joblib context to override the `"threads"` preference in `_optimize.py`.

```python
from joblib import parallel_backend
import optuna

def objective(trial):
    return trial.suggest_float("x", 0, 1)

storage = "sqlite:///example.db"
study = optuna.create_study(storage=storage)

with parallel_backend('multiprocessing'):  # Overrides `prefer="threads"` to use multi-processing.
    study.optimize(objective, n_trials=30, n_jobs=2)
```

Another way which is commonly adopted by Optuna users is to have a script similar to the one above but without the joblib context and with `n_jobs=1`, but instead run that script from different Python processes (e.g. by invoking `python my_script.py` from several terminals). The [tutorial here](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html#sphx-glr-tutorial-10-key-features-004-distributed-py) gives more details.

Note that in either case, you must use some sort of RDB storage (not the default in-memory) storage that allows being accessed from multiple processes simultaneously. The example here instantiates an RDB storage with SQLite, but you could also use MySQL, PostgreSQL, etc.

**Comment by safranchik** [comment]
Thank you! That does resolve my question.
