### ISSUE TITLE
`plot_pareto_front` improvement suggestion

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#2203]
## Motivation

`optuna.visualization.plot_pareto_front` could be further improved by

- aligning the color with `optuna.visualization.plot_optimization_history`, such that the red/blue colors represent the best points or any other points in a consistent way
- including a legend, again, similar to `optuna.visualization.plot_optimization_history`

## Description

Should be clear from above.

## Additional context (optional)

- [`optuna.visualization.plot_optimization_history`](https://optuna.readthedocs.io/en/v2.4.0/reference/visualization/generated/optuna.visualization.plot_optimization_history.html)
- [`optuna.visualization.plot_pareto_front`](https://optuna.readthedocs.io/en/v2.4.0/reference/visualization/generated/optuna.visualization.plot_pareto_front.html#optuna.visualization.plot_pareto_front)

The matplotlib implementation is pending and tracked by https://github.com/optuna/optuna/issues/2113

**Comment by not522** [comment]
My suggestion: best points on Pareto front should not be covered by other points.

**Comment by 0x41head** [comment]
It doesn't seem as if someone has picked this up. Mind if I give it a try ?

**Comment by hvy** [comment]
Sure, it'd be great.

**Comment by 0x41head** [comment]
@hvy Could you please look at the current and updated versions below and provide comments regarding the same.

Current:
![before](https://user-images.githubusercontent.com/53595853/107936156-4f445800-6fa8-11eb-8855-e32f0b6300de.png)

Updated:
![after](https://user-images.githubusercontent.com/53595853/107936180-5703fc80-6fa8-11eb-8e5b-d9d6a9c54d75.png)

If this looks good, I can go ahead and submit a PR

**Comment by hvy** [comment]
Looks great. Will you make similar changes to the 3d variant as well? A detail but the legend labels might open for discussion since they're here singular. There are in practice multiple values for each data point (trial). We could name those "Trial" and "Best Trial" for instance (if you hover over the points, you'll see the trial information so it's consistent from this point of view).

**Comment by 0x41head** [comment]
Thanks for the commenting @hvy. I have made similar changes to the 3d variant as well.
Below is the updated image for the pareto plot. Do let me know if you have any other recommendations.
![image](https://user-images.githubusercontent.com/53595853/108032136-04821900-7058-11eb-8fbd-821ed74d10e6.png)

**Comment by hvy** [comment]
Thanks for the quick action. That looks good to me. Could you work on a PR perhaps?

**Comment by 0x41head** [comment]
@hvy done 👍

**Comment by 0x41head** [comment]
Issue was resolved with PR. Can someone close it ?

**Comment by hvy** [comment]
You're right. Sorry for having it delayed, and again, thanks for the PR 🙇
