### ISSUE TITLE
plot_param_importances is portraying parameter importances different from get_param_importances

### ISSUE THREAD

**Issue by XyDrKRulof** [optuna/optuna#2207]
(My first issue on an open source GitHub repository)
When I am using the function _plot_param_importances(study)_ the plot is displaying different values than the ordered dict received by the function _get_param_importances(study)_.

## Expected behavior

I would expect the function _plot_param_importances_ to display values close to those of _get_param_importances_.

## Environment

- Optuna version: 2.4.0
- Python version: 3.6.9
- OS: Ubuntu 18.04

## Error messages, stack traces, or logs

![importance_ddpg](https://user-images.githubusercontent.com/65008699/104577124-661a2680-5659-11eb-8252-fae6d9318756.png)
![Selection_048](https://user-images.githubusercontent.com/65008699/104577139-6a464400-5659-11eb-92fd-f00c5d598153.png)

![importance_td3](https://user-images.githubusercontent.com/65008699/104577161-703c2500-5659-11eb-9719-816dfbe95688.png)
![image](https://user-images.githubusercontent.com/65008699/104577748-2142bf80-565a-11eb-8137-e2836582115d.png)

## Steps to reproduce

1. Pretty Print optuna.importance.get_param_importances(study)
2. Plot optuna.visualization.plot_param_importances(study)
3. Compare

## Reproducible examples

```python
importance_dict = optuna.importance.get_param_importances(study)
pprint.pprint(importance_dict)
fig = optuna.visualization.plot_param_importances(study)
fig.write_image(f"images/importances.png")
```

**Comment by XyDrKRulof** [comment]
Okay this is not an issue, this is expected behavior. The way optuna calculates the importances is through an random forest:

https://optuna.readthedocs.io/en/latest/reference/generated/optuna.importance.FanovaImportanceEvaluator.html?highlight=FanovaImportanceEvaluator

That means the results are not deterministic and can differ at each call.

**Comment by hvy** [comment]
> That means the results are not deterministic and can differ at each call.

Exactly. If you really want to both visualize and get the dictionary with identical results, you'll have to create two evaluators you referred to above with the same seeds.
