### ISSUE TITLE
Add `seed` argument to the `GridSampler`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#2210]
## Motivation

In the `optuna.samplers.GridSampler`, the order of visiting the grids is randomly determined. However, the `GridSampler` missed the `seed` argument, so there is no reproducibility in that order.

## Description

Add `seed` argument to `optuna.samplers.GridSampler`.

**Comment by pratik-99** [comment]
I'm new to contributions can you please help me understand what needs to be done here

**Comment by HideakiImamura** [comment]
@pratik-99 Thanks for the contribution. Unfortunately, in the discussion with other core-development members, the `seed` argument is not necessary for `GridSampler` due to the following reasons.
- We don't have any scenarios in which we want to ensure the order of grids.
- If we want to ensure the order of grids, we can use `Study.enqueue_trial` now.

Therefore, I closed this issue. Sorry for the confusion. If you try to work on other issues, I'll help you. Thanks again for your intention to contribute to Optuna.
