### ISSUE TITLE
Make `GridSampler` aware of partially fixed parameters by `PartialFixedSampler`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#2211]
## Motivation

Currently, even if we partially fix some parameters with `GridSampler` by using `PartialFixedSampler`, the `GridSampler` ignores the partially fixed parameters and simply visits all grids. However, the actual sampled parameters are fixed parameters. It means we waste trials if we use `PartialFixedSampler` with `GridSampler`.

## Reproducible example
- optuna: https://github.com/optuna/optuna/pull/2209/commits/ff80efe044b444c2e9999bb1391d4c235eb483a1
```python
import optuna


def objective(trial):
    x = trial.suggest_float("x", -10, 10)
    y = trial.suggest_float("y", -10, 10)
    return x ** 2 + y ** 2

# the number of grids is 4 * 4 = 16
search_space = {"x": list(range(-10, 10, 5)), "y": list(range(-10, 10, 5))}

study0 = optuna.create_study()
study0.sampler = optuna.samplers.GridSampler(search_space)
study0.optimize(objective, n_trials=16)

study1 = optuna.create_study()
study1.sampler = optuna.samplers.PartialFixedSampler(
    fixed_params={"y": 0}, base_sampler=optuna.samplers.GridSampler(search_space)
)
study1.optimize(objective, n_trials=16)

print(len(study0.trials))
print(len(study1.trials))
```
### Output
```
16
16
```
### Expected Output
Since `y` is fixed to 0, we should only consider `x` and the size of the grid should be 4.
```
16
4
```

## Approach
I think we should not use `PartialFixedSampler` with `GridSampler`. If we want to fix some parameters with `GridSampler`, we can simply re-define the search space and `GridSampler`. IMO, we should prohibit the use of `PartialFixedSampler` with `GridSampler` or warn.

**Comment by hvy** [comment]
I personally find the current behavior logical and well defined, at least from an API perspective, and would suggest keeping the two samplers decoupled. I agree that it's not very practical.

**Comment by HideakiImamura** [comment]
Thanks for the reply. Hmm... I'd like to know the user's opinion. As you mentioned, making the two samplers unrelated may make it easier for the user to understand each one. This behavior could be made a specification. I would like to leave this issue open and work on it when a user has questions.
