### ISSUE TITLE
Disable UserWarning?

### ISSUE THREAD

**Issue by tide90** [optuna/optuna#2225]
Hey,

How can I diasble/ignore the follwoing warning:
Getting this from suggest_int with a step.

```
/usr/local/lib/python3.6/dist-packages/optuna/distributions.py:569: UserWarning:

The distribution is specified by [1, 1000] and step=10, but the range is not divisible by `step`. It will be replaced by [1, 991].
```

I tried:
```
import warnings
with warnings.catch_warnings():
    warnings.filterwarnings(action='ignore', category=UserWarning, module='/usr/local/lib/python3.6/dist-packages/optuna/*')
    import optuna
```

But did not work!

**Comment by HideakiImamura** [comment]
For the `UserWarning`, please fix your own code. I think the range of `suggest_int` should be changed to [1, 991], whose width `991 - 1 = 990` can be divisible by `step=10`.

There are two types of warnings: one that can be suppressed by modifying the user code, and one that the user has no way of dealing with and can adjust the level of display of logging. The `UserWarning` is the former one. Please check [the Wiki of Optuna.](https://github.com/optuna/optuna/wiki/Coding-Style-Conventions#logging-howto.)

To adjust the level of display of logging, please check [the `optuna.logging` module.](https://optuna.readthedocs.io/en/stable/reference/logging.html)

**Comment by tide90** [comment]
@HideakiImamura  Thank you. But what is now the right handling for this warning? Could you make an example?

**Comment by nzw0301** [comment]
I execute the following code, but the warning message still appears...

```python
import optuna

optuna.logging.set_verbosity(optuna.logging.CRITICAL)

def objective(trial):
    x = trial.suggest_int("x", 1, 1000, step=10)

    return x


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=3)
print(study.best_trial)
```

**Comment by nzw0301** [comment]
@tide90 
How about this?

```python
import optuna
import warnings

warnings.filterwarnings("ignore", category=UserWarning)

def objective(trial):
    x = trial.suggest_int("x", 1, 1000, step=10)

    return x


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=3)
print(study.best_trial)

```

**Comment by nzw0301** [comment]
@HideakiImamura I think we cannot disable `UserWarning` by using `optuna.logging.set_verbosity` as in https://github.com/optuna/optuna/issues/2225#issuecomment-762732337.

**Comment by HideakiImamura** [comment]
As I described in https://github.com/optuna/optuna/issues/2225#issuecomment-762512549, the users should deal with the `UserWarning` by modifying their own code. Now, you should change your code as follows.
```python
import optuna
import warnings


def objective(trial):
    x = trial.suggest_int("x", 1, 991, step=10)

    return x


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=2)
print(study.best_trial)
```

**Comment by tide90** [comment]
@HideakiImamura I think you missed soemthing in your code example above? Or why does this block the message?

**Comment by himkt** [comment]
Hello @tide90, I think the suggestion by @HideakiImamura will not contain any logic to block a warning message. I think we can erase a warning message by (a) filtering out it explicitly (https://github.com/optuna/optuna/issues/2225#issuecomment-764713213) or (b) modifying a code to fixing a cause of warning. The suggestion takes the latter approach.

He suggested fixing a code such that a range of parameters so that a width of a range is divisible by `step`. Your original code creates a range whose width 999 (`1000 (upper) - 1 (lower)`), which is not divisible by `step` 10. If a range will start from `1` and end at `991`, the width would be `990` and it is divisible by 10.
