### ISSUE TITLE
`study.trials_dataframe` call fails for multi-objective studies

### ISSUE THREAD

**Issue by blaney83** [optuna/optuna#2227]
When using the new multi-objective study framework in v2.4.0 (`optuna.create_study(..., directions=[...])`), calling the `trials_dataframe` message raises an exception caused by some incorrect column spec type comparison in the _dataframe framework. It appears the column aggregation for contains a bug when used with multiple objectives, which adds an extra `values` Tuple to the `values` Set during the initial mapping of `'value' -> 'values'` for a multi-objective study.

## Expected behavior

Accessing the `trials_dataframe` method of a study works the same for both single and multi-objective studies.

## Environment

- Optuna version: 2.3.0 -> 2.4.0
- Python version: 3.8
- OS: Ubuntu 20.04.1, Linux Kernel v5.4.0-56

## Error messages, stack traces, or logs

```
Traceback (most recent call last):
  File "optuna_vis.py", line 12, in <module>
    study_df = study.trials_dataframe()
  File "/home/user.name/anaconda3/lib/python3.8/site-packages/optuna/study.py", line 499, in trials_dataframe
    return _trials_dataframe(self, attrs, multi_index)
  File "/home/user.name/anaconda3/lib/python3.8/site-packages/optuna/_dataframe.py", line 80, in _trials_dataframe
    columns: List[Tuple[str, str]] = sum(
  File "/home/user.name/anaconda3/lib/python3.8/site-packages/optuna/_dataframe.py", line 81, in <genexpr>
    (sorted(column_agg[k]) for k in attrs if k in column_agg), []
TypeError: '<' not supported between instances of 'str' and 'int'
```

By inspecting the `attr` field in the `_trials_dataframe` method (line 23, _dataframe.py), reveals an extra `values` item:

```
{'number': {('number', '')}, 'values': {('values', 1), ('values', ''), ('values', 0), ('values', 3), ('values', 2)}, 'datetime_start': {('datetime_start', '')}, 'datetime_complete': {('datetime_complete', '')}, 'duration': {('duration', '')}, 'params': {(<param_tuples>), ...}, 'user_attrs': {('user_attrs', 'total_x'), ('user_attrs', 'total_y'), ('user_attrs', '_time_'), ('user_attrs', 'value_total')}, 'system_attrs': {('system_attrs', 'nsga2:generation')}, 'state': {('state', '')}}
```

For context, I have defined 4 objectives in this study. After the first trial, there appears this `('values', '')` anomaly which causes the above exception.

## Steps to reproduce

1. Create a MPO study with 4 objectives.
2. Start your study and after at least 2 trials, try to call the `study.trials_dataframe()` method.
3. The above exception will be raised.

**Comment by HideakiImamura** [comment]
Thanks for raising an issue. I have tested with the following code snippets but had no error with the following outputs. The version of Optuna is v2.4.0.
```python
import optuna


def objective(trial):
    return 0, 1, 2, 3

study = optuna.create_study(directions=["minimize"]*4)
study.optimize(objective, n_trials=2)
print(study.trials_dataframe())
```
<img width="1182" alt="スクリーンショット 2021-01-19 8 16 08" src="https://user-images.githubusercontent.com/38826298/104970387-9af9f500-5a2e-11eb-97ef-e1a779ea7760.png">

Could you share the reproducible codes or snippet?

**Comment by blaney83** [comment]
Sure! After investigation, I found the cause of the issue. It seems that if, for some reason, the first trial fails or returns a value which is inconsistent with the multi-objective value intended for the trial, the mapping of `value -> values` adds this erroneous item to the `values` set. Then, in the internal `_trials_dataframe` method, the `sort` comparison fails.

In my case, the distributed nature of the study would sometimes fail during initialization on the first trial or a subsequent trial would finish before the first trial had finished, causing the value for the first trial to remain unset during the first call of `study.trials_dataframe`.

Here is a modified version of your snippet which reproduces the issue:

```
import optuna

def objective(trial):
    return 0, 1, 2, 3 if trial.number else None

study = optuna.create_study(study_name="test", directions=["minimize"]*4, storage="sqlite:///motpe.db", load_if_exists=True)
study.optimize(objective, n_trials=10)
print(study.trials_dataframe())
```

Perhaps it would make more sense to create the `values` set on the initial creation of the study from the `directions` passed during to `optuna.create_study` rather than trying to parse the first trial's returned values? This would certainly be more consistent.

**Comment by not522** [comment]
Thank you for your investigation! I wrote the PR #2265 to fix this error.

**Comment by blaney83** [comment]
Awesome. Thank you!
