### ISSUE TITLE
How to make optuna suggest different values (i.e. overwrite them) few times in a row?

### ISSUE THREAD

**Issue by ZumbiAzul** [optuna/optuna#2234]
Here is the code example:
```
import optuna

def objective(trial):
    i=0
    while i < 5:
        x = trial.suggest_uniform('x', -10, 10)
        c = trial.suggest_categorical('c',['dave','masha'])
        print('x =',x,'; c =',c)
        i +=1
    return (x - 2) ** 2

study = optuna.create_study()
study.optimize(objective, n_trials=1)
```

When I run it I get this:
```
[I 2021-01-18 15:54:35,991] A new study created in memory with name: no-name-dede52a4-81d4-494d-9461-79d6bc45092c
[I 2021-01-18 15:54:35,993] Trial 0 finished with value: 1.1393024707748967 and parameters: {'x': 0.9326188727662004, 'c': 'dave'}. Best is trial 0 with value: 1.1393024707748967.
x = 0.9326188727662004 ; c = dave
x = 0.9326188727662004 ; c = dave
x = 0.9326188727662004 ; c = dave
x = 0.9326188727662004 ; c = dave
x = 0.9326188727662004 ; c = dave
```
As you see, `trial` somehow sticks to the value it initially suggested.
I would like `trial` to suggest new value each time `trial.suggest...` is called. There must be a way of doing it, but I have not figured it out yet. Could anybody point me at the solution?

I have also posted this question on [StackOverflow](https://stackoverflow.com/questions/65777040/how-to-make-optuna-suggest-different-values-few-times-in-a-row-and-use-only-th).

**Comment by nzw0301** [comment]
I think you just need to set a larger value to `n_trials.` If you want to avoid evaluating objective with the same hyper-parameters, I suggest you the following strategies depending on your problem

1. evaluate again. I think that it is acceptable if the evaluation cost is low
2. perform grid-search if your searched space is small
3. return the objective value evaluated at previous trials. (I'm not sure it can be done easily)

**Comment by ZumbiAzul** [comment]
@nzw0301 If I use `n_trials=3' I get the following:
```
x = 6.42028440485651 ; c = masha
x = 6.42028440485651 ; c = masha
x = 6.42028440485651 ; c = masha
x = 6.42028440485651 ; c = masha
x = 6.42028440485651 ; c = masha
x = -0.16786019514408324 ; c = dave
x = -0.16786019514408324 ; c = dave
x = -0.16786019514408324 ; c = dave
x = -0.16786019514408324 ; c = dave
x = -0.16786019514408324 ; c = dave
x = 7.872881958915212 ; c = masha
x = 7.872881958915212 ; c = masha
x = 7.872881958915212 ; c = masha
x = 7.872881958915212 ; c = masha
x = 7.872881958915212 ; c = masha
```
But I really need it to work for `n_trials=1`. 
I am trying to suggest a neural network architecture, using `while`-loop in y code. And I check the suggested values for ertain conditions. If they do not meet them I want to suggest other values.

For example, one of the conditions I check is whether a new size of the input image after a conv-layer is not smaller than zero, and if it is I disregard suggested parameters for that conv-layer and suggest again.

**Comment by nzw0301** [comment]
How about pruning such a trial?

**Comment by ZumbiAzul** [comment]
@nzw0301 That is an interesting suggestion. I am relatively new to optuna, and I have a feeling that pruning works automatically (provided I use `report` and `should_prune`). How can I just tell optuna to prune a trial?

**Comment by nzw0301** [comment]
@ZumbiAzul I think you just call `raise optuna.TrialPruned()` like optuna's pruner, such as [`MedianPruner`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.pruners.MedianPruner.html)'s example:


```python
import optuna

def objective(trial):
    x = trial.suggest_uniform('x', -10, 10)
    c = trial.suggest_categorical('c', ['dave', 'masha'])
    print('x =', x, '; c =', c)

    if some_condition_for_x_or_c_to_stop_evaluation:
        raise optuna.TrialPruned()

    return (x - 2) ** 2

study = optuna.create_study()
study.optimize(objective, n_trials=10)
```

I note that pruned trials are differently treated by the sampler depending on the sampler. Please see https://github.com/optuna/optuna/issues/1647 for details.

I'm not sure this is a good way to solve your question.

**Comment by ZumbiAzul** [comment]
Thanks, @nzw0301 . This definitely helps, although it does not solve my question directly. I had to rewrite/restructure my code in order for it to work as I want using `raise optuna.TrialPruned()`.

**Comment by nzw0301** [comment]
I believe the issue was resolved by my comment.
