### ISSUE TITLE
Optuna does not overwrite a suggested value by another following suggestion

### ISSUE THREAD

**Issue by ZumbiAzul** [optuna/optuna#2235]
Here is the code example:
```
import optuna

def objective(trial):
    i=0
    while i < 5:
        x = trial.suggest_uniform('x', -10, 10)
        c = trial.suggest_categorical('c',['dave','masha'])
        print('x =',x,'; c =',c)
        i +=1
    return (x - 2) ** 2

study = optuna.create_study()
study.optimize(objective, n_trials=1)
```

When I run it I get this:
```
[I 2021-01-18 15:54:35,991] A new study created in memory with name: no-name-dede52a4-81d4-494d-9461-79d6bc45092c
[I 2021-01-18 15:54:35,993] Trial 0 finished with value: 1.1393024707748967 and parameters: {'x': 0.9326188727662004, 'c': 'dave'}. Best is trial 0 with value: 1.1393024707748967.
x = 0.9326188727662004 ; c = dave
x = 0.9326188727662004 ; c = dave
x = 0.9326188727662004 ; c = dave
x = 0.9326188727662004 ; c = dave
x = 0.9326188727662004 ; c = dave
```
As you see, `trial` somehow sticks to the value it initially suggested.
It would be more natural if `trial` suggested new value each time `trial.suggest...` is called. It is also very handy when building up a neural network architecture, and in cases when a suggested parameter does not satisfy a certain condition, so another suggestion is required.

I have also posted this question on [StackOverflow](https://stackoverflow.com/questions/65777040/how-to-make-optuna-suggest-different-values-few-times-in-a-row-and-use-only-th).

**Comment by y0z** [comment]
Hi. I have investigated why this happens.

The following code says that this behavior is intended.
https://github.com/optuna/optuna/blob/0280b598a85a6bc79b22a10a1e5edde82a09044e/optuna/trial/_trial.py#L704

**Comment by ZumbiAzul** [comment]
Thanks a lot @y0z for looking into it. I still think that it should be in principle realizable to be able to overwrite a suggested value by another value without spoiling the intentions of the algorithm. This would be extremely useful in many practical implementations. I understand that this is more like a feature suggestion and not a reporting a bug.

**Comment by ZumbiAzul** [comment]
@nzw0301 Thats right.

**Comment by raquelhortab** [comment]
I think this would be an interesting feature. For instance, there might be a specific config that is not feasible but we don't want the algorithm to "judge" the specific values it chose. For me, I first suggest the amount of conv layers the model will have, and then their specific config (sizes, stride, kernel, pooling, etc). It may happen that when using a large amount of layers, it gets to a point where the dimension gets too small for so many layers and I need to prune that config. If, for instance, layer 1 had a specific size suggested, I don't want optuna to penalize those suggestions but prune the algorithm without any effect. A good workaround would be to change the suggested value to the maximum num of layers that config could hold.

**Comment by raquelhortab** [comment]
I see if I do this:
```
 trial._cached_frozen_trial.params['param_name'] = new_value
```
the change seems to be preserved. Does anyone know the implications of this?
