### ISSUE TITLE
Add Hydra Optuna Sweeper example

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#2246]
## Motivation

[Hydra](https://hydra.cc/) is a framework for configuring complex applications. Recently, it provides a [plugin](https://hydra.cc/docs/next/plugins/optuna_sweeper/) to optimize hyperparameters using  Optuna. I think providing an example of Hydra Optuna plugin will be helpful for both Hydra and Optuna users.

![image](https://user-images.githubusercontent.com/3255979/105261405-eea54380-5bd2-11eb-9367-b34ebe00ebdb.png)

## Description

Please add a example of Hydra Optuna plugin to `examples` directory of Optuna repository.

## Alternatives (optional)

Add a link to Hydra Optuna plugin in `examples/README.md`.

## Additional context (optional)

- A [simple example](https://github.com/facebookresearch/hydra/tree/master/plugins/hydra_optuna_sweeper/example) in Hydra repository.
- [Documentation](https://hydra.cc/docs/next/plugins/optuna_sweeper/) of Hydra Optuna plugin.

**Comment by nzw0301** [comment]
@toshihikoyanase I think this issue is solved by #2290.  Could you close the issue? If there is a thing for this issue, I'm happy to work for it.

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for your kind ping. As you mentioned, this issue was resolved. I'd like to close it.
