### ISSUE TITLE
`MOTPESampler` raises `ValueError` when it solves a simple knapsack problem

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#2247]
## Expected behavior

When I tried to solve a simplified multi-objective knapsack problem using `MOTPE`, I got `ValueError`. I think it should handle this problem or show a more user-friendly error message.

The problem is defined as follows:
```python
import numpy as np

import optuna


def create_knapsack(n_items, n_knapsack, seed):
    rng = np.random.RandomState(seed=seed)
    profits = rng.randint(10, 101, size=(n_knapsack, n_items))
    return profits


def knapsack(trial, profits):
    p0, p1 = 0, 0
    for i, p in enumerate(profits.tolist()):
        x = trial.suggest_categorical(f"x_{i}", (0, 1))
        p0 += p[0] * x
        p1 += p[1] * x

    return p0, p1

profits = create_knapsack(20, 2, 1)
objective = lambda t: knapsack(t, profits)
```

## Environment

- Optuna version: v2.4.0
- Python version: Python 3.6 (Google Colab)
- OS: N/A (Google Colab)

## Error messages, stack traces, or logs

```console
[W 2021-01-21 06:35:39,582] Trial 20 failed because of the following error: ValueError('pvals < 0, pvals > 1 or pvals contains NaNs',)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/optuna/_optimize.py", line 198, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-3-7aaa3bf88873>", line 7, in <lambda>
    objective = lambda t: knapsack(t, profits)
  File "<ipython-input-2-d1a010db23b5>", line 15, in knapsack
    x = trial.suggest_categorical(f"x_{i}", (0, 1))
  File "/usr/local/lib/python3.6/dist-packages/optuna/trial/_trial.py", line 505, in suggest_categorical
    return self._suggest(name, CategoricalDistribution(choices=choices))
  File "/usr/local/lib/python3.6/dist-packages/optuna/trial/_trial.py", line 717, in _suggest
    study, trial, name, distribution
  File "/usr/local/lib/python3.6/dist-packages/optuna/samplers/_tpe/multi_objective_sampler.py", line 208, in sample_independent
    study, trial, param_distribution, below_param_values, above_param_values
  File "/usr/local/lib/python3.6/dist-packages/optuna/samplers/_tpe/multi_objective_sampler.py", line 476, in _sample_mo_categorical_index
    samples_below = self._sample_from_categorical_dist(weighted_below, size)
  File "/usr/local/lib/python3.6/dist-packages/optuna/samplers/_tpe/sampler.py", line 628, in _sample_from_categorical_dist
    sample = self._rng.multinomial(n=1, pvals=probabilities, size=n_draws)
  File "mtrand.pyx", line 4212, in numpy.random.mtrand.RandomState.multinomial
  File "_common.pyx", line 338, in numpy.random._common.check_array_constraint
ValueError: pvals < 0, pvals > 1 or pvals contains NaNs
```

## Steps to reproduce

Please refer to this [notebook](https://colab.research.google.com/drive/1dufGlGX_TIUOdpIQrz8Usnfl52BMwoKA?usp=sharing).

**Comment by toshihikoyanase** [comment]
Although the error occurred in `optuna/samplers/_tpe/sampler.py`,  I confirmed that `TPESampler` can solve a single-objective version of the problem as expected. I think this is an issue of `MOTPESampler`.

<details> 
<summary> TPE reproducible code </summary>

```python
import numpy as np

import optuna


def create_knapsack(n_items, seed):
    rng = np.random.RandomState(seed=seed)
    profits = rng.randint(10, 101, size=(n_items, ))
    return profits


def knapsack(trial, profits):
    total = 0
    for i, p in enumerate(profits.tolist()):
        x = trial.suggest_categorical(f"x_{i}", (0, 1))
        total += p * x
    return total


if __name__ == "__main__":
    sampler = optuna.samplers.TPESampler(seed=10)
    study = optuna.create_study(
        direction="maximize",
        sampler=sampler,
    )
    profits = create_knapsack(20, 1)
    objective = lambda t: knapsack(t, profits)
    study.optimize(objective, n_trials=100, timeout=600)

    print("Number of finished trials: ", len(study.trials))

    print(study.best_trial)
```

</details>

**Comment by y0z** [comment]
Hi. Thank you for your report.

I find that _calculate_weights_below returns a corrupted weights_below by using your reproducible code.
Sorry, this is my fault.
This is a bug of `_calculate_weights_below` without enough corner case handling.
https://github.com/optuna/optuna/blob/e6f788901060e42857b97c1ccc5b36978c7ed1e3/optuna/samplers/_tpe/multi_objective_sampler.py#L563

When I run your reproducible code, I find that an input `lvals` is pretty pathological, i.e., all of the vectors in `lvals` are duplicated.
Then, the hypervolume contribution of each sample becomes zero.

```sh
[I 2021-01-21 23:41:01,611] Trial 19 finished with values: [86.0, 46.0] and parameters: {'x_0': 1, 'x_1': 1}.
lvals= [[ -0.  -0.]
 [-86. -46.]
 [ -0.  -0.]
 [-39. -24.]
 [-86. -46.]
 [-39. -24.]
 [-86. -46.]
 [-39. -24.]
 [-47. -22.]
 [ -0.  -0.]
 [-86. -46.]
 [-86. -46.]
 [-86. -46.]
 [-86. -46.]
 [-86. -46.]
 [-47. -22.]
 [-86. -46.]
 [-47. -22.]
 [-86. -46.]
 [-86. -46.]]
contributions= [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
weight_below= [nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
```

As a result, we need to modify our weight calculation heuristic to solve this issue.
Do you have any idea? (I will also consider it.)
Additionally, I propose to add some test cases of calculate_weights_below at this time.

**Comment by y0z** [comment]
Here is a simple heuristic that I came up with, though a better weighting strategy may exist.

First, make observed objective vectors unique before calculating their hypervolume contribution.
Then, calculate weights `w` for each objective vector `v` based on their hypervolume contribution.
Finally, assign the weights of `w/n` to each observation where `n` is the number of observations having the objective vector `v`.

```python
def _calculate_weights_below(
    self,
    lvals: np.ndarray,
    indices_below: np.ndarray,
) -> np.ndarray:
    # Calculate weights based on hypervolume contributions.
    n_below = len(indices_below)
    if n_below == 0:
        return np.asarray([])
    elif n_below == 1:
        return np.asarray([1.0])
    else:
        lvals_below_duplicated = {}  # type: Dict[tuple, List[int]]
        for i, v in enumerate(lvals[indices_below]):
            k = tuple(v)
            if k not in lvals_below_duplicated:
                lvals_below_duplicated[k] = []
            lvals_below_duplicated[k].append(i)
        lvals_below_unique = [np.asarray(k) for k in lvals_below_duplicated.keys()]
        worst_point = np.max(lvals_below_unique, axis=0)
        reference_point = np.maximum(1.1 * worst_point, 0.9 * worst_point)
        reference_point[reference_point == 0] = EPS
        hv = self._compute_hypervolume(np.asarray(lvals_below_unique), reference_point)
        contributions = np.asarray(
            [
                hv
                - self._compute_hypervolume(
                    np.asarray(lvals_below_unique[:i] + lvals_below_unique[i + 1 :]),
                    reference_point
                )
                for i in range(len(lvals_below_unique))
            ]
        )
        weights_below_unique = np.clip(contributions / np.max(contributions), 0, 1)
        weights_below = np.empty(n_below)
        for v, w in zip(lvals_below_unique, weights_below_unique):
            k = tuple(v)
            indices = lvals_below_duplicated[k]
            weights_below[indices] = w / len(indices)
        return weights_below
```

```python
@staticmethod
def _compute_hypervolume(solution_set: np.ndarray, reference_point: np.ndarray) -> float:
    if len(solution_set) == 0:  # allow empty solution_set
        return 0
    return optuna.multi_objective._hypervolume.WFG().compute(solution_set, reference_point)
```

**Comment by toshihikoyanase** [comment]
@y0z Thank you for your investigation.

> This knapsack problem is terrible. Only four unique points were found 

Oh, I'm sorry but I made a mistake. The dimension of `profits` is not correct. It was `(n_knapsack, n_items)` but it should be `(n_items, n_knapsack)`.

The points are distributed if I plot the fixed objective functions using the random sampler. 
![image](https://user-images.githubusercontent.com/3255979/105458766-82a70600-5ccc-11eb-892d-a0b38e3b60cc.png)

Still, I can see the same error, which may not be so unusual. The correct notebook is [here](https://colab.research.google.com/drive/1_wNKzLQoO01PhWjNeo2HZAARo0jBFb1C?usp=sharing).

> Then, the hypervolume contribution of each sample becomes zero.

I see. All the elements of `contributions` were zero, and the `weights_below` will be `NaN` due to the zero division. In this case, all samples are equally bad, and your solution seems reasonable to me.

Alternatively, we useally replace zero denominator with a small number to avoid zero division, for example, as follows:

```python
            weights_below = np.clip(contributions / max(np.max(contributions), EPS), 0, 1)
```

I'm not sure if `weight_below` can be zero, but this approach keeps the computational results if the denominator is large enough. What do you think?

**Comment by y0z** [comment]
@toshihikoyanase Thank you for your comment.
> Oh, I'm sorry but I made a mistake. The dimension of profits is not correct. It was (n_knapsack, n_items) but it should be (n_items, n_knapsack).

I see, no problem.

----

It is a more complex problem than first I expected.
I have considered the problem and my opinion is that adding `EPS` to contributions may be better.

The proposed change actually avoids zero division but `weights_below` still can be an array of zeros.
```python
weights_below = np.clip(contributions / max(np.max(contributions), EPS), 0, 1)
```

Based on my understanding, some of the values of `weights_below` can be zero but at least one of them must not be zero because the weights are converted to probabilities in a way, e.g. `weighted_below /= weighted_below.sum()`.

`weights_below=[0, 0, ..., 0]` causes a problem when sampling using `ParzenEstimator` as follows.
If `consider_prior=False` and avoiding zero division by using `max(np.max(contributions), EPS)`, `weights_below=[0, 0, ..., 0]` can be passed to `ParzenEstimator`.
https://github.com/optuna/optuna/blob/23eba5a620cdc5c04637a644a749fdab6003469f/optuna/samplers/_tpe/multi_objective_sampler.py#L402-L423

Then, another zero division will occur in `_calculate`.
https://github.com/optuna/optuna/blob/23eba5a620cdc5c04637a644a749fdab6003469f/optuna/samplers/_tpe/parzen_estimator.py#L120

If we avoid the zero division in `_calculate` by using `/= max(sorted_weights.sum(), EPS)`, after that, `_sample_from_gmm` calls `numpy.random.multinomial` with `pvals=[0, 0, ..., 0]`.
https://github.com/optuna/optuna/blob/23eba5a620cdc5c04637a644a749fdab6003469f/optuna/samplers/_tpe/sampler.py#L535

[NumPy docs](https://numpy.org/doc/stable/reference/random/generated/numpy.random.multinomial.html) say that `multinomial` treats `pvals=[0, 0, ..., 0]` as `pvals=[0, 0, ..., 1]`. This means that the final outcome will be always sampled.
> pvals : sequence of floats, length p
> Probabilities of each of the p different outcomes. These must sum to 1 (however, the last element is always assumed to account for the remaining probability, as long as sum(pvals[:-1]) <= 1).

This is obviously not preferable.

On the other hand, `contributions += EPS` makes `contributions=[EPS, EPS, ..., EPS]` when contributions are zeros. This means that each outcome will be uniformly sampled and seems to be more preferable than the former situation. When `contributions` are not zeros, the effect of adding `EPS` to `contributions` will be negligible in practice.

----

FYI, the motivation of the weighting heuristic of MOTPE is to avoid a stagnation that similar objective vectors are continuously obtained and to do a well-balanced search in the objective space. However, this weighting heuristic is designed for continuous problems such as WFG benchmarks. Therefore, another weighting strategy may work well for discrete problems.

<img width="2336" alt="Screen Shot 2021-01-22 at 18 13 23" src="https://user-images.githubusercontent.com/30489874/105473228-336ad080-5ce0-11eb-8092-a9a761aa67f8.png">

**Comment by toshihikoyanase** [comment]
> I have considered the problem and my opinion is that adding EPS to contributions may be better.
> How do you think? If there is no problem, I will create a pull request to fix this issue.

Thank you for your detailed explanation. I totally agree with you. Your PR is more than welcome.

One thing I want to mention is that I used only categorical variables. In your explanation, you dived into the `_sample_mo_numerical`, but I guess we needed to check `_sample_mo_categorical_index` actually. When the `weights_below` is a zero vector, `counts_below` is also a zero vector. Then, `weighted_below` will be usually a vector whose elements are all one since the default value of `self._prior_weight` is one. In this case, we can avoid a zero-division error.

But, I don't think setting a zero vector to `weights_below`, and I agree to the idea to add `EPS` to contributions.

https://github.com/optuna/optuna/blob/23eba5a620cdc5c04637a644a749fdab6003469f/optuna/samplers/_tpe/multi_objective_sampler.py#L472-L477

https://github.com/optuna/optuna/blob/23eba5a620cdc5c04637a644a749fdab6003469f/optuna/samplers/_tpe/multi_objective_sampler.py#L120

---

> weighting heuristic

Thank you for your investigation, but currently, I can't understand why we need a new weighting heuristic for discrete problems because of my limited understanding of the behavior. I'll check the issue more in detail.

**Comment by y0z** [comment]
@toshihikoyanase 
Thank you for your comment.
It is quite helpful for me to understand the behavior of Optuna.

I have just made a minimal PR to fix this issue based on our discussion (https://github.com/optuna/optuna/pull/2274). 
Could you review the PR?

**Comment by toshihikoyanase** [comment]
@y0z Thank you for your PR. I'll check it.

**Comment by toshihikoyanase** [comment]
Let me close this issue since #2274 fixed the error.
BTW, I think the [discussion](https://github.com/optuna/optuna/issues/2247#issuecomment-765313554) about heuristics of weights seems to be worthful for future improvement, we may want to create an independent issue as `feature-request`.

@y0z What do you think of it?
