### ISSUE TITLE
Could the document of disabling logging message be improved?

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2250]
This issue is based on my poor understanding of optuna. It might be wrong.

Optuna's warning messages come from two different logging methods according to [the wiki page of coding style](https://github.com/optuna/optuna/wiki/Coding-Style-Conventions#logging-howto):

- `warnings.warn`
- `optuna.logging.Logger.warnings`

However, I think that [the document of logging](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.logging.set_verbosity.html) and [FAQ](https://optuna.readthedocs.io/en/latest/faq.html#how-to-suppress-log-messages-of-optuna) only mention the optuna's warning. So when I read these document pages, I probably use `optuna.logging.set_verbosity` to disable `UserWarning` for the following code based on https://github.com/optuna/optuna/issues/2225#issue-788172175. But it does not work because `warnings.warn` shows this `UserWarning` that we cannot disable by using `optuna.logging.set_verbosity`. I feel it is a little bit unfriendly for users since the most helpful explanation exists only on the wiki page of coding style. So I propose adding information to both faq and logging pages.

---

## code

```python
import optuna

def objective(trial):
    x = trial.suggest_int("x", 1, 100, step=10)

    return x


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=3)
```

## warning message
```
[I 2021-01-22 05:28:05,449] A new study created in memory with name: no-name-4e61919e-9d81-4e3b-b748-02d2566c37e9
.../optuna/optuna/distributions.py:562: UserWarning: The distribution is specified by [1, 100] and step=10, but the range is not divisible by `step`. It will be replaced by [1, 91].
  warnings.warn(

```

**Comment by HideakiImamura** [comment]
Thanks for the proposal! I had an informal discussion with other committers about this proposal. In conclusion, we agreed to add some information to make it easier for users to understand the difference between `warnings.warn` and `_logger.warnings`. Do you have any ideas on where exactly to add this information?

**Comment by nzw0301** [comment]
Thank you for discussing this issue with other committers! I'm glad to hear that. I think [this faq section](https://optuna.readthedocs.io/en/latest/faq.html#how-to-suppress-log-messages-of-optuna) and  [`logging.set_verbosity`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.logging.set_verbosity.html).
