### ISSUE TITLE
TypeError: can't pickle _thread.RLock objects

### ISSUE THREAD

**Issue by EROPLM** [optuna/optuna#2256]
When training tensorflow.keras model using Jupiter lab, program prints TypeError on finishing trial_0.
Training data is MNIST data. 

# Steps to reproduce

1) Downloading data 

2) Preprocessing data below

image data shape: (n_data,28,28,1)
target data shape: (n_data,10)
image data file: X_train.npy
target data file: y_train.npy

3) Run source code below
`
import os
import optuna
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D,MaxPooling2D,BatchNormalization
from tensorflow.keras.layers import Dropout,Flatten,Dense
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import CSVLogger
from optuna.integration import TFKerasPruningCallback
from tensorflow.keras import backend as K
from sklearn.model_selection import train_test_split
from optuna.samplers import RandomSampler 
from optuna.pruners import SuccessiveHalvingPruner

os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'
np.random.seed(10)
tf.random.set_seed(11)

def cnn_model(trial):
    model = Sequential()
    model.add(Conv2D(trial.suggest_int("input_1",1,1000),(3,3),activation="relu",padding="same",input_shape=input_shape))
    model.add(Conv2D(trial.suggest_int("block1_conv1",1,1000), (3,3), activation='relu', padding='same'))
    model.add(Conv2D(trial.suggest_int("block1_conv2",1,1000), (3,3), activation='relu', padding='same'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(drop_rate))
    model.add(Conv2D(trial.suggest_int("block2_conv1",1,1000), (3,3), activation='relu', padding='same'))
    model.add(Conv2D(trial.suggest_int("block2_conv2",1,1000), (3,3), activation='relu', padding='same'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(drop_rate))
    model.add(Conv2D(trial.suggest_int("block3_conv1",1,1000), (3,3), activation='relu', padding='same'))
    model.add(Conv2D(trial.suggest_int("block3_conv2",1,1000), (3,3), activation='relu', padding='same'))
    model.add(Conv2D(trial.suggest_int("block3_conv3",1,1000), (3,3), activation='relu', padding='same'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(drop_rate))
    model.add(Conv2D(trial.suggest_int("block4_conv1",1,1000), (3,3), activation='relu', padding='same'))
    model.add(Conv2D(trial.suggest_int("block4_conv2",1,1000), (3,3), activation='relu', padding='same'))
    model.add(Conv2D(trial.suggest_int("block4_conv3",1,1000), (3,3), activation='relu', padding='same'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2)))
    model.add(Dropout(drop_rate))
    model.add(Conv2D(trial.suggest_int("block5_conv1",1,1000), (3,3), activation='relu', padding='same'))
    model.add(Conv2D(trial.suggest_int("block5_conv2",1,1000), (3,3), activation='relu', padding='same'))
    model.add(Conv2D(trial.suggest_int("block5_conv3",1,1000), (3,3), activation='relu', padding='same'))
    model.add(BatchNormalization())
    model.add(MaxPooling2D(pool_size=(2,2),padding='same'))
    model.add(Dropout(drop_rate))
    model.add(Flatten())
    model.add(Dense(trial.suggest_int("fc1",1,1000), activation='relu'))
    model.add(Dense(trial.suggest_int("fc2",1,1000), activation='relu'))
    model.add(Dropout(drop_rate))
    model.add(Dense(output_classes, activation="softmax"))
    return model

def callback(study, trial):
    if study.best_trial.number == trial.number:
        study.set_user_attr(key="best_model", value=trial.user_attrs["best_model"])

def objective(trial):
    batch_size = 1280
    epochs = 100
    validation_split = 0.25
    X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=1,shuffle=True)
    model = cnn_model(trial)
    model.compile(loss='categorical_crossentropy', optimizer='rmsprop',
              metrics=["accuracy"])
    callbacks = [EarlyStopping(monitor="val_accuracy",patience=4,verbose=1),TFKerasPruningCallback(trial,"val_accuracy")]
    model.fit(X_train, y_train, batch_size=batch_size,epochs=epochs, validation_split=validation_split,callbacks=callbacks)
    score = model.evaluate(X_test, y_test, verbose=0)
    trial.set_user_attr(key="best_model",value=model)
    return score[1]

sampler = RandomSampler(seed=5)
study = optuna.create_study(direction="maximize",sampler=sampler,pruner=SuccessiveHalvingPruner())
study.optimize(objective,n_trials=200,callbacks=[callback])
best_model = study.user_attrs["best_model"]

print(study.best_params)
print(study.best_value)
print(best_model.summary())
model_file = "best_model.h5"
best_model.save(model_file)

`
# Actual Behavior
After running code, I expect to make model file named "best_model.h5".
I saw an error page as attached. Please refer to the following error and log as well.
# error and log

[I 2021-01-23 19:12:35,802] A new study created in memory with name: no-name-2b2ac2d7-95c5-4bb2-8a12-4df2be6444cb
Epoch 1/100
19/19 [==============================] - 2541s 134s/step - loss: 2.4031 - accuracy: 0.1624 - val_loss: 3.6026 - val_accuracy: 0.0937
Epoch 2/100
19/19 [==============================] - 2543s 134s/step - loss: 1.7317 - accuracy: 0.3212 - val_loss: 1.9697 - val_accuracy: 0.3157
Epoch 3/100
19/19 [==============================] - 2574s 135s/step - loss: 1.4891 - accuracy: 0.4021 - val_loss: 1.5672 - val_accuracy: 0.4437
Epoch 4/100
19/19 [==============================] - 2523s 133s/step - loss: 1.0424 - accuracy: 0.5749 - val_loss: 2.4903 - val_accuracy: 0.4566
Epoch 5/100
19/19 [==============================] - 2557s 135s/step - loss: 0.8922 - accuracy: 0.6639 - val_loss: 3.0987 - val_accuracy: 0.4432
Epoch 6/100
19/19 [==============================] - 2586s 136s/step - loss: 0.5586 - accuracy: 0.8032 - val_loss: 1.9330 - val_accuracy: 0.6080
Epoch 7/100
19/19 [==============================] - 2627s 138s/step - loss: 0.4925 - accuracy: 0.8481 - val_loss: 1.2843 - val_accuracy: 0.7171
Epoch 8/100
19/19 [==============================] - 2619s 138s/step - loss: 0.3437 - accuracy: 0.8997 - val_loss: 0.6904 - val_accuracy: 0.8010
Epoch 9/100
19/19 [==============================] - 2543s 134s/step - loss: 0.2038 - accuracy: 0.9441 - val_loss: 1.6648 - val_accuracy: 0.6272
Epoch 10/100
19/19 [==============================] - 2547s 134s/step - loss: 0.2471 - accuracy: 0.9286 - val_loss: 0.5681 - val_accuracy: 0.8705
Epoch 11/100
19/19 [==============================] - 2548s 134s/step - loss: 0.1330 - accuracy: 0.9640 - val_loss: 0.3243 - val_accuracy: 0.9274
Epoch 12/100
19/19 [==============================] - 2538s 134s/step - loss: 0.1784 - accuracy: 0.9545 - val_loss: 2.0230 - val_accuracy: 0.6674
Epoch 13/100
19/19 [==============================] - 2536s 133s/step - loss: 0.0992 - accuracy: 0.9739 - val_loss: 0.1754 - val_accuracy: 0.9688
Epoch 14/100
19/19 [==============================] - 2531s 133s/step - loss: 0.1103 - accuracy: 0.9703 - val_loss: 0.3091 - val_accuracy: 0.9084
Epoch 15/100
19/19 [==============================] - 2539s 134s/step - loss: 0.1133 - accuracy: 0.9705 - val_loss: 0.1693 - val_accuracy: 0.9689
Epoch 16/100
19/19 [==============================] - 2542s 134s/step - loss: 0.2012 - accuracy: 0.9591 - val_loss: 0.3192 - val_accuracy: 0.9454
Epoch 17/100
19/19 [==============================] - 2532s 133s/step - loss: 0.0465 - accuracy: 0.9878 - val_loss: 0.2381 - val_accuracy: 0.9605
Epoch 18/100
19/19 [==============================] - 2542s 134s/step - loss: 0.0654 - accuracy: 0.9826 - val_loss: 0.2098 - val_accuracy: 0.9637
Epoch 19/100
19/19 [==============================] - 2534s 133s/step - loss: 0.0783 - accuracy: 0.9782 - val_loss: 0.1598 - val_accuracy: 0.9712
Epoch 20/100
19/19 [==============================] - 2542s 134s/step - loss: 0.0459 - accuracy: 0.9888 - val_loss: 0.3331 - val_accuracy: 0.9430
Epoch 21/100
19/19 [==============================] - 2537s 134s/step - loss: 0.0583 - accuracy: 0.9851 - val_loss: 0.2036 - val_accuracy: 0.9705
Epoch 22/100
19/19 [==============================] - 2538s 134s/step - loss: 0.0534 - accuracy: 0.9860 - val_loss: 0.2062 - val_accuracy: 0.9646
Epoch 23/100
19/19 [==============================] - 2539s 134s/step - loss: 0.0424 - accuracy: 0.9890 - val_loss: 0.6059 - val_accuracy: 0.8954
Epoch 00023: early stopping
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-5ab3d8acb473> in <module>
      1 sampler = RandomSampler(seed=5)
      2 study = optuna.create_study(direction="maximize",sampler=sampler,pruner=SuccessiveHalvingPruner())
----> 3 study.optimize(objective,n_trials=200,callbacks=[callback])
      4 best_model = study.user_attrs["best_model"]

~\Miniconda3\envs\kaggle\lib\site-packages\optuna\study.py in optimize(self, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
    379             callbacks=callbacks,
    380             gc_after_trial=gc_after_trial,
--> 381             show_progress_bar=show_progress_bar,
    382         )
    383 

~\Miniconda3\envs\kaggle\lib\site-packages\optuna\_optimize.py in _optimize(study, func, n_trials, timeout, n_jobs, catch, callbacks, gc_after_trial, show_progress_bar)
     68                 reseed_sampler_rng=False,
     69                 time_start=None,
---> 70                 progress_bar=progress_bar,
     71             )
     72         else:

~\Miniconda3\envs\kaggle\lib\site-packages\optuna\_optimize.py in _optimize_sequential(study, func, n_trials, timeout, catch, callbacks, gc_after_trial, reseed_sampler_rng, time_start, progress_bar)
    159 
    160         try:
--> 161             trial = _run_trial(study, func, catch)
    162         except Exception:
    163             raise

~\Miniconda3\envs\kaggle\lib\site-packages\optuna\_optimize.py in _run_trial(study, func, catch)
    228 
    229         if state == TrialState.COMPLETE:
--> 230             study._log_completed_trial(trial, cast(List[float], values))
    231         elif state == TrialState.PRUNED:
    232             _logger.info("Trial {} pruned. {}".format(trial.number, str(func_err)))

~\Miniconda3\envs\kaggle\lib\site-packages\optuna\study.py in _log_completed_trial(self, trial, values)
    693                     values[0],
    694                     trial.params,
--> 695                     self.best_trial.number,
    696                     self.best_value,
    697                 )

~\Miniconda3\envs\kaggle\lib\site-packages\optuna\study.py in best_trial(self)
     89             )
     90 
---> 91         return copy.deepcopy(self._storage.get_best_trial(self._study_id))
     92 
     93     @property

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

C:\Python37\Lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

C:\Python37\Lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_list(x, memo, deepcopy)
    213     append = y.append
    214     for a in x:
--> 215         append(deepcopy(a, memo))
    216     return y
    217 d[list] = _deepcopy_list

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

C:\Python37\Lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_list(x, memo, deepcopy)
    213     append = y.append
    214     for a in x:
--> 215         append(deepcopy(a, memo))
    216     return y
    217 d[list] = _deepcopy_list

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

C:\Python37\Lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

C:\Python37\Lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

C:\Python37\Lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

C:\Python37\Lib\copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

C:\Python37\Lib\copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

C:\Python37\Lib\copy.py in deepcopy(x, memo, _nil)
    167                     reductor = getattr(x, "__reduce_ex__", None)
    168                     if reductor:
--> 169                         rv = reductor(4)
    170                     else:
    171                         reductor = getattr(x, "__reduce__", None)

TypeError: can't pickle _thread.RLock objects

# package list

 Name =Version=Build  Channel
_py-xgboost-mutex=2.0=cpu_0
_tflow_select=2.3.0=eigen
absl-py=0.11.0=pyhd3eb1b0_1
alembic=1.5.2=pyhd3eb1b0_0
argon2-cffi=20.1.0=py37he774522_1
astunparse=1.6.3=py_0
async_generator=1.10=py37h28b3542_0
attrs=20.3.0=pyhd3eb1b0_0
backcall=0.2.0=py_0
blas=1.0=mkl
bleach=3.2.2=pyhd3eb1b0_0
blinker=1.4=py37_0
ca-certificates=2021.1.19=haa95532_0
cachetools=4.2.0=pyhd3eb1b0_0
certifi=2020.12.5=py37haa95532_0
cffi=1.14.4=py37hcd4344a_0
chainer=6.3.0=py_0
chardet=4.0.0=py37haa95532_1003
click=7.1.2=pyhd3eb1b0_0
cliff=3.5.0=pyhd8ed1ab_0
cmaes=0.7.0=pyhac0dd68_0
cmd2=0.9.22=py37hc8dfbb8_1
colorama=0.4.4=pyhd3eb1b0_0
colorlog=4.7.2=py37haa95532_1
cryptography=3.3.1=py37hcd4344a_0
cycler=0.10.0=py37_0
decorator=4.4.2=py_0
defusedxml=0.6.0=py_0
entrypoints=0.3=py37_0
filelock=3.0.12=pyhd3eb1b0_1
freetype=2.10.4=hd328e21_0
gast=0.3.3=py_0
google-auth=1.21.3=py_0
google-auth-oauthlib=0.4.2=pyhd3eb1b0_2
google-pasta=0.2.0=py_0
grpcio=1.31.0=py37he7da953_0
h5py=2.10.0=py37h5e291fa_0
hdf5=1.10.4=h7ebc959_0
icc_rt=2019.0.0=h0cc432a_1
icu=58.2=ha925a31_3
idna=2.10=pyhd3eb1b0_0
importlib-metadata=2.0.0=py_1
importlib_metadata=2.0.0=1
intel-openmp=2020.2=254
ipykernel=5.3.4=py37h5ca1d4c_0
ipython=7.19.0=py37hd4e2768_0
ipython_genutils=0.2.0=pyhd3eb1b0_1
jedi=0.18.0=py37haa95532_1
jinja2=2.11.2=pyhd3eb1b0_0
joblib=1.0.0=pyhd3eb1b0_0
jpeg=9b=hb83a4c4_2
json5=0.9.5=py_0
jsonschema=3.2.0=py_2
jupyter_client=6.1.7=py_0
jupyter_core=4.7.0=py37haa95532_0
jupyterlab=2.2.6=py_0
jupyterlab_pygments=0.1.2=py_0
jupyterlab_server=1.2.0=py_0
kaggle=1.5.10=py37h03978a9_0
keras-applications=1.0.8=py_1
keras-preprocessing=1.1.0=py_1
kiwisolver=1.3.0=py37hd77b12b_0
libpng=1.6.37=h2a8f88b_0
libprotobuf=3.13.0.1=h200bbdf_0
libsodium=1.0.18=h62dcd97_0
libtiff=4.1.0=h56a325e_1
libxgboost=0.90=1
lightgbm=3.1.1=py37hd77b12b_0
lz4-c=1.9.3=h2bbff1b_0
m2w64-gcc-libgfortran=5.3.0=6
m2w64-gcc-libs=5.3.0=7
m2w64-gcc-libs-core=5.3.0=7
m2w64-gmp=6.1.0=2
m2w64-libwinpthread-git=5.0.0.4634.697f757=2
mako=1.1.4=pyhd3eb1b0_0
markdown=3.3.3=py37haa95532_0
markupsafe=1.1.1=py37hfa6e2cd_1
matplotlib=3.3.2=haa95532_0
matplotlib-base=3.3.2=py37hba9282a_0
mistune=0.8.4=py37hfa6e2cd_1001
mkl=2020.2=256
mkl-service=2.3.0=py37h196d8e1_0
mkl_fft=1.2.0=py37h45dec08_0
mkl_random=1.1.1=py37h47e9c7a_0
msys2-conda-epoch=20160418=1
nbclient=0.5.1=py_0
nbconvert=6.0.7=py37_0
nbformat=5.1.2=pyhd3eb1b0_1
nest-asyncio=1.4.3=pyhd3eb1b0_0
notebook=6.2.0=py37haa95532_0
numpy=1.19.2=py37hadc3359_0
numpy-base=1.19.2=py37ha3acd2a_0
oauthlib=3.1.0=py_0
olefile=0.46=py37_0
openssl=1.1.1i=h2bbff1b_0
opt_einsum=3.1.0=py_0
optuna=2.4.0=pyhd8ed1ab_0
packaging=20.8=pyhd3eb1b0_0
pandas=1.2.1=py37hf11a4ad_0
pandoc=2.11=h9490d1a_0
pandocfilters=1.4.3=py37haa95532_1
parso=0.8.1=pyhd3eb1b0_0
pbr=5.5.1=py_0
pickleshare=0.7.5=pyhd3eb1b0_1003
pillow=8.1.0=py37h4fa10fc_0
pip=20.3.3=py37haa95532_0
prettytable=2.0.0=pyhd8ed1ab_0
prometheus_client=0.9.0=pyhd3eb1b0_0
prompt-toolkit=3.0.8=py_0
protobuf=3.13.0.1=py37ha925a31_1
py-xgboost=0.90=py37_1
pyasn1=0.4.8=py_0
pyasn1-modules=0.2.8=py_0
pycparser=2.20=py_2
pygments=2.7.4=pyhd3eb1b0_0
pyjwt=1.7.1=py37_0
pyopenssl=20.0.1=pyhd3eb1b0_1
pyparsing=2.4.7=pyhd3eb1b0_0
pyperclip=1.8.0=pyh9f0ad1d_0
pyqt=5.9.2=py37h6538335_2
pyreadline=2.1=py37_1
pyrsistent=0.17.3=py37he774522_0
pysocks=1.7.1=py37_1
python=3.7.9=h60c2a47_0
python-dateutil=2.8.1=py_0
python-editor=1.0.4=py_0
python-slugify=4.0.1=py_0
python_abi=3.7=1_cp37m
pytz=2020.5=pyhd3eb1b0_0
pywin32=227=py37he774522_1
pywinpty=0.5.7=py37_0
pyyaml=5.4.1=py37h2bbff1b_1
pyzmq=20.0.0=py37hd77b12b_1
qt=5.9.7=vc14h73c81de_0
requests=2.25.1=pyhd3eb1b0_0
requests-oauthlib=1.3.0=py_0
rsa=4.7=pyhd3eb1b0_1
scikit-learn=0.23.2=py37h47e9c7a_0
scipy=1.5.2=py37h9439919_0
send2trash=1.5.0=pyhd3eb1b0_1
setuptools=51.3.3=py37haa95532_4
sip=4.19.8=py37h6538335_0
six=1.15.0=py37haa95532_0
sqlalchemy=1.3.21=py37h2bbff1b_0
sqlite=3.33.0=h2a8f88b_0
stevedore=3.3.0=py37h03978a9_1
tensorboard=2.3.0=pyh4dce500_0
tensorboard-plugin-wit=1.6.0=py_0
tensorflow=2.3.0=mkl_py37h04bc1aa_0
tensorflow-base=2.3.0=eigen_py37h17acbac_0
tensorflow-estimator=2.3.0=pyheb71bc4_0
termcolor=1.1.0=py37_1
terminado=0.9.2=py37haa95532_0
testpath=0.4.4=py_0
text-unidecode=1.3=py_0
threadpoolctl=2.1.0=pyh5ca1d4c_0
tk=8.6.10=he774522_0
tornado=6.1=py37h2bbff1b_0
tqdm=4.55.1=pyhd3eb1b0_0
traitlets=5.0.5=py_0
typing=3.7.4.3=py37_0
typing_extensions=3.7.4.3=py_0
unidecode=1.1.2=pyhd3eb1b0_0
urllib3=1.24.3=py37_0
vc=14.2=h21ff451_1
vs2015_runtime=14.27.29016=h5e58377_2
wcwidth=0.2.5=py_0
webencodings=0.5.1=py37_1
werkzeug=1.0.1=py_0
wheel=0.36.2=pyhd3eb1b0_0
win_inet_pton=1.1.0=py37haa95532_0
wincertstore=0.2=py37_0
winpty=0.4.3=4
wrapt=1.12.1=py37he774522_1
xz=5.2.5=h62dcd97_0
yaml=0.2.5=he774522_0
zeromq=4.3.3=ha925a31_3
zipp=3.4.0=pyhd3eb1b0_0
zlib=1.2.11=h62dcd97_4
zstd=1.4.5=h04227a9_0

# Execution environment
- Optuna version: 2.4.0
- Python version: 3.7
- OS: Windows10 Miniconda3

Thank you all.

**Comment by nzw0301** [comment]
I'm afraid that your code does not work since some variables are undefined. But, I suggest you save your model's weights in the objective function with trial id instead save as a user-attribute, then you can load the model's weight after the optuna's optimisation.

See details on [this faq page](https://optuna.readthedocs.io/en/stable/faq.html#how-to-save-machine-learning-models-trained-in-objective-functions)

**Comment by EROPLM** [comment]
Thank you for your comment.
I want to use HDD as little as possible.
Would it be possible to save only best trial model?

I have another question.
What do you think is the cause of this error?

**Comment by EROPLM** [comment]
When I write this program, I use <a href="https://stackoverflow.com/questions/62144904/python-how-to-retrive-the-best-model-from-optuna-lightgbm-study">this page</a>.

**Comment by nzw0301** [comment]
Thank you for sharing the page.

> Would it be possible to save only best trial model?

Yes. I think [this answer](https://stackoverflow.com/a/62164601/2406562) is what you want: please use a global variable rather than the user-attribute to store keras model. Another option is to use a custom objective such that you save the best "performance" and save your model at the end of the evaluation of the objective as I answered before.

> What do you think is the cause of this error?

In my understanding, `tf.keras`'s model is supposed to be a non-pickle-able object, and `copy.deepcopy` used in a optuna's function to treat `best_trial` can copy a pickle-able object, so your error happens.

Reference: https://github.com/tensorflow/tensorflow/issues/34697

**Comment by EROPLM** [comment]
@nzw0301 Thank you for your comment.
Could you tell me the way to solve the error?
I think I can solve the error by making a non-pickle-able object a pickle-able object.
Could you tell me how to do it?

**Comment by nzw0301** [comment]
Could be? Please check comments in the tensorflow's issue that I have shared in the previous comment to you.

However, I do not recommend converting your model to pickle-able object since [this answer](https://stackoverflow.com/questions/62144904/python-how-to-retrive-the-best-model-from-optuna-lightgbm-study/62164601#62164601) will be enough for you.

**Comment by EROPLM** [comment]
I'll check tensorflow's issue and trial and error.
Thank you very much.

**Comment by nzw0301** [comment]
@EROPLM Could you close this issue? I believe your problem has come from `tf.keras` and I have provided other ways to solve your issue.

**Comment by EROPLM** [comment]
@nzw0301 Thank you for your advice. This Error was resolved thanks to your support.
I will close this issue.
Thank you very much!

**Comment by nzw0301** [comment]
@EROPLM Awesome! I'm glad to hear that!

Cheers,
