### ISSUE TITLE
visualization problem

### ISSUE THREAD

**Issue by Uproar197** [optuna/optuna#2262]
Hello, I am new to optuna, and now I'm trying to make use of optuna's visualization tools on linux server, but after i run the example provided at https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.plot_edf.html
there is no response, that means I can not visualize it. Can you do help me ?

**Comment by not522** [comment]
Thank you for your question. Maybe you need to call the `.show()` method. Because visualization functions just return `plotly.graph_objs._figure.Figure`.
```
fig = optuna.visualization.plot_edf([study0, study1, study2])
fig.show()
```

**Comment by Uproar197** [comment]
Thanks !

**Comment by crcrpar** [comment]
Let me close this as the question seems to be resolved (It's great)!
