### ISSUE TITLE
How can I alter ranges of the parameters during the optimization process?

### ISSUE THREAD

**Issue by ZumbiAzul** [optuna/optuna#2263]
How can I alter ranges of the parameters during the optimization process?

So I run this command:
```
study.optimize(objective)
```
When it reaches 100 trials I would like it to change ranges for the suggested parameters.
Is there a way of doing it?

**Comment by nzw0301** [comment]
How about this?

```python
import optuna



def objective(trial):
    
    if trial.number > 100:
        x = trial.suggest_uniform("x", -2, 2)
    else:
        x = trial.suggest_uniform("x", -1, 1)
    return (x - 2) ** 2


study = optuna.create_study()
study.optimize(objective, n_trials=200)
```

**Comment by ZumbiAzul** [comment]
Thanks! It works.

**Comment by nzw0301** [comment]
@ZumbiAzul Awesome! Could you close this issue? I believe your issue is solved.
