### ISSUE TITLE
Is it possible to re-use a study with a different sampler?

### ISSUE THREAD

**Issue by Hoeze** [optuna/optuna#2264]
Hi, I wonder whether it would be possible to re-use an existing studie's trials.
I.e. create a study with a RandomSampler and then, lateron, load the trial outcomes into a different study to pre-initialize e.g. some TPESampler.

**Comment by blaney83** [comment]
Yes, that shouldn't be a problem. If you want to initialize a baseline study with e.g. `n` startup trials, save the study locally after `n` trials and then load it again and continue with a different sampler or a variety of samplers to test their performance, that will work just fine. Each time you load a study, it uses the provided Sampler instance or creates a default if none is provided.

Some samplers use this basic principle internally already. For example, the TPE and Multi-Objective TPE samples can be initialized with the optional `n_startup_trials` kwarg which defines the number of initialization trials to be performed. These first `n` trials will use a random sampling method to explore the search space before switching over to the algorithmic optimization.

If you wanted to test different Sampler configurations, you could manually create these random trials before loading the saved study and providing a different Sampler each time. Of course, you'll be losing some of the random noise you get from initializing a new study each time, but this could be helpful if your focus is exploration of Samplers and their performance on your usecase.

**Comment by Hoeze** [comment]
Thanks for the great explanation!
