### ISSUE TITLE
Optuna 2.4.0 and XGBoost 1.3.3 : Using optuna integration and xgb.cv() : n_jobs > 16

### ISSUE THREAD

**Issue by SurajitTest** [optuna/optuna#2270]
1. When I use Optuna 2.4.0 and XGBoost 1.3.3 (using optuna integration and xgb.cv()) with 'n_jobs'=32 in a machine that has 60 CPUs - the program runs for 18 hours without any trial output.

2. I am presently using Optuna 2.4.0 and XGBoost 1.3.3 , with 'n_jobs'=16 on a machine with 60 CPUs, I start obtaining results of trial outputs within 45-60 mins.

As I have a machine with 60 CPUs , what value to set for n_jobs (greater than 16)  so that I can complete trials faster ?

**Comment by toshihikoyanase** [comment]
Hi @SurajitTest
Thank you for your question.

I guess XGBoost also creates threads (c.f., https://stackoverflow.com/questions/48269248/limiting-the-number-of-threads-used-by-xgboost) in addition to Optuna's threads. I'm not fully sure, but you might unexpectedly many threads (e.g., `n_jobs` * `n_cpus` = 32 * 60 = 1920).
How about setting the environment variable `OMP_NUM_THREADS=1` to restrict the number of threads created by XGBoost?

**Comment by SurajitTest** [comment]
Hi @toshihikoyanase,  
                                    Thanks a ton for your response. Presently , I am running with n_jobs=16 and I did observe that the OMP_NUM_THREADS environment variable is not set.  Shall  (n_jobs=32,OMP_NUM_THREADS environment variable=1) complete trials faster as compared to (n_jobs=16,OMP_NUM_THREADS environment variable is not set) considering the given below ?
1. Number of trials=500
2. I am presently using Optuna 2.4.0 and XGBoost 1.3.3 (using optuna integration and xgb.cv())
3. I am using 5 fold stratified cross validation on a dataset with about 300 features(after OHE) and 138,000 rows

**Comment by toshihikoyanase** [comment]
I'm sorry but I cannot tell whether (n_jobs=32,OMP_NUM_THREADS environment variable=1) is faster or not since I'm not fully confident with the cause of the problem.

Is it possible to measure the actual computation time?
