### ISSUE TITLE
Handling Times

### ISSUE THREAD

**Issue by tide90** [optuna/optuna#2272]
I cannot see how to do this in asimple way withot subclassing your whole framework:

I want to write a message lets say every 1 hour to a file if my study is running.

```
start = time.time()
start_data= datetime.now()

def objective(trial):

  print("MULTIPLE OF 1 MIN: ", (time.time() - start) // 60)

  if (time.time() - start) // 60 == 1:
    print("1 MIN OVERb Since")
    print(start_data)
    start = time.time()
    start_data= datetime.now()

    ....
    
   return score


study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=300, timeout=None)
```

But since start is outside the function it is unknown inside the trials...

`UnboundLocalError: local variable 'start' referenced before assignment
`
How can I handover a start time to measure how much time is elapsed? I just can start the time each trial...

**Comment by nzw0301** [comment]
I think the simplest way to define your own objective as in [this page](https://optuna.readthedocs.io/en/stable/faq.html#how-to-define-objective-functions-that-have-own-arguments). The objective stores the `start_time` and check your condition in each call.

So how about this?


```python
import optuna
import time
from datetime import datetime


class Objective(object):
    def __init__(self, min_x, max_x):
        self.min_x = min_x
        self.max_x = max_x
        self.start_time = time.time()

    def __call__(self, trial):
        time.sleep(0.5)  # for this example

        # Calculate an objective value by using the extra arguments.
        x = trial.suggest_uniform("x", self.min_x, self.max_x)

        current_time = time.time()

        if current_time- self.start_time >= 1.0:  # check the evaluation takes more than 1 second since ether the last message or the initialisation
            print("1 MIN OVER Since", self.start_time)
            self.start_time = current_time

        return (x - 2) ** 2


study = optuna.create_study(direction="maximize")
study.optimize(Objective(1., 1.), n_trials=10, timeout=None)
```

**Comment by nzw0301** [comment]
@tide90 hi, did you use this example for your issue?

**Comment by nzw0301** [comment]
Please feel free to re-open the issue if the question was not solved.
