### ISSUE TITLE
How to handle incremental addition of new models?

### ISSUE THREAD

**Issue by Hoeze** [optuna/optuna#2275]
Hi, I'd like to incrementally add more models / architectures to my study like this:
```python
list_of_models = ["LinReg", "some_new_model"]
model_type = trial.suggest_categorical("model_type", list_of_models)
```
However, when I try to append more models I get this error:
`ValueError: CategoricalDistribution does not support dynamic value space.`

Is there a good way to solve this issue?

**Comment by nzw0301** [comment]
How about using `suggest_int` with a dynamic range instead of using `suggest_categorical`?

**Comment by Hoeze** [comment]
Does this have some practical issues because of integer being ordered?

**Comment by nzw0301** [comment]
I guess there is no issue with `log=False`.
