### ISSUE TITLE
handling evaluation cost

### ISSUE THREAD

**Issue by majiang** [optuna/optuna#2289]
## Motivation
Depending on the parameters, a trial takes a short or long time, or more generally, costs less or more.  Currently, [we can utilize timeout-decorator to mark a trial pruned if it takes too long a time](https://github.com/optuna/optuna/issues/1484).  It is more convenient to easily invest more to promising trials than others.

## Description
A sampler which
* models the cost *C*(*p*) for evaluation with parameters *p*,
* samples low-*C* parameters with larger probability,
* to achieve good optimization result with given total cost, rather than total number of trials.

**Comment by blaney83** [comment]
Just an idea- could you add a penalty to the trial value if it's long running? I feel like you could steer the algorithm just by taking time into account in the value. This would be more subtle than pruning for example, as the trials will finish, but they will be viewed as less promising when choosing the next parameters.
