### ISSUE TITLE
Importances in plot do not match values in dictionary saved out

### ISSUE THREAD

**Issue by brethvoice** [optuna/optuna#2296]
The parameter importances I saved out as a .json dictionary do not match what appears when they are plotted automatically.

## Expected behavior

The numbers and order of importance could match to make more sense.

## Environment

- Optuna version: 2.4
- Python version: 3.8
- OS: Windows 10

## Steps to reproduce

1.  Save out parameter importances ordered dictionary as .json file in callback, as so:
```
def save_importances_as_json(study, trial):
    completed_trials = [
        t for t in study.trials if t.state == optuna.trial.TrialState.COMPLETE
    ]
    if len(completed_trials) > 1:
        importances_dict = optuna.importance.get_param_importances(study)
        with open('importances.json', 'w') as fp:
            json.dump(importances_dict, fp, indent=2)
```
2.  After `study.optimize(objective, callbacks=[save_importances_as_json])` is completed, run the following to produce the plot of importances:
```
fig = optuna.visualization.plot_param_importances(study)
fig.show()
```
3.  Compare the two.  The importances.json file will be over-written at the end of each trial so it will be up to date.

**Comment by brethvoice** [comment]
To see what the plotted importances could look like, use the following code (stripped down from [source](https://optuna.readthedocs.io/en/stable/_modules/optuna/visualization/_param_importances.html#plot_param_importances)):
```
from collections import OrderedDict
from optuna.visualization._plotly_imports import go

def plot_param_importances(importances) -> "go.Figure":
    """Plot hyperparameter importances.
        This function visualizes the results of :func:`optuna.importance.get_param_importances`.
    Args:
        importances: ordered dict
    Returns:
        A :class:`plotly.graph_objs.Figure` object.
    """
    layout = go.Layout(
        title="Hyperparameter Importances",
        xaxis={"title": f"Importance"},
        yaxis={"title": "Hyperparameter"},
        showlegend=False,
    )
    # Importances cannot be evaluated without completed trials.
    importances = OrderedDict(reversed(list(importances.items())))
    importance_values = list(importances.values())
    param_names = list(importances.keys())
    fig = go.Figure(
        data=[
            go.Bar(
                x=importance_values,
                y=param_names,
                text=importance_values,
                texttemplate="%{text:.2f}",
                textposition="outside",
                cliponaxis=False,  # Ensure text is not clipped.
                orientation="h",
            )
        ],
        layout=layout,
    )
    return fig
```
Then in a Python environment, load importances.json, then show the `plot_param_importances` figure instantiated with it as the sole argument.

**Comment by hvy** [comment]
This is actually not a bug per se. https://github.com/optuna/optuna/issues/2207 is a duplicate.

**Comment by brethvoice** [comment]
@hvy thank you for the educational comment.  I have updated my code to do the following:
```
FANOVA_EVALUATOR_SEED = 0
FANOVA_evaluator = optuna.importance.FanovaImportanceEvaluator(seed=FANOVA_EVALUATOR_SEED)
```
and then whenever I call `optuna.importance.get_param_importances()` or `optuna.visualization.plot_param_importances()` I pass it this same evaluator, based on the same random seed.
