### ISSUE TITLE
Add RL and multi-objective examples to examples/readme.MD

### ISSUE THREAD

**Issue by Crissman** [optuna/optuna#2306]
In working on #2302 , I noticed that multi-objective and rl examples are not linked in the examples/readme.MD. Once that PR is merged, will add them to the examples page.

While there, would also be good to simplify the links for that page, to remove the repetition between simple and pruning examples, which are in the same folder now anyway.

**Comment by jeromepatel** [comment]
@Crissman I would like to work on this issue. Can you provide some guidance/steps or how should I tackle this issue?

**Comment by hvy** [comment]
Let me close this issue as fixed by #2432 .
