### ISSUE TITLE
In trial you get always the same suggestions?

### ISSUE THREAD

**Issue by tide90** [optuna/optuna#2310]
Hi,

I thought I have to tackle this and take care by myself, but the suggestions are always the same within each trial?

So using a for loop inside the trial I get always the same suggestions of the parameters. Is this intended or accidentally?

```
def objective(trial,):
    for i in range(10):
        x1 = trial.suggest_uniform("x1", 0, 3)
        x2 = trial.suggest_categorical("x2", [1, 2, 3])
        
        print(x1, x2)

    return (x - 2) ** 2

```

I get always the same x1, x2 per trial.

**Comment by nzw0301** [comment]
Could you share the full code to reproduce the results?

**Comment by nzw0301** [comment]
This is the intended behaviour. If a hyper-parameters is already sampled in a trial, optuna does not sample the hyper-parameter again.

Related issue: https://github.com/optuna/optuna/blob/0280b598a85a6bc79b22a10a1e5edde82a09044e/optuna/trial/_trial.py#L704
