### ISSUE TITLE
No plots appearing when using visualisation tools.

### ISSUE THREAD

**Issue by ZumbiAzul** [optuna/optuna#2312]
Hello, I am using Spyder to write my python code, and I am using optuna to optimise my neural network.
When I try any of the optuna's visualisation commands, there is no plot appearing in the Plots section of the Spyder interface.

Amongst the lines I tried are the following
```
fig = optuna.visualization.plot_slice(study, 
                                  params=["network_params['conv_layer_out_channels'][1]",
                                          "network_params['conv_layer_out_channels'][1]"])
optuna.visualization.plot_intermediate_values(study)
optuna.visualization.plot_optimization_history(study)
optuna.visualization.plot_param_importances(study)
```

Is there a way how I can use the Figure object `fig` that is returned by optuna visualisation methods to force the plot to be created?

**Comment by crcrpar** [comment]
Hi @ZumbiAzul 

I would try `fig.show()` method to display the figure.
https://github.com/optuna/optuna/issues/2262 might be related.

**Comment by ZumbiAzul** [comment]
> Hi @ZumbiAzul
> 
> I would try `fig.show()` method to display the figure.
> #2262 might be related.

@crcrpar `fig.show()` doesn't seem to have any effect.

**Comment by ZumbiAzul** [comment]
Using `dir(fig)`, I found that `fig` has the method `write_image('image.png')`, which creates the file `image.png` into the working directory. This is, of course not the direct solution, but better than nothing.

Another method was `to_image()`, but I havent figured out how to use it yet to show the plot in Spyder.

**Comment by SonghuaHu-UMD** [comment]
You may use the browser to show the figure since Spyder did not support the figure in plotly.
`optuna.visualization.plot_intermediate_values(study).show(renderer="browser")`

**Comment by StatsGary** [comment]
> You may use the browser to show the figure since Spyder did not support the figure in plotly. `optuna.visualization.plot_intermediate_values(study).show(renderer="browser")`

This worked for me. Thanks.

**Comment by AraceliAL** [comment]
You can also use `optuna.visualization.matplotlib.plot_intermediate_values(study)`

**Comment by chenzhiling616** [comment]
> You can also use `optuna.visualization.matplotlib.plot_intermediate_values(study)`

success！Thank you！

**Comment by BertramLoong** [comment]
This is also worked:
```python
fig = optuna.visualization.plot_contour(study)
fig.show()
```
