### ISSUE TITLE
`LightGBMTuner` default metric consideration

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#2314]
## Motivation

The following comment in https://github.com/optuna/optuna/pull/2299#issuecomment-773321979 should be addressed.

>> ... binary_logloss was a default value of metric, but it's supposed to set the metric corresponding to objective according to the reference. This issue should be fixed in a follow-up PR.

> "" (empty string or not specified) means that metric corresponding to specified objective will be used (this is possible only for pre-defined objective functions, otherwise no evaluation metric will be added)

(C.f. https://lightgbm.readthedocs.io/en/latest/Parameters.html#metric)

Currently, the `LightGBMTuner` always defaults to `binary_logloss`.

## Description

See above.

**Comment by hvy** [comment]
@toshihikoyanase, is this aligned with your interpretation?

**Comment by toshihikoyanase** [comment]
Yes, it is! Thank you for reporting the issue.
