### ISSUE TITLE
Change inheritance of PytorchLightningPruningCallback

### ISSUE THREAD

**Issue by TezRomacH** [optuna/optuna#2315]
## Motivation

PyTorchLightningPruningCallback class is inherited from `pl.EarlyStopping`.
But EarlyStopping itself determines when to stop training, without using data from Trial. Is it necessary to keep such a construct or is it enough to inherit from `pl.Callback`?

## Additional context (optional)

Previous discussion was here: #2294

**Comment by himkt** [comment]
Thank you @TezRomacH for reporting the problem (#2294) and working on fixing it (#2326).
Let me close this issue because the problem seems to be fixed now. (cc. @toshihikoyanase, @HideakiImamura)
