### ISSUE TITLE
Two issues with optuna.integration.allennlp.AllenNLPExecutor. One is error, the other is wrong results.

### ISSUE THREAD

**Issue by allenciox** [optuna/optuna#2317]
There are two issues, using Optuna with optuna.integration.allennlp.AllenNLPExecutor.   The first is that everything works fine when number of jobs is set to be greater than one.   But when njobs is set > 1 an error always occurs after a random number of trials. 

The second is that when the parameter to be optimized is based on validation data, it is always obtained from the last epoch, not the best epoch, 

## Expected behavior

I expected to be able to do a run with study.optimize( objective, n_jobs=2) without getting an error at some random trial about some other trial. 100% of the time, at some random point an error is generated. 

I expected that when using "best_validation_accuracy" as the metric, that it would return the validation_accuracy of the "best" epoch, not the last epoch, when patience is set to 4.  On an example run where I set max_epochs to 32, the last epoch of trial 36 is listed as the "best_trial" in the results with a validation accuracy of .691.  However, for trial 45, the 23rd epoch had a validation accuracy of .694 but had an accuracy of .689 in the 27th (and last, because of patience of 4) epoch.  Yet this is not returned as the best model, since the last epoch had a worse result. 

## Environment

- Optuna version: 2.4.0
- Python version: 3.7.7
- OS: Linux
- (Optional) Other libraries and their versions:
- allennlp: 1.2.1
- SQLAlchemy                         1.3.17
- sqlitedict                         1.6.0

## Error messages, stack traces, or logs

This error is generated if and only if n_jobs > 1 when n_trials is set to 64.   Sometimes it might run a bunch of trials before it happens, other times it happens early on (as in the error below)  It generally happens faster if n_jobs is set to higher numbers. 

[W 2021-02-04 16:29:48,994] Trial 2 failed because of the following error: RuntimeError('Trial#3 has already finished and can not be updated.')
Traceback (most recent call last):
  File "/bigdisk/lax/cox/anaconda/lib/python3.7/site-packages/optuna/_optimize.py", line 198, in _run_trial
    value_or_values = func(trial)

This is immediately followed by another error message, and the process ends soon after that:
2021-02-04 16:29:49,839 - ERROR - sqlalchemy.pool.impl.NullPool - Exception closing connection <sqlite3.Connection object at 0x7f861010fe30>
Traceback (most recent call last):
  File "/bigdisk/lax/cox/anaconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 697, in _finalize_fairy
    fairy._reset(pool)
  File "/bigdisk/lax/cox/anaconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 893, in _reset
    pool._dialect.do_rollback(self)
  File "/bigdisk/lax/cox/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 540, in do_rollback
    dbapi_connection.rollback()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140213797365504 and this is thread id 140213805758208.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/bigdisk/lax/cox/anaconda/lib/python3.7/site-packages/sqlalchemy/pool/base.py", line 270, in _close_connection
    self._dialect.do_close(connection)
  File "/bigdisk/lax/cox/anaconda/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 546, in do_close
    dbapi_connection.close()
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 140213797365504 and this is thread id 140213805758208.

```
# error messages, stack traces, or logs
```

## Steps to reproduce

1. Set up study
2. Run study.optimize()
3. View results

## Reproducible examples (optional)
```python
# python code
Here is my code:
import optuna
def objective(trial: optuna.Trial) -> float:
    trial.suggest_int("rnn_hidden", 1, 64, log=True)
    trial.suggest_float("model_dropout", 0.0, 0.8)
    trial.suggest_float("feedforward_dropout", 0.0, 0.8)
    trial.suggest_float("lr", 5e-4, 5e-1, log=True)
    trial.suggest_categorical("opt_type", ["adam","adamw","adagrad"])

    executor = optuna.integration.allennlp.AllenNLPExecutor(
        trial=trial,  # trial object
        config_file=f"/bigdisk/lax/cox/jupyter/news3_cat.jsonnet",  # path to jsonnet
        serialization_dir=f"/bigdisk/lax/cox/jupyter/news3/o_{trial.number}",
        metrics="best_validation_accuracy",
        force=True,
        file_friendly_logging=True,
    )
    return executor.run()


study = optuna.create_study(
        storage="sqlite:////bigdisk/lax/cox/db/news3.db",  # save results in DB
        sampler=optuna.samplers.TPESampler(seed=24),
        study_name="optuna_news3_cat",
        direction="maximize",
        pruner=optuna.pruners.HyperbandPruner(),  # pruner here!
        load_if_exists=True,
    )

    timeout = 60 * 5  # timeout (sec): 60*60*10 sec => 10 hours
    
    study.optimize(
        objective,
        n_jobs=4,  # number of processes in parallel execution
        n_trials=64,  # number of trials to train a model
        timeout=timeout,  # threshold for executing time (sec)
         )
    
If I set n_jobs above to 1, it always runs, but doesn't return the best result from a trial. 

## Additional context (optional)

this is my jsonnet script that is referenced above:

local batch_size = 16;
local cuda_device = 0;
local num_epochs = 32;
local patience=4;
local embedding_dim=300;
local model_dropout=0.2;
local feedforward_dropout=0.2;
local opt_lr=0.001;

local data_path="/bigdisk/lax/cox/data/nhtsa";
local seed = 3542;
local opt_type="adam";
local env(var,type='char') = 
      if type == 'char' then std.extVar(var)
      else if type == 'int' then std.parseInt(std.extVar(var))
      else if type == 'float' then std.parseJson(std.extVar(var))
      else if type == 'bool' then (std.parseInt(std.extvar(var)) == 1)
      ;
local seed=env('seed','int');
local model_dropout=env('model_dropout','float');
local feedforward_dropout=env('feedforward_dropout','float');
local hidden_dims=env('rnn_hidden', 'int');
local opt_type=env('opt_type');
// local opt_type=std.extvar("opt_type");
local opt_lr=env('opt_lr', 'float');
// local opt_eps=env('opt_eps', 'float');


{
  numpy_seed: seed,
  pytorch_seed: seed,
  random_seed: seed,
  dataset_reader: {
    type: "text_classification_jsonfile",
    text_key: "cdescr",
    label_key: "component",
    token_indexers: {
       tokens: {
          type: "single_id",
          },
       },
    },
    train_data_path: data_path + "_train.json",
    // train_data_path: "/bigdisk/lax/cox/data/news3_train.json",
    validation_data_path: data_path + "_val.json",            
    model: {
       type: "basic_classifier",
       dropout: model_dropout,
       text_field_embedder: {
           token_embedders: {
              tokens: {
                 type: "embedding",
                 embedding_dim: embedding_dim,
                 trainable: false,
                 pretrained_file: data_path + "_embed.txt",
                 },
              },
           },
       // seq2seq_encoder: ,
       seq2vec_encoder: {
          type: "bag_of_embeddings",
          embedding_dim: embedding_dim,
          averaged: true,
          },
       feedforward: {
          input_dim: embedding_dim,
          num_layers: 1,
          hidden_dims: hidden_dims,
          dropout: feedforward_dropout,
          activations: {
             type: 'torch.nn.ReLU'
             },
          },
       
       },
    data_loader: {
       "batch_size": batch_size,
       "shuffle": true,
       // batches_per_epoch: None,
       },
    trainer: {
     epoch_callbacks: [ {type: 'optuna_pruner',},],
     "optimizer": {
       type: opt_type,   // can be adam, sparseadam, adamax, adamw, huggingface_adamw, adagrad,dense_sparse_adam
       lr: opt_lr,       // default is 0.001
       // betas: opt_beta,  // default is Tuple[float, float] = (0.9, 0.999)
       // eps: opt_eps,     // default is 1e-08
       // weight_decay: opt_decay, // default is 0
        },
    "num_epochs": num_epochs,
    "patience": patience,
    "cuda_device": cuda_device,
    // "validation_metric": "+f1-measure-overall",

    },

  }

**Comment by allenciox** [comment]
whoops, timeout I used was actually 60*60*12, not 60*5 as reported (that was on a debugging run, to try to discover more about what was going on)

**Comment by himkt** [comment]
Hello @allenciox. First of all, sorry for the late reply.
And thank you for trying Optuna with AllenNLP.

If you want to run parallel execution, please try simply running your Python code from multiple prompts instead of specifying `n_jobs` in `optimize`.

(And also, consider using [allennlp-optuna](https://github.com/himkt/allennlp-optuna), if you want to use Optuna in `allennlp` command. `allennlp-optuna` provides a way to optimize your AllenNLP model with JSON style search space and an ordinal AllenNLP config file.)

I'll investigate about wrong result as well.

**Comment by himkt** [comment]
> // "validation_metric": "+f1-measure-overall",

I'm wondering allennlp trainer picks the best epoch based on the value of `loss`, as you commented out `validation_metric` in your trainer configuration. (`GradientDescentTrainer` watches `loss` by default. https://docs.allennlp.org/v1.3.0/api/training/trainer/#gradientdescenttrainer)

What happens if a configuration is updated to watch an accuracy as a validation metric?
If it doesn't solve your problem, I want to read a full log of training.
