### ISSUE TITLE
`model_dir` of `LightGBMTunerCV` is not generated.

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2324]
## Expected behavior 

According to [`LightGBMTuner` ](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTuner.html#optuna.integration.lightgbm.LightGBMTuner), if `model_dir` does not exist, optuna creates the directory, and saves boosters into the directory. I can confirm that I just add `model_dir=` (say `model_dir="./boosters"`) to the argument of `.train()` in [this example](https://github.com/optuna/optuna/blob/533f081d33817f2a9a37b21916eb5f03a0fc13c2/examples/lightgbm_tuner_simple.py#L30).

> `model_dir` – A directory to save boosters. By default, it is set to None and no boosters are saved. Please set shared directory (e.g., directories on NFS) if you want to access `get_best_booster()` in distributed environments. Otherwise, it may raise ValueError. If the directory does not exist, it will be created. The filenames of the boosters will be `{model_dir}/{trial_number}.pkl` (e.g., `./boosters/0.pkl`).

However, when I add the same argument to `LightGBMTunerCV` in [this example](https://github.com/optuna/optuna/blob/533f081d33817f2a9a37b21916eb5f03a0fc13c2/examples/lightgbm_tuner_cv.py#L25), the directory is not generated. We (at least I) do not expect this inconsistent behavior.

I also replace `train` with `run` and set `model_dir` as in `LightGBMTunerCV`'s case I described for `LightGBMTuner`, and it worked well:

```python
tuner = lgb.LightGBMTuner(params, dtrain, valid_sets=[dtrain, dval], verbose_eval=100, early_stopping_rounds=100,
                          model_dir="./best_boosters",)
tuner.run()
```

## Environment

- Optuna version: 533f081
- Python version: 3.8.6
- OS: MacOS Catalina
- (Optional) Other libraries and their versions:
    - lightgbm: 3.1.1

## Reproducible example

```python
import sklearn.datasets
from sklearn.model_selection import KFold

import optuna.integration.lightgbm as lgb


if __name__ == "__main__":
    data, target = sklearn.datasets.load_breast_cancer(return_X_y=True)
    dtrain = lgb.Dataset(data, label=target)

    params = {
        "objective": "binary",
        "metric": "binary_logloss",
        "verbosity": -1,
        "boosting_type": "gbdt",
    }

    tuner = lgb.LightGBMTunerCV(
        params, dtrain, verbose_eval=100, early_stopping_rounds=100, folds=KFold(n_splits=3),
        model_dir="./boosters",
    )

    tuner.run()

    print("Best score:", tuner.best_score)
    best_params = tuner.best_params
    print("Best params:", best_params)
    print("  Params: ")
    for key, value in best_params.items():
        print("    {}: {}".format(key, value))

```

**Comment by crcrpar** [comment]
Somehow `"model_dir"` is not listed in `LightGBMTunerCV` documentation: https://optuna.readthedocs.io/en/latest/reference/generated/optuna.integration.lightgbm.LightGBMTunerCV.html, 

![image](https://user-images.githubusercontent.com/16191443/107150915-6cbf6380-69a3-11eb-802d-cd96b1c3cf19.png)

**Comment by toshihikoyanase** [comment]
@nzw0301 @crcrpar Thank you for your investigation. We should fix this bug.

Currently, `LightGBMTuner.__init__` creates the `model_dir` if it does not exist.
https://github.com/optuna/optuna/blob/03eb57eb8eb1d844936445f6768c6d13fc859e34/optuna/integration/_lightgbm_tuner/optimize.py#L832-L835

But, we can move the logic to the `LightGBMBaseTuner.__init__` because all the subclasses have the `model_dir` argument.
https://github.com/optuna/optuna/blob/03eb57eb8eb1d844936445f6768c6d13fc859e34/optuna/integration/_lightgbm_tuner/optimize.py#L403

In addition, we also need to add the description of `model_dir` and `returns_booster` to the `LightGBMTunerCV`, but I think we can separate the PRs.

@nyanhi Are you interested in this issue?

**Comment by nyanhi** [comment]
@toshihikoyanase Sure, I will take a look this issue this weekend. Sorry for the delay in response.

**Comment by toshihikoyanase** [comment]
@nyanhi Thanks! If you have any questions on this issue, please feel free to ask me.

**Comment by crcrpar** [comment]
closing, as 2336 has been landed.

**Comment by nzw0301** [comment]
Thanks, guys!
