### ISSUE TITLE
What Sampling function does Optuna use and how to use a custom Sampling function

### ISSUE THREAD

**Issue by viiids** [optuna/optuna#2339]
I am interested in knowing what Sampling function Optuna uses and also if I can customize it. Also, I need to pass some additional information while observing trials and need this information when running my custom sampling function. Is there a pluggable way to do this?

**Comment by y0z** [comment]
Hi. The tutorial about User-Defined Sampler may be helpful.
https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/005_user_defined_sampler.html#sphx-glr-tutorial-20-recipes-005-user-defined-sampler-py

**Comment by viiids** [comment]
@y0z thank you for responding. My acquisition function also changes after every observation so ideally I would like to create a new study with a freshly updated instance of CustomSampler and observe all the existing trials into that study again. 

So is there a service API similar to what most other HPO libraries have where I can request for new trials to be evaluated and observe existing trials, as opposed to using the `study.optimize` method?

**Comment by y0z** [comment]
Although I'm not so an expert in Optuna, you might be able to implement what you want by combining the following APIs.
`add_trials` API
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.add_trials
`ask` and `tell` APIs
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.ask
`get_trials` API
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.get_trials
