### ISSUE TITLE
examples/kubernetes `check_study.sh` should match whole words

### ISSUE THREAD

**Issue by twolffpiggott** [optuna/optuna#2356]
In the [Distributed Optimisation on Kubernetes](https://github.com/optuna/optuna/tree/master/examples/kubernetes) example, the `check_study` script is intended to ensure that a study exists before allowing the Optuna workers to start optimisation.

Since it uses `grep PATTERN` instead of `grep -w PATTERN`, it can succeed when a study that only has "k8s_mlflow" as a substring exists e.g. "foo_k8s_mlflow" but the study "k8s_mlflow" does not exist. This IMO is unexpected behaviour and can allow the workers to start without the expected study existing.

https://github.com/optuna/optuna/blob/7cd4fa3c764b5ef8c0e9d14096ebe2453ba3b651/examples/kubernetes/mlflow/check_study.sh#L2

I would suggest the very minor update of using `grep -w PATTERN` to ensure the expected study exists and prevent matching substrings.

**Comment by hvy** [comment]
Makes sense, thanks a lot for the report. Would you like to send a PR? Otherwise, I could label this as `contribution-welcome`.

**Comment by twolffpiggott** [comment]
Great, no problem- I'd love to make a PR :)

**Comment by hvy** [comment]
Oh, that'd be great.

**Comment by himkt** [comment]
Let me close this issue, as #2363 was merged. Thank you @twolffpiggott for your great contribution!
