### ISSUE TITLE
SuccessiveHalvingPruner Implementation question

### ISSUE THREAD

**Issue by veritas9872** [optuna/optuna#2358]
According to the documentation, the SuccessiveHalvingPruner implements [ASHA](https://arxiv.org/pdf/1810.05934.pdf).

However, it does not expose the number of `brackets` as a hyper-parameter and has a `bootstrap_count` variable instead.

Are these two equivalent? If not, I would like to request more documentation on what this variable does.

Also, if there is no way to change the number of brackets, I would like to request a fix.

**Comment by crcrpar** [comment]
I'm not quite sure whether I understand your question correctly, though the number of brackets is a value used inside Hyperband is computed in `HyperbandPruner` as follows:
https://github.com/optuna/optuna/blob/563f3a7d8c738bc0d645d0cda1e6e827782578ab/optuna/pruners/_hyperband.py#L195-L210.

**Comment by veritas9872** [comment]
@crcrpar Does this mean that `n_brackets` cannot be specified during class initialization? I believe that this was a hyper-parameter that could be set by the user. The original paper uses a default of 3 and the implementation in ray tune uses a default of 1.

**Comment by HideakiImamura** [comment]
> However, it does not expose the number of brackets as a hyper-parameter and has a bootstrap_count variable instead.
Are these two equivalent?

No, they are not equivalent.

> If not, I would like to request more documentation on what this variable does.

Sure. In short, bootstrap_count specify the minimum number of trials to proceed one "rung"(this is referred in the original paper of Hyperband) to the next. This argument has been introduced in #1945. Please check it for more details. By the way, your proposal to make the documentation richer is reasonable. Do you have any motivation to contribute after the check of the PR? I'm very glad to get your enthusiasm to Optuna.

> Also, if there is no way to change the number of brackets, I would like to request a fix.

Yes, we can control the number of brackets by specifying max_resource and min_resource. This is originally motivated from the Hyperband paper. In the paper, the number of brackets is determined by those two resources.

**Comment by veritas9872** [comment]
@HideakiImamura Thank you for the explanation. I will look into the original paper and find out more about the algorithm.
