### ISSUE TITLE
CLI option to merge multiple RDBStorages 

### ISSUE THREAD

**Issue by phiresky** [optuna/optuna#2364]
## Motivation

I have multiple studies running on different computers that are not in the same network, and I don't or can't setup a central DB server. 

## Description

A cli option like `optuna merge target.db postgresql://...` would copy all studies and trials from source.db into target.db. This can be used both to migrate a storage as well as to merge data from different storages after the fact.

The main thing architecturally that currently makes this somewhat hard (I think) is that studies and trials don't have globally unique identifiers.

Here's how I think this would go:

0. Verify storage versions are the current for source and target
1. Load all studies and trials from the `source` storage.
2. For every study and trial in source storage without system attribute `guid` generate a random ID using e.g. `uuid.uuid4()`
3. Same for target storage
4. For every study and trial in source storage, check if same GUID already exists in target storage. If not, copy it over.

Studies and trials would get different ids and trial numbers than before, but I don't think it would be an issue?

Ideally, the GUIDs would be generated on study / trial creation, but I'm not sure if you want that. 
This way, it is ensured that trials and studies are not duplicated.

Study names could also kinda be used as a "GUID" but that's somewhat dangerous.

I'll probably need this feature soon anyways so I could probably make a PR. Let me know if you think it would be merged.

## Alternatives (optional)

Set up a central postgresql server beforehand, make sure you always use that. This only covers part of the reason to have this feature and is less flexible.

**Comment by keisuke-umezawa** [comment]
If you have not started to use the target DB, how about migrating data from the source to the taarget by [postgre migration tool](https://www.postgresql.org/docs/9.0/migration.html)?

**Comment by hvy** [comment]
Thanks @phiresky for the report. I encountered a similar situation recently myself and implemented `optuna.copy_study` https://github.com/optuna/optuna/pull/2607 . Does this address your problem? It's currently only available in the `master` branch and will be included in the next release v2.8.0 as an experimental feature.

> Studies and trials would get different ids and trial numbers than before, but I don't think it would be an issue?

This is by design and neither do I think that this is an issue.

> Study names could also kinda be used as a "GUID" but that's somewhat dangerous.

A tuple of study name and storage (URI for RDB storages) acts as a "GUID".

**Comment by phiresky** [comment]
Looks like a good feature to have, but it wouldn't solve my use case completely:

* It looks like your code only works once, if more trials are added later to the same study in the input DB it will fail. So it's more of a "migrate study from A to B" instead of "merge data between A and B". It can't merge two studies representing the same experiment in general, since that would require either an UUID per trial or some inexact heuristic to define equivalence on two trials (e.g. based on the run parameters).
* It only does a single study. What I was thinking about was more "merge all new trials and new studies from db A into db B", in an idempotent way, from the CLI without writing new code.

> A tuple of study name and storage (URI for RDB storages) acts as a "GUID".
I didn't see aynthing in your PR that uses the (uri, studyname) as a key to identify a study? If it were used, the URI of the storage that a study was initially created in would have to be stored in the new DB, otherwise the key is just (studyname). I don't think it would be a great key either since the URI is not immutable (moving the sqlite file, connecting to PG from a different server).

So in general it's good to have a way to copy a study into a different storage (and to know that the logic you implemented works), but it doesn't really solve merging multiple storages.

**Comment by hvy** [comment]
I see, thanks for the additional information. So you mean to actually merge studies (you could merge storages without merging studies, which I what I first thought). Just to clarify, is it the case that you have studies optimized independently but then later want to merge those studies into a new study? I'm not so sure how common of a use case this is and whether we should provide this as a feature (via CLI) so if possible, I'd be great if you could give additional background. As for the implementation, I think it would be possible by creating globally unique identifiers (tuple of storage URI, study name, trial number) and store this information in each trial in B.

**Comment by phiresky** [comment]
The specific use case when I created the issue was that I had a study with experiments that take around 24h and I had some compute resources in a cluster (can't open ports), and some compute resources on 2 random machines. The first ~ 20 runs couldn't use the results from the others anyway since I could run them in parallel on different, isolated machines. So I just ran them with separate SQLite storage backends and thought I could merge the SQLite storages later / manually and have Optuna choose the parameters for the next 20 runs based on those results. 

Later I realized it's not easy to merge optuna storages (needed so the next runs use all the gathered information), and it's not easy to migrate from one engine to another (e.g. to move all the SQLite results into one postgresql database), so I opened the issue. It seemed like a fairly common use case to run some experiments (of the same or of different studies) in an isolated way (can't create / share a DB for some reason and can't share the SQLite database in a read-write manner).

Migrating to a different storage engine and merging separate studies from different storages into one storage can be seen as special cases of a general merge mechanism which is why I mentioned them above - though only merging trials in a study needs GUIDs.

> As for the implementation, I think it would be possible by creating globally unique identifiers (tuple of storage URI, study name, trial number) and store this information in each trial in B

IMO it would be best to just directly generate a random globally unique identifier for each trial when it is created (instead of or in addition to identifying them by (study_name, trial_index)), since that actually stays the same when it's moved around.

**Comment by BabaYara** [comment]
This would really be a great feature to have. I am in a similar situation.
I am running process over different computers that cannot talk to each other. 
It would be great to be able to later merge all the save files and then have all independent process start with the merged data.

**Comment by eugeborzone** [comment]
I create a function that combines 2 sqlite3 optuna dbs:

`import sqlite3
import pandas as pd

def combine_optuna_dbs(db1_path, db2_path):
    """"
    This function combines two optuna databases into the db1. 
    Both dbs should be from the same study.
    The ids of the db2 are updated to be unique.
    """

    # get all the tables names
    with sqlite3.connect(db1_path) as con:
        tables = con.execute("SELECT name FROM sqlite_master WHERE type='table';").fetchall()
        tables = [table[0] for table in tables]
    not_tables = ['studies', 'version_info', 'study_directions', 'alembic_version']
    tables = [table for table in tables if table not in not_tables]

    dfs1 = {}
    with sqlite3.connect(db1_path) as con:
        for table in tables:
            dfs1[table] = pd.read_sql_query(f"SELECT * FROM {table}", con)

    table_ids = {'study_user_attributes' : ['study_user_attribute_id'],
                'study_system_attributes' : ['study_system_attribute_id'],
                'trials' : ['trial_id', 'number'],
                'trial_user_attributes' : ['trial_user_attribute_id'],
                'trial_system_attributes' : ['trial_system_attribute_id'],
                'trial_params' : ['param_id'],
                'trial_values' : ['trial_value_id'],
                'trial_intermediate_values' : ['trial_intermediate_value_id'],
                'trial_heartbeats' : ['trial_heartbeat_id'],
    }

    max_ids = {}
    # add max id if the table is not empty
    for table in tables:
        if len(dfs1[table]) > 0:
            for id in table_ids[table]:
                max_ids[id] = dfs1[table].iloc[-1][id]
        else:
            for id in table_ids[table]:
                max_ids[id] = 0

    dfs2 = {}
    with sqlite3.connect(db2_path) as con:
        for table in tables:
            dfs2[table] = pd.read_sql_query(f"SELECT * FROM {table}", con)

    update_ids = {'study_user_attributes' : ['study_user_attribute_id'],
             'study_system_attributes' : ['study_system_attribute_id'],
            'trials' : ['trial_id', 'number'],
            'trial_user_attributes' : ['trial_user_attribute_id', 'trial_id'],
            'trial_system_attributes' : ['trial_system_attribute_id', 'trial_id'],
            'trial_params' : ['param_id', 'trial_id'],
            'trial_values' : ['trial_value_id', 'trial_id'],
            'trial_intermediate_values' : ['trial_intermediate_value_id', 'trial_id'],
            'trial_heartbeats' : ['trial_heartbeat_id', 'trial_id'],
    }

    # update the ids of the second db
    for table in tables:
        if len(dfs2[table]) > 0:
            for id in update_ids[table]:
                dfs2[table][id] = dfs2[table][id] + max_ids[id]

    # add the second db to the first db
    with sqlite3.connect(db1_path) as con1:
        for table in tables:
            dfs2[table].to_sql(table, con1, if_exists='append', index=False)
`
