### ISSUE TITLE
Trial.suggest_int() with NSGAIISampler exceeds the range which is set using another sampled variable

### ISSUE THREAD

**Issue by kousakuin-A** [optuna/optuna#2371]
When one variable was sampled with the range using another sampled variable, such as `a = trial.suggest_int('a', 0, 100)` and `b = trial.suggest_int('b', 0, 100-a)`, `a + b <= 100` should be True.
However, this constraint happened to be violated when used with `NSGAIISampler`.
I also tried with `RandomSampler` and `TPESampler`, and these samplers seems to obey the constraint.

## Expected behavior

When two variable `a` and `b` was sampled as below:
```python
a = trial.suggest_int('a', 0, 100)
b = trial.suggest_int('b', 0, 100-a)
```
then, `a+b <= 100` should always be True.

## Environment
- Environment 1
  - Optuna version: 2.5.0
  - Python version: 3.7.0
  - OS: Windows 10 Home 1909
  - (Optional) Other libraries and their versions: nupy 1.17.4
- Environment 2
  - Optuna version: 2.5.0
  - Python version: 3.7.3
  - OS: Ubuntu 18.04.3 on WSL1 system on the above environment.
  - (Optional) Other libraries and their versions:  numpy 1.18.1

## Error messages, stack traces, or logs

```
[W 2021-02-22 14:44:46,194] Trial 50 failed because of the following error: AssertionError("param={'a': 64, 'b': 37}, dist={'a': IntUniformDistribution(high=100, low=0, step=1), 'b': IntUniformDistribution(high=36, low=0, step=1)}")
```

## Steps to reproduce
See *Reproducible examples*.
`seed=42` and `n_jobs=1` are set to reproduce the trial number when AssertionError occured.

## Reproducible examples

```python
import optuna


def objective(trial):
    a = trial.suggest_int('a', 0, 100)
    b = trial.suggest_int('b', 0, 100-a)
    assert a+b <= 100, f'param={trial.params}, dist={trial.distributions}'
    return (a-50)**2 + (b-50)**2


# OK
study = optuna.create_study(sampler=optuna.samplers.RandomSampler(seed=42))
study.optimize(objective, n_trials=2000, n_jobs=1)

# OK
study = optuna.create_study(sampler=optuna.samplers.TPESampler(seed=42))
study.optimize(objective, n_trials=200, n_jobs=1)

# Failed at Trial 50
study = optuna.create_study(sampler=optuna.samplers.NSGAIISampler(seed=42))
study.optimize(objective, n_trials=2000, n_jobs=1)
```

## Additional context

I have faced this problem when I was using optuna for optimization of a chemical composition.
Suppose there is a ternary system. The compound was composed of three materials A, B, and C. I'd like to know the optimal composition ratio (wt%) of these materials, `a`, `b`, and `c`, and `a+b+c==100`.
The objective function is a prediction model of the chemical property of the compound from `a`, `b`, and `c`.
So,
```python
def objective(trial):
    a = trial.suggest_int('a', 0, 100)
    b = trial.suggest_int('b', 0, 100-a)
    c = 100 - a - b
    return model.predict([a, b, c])
```
is what I want to do.
At first I faced this problem when I tried multi-objective optimization. `optuna.visualization.plot_pareto_front` is quite useful for that.
Finally I found the problem seems to be related to NSGAIISampler, and the multi-objective optimization is not.

**Comment by nzw0301** [comment]
Note that the reported issue happens when we use other `suggest_*` method with `NSGAIISampler`. For example, `suggest_uniform`.

**Comment by nzw0301** [comment]
@kousakuin-A Did you try to use `constraints_func`?

**Comment by kousakuin-A** [comment]
@nzw0301 Thank you very much for your comment, and I am sorry for my late reply.
I have tried to use `constraints_func` and it seems to work well. (code is shown below)
I confirmed that the suggestion did not fall into constraint-violating samples such as a=b=200. Without `constraints_func`, it goes bad.

Unfortunately, a useful function `optuna.visualization.plot_pareto_front` does not work well as-is.
However it is not so hard to implement a function like get_pareto_front_trials() with filtering inappropriate samples, so it is not a huge problem for me...

```python
import optuna
import matplotlib.pyplot as plt


def objective(trial):
    a = trial.suggest_int('a', 0, 100)
    b = trial.suggest_int('b', 0, 100-a)
    trial.set_user_attr("constraint", [a+b-100])
    #assert a+b <= 100, f'param={trial.params}, dist={trial.distributions}'
    return (a-200)**2 + (b-200)**2


def constraints_func(trial):
    return trial.user_attrs["constraint"]


study = optuna.create_study(sampler=optuna.samplers.NSGAIISampler(
    seed=42, constraints_func=constraints_func))
study.optimize(objective, n_trials=1000, n_jobs=1)

xa, ya = [], []  # violating points
xb, yb = [], []  # feasible points
for t in study.trials:
    if any(constraint > 0 for constraint in t.system_attrs['nsga2:constraints']):
        xa.append(t.number)
        ya.append(t.value)
    else:
        xb.append(t.number)
        yb.append(t.value)
plt.scatter(xa, ya, c='red', s=2)
plt.scatter(xb, yb, c='blue', s=2)
plt.show()
```

**Comment by kousakuin-A** [comment]
Now I understand *crossover* cause a swap of parameter to sample (like `a` or `b`) between parent samples. Thus, the child sample may violate the constraints (like `a+b=100`).

I am wondering why the *mutation* cause the violation when `swapping_prob=0` and/or `crossover_prob=0`. It seems that the mutation simply call `RandomSampler.sample_independent`, and `param_distribution` should be set appropriately...

**Comment by jmrichardson** [comment]
I am seeing this same issue

**Comment by kasparthommen** [comment]
I have the same problem. Here's another pretty minimal example:

```python
import optuna
from optuna import Trial
from optuna.samplers import NSGAIISampler


def objective(trial: Trial) -> float:
    x = trial.suggest_float('x', 0, 5)
    y = trial.suggest_float('y', x, 10)
    assert y >= x, f'Constraint violation: x={x}, y={y}'
    return x - y


study = optuna.create_study(direction='maximize', sampler=NSGAIISampler(seed=42))
study.optimize(objective, n_trials=100)
```

When run with optuna 2.10.0, this produces the following output:

```
...
[I 2021-11-11 07:56:52,662] Trial 59 finished with value: -1.3786423614276657 and parameters: {'x': 1.4487572645688402, 'y': 2.827399625996506}. Best is trial 14 with value: -0.3269146210750704.
[W 2021-11-11 07:56:52,663] Trial 60 failed because of the following error: AssertionError()
Traceback (most recent call last):
  File "C:\Miniconda3\envs\p37\lib\site-packages\optuna\study\_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "<ipython-input-12-6131b75193b2>", line 9, in objective
    assert y >= x, f'Constraint violation: x={x}, y={y}'
AssertionError: Constraint violation: x=4.648488261712865, y=4.224960229024017```

**Comment by kasparthommen** [comment]
@nzw0301 I have tried using `constraints_func` as you had suggested, but that doesn't seem to help, see below:

```python
import optuna
from optuna import Trial
from optuna.samplers import NSGAIISampler


def objective(trial: Trial) -> float:
    x = trial.suggest_float('x', 0, 5)
    y = trial.suggest_float('y', x, 10)  # implies y >= x
    return y - x


study = optuna.create_study(
    direction='minimize',
    sampler=NSGAIISampler(
        seed=42,
        constraints_func=lambda trial: [1 if trial.params['y'] < trial.params['x'] else 0]
    )
)
study.optimize(objective, n_trials=400)
print(study.best_trial)
```

This eventually prints
```
FrozenTrial(number=393, values=[-3.192660428675915], ... params={'x': 4.933197892505877, 'y': 1.7405374638299622}, ...)
```

which is clearly a violation of the `y >= x` condition.

Looks like the only workaround at this moment is to raise `TrialPruned` when the constraint is violated:

```python
import optuna
from optuna import Trial, TrialPruned
from optuna.samplers import NSGAIISampler


def objective(trial: Trial) -> float:
    x = trial.suggest_float('x', 0, 5)
    y = trial.suggest_float('y', x, 10)  # implies y >= x
    if y < x:
        # constraint violated
        raise TrialPruned
    
    return y - x


study = optuna.create_study(direction='minimize', sampler=NSGAIISampler(seed=42))
study.optimize(objective, n_trials=400)
print(study.best_trial)
```

This will lead to valid solutions but is not very elegant.

**Comment by kasparthommen** [comment]
Is anyone looking into this? This is a major bug that completely obliterates the dynamic search space feature IMHO.

**Comment by nzw0301** [comment]
When I ran the first code in https://github.com/optuna/optuna/issues/2371#issuecomment-966178582 with the latest Optuna (https://github.com/optuna/optuna/commit/0a63f6209782f3e1ee6b998fcd5887703df030b5), 
the best trial was 

```python
FrozenTrial(
    number=102,
    values=[0.06408371934872914], 
    datetime_start=datetime.datetime(2022, 3, 8, 17, 56, 7, 748629),
    datetime_complete=datetime.datetime(2022, 3, 8, 17, 56, 7, 748949),
    params={'x': 3.0321452982979498, 'y': 3.096229017646679},
    distributions={'x': UniformDistribution(high=5.0, low=0.0), 'y': UniformDistribution(high=10.0, low=3.0321452982979498)}, user_attrs={}, system_attrs={'nsga2:generation': 2, 'nsga2:constraints': (0,)}, intermediate_values={}, trial_id=102, state=TrialState.COMPLETE, value=None)
```

The solution does not violate the constraint.

Is this problem?

**Comment by kasparthommen** [comment]
@nzw0301 I have just run it with the latest version as well. You are right, the bug has indeed been fixed! Feel free to close the issue.

**Comment by nzw0301** [comment]
Awesome. Thank you for varifying it!
