### ISSUE TITLE
Favoring stable parameters (sensitivity analysis)

### ISSUE THREAD

**Issue by brunofacca** [optuna/optuna#2374]
Hello,

I've been looking into a couple of sensitivity analysis libraries and I'm wondering if Optuna provides any way of favoring regions of the parameter space that produce more stable results. For simplicity's sake, imagine that we're optimizing a single hyperparameter of an ML model. In the following plot, the x axis is the value of the parameter and the y axis is the objective  (higher is better).

![param optimization](https://user-images.githubusercontent.com/13872579/108740768-c92e9100-7514-11eb-9999-4bfef03d40b3.png)

If we look at the score of each trial individually, we'll choose the parameter value near 170. However, the results deteriorate very rapidly with only a small change in that parameter (the peak in the chart is surrounded by valleys). That may indicate that the high score was a statistical fluke or at least that it's not very robust/stable. It would probably be better to select a value around 60, whose results are more stable. Does Optuna support that?

**Comment by toshihikoyanase** [comment]
Hello @brunofacca 
Thank you for your question. Optuna has visualization functions, and I think we can create a similar plot to yours using [plot_slice](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_slice.html#optuna.visualization.plot_slice).

**Comment by brunofacca** [comment]
That's a very interesting plot, @toshihikoyanase. Thank you for letting me know about it. 

I've used an example of optimizing a single parameter to make it easier to explain and to plot. In practice, I'm optimizing 12+ parameters together. I could plot each of them individually and manually choose the most stable value for each. However, the ideal scenario would be for Optuna to take such stability into account when optimizing (multiple parameters together), in order to find the combination of parameters with the highest stability/robustness. 

That could be highly beneficial, especially for datasets with a high signal-to-noise ratio. If such a feature is not currently available, please allow me to suggest it as a possibility for future implementation. Unfortunately, I don't have enough domain knowledge to create a PR.

**Comment by toshihikoyanase** [comment]
> I'm optimizing 12+ parameters together.

Ah, in that case, `plot_slice` will create `n_params` plots without considering the correlation between the parameters, and it may be difficult for us to choose the stable parameters based on them.

> That could be highly beneficial, especially for datasets with a high signal-to-noise ratio. If such a feature is not currently available, please allow me to suggest it as a possibility for future implementation.

Currently, Optuna does not have such a feature to help users find stable solutions, but I agree with you. Could you give us links to the papers / software related to sensitivity analysis if you have?

**Comment by brunofacca** [comment]
Hello @toshihikoyanase. Sorry for the delayed reply.

* [SALib](https://github.com/SALib/SALib) is the most popular sensitivity analysis library (that I'm aware of) in Python. The "Methods included" section of their GitHub repo readme links to the various papers whose methods are implemented in the library.
* [uncertainpy](https://github.com/simetenn/uncertainpy) also looks interesting to me. It's focused on neuroscience but it may provide some useful insights into sensitivity analysis. The coffee cup cooling example plot in the readme, for example, may be interesting to look at.
* The [savvy](https://github.com/houghb/savvy) library, which seems to no longer be maintained, contains some ways to plot the sensitivity of the parameters.

One simple way of measuring the sensitivity of a parameter is, once you find a potential optimal value, also test the adjacent values (e.g., increment or decrement the value in steps of 5% or 10%), then calculate the standard deviation of the objective function's output for all those values. The lowest the standard deviation, the more stable the parameter is. 

A possible way to compare different values for a parameter may be to divide the contribution of the optimal value of that parameter to the improvement in the objective function by the standard deviation of the contributions of the adjacent values. Those are just random ideas, not based on any specific papers that I'm aware of.

Thank you.

**Comment by brunofacca** [comment]
Hello. I've found a couple of interesting papers on the subject:

* https://www.mitpressjournals.org/doi/pdf/10.1162/evco.2006.14.4.463
* https://riuma.uma.es/xmlui/bitstream/handle/10630/15353/TD_BERUTICH_%20LINDQUIST_Jose_Manuel.pdf?sequence=1&isAllowed=y: This one is about optimization of trading strategies but a lot of its contents discuss optimization in general.
