### ISSUE TITLE
Support botorch v0.4.0

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#2381]
The arguments of [`NondominatedPartitioning`](https://botorch.org/api/utils.html?highlight=nondominatedpartitioning#botorch.utils.multi_objective.box_decompositions.non_dominated.NondominatedPartitioning) seems to have been changed during the transition to v0.4.0, leading to a failure of Optuna's integration test and version constraint (#2379)

**Comment by nzw0301** [comment]
Like this?

Replace these lines

https://github.com/optuna/optuna/blob/202b9b81c254a776b5ebcf65cff3e631104fc1d7/optuna/integration/botorch.py#L203-L208

with 
```python
    ref_point = train_obj.min(dim=0).values - 1e-8
    ref_point_list = ref_point.tolist()

    partitioning = NondominatedPartitioning(
        ref_point=torch.tensor(ref_point_list), Y=train_obj_feas, alpha=alpha
    )
```

**Comment by crcrpar** [comment]
I'm not familiar with BoTorch things at all, but `ref_point` shouldn't be Tensor?

**Comment by nzw0301** [comment]
Oops, indeed. It's my fault.
