### ISSUE TITLE
Use `study.get_trials` with states instead of naive filtering

### ISSUE THREAD

**Issue by not522** [optuna/optuna#2384]
## Motivation
In many examples, `pruned_trials` and `complete_trials` are obtained by filtering `study.trials`. `study.get_trials` with `states` argument introduced by #1943 will simplify the implementation.
https://github.com/optuna/optuna/blob/b6de94d1f3042b43d5a1cb5b729795d74cebb026/examples/pytorch/pytorch_simple.py#L128-L129

**Comment by jeromepatel** [comment]
I am interested in working on this issue. Can you guide me on this and how many examples (files) are needed to be changed?

**Comment by not522** [comment]
Thank you! Following examples have stale implementations. 
- `examples/simple_pruning.py`
- `examples/chainer/chainer_integration.py`
- `examples/chainer/chainermn_integration.py`
- `examples/keras/keras_integration.py`
- `examples/mxnet/mxnet_integration.py`
- `examples/pytorch/pytorch_distributed_simple.py`
- `examples/pytorch/pytorch_simple.py`
- `examples/samplers/simulated_annealing_sampler.py`
- `examples/tensorflow/tensorflow_estimator_integration.py`
- `examples/tfkeras/tfkeras_integration.py`

**Comment by jeromepatel** [comment]
Okay, I'll start working on it, and once completed, submit a PR for the same.

**Comment by not522** [comment]
This issue is resolved by #2393.
