### ISSUE TITLE
Adding a new parameter to `TPESampler`

### ISSUE THREAD

**Issue by jeromepatel** [optuna/optuna#2385]
## Motivation

Currently, there is no argument to pass <code>independent_sampler</code> in <code>TPESampler</code> but in the future, it may be useful to users and may provide flexibility if we can add something as an argument to it like other samplers. 

## Description

In current implementation, There is a variable <code>random_sampler</code> there in <code>TPESampler</code>, whose <code>after_trial</code> method is called when a fallback occurs. Other samplers use <code>independent_sampler</code> by default initialized with <code>RandomSampler</code>, so in both the cases the performance is same if no argument is passed. However, if we include <code>independent_sampler</code> in <code>TPESampler</code> there will be flexibility when a new sampler can be used in place of <code>RandomSampler</code> (such as Sobol, issue #1797 ).

## Additional context (optional)

This is discussion of <code>independent_sampler</code> in continuation of PR #2376. Let me know your views on this!

**Comment by jeromepatel** [comment]
I want to point out that currently, <code>NSAGAIISampler</code> and <code>MOTPESampler</code> don't have <code>independent_sampler</code> either, so we can consider them also (just for a reference of upgrade)

**Comment by HideakiImamura** [comment]
TPE supports independent sampling by default. So, it is inappropriate to add `independent_sampler` to `TPESampler`.

By the way, if the number of previous trials is smaller than `n_startup_trials`, the `RandomSampler` is used in `TPESampler`. I think it would be natural to allow this `RandomSampler` to be changed to any other sampler. For example, if `SobolSampler` or `LatinHypercubeSampler` are supported in the future, there is a good chance that we will want to replace it with something like that.

**Comment by HideakiImamura** [comment]
I'd like to discuss the name of the argument to be added. `independent_sampler` is inappropriate as I said. How about `init_sampler`? Do you have any opinions?

**Comment by jeromepatel** [comment]
@HideakiImamura Thank you for your suggestion. I agree with you on the point that <code>TPESampler</code> doesn't look appropriate with an argument named <code>independent_sampler</code> as it already supports it by default. As the proposal for a new sampler could improve flexibility (for eg. <code>SobolSampler</code> and others), the name <code>init_sampler</code> sounds perfect to me. I would like to know others views on this.
