### ISSUE TITLE
Sample a batch of params, evaluate objective function offline, and provide objective function results to BO study explicitly.

### ISSUE THREAD

**Issue by juliuskittler** [optuna/optuna#2387]
## Motivation

First of all, a huge "Thank You" for this package; Optuna has become my favourite package for hyperparameter tuning with Bayesian Optimization (BO). 

It seems to me that with a few tweaks, Optuna could become very successful even beyond hyperparameter tuning. In domains such as R&D, we also sometimes optimize a complex objective function that takes very long to evaluate. Evaluating the objective function in such a setting actually involves manual work (setting up experiments, taking measurements etc.). With that in mind, it is generally not feasible/efficient to evaluate a single 1 set of parameters at a time. Instead, batches of trials are conducted (say 10 trials in every batch). 

_This means that:_ 

1. We need to (up-front) sample and make available a **batch** of `k` parameter sets, i.e. the `k` parameter sets to be evaluated next.
2. We need a way to pass the corresponding `k` results of the objective function to the BO study directly/manually (since the objective function is not a Python function that can be evaluated but a function that exists in the real world, i.e. people running an experiment).

## Description

In pseudo code, I imagine a solution that could look as below:

```
# 1. Create a study and directly provide the `sample_fun` function, which samples the parameters as usual.
study = optuna.create_study(sample_fun = sample_fun, **sample_fun_kwargs)

# 2. Sample a batch of 10 parameter sets, resulting in a list of dicts
param_list = study.sample_params(n = 10)

# 3. Now, we go and evaluate these 10 parameter sets by running manual experiments in the real world.
# After a day has passed, we obtain the results of the objective function from a scientist:
result_list = [0.1, 0.4, 0.2, 0.4, 0.3, 0.1, 0.04, 0.1, 0.5, 0.6] 

# 4. Finally, we update the study; so that the surrogate function learns from the results
study.update(param_list, result_list)

# ... We repeat the steps 2-4 until the results are sufficient.

```

Thank you so much in advance - I am very much looking forward to your response.

**Comment by not522** [comment]
Thank you for your feedback! I think the [ask-and-tell](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.ask)  interface will help with your case. The following code is an example of how to use the ask-and-tell interface for batch optimization.

```python
import optuna

n_batch = 10
batch_size = 10

study = optuna.create_study()
for i in range(n_batch):
    trial_list = [study.ask() for _ in range(batch_size)]

    # Change here for your optimization.
    value_list = [trial.suggest_float("x", -1, 1) ** 2 for trial in trial_list]

    for trial, value in zip(trial_list, value_list):
        study.tell(trial, value)
```

**Comment by juliuskittler** [comment]
@not522 thanks a lot, that is very helpful!

**Comment by not522** [comment]
OK! Let me close this.
