### ISSUE TITLE
AttributeError: 'function' object has no attribute 'zero_grad' 

### ISSUE THREAD

**Issue by aimanmutasem** [optuna/optuna#2388]
## Note to the questioner

Hello all :) 

I'm excited to use `optuna` in my NMT project, especially to optimize only the learning rate following an example in GitHub as : 

```
def objective(trial):
 
    model = define_model(trial).to(DEVICE)
    optimizer_name = trial.suggest_categorical("optimizer", ["Adam", "RMSprop", "SGD"])
    lr = trial.suggest_float("lr", 1e-5, 1e-1, log=True)
    optimizer = getattr(optim, optimizer_name)(transformer.parameters(), lr=lr)
    
    return optimizer

optimizer = objective
```
Unfortunately, I got an error during the implementation: 

```
<ipython-input-23-109244610126> in train_step(self, loader, epoch, grad_clip)
     12         for i, batch in progress_bar:
     13             src, trg = batch.src, batch.trg
---> 14             self.optimizer.zero_grad()
     15             logits, _ = self.model(src, trg[:, :-1]) # [batch_size, dest_len, vocab_size]
     16             loss = self.criterion(logits.contiguous().view(-1, self.model.decoder.vocab_size), trg[:, 1:].contiguous().view(-1))

AttributeError: 'function' object has no attribute 'zero_grad' 
```

Could you help? 

Kind regards,
Aiman Solyman

**Comment by toshihikoyanase** [comment]
Hello @aimanmutasem 

Thank you for using Optuna. I guess you need to evaluate the `objective` function to get the `optimizer` instance.
As you may not use `Study.optimize`, you can evaluate the `objective` as follows: 

```python
study = optuna.create_study()
for i in range(N_TRIAL):
    trial = study.ask()
    optimizer = objective(trial)
     ...
     for i, batch in progress_bar:
          ...
          loss = self.criterion(logits.contiguous().view(-1, self.model.decoder.vocab_size), trg[:, 1:].contiguous().view(-1))
     study.tell(trial, loss)
```
(See also https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.ask)

**Comment by aimanmutasem** [comment]
Thank you sir, I'm a beginner with `Optuna` and it is my fault I don't study the basics well.

There are good examples of using `Optuna` with image processing tasks like [1](https://github.com/shaktiwadekar9/Optuna_PyTorch_Hyperparameter_Searchl) and [2](https://towardsdatascience.com/https-medium-com-perlitz-hyper-parameter-optimization-with-optuna-1c32785e7df). 

In my [project](https://github.com/aimanmutasem/Arabic-GEC-project/blob/main/Optuna/Arabic%20grammar%20error%20correction%20-%20example.ipynb), I'm trying to use `Optuna` with multi-head attention for NMT or grammar correction. Unfortunately, I don't find any examples of NMT or transformer using `Optuna`. 

Could you give me a small example based on multi-head attention to working on?
