### ISSUE TITLE
Optuna TPE optimizer with multivariate=True returns incorrect range of numbers for suggest_int after some trials

### ISSUE THREAD

**Issue by casparvl** [optuna/optuna#2391]
When using a TPE sample with `multivariate=True` (i.e. `optuna.samplers.TPESampler(multivariate=True)`), the `suggest_int` function starts to return integers that are not within the specified range after a certain number of trials. 

For example, I've specified `my_int = trial.suggest_int('my_int', 1, 9, 2)`, thus expected trials to select `my_int` from the range `1, 3, 5, 7, 9`. However, after ~15-25 trials, the sampler starts generating even numbers (`2, 4, 6, 8`) and stops generating `3, 5, 7` (it still generates 1's and 9's).

The exact number of trials after which this behaviour is show varies, probably because this behaviour is related to the underlying model that is estimated by the sampler (and which is different every run since my objective function is not deterministic between runs).

## Expected behavior

I expect that `my_int = trial.suggest_int('my_int', 1, 9, 2)` only generates numbers from the range `1, 3, 5, 7, 9`. While I understand that the sampler will estimate an underlying model, I dont think it should under any circumstance generate a number that is not allowed by my prespecified `low`, `high` and `step`.

## Environment

- Optuna version: 2.3.0
- Python version: 3.6.6
- OS: Debian 10
- (Optional) Other libraries and their versions: N/A

## Error messages, stack traces, or logs

N/A
# error messages, stack traces, or logs
N/A

## Steps to reproduce
See below

## Reproducible examples (optional)

This small reproducer gives me even numbers after ~15-25 trials:

```python
import random as rand
import optuna

study_name='multivariate'
current_sampler = optuna.samplers.TPESampler(multivariate=True)
current_pruner = optuna.pruners.SuccessiveHalvingPruner()
study = optuna.create_study(direction = "minimize", study_name = study_name, 
                pruner = current_pruner, sampler = current_sampler
            )

def optuna_objective(trial):
    my_int = trial.suggest_int('my_int', 1, 9, 2)
    return rand.random()

study.optimize(optuna_objective, n_trials = 100)
```

**Comment by not522** [comment]
This issue is resolved by #2392.
