### ISSUE TITLE
Don't use `numpy.append`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#2396]
In some parts of Optuna, `numpy.append` is used. However, dynamically changing `numpy.ndarray` is slow, so for performance, it is better to append as a list first, and then cast with `numpy.asarray`. We are looking for someone to list and fix the parts where `numpy.append` is used.

**Comment by hvy** [comment]
I suppose you're referring to code that repeatedly calls `numpy.append` inside a loop. Allocating new arrays in each iteration is inefficient and I agree that such code can be optimized. Just leaving a note that this can be done in different ways. For instance, if you know the loop size, you could perform a single allocation prior to the loop.

**Comment by jeromepatel** [comment]
I would like to work on this issue if you can guide me on this, it would be helpful.

**Comment by nzw0301** [comment]
@HideakiImamura I think that this issue can be closed.

@jeromepatel Please do not worry that your kindful proposal was not accepted 😢

**Comment by jeromepatel** [comment]
@nzw0301 I am happy with the progress and contribution I am making to this organization. So, thank you for all your support and guidance.

**Comment by nzw0301** [comment]
Let me close this issue since the related pull request #2419 has been merged. Please feel free to re-open this issue if this issue has not been resolved yet.
