### ISSUE TITLE
Add more visualization features for multi-objective optimization (e.g., constraint handling, animation)

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#2397]
## Motivation

When I used multi-objective optimization, I wanted new features of `plot_pareto_front`. I'm not fully sure if they are useful for the other people, but let me share the ideas.

### [DONE] 1. Constraint-aware pareto-front plot

Recently, Optuna enables us to add constraints to multi-objective optimization. The `plot_paret_front` function, however, does not consider whether the solution is feasible or not. So, I needed to modify it to visualize the constraint optimization.

For example, the following plot is an example of multi-objective knapsack problem. The objectives are to be maximized, but infeasible solutions are likely to be seen in the up-right region. In this case, I couldn't find the shape of Pareto front without removing the infeasible solutions.

![0199](https://user-images.githubusercontent.com/3255979/109284470-3cad0700-7863-11eb-82bc-63e48a530205.png)

### [REJECTED] 2. Animation of evolution

Since the NSGA-II is an evolution-based algorithm, we can traverse parents/ancestors of solutions. When I used the NSGA-II Sampler, I visualized the evolution of solutions using the animation and checked if the genetic operators produced good solutions. I think it is useful if we provide a new visualization feature that shows pareto-front trial by trial including the parents of the newly added point.

The following plots are snapshots of the animation.
![0021](https://user-images.githubusercontent.com/3255979/109287226-ab3f9400-7866-11eb-910d-c8c7cd77792f.png)
![0022](https://user-images.githubusercontent.com/3255979/109287235-ada1ee00-7866-11eb-9e07-8905978c9a23.png)
...
![0196](https://user-images.githubusercontent.com/3255979/109287383-d4602480-7866-11eb-864d-86da6f0a94b4.png)

## Description

We may not necessarily implement both features. I think the first one is relatively well-defined.

### [DONE] 1. Constraint-aware pareto-front plot

We can add a new argument to `plot_pareto_front`.  I think the design discussion is needed about the way to pass the thresholds and constraint values. Currently, both `BoTorchSampler` and `NSGAIISampler` employ the following settings, but we don't decide it should be kept by upcoming samplers for constraint optimization.

- Threshold is always zero.
- The constraint values are stored in Trial's system_attr.

### [REJECTED] 2. Animation of evolution

I drew the example plots for each trial, but it may be verbose to call the visualization function by the number of trials. So, I think we can use the [plotly's animation functionality](https://plotly.com/python/animations/) to visualize the evolution interactively.
We may need to start with some prototypical implementation.

**Comment by HideakiImamura** [comment]
The constraint aware pareto front plot was introduced. The animation is the out of scope of Optuna V3. Let me remove the v3 label.
