### ISSUE TITLE
Explain the backend of `optimize` with  `n_jobs != 1`

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2424]
Let me write a note related to the discussion of the behaviours of optuna's `n_jobs=-1` at the last dev-sprint.

Optuna's `optimize` with `n_job=-1` or `n_job>1` sometimes confuses the users because it is multi-threading. However, users from the machine learning community are familiar `n_jobs=-1`  in sklearn's usage; sklearn's `n_jobs` uses multi-processing for parallelization. As a result, optuna's `n_jobs=-1` does not make some sort of optimization problems faster like sklearn's one.

It would be great to explain the backend and when it can accelerate the optimization at least in the document.

**Comment by kmedved** [comment]
Agreed. I spent a long time playing with Optuna trying to understand this behavior before figuring this out. It's very counterintuitive given the rest of the python ecosystem right now.

**Comment by crcrpar** [comment]
That's super great if the documentation explains what's going on when `n_jobs=-1`.
