### ISSUE TITLE
How to get the best parameters and values of multi objective study?

### ISSUE THREAD

**Issue by zhuo931077127** [optuna/optuna#2426]
```
study = optuna.create_study(directions=('maximize', 'maximize'),
                                storage= 'sqlite:///' + db_file,
                                study_name=args.study_path,
                                load_if_exists=True)
study.optimize(objective, n_trials=args.trials, n_jobs=args.n_cores)

print(f"Best parameters: {study.best_params}")
print(f"Best values: {study.best_value}")
```

And I get the following error:
RuntimeError: The best trial of a `study` is only supported for single-objective optimization.  

How to get the best params and values of multi-objective optimization? Thanks

**Comment by y0z** [comment]
Hi.

You can use `best_trials` instead.
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.best_trials
