### ISSUE TITLE
trial.sample_distribution

### ISSUE THREAD

**Issue by turian** [optuna/optuna#2451]
There should be a `trial.sample_distribution(nsteps=1000)` method which returns a probability distribution, in range [0, 1] with nsteps steps
 
## Motivation

It would be nice to learn whether a distribution should be linear or exponential (with a particular exponent) or gaussian or whatever.

We have a target dataset. We have a method that creates a new dataset. We want our new dataset to have low [Maximum Mean Distance](https://stats.stackexchange.com/questions/510793/sets-clustering/511130#511130) from the target data set.

A very specific example is this:
* We have a target dataset of n synthesized audio sounds.
* We have a synthesizer that has k parameters. We want to sample the k parameter values in such a way that if we synthesize n' audio sounds, they are very similar to the target dataset (and doesn't oversample a particular subspace).

Hence, we have several parameters that we would like to do trial.sample_distribution() from which to pick weighted random samples.

## Description

`trial.sample_distribution(nsteps=1000)` returns a weighted probability distribution with 1000 values.

## Alternatives (optional)

Have several possible parameterizations of the distribution, have optuna pick one, and then have optuna pick the hyperparams of the distribution (e.g. mean and variance).

## Additional context (optional)

See use-case above and related statsoverflow link

**Comment by turian** [comment]
Another use case: You want to sample points with maximal diversity. However, distance of the parameters is not correlated with actual instance distance. Thus, you want the parameter distribution to be optuna'ed

**Comment by turian** [comment]
Any thoughts on this? I have another project now where I would like this functionality

**Comment by not522** [comment]
Let me confirm what you want.
For example,
`p = trial.sample_distribution(nsteps=1000)`
in this case,  `p` should be a list of 1000 floats (or `np.ndarray`) and the sum of `p` is 1, is it correct?

I think that this issue is related to [the FAQ for suggesting a proportion](https://optuna.readthedocs.io/en/stable/faq.html#how-do-i-suggest-variables-which-represent-the-proportion-that-is-are-in-accordance-with-dirichlet-distribution). But it should be more difficult because of the large `nsteps`. Do you have any idea to limit the distribution?

**Comment by turian** [comment]
@not522 I've been thinking about this more recently, and actually the parameterized distributions approach seems good.

How this would work would be there would be a `sample_continuous_distribution(min: Optional[float], max: Optional[float])` method specifying optional min and max extrema for the distribution.

Under the hood, this would call `suggest_categorical` on all or many commonplace `scipy.stats` distributions, and would pick parameters (e.g. mean and std for normal distribution).

Then, you would have a [scipy.stats.rv_continuous](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.rv_continuous.html) object and all its methods, which you could use for computing whatever objective function you like.
