### ISSUE TITLE
Bump PyTorch version to 1.8

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#2454]
We've seen MNIST download failure recently: #2438 #2453 

Once the next AllenNLP comes out, we can update PyTorch version and remove the patches introduced by the two pull requests mentioned above.

**Comment by hvy** [comment]
For the record, we've now bumped `torch` to 1.8.0 for everything besides AllenNLP. Let's keep an eye out for AllenNLP's next release when we could clean up some of the mess introduced by #2442 . Let me leave this issue open until then.

**Comment by crcrpar** [comment]
#2442 and https://github.com/optuna/optuna/pull/2528 got landed, let me close this.
