### ISSUE TITLE
Sort categorical values including numbers in `plot_parallel_coordinate`

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2455]
## Motivation

When the categorical values contain only numerical values such as int or float values, it would be great that the axis of `plot_parallel_coordinate` is sorted. (see also the example and plots below.)

I guess current both implementations don't sort the suggested values.

## Description

Treat the values as numerical and sort them.

## Additional context (optional)

```python
import optuna


def objective(trial):
    x = trial.suggest_uniform("x", -100, 100)
    y = trial.suggest_categorical("y", list(range(-1, 7)))
    return x ** 2 + y


sampler = optuna.samplers.TPESampler(seed=10)
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=10)

optuna.visualization.plot_parallel_coordinate(study)
optuna.visualization.matplotlib.plot_parallel_coordinate(study)
```

The following both plots do not sort y-axis

## Plotly
![newplot (3)](https://user-images.githubusercontent.com/7121753/110315896-41d13980-804d-11eb-8d37-56b55986e92d.png)

## Matplotlib
![download (2)](https://user-images.githubusercontent.com/7121753/110315904-44cc2a00-804d-11eb-918c-1b06ca981a1c.png)

---

## Dependencies

- optuna: 2.6.0
- plotly: 4.14.3
- matplotlib 3.3.4

**Comment by TakuyaInoue-github** [comment]
I tackled this issue(but I have to implement test.) I hope you will check out this PR and give me comments for fixes.
