### ISSUE TITLE
New CatBoost integration - add CatBoostPruningCallback

### ISSUE THREAD

**Issue by pplonski** [optuna/optuna#2464]
I'm working on the integration of Optuna in my AutoML framework: [MLJAR](https://github.com/mljar/mljar-supervised). In the MLJAR AutoML, there are available many different algorithms, among them, there are Xgboost, LightGBM, CatBoost. There is a lack of CatBoost pruning callback. From experimenting with Xgboost and LightGBM I see a huge improvement when pruning callback is used. 

Do you have plans to add a pruning callback for CatBoost?

Would you be interested in PR?

BTW, I get really nice results with Optuna+MLJAR, thank you for your work!

**Comment by nzw0301** [comment]
Hi @pplonski, I think catboost doesn't have any callback function like other boosting libraries; it sounds impossible to implement a pruning callback. Do you know something like a callback in cat boost?


By the way, your project looks really cool!

**Comment by pplonski** [comment]
@nzw0301 thank you! 

You are right. The callbacks will be added in CatBoost in about 2 months.

**Comment by nzw0301** [comment]
Awesome 👍 Thank you for sharing the information and creating the issue at catboost repo.

**Comment by nzw0301** [comment]
According to [the release note of v0.26](https://github.com/catboost/catboost/releases/tag/v0.26), catboost introduces callback functionality!
