### ISSUE TITLE
Should we use FashionMNIST instead of MNIST?

### ISSUE THREAD

**Issue by crcrpar** [optuna/optuna#2469]
We've seen a bunch of errors related to MNIST dataset (403/503).

#2438 #2453 #2459 were made to avoid 403 but failed to avoid 503.
#2468 is a promising way to tackle this problem.

**Comment by crcrpar** [comment]
Either #2504 or #2505 will suffice.

**Comment by HideakiImamura** [comment]
We found a similar MNIST download error in https://github.com/optuna/optuna/pull/2472. I created the issue https://github.com/optuna/optuna/issues/2513. (The error code is 522, neither 403 nor 503).

**Comment by crcrpar** [comment]
Both #2472 and #2513 landed, let me close this issue.
