### ISSUE TITLE
Does it make sence to use pruner with TPE sampler?

### ISSUE THREAD

**Issue by mikkellars** [optuna/optuna#2481]
Hey all.
My question is about whether is makes sense to use a TPE with Successive Halving Pruner or generally combining TPE with a pruner.

I am currently optimizing a resnet18 for a classification problem and optuna successfully finds good parameters while also pruning. For the sampler i am using TPE and for the pruner i am using Successive Halving Pruner. 

As i understand the successive halving pruner look at top k scores after some steps/epochs and then throw away the trials which does not achieve high enough score. This means the trials are evaluated simultaneously.
I understand this makes sense when the sampled parameters stays the same for each trial (e.g. pre-sampled for each trial random), but as far as i understand the TPE samples new parameters. What happens then? Do the epochs and networks reset and reevaluated from the start?

Have i misunderstood some theory about TPE or successive halving pruner or have i overlooked some smart way to combine the two algorithms?

**Comment by Crissman** [comment]
Hi @mikkellars . When TPE is samping, it reviews all completed trials, including the pruned ones, to look for promising areas to try, so the pruned history is not reset.

Does that answer your question?

**Comment by mikkellars** [comment]
Yeah just what i was looking for. Thank you.
