### ISSUE TITLE
How to convert study.pkl to study.db?

### ISSUE THREAD

**Issue by yywangvr** [optuna/optuna#2482]
## Note to the questioner

1.As a new user of Optuna, I really love it. However, in the beginning I saved an existing study to .pkl file, but now I wish to convert it to RDB backend in order to perform the [parallelization](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html) . How can I have that? 

I may wish something like
```python
existing_study=joblib.load("existing_study.pkl")

#save it to .db file
existing_study.save( 'sql_base.db')
```
Is there any solution?

2. In addition, how can I list all study names which have been saved in .db file? Sorry, I do not have so much knowledge in RDB also...

Thank you in advance.

**Comment by nzw0301** [comment]
I think the following way should work.

Let's assume that we have finished a few trials and saved the study as `existing_study.pkl`.

```python
import optuna
import joblib


def objective(trial):
    x = trial.suggest_float("x", -1, 1)
    return x ** 2

study = optuna.create_study()
study.optimize(objective, n_trials=3)

joblib.dump(study, "existing_study.pkl")
```

Then we load the `existing_study.pkl` and save the study into a database, `example.db`. I think that can be done by using `create_new_study` and `create_new_trial`.

```python
import optuna
import joblib


study = joblib.load("existing_study.pkl")

storage = optuna.storages.RDBStorage(
    url="sqlite:///example.db"
)
study_id = storage.create_new_study(study_name="study_on_db")

for trial in study.get_trials():
    storage.create_new_trial(study_id=study_id, template_trial=trial)

study = optuna.load_study(study_name="study_on_db", storage=storage)

study.optimize(objective, n_trials=10)

len(study.get_trials())  # == 13
```

**Comment by yywangvr** [comment]
@nzw0301  Thank you very much. I am personally still have another question, I do not understand why do Optuna remove the multi-objective optimization in the package?  Is there any reasons for that? 

```bash
miniconda3/envs/py38/lib/python3.7/site-packages/optuna/multi_objective/study.py:133: FutureWarning: MultiObjectiveStudy has been deprecated in v2.4.0. This feature will be removed in v4.0.0.
  return MultiObjectiveStudy(study)
```
As I am currently working on a multi-objective optimization problem, I do not know if I still can use the following optimiser :
```python
optuna.multi_objective.samplers.NSGAIIMultiObjectiveSampler()
```


Thank you again and you work are valued to everyone in this community!

**Comment by nzw0301** [comment]
@yywangvr I'm glad to hear that!

## answer to the additional question

Yes, you can use multi-objective optimisation in optuna.

This is because the samplers and study support multi-objective with a unified interface of single objective optimisation. Intead of `optuna.multi_objective.samplers.NSGAIIMultiObjectiveSampler` and `optuna.multi_objective.study.create_study`, we can use `optuna.samplers.NSGAIISampler` and `optuna.study.create_study` for multi-objective, respectively.

### Example 

I suppose that we have the following multi-objective code

```python
import optuna

def objective(trial):
    x = trial.suggest_float("x", 0, 5)
    y = trial.suggest_float("y", 0, 3)

    v0 = 4 * x ** 2 + 4 * y ** 2
    v1 = (x - 5) ** 2 + (y - 5) ** 2
    return v0, v1

sampler = optuna.multi_objective.samplers.NSGAIIMultiObjectiveSampler(seed=1)
study = optuna.multi_objective.create_study(["minimize", "minimize"], sampler=sampler)
study.optimize(objective, n_trials=3)
```

The following code is equivalent to the previous one:

```python
sampler = optuna.samplers.NSGAIISampler(seed=1)
study = optuna.study.create_study(directions=["minimize", "minimize"], sampler=sampler)
study.optimize(objective, n_trials=3)
```

This interface is available since [`optuna>=2.4.0`](https://github.com/optuna/optuna/releases/tag/v2.4.0).

**Comment by yywangvr** [comment]
Dear @nzw0301, thanks for reporting the new interface for me. However, after updating, I still get the following warning:

```bash
/home/wang/miniconda3/envs/py38/lib/python3.7/site-packages/optuna/multi_objective/study.py:443: FutureWarning: FrozenMultiObjectiveTrial has been deprecated in v2.4.0. This feature will be removed in v4.0.0.
  for t in self._study.get_trials(deepcopy=deepcopy, states=states)
```

I guess that Optuna is not going to support the multi-objective optimisation, which is not related to the sampler types...Otherwise, the warnings here is confusing..

Thank you

**Comment by nzw0301** [comment]
I suppose that `study` is created by `optuna.multi_objective.create_study(directions=["minimize", "minimize"], sampler=sampler)` method according to the warning message.   But if `study` was instantiated by using `optuna.study.create_study(directions=["minimize", "minimize"], sampler=sampler)` method that supports multi-objective, the warning message won't appear.

**Comment by nzw0301** [comment]
@yywangvr 

I suppose that study is created by optuna.multi_objective.create_study(directions=["minimize", "minimize"], sampler=sampler) method according to the warning message. But if study was instantiated by using optuna.study.create_study(directions=["minimize", "minimize"], sampler=sampler) method that supports multi-objective, the warning message will disappear.

**Comment by yywangvr** [comment]
I am very grateful for your help. Thank you again.

**Comment by nzw0301** [comment]
@yywangvr Awesome! Thank you for creating issue. The warning message looks unclear for me. This issue is helpful to know that.

**Comment by yywangvr** [comment]
I am sorry to bother you again.

##
I finished the multi-objective optimisation (I have six objectives) , but the outputs from .trials_dataframe() seem strange. 

```python
loaded_study = optuna.load_study(study_name=study_name, storage=storage)
study_results = loaded_study.trials_dataframe()
study_results.to_csv('pid_Optuna.xlsx', index=False
```

After opening the saved file, I found the column `value` keeping zero and I also did not find the `intermediate_values` of each trial. [pid_Optuna.xlsx](https://github.com/optuna/optuna/files/6156771/pid_Optuna.xlsx)
 
I suppose the column should be a stack of something ( like print(loaded_study.best_trial) ) including the following information such as

```python

FrozenTrial(number=0, values=[0.0], datetime_start=datetime.datetime(2021, 3, 16, 19, 44, 6, 600686), datetime_complete=datetime.datetime(2021, 3, 16, 19, 46, 56, 527579), params={'coeff_eda_acc': 0.0028374752723166917, 'coeff_eda_rotation': 0.00864820362603393, 'pid_gsr_D': 0.7960477724841889, 'pid_gsr_I': 0.005968617003375035, 'pid_gsr_P': 0.5909379771569737, 'pid_long_D': 0.020177425505735057, 'pid_long_I': 0.2522589329251081, 'pid_long_P': 0.01131627072780415, 'pid_rotation_D': 0.65018123097609, 'pid_rotation_I': 0.005401413557853871, 'pid_rotation_P': 0.08455131343079868}, distributions={'coeff_eda_acc': LogUniformDistribution(high=2.0, low=0.001), 'coeff_eda_rotation': LogUniformDistribution(high=2.0, low=0.001), 'pid_gsr_D': LogUniformDistribution(high=1.0, low=0.005), 'pid_gsr_I': LogUniformDistribution(high=1.0, low=0.005), 'pid_gsr_P': LogUniformDistribution(high=1.0, low=0.005), 'pid_long_D': LogUniformDistribution(high=1.0, low=0.005), 'pid_long_I': LogUniformDistribution(high=1.0, low=0.005), 'pid_long_P': LogUniformDistribution(high=1.0, low=0.005), 'pid_rotation_D': LogUniformDistribution(high=1.0, low=0.005), 'pid_rotation_I': LogUniformDistribution(high=1.0, low=0.005), 'pid_rotation_P': LogUniformDistribution(high=1.0, low=0.005)}, user_attrs={}, system_attrs={'multi_objective:nsga2:generation': 0}, intermediate_values={0: 0.37434327084021657, 1: 0.8379479784162127, 2: 0.5411359739545133, 3: -1.9317150635208686, 4: 1.234260289210234, 5: -12.099912357581067}, trial_id=3, state=TrialState.COMPLETE, value=None) 
```

In addition, how do you define/understand the best trial in multi objective problem as there are so many objectives? Any rules to determine that the current trial is the best trial?

**Comment by nzw0301** [comment]
## dataframe

According to [`trials_dataframe`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.trials_dataframe), `intermediate_values` is not in default attributes. To contain intermediate values, we need to add `'intermediate_values'` to `attr` arguments:

```python
study_results = loaded_study.trials_dataframe(
    attrs=('number', 'value', 'datetime_start', 'datetime_complete', 'duration', 'params', 'user_attrs', 'system_attrs', 'state', 'intermediate_values'))
```

## MultiObject's best trials

Indeed, the [`best_trials`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.best_trials) of multi-objective optimisation are located at Pareto front.

**Comment by yywangvr** [comment]
Dear @nzw0301 , thanks for the support. I started the code,
```python
import optuna

storage="sqlite:///optuna_studyBase.db"
study_name='onlyPIDoptimization'

loaded_study = optuna.load_study(study_name=study_name, storage=storage)

sstudy_results = loaded_study.trials_dataframe(attrs=('number', 'value', 
                                                      'datetime_start',
                                                      'datetime_complete',
                                                      'duration', 'params', 
                                                      'user_attrs',
                                                      'system_attrs','state',
                                                      'intermediate_values'),multi_index=True)


study_results.to_excel('pid_Optuna.xlsx', index=False)
study_results.to_csv('pid_Optuna.csv', index=False)
print(loaded_study.best_trial,'\n')
print(loaded_study.best_params,'\n')
print(loaded_study.best_value,'\n')
```
However, I still did not see `intermediate_values`, as a ref [pid_Optuna.xlsx](https://github.com/optuna/optuna/files/6158159/pid_Optuna.xlsx), [optuna_studyBase.db](https://drive.google.com/file/d/1nQ0eHoup2Ju2hx2lLBi9dNqdLSIL5eZk/view?usp=sharing). 



In addition, why does the column `value` keep zero in all trials? (I might lack knowledge in genetic optimization algorithms)

**Comment by nzw0301** [comment]
Awesome! 

For a multi-objective function, `objective` needs to return multiple objective values; `v0`  and `v1` in the following example code block:

```python
def objective(trial):
    x = trial.suggest_float("x", 0, 5)
    y = trial.suggest_float("y", 0, 3)

    v0 = 4 * x ** 2 + 4 * y ** 2
    v1 = (x - 5) ** 2 + (y - 5) ** 2
    return v0, v1
```

I think that `intermediate_values` are not used as final objective values and they tend to be used for pruning feature in optuna, like [this page](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.pruners.MedianPruner.html). Thus `values` should be returned values of `objective`; `v0` and `v1` again in the example `objective` above.

**Comment by yywangvr** [comment]
Thank you again.  I guess this may because I run Optuna in two processes as indicated in [here](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html), and therefore I do not have `values` but obtain `intermediate_values` instead. 

When I retry my code in one process, everything seems fine.
