### ISSUE TITLE
Defining a range that depends on prior range definition, best practice?

### ISSUE THREAD

**Issue by DrAgdur** [optuna/optuna#2495]
***DELETE THIS ISSUE***, i asked my question in the gitter room, seemed more appropiate.
Sorry for any caused misconvencience.

kind regards

**Comment by MaximilianSamLickeAgdur** [comment]
DELETE ISSUE. I asked the same thing in the gitter room, seems more appropiate to ask it there. sorry for any misconvencience.

**Comment by nzw0301** [comment]
If so, could you close this issue because this issue is not informative anymore

**Comment by DrAgdur** [comment]
closing issue
