### ISSUE TITLE
Add a FAQ entry for constrained optimization

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2497]
It would be great to add an FAQ entry to describe constrained optimization in optuna. I think the entry mentions some samplers that support `constraints_func` and [pruning unsatisfied hyper-parameter combination](https://github.com/optuna/optuna/issues/465#issuecomment-515835378). I'm not familiar with constrained optimization, so the aforementioned content might not be included.

**Comment by nzw0301** [comment]
Now, I feel that a tutorial format is better to describe the optimization. Candidates of the content are as in the following issues:

For example
- https://github.com/optuna/optuna/issues/2713
- https://github.com/optuna/optuna/issues/2775
- https://github.com/optuna/optuna/issues/2701

**Comment by HideakiImamura** [comment]
Let me close this issue since #3117 has been merged.
