### ISSUE TITLE
optuna create-study, Could not load the Qt platform plugin "xcb" in "" even though it was found

### ISSUE THREAD

**Issue by max-yue** [optuna/optuna#2500]
# optuna create-study --study-name "distributed-example" --storage "mysql://root@localhost/example"

QFactoryLoader::QFactoryLoader() checking directory path "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archreq": 0,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqlinuxfb.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archreq": 0,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("linuxfb")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archreq": 0,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqminimalegl.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archreq": 0,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archreq": 0,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqvnc.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archreq": 0,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwayland-egl.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwayland-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-egl"
        ]
    },
    "archreq": 0,
    "className": "QWaylandEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("wayland-egl")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwayland-generic.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwayland-generic.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland"
        ]
    },
    "archreq": 0,
    "className": "QWaylandIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("wayland")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-egl.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-egl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-xcomposite-egl"
        ]
    },
    "archreq": 0,
    "className": "QWaylandXCompositeEglPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("wayland-xcomposite-egl")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-glx.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwayland-xcomposite-glx.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "wayland-xcomposite-glx"
        ]
    },
    "archreq": 0,
    "className": "QWaylandXCompositeGlxPlatformIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("wayland-xcomposite-glx")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwebgl.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqwebgl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "webgl"
        ]
    },
    "archreq": 0,
    "className": "QWebGLIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("webgl")
QFactoryLoader::QFactoryLoader() looking at "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so"
Found metadata in lib /share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}

Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/share/apps/anaconda3/envs/qa_env/bin/platforms" ...
loaded library "/share/apps/anaconda3/envs/qa_env/lib/python3.6/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display localhost:0.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted

**Comment by max-yue** [comment]
(qa_env) root@ali-g:~# optuna create-study --study-name "distributed-example" --storage "mysql://root@localhost/example"
Traceback (most recent call last):
  File "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/apps/anaconda3/envs/qa_env/bin/optuna", line 5, in <module>
    from optuna.cli import main
  File "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/optuna/cli.py", line 22, in <module>
    from cliff.app import App
  File "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/cliff/app.py", line 22, in <module>
    import cmd2
  File "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/cmd2/__init__.py", line 30, in <module>
    from .cmd2 import Cmd
  File "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/cmd2/cmd2.py", line 73, in <module>
    from .clipboard import (
  File "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/cmd2/clipboard.py", line 14, in <module>
    _ = pyperclip.paste()
  File "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/pyperclip/__init__.py", line 680, in lazy_load_stub_paste
    copy, paste = determine_clipboard()
  File "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/pyperclip/__init__.py", line 582, in determine_clipboard
    import qtpy  # check if qtpy is installed
  File "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found
(qa_env) root@ali-g:~# pip install pyqt5
Looking in indexes: http://mirrors.cloud.aliyuncs.com/pypi/simple/
Collecting pyqt5
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/ed/62/cd9f10702c75b242f82da858668fba0cda04cda92133244d3d1555e530b4/PyQt5-5.15.4-cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl (8.3 MB)
     |████████████████████████████████| 8.3 MB 506 kB/s 
Collecting PyQt5-Qt5>=5.15
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/83/d4/241a6a518d0bcf0a9fcdcbad5edfed18d43e884317eab8d5230a2b27e206/PyQt5_Qt5-5.15.2-py3-none-manylinux2014_x86_64.whl (59.9 MB)
     |████████████████████████████████| 59.9 MB 56.8 MB/s 
Collecting PyQt5-sip<13,>=12.8
  Downloading http://mirrors.cloud.aliyuncs.com/pypi/packages/31/24/f887203677955ba4d5d4efe9176ac7ed2bf84efce8c243ab91e63183ad9e/PyQt5_sip-12.8.1-cp37-cp37m-manylinux1_x86_64.whl (283 kB)
     |████████████████████████████████| 283 kB 888 kB/s 
Installing collected packages: PyQt5-sip, PyQt5-Qt5, pyqt5
Successfully installed PyQt5-Qt5-5.15.2 PyQt5-sip-12.8.1 pyqt5-5.15.4
(qa_env) root@ali-g:~# optuna create-study --study-name "distributed-example" --storage "mysql://root@172.17.112.91/example"
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
(qa_env) root@ali-g:~#

**Comment by max-yue** [comment]
# optuna create-study --study-name "distributed-example" --storage "mysql://root@localhost/example"

Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/share/apps/anaconda3/envs/qa_env/bin/platforms" ...
loaded library "/share/apps/anaconda3/envs/qa_env/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display localhost:11.0
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted

**Comment by max-yue** [comment]
according to this page, https://www.programmersought.com/article/66666346249/

question
The problem appears to be called under Linuxplt.savefig()Function, a display error occurred.

Solution
Add two lines of code under the file that calls the function.

import matplotlib
matplotlib.use('Agg')

**Comment by nzw0301** [comment]
I'm afraid that I cannot understand what is a bug in this issue. I would like to kindly ask you to follow the issue template for the bug report. Otherwise, this issue won't be checked because it will take too much time to understand it. 

I suppose that using [markdown](https://guides.github.com/features/mastering-markdown/), providing reproducible code example, and clarifying dependencies are really helpful to understand the issue.


Cheers,
