### ISSUE TITLE
Time zone problems

### ISSUE THREAD

**Issue by Turakar** [optuna/optuna#2502]
I use Optuna with a RDB backend and from two different workers, one on my home computer and one remote. The two computers use different time zones (GMT+1 and UTC respectively). The datetimes in the database seem to wrong, i.e. the stored datetime is the local time of the machine.

## Expected behavior
The shown datetimes either store time zone information with them or all use one time zone (e.g. UTC).

## Environment

- Optuna version: 2.5.0
- Python version: 3.9
- OS: Linux (Fedora 33 and Docker `python:3.9` container)
- (Optional) Other libraries and their versions: PostgreSQL 12

## Steps to reproduce

1. Create a study with a RDB backend.
2. Set up two workers with different time zones.
3. Observe the datetime values in the database.

**Comment by nzw0301** [comment]
Hi @Turakar, 

[`optuna.storages.RDBStorage`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.storages.RDBStorage.html) can pass keywords of database to the DB by using `engine_kwargs` via `sqlalchemy` package.

I think that [this stackoverflow's answer](https://stackoverflow.com/questions/26105730/sqlalchemy-converting-utc-datetime-to-local-time-before-saving/26106482) might be helpful.

Note:  I haven't checked that the combination of  `engine_kwargs` and the stackoverflow's answer works to change the timezone.
