### ISSUE TITLE
Is it possible log a variable in the objective function?

### ISSUE THREAD

**Issue by yywangvr** [optuna/optuna#2520]
```python
import optuna

def objective(trial):
    x = trial.suggest_float("x", 0, 5)
    y = trial.suggest_float("y", 0, 3)

    v0 = 4 * x ** 2 + 4 * y ** 2
    v1 = (x - 5) ** 2 + (y - 5) ** 2
    v=v0+v1
    return v

```

Is it possible to log the value of `v0` and `v1` in  some functions such as`study.trials_dataframe`. As I also wish to analyse the intermediate values in the objective functions.

**Comment by nzw0301** [comment]
Hi @yywangvr, I think we can store such values in `Trial.user_attrs`. To do so, we call [`Trial.set_user_attr`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.set_user_attr) during each objective evaluation. For your example

```python
import optuna

def objective(trial):
    x = trial.suggest_float("x", 0, 5)
    y = trial.suggest_float("y", 0, 3)

    v0 = 4 * x ** 2 + 4 * y ** 2
    v1 = (x - 5) ** 2 + (y - 5) ** 2
    trial.set_user_attr("v0", v0)
    trial.set_user_attr("v1", v1)
    v= v0 + v1
    return v
```

**Comment by yywangvr** [comment]
Hi @nzw0301 , it works.  I really appreciate your sustaining support and help during my using of Optuna!

**Comment by nzw0301** [comment]
It's my pleasure! I'm glad to hear that I could support your optuna life.
