### ISSUE TITLE
Truncate the length of valued of set_user_attr.

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#2522]
When I want to log long strings (like exceptions with stacktrace) as an `user_attr` the content might get very long. If `value` is above the length of 2048 characters an exception is thrown. This should be avoided by truncation and maybe logging a warning.

There might be other locations where the same problem might happen. Like in `set_system_attr`. This can be done on `trial` and `study` layer. That needs to be analysed.

**Comment by y0z** [comment]
Hi. I think this limitation problem has already been relaxed in #2395.

**Comment by PhilipMay** [comment]
Ok - I will check.

**Comment by PhilipMay** [comment]
Works. Thanks - I am closing this again.
