### ISSUE TITLE
How to access information about best trial inside the objective function?

### ISSUE THREAD

**Issue by ZumbiAzul** [optuna/optuna#2523]
How to access information about the best trial within the objective function.
I would like to get access to the information that is usually accessed after study has finished. 
For example, I would like to access the following info:

- info that is normally obtainable by this command: `print(study.best_trial)`
- info that is normally obtainable by this command: `print(study.best_trial.value)`
- info obtainable from
```
for key, value in study.best_trial.params.items():
    print("    {}: {}".format(key, value))
```
- state of the trial (in the end of the objective function)
- information about all previous trials (e.g. provided by `study.trials_dataframe(attrs=('number', 'value', 'params', 'state'))`)

**Comment by toshihikoyanase** [comment]
Hi @ZumbiAzul 
Currently, Optuna does not provide public API to access the best trials inside objective functions.
Alternatively, users can access them in the callbacks which are executed right after objective functions. For example, you can print the best trial and trials dataframe as follows:

```python
def print_callback(study, trial):
    print(study.best_trial)
    print(study.trials_dataframe(attrs=('number', 'value', 'params', 'state')))

...
study.optimize(objective, callbacks=[print_callback], ...)
```
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize

Does it work for your use case?

**Comment by ZumbiAzul** [comment]
> Hi @ZumbiAzul
> Currently, Optuna does not provide public API to access the best trials inside objective functions.
> Alternatively, users can access them in the callbacks which are executed right after objective functions. For example, you can print the best trial and trials dataframe as follows:
> 
> ```python
> def print_callback(study, trial):
>     print(study.best_trial)
>     print(study.trials_dataframe(attrs=('number', 'value', 'params', 'state')))
> 
> ...
> study.optimize(objective, callbacks=[print_callback], ...)
> ```
> 
> https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize
> 
> Does it work for your use case?

Thanks for your reply!
I think it could be a solution, if it was possible to pass some other variable into the callback-function.
An idea of what I would like to have is something like this:
```
def print_callback(study, trial, n):
    print(study.best_trial)
    print(study.trials_dataframe(attrs=('number', 'value', 'params', 'state')))
    print(n)

...
study.optimize(objective, callbacks=[print_callback(n)], ...)
```

Are there workarounds to achieve this?

**Comment by nzw0301** [comment]
Like this?

```python
class MyCallback(object):

    def __init__(self, n):
        self.n = n

    def __call__(self, study, trial):
        print(self.n)
        print(study.best_trial)
        print(study.trials_dataframe(attrs=('number', 'value', 'params', 'state')))


study = optuna.create_study()
study.optimize(objective, n_trials=3,
              callbacks=[MyCallback(n=10)])
```

**Comment by ZumbiAzul** [comment]
@nzw0301 Thanks! It is not a straightforward solution, but I can make it work with some changes in the logic in my code.
