### ISSUE TITLE
[BUG] `plot_optimization_history` not working with multi objective even if target is given

### ISSUE THREAD

**Issue by YannDubs** [optuna/optuna#2531]
`matplotlib.plot_optimization_history` does not work in multi objective setting even if the `target` is given. Despite the doc saying that it would raise an error only if `If target is None and study is being used for multi-objective optimization.`

The issue is that the code uses `study.direction` (which does not exist in multi objective) at this line:
https://github.com/optuna/optuna/blob/master/optuna/visualization/matplotlib/_optimization_history.py#L102 

And so the error is : 
```
RuntimeError: The single direction of a `study` is only supported for single-objective optimization.
```

**Comment by nzw0301** [comment]
@YannDubs Thank you for reporting the bug and sharing your investigation! I could confirm the bug.

**Comment by nzw0301** [comment]
Let me create a pull request to resolve this bug, but if you already prepare a pull request for this PR, I'm willing to close my PR.

---

BTW, your neural process family pages are really helpful to learn NPs, and I enjoyed reading your paper about representation learning and information theory!

**Comment by YannDubs** [comment]
Perfect, looking forward to have this PR merged :) 

@nzw0301 woaw thanks for the very kind words about the projects !!

**Comment by nzw0301** [comment]
The pull request has been merged! The bug will be fixed in the next release! Again, thank you for your investigation and for reporting the bug! Let me close this issue.
