### ISSUE TITLE
Is this normal contour plot with categorical value?

### ISSUE THREAD

**Issue by fsmosca** [optuna/optuna#2544]
The contour [plot seems weird](https://fsmosca.github.io/Mabigat/example.html). Is this normal?

The variable random_multi_pv in this case is categorical integer. If I change this to continuous, it is fine

Ref.:
optuna==2.6.0
plotly==4.14.3

I tried it with matplotlib, the same thing happened - not nice.
I tried it with optuna==2.5.0 / plotly, not nice too.

I use it in this [repo](https://github.com/fsmosca/Mabigat).

**Comment by nzw0301** [comment]
Could you explain a little bit more about the wiredness of the plot?

**Comment by fsmosca** [comment]
![](https://i.imgur.com/om0S2ur.png)

red marking: the plot does not exactly fit.
yellow: the number is not in sequence.

**Comment by nzw0301** [comment]
Thank you for your helpful clarification! 

Let me put a minimum example.

```python
import optuna
import numpy as np


def objective(trial):
    x = trial.suggest_uniform('x', -100, 100)
    y = trial.suggest_categorical('y', np.arange(-10, 10, 1))
    z = trial.suggest_uniform('z', -100, 100)
    return x ** 2 + y - z

study = optuna.create_study()
study.optimize(objective, n_trials=30)

optuna.visualization.plot_contour(study, params=['x', 'y', 'z'])
```

**Comment by nzw0301** [comment]
About yellow circles: I think a number of visualisation functions, such as `plot_contour` and `plot_parallel_coordinate`, do not sort the suggested values from categorical distribution when drawing a plot.

**Comment by nzw0301** [comment]
Yellow circles: I was wrong. The suggested values from a categorical distribution are actually **sorted**, but they are soreted as `str`.

**Comment by fsmosca** [comment]
Try this for the yellow.
```python
y = trial.suggest_categorical('y', [4, 5, 8, 11])
```

On red the plot fits as expected. I will check again my code why it does not fit well.

**Comment by nzw0301** [comment]
Yes, I think the reason is same: categorical calues are sorted as `str`: 

```python
sorted(map(str, [4, 5, 8, 11]))
# ['11', '4', '5', '8']
```

This is why `10` or `11` appears in the left corner....

**Comment by nzw0301** [comment]
If the suggested values only contain float or int, we can sort the values as a numerical value rather than `str`.
if I apply this patch https://github.com/nzw0301/optuna/commit/4ac96585c0a548866d98a4f5a7ddf562b087fd3c, then the plot is 

![newplot (4)](https://user-images.githubusercontent.com/7121753/113039760-01d81f00-91d3-11eb-8300-75681a1ce3d3.png)

**Comment by fsmosca** [comment]
I still cannot solve my contour plot fitting. At the moment I will just try to avoid the categorical param type to get a beautiful contour plots.

**Comment by nzw0301** [comment]
Hi @fsmosca, I think the plot seems similar to what you want now! 

![newplot (4)](https://user-images.githubusercontent.com/7121753/113718054-3bef7680-9727-11eb-9781-f7b39ec09deb.png)

**Comment by fsmosca** [comment]
The coordinates are now in sequence so it is fine.

My issue is still the fitting at the sides. I will try later this new 2.7.0.
