### ISSUE TITLE
Weights and biases integration

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2553]
NOTE: I haven't used any management tools for ML; so it is an idea to enlarge optuna community.

## Motivation

[weights and biases](https://wandb.ai/site) (W&B) is a tool for tracking machine learning experiments, visualize metrics, and share results like MLflow. As a counterpart of MLflow, it might be great to support W&B integration for W&B users.

## Description

Like optuna's mlflow integration, optuna might provide a callback for W&B and its example.

## Additional context (optional)

[A blog post to use optuna and W&B](https://www.h4pz.co/blog/2020/10/3/optuna-and-wandb)

**Comment by xadrianzetx** [comment]
Hi, can I implement this callback?

**Comment by nzw0301** [comment]
@xadrianzetx  Yes! Thank you for your proposal.
