### ISSUE TITLE
trial.suggest_int() ignores step

### ISSUE THREAD

**Issue by shu65** [optuna/optuna#2557]
I used `trial.suggest_int()` with step. But, `suggest_int()` ignores arguments when study has trials with different distributions.

## Environment

- Optuna version: 2.6.0 
- Python version: 3.7.10
- OS: (I used Google Colab)
- (Optional) Other libraries and their versions:

## Error messages, stack traces, or logs

```
# error messages, stack traces, or logs
```

## Steps to reproduce

1. run reproducible example on Google Colab

## Reproducible examples (optional)

Bug case:
```python
import optuna

sampler = optuna.samplers.TPESampler(multivariate=True, n_startup_trials=10)
study = optuna.create_study(direction='maximize', sampler=sampler)

test_int_dist = optuna.distributions.IntUniformDistribution(0, 100) # no step
for v in range(100):
  trial = optuna.trial.create_trial(
          params={'test-int':v},
          distributions={'test-int': test_int_dist},
          value=0)
  study.add_trial(trial)

trial = study.ask()
trial.suggest_int('test-int', low=0, high=100, step=5) # specific step
```

the output is this:
![image](https://user-images.githubusercontent.com/261656/113367103-1f091b00-9396-11eb-8d80-4a7dba851d0f.png)

correct case:
```python
import optuna

sampler = optuna.samplers.TPESampler(multivariate=True, n_startup_trials=10)
study = optuna.create_study(direction='maximize', sampler=sampler)

test_int_dist = optuna.distributions.IntUniformDistribution(0, 100, step=5) 
for v in range(100):
  trial = optuna.trial.create_trial(
          params={'test-int':v},
          distributions={'test-int': test_int_dist},
          value=0)
  study.add_trial(trial)

trial = study.ask()
trial.suggest_int('test-int', low=0, high=100, step=5) # specific step
```

**Comment by not522** [comment]
Thank you for your investigation! It seems we need a more detailed checking in `check_distribution_compatibility`.
https://github.com/optuna/optuna/blob/c228f0a5011579b21449b06f4b7ba308090fb515/optuna/distributions.py#L503-L534

**Comment by fsmosca** [comment]
Based from this,

```python
for v in range(100):
  trial = optuna.trial.create_trial(
          params={'test-int':v},
          distributions={'test-int': test_int_dist},
          value=0)
  study.add_trial(trial)
```
the params `test-int` can have a value of 8. Later the step is changed to 5. Now 8 - 5 = 3. So 3 is just fine because 8 is in the trial history and the optimizer considers the value of 8 in its calculation.
