### ISSUE TITLE
MLFlow logging multiple metrics

### ISSUE THREAD

**Issue by UgurKap** [optuna/optuna#2567]
I want to log multiple metrics in MLFlow but under the hood, Optuna uses mlflow.log_metric in its MLFlowCallBack so there is no straigthforward way to do it.

## Motivation

When I am using MLFlow to log experiments, I might want to log additional metrics even though I am not optimizing specifically for them. Or I could be using their sum in my objective function and I might want to learn their individual contribution to the objective score.

## Description

MLFlowCallBack can get additional parameters (functional parameters, not hyperparameters) to log.

## Alternatives (optional)

--

## Additional context (optional)

--

**Comment by HideakiImamura** [comment]
Thanks for the proposal. Let me label this issue as "contribution-welcome".

**Comment by lucafurrer** [comment]
Hi, I run into the same case. I am thinking about writing a decorator. If it works I voluntary share the result with you.

**Comment by lucafurrer** [comment]
@HideakiImamura A decorator for the objective function seems the work fine and address the problem. Should I try to work out a PR or is totally out of scope where you want to go with optuna?

**Comment by HideakiImamura** [comment]
@lucafurrer Thank you for the investigation! Could you create a draft PR? I'd like to discuss the design in the draft PR.

**Comment by lucafurrer** [comment]
Hi @HideakiImamura I will do that (I hope soon 😉)

**Comment by lucafurrer** [comment]
Hi @HideakiImamura  I finally managed to make a draft PR #2670 with my idea. I would be glad if you could have a look at it.
