### ISSUE TITLE
Large number of binary hyperparameters

### ISSUE THREAD

**Issue by FelixNeutatz** [optuna/optuna#2572]
Dear all,

I am currently experimenting with a large number of binary hyperparameters (>1k/10k). Unfortunately, Optuna is getting slow when I use the TPESampler and I do not want to use random sampling. Do you have any tip for me how to apply Bayesian optimization here?

Thank you for your help.

Best regards,
Felix

**Comment by fsmosca** [comment]
What is binary hyperparameters?

What is the slow down from using 10 param to 1k param?

In TPE you can use multivariate=True if you want the sampling to consider dependencies among parameters. By using TPE sampler you are already using bayesian optimization. Do you mean other optuna samplers?

**Comment by FelixNeutatz** [comment]
Hi @fsmosca,

thank you for your quick response. The multivariate idea was a good tip. 

Here, is a toy example of what I mean:

```
import numpy as np
import optuna
from optuna.samplers import TPESampler
import random
import time

number_parameters = []
all_time = []

for power_i in range(5):
    number_of_bin_parameters = np.power(10, power_i)

    def my_loss(trial):
        x = []
        for i in range(number_of_bin_parameters):
            x.append(trial.suggest_categorical('x' + str(i), [True, False]))
        return random.random()

    start = time.time()

    study = optuna.create_study(direction='minimize', sampler=TPESampler())
    study.optimize(my_loss, n_trials=100)

    all_time.append(time.time() - start)
    number_parameters.append(number_of_bin_parameters)

print(number_parameters)
print(all_time)
```

This yields the following numbers:
![image](https://user-images.githubusercontent.com/5217389/114007503-b1f7f880-9861-11eb-8444-1cc134c1e934.png)

Is there any way to make this faster and more scalable with respect to the number of parameters?

Best regards,
Felix

**Comment by fsmosca** [comment]
Here is a comparison with different sampler/optimizers.

Notes:
1. cmaes when optimizing at 2k params almost used all my 4-core/8-threads processing power. This needs to be reported as it should not use my cpu at 90 to 95% without prior knowledge.
2. bayes_opt is from https://github.com/fmfn/BayesianOptimization, this is not in optuna. I used it via nevergrad.
3. I will not complete the test on 10k params, as my 16GB RAM is almost consumed.

![](https://i.imgur.com/Fw6U0sr.png)

```
 num_param  random     tpe  tpe_multivar  hyper_opt     cmaes  scikit_opt  bayes_opt
       100    0.23    7.65          6.78       4.07      0.66       25.35     268.00
       500    1.16   38.03         33.71      20.19      6.20      115.36     438.64
      1000    2.44   76.77         67.93      40.36    797.52      235.75     768.38
      2000    5.68  159.24        154.20      84.58  18838.26      493.46     827.38
```

You can [browse the plot here](https://fsmosca.github.io/Mabigat/optimizer_comparison.html).

bayes_opt is interesting it seems like it does not spent too much time from 1k to 2k num_params.

I am not sure though if optuna developers have attempted to make some serious optimization on the samplers. Profiling to find some hotspots and bottleneck would be interesting.

**Comment by andyDoucette** [comment]
Please re open this issue as it's a show stopper.  I'm using 1000 binary hyperparameters and it trials 1 and 2 took about 0.2 seconds and trial 2000 takes about 20 seconds with NSGAIIISampler.  That's a genetic algorithm.  It keeps a fixed population size and has no dependency on the history, only it's current population.  Each trial should take the same amount of time, regardless of if it's trial 1 or 2000.

**Comment by nabenabe0928** [comment]
@andyDoucette could you tell me which optuna version you are using?

**Comment by andyDoucette** [comment]
@nabenabe0928  optuna==3.1.0

**Comment by nabenabe0928** [comment]
@andyDoucette 
Could you upgrade the version and try the same thing?
If possible, I would like to have the dimension of your search space and what population size you used in your experiments.

**Comment by andyDoucette** [comment]
Ok.  I've upgraded to optuna==4.3.0 and will run it again (It will take a
while - I'll probably report the results tomorrow.).

The search stace has 950 binary parameters.

I'm using this code to initialize the sampler:
optuna_seed=42
sampler = optuna.samplers.NSGAIISampler(seed=optuna_seed)

I believe that uses the defaults.

**Comment by andyDoucette** [comment]
The new version shows the same deleterious results.

Here is a plot of the number of seconds that each iteration takes vs time.

<img width="782" alt="Image" src="https://github.com/user-attachments/assets/de4f2350-5adb-44a4-9a04-142eaf852d2b" />

You can see how this would really get in the way of a long optimization.

Just to be really sure, I'll replace the objective function with a random number generator and see if I can prove that it's 100% optivo...

**Comment by andyDoucette** [comment]
The spikes at 500 and 1000 are my callback function making plots every 500 iterations.  That can be ignored.

**Comment by andyDoucette** [comment]
Before I respond to your message, allow me to update my results from last night.  

Here's my code, minimized a bit. (I haven't tested the minimzed version.  There might be a missing import or variable or something but it should be easy to get working.

```
#!/usr/bin/python3
from constants import duration, out_dir, sampler
from benefit import benefit
from pprint import pprint
import os

import optuna

#how long we wait for an answer.
duration=7*24*60*60

#Set this to an integer if I want deterministic results:
optuna_seed=42

#Choose our sampler here:
sampler = optuna.samplers.NSGAIISampler(seed=optuna_seed)  

radius=10

# Disable all python warnings:
import warnings
warnings.filterwarnings("ignore")

study = optuna.create_study(direction='maximize',
                            sampler=sampler)

print("Optimizing...")
study.optimize(benefit, timeout=duration)

print('Optimization complete.')
print()


def params_get(trial, radius):
    '''
    Accepts a trial, gets the parameters from Optuna, and returns a dictionary of the parameters.
    '''

    #Thanks, chatGPT! :)
    num_edges=9*radius**2 + 5*radius + 1

    #We just use the side-effect of this.  It populates trial.params:
    params_list=[ trial.suggest_int(f'e{edge_id}', 0, 1) for edge_id in range(num_edges)]

    return trial.params

def benefit(trial=None, params=None):
    
    if params is None:
        assert trial is not None, 'benefit() needs either a set of params or a trial.'
        params=params_get(trial, radius)

    #This just proves that it's not an issue with my objective function getting slower.  random() is definitely constant time vs iteration:
    efficiency=random()

    return efficiency
```


requirements.txt:
```
agate==1.6.3
agate-dbf==0.2.2
agate-excel==0.2.5
agate-sql==0.5.8
aiohappyeyeballs==2.6.1
aiohttp==3.11.14
aiosignal==1.3.2
alembic==1.8.1.dev0
annotated-types==0.7.0
anyio==3.6.2
appdirs==1.4.4
apsw==3.40.0.0
asttokens==2.2.1
async-timeout==4.0.2
attrs==22.2.0
Babel==2.10.3
backcall==0.2.0
beautifulsoup4==4.11.2
beniget==0.4.1
blinker==1.5
Brlapi==0.8.4
Brotli==1.0.9
certifi==2022.9.24
chardet==5.1.0
charset-normalizer==3.0.1
click==8.1.3
cmaes==0.9.1
colorama==0.4.6
colorlog==6.7.0
contourpy==1.0.7
cryptography==38.0.4
css-parser==1.0.8
cssselect==1.2.0
csvkit==1.0.7
cupshelpers==1.0
cycler==0.11.0
dbfread==2.0.7
dbus-python==1.3.2
decorator==5.1.1
distlib==0.3.9
distro==1.8.0
distro-info==1.5+deb12u1
dnspython==2.3.0
docker==5.0.3
docker-compose==1.29.2
dockerpty==0.4.1
docopt==0.6.2
docstring-parser==0.15
envoy==0.0.3
et-xmlfile==1.0.1
executing==1.2.0
feedparser==6.0.10
filelock==3.18.0
fonttools==4.38.0
frozenlist==1.5.0
fs==2.4.16
fuse-python==1.0.5
gast==0.5.2
gpg==1.18.0
greenlet==2.0.2
h11==0.14.0
h2==4.1.0
hpack==4.0.0
html2text==2020.1.16
html5-parser==0.4.10
html5lib==1.1
httpcore==0.16.3
httplib2==0.20.4
httpx==0.23.3
hyperframe==6.0.0
idna==3.3
ifaddr==0.1.7
igraph==0.11.8
iniconfig==1.1.1
instructor==0.6.8
iotop==0.6
ipython==8.5.0
isodate==0.6.1
jdcal==1.0
jedi==0.18.2
jeepney==0.8.0
jiter==0.9.0
jsonpointer==2.3
jsonschema==4.10.3
kiwisolver==0.0.0
lazr.restfulclient==0.14.5
lazr.uri==1.0.6
leather==0.3.4
libvirt-python==9.0.0
louis==3.24.0
lxml==4.9.2
lz4==4.0.2+dfsg
Mako==1.2.4.dev0
Markdown==3.4.1
markdown-it-py==3.0.0
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.6
mdurl==0.1.2
mechanize==0.4.8
more-itertools==8.10.0
mpmath==0.0.0
msgpack==1.0.3
multidict==6.2.0
netifaces==0.11.0
ntpsec==1.2.2
numpy==1.24.2
oauthlib==3.2.2
olefile==0.46
openai==1.68.2
openpyxl==3.0.9
optuna==4.3.0
packaging==23.0
parsedatetime==2.6
parso==0.8.3
pdfminer.six==20221105
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==4.3.7
pluggy==1.0.0+repack
ply==3.11
prompt-toolkit==3.0.36
propcache==0.3.1
ptyprocess==0.7.0
pure-eval==0.0.0
py==1.11.0
py7zr==0.11.3+dfsg
pycairo==1.20.1
pychm==0.8.6
pycryptodomex==3.11.0
pycups==2.0.1
pydantic==2.10.6
pydantic_core==2.27.2
Pygments==2.14.0
PyGObject==3.42.2
PyICU==2.10.2
PyJWT==2.6.0
pylibacl==0.7.0
pyparsing==3.0.9
PyQt5==5.15.9
PyQt5-sip==12.11.1
PyQt6==6.4.2
PyQt6-sip==13.4.1
PyQt6-WebEngine==6.4.0
pyrsistent==0.18.1
pysmbc==1.0.23
pytest==7.2.1
python-apt==2.6.0
python-dateutil==2.8.2
python-dotenv==0.21.0
python-igraph==0.11.8
python-magic==0.4.26
python-slugify==4.0.0
pythran==0.11.0
pytimeparse==1.1.5
pytz==2022.7.1
pyxattr==0.8.1
pyxdg==0.28
PyYAML==6.0
regex==2022.10.31
reportlab==3.6.12
repoze.lru==0.7
requests==2.28.1
requests-toolbelt==0.10.1
rfc3986==1.5.0
rfc3987==1.3.8
rich==13.9.4
Routes==2.5.1
s3cmd==2.3.0
scipy==1.10.1
scour==0.38.2
sgmllib3k==1.0.0
shell_gpt==1.4.4
six==1.16.0
sniffio==1.2.0
soupsieve==2.3.2
SQLAlchemy==1.4.46
stack-data==0.6.2
sympy==1.11.1
tenacity==8.5.0
texttable==1.6.7
tornado==6.2
tqdm==4.64.1
traitlets==5.5.0
trash-cli==0.17.1.14
typer==0.9.4
typing_extensions==4.13.0
ufoLib2==0.14.0
ufw==0.36.2
unattended-upgrades==0.1
Unidecode==1.3.6
uritemplate==4.1.1
urllib3==1.26.12
virtualenv==20.29.3
wadllib==1.3.6
wcwidth==0.2.5
webcolors==1.11.1
webencodings==0.5.1
WebOb==1.8.6
websocket-client==1.2.3
xdg==5
xlrd==1.2.0
yarl==1.18.3
zeroconf==0.47.3
```

Here is the time-per-iteration vs iteration number again, for this dummy-objective function.

<img width="617" alt="Image" src="https://github.com/user-attachments/assets/181d325e-7c03-4cc2-953e-80bbb1aef0ea" />

**Comment by andyDoucette** [comment]
@nabenabe0928 :  Ok, regarding your effort to reproduce my issue.  First of all, thank you so much for looking into this a bit!  :) I really hope we can get to the bottom of this together and figure out what's happening.

Let me know if you need any more information about my setup to reproduce the issue.  I'm using Debian 12.10.  I'd be willing to run it with a profiler (cProfile?) active if that helps, and if you'd be willing to analyze the results.

**Comment by nabenabe0928** [comment]
Could you, @andyDoucette , please first confirm the speed with my code as my code does not have any other dependencies?
In my environment, your code did not exhibit any slowdown.

```python
import optuna


def f(t: optuna.Trial) -> float:
    if (t.number + 1) % 50 == 0:
        print(f"{t.number}-th Trial")
    return sum(t.suggest_int(f"b{i}", 0, 1) for i in range(1000))

optuna.logging.set_verbosity(optuna.logging.CRITICAL)
sampler = optuna.samplers.NSGAIISampler(seed=42)
study = optuna.create_study(sampler=sampler)
study.optimize(f, n_trials=2000)
```

**Comment by andyDoucette** [comment]
I can confirm the speed is fine with your code, on my system, with my dependencies still installed.  Now I'm very confused...

**Comment by andyDoucette** [comment]
When I have more time in a few days I'll see if I can binary search on the difference between your code and my code to find what the culprit is.  At first glance they seem like they should be equivalent.

**Comment by nabenabe0928** [comment]
@andyDoucette 
You could probably ask some LLMs, e.g., Grok, Gemini, ChatGPT, or Claude, with the advanced reasoning mode to figure out what your problems exactly are 🤔

**Comment by andyDoucette** [comment]
@nabenabe0928 : "Ask an AI" is the new "Did you google it?"  LOL. 

Regarding the benefit importing, that was just an artifact of me copy-pasting things together to fit into one example.  I never actually ran the minimized code I pasted here -that was just for the benefit of the chat.  My actual test runs were done with code in multiple files (still the same effective code though).
