### ISSUE TITLE
How to make search algorithms sometime re-evaluate already searched areas for models that change over time?

### ISSUE THREAD

**Issue by Akkarine** [optuna/optuna#2579]
Case:
I want to automate forecasting with [Prophet](https://github.com/facebook/prophet) for some physical process. Process can slowly or suddenly change behavior. So models, that worked before, may fail over time, but some fundamental characteristics will not change. In other words, some hyperparameters still has same importance.

Question:
If I want to benefit from parallelizing and saving results to RDB, how this case would affect to searching algorithms? Will some hyperparameters combinations, evaluated before as 'not promising', but now possibly could have better results, never recalculated again? And how I could save 'knowledge' about those fundamental characteristics?

I have a theory, that I should sometimes prune already calculated results from RDB with lower importance hyperparameters. But I want to keep tracking. Maybe I should make another Study and populate It from previous Studies and mark them somehow (so get a mark in UI)? But here I'm starting to worry about DB volume)

**Comment by fsmosca** [comment]
Interesting but what data does prophet is forecasting? Is it weather? typhoon or anything?

> Process can slowly or suddenly change behavior.

Does your objective value depends on this Process? If there is a change in this process the parameter that affects this change should be included in the optimization.

Optuna has feature to force params for re-evaluation, so if you feel like the old params that performed bad before might be good now, you can send it for re-evaluation.

**Comment by Akkarine** [comment]
It is water consumption by people, gathered from city infrastructure. Consumption can slowly change (population fluctuations) or, if new cluster added or some technical changes were made, completely change behavior.

By score I take *(MAE / 90% quantile of dataset)*.

Could you point me to docs where the feature you mentioned is documented? Can't find it.

**Comment by fsmosca** [comment]
All right that must be interesting.

Try [enqueue trial](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html?highlight=enqueue_trial#optuna.study.Study.enqueue_trial).

**Comment by Akkarine** [comment]
Thanks!
