### ISSUE TITLE
Set `n_jobs=1` in examples

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2581]
## Motivation

`n_jobs` argument of `Study.optimize` has been deprecated since optuna v2.7.0.

## Description

Set `n_jobs=1` in examples codes, for example https://github.com/optuna/optuna/blob/master/examples/rl/sb3_simple.py#L26.

**Comment by jeromepatel** [comment]
@nzw0301 Could you please provide a list of examples that need to be changed. I tried searching for `n_jobs` but I was able to locate only one (above example `examples/rl/sb3_simple.py`) occurrence of `n_jobs`. The search result can be found [here](https://github.com/search?q=n_jobs+repo%3Aoptuna%2Foptuna+extension%3Apy+language%3APython+path%3Aexamples%2F&type=Code&ref=advsearch&l=&l=).

**Comment by nzw0301** [comment]
Hi, @jeromepatel! Thank you for your suggestion. Indeed, the target file is only one in the example.
