### ISSUE TITLE
Switch off grid lines in matplotlib parallel coordinate plot

### ISSUE THREAD

**Issue by pplonski** [optuna/optuna#2596]
In the matplotlib parallel coordinate plot there are grid lines that make the plot hard to read. They should be switched off. The grid lines are added to each ax of the parallel coordinate plot and that's why they break the image.

![image](https://user-images.githubusercontent.com/6959032/115109459-21fb3280-9f76-11eb-8b81-92411db57d41.png)

This can be fixed by setting matplotlib properties before calling the plot method:
```python
plt.rcParams["axes.grid"] = False
```

but I believe it will be better to switch it off in the plot method.

This problem is only for matplotlib backend.

I would like to thank you for the two backends for plots. I love the plotly interactive plots in the jupyter notebook. For creating reports I'm using matplotlib backend plots because I don't want to install additional plotly dependencies (with chromium) to save plots to png files. Thank you!

**Comment by nzw0301** [comment]
Hi @pplonski! Thank you for reporting the bug.

On my environment and [Colab](https://colab.research.google.com/drive/19ix-ILBHaGg3wzmcAmj_7btZDjhNqvCq?usp=sharing), there are no grid lines on the plot generated by `optuna.visualization.matplotlib.parallel_coordinate` like this:
![download (4)](https://user-images.githubusercontent.com/7121753/115113567-f56f0700-9fc5-11eb-9c2f-c2d02f0917bf.png)

In my experience, I saw a similar plot to yours when I called `seaborn.set_theme()` or I changed Matplotlib parameters. What do you think about it?

**Comment by pplonski** [comment]
@nzw0301 oh, sorry, looks like it is my env problem. Closing the issue. Thank you for checking.

**Comment by nzw0301** [comment]
Please do not worry. My pleasure!
