### ISSUE TITLE
Sort categorical values on axis that contains only numerical values in `visualization.matplotlib.plot_slice`

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2605]
## Motivation

Similar to #2590, `slice_contour` does not sort the axis if the axis contains only numerical values.

## Description

Please treat such categorical parameters as numerical values.

## Example case

For example, the right sub-plot in the following figure:

![download (9)](https://user-images.githubusercontent.com/7121753/115230546-7c9bb680-a14f-11eb-8d13-05cdd1a3ec69.png)

As we can see, the y-axis values are sorted as `str` now.

## Code snippet

```python
import optuna


def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_categorical("y", list(range(-10, 10)))
    return x ** 2 + y


sampler = optuna.samplers.TPESampler(seed=10)
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=10)

optuna.visualization.matplotlib.plot_slice(study, params=["x", "y"])
```

**Comment by Muktan** [comment]
I would like to work on this issue.

**Comment by nzw0301** [comment]
@Muktan Awesome! please go ahead!
