### ISSUE TITLE
Comparison table for samplers

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2622]
The choice of a sampler is a critical factor to perform hyperparameter optimization well. Some sampler works poorly for some specific cases such as batch optimization or optimization over discrete parameters (i.e., int and categorical). To select an appropriate sampler for such a use-case, I would like to see a comparison table on [samplers page](https://optuna.readthedocs.io/en/stable/reference/samplers.html). 

| | Random | Grid | TPE | CmaEs | NSGAII | skopt | BoTorch | 
|-|:----:|:--------:|----|---|----|----|----|
| Batch optimization | | ✔️  | 
| Integer parameter  | ✔️ |  ▲ | 
| Multi-objective | ... | 
| Constraint | ... | 
| Categorical | ... | 
| Time compexity | O(1) | 

Time complexity should include the number of parameters as suggested by https://github.com/optuna/optuna/issues/2622#issuecomment-828670261.

It might be great to provide the table with Kurobako's benchmark performance.

**Comment by turian** [comment]
multivariate would be useful too.

**Comment by nzw0301** [comment]
We found a comparison table on [the tutorial page](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/003_efficient_optimization_algorithms.html). But I think it should be on the sampler page on the document rather than here and I would like to see a more comprehensive one.

**Comment by HideakiImamura** [comment]
I will work on this issue.

**Comment by nzw0301** [comment]
@HideakiImamura Thank you for your great work! It would be a helpful guide to selecting an appropriate sampler for users!
