### ISSUE TITLE
How do you switch samplers during a study?

### ISSUE THREAD

**Issue by turian** [optuna/optuna#2635]
In the original optuna paper, TPESampler was followed by CMA-ES.

I am actually finding that CMA-ES is much faster than multivariate TPESampler, but multivariate TPESampler achieves better objectives.

How do I switch the sampler of a study but use all previous results? e.g. run CMA-ES (with random initialization trials) first and then switch to multivariate TPESampler, with the second sampler learning from all previous trials

**Comment by turian** [comment]
Ah I see this related issue: https://github.com/optuna/optuna/issues/2264

Is there a way to save a study that has not be initialized with a particular storage location?

**Comment by turian** [comment]
(My preference would be not to use storage and just switch the sampler of a study that is already in memory.)

**Comment by not522** [comment]
You can switch samplers using `add_trials`.
I'm not sure what code was used in Optuna's paper. However, we can do the same with the following code.

```python
# First sampler
cmaes_sampler = optuna.samplers.CmaEsSampler()
cmaes_study = optuna.create_study(sampler=cmaes_sampler)
cmaes_study.optimize(objective, n_trials=20)

# Second sampler
tpe_sampler = optuna.samplers.TPESampler(multivariate=True)
tpe_study = optuna.create_study(sampler=tpe_sampler)
# Add the results of the first sampler's suggestions.
tpe_study.add_trials(cmaes_study.trials)
tpe_study.optimize(objective, n_trials=20)
```

**Comment by sile** [comment]
In addition to @not522 solution, you can just update the `sampler` field of a study after the first optimization as follows:
```python
study = optuna.create_study(sampler=optuna.samplers.CmaEsSampler()
study.optimize(...)  # First optimization with CmaEsSampler

study.sampler = optuna.samplers.TPESampler(multivariate=True)
study.optimize(...) # Second optimization with TPESampler
```

**Comment by turian** [comment]
Thank you.

**Comment by JRice15** [comment]
> In addition to @not522 solution, you can just update the `sampler` field of a study after the first optimization 

I am curious if anyone knows how this approach interacts with multiple optuna processes connected via RDBStorage?
