### ISSUE TITLE
Refactor test cases in `tests/pruners_tests/*.py`

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#2645]
## Motivation
Test cases in `tests/pruners_tests/*.py` can be simpler using should_prune and the ask-and-tell interface. e.g. https://github.com/optuna/optuna/pull/2644

## Description

- [ ] ~test_hyperband.py~
- [x] test_median.py
- [x] test_nop.py
- [x] test_percentile.py
- [x] test_successive_halving.py
- [x] test_threshold.py

**Comment by afozk95** [comment]
This seems to be fixed by #2691.

**Comment by Crissman** [comment]
@keisuke-umezawa Ok to close?

**Comment by keisuke-umezawa** [comment]
@Crissman Thank you! I close it.
