### ISSUE TITLE
Suggest fixed list of values

### ISSUE THREAD

**Issue by zzzbobml** [optuna/optuna#2646]
Is it possible to provide a fixed list of values for optimization? 
For example, I'd like my parameter to be one of the values in [1, 2.5, 3, 12.1].

**Comment by nzw0301** [comment]
Hi, @zzzbobml Could you explain a little bit more about it? Ideally, I would like to see the definition of the objective function.

**Comment by zzzbobml** [comment]
From the documentation 

```
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 50, 400)
    clf = RandomForestClassifier(n_estimators=n_estimators, random_state=0)
    clf.fit(X_train, y_train)
    return clf.score(X_test, y_test)
```
Let's say I wanted to try only the values of 50, 75 and 91 in `n_estimators`. 
Would that be possible?

**Comment by nzw0301** [comment]
yes! [`suggest_categorical`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.suggest_categorical) enables us to sample hyper-parameters from a list:

```python
def objective(trial):
    n_estimators = trial.suggest_categorical('n_estimators', [50, 75, 91])
    clf = RandomForestClassifier(n_estimators=n_estimators, random_state=0)
    clf.fit(X_train, y_train)
    return clf.score(X_test, y_test)
```

**Comment by zzzbobml** [comment]
Thank you!
