### ISSUE TITLE
Record additional values while searching

### ISSUE THREAD

**Issue by zzzbobml** [optuna/optuna#2650]
Is it possible to record additional values without interfering with the objective?
For example, in the code below I'd like to record `my_metric` so that I can see it in `study.trials_dataframe()` when optimization has completed.  In this case, `my_metric` is not used for optimization, but I would still need to record it. 

```
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 50, 400)
    clf = RandomForestClassifier(n_estimators=n_estimators, random_state=0)
    clf.fit(X_train, y_train)
    my_metric = compute_metric(clf, X_train, y_train)
    return clf.score(X_test, y_test)
```

**Comment by nzw0301** [comment]
Yes, it is. We can store such a variable as a user-attribute per trial by using `set_user_attr`:

```python
def objective(trial):
    n_estimators = trial.suggest_int('n_estimators', 50, 400)
    clf = RandomForestClassifier(n_estimators=n_estimators, random_state=0)
    clf.fit(X_train, y_train)
    my_metric = compute_metric(clf, X_train, y_train)
    trial.set_user_attr("my_metric", my_metric)
    return clf.score(X_test, y_test)
```

You can find details on https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/003_attributes.html.
