### ISSUE TITLE
[RFC] Create `oputna/examples` repository and move existing examples

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#2654]
## Motivation

Currently, the `optuna/optuna` repository has more than 60 example files, thanks to the great efforts of the contributors. It provides the usage of Optuna for various kinds of ML libraries such as PyTorch, LightGBM and etc. 

However,  I saw some problems in the CI of the examples as follows:
- The [GitHub Actions workflow file](https://github.com/optuna/optuna/blob/master/.github/workflows/examples.yml) is getting complicated. For example, some libraries does not support Python 3.6, and we need to exclude them in the workflow file. Such exception handling will increase when we add new libraries.
- The conflicts of library versions. For example, we wanted to test PyTorch examples with PyTorch v1.8.0, but AllenNLP did not support it.
- It takes more than 4 hours to execute all examples sequentially. Due to the execution time, we cannot run the CI jobs when submitting pull requests.

Some of these problems can be solved by splitting the CI workflow, but I think that this is a good opportunity to create an independent repository for Optuna examples. This is partly because we had already had enough contents, and partly because we may want to employ different policies (code review (1 approval or 2 approvals) and coding style(#2240)) from the `optuna/optuna` repository.

## Description

I propose to create a new repository to host the Optuna examples. I created a prototype repository and please take a look:
https://github.com/toshihikoyanase/optuna-examples

- It has an independent workflow file for each ML libraries (18 workflows in total). These workflows can be executed in parallel, and the CI jobs finish in an hour. With this change, we can execute CI with 
- We can preserves the git history by using the `git subtree split` command.

## Alternatives (optional)

We can just divide the `examples.yml` in the `optuna/optuna` repository. I tried this approach in #2587, and I created about 20 workflows for the CI of `examples`.

However, I and reviewers found that this approach had potential risk to deteriorate the productivity. This is because it doubled the workflows and it may annoy developers/reviewers when they edit/review the workflow. If we can nest the workflow like `.github/workflow/examples/allennlp`, we can employ this approach, but GitHub does not recognize the yaml files in subdirectories as workflows.

**Comment by toshihikoyanase** [comment]
I'll re-run `git subtree split` and  create the optuna-example repository in the [optuna organization](https://github.com/optuna) from now. After that, the changes to the contents of the `examples` directory in this repository may not be applied to the new repository.
So, please consider creating a PR in the new repository for the Optuna examples.

**Comment by hvy** [comment]
I think we can close this issue since the new repository has been created (and issues are tracked there as well). @toshihikoyanase what do you think?

**Comment by toshihikoyanase** [comment]
@hvy That makes sense. Let me close it. Thank you.
