### ISSUE TITLE
Overwrite existing study with new parameter distributions

### ISSUE THREAD

**Issue by marcelned** [optuna/optuna#2671]
When I run a study, saving results to Postgres, I cannot load an old study with new parameters. 

If the parameters distributions aren't exactly the same as when the study was first run, i get the following error:

```
ValueError: Cannot set different distribution kind to the same parameter name.
```

Is there a way to use Optuna to either delete old studies from the database, or reset them? Currently I have to resort to renaming the study everytime I run it with new parameters.

**Comment by hvy** [comment]
Do you have code/steps for reproduction? 

There is a function to delete a study if that is what you are looking for https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.delete_study.html#optuna.study.delete_study. You can also do this from Optuna's CLI https://optuna.readthedocs.io/en/stable/reference/cli.html#delete-study.

**Comment by marcelned** [comment]
@hvy  It was as easy as calling this optuna.study.delete_study method.

Thank you for the quick response!
