### ISSUE TITLE
Add an explanation of `WAITING` attribute

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2680]
## Motivation

`optuna.trial.TrialState` has five attributes, but one of them, `WAITING`, is missing on [the page](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.trial.TrialState.html).

## How to resolve it?

Please add the explanation `WAITING`  attribute to the docstring in [`optuna/trial/_state.py`](https://github.com/optuna/optuna/blob/master/optuna/trial/_state.py).

**Comment by hvy** [comment]
Let me close this issue since https://github.com/optuna/optuna/pull/2683 has been merged.
