### ISSUE TITLE
Waiting for Heartbeat

### ISSUE THREAD

**Issue by Turakar** [optuna/optuna#2685]
## Expected behavior

After `study.optimize` with a high heartbeat interval (e.g. 60s) finishes running trials, it should exit almost immediately. 

## Environment

- Optuna version: 2.7.0
- Python version: 3.9
- OS: Fedora 33
- (Optional) Other libraries and their versions: PostgreSQL

## Observed Behavior
Instead of exiting immediately, the main thread tries to join with the heartbeat thread, which only completes after the next scheduled hearbeat. This can lead to high delays where the program does basically nothing.

## Steps to reproduce

1. Create a RDB storage with a heartbeat interval of 60s.
2. Create a fast objective, a study and call `study.optimize(n_trials=1)`.
3. Measure runtime.

## Additional context (optional)
It might be better to use the [`wait(timeout=...)`](https://docs.python.org/3/library/threading.html#threading.Event.wait) method [here](https://github.com/optuna/optuna/blob/2fd68d0102a22e76b5a4a142cc87722d92dcf667/optuna/_optimize.py#L340).

**Comment by Turakar** [comment]
I would like to contribute a PR for this issue if you think this is adequate.

**Comment by hvy** [comment]
I'm not sure whether this is a bug but you're absolutely right about this issue (it's been mentioned before https://github.com/optuna/optuna/pull/2190#issuecomment-760655788). I'd be happy to take a look if you could send a PR!
