### ISSUE TITLE
optuna interfering with pytorch dataloaders

### ISSUE THREAD

**Issue by pyscorcher** [optuna/optuna#2693]
When using optuna with pytorch/torchvision dataloaders with multiple workers, sometimes the dataloader workers will pause indefinitely. If the order of imports is changed, it works fine. The behaviour only randomly seems to affect some runs. 

## Expected behavior
I expect the import order not to matter at all. I suspect optuna changes some global settings with respect to the multiprocessing libraries.

## Environment

- Optuna version: 2.7.0
- Python version: 3.9.2
- OS: Ubuntu 20.04
- Pytorch: 1.8.1

## Example
Unfortunately I'm not able to make a minimal reproducible example due to the erratic behaviour because only in about one of five or ten runs this issue would arise. But I wanted to bring thes strange behavour to attention and I try my best to describe the relevant parts:

In my case `train.py` just contains a training loop over a dataloader, loading large amounts of data (multiple 3d-volumes), which is created about as follows. Note that the issue only arises when using multiple workers, which means there are subprocesses being created.

```python
loader = torch.utils.data.DataLoader(
    my_dataset,
    batch_size=5,
    num_workers=3, # 0: loading from main process, >=1: loading from subprocesses (multiprocessing)
)
```

The hyperparameter optimization is in a separate file that imports `train.py` as well as `optuna`.

```python
# optuna main file
import optuna
from train import train  # this order of imports sometimes causes issues with the DataLoader

def objective(trial: optuna.trial.BaseTrial):
    p = dict()
    p['var'] = trial.suggest_int('var', low=0, high=100)
    metric = train(p)
    return metric

def main():
    study = optuna.create_study(
        study_name='my_study',
        storage="sqlite:///my_database.db",
        load_if_exists=True,
        direction='maximize'
        )
    study.optimize(objective, n_trials=100)
    print(f'{study.best_params=}')

if __name__ == '__main__':
    main()

```

## Possible Workaround
If we have the opposite order of imports (like the following), everything seems to work fine.

```python
from train import train
import optuna
```

## Additional context
As mentioned above, I believe that importing `optuna` somehow changes some global settings or the way `multiprocessing` works. I have noticed that `optuna` will also spawn subprocesses with the code snippet above, even if this is conceptually not necessary.

**Comment by nzw0301** [comment]
I saw a similar situation when just using PyTorch, for example, https://discuss.pytorch.org/t/training-freezes-when-using-dataloader-with-num-workers-0/34055/3.
