### ISSUE TITLE
Does TPESampler learn from pruned trials?

### ISSUE THREAD

**Issue by FelixNeutatz** [optuna/optuna#2696]
Hi everybody,

I have a short question about pruning: Does TPESampler learn from pruned trials? More specifically, I wonder whether pruned trials are inserted into the training data of the TPE model.

Unfortunately, I did not find anything on this in the documentation.

Best regards,
Felix

**Comment by nzw0301** [comment]
Hi @FelixNeutatz!  The short answer is Yes. I think this issue addresses your concern https://github.com/optuna/optuna/issues/1647.

**Comment by FelixNeutatz** [comment]
Great, thank you for the quick answer :)
