### ISSUE TITLE
How to fix certain parameters for optimization.

### ISSUE THREAD

**Issue by guangmingjian** [optuna/optuna#2697]
Optuna is a great project, but I encountered a problem and don't know what to do.  The problem is as follows. Suppose there is already a study, and some optimizations have been completed and saved in the database. I hope to **fix some of the parameters**, load the study and continue to optimize. What should I do? Thank you!

**Comment by nzw0301** [comment]
I'm not sure I understand the problem but how about [`PartialFixedSampler`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.samplers.PartialFixedSampler.html)?

**Comment by guangmingjian** [comment]
Thx. It works.
