### ISSUE TITLE
Optimize historical hyperparameters many times

### ISSUE THREAD

**Issue by guangmingjian** [optuna/optuna#2698]
I am a fan of optuna. Love it very much, it's so cool. But encountered a problem. 

The default sampling of optuna is used, but the same parameters are always searched. I used parallel optimization, but I searched for the same number of times too much. How can I avoid this problem.

![image](https://user-images.githubusercontent.com/20612185/119285600-f7874e00-bc74-11eb-9008-a13fe360653f.png)

**Comment by nzw0301** [comment]
We are happy to hear that! Could you share the minimal reproducible code?

**Comment by guangmingjian** [comment]
Sorry, I did not find a suitable minicode. But I thought of a solution. After optuna recommends the current parameter, I will judge whether this parameter has been run. Raise Pruner if it has been run.
