### ISSUE TITLE
How to categorical suggestions without duplicates?

### ISSUE THREAD

**Issue by NielsHoogeveen1990** [optuna/optuna#2701]
I am building a cipher with Optuna.

I would like to get suggestions, but no duplicates. 
So it should not be `{'a': 'c', 'b': 'c', 'c': 'c'}`
For example:
`suggestions_space = ['a', 'b', 'c']`
`a = trial.suggest_categorical('a', suggestions_space)`
Let's assume `{'a': 'c'}`. I would like to get suggestions for b and c, where it cannot be 'c' anymore.
Hence, I would like my suggestions_space now to be:
`suggestions_space = ['a', 'b']`
`b = trial.suggest_categorical('b', suggestions_space)`
et cetera.

How can I achieve this with Optuna?

**Comment by Crissman** [comment]
An Optuna cipher! That's fun.

I'd do the constraint by removing the used values. Something like:

```
a = trial.suggest_categorical('a', suggestions_space)
suggestions_space.remove(a)
b = trial.suggest_categorical('b', suggestions_space)
```

Please close this issue if that resolved your issue.

**Comment by Crissman** [comment]
Hoping this resolved your issue. Closing. Feel free to re-open if not solved yet.
