### ISSUE TITLE
Mistake in Pruning Algorithm's Doc

### ISSUE THREAD

**Issue by 01-vyom** [optuna/optuna#2703]
For the `Asynchronous Successive Halving algorithm` sentence, incorrect spelling of `implemented`.

[Link to the doc](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/003_efficient_optimization_algorithms.html#pruning-algorithms)

**Comment by nzw0301** [comment]
@01-vyom Thank you for reporting the typo!

**Comment by hvy** [comment]
Let me close this issue as fixed since https://github.com/optuna/optuna/pull/2704 has been merged into `master`. Again, thanks for the report.
