### ISSUE TITLE
Resume trial within a study with the original hyperparameters

### ISSUE THREAD

**Issue by KevinMusgrave** [optuna/optuna#2705]
I'm able to resume a study as shown [in the documentation](https://optuna.readthedocs.io/en/stable/faq.html?highlight=joblib#how-can-i-save-and-resume-studies)

But let's say my experiment gets killed in the middle of trial 5. I want to resume trial 5 exactly where it left off, so I need to load the original hyperparameters associated with trial 5. Is there a way of doing that?

I believe the following will cause trial 5 to resume with different hyperparameters:

```python
study = joblib.load("study.pkl")
study.optimize(objective)
```

(Note, I save the study after every trial using the ```callbacks``` argument of ```study.optimize```)

**Comment by Crissman** [comment]
@KevinMusgrave This case is addressed with the new [RetryFailedTrialCallback](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.storages.RetryFailedTrialCallback.html).

Please close this issue if that addresses it. Thanks!

**Comment by KevinMusgrave** [comment]
I think that should probably do it, thanks!
