### ISSUE TITLE
Multi objective task

### ISSUE THREAD

**Issue by zzzbobml** [optuna/optuna#2706]
Hello,
could you, please, provide a reference to the algorithm used for multi objective optimization?
Thank you,

**Comment by nzw0301** [comment]
As a default sampler for multi-objective trial, [`NSGAIISampler`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.samplers.NSGAIISampler.html) is used. The reference is on the page: https://ieeexplore.ieee.org/document/996017.
