### ISSUE TITLE
Autoformatting command's parameter change in CONTRIBUTING.md.

### ISSUE THREAD

**Issue by 01-vyom** [optuna/optuna#2708]
Issue with `CONTRIBUTING.md`

While running the command for installing autoformatters `$ pip install .[checking]` , I get the following error:
`no matches found: .[checking]`

When I run the following command:  `$ pip install -e ".[checking]"`, it works correctly.

## Environment
- Optuna version: 2.8.0.dev
- Python version: 3.8.5
- OS: Ubuntu 20.04

**Comment by nzw0301** [comment]
I suppose that it works with `bash`.  But it does not work with `zsh`. I agree with your suggestion -- `"` should be added.

**Comment by nzw0301** [comment]
If you are interested in sending a pull request, please go ahead!

**Comment by 01-vyom** [comment]
Yes, I am using `zsh` and in `bash` it worked fine. Will make a PR.
