### ISSUE TITLE
ordering trials with n_jobs>1

### ISSUE THREAD

**Issue by zzzbobml** [optuna/optuna#2720]
When `n_jobs` is greater than 1, for example, `n_jobs=4`, it seems optuna is not waiting for the batch of trials to finish before deciding where to sample next.  

How do the results differ versus using `n_jobs=1`?

**Comment by Crissman** [comment]
n_jobs is deprecated due to issues with the Python GIL. Process parallelization works better: https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html#distributed

Closing this issue since it deals with deprecated parameter. 🙇
