### ISSUE TITLE
Delete some existing useless trials in the study

### ISSUE THREAD

**Issue by guangmingjian** [optuna/optuna#2740]
Under special circumstances, some useless trials will be left behind, and we hope to delete them, for example, failed, terminated process, repeated trials,  and so on.

Is there a way to delete according to trial id？ Thank you!

**Comment by Crissman** [comment]
Deleting the trials removes history, which we generally avoid. One approach this would be filter out the `Fail` or `Running` trials by `TrialState` once the study is complete.

Another approach would be to create a new study, and then add the successful trials manually, using `Study.add_trials` if you want a clean history.

Does either of those work?

**Comment by guangmingjian** [comment]
thx
