### ISSUE TITLE
How to report trial as failed?

### ISSUE THREAD

**Issue by pyscorcher** [optuna/optuna#2742]
Let's assume we e.g. stop a training in a distributed setting using `Crtl+C`. Then the state is still recorded as `RUNNING` in the database. But as far as I understand, if we use `TPESampler(constant_liar=True)` then these still influence the future samples.

Now Is it possible to e.g. use a `try-catch` block for `KeyboardInterrupt` and set the interrupted trial to `FAIL` such that it doesn't influence future samples? Or is there another solution or do I maybe misunderstand something?

**Comment by nzw0301** [comment]
[`tell`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.tell) can report the trial state as `FAIL` manually. So I suppose that is possible.

**Comment by pyscorcher** [comment]
@nzw0301 thank you very much, I now use the ask & tell interface and it works fine!
