### ISSUE TITLE
Empty plots with optuna.visualization in Jupyterlab even after following plotly installation instructions

### ISSUE THREAD

**Issue by aartdvark** [optuna/optuna#2744]
optun.visualization plot functions produce empty plots in Jupyterlab.

I followed the guide in the documentation (`pip install "jupyterlab>=3" "ipywidgets>=7.6"`), but the issue persists.

![image](https://user-images.githubusercontent.com/42552319/121692760-5136a780-cac0-11eb-9891-bbc793c1ebd1.png)

## Environment

- Optuna version: 2.7.0
- Plotly: 2.7.0
- jupyter core: 4.7.1
- jupyter lab: 3.0.16

System:
    python: 3.6.13 |Anaconda, Inc.| (default, Feb 23 2021, 21:15:04)  [GCC 7.3.0]
executable: /anaconda/envs/azureml_py36/bin/python
   machine: Linux-5.4.0-1046-azure-x86_64-with-debian-buster-sid

## Error messages, stack traces, or logs

None.

## Steps to reproduce

```
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

X, y = load_iris(return_X_y=True)

def objective(trial):

    clf_estimator=RandomForestClassifier()
    
    score = cross_val_score(clf_estimator, X, y, cv=StratifiedKFold(2), n_jobs=-1)
    score = score.mean()
    return score

study = optuna.create_study(direction="maximize")
study.optimize(objective, n_trials=10)

optuna.visualization.plot_optimization_history(study)
```

**Comment by nzw0301** [comment]
Could you check this duplicated issue https://github.com/optuna/optuna/issues/837?

**Comment by aartdvark** [comment]
@nzw0301 This solved the issue! I didn't see this particular instruction on the thread you referenced. Have I missed it?
