### ISSUE TITLE
is percentilepruner not useful for moving average use case ?

### ISSUE THREAD

**Issue by externalsupplierstaff** [optuna/optuna#2747]
Hello,

**my use case**
My problem is the following, I have a function of some params I want to optimize according to the results over a database of images. This is, for each set of parameters, I want to evaluate my function. The result of the evaluation is the average of the individual errors over each image.

It's crucial to note that, as it is a moving average, statistics tell us that we approximate the final error without bias and with a standard deviation decreasing as 1/\sqrt{N}, where N is the number of evaluated images. Furthermore, I don't shuffle the database, and the results are generally well defined after a few steps (see image below, with almost no crossing lines and a clear winner)
![image](https://user-images.githubusercontent.com/84398715/122090581-32118000-ce08-11eb-8b7a-f8962277ff39.png)

**first problem: requires pruning**
The problem is that, as the database is large, evaluating bad parameters is a waste of time. To avoid this, I report the rolling mean and use PercentilePruner. However, this pruner will run a whole evaluation before starting pruning any trial, and as seen in the image above, it's obvious one could prune trials way before full completion of any of them.

To do this, I hardcoded a warmup that breaks the evaluation loop after n steps (n=4). This is, this trial is supposed to have been not pruned but completed in a smaller number of evaluations. The metric I return is increased substantially in order to make optuna ignore these warmup trials when looking at the end result. 

**second (MAIN) problem: unfair pruning**
running this, optuna correctly respects my hardcoded warmup trials, but the first trial outside the warmup phase goes for full evaluation with terrible parameters. I didn't understand this, so I went to the source code and voila, the comparison is done between `best_intermediate_result` and `_get_percentile...(all_trials, direction, step...)`, which is clearly unfair because *the best result between all images is compared with the rolling mean*.

I think one would expect the comparison to be done step by step. Why is this not the case? Where is this use case (that I would expect to be relatively common) contemplated?

Please correct my logic or ask for clarification if needed

**Comment by nzw0301** [comment]
Could you share the code?

**Comment by externalsupplierstaff** [comment]
Note that I corrected `optuna/pruners/_percentile.py` around line 202 with the following
```python
        direction = study.direction
        best_intermediate_result = _get_best_intermediate_result_over_steps(trial, direction)
        # hardcode
        best_intermediate_result = np.asarray(list(trial.intermediate_values.values()), dtype=float)[step]
        # end hardcode
        if math.isnan(best_intermediate_result):
            return True
```
Now the scripts: (non reproducible, won't send the whole code and database). 
`optuna.py` (main script)
```python
import os
import time
import pickle
from exploration.ipol_optimization.common.fitter import IpolFitter


STUDY_NAME = f"ace_study_{time.time()}.pickle"


class ACEFitter(IpolFitter):
    def __init__(
        self,
        n_trials,
        timeout,
        verbose=True,
        n_imgs=9999999,
        warmup={"trials": 0, "steps_per_trial": 10},
    ):
        super().__init__(
            n_trials, timeout, "ace", verbose=verbose, n_imgs=n_imgs, warmup=warmup
        )

    def save_study(self):
        with open(
            os.path.join(
                r"C:\Users\f84188285\huawei\code\exploration\ipol_optimization\ace\runs",
                STUDY_NAME,
            ),
            "wb",
        ) as f:
            pickle.dump(self.study, f)

    def optuna_get_next_parameter(self, trial):
        self.save_study()
        param_w_switch = trial.suggest_categorical("w_type", ["1/r", "1", "G:"])
        if "G:" in param_w_switch:
            param_w = "G:" + str(trial.suggest_int("sigma", 1, 1000, log=True))
        else:
            param_w = param_w_switch
        params = {
            "param_a": trial.suggest_float("param_a", 1, 8),
            "param_w": param_w,
        }
        return params


if __name__ == "__main__":
    # run
    acefitter = ACEFitter(100000, 50000, warmup={"trials": 3, "steps_per_trial": 2}, verbose=True)
    best_params = acefitter.get_best_params()
    acefitter.save_study()
    print("-" * 20)
```

`fitter.py`
```python
import glob
from pathlib import Path

import matplotlib.pyplot as plt
import optuna

from workflow.evaluation.metrics import Lp_distance_in_Lab_from_rgb
from workflow.enhancement_algorithms.ipol import ipol_algorithm_wrapper_from_path
from exploration.distort_and_recover.utils import minmaxnorm


class OptunaFitter:
    def __init__(
        self,
        n_trials,
        timeout,
        img_path_list,
        evaluate_fn,
        direction="minimize",
        verbose=True,
        warmup={"trials": 0, "steps_per_trial": 10},
    ):
        self.n_trials, self.timeout = n_trials, timeout
        self.evaluate = evaluate_fn
        self.direction = direction
        self.enh_function = self.get_enh_function(
            params=None
        )  # default, untrained model
        self.img_path_list = img_path_list
        self.verbose = verbose
        self.warmup_count = 0
        self.warmup_steps_per_trial = warmup["steps_per_trial"]
        self.warmup_trials = warmup["trials"]

    def load_img(self, img_path):
        img = minmaxnorm(plt.imread(img_path))
        assert (0 <= img.min()) and (img.max() <= 1)
        return img

    def optuna_objective(self, trial):
        self.warmup_count += 1
        warmup_mode = True
        if self.warmup_trials < self.warmup_count:
            self.warmup_count = 0  # "warm up" again
            self.warmup_steps_per_trial *= 2


        params = self.optuna_get_next_parameter(trial)
        if self.verbose:
            print('-'*30)
            print("using params", params)
        enh_function = self.get_enh_function(params)
        rolling_mean = 0
        for i, img_path in enumerate(self.img_path_list):
            out_img = enh_function(img_path)
            img = self.load_img(img_path)
            diff = self.evaluate(out_img, img)
            rolling_mean = (rolling_mean * i + diff) / (i + 1)
            trial.report(rolling_mean, i)
            if self.verbose:
                print(i, "| rolling mean:", rolling_mean)
                print("-" * 30)

            if trial.should_prune():
                if self.verbose:
                    print("pruning trial")
                self.warmup_count -= 1  # don't count if pruned
                raise optuna.TrialPruned()

            if warmup_mode:
                if i + 1 == self.warmup_steps_per_trial:
                    # rolling_mean += 10
                    break
                    # raise optuna.TrialPruned()
                


        return rolling_mean

    def get_best_params(self):
        self.study = optuna.create_study(
            direction=self.direction,
            sampler=optuna.samplers.TPESampler(seed=0),
            pruner=optuna.pruners.PercentilePruner(
                percentile=50,
                n_startup_trials=self.warmup_trials-1,
                n_warmup_steps=self.warmup_steps_per_trial-1,
                n_min_trials=3,
            ),
        )
        self.study.optimize(
            self.optuna_objective, n_trials=self.n_trials, timeout=self.timeout
        )
        return self.study.best_trial.params

    def optuna_get_next_parameter(self, trial):
        raise NotImplementedError

    def get_enh_function(self, params=None):
        raise NotImplementedError


class IpolFitter(OptunaFitter):
    def __init__(
        self,
        n_trials,
        timeout,
        algorithm_name,
        verbose=True,
        n_imgs=99999999,
        warmup={"trials": 0, "steps_per_trial": 10},
    ):
        evaluate_fn = Lp_distance_in_Lab_from_rgb
        img_path_list = [
            Path(path)
            for path in sorted(
                glob.glob(r"C:\Users\f84188285\huawei\data\C\val\raw\*.jpg")
            )
        ]
        n_imgs = max(0, min(n_imgs, len(img_path_list) - 1))
        img_path_list = img_path_list[:n_imgs]
        super().__init__(
            n_trials=n_trials,
            timeout=timeout,
            img_path_list=img_path_list,
            evaluate_fn=evaluate_fn,
            direction="minimize",
            verbose=verbose,
            warmup=warmup,
        )
        self.algorithm_name = algorithm_name

    def get_enh_function(self, params):
        return lambda input_path: minmaxnorm(
            ipol_algorithm_wrapper_from_path(
                input_path, self.algorithm_name, algo_kwargs=params, return_dict=False
            )
        )
```

**Comment by nzw0301** [comment]
Sorry for the delayed response and thank you for sharing the code. I got your points. 

## 1. requires pruning

If this is the case, we can stop the optimisation depending on the trial id before reaching the end of evaluations rather than change the optuna code directly. For example, during the first 5 times, we can return the evaluation value when we evaluate 10% of images in the database in `objective` using just python's `if` statement! 

## 2. second (MAIN) problem: unfair pruning

Technically, the reason is [this line](https://github.com/optuna/optuna/blob/c41f60dd8093ab1aa281f9925ca3e86e45c518a6/optuna/pruners/_percentile.py#L41); if the intermediate values at the `step` in previous trials do not exist at all, then the current optimisation goes to the end by default. So the comparison logic does not relate to that.

I think the comparison logic makes sense. We can find many use-cases where users use `MedianPruner` in their optimisation problem.

If optuna's pruners are not suitable for your optimisation problem, then you can define your own pruner by following [the tutorial](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/006_user_defined_pruner.html). I suppose you are already familiar with optuna's pruner logic, so it might be an easy way to deal with the problem.


Best regards,

**Comment by nzw0301** [comment]
This issue does not look active anymore and I believe that my previous comment addressed the original question. So let me close this issue.
