### ISSUE TITLE
How can I extract evaluation history (eval_hist) from LightGBMTunerCV?

### ISSUE THREAD

**Issue by nbkn865** [optuna/optuna#2750]
According to the LightGBMTunerCV documentation (https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTunerCV.html), LightGBMTunerCV invokes lightgbm.cv() for training.

lightgbm.cv() returns eval_hist, a dictionary that stores the evaluation history.  However, I can't find any documentation in LightGBMTunerCV of how to extract that.

So, my question is, is it possible to get the evaluation history in lightgbm.cv() from LightGBMTunerCV?

I can't find any method call in LightGBMTunerCV that would do that, or any property in LightGBMTunerCV that stores that.

I would like to be able to plot and visualize the evaluation history of all the models built in LightGBMTunerCV, thanks!

**Comment by nbkn865** [comment]
Can someone help me add a "question" label to this question?  I can't add labels to this question for some reason, and I fear it is being filtered out as a result

**Comment by nbkn865** [comment]
Thank you @nzw0301!

**Comment by nzw0301** [comment]
Hi, sorry for the late response. Unfortunately, the short answer is no.

I read the source code of `LightGBMTunerCV` and I think [these lines](https://github.com/optuna/optuna/blob/c2e528a3f2b8d67075cec117ecc964601f609cc3/optuna/integration/_lightgbm_tuner/optimize.py#L320-L343) are related to your question. Internally, `lightgbm.cv()`'s return value is not stored except for summarised validation value: `val_score ` and `return_cvbooster`.

**Comment by nbkn865** [comment]
Thank you @nzw0301!

**Comment by nbkn865** [comment]
I will try to figure out a workaround
