### ISSUE TITLE
Saving a study locally 

### ISSUE THREAD

**Issue by dianemarquette** [optuna/optuna#2751]
Hi !

From what I read in the `optuna.study.create_study` [documentation](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.create_study.html#optuna-study-create-study), the `storage` parameter only takes a database URL as input. Is there a way to persist a study locally? (I'm already using MLflow to log my metrics and model parameters, could it help?)

Thanks for your input :)

**Comment by nzw0301** [comment]
Do you mean that you save a study instance? If so, yes, you can as [this FAQ section]( https://optuna.readthedocs.io/en/stable/faq.html#how-can-i-save-and-resume-studies).

**Comment by dianemarquette** [comment]
Hi @nzw0301!

Thanks for your quick reply. I'm using the Optuna sweeper [plugin](https://hydra.cc/docs/plugins/optuna_sweeper) from Hydra. Therefore, I don't easily have access to the study instance. That's why I was wondering whether there was a way to make the `storage` paramater (that I can set with this plugin) compatible with a local storage.

**Comment by nbkn865** [comment]
@dianemarquette, not familiar with Hydra, but it looks like a Python package, and it looks like there's a parameter for Optuna storage.  Given that, have you tried using the built-in SQLite database in Python?

From a Python call, you can set an Optuna study to store in SQLite that resides locally on whatever path your script is on.

For example:

study_name = "my_study"
storage_name = f"sqlite:///{study_name}.db"
study = optuna.create_study(study_name=study_name, storage=storage_name, load_if_exists=True)

This will create a file called my_study.db in the directory of your Python script that stores the study

You can then query it's results the following method call that creates a pandas dataframe:

df = study.trials_dataframe()  # Get all columns of study


Based on the above, and using the Hydra documentation, maybe you can try the following parameter for `storage` and `study_name`:

sampler:
  _target_: optuna.samplers.TPESampler
  seed: 123
...
  warn_independent_sampling: true
_target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
direction: minimize
storage: sqlite:///my_test_study.db
study_name: my_test_study

**Comment by dianemarquette** [comment]
@nbkn865 Thanks for your input :). I wasn't aware of the built-in SQLite database in Python that can run locally. I'm going to try to implement your solution 👍🏻

**Comment by nbkn865** [comment]
You're welcome, I hope it works!
