### ISSUE TITLE
Running a multiobjective function and I'm maximizing 12 values

### ISSUE THREAD

**Issue by LeparaLaMapara** [optuna/optuna#2758]
My objective functions return a list of 12 values and I want to maximize each value in the list. But I get this error 

`Trial 21 failed, because the number of the values 12 does not match the number of the objectives 1.`

**Comment by nzw0301** [comment]
Could you give a minimal reproducible code? Otherwise, could you double-check the objective values return 12 values?

**Comment by nzw0301** [comment]
Let me close the issue since we haven't been seen the update for while. But, please feel free to re-open the issue.
