### ISSUE TITLE
Does sampler behavior changes depending n_trials of study?

### ISSUE THREAD

**Issue by dmasmont** [optuna/optuna#2771]
Not sure if this has been asked before:

Should I expect different results when running:  `study.optimize(..., n_trials=1)`  **(n_trials=1)** a total of **N** times (with the same study object) VS when running once `study.optimize(..., n_trials=N)`  **(n_trials=N)**? Do any of the samplers use the value of n_trials for any of their computations?

If they are a difference between both approaches, is there an easy way to store the study object (e.g. in a pickle) after every trial?

Thanks!

**Comment by Crissman** [comment]
@dmasmont In general, as long as the trial history is visible in the storage, there wouldn't be a difference in running study.optimize multiple times vs. once with multiple trials.

If that answers your question, please close this issue. 🙇
