### ISSUE TITLE
Build dedicated Python Package for `try_import()`

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#2776]
Dear Optuna team,

I very much like your `try_import()` utility from here: https://github.com/optuna/optuna/blob/99484054fcec97eb530960a8612c3e6058ee5690/optuna/_imports.py

I would like to use that kind of functionality in other Python Packages that we want to develop.
But that package does not have an optuna dependency. That's why I ask:

Do you plan to release that as an utility package that can be reused by other packages?

If not I would like to inform you that I am creating such a package and open source it under 
the same MIT License.

**Comment by PhilipMay** [comment]
@hvy

**Comment by hvy** [comment]
Sorry for the late reply. Appreciate you checking.

Creating an independent library sounds interesting. I could see it being applicable to other applications as you say. Unfortunately, there's no plan for the time being in doing so. `try_import` was mostly implemented as a quick internal/private tool to DRY code. There might be room for improving the API, or perhaps even including other related features such as the [lazy submodule import helper](https://github.com/optuna/optuna/blob/v2.8.0/optuna/integration/__init__.py#L67-L103).

Having that said, I don't see problems in you creating a library deriving it given your description (e.g. the MIT license). If you don't mind, mentioning Optuna would be very much appreciated, though.

**Comment by PhilipMay** [comment]
> perhaps even including other related features such as the lazy submodule import helper.

That is an great idea! Thanks.

> Having that said, I don't see problems in you creating a library deriving it given your description (e.g. the MIT license). 

Yes. I very much prefer MIT!

> If you don't mind, mentioning Optuna would be very much appreciated, though.

Yes, of course, that is a matter of course.

**Comment by PhilipMay** [comment]
I did a first development release:
- https://github.com/telekom/lazy-imports
- https://pypi.org/project/lazy-imports/

@hvy Almost 10 sec. later I discovered this: https://github.com/mnmelo/lazy_import

Did you already know this? Could it possibly fully cover your functionality?

**Comment by hvy** [comment]
Great, thanks for the heads up. 

And no, I had unfortunately not heard of this library... It does indeed look like it could cover the use cases. Our `try_import` is again really simple, just that we're currently wrapping the errors trying to make it user friendly. I'm not sure this is provided by the library that you referenced. On a side note, it looks like the development has become a bit stale so it might still be worth working on your library, although I'd in general prefer sticking to existing technology.

**Comment by PhilipMay** [comment]
> although I'd in general prefer sticking to existing technology.

Yes. That's exactly the dilemma I'm in now.

**Comment by PhilipMay** [comment]
Turned the project to private again to clarify which way to go.

**Comment by PhilipMay** [comment]
Thanks again. We have published the try_import functionality here:
https://github.com/telekom/lazy-imports

Although we took the _LazyModule class from HuggingFace. This implementation somehow worked better for us.

**Comment by PhilipMay** [comment]
Closing this.
