### ISSUE TITLE
Does Optuna support pruner when use mysql to run dist tuing.

### ISSUE THREAD

**Issue by zwqjoy** [optuna/optuna#2797]
Does Optuna support pruner when use mysql to run dist tuing?

Now I use the optuna with njobs, so every train process have the trial ojbect. 
But If I want use mysql to run dist tuning in different node, How can I use pruner ?

**Comment by nzw0301** [comment]
Hi, I think so by specifying the same MySQL among nodes.

**Comment by zwqjoy** [comment]
> Hi, I think so by specifying the same MySQL among nodes.

@nzw0301 USE mysql among node,  the pruner still can work ?

**Comment by nzw0301** [comment]
Yes

**Comment by nzw0301** [comment]
As in [the tutorial](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html), Optuna supports distributed optimisation using multiple processes on either the same node or nodes. If we specify the same MySQL from each process, then pruner still works based on the optimisation history stored in the MySQL database.

By the way, `n_jobs` is the thread-based parallelisation, not the process-based one.

**Comment by nzw0301** [comment]
I believe my answer addresses the question. Let me close this issue.
