### ISSUE TITLE
Help us create the next version of Optuna!

### ISSUE THREAD

**Issue by Crissman** [optuna/optuna#2800]
Please take a few minutes to fill in this survey, and let us know how you use Optuna now and what improvements you'd like.🤔
All questions optional. 🙇‍♂️
https://forms.gle/mCAttqxVg5oUifKV8

**Comment by profPlum** [comment]
Hello @Crissman & Optuna team, please see my [proposal for a simpler parallelism implementation](https://github.com/optuna/optuna/issues/3328#issue-1147540916). I believe my suggestion is a solution to [a problem Optuna Dev's have already identified](https://github.com/optuna/optuna/wiki/Optuna-V3-Roadmap#name-consider-storage-that-can-be-easily-used-with-multi-process-2950).

**Comment by hvy** [comment]
We'll close the survey for now since it's been active for some time. Thanks a lot to everyone who participated and shared their experiences and thoughts.
