### ISSUE TITLE
RuntimeError: The runtime optuna version 2.8.0 is no longer compatible with the table schema (set up by optuna 2.8.0). Please try updating optuna to the latest version by `$ pip install -U optuna`.

### ISSUE THREAD

**Issue by Zakhar17** [optuna/optuna#2812]
## Expected behavior

I am trying to use MySQL DB as the Optuna storage, however when trying to create the study (optuna.create_study(... , storage=link_to_db, load_if_exists=True)) I receive the following error: RuntimeError: The runtime optuna version 2.8.0 is no longer compatible with the table schema (set up by optuna 2.8.0). Please try updating optuna to the latest version by `$ pip install -U optuna`. 

I tried to install and uninstall optuna, create a new venv, recreate DB but it doesn't help. Have no idea what to do. Perhaps, some problems may be with installed packages. When trying to run the code for the first time there was an error that there is no module MySQLdb. However, installing this package didn't help with the error. I googled -  this package is for Python 2. So I installed mysqlclient package for my Python 3.8.10. The code went further but then I get the error above and can't find anything on it in google.

Thank you for any help!

## Environment

- Optuna version: 2.8.0
- Python version: 3.8.10
- OS: Ubuntu 20.04.2 LTS
- (Optional) Other libraries and their versions:
alembic==1.4.1
attrs==21.2.0
certifi==2021.5.30
charset-normalizer==2.0.2
click==8.0.1
cliff==3.8.0
cloudpickle==1.6.0
cmaes==0.8.2
cmd2==2.1.2
colorama==0.4.4
colorlog==5.0.1
databricks-cli==0.14.3
docker==5.0.0
entrypoints==0.3
Flask==2.0.1
gitdb==4.0.7
GitPython==3.1.18
greenlet==1.1.0
gunicorn==20.1.0
idna==3.2
itsdangerous==2.0.1
Jinja2==3.0.1
joblib==1.0.1
lightgbm==3.2.1
Mako==1.1.4
MarkupSafe==2.0.1
mlflow==1.19.0
mysqlclient==2.0.3
numpy==1.21.0
optuna==2.8.0
packaging==21.0
pandas==1.3.0
pbr==5.6.0
prettytable==2.1.0
prometheus-client==0.11.0
prometheus-flask-exporter==0.18.2
protobuf==3.17.3
pyparsing==2.4.7
pyperclip==1.8.2
python-dateutil==2.8.2
python-editor==1.0.4
pytz==2021.1
PyYAML==5.4.1
querystring-parser==1.2.4
requests==2.26.0
scikit-learn==0.24.2
scipy==1.7.0
six==1.16.0
smmap==4.0.0
SQLAlchemy==1.4.21
sqlparse==0.4.1
stevedore==3.3.0
tabulate==0.8.9
threadpoolctl==2.2.0
tqdm==4.61.2
urllib3==1.26.6
wcwidth==0.2.5
websocket-client==1.1.0
Werkzeug==2.0.1
xgboost==1.4.2

## Error messages, stack traces, or logs
File "/home/dev0007/Projects/automl/optuna_mlflow/optuna_mlflow_new_venv/lib/python3.8/site-packages/optuna/study.py", line 1137, in create_study
    storage = storages.get_storage(storage)
  File "/home/dev0007/Projects/automl/optuna_mlflow/optuna_mlflow_new_venv/lib/python3.8/site-packages/optuna/storages/__init__.py", line 29, in get_storage
    return _CachedStorage(RDBStorage(storage))
  File "/home/dev0007/Projects/automl/optuna_mlflow/optuna_mlflow_new_venv/lib/python3.8/site-packages/optuna/storages/_rdb/storage.py", line 186, in __init__
    self._version_manager.check_table_schema_compatibility()
  File "/home/dev0007/Projects/automl/optuna_mlflow/optuna_mlflow_new_venv/lib/python3.8/site-packages/optuna/storages/_rdb/storage.py", line 1330, in check_table_schema_compatibility
    raise RuntimeError(message)
RuntimeError: The runtime optuna version 2.8.0 is no longer compatible with the table schema (set up by optuna 2.8.0). Please try updating optuna to the latest version by `$ pip install -U optuna`.
```
# error messages, stack traces, or logs
```

## Steps to reproduce

1.
2.
3.

## Reproducible examples (optional)

```python
# python code
```

**Comment by himkt** [comment]
Hello @Zakhar17.

Could you please give us the output of `SELECT * FROM version_info;' on your MySQL database? When connecting DB, please use the same configuration as `link_to_db` you specified in Python.
