### ISSUE TITLE
How to catch special type of error in optimize

### ISSUE THREAD

**Issue by LeZhengThu** [optuna/optuna#2815]
Hi, I'm using Optuna to optimize the hyperparameters of the LSTM policy in stable baselines. With some hyperparameters combination, the LSTM gradient blows out and throws an InvalidArgumentError. Then the whole optimization process stopped. So I use the code ``` study.optimize(objective, n_trials=100, catch=(InvalidArgumentError,)) ```, trying to test other hyperparameters . And I get an error ``` NameError: name 'InvalidArgumentError' is not defined```. I wonder how to skip the error, or just simply skip all the errors with the catch argument.

**Comment by nzw0301** [comment]
did you import `InvalidArgumentError`?

**Comment by LeZhengThu** [comment]
@nzw0301  No, InvalidArgumentError is an exception raised by tensorflow. How can I import InvalidArgumentError?
