### ISSUE TITLE
Can optimization function be defined as a class method?

### ISSUE THREAD

**Issue by sokol11** [optuna/optuna#2819]
Hi. Thanks so much for developing such a great library. I was wondering if I can define the optimize function as a class method that is called my another method of the same class and gets the `self` passed to it, like so:
```
class OptimizerClass:
    def optimization_function(self, trial):
        if self.some_attribute:
            param = trial.suggest_int('param', min, max)
        else:
            param = # something else    
        return self.evaluate_optimization_function(param)

    def run(self):
        study = optuna.create_study()
        study.optimize(self.optimization function)
```
I saw in the docs that one can define the optimization function itself as a class, but I was wondering if we were allowed to define it as a class method. Thank you!

**Comment by himkt** [comment]
Hello @sokol11,

I think a naive implementation looks like:

```python
import optuna


class OptimizerClass:
    @staticmethod
    def objective_function(x):
        return (x - 2) ** 2

    @staticmethod
    def run_trial(trial):
        x = trial.suggest_float("x", -10, 10)
        return OptimizerClass.objective_function(x)

    def run(self):
        study = optuna.create_study()
        study.optimize(self.run_trial, n_trials=100)
        print(study.trials_dataframe())


optimizer = OptimizerClass()
optimizer.run()
```

Because `run_trial()` is implemented as a class method (it doesn't access `self`),
I invoke `objective_function` directly from the class name. It looks somehow hacky, I think.

You can also use the ask-and-tell interface (https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/009_ask_and_tell.html).
Using ask-and-tell, the above code could be rewritten as follows:

```python
import optuna


class OptimizerClass:
    def __init__(self):
        pass

    @staticmethod
    def objective_function(x):
        return (x - 2) ** 2

    def run_trial(self, trial):
        x = trial.suggest_float("x", -10, 10)
        return self.objective_function(x)

    def run(self):
        study = optuna.create_study()

        n_trials = 100
        for trial_number in range(n_trials):
            trial = study.ask()
            study.tell(trial, self.run_trial(trial))


optimizer = OptimizerClass()
optimizer.run()
```

**Comment by sokol11** [comment]
Hi @himkt Thanks so much. Your example looks like it would work great for my use case. This is super helpful! Closing this.
