### ISSUE TITLE
attribute error in importing optuna

### ISSUE THREAD

**Issue by kaussie-k** [optuna/optuna#2825]
I'm using jupyter environment.
Optuna got successfully installed.
While importing it gives error:
AttributeError: 'Version' object has no attribute 'major'

packaging is updated to latest version 21.0

> Full error:
AttributeError                            Traceback (most recent call last)
<ipython-input-207-deb984238a1b> in <module>
----> 1 import optuna

~\Anaconda3\lib\site-packages\optuna\__init__.py in <module>
      6 from optuna import distributions
      7 from optuna import exceptions
----> 8 from optuna import importance
      9 from optuna import integration
     10 from optuna import logging

~\Anaconda3\lib\site-packages\optuna\importance\__init__.py in <module>
      4 from typing import Optional
      5 
----> 6 from optuna.importance._base import BaseImportanceEvaluator
      7 from optuna.importance._fanova import FanovaImportanceEvaluator
      8 from optuna.importance._mean_decrease_impurity import MeanDecreaseImpurityImportanceEvaluator

~\Anaconda3\lib\site-packages\optuna\importance\_base.py in <module>
      7 
      8 from optuna.distributions import BaseDistribution
----> 9 from optuna.samplers import intersection_search_space
     10 from optuna.study import Study
     11 from optuna.trial import FrozenTrial

~\Anaconda3\lib\site-packages\optuna\samplers\__init__.py in <module>
----> 1 from optuna.samplers._base import BaseSampler
      2 from optuna.samplers._cmaes import CmaEsSampler
      3 from optuna.samplers._grid import GridSampler
      4 from optuna.samplers._nsga2 import NSGAIISampler
      5 from optuna.samplers._partial_fixed import PartialFixedSampler

~\Anaconda3\lib\site-packages\optuna\samplers\_base.py in <module>
      6 
      7 from optuna.distributions import BaseDistribution
----> 8 from optuna.study import Study
      9 from optuna.trial import FrozenTrial
     10 from optuna.trial import TrialState

~\Anaconda3\lib\site-packages\optuna\study.py in <module>
    208 
    209 
--> 210 class Study(BaseStudy):
    211     """A study corresponds to an optimization task, i.e., a set of trials.
    212 

~\Anaconda3\lib\site-packages\optuna\study.py in Study()
    985         return None
    986 
--> 987     @deprecated("2.5.0")
    988     def _ask(self) -> trial_module.Trial:
    989         return self.ask()

~\Anaconda3\lib\site-packages\optuna\_deprecated.py in deprecated(deprecated_version, removed_version, name, text)
     83     _validate_version(deprecated_version)
     84     if removed_version is None:
---> 85         removed_version = _get_removed_version_from_deprecated_version(deprecated_version)
     86     _validate_version(removed_version)
     87     _validate_two_version(deprecated_version, removed_version)

~\Anaconda3\lib\site-packages\optuna\_deprecated.py in _get_removed_version_from_deprecated_version(deprecated_version)
     45     parsed_deprecated_version = version.parse(deprecated_version)
     46     assert isinstance(parsed_deprecated_version, version.Version)  # Required for mypy.
---> 47     return "{}.0.0".format(parsed_deprecated_version.major + 2)
     48 
     49 

AttributeError: 'Version' object has no attribute 'major'

**Comment by himkt** [comment]
Hello @kaussie-k, could you please try upgrading `packaging` (`pip install -U packaging`)?

ref. https://github.com/optuna/optuna/pull/1599

**Comment by IloBe** [comment]
Hi all,
working with a jupyter notebook I have got the same symptom with 'import optuna'
by using Anaconda3 on a Windows 10 PC with firefox v90 and AMD64
Requirement for packaging is satisfied according installation message of optuna (v21.0).

python 3.7.0
ipython 7.6.1
pandas 1.0.3
lightgbm 2.3.1
xgboost 1.0.2
shap 0.39.0

As well, there is a deprecated message in optuna/study/study.py

Please, what can I do to use optuna appropriately?
Help is appreciated!

**AttributeError: 'Version' object has no attribute 'major'**

Details:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-469-deb984238a1b> in <module>
----> 1 import optuna

C:\ProgramData\Anaconda3\lib\site-packages\optuna\__init__.py in <module>
      6 from optuna import distributions
      7 from optuna import exceptions
----> 8 from optuna import importance
      9 from optuna import integration
     10 from optuna import logging

C:\ProgramData\Anaconda3\lib\site-packages\optuna\importance\__init__.py in <module>
      4 from typing import Optional
      5 
----> 6 from optuna.importance._base import BaseImportanceEvaluator
      7 from optuna.importance._fanova import FanovaImportanceEvaluator
      8 from optuna.importance._mean_decrease_impurity import MeanDecreaseImpurityImportanceEvaluator

C:\ProgramData\Anaconda3\lib\site-packages\optuna\importance\_base.py in <module>
      7 
      8 from optuna.distributions import BaseDistribution
----> 9 from optuna.samplers import intersection_search_space
     10 from optuna.study import Study
     11 from optuna.trial import FrozenTrial

C:\ProgramData\Anaconda3\lib\site-packages\optuna\samplers\__init__.py in <module>
----> 1 from optuna.samplers._base import BaseSampler
      2 from optuna.samplers._cmaes import CmaEsSampler
      3 from optuna.samplers._grid import GridSampler
      4 from optuna.samplers._nsga2 import NSGAIISampler
      5 from optuna.samplers._partial_fixed import PartialFixedSampler

C:\ProgramData\Anaconda3\lib\site-packages\optuna\samplers\_base.py in <module>
      6 
      7 from optuna.distributions import BaseDistribution
----> 8 from optuna.study import Study
      9 from optuna.trial import FrozenTrial
     10 from optuna.trial import TrialState

C:\ProgramData\Anaconda3\lib\site-packages\optuna\study\__init__.py in <module>
      2 from optuna.study._study_direction import StudyDirection
      3 from optuna.study._study_summary import StudySummary
----> 4 from optuna.study.study import BaseStudy
      5 from optuna.study.study import copy_study
      6 from optuna.study.study import create_study

C:\ProgramData\Anaconda3\lib\site-packages\optuna\study\study.py in <module>
    207 
    208 
--> 209 class Study(BaseStudy):
    210     """A study corresponds to an optimization task, i.e., a set of trials.
    211 

C:\ProgramData\Anaconda3\lib\site-packages\optuna\study\study.py in Study()
    984         return None
    985 
--> 986     @deprecated("2.5.0")
    987     def _ask(self) -> trial_module.Trial:
    988         return self.ask()

C:\ProgramData\Anaconda3\lib\site-packages\optuna\_deprecated.py in deprecated(deprecated_version, removed_version, name, text)
     83     _validate_version(deprecated_version)
     84     if removed_version is None:
---> 85         removed_version = _get_removed_version_from_deprecated_version(deprecated_version)
     86     _validate_version(removed_version)
     87     _validate_two_version(deprecated_version, removed_version)

C:\ProgramData\Anaconda3\lib\site-packages\optuna\_deprecated.py in _get_removed_version_from_deprecated_version(deprecated_version)
     45     parsed_deprecated_version = version.parse(deprecated_version)
     46     assert isinstance(parsed_deprecated_version, version.Version)  # Required for mypy.
---> 47     return "{}.0.0".format(parsed_deprecated_version.major + 2)
     48 
     49 

AttributeError: 'Version' object has no attribute 'major'

**Comment by lferrado** [comment]
I'm having the exact same error, even having upgraded to `packaging==21.0`. Is there a solution for this? 

```
============================= test session starts ==============================

platform linux -- Python 3.7.4, pytest-6.2.5, py-1.10.0, pluggy-0.13.1 -- /usr/local/bin/python3

cachedir: .pytest_cache

rootdir: /app, configfile: setup.cfg, testpaths: tests/unit

plugins: bdd-4.0.2, cov-2.11.1, mock-3.6.1, hydra-core-1.1.0, typeguard-2.12.1

collecting ... collected 39 items / 1 error / 38 selected



==================================== ERRORS ====================================

____________ ERROR collecting tests/unit/test_core_training_xgb.py _____________

tests/unit/test_core_training_xgb.py:6: in <module>

    import optuna

/usr/local/lib/python3.7/site-packages/optuna/__init__.py:8: in <module>

    from optuna import importance

/usr/local/lib/python3.7/site-packages/optuna/importance/__init__.py:6: in <module>

    from optuna.importance._base import BaseImportanceEvaluator

/usr/local/lib/python3.7/site-packages/optuna/importance/_base.py:9: in <module>

    from optuna.samplers import intersection_search_space

/usr/local/lib/python3.7/site-packages/optuna/samplers/__init__.py:1: in <module>

    from optuna.samplers._base import BaseSampler

/usr/local/lib/python3.7/site-packages/optuna/samplers/_base.py:8: in <module>

    from optuna.study import Study

/usr/local/lib/python3.7/site-packages/optuna/study.py:207: in <module>

    class Study(BaseStudy):

/usr/local/lib/python3.7/site-packages/optuna/study.py:912: in Study

    @deprecated("2.5.0")

/usr/local/lib/python3.7/site-packages/optuna/_deprecated.py:78: in deprecated

    removed_version = _get_removed_version_from_deprecated_version(deprecated_version)

/usr/local/lib/python3.7/site-packages/optuna/_deprecated.py:40: in _get_removed_version_from_deprecated_version

    return "{}.0.0".format(parsed_deprecated_version.major + 2)

E   AttributeError: 'Version' object has no attribute 'major'
```

**Comment by himkt** [comment]
@IloBe @lferrado Hmm, I'm wondering there are multiple versions of `packaging`.
Could you try removing packaging and re-installing.

If it doesn't solve anything, I want to know the following steps to replicate.
(It would be a shell script to install Optuna and upgrade packaging, etc)

**Comment by lferrado** [comment]
@himkt I've just checked the same, and apparently another dependency downgraded packaging from 21.0 to 19.2. So I solved the problem by ensuring that `packaging==21.0` before running the tests. Thanks for the help!

**Comment by himkt** [comment]
Ah, OK. Happy to hear!

**Comment by IloBe** [comment]
@himkt Being a little bit late, but I uninstalled everything and tried it again according your proposal. It worked for me as well. Thanks for help too!

**Comment by himkt** [comment]
Nice! So, I close this issue. Feel free to reopen if you need.
