### ISSUE TITLE
Changing a `suggest_uniform` call trigger an error in plot_param_importances when `params` argument given.

### ISSUE THREAD

**Issue by jeremycochoy** [optuna/optuna#2827]
If the database (I use the potgresql backend for storing trials) contains entries:
```
598|61|x|51.0|{"name": "IntUniformDistribution", "attributes": {"low": 20, "high": 100, "step": 1}}
608|62|x|63.0|{"name": "IntUniformDistribution", "attributes": {"low": 30, "high": 120, "step": 1}}
```

then using `suggest_uniform(study, params=['x'])` raise a `ValueError: Parameters importances cannot be assessed with dynamic search spaces if parameters are specified. Specified parameters: ['x'].`.

I have to manually edit the entries in the database to low:20, high:120 to fix the issue. :(

It would be nice if the plotting function could do this kumfu by itself :)

**Comment by nzw0301** [comment]
Thank you for creating the issue! According to the error message, I suppose that the behaviour is intended, so let me change the label to `feature`.

At least, it would be great to give a note to explain the dynamical range is not supported by `plot_param_importances`.

----

Let me put a minimal example to see the error message.

```python
import optuna


def objective(trial):
    x = trial.suggest_int("x", 0, trial.number)
    y = trial.suggest_float("y", -1.0, 1.0)
    z = trial.suggest_float("z", 0.0, 1.5)
    return x ** 2 + y ** 3 - z ** 4


sampler = optuna.samplers.RandomSampler(seed=10)
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=10)

optuna.visualization.plot_param_importances(study, params=["x"])
```

**Comment by jeremycochoy** [comment]
@nzw0301  Thanks. I didn't understood the error message at first and it took me some time to understand it was caused by a change in the range (I wanted to help optuna to focus on a different search space where I know I can expect better performance). My first research lead me to why changing the arguments in suggest_categorical() can be a problem (use. of index to refer to values).

Indeed it sounds more like a feature. Maybe this could implemented as an optional (opt-in) argument to ask plot_param_importances to create a unique range covering the multiple values? Curious to read your opinion on how you would do it.

**Comment by nzw0301** [comment]
Unfortunately, I don't understand the algorithm behind the importance calculation such as [this](http://proceedings.mlr.press/v32/hutter14.html), so I'm not sure it might be possible :(
 
I think @hvy has implemented this feature. What do you think about the feature request: can we accept the dynamic range's parameter space to calculate the importance score?

**Comment by hvy** [comment]
I'm wondering if this previous discussion doesn't address the topic here https://github.com/optuna/optuna/issues/1856#issuecomment-703935388. A PR was worked on but unfortunately got stale.
