### ISSUE TITLE
Implement Simultaneous Perturbation Stochastic Approximation Sampler

### ISSUE THREAD

**Issue by brethvoice** [optuna/optuna#2831]
Please add SPSA algorithm and consider making it the base sampler.

## Motivation

The SPSA is an intelligent method of sampling based on previous iterations, and does not require a long "burn in" period.  For example, it can begin optimization after only two observations.

## Description

It is currently implemented in MATLAB code available at:
https://www.jhuapl.edu/SPSA/Pages/MATLAB.htm

## Alternatives (optional)

There is currently an update called "second order SPSA" available from James Spall:
https://www.jhuapl.edu/SPSA/PDF-SPSA/zhu_spall_IJACSP.pdf

**Comment by nzw0301** [comment]
Hi, thank you for your interesting suggestion. Could you know some paper or any resource that comparing an SPSA algorithm and at least one of the algorithms provided by Optuna such as TPE or CmaEs sampler for hyper-parameter optimisation or black-box optimisation problem?

**Comment by brethvoice** [comment]
No @nzw0301 I was suggesting SPSA as a replacement for the base.  Perhaps that was too much.  I definitely am not aware of any comparisons between SPSA and anything that uses pseudo-random methods, except in this one case, and the point of the paper was not to compare them: https://www.sciencedirect.com/science/article/abs/pii/S2213397614000457

**Comment by brethvoice** [comment]
> No @nzw0301 I was suggesting SPSA as a replacement for the base. Perhaps that was too much. I definitely am not aware of any comparisons between SPSA and anything that uses pseudo-random methods, except in this one case, and the point of the paper was not to compare them: https://www.sciencedirect.com/science/article/abs/pii/S2213397614000457

There was only one tidbit of language comparing SPSA, CMA-ES, and genetic algorithm:
"All algorithms converge to the solution within several iterations, but CMA-ES yields slightly higher optimal value and obtains it with smaller uncertainty than the other two algorithms...
"SPSA's advantage becomes apparent in this test suite: SPSA requires the smallest number of the simulator calls and total computation time.  CMA-ES performs slightly better than GA: CMA-ES gives higher improved NPV and requires smaller number of iterations to converge to the optimal results because it has the covariance matrix to control the new generation direction and evolution paths."

**Comment by nzw0301** [comment]
Thank you for sharing the reference. I'm still curious that it is worth adding the algorithm to Optuna's sampler family because we cannot draw the conclusion that the algorithm is better than others somehow from only one paper. So at least, the following steps are supposed to be necessary to move forward

1. implement the algorithm minimally
2. compare the algorithm and other algorithms using [kurobako](https://github.com/optuna/kurobako), which is a benchmark tool for black-box optimisation

**Comment by brethvoice** [comment]
Sorry, I do not have time to look into this.  Closing the issue.
