### ISSUE TITLE
Redis Compatibility

### ISSUE THREAD

**Issue by Turakar** [optuna/optuna#2841]
Improve the compatibility of the redis storage backend between versions.

## Motivation

With the update from 2.8.0 to 2.9.0 import paths changed, which led to incompatibility of old redis databases at unpickling. Additionally, there is no schema migration if we ever change the way we use the keys.

## Description

I see two main ways for tackling the binary compatibility problem:

1. Replace pickle with a different serialization protocol that is cross-version compatible. Benchmarking would be required here to ensure that the new protocol is comparable in speed - after all, the main feature of the Redis database is its low latency from my experience.
2. [Fix pickle imports in a migration step.](https://stackoverflow.com/a/2121918)

And two main ways for tackling the schema compatibility problem:

1. Add a schema migration process similar to the RDBs that operates in place, possibly with the help of an appropriate library.
2. Load the data using the old model, copy it to an InMemoryStorage, switch to the new model, drop all keys, and copy it back to database.

## Alternatives (optional)

The current workaround: Copy the studies to an RDB with the old version, do the migration if applicable, and copy back.

**Comment by himkt** [comment]
So sorry for not responding your issue @Turakar. We don't afford to prepare migration scripts for all storages right now.
Please continue the workaround to migrate a schema through `RDBStorage`.
