### ISSUE TITLE
Add Spark (PySpark) support for distributed optimization

### ISSUE THREAD

**Issue by candalfigomoro** [optuna/optuna#2843]
I propose to add support for Spark (PySpark) for massively parallel hyperparameter optimization.

## Motivation

When a Spark cluster is available, it can be used for massive parallelization of the hyperparameters search in order to speedup hyperparameter optimization.

There had been some proposals to use joblibspark, but Optuna dropped joblib (see https://github.com/optuna/optuna/issues/1381#issuecomment-772365885).

## Description

It should be possible to distribute trials to different Spark worker nodes.

## Alternatives (optional)

- the hyperopt package provides a SparkTrials class for Spark support (see http://hyperopt.github.io/hyperopt/scaleout/spark/).
- a simple random search without Optuna

**Comment by candalfigomoro** [comment]
@HideakiImamura 
Any idea how it might be designed?

**Comment by bstuddard** [comment]
Also interested in this. It looks like hyperopt was able to use sparktrials, I wonder if optuna could do something similar. 

http://hyperopt.github.io/hyperopt/scaleout/spark/

**Comment by WaterKnight1998** [comment]
Hi, any news on this? What about using an embedded DB in Spark Driver and connecting Workers to it?

**Comment by gonzalogarcia-dd** [comment]
![image](https://user-images.githubusercontent.com/96131955/198114779-41782bd4-ac5f-4f31-bd8e-cd7f47f5dc0b.png)

**Comment by nzw0301** [comment]
Optuna is an OSS. If you would like to use such a feature, you can send a pull request to Optuna or create a third-party library like https://github.com/jrbourbeau/dask-optuna.
