### ISSUE TITLE
optuna.create_study() persistence a in local file system 

### ISSUE THREAD

**Issue by zollen** [optuna/optuna#2848]
Is it possible for optuna.create_study() to persistence a file in a local window 10 file system. I found it surprising it support only the SQLAlchemy database, but no other option.

**Comment by nzw0301** [comment]
I suppose the following FAQ section answers your question to save the study without RDB.
https://optuna.readthedocs.io/en/stable/faq.html#how-can-i-save-and-resume-studies

**Comment by zollen** [comment]
Thanks!!!!!!!!!!!!! It works!!! I love optuna!
