### ISSUE TITLE
Visualization (plot_contou) different after upgrading db from optuna 2.4 to 2.9.1

### ISSUE THREAD

**Issue by andife** [optuna/optuna#2858]
Upgrading the sqlite db from optuna 2.4 to 2.9.1 results in a different visualization using
optuna.visualization.matplotlib.plot_contour(study)

## Expected behavior

The images should look quite similiar

## Environment

- Optuna version: 2.9.1 (2.4)

- Python version:
- OS: ubuntu 18.04
- (Optional) Other libraries and their versions:

## Error messages, stack traces, or logs

```
# error messages, stack traces, or logs
```

## Steps to reproduce

1.
2.
3.

## Reproducible examples (optional)

```python
# python code
```

## Additional context (optional)

![optuna_bug](https://user-images.githubusercontent.com/20612932/129552001-de581b1b-fe55-4bd0-995b-654d9378e3ba.PNG)

**Comment by nzw0301** [comment]
This is not a bug. We've replaced the interpolation as in https://github.com/optuna/optuna/pull/2712. We note that, in the next version, the interpolation method becomes quite similar to Plotly's version.
