### ISSUE TITLE
Ticklabels too small / not consistent using matplotlib.plot_contour

### ISSUE THREAD

**Issue by andife** [optuna/optuna#2859]
The x/yticklabel size in the Contour_plot is not consistent. It is smaller at the images 2,3, 5,6
when is image is composed of three variables and visualized as

1 2 3
4 5 6
7 8 9

## Expected behavior

All labels should have the same size

## Environment

- Optuna version: 2.9.1
- Python version:
- OS:
- (Optional) Other libraries and their versions:

## Error messages, stack traces, or logs

```
# error messages, stack traces, or logs
```

## Steps to reproduce

1.
2.
3.

## Reproducible examples (optional)

```python
# python code
```

## Additional context (optional)

![labelsize_optuna](https://user-images.githubusercontent.com/20612932/129552796-3d80c9ca-adf3-4349-bbb7-edf4e88b1762.PNG)

**Comment by nzw0301** [comment]
More precisely, as you can see in the figure, xticklabels and yticklabels are common among columns and rows, respectively. So 2, 3, 5, and 6 as in your example do not have labels.
