### ISSUE TITLE
Adding features for the surrogate model

### ISSUE THREAD

**Issue by FelixNeutatz** [optuna/optuna#2860]
Hi everybody,

I am thinking about giving hints to the surrogate model by adding additional features. My idea is to provide an additional function that generates more features.

```
import optuna
import numpy as np

def generate_additional_features(trial):
    my_list = []
    for i in range(5):
        my_list.append(trial.paramaters['f' + str(i)])

    return np.sum(my_list) > 10

def opt(trial):
    my_list = []
    for i in range(5):
        my_list.append(trial.suggest_int('f'+str(i), 0, 5))

    if np.sum(my_list) > 10:
        return 0

    return np.product(my_list)

study = optuna.create_study(direction='maximize')
study.optimize(opt, feature_transformation=generate_additional_features, n_trials=200)
print(study.best_value)
```
Is there any way to do this?

Best regards,
Felix

**Comment by nzw0301** [comment]
I could not understand the question. Could you explain a little bit more?

**Comment by FelixNeutatz** [comment]
Sure, lets say we have 5 hyperparameters and a constraint based on these hyperparameters. In my example, the constant is a simple aggregate of the hyperparameters: np.sum(my_list) > 10.
So, if we could add this constraint as an additional feature for the surrogate model, then TPE would quickly learn that this constraint should be satisfied and it will not suggest any configuration that violates the constraint.
However, if we do not provide such a feature, it is extremely hard for TPE to learn that "np.sum(my_list) > 10" always leads to poor performance and would require significantly more runs to learn this constraint.

So, my question is whether there is any way to pass a feature transformation function that builds more features based on the given hyperparameters.

I hope this explanation is more clear. Please let me know if anything is not clear yet.

**Comment by FelixNeutatz** [comment]
I also tried the following approach:

```
import optuna
import numpy as np

def opt(trial):
    my_list = []
    for i in range(5):
        my_list.append(trial.suggest_int('f'+str(i), 0, 5))
        
    trial.suggest_int('constraint', np.sum(my_list) > 10, np.sum(my_list) > 10)

    if np.sum(my_list) > 10:
        return 0

    return np.product(my_list)

study = optuna.create_study(direction='maximize')
study.optimize(opt, n_trials=200)
print(study.best_value)
```
This way the surrogate model knows the constraint but cannot access it during the acquisition function :(

Does anybody have an idea?

**Comment by nzw0301** [comment]
To introduce a constraint, I'll use either `NSGAIISampler` or `BoTorchSampler` rather than TPE since we cannot impose a constraint on TPE.

**Comment by FelixNeutatz** [comment]
ok thank you, I will try it :)

**Comment by nzw0301** [comment]
For `NSGAIISampler `, [`Constrained NSGA-II`](https://github.com/optuna/optuna/releases/tag/v2.5.0) gives an example code of constrained optimisation. I hope this is also helpful for your use case!
