### ISSUE TITLE
Parallel optimization for sklearn using joblib for multiprocessing

### ISSUE THREAD

**Issue by AlexisMignon** [optuna/optuna#2862]
It would be convenient to have a `multiprocessing` based parallelization directly available in the `sklearn` wrapper.

## Motivation

At the moment (version 2.9.1), in the `sklearn` wrapper, the `n_jobs` attributes of `OptunaSearchCV` maps to the `n_jobs` attribute of `optuna.optimize` which uses `multithreading` and as such is submitted to the Python GIL. A `multiprocessing` based parallelization would be an important feature to accelerate computations.

## Description

Some preliminary tests show that it could be possible to implement, with least  effort, a `multiprocessing` based parallelization based on `joblib`.

I've tested the following code:

```python
def objective(trial: optuna.trial.Trial):
    time.sleep(0.05)
    x = trial.suggest_uniform("x", -1, 1)
    y = trial.suggest_uniform("y", -1, 1)
    return (x ** 2 + y ** 2)
```
And tried tested the execution time for the three following snippets:

1. Single threaded
```python
study = optuna.create_study(storage="sqlite:///./test.db", direction="minimize")
study.optimize(objective, n_trials=200)
len(study.get_trials())
```
2. Multi threaded

```python
study = optuna.create_study(storage="sqlite:///./test.db", direction="minimize")
study.optimize(objective, n_jobs=8, n_trials=200)
len(study.get_trials())
```

3. with joblib 
```python
def optimize_study(study_name, storage, objective, n_trials):
    study = optuna.create_study(study_name=study_name, storage=storage, load_if_exists=True)
    study.optimize(objective, n_trials=n_trials)

storage_string = "sqlite:///./test.db"
study = optuna.create_study(storage=storage_string, direction="minimize")

joblib.Parallel(8)(
    joblib.delayed(optimize_study)(study.study_name,
                                  storage_string,
                                  objective, n_trials=25)
    for i in range(8)
)
len(study.get_trials())
```

On my i7 machine, this leads each time to the expected 200 trials and the execution times (using `timeit`) were respectively:

1. 39.0 +- 0.3s
2. 20.1 +- 0.4s
3. 15.0 +- 0.4s

**Comment by AlexisMignon** [comment]
A small wrapper like this could so the job:

```python
import optuna

class JoblibStudy:
    def __init__(self, **study_parameters):
        self.study_parameters = study_parameters
        self.study: optuna.study.Study = optuna.create_study(**study_parameters)

    def _optimize_study(self, func, n_trials, **optimize_parameters):
        study_parameters = copy.copy(self.study_parameters)
        study_parameters["study_name"] = self.study.study_name
        study_parameters["load_if_exists"] = True
        study = optuna.create_study(**study_parameters)
        study.optimize(func, n_trials=n_trials, **optimize_parameters)
        
    @staticmethod
    def _split_trials(n_trials, n_jobs):
        n_per_job, remaining = divmod(n_trials, n_jobs)
        for i in range(n_jobs):
            yield n_per_job + (1 if remaining > 0 else 0)
            remaining -= 1

    def optimize(self, func, n_trials=1, n_jobs=-1, **optimize_parameters):
        if n_jobs == -1:
            n_jobs = joblib.cpu_count()

        if n_jobs == 1:
            self.study.optimize(n_trials=n_trials, **optimize_parameters)
        else:
            parallel = joblib.Parallel(n_jobs)
            parallel(
                joblib.delayed(self._optimize_study)(func, n_trials=n_trials_i, **optimize_parameters)
                for n_trials_i in self._split_trials(n_trials, n_jobs)
            )
            
    def __getattr__(self, name):
        if not name.startswith("_") and hasattr(self.study, name):
            return getattr(self.study, name)
        else:
            raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")
```
Could be used like:

```python
def objective(trial):
    x = trial.suggest_uniform("x", -1, 1)
    y = trial.suggest_uniform("y", -1, 1)
    return (x + y) ** 2
            
jlstudy = JoblibStudy(storage=storage_string)
jlstudy.optimize(objective, n_trials=200, n_jobs=8)
len(jlstudy.get_trials())

**Comment by AtomScott** [comment]
I like the simplicity of number 3, thanks.

**Comment by matt-nann** [comment]
`
import optuna
import joblib
import copy
import numpy as np
import random
import uuid
import scipy.spatial as ss
import matplotlib.pyplot as plt
from functools import partial
from src.logger import logger
import time
import math

logger.initialize(False, False, False, False, False, False)

STORAGE_ADDRESS = "postgresql://postgres:postgrespw@localhost:55004"

def calcParetoFront(pts):
    """
    https://stackoverflow.com/questions/32791911/fast-calculation-of-pareto-front-in-python
    """
    'returns Pareto efficient row subset of pts'
    # sort points by decreasing sum of coordinates
    pts = pts[pts.sum(1).argsort()[::-1]]
    # initialize a boolean mask for undominated points
    # to avoid creating copies each iteration
    undominated = np.ones(pts.shape[0], dtype=bool)
    for i in range(pts.shape[0]):
        # process each point in turn
        n = pts.shape[0]
        if i >= n:
            break
        # find all points not dominated by i
        # since points are sorted by coordinate sum
        # i cannot dominate any points in 1,...,i-1
        undominated[i+1:n] = (pts[i+1:] >= pts[i]).any(1) 
        # keep points undominated so far
        pts = pts[undominated[:n]]
    return pts

def calculateParetoVolume(paretoPts):
    paretoVolumePts = paretoPts.max(axis=0) * np.identity(paretoPts.shape[1])
    paretoVolumePts = np.concatenate((paretoVolumePts, paretoPts, np.zeros((1, paretoPts.shape[1]))), axis=0)
    paretoVolumePts = np.unique(paretoVolumePts, axis=0)
    if paretoVolumePts.shape[0] < 3:
        return 0
    hull = ss.ConvexHull(paretoVolumePts)
    return hull.volume

def early_stopping_opt(study, trial, EarlyStop, BAD_TRIALS_FOR_STOP = 10, VOLUME_INCREASE = 0.005):
    # having the volume slowly decrease than drop off is normal behavior because it the objective values are negative anytime the pareto front is updated while removing
    isSingleObjective = not study._is_multi_objective()
    newBestTrial = np.array([trial.value]) if isSingleObjective else np.array([t.values for t in study.best_trials])
    if EarlyStop.paretoFront.shape[0] == 0:
        EarlyStop.paretoFront = newBestTrial
        return
    if isSingleObjective:
        improved = newBestTrial[0] > EarlyStop.paretoFront[0]
    else:
        oldMin = EarlyStop.paretoFront.min(axis=0)
        newMin = newBestTrial.min(axis=0)
        if np.all(oldMin < 0) or np.all(newMin < 0):
            origin = np.vstack((oldMin, newMin)).min(axis=0)    
            currVol = calculateParetoVolume(EarlyStop.paretoFront - origin)
            newVol = calculateParetoVolume(newBestTrial - origin)
        else:
            currVol = calculateParetoVolume(EarlyStop.paretoFront)
            newVol = calculateParetoVolume(newBestTrial)
        improved = currVol == 0 or (newVol - currVol) / currVol > VOLUME_INCREASE

    if improved:
        EarlyStop.paretoFront = newBestTrial
        EarlyStop.early_stop_count = 0
    else:
        if EarlyStop.early_stop_count > BAD_TRIALS_FOR_STOP:
            EarlyStop.early_stop_count = 0
            raise EarlyStop()
        else:
            EarlyStop.early_stop_count += 1
    return

class ParallelStudyEarlyStop:
    """
    from https://github.com/optuna/optuna/issues/2862
    """
    def __init__(self, BAD_TRIALS_FOR_STOP = 10, VOLUME_INCREASE = 0.005, NUM_RANDOM_STARTS = 1, **study_parameters):
        self.study_parameters = study_parameters
        self.NUM_RANDOM_STARTS = max(NUM_RANDOM_STARTS, 1)
        self.study: optuna.study.Study = optuna.create_study(**study_parameters)
        self.earlyStopCallback = partial(early_stopping_opt, BAD_TRIALS_FOR_STOP=BAD_TRIALS_FOR_STOP, VOLUME_INCREASE=VOLUME_INCREASE)

    def _optimize_study(self, func, n_trials, studyName, **optimize_parameters):
        class EarlyStop(optuna.exceptions.OptunaError): # needs to be within a single job's optimization or else the EarlyStop class is shared
            early_stop_count = 0
            paretoFront = np.array([])
            volume = 0
        # logger.log_debug("Optimizing", studyName, "with", n_trials, "trials")
        study_parameters = copy.copy(self.study_parameters)
        study_parameters["study_name"] = studyName
        study_parameters["load_if_exists"] = True
        study = optuna.create_study(**study_parameters)
        trialIds = []
        # multiple jobs can work on the same random start, thus the study.trials will collect the trials from multiple jobs
        # to prevent from trials from being added multiple times, a callback saves the trial numbers that this job worked on and only adds its own trials
        def saveCallback(study, trial):
            trialIds.append(trial.number)
        try:
            study.optimize(func, n_trials=n_trials, **optimize_parameters, callbacks=[partial(self.earlyStopCallback, EarlyStop=EarlyStop), saveCallback])
        except EarlyStop:
            raise
        for trial in study.trials:
            if trial.number not in trialIds:
                continue
            self.study.add_trial(trial) 

    def optimize(self, func, trialsPerStart=1, n_jobs=-1, **optimize_parameters):
        if n_jobs > 12:
            raise ValueError("decrease number of jobs, 12 jobs seems like the upper limit before the postsql server doesn't like having that many clients")
        startTime = time.time()
        if n_jobs == -1:
            n_jobs = joblib.cpu_count()
        names = [(trialsPerStart, self.study.study_name + "_UUID:" + str(uuid.uuid4()))  for _ in range(self.NUM_RANDOM_STARTS)]
        # names = [(trialsPerStart, str(_))  for _ in range(self.NUM_RANDOM_STARTS)] # simple names for easy debugging
        if self.NUM_RANDOM_STARTS < n_jobs:
            rounds = [n_jobs]
            names = names * (n_jobs // self.NUM_RANDOM_STARTS) + names[:n_jobs % self.NUM_RANDOM_STARTS]
            finalNames = []
            for name in set(names):
                jobsForName = names.count(name)
                numTrials = [trialsPerStart // jobsForName] * (jobsForName)
                # evenly distribute remainder of trials over the jobs assigned to that random start
                for i in range(trialsPerStart % jobsForName): 
                    numTrials[i] += 1
                numTrials = [n for n in numTrials if n > 0]
                finalNames += [(numTrials[i], name[1]) for i in range(len(numTrials))]
            names = finalNames
        elif self.NUM_RANDOM_STARTS > n_jobs:
            # evenly distributing number of jobs per round to satisfy number of random starts
            bins = math.ceil(self.NUM_RANDOM_STARTS / n_jobs)
            rounds = [0 for _ in range(bins)]
            for i in range(self.NUM_RANDOM_STARTS):
                rounds[i % bins] += 1
        else:
            rounds = [n_jobs]

        doneJobs = 0
        for i, n_jobs in enumerate(rounds):
            parallel = joblib.Parallel(n_jobs, prefer="threads") 
            # no idea what really is going on, but this doesn't work without prefer="threads" when using internal dependencies https://joblib.readthedocs.io/en/latest/parallel.html
            parallel(
                joblib.delayed(self._optimize_study)(func, n_trials=trials, studyName = name, **optimize_parameters)
                for trials, name in names[doneJobs:doneJobs+n_jobs]
            )
            logger.log_debug(200,"round ",i," ", ", ".join([str(name) + ": " + str(trials) + " trials " for trials, name in names[doneJobs:doneJobs+n_jobs]]))
            doneJobs += n_jobs

        for name in names:
            try:
                optuna.delete_study(study_name=name, storage=STORAGE_ADDRESS)
            except:
                ...
        timeElapsed = time.time() - startTime 
        logger.log(200,f"Optimization finished in {timeElapsed:.2f} seconds with {len(self.study.trials)} trials")

    def __hasattr__(self, name):
        if not name.startswith("_") and hasattr(self.study, name):
            return True
        else:
            return False

    def __getattr__(self, name):
        if not name.startswith("_") and hasattr(self.study, name):
            return getattr(self.study, name)
        else:
            raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")
        
def example():
    NUM_RANDOM_STARTS = 13
    BAD_TRIALS_FOR_STOP = 100
    VOLUME_INCREASE = 0.005
    n_jobs = 3
    trialsPerStart = 10
    studyName = "temp"

    def BUKIN_FUNCTION_N6(x1,x2):
        ab=np.fabs(x2-0.01*x1*x1)
        a=-100*np.sqrt(ab)+0.01*np.fabs(x1+10)
        return a
    def objective(trial):
        x = trial.suggest_float("x", -15, -5)
        y = trial.suggest_float("y", -3, 3)
        return BUKIN_FUNCTION_N6(x,y) 
    try:
        optuna.delete_study(study_name=studyName, storage=STORAGE_ADDRESS)
        logger.log_debug(200, "deleted old study")
    except:
        pass
    jlstudy = ParallelStudyEarlyStop(storage=STORAGE_ADDRESS, study_name=studyName, directions=['maximize'], 
        BAD_TRIALS_FOR_STOP = BAD_TRIALS_FOR_STOP, VOLUME_INCREASE = VOLUME_INCREASE, NUM_RANDOM_STARTS = NUM_RANDOM_STARTS)
    # logger.log_debug("Starting optimization")
    jlstudy.optimize(objective, trialsPerStart=trialsPerStart, n_jobs=n_jobs)

`

**Comment by matt-nann** [comment]
I added a few features on to @AlexisMignon that I found particularly helpful. Mainly I added the ability to specify a number of random starts as many objective functions such as BUKIN_FUNCTION_N6 are heavily dependent on starting location. Also I added in early stopping. Cheers, hope this helps someone!

```
import optuna
import joblib
import copy
import numpy as np
import random
import uuid
import scipy.spatial as ss
import matplotlib.pyplot as plt
from functools import partial
from src.logger import logger
import time
import math

logger.initialize(False, False, False, False, False, False)

STORAGE_ADDRESS = "postgresql://postgres:postgrespw@localhost:55004"

def calcParetoFront(pts):
    # sort points by decreasing sum of coordinates
    pts = pts[pts.sum(1).argsort()[::-1]]
    # initialize a boolean mask for undominated points
    # to avoid creating copies each iteration
    undominated = np.ones(pts.shape[0], dtype=bool)
    for i in range(pts.shape[0]):
        # process each point in turn
        n = pts.shape[0]
        if i >= n:
            break
        # find all points not dominated by i
        # since points are sorted by coordinate sum
        # i cannot dominate any points in 1,...,i-1
        undominated[i+1:n] = (pts[i+1:] >= pts[i]).any(1) 
        # keep points undominated so far
        pts = pts[undominated[:n]]
    return pts

def calculateParetoVolume(paretoPts):
    paretoVolumePts = paretoPts.max(axis=0) * np.identity(paretoPts.shape[1])
    paretoVolumePts = np.concatenate((paretoVolumePts, paretoPts, np.zeros((1, paretoPts.shape[1]))), axis=0)
    paretoVolumePts = np.unique(paretoVolumePts, axis=0)
    if paretoVolumePts.shape[0] < 3:
        return 0
    hull = ss.ConvexHull(paretoVolumePts)
    return hull.volume

def early_stopping_opt(study, trial, EarlyStop, BAD_TRIALS_FOR_STOP = 10, VOLUME_INCREASE = 0.005):
    # having the volume slowly decrease than drop off is normal behavior because it the objective values are negative anytime the pareto front is updated while removing
    isSingleObjective = not study._is_multi_objective()
    newBestTrial = np.array([trial.value]) if isSingleObjective else np.array([t.values for t in study.best_trials])
    if EarlyStop.paretoFront.shape[0] == 0:
        EarlyStop.paretoFront = newBestTrial
        return
    if isSingleObjective:
        improved = newBestTrial[0] > EarlyStop.paretoFront[0]
    else:
        oldMin = EarlyStop.paretoFront.min(axis=0)
        newMin = newBestTrial.min(axis=0)
        if np.all(oldMin < 0) or np.all(newMin < 0):
            origin = np.vstack((oldMin, newMin)).min(axis=0)    
            currVol = calculateParetoVolume(EarlyStop.paretoFront - origin)
            newVol = calculateParetoVolume(newBestTrial - origin)
        else:
            currVol = calculateParetoVolume(EarlyStop.paretoFront)
            newVol = calculateParetoVolume(newBestTrial)
        improved = currVol == 0 or (newVol - currVol) / currVol > VOLUME_INCREASE

    if improved:
        EarlyStop.paretoFront = newBestTrial
        EarlyStop.early_stop_count = 0
    else:
        if EarlyStop.early_stop_count > BAD_TRIALS_FOR_STOP:
            EarlyStop.early_stop_count = 0
            raise EarlyStop()
        else:
            EarlyStop.early_stop_count += 1
    return

class ParallelStudyEarlyStop:
    def __init__(self, BAD_TRIALS_FOR_STOP = 10, VOLUME_INCREASE = 0.005, NUM_RANDOM_STARTS = 1, **study_parameters):
        self.study_parameters = study_parameters
        self.NUM_RANDOM_STARTS = max(NUM_RANDOM_STARTS, 1)
        self.study: optuna.study.Study = optuna.create_study(**study_parameters)
        self.earlyStopCallback = partial(early_stopping_opt, BAD_TRIALS_FOR_STOP=BAD_TRIALS_FOR_STOP, VOLUME_INCREASE=VOLUME_INCREASE)

    def _optimize_study(self, func, n_trials, studyName, **optimize_parameters):
        class EarlyStop(optuna.exceptions.OptunaError): # needs to be within a single job's optimization or else the EarlyStop class is shared
            early_stop_count = 0
            paretoFront = np.array([])
            volume = 0
        # logger.log_debug("Optimizing", studyName, "with", n_trials, "trials")
        study_parameters = copy.copy(self.study_parameters)
        study_parameters["study_name"] = studyName
        study_parameters["load_if_exists"] = True
        study = optuna.create_study(**study_parameters)
        trialIds = []
        # multiple jobs can work on the same random start, thus the study.trials will collect the trials from multiple jobs
        # to prevent from trials from being added multiple times, a callback saves the trial numbers that this job worked on and only adds its own trials
        def saveCallback(study, trial):
            trialIds.append(trial.number)
        try:
            study.optimize(func, n_trials=n_trials, **optimize_parameters, callbacks=[partial(self.earlyStopCallback, EarlyStop=EarlyStop), saveCallback])
        except EarlyStop:
            raise
        for trial in study.trials:
            if trial.number not in trialIds:
                continue
            self.study.add_trial(trial) 

    def optimize(self, func, trialsPerStart=1, n_jobs=-1, **optimize_parameters):
        if n_jobs > 12:
            raise ValueError("decrease number of jobs, 12 jobs seems like the upper limit before the postsql server doesn't like having that many clients")
        startTime = time.time()
        if n_jobs == -1:
            n_jobs = joblib.cpu_count()
        names = [(trialsPerStart, self.study.study_name + "_UUID:" + str(uuid.uuid4()))  for _ in range(self.NUM_RANDOM_STARTS)]
        # names = [(trialsPerStart, str(_))  for _ in range(self.NUM_RANDOM_STARTS)] # simple names for easy debugging
        if self.NUM_RANDOM_STARTS < n_jobs:
            rounds = [n_jobs]
            names = names * (n_jobs // self.NUM_RANDOM_STARTS) + names[:n_jobs % self.NUM_RANDOM_STARTS]
            finalNames = []
            for name in set(names):
                jobsForName = names.count(name)
                numTrials = [trialsPerStart // jobsForName] * (jobsForName)
                # evenly distribute remainder of trials over the jobs assigned to that random start
                for i in range(trialsPerStart % jobsForName): 
                    numTrials[i] += 1
                numTrials = [n for n in numTrials if n > 0]
                finalNames += [(numTrials[i], name[1]) for i in range(len(numTrials))]
            names = finalNames
        elif self.NUM_RANDOM_STARTS > n_jobs:
            # evenly distributing number of jobs per round to satisfy number of random starts
            bins = math.ceil(self.NUM_RANDOM_STARTS / n_jobs)
            rounds = [0 for _ in range(bins)]
            for i in range(self.NUM_RANDOM_STARTS):
                rounds[i % bins] += 1
        else:
            rounds = [n_jobs]

        doneJobs = 0
        for i, n_jobs in enumerate(rounds):
            parallel = joblib.Parallel(n_jobs, prefer="threads") 
            # no idea what really is going on, but this doesn't work without prefer="threads" when using internal dependencies https://joblib.readthedocs.io/en/latest/parallel.html
            parallel(
                joblib.delayed(self._optimize_study)(func, n_trials=trials, studyName = name, **optimize_parameters)
                for trials, name in names[doneJobs:doneJobs+n_jobs]
            )
            logger.log_debug(200,"round ",i," ", ", ".join([str(name) + ": " + str(trials) + " trials " for trials, name in names[doneJobs:doneJobs+n_jobs]]))
            doneJobs += n_jobs

        for name in names:
            try:
                optuna.delete_study(study_name=name, storage=STORAGE_ADDRESS)
            except:
                ...
        timeElapsed = time.time() - startTime 
        logger.log(200,f"Optimization finished in {timeElapsed:.2f} seconds with {len(self.study.trials)} trials")

    def __hasattr__(self, name):
        if not name.startswith("_") and hasattr(self.study, name):
            return True
        else:
            return False

    def __getattr__(self, name):
        if not name.startswith("_") and hasattr(self.study, name):
            return getattr(self.study, name)
        else:
            raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")
        
def example():
    NUM_RANDOM_STARTS = 13
    BAD_TRIALS_FOR_STOP = 100
    VOLUME_INCREASE = 0.005
    n_jobs = 3
    trialsPerStart = 10
    studyName = "temp"

    def BUKIN_FUNCTION_N6(x1,x2):
        ab=np.fabs(x2-0.01*x1*x1)
        a=-100*np.sqrt(ab)+0.01*np.fabs(x1+10)
        return a
    def objective(trial):
        x = trial.suggest_float("x", -15, -5)
        y = trial.suggest_float("y", -3, 3)
        return BUKIN_FUNCTION_N6(x,y) 
    try:
        optuna.delete_study(study_name=studyName, storage=STORAGE_ADDRESS)
        logger.log_debug(200, "deleted old study")
    except:
        pass
    jlstudy = ParallelStudyEarlyStop(storage=STORAGE_ADDRESS, study_name=studyName, directions=['maximize'], 
        BAD_TRIALS_FOR_STOP = BAD_TRIALS_FOR_STOP, VOLUME_INCREASE = VOLUME_INCREASE, NUM_RANDOM_STARTS = NUM_RANDOM_STARTS)
    # logger.log_debug("Starting optimization")
    jlstudy.optimize(objective, trialsPerStart=trialsPerStart, n_jobs=n_jobs)
```
