### ISSUE TITLE
Increase number of digits in the decimal part for importances plot

### ISSUE THREAD

**Issue by fsmosca** [optuna/optuna#2868]
![image](https://user-images.githubusercontent.com/22366935/130712277-1afcba0c-cfcd-46ce-a3aa-35f082b646ba.png)

`LMRFactor` could be 0.00125 for example. This would allow comparisons even for smaller values.

**Comment by nzw0301** [comment]
For Plotly graphs, we can see an actual importance score value by placing the mouse cursor over each bar as follows.
<img width="969" alt="Screenshot 2021-08-25 at 17 07 08" src="https://user-images.githubusercontent.com/7121753/130752413-68c0915f-3199-485c-b063-33cb4cf56558.png">

What do you think about this? Is not it enough?

But, personally, I feel that the score value at just right next to each bar looks misleading...

**Comment by fsmosca** [comment]
I saved plots in png format.

**Comment by nzw0301** [comment]
Ok, we can change the number of digits because the plot function returns plotly's plot object:

```python
fig = optuna.visualization.plot_param_importances(study)
fig.data[0]["texttemplate"] = "%{text:.5f}" 
fig.write_image("study.png")
```
