### ISSUE TITLE
Not able to import Optuna library - Import Error

### ISSUE THREAD

**Issue by Avishnaredi77** [optuna/optuna#2874]
So, I am trying to work with the optuna library for a Bayesian regression problem. However, I am not able to import it into my python code.
I have reproduced the error I am facing here.

ImportError Traceback (most recent call last)
in
6 from multiprocessing import Process, Queue
7 import pandas as pd
----> 8 import optuna
9 import matplotlib.pyplot as plt
10 from matplotlib.gridspec import GridSpec

C:\ProgramData\Anaconda3\lib\site-packages\optuna_init_.py in
1 from optuna import config # NOQA
----> 2 from optuna import dashboard # NOQA
3 from optuna import distributions # NOQA
4 from optuna import integration # NOQA
5 from optuna import logging # NOQA

C:\ProgramData\Anaconda3\lib\site-packages\optuna\dashboard.py in
20 import optuna.logging
21 import optuna.structs
---> 22 import optuna.study
23 from optuna import types
24

C:\ProgramData\Anaconda3\lib\site-packages\optuna\study_init_.py in
----> 1 from optuna._callbacks import MaxTrialsCallback
2 from optuna.study._study_direction import StudyDirection
3 from optuna.study._study_summary import StudySummary
4 from optuna.study.study import BaseStudy
5 from optuna.study.study import copy_study

C:\ProgramData\Anaconda3\lib\site-packages\optuna_callbacks.py in
4 import optuna
5 from optuna._experimental import experimental
----> 6 from optuna.trial import FrozenTrial
7 from optuna.trial import TrialState
8

C:\ProgramData\Anaconda3\lib\site-packages\optuna\trial_init_.py in
----> 1 from optuna.trial._base import BaseTrial
2 from optuna.trial._fixed import FixedTrial
3 from optuna.trial._frozen import create_trial
4 from optuna.trial._frozen import FrozenTrial
5 from optuna.trial._state import TrialState

C:\ProgramData\Anaconda3\lib\site-packages\optuna\trial_base.py in
7
8 from optuna.distributions import BaseDistribution
----> 9 from optuna.distributions import CategoricalChoiceType
10
11

ImportError: cannot import name 'CategoricalChoiceType' from 'optuna.distributions' (C:\ProgramData\Anaconda3\lib\site-packages\optuna\distributions.py)

Environment
I am using Windows 10, and working on Jupyter Notebook, as well as using latest versions of both.

**Comment by himkt** [comment]
Hi @Avishnaredi77, could you please tell me versions of Python/Optuna. 

And it is difficult to identify a cause with current information.
Can you share a reproducible code as well?

**Comment by nzw0301** [comment]
Since we could not get additional info for while. Let me close this issue. But please feel free to re-open this issue.
