### ISSUE TITLE
Will Optuna be confused with hyperparameters with same name but different meaning?

### ISSUE THREAD

**Issue by stepthom** [optuna/optuna#2881]
Let's say I want to try both LGBM and XGBoost, each of which have several hyperparemters with the same name:

```python
estimator_name = trial.suggest_categorical("estimator_name", ["lgbm", "xgboost"])

if estimator_name == "lgbm":
  params = {
        "reg_alpha": trial.suggest_loguniform("reg_alpha", 1/1024, 1024),
       # ...

  }
  estimator = LGBMClassifier(**params)
  
elif estimator_name == "xgboost":
  params = {
        "reg_alpha": trial.suggest_loguniform("reg_alpha", 1/1024, 1024),
        # ...
  }
  estimator = XGBClassifier(**params)

estimator.fit( ... )
```

In LGBM and XGBoost, `reg_alpha` have different meanings, since LGBM works at the leaf level and XGBoost works at the feature level. So in this case, different values of `reg_alpha` will have very different effects, depending on the value of `estimator_name`.

Will Optuna be able to handle this properly? Or is there a better way I should be doing this?

(Cross-posted on StackOverflow: https://stackoverflow.com/questions/68976742/will-optuna-be-confused-with-hyperparameters-with-same-name-but-different-meanin)

**Comment by nzw0301** [comment]
How about adding a prefix depending on the library as follows? 

```python

if estimator_name == "lgbm":
  reg_alpha = trial.suggest_loguniform("lgbm_reg_alpha", 1/1024, 1024)
  params = {
        "reg_alpha": reg_alpha,
       # ...
  }
  estimator = LGBMClassifier(**params)
  
elif estimator_name == "xgboost":
  reg_alpha = trial.suggest_loguniform("xgboost_reg_alpha", 1/1024, 1024)
  params = {
        "reg_alpha": reg_alpha,
        # ...
  }
  estimator = XGBClassifier(**params)
```

**Comment by stepthom** [comment]
@nzw0301 I will give it a shot, thank you.

**Comment by nzw0301** [comment]
Let me close the issue because we couldn't get further updates for while. But please feel free to re-open this issue if you have still the issue.
