### ISSUE TITLE
Visualization: custom trial filter

### ISSUE THREAD

**Issue by discochance** [optuna/optuna#2891]
Allow passing a filter function to each visualization call, which filters all trials into those to be plotted. 

## Motivation
Sometimes it is necessary to plot only a subset of all trials. Maybe one is interested in the contour graph of the near surroundings
of the best value, but due to much worse trials existing in the same study, the color code is not detailed enough.
For these cases, a filter function might reduce the trials plotted to only those with small values, resulting in a better resolution.

It might even be important to know the values of pruned trials. A possible example may be an optimization function which
prunes unsuccessful runs, where the plot should show those unsuccessful runs with a predefined value.

## Description
I propose two new optional arguments to each plotting function:
- `filter (Optional[Callable[[optuna.trial._frozen.FrozenTrial], bool]])`: A filtering function which is run on each trial, if it returns true, the trial should be plotted; can be used in combination with `target`
- `plot_all (Optional(bool)`: A flag determining if only  `COMPLETE` trials should be plotted, or if all trials should be plotted. If it is true, the `target` argument is required as no value for `FAILED` or `RUNNING` trials exist.

## Implementation Example:
```python
def _get_contour_plot(
    study: Study,
    params: Optional[List[str]] = None,
    plot_all: Optional[bool] =False,
    filter: Optional[Callable[[FrozenTrial],bool ]] = None,
    target: Optional[Callable[[FrozenTrial], float]] = None,
    target_name: str = "Objective Value",
) -> "go.Figure":

    # New:
    if plot_all is True and target is None:
        raise ValueError("If all trials are plotted, a target function s is necessary")

    layout = go.Layout(title="Contour Plot")

    # Modified:
    trials = [trial for trial in study.trials if trial.state == TrialState.COMPLETE or plot_all]

    # New:
    if filter is not None:
        trials = [trial for trial in trials if filter(trial)]

    [...]
```

## Additional context (optional)
A comparison for plotting only small value-trials versus the same plot with all trials, but zoomed in to roughly the same region.
Unfiltered:
![unfiltered contour plot](https://user-images.githubusercontent.com/6860520/131514539-2a0d51f9-a73e-45c8-a6ea-aa0fea92044e.png)
Filtered value between 0 and 4:
![filtered](https://user-images.githubusercontent.com/6860520/131514635-bcb81c14-cbc4-4a95-8195-2e17cbcb7f1c.png)

### Concerning the plotting of Failed/Pruned Trials:
The algorithm I am optimizing can fail under certain circumstances, which can be influenced by the hyperparameters. In the event of a failure, the trial is pruned by default to save execution time and the user attributes are set accordingly. In the end, it might be interesting to embed failed trials with a  value from the attributes etc., which would neet the `plot_all` functionality.

**Comment by himkt** [comment]
Hello @discochance, we can use `add_trials` for the situation.

We want to keep plot APIs simple so we don't have a plan to add an option to plot APIs.
Instead of adding a filter option to plot APIs, please create a new study and insert trials you want to visualize into it.

```python
import optuna
import sklearn.datasets
import random

def objective(trial):
    iris = sklearn.datasets.load_iris()
    
    n_estimators = trial.suggest_int('n_estimators', 2, 20)
    max_depth = int(trial.suggest_float('max_depth', 1, 32, log=True))
    
    clf = sklearn.ensemble.RandomForestClassifier(
        n_estimators=n_estimators, max_depth=max_depth)
    
    return sklearn.model_selection.cross_val_score(
        clf, iris.data, iris.target, n_jobs=-1, cv=3).mean()

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=100, catch=(Exception,))

# Create study
study_with_filtered_trials = optuna.create_study()

# Filter trials and feed them to the new study
study_with_filtered_trials.add_trials(t for t in study.trials if t.values is not None and t.values[0] < 0.95)  # <- custom filter

# Plot!
optuna.visualization.plot_contour(study_with_filtered_trials)
```

colab example: https://colab.research.google.com/gist/himkt/12217bab433ba6cadfe4cf0f59eabf8c/quickstart.ipynb#scrollTo=8RuId1545n6t

> A flag determining if only COMPLETE trials should be plotted, or if all trials should be plotted. If it is true, the target argument is required as no value for FAILED or RUNNING trials exist.

As far as I understand, trials whose states are FAILED, RUNNING, or PRUNED may not have values.
So I think we cannot plot anything for them.

**Comment by nzw0301** [comment]
For non-completed trials, we can use similar logic to @himkt's suggestion.

```python
PRE_DEFINED_VALUE = 100.

trials = []
for t in study.get_trials():
    if t.state != optuna.trial.TrialState.COMPLETE:
        t.state= optuna.trial.TrialState.COMPLETE
        t.value = PRE_DEFINED_VALUE
    trials.append(t)

other_study = optuna.create_study()
other_study.add_trials(trials)
# call plot function
```

As you know, the non-completed trials are mainly ignored by the plot functions, so we need to update the trial state to plot them.

**Comment by discochance** [comment]
I realized that non-completed trials wouldn't have a value that could be plotted, which is why I suggested requiring the existing `target` feature in that case. But I understand that this feature is not wanted, as the workaround by creating a new study is possible. I thought it would be easier to use, but wrapping the plot call with a new study is possible as well. Thanks for your suggestions!
