### ISSUE TITLE
Add test for `show_progress_bar` of `optimize` method

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2892]
## Motivation

[`optuna.study.Study.optimize` ](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html?highlight=progress_bar#optuna.study.Study.optimize) method has `show_progress_bar` option using [tdqm](https://github.com/tqdm/tqdm). Unfortunately, optuna does not have a test for this functionality. 

## Description

Please add a test for the option to [`tests/study_tests/test_study.py`](https://github.com/optuna/optuna/blob/master/tests/study_tests/test_study.py). tqdm provides a good test example: https://github.com/tqdm/tqdm/blob/140c94855bf98e7e0fda55b040a7a2c8ac76e786/tests/tests_keras.py#L42-L45

**Comment by xadrianzetx** [comment]
I can take it that's ok with you.

**Comment by nzw0301** [comment]
@xadrianzetx  Awesome! Sure! I think at least two test cases are supposed to be necessary depending on `n_jobs`:

1. `n_jobs==1`: check that the progress bar is printed as we expected by following [the example](https://github.com/tqdm/tqdm/blob/140c94855bf98e7e0fda55b040a7a2c8ac76e786/tests/tests_keras.py#L42-L45)
2. `n_jobs!=1`: check that the progress bar is _not_ printed as we expected because the progress bar feature is disabled when`n_jobs != 1`.

**Comment by xadrianzetx** [comment]
Thanks, looks solid! I will open PR in the next few days.
