### ISSUE TITLE
mlflow integration error while using MLFlowcallback client

### ISSUE THREAD

**Issue by p-mishra1** [optuna/optuna#2898]
```python
import optuna
import mlflow
from optuna.integration.mlflow import MLflowCallback

mlflc = MLflowCallback(
    tracking_uri=YOUR_TRACKING_URI,
    metric_name="my metric score",
)


@mlflc.track_in_mlflow()
def objective(trial, y):
    x = trial.suggest_float("x", -10, 10)
    mlflow.log_param("power", 2)
    mlflow.log_metric("base of metric", x - 2)

    return (x - 2) ** 2

y=3
study = optuna.create_study(study_name="my_other_study")
study.optimize(lambda trial : objective(trial, y=y), n_trials=10, callbacks=[mlflc])
```

how can we pass multiple arguments like this while using MLflowCallback decorator it gives an error.
TypeError: wrapper() got an unexpected keyword argument 'y'

**Comment by nzw0301** [comment]
Hi, thank you for asking the good question. As a workaround, the following objective function will resolve the issue. As a developer side, there is room to improve the mlflow's integration.


```python
def objective_with_argument(y):
    
    @mlflc.track_in_mlflow()    
    def objective(trial):
        x = trial.suggest_float("x", -10, 10)
        mlflow.log_param("power", 2)
        mlflow.log_metric("base of metric", x - 2)

        return (x - 2) ** 2 + y
    
    return objective

y = 3
study = optuna.create_study(study_name="my_other_study")
study.optimize(objective_with_argument(y), n_trials=10, callbacks=[mlflc])
```

**Comment by p-mishra1** [comment]
Thanks for the Workaround @nzw0301, I used global variable as a workaround, but this is better than that.
I do have a follow up question on this, I'm getting mlflow experiment exist error while using n_job parameter in optuna create study.(what i suspect is optuna trying to create a new experiment with the same name in mlflow with each thread).

Trial 3 failed because of the following error: MlflowException("Experiment 'optuna_test' already exists.")

**Comment by nzw0301** [comment]
My pleasure!

You are right. I think the current code does not support `n_jobs != 1`, unfortunately...
