### ISSUE TITLE
Clean up deprecated features

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#2902]
## Motivation

There are several methods/classes annotated with `@deprecated` in Optuna. It's time to consider whether they should be removed or when to remove them.

## Description

- [x] List deprecated features
- [x] Remove APIs whose `removed_version` are less than `v3.0.0` (deprecated in before `v2.0.0`)
- [x] Document `@deprecated` decorator (we remove `_get_removed_version_from_deprecated_version` and simplify it)

**Comment by nuka137** [comment]
List of Classes/Methods with `@deprecated` is here.

|File|Method/Class|Deprecated Version|Remove Version|
|---|---|---|---|
|`integration/_lightgbm_tuner/optimize.py`|`LightGBMTuner::best_booster`|1.4.0|-|
|`integration/catalyst.py`|`CatalystPruningCallback`|2.7.0|-|
|`integration/chainermn.py`|`ChainerMNTrial::suggest_uniform`|2.11.0|6.0.0|
|`integration/chainermn.py`|`ChainerMNTrial::suggest_loguniform`|2.11.0|6.0.0|
|`integration/chainermn.py`|`ChainerMNTrial::suggest_discrete_uniform`|2.11.0|6.0.0|
|`integration/cma.py`|`CmaEsSampler`|2.0.0|-|
|`integration/fastaiv1.py`|`FastAIV1PruningCallback`|2.4.0|-|
|`integration/pytorch_distributed.py`|`TorchDistributedTrial::suggest_uniform`|2.11.0|6.0.0|
|`integration/pytorch_distributed.py`|`TorchDistributedTrial::suggest_loguniform`|2.11.0|6.0.0|
|`integration/pytorch_distributed.py`|`TorchDistributedTrial::suggest_discrete_uniform`|2.11.0|6.0.0|
|`multi_objective/samplers/_base.py`|`BaseMultiObjectiveSampler`|2.4.0|4.0.0|
|`multi_objective/samplers/_motpe.py`|`MOTPEMultiObjectiveSampler`|2.4.0|4.0.0|
|`multi_objective/samplers/_nsga2.py`|`NSGAIIMultiObjectiveSampler`|2.4.0|4.0.0|
|`multi_objective/samplers/_random.py`|`RandomMultiObjectiveSampler`|2.4.0|4.0.0|
|`multi_objective/study.py`|`create_study`|2.4.0|4.0.0|
|`multi_objective/study.py`|`load_study`|2.4.0|4.0.0|
|`multi_objective/study.py`|`MultiObjectiveStudy`|2.4.0|4.0.0|
|`multi_objective/trial.py`|`MultiObjectiveTrial`|2.4.0|4.0.0|
|`multi_objective/trial.py`|`FrozenMultiObjectiveTrial`|2.4.0|4.0.0|
|`multi_objective/visualization/_pareto_front.py`|`plot_pareto_front`|2.4.0|4.0.0|
|`samplers/_tpe/multi_objective_sampler.py`|`MOTPESampler`|2.9.0|-|
|`structs.py`|`FrozenTrial`|1.4.0|-|
|`structs.py`|`StudySummary`|1.4.0|-|
|`structs.py`|`TrialPruned`|0.19.0|-|
|`study/study.py`|`Study::_ask`|2.5.0|-|
|`study/study.py`|`Study::_tell`|2.5.0|-|
|`trial/_base.py`|`BaseTrial::suggest_uniform`|2.11.0|6.0.0|
|`trial/_base.py`|`BaseTrial::suggest_loguniform`|2.11.0|6.0.0|
|`trial/_base.py`|`BaseTrial::suggest_discrete_uniform`|2.11.0|6.0.0|
|`trial/_fixed.py`|`FixedTrial::suggest_uniform`|2.11.0|6.0.0|
|`trial/_fixed.py`|`FixedTrial::suggest_loguniform`|2.11.0|6.0.0|
|`trial/_fixed.py`|`FixedTrial::suggest_discrete_uniform`|2.11.0|6.0.0|
|`trial/_frozen.py`|`FrozenTrial::suggest_uniform`|2.11.0|6.0.0|
|`trial/_frozen.py`|`FrozenTrial::suggest_loguniform`|2.11.0|6.0.0|
|`trial/_frozen.py`|`FrozenTrial::suggest_discrete_uniform`|2.11.0|6.0.0|
|`trial/_trial.py`|`Trial::suggest_uniform`|2.11.0|6.0.0|
|`trial/_trial.py`|`Trial::suggest_loguniform`|2.11.0|6.0.0|
|`trial/_trial.py`|`Trial::suggest_discrete_uniform`|2.11.0|6.0.0|

**Comment by himkt** [comment]
@nuka137 Thank you for the comprehensive list! Looks nice and we can remove following stuffs.

- `LightGBMTuner::best_booster`
- `FrozenTrial`
- `StudySummary`
- `TrialPruned`

For `_Dashboard::take_action`, we have the ongoing discussion how to migrate to `optuna-dashboard`. So, it would be better to be done as the separated task of deleting above features.

**Comment by himkt** [comment]
All deprecated features are well organized now. Thank you @nuka137 for the contributions!
