### ISSUE TITLE
Align arguments with `create_study` and `load_study`

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#2911]
## Motivation

Currently, the orders of arguments are different between `create_study` and `load_study`, although users might think interfaces are the same. In this issue, we consider changing the interface of `create_study` or `load_study` to align them and make a change if we decide to do.

## Description

- Discuss if we should align interfaces of `create_study` and `load_study`
- Decide how to introduce the changes less burdensome for users (if we decide to change)
- Make PR(s) with appropriate messages to let users know about the change

**Comment by himkt** [comment]
The current signature of `load_study` looks following:

```python
def load_study(
    study_name: Optional[str],
    storage: Union[str, storages.BaseStorage],
    sampler: Optional["samplers.BaseSampler"] = None,
    pruner: Optional[pruners.BasePruner] = None,
) -> Study:
```

Albeit `study_name` is optional, it is a positional, which means users have to specify `None` if they want to load a study without its name specified. I think it's reasonable to make `study_name` a keyword argument with default value `None` and switch the order from `study_name`, `storage`, `sampler`, and `pruner` to `storage`, `study_name`, `sampler`, and `pruner`. The order is still different between `create_study` and `load_study` (`study_name` will be second in `load_study` but is fourth in `create_study`) but it is not wired because `study_name` is more important in `load_study` compared to `create_study`.

If anyone has an opinion on this change, please feel free to comment!

**Comment by HideakiImamura** [comment]
Note: https://github.com/optuna/optuna/pull/3159#issuecomment-995820038

**Comment by HideakiImamura** [comment]
Let me close this issue, as #3270 is complete and further discussion is going on in #3324. Please feel free to reopen if you have any concern.
