### ISSUE TITLE
Does Optuna allow for idiomatic usage if I want to treat it as a trial generator

### ISSUE THREAD

**Issue by alexis-intellegens** [optuna/optuna#2916]
Rather than:
```Python
def objective(trial):
    # logic
    return error

study = optuna.create_study()
study.optimize(objective, n_trials=100)
```

I want something like:
```Python
def objective(search_space):
    # logic
    return error

study = optuna.create_study()

while True:
    suggested_spaces = study.next_trials(num_trials=4)
    errors = []
    for suggested_space in suggested_spaces:
        errors.append(objective(search_space))
    study.give_objective_results(errors)

    if user_satisfied:
        best_params = study.best_params
        break
```

Where I can handle the running of the objective + can generate future trials to run as required. I couldn't find much on this in the docs/issues.

I essentially want the algorithms but handle my own objectives (and how they run), search spaces and getting trials on the fly.

**Comment by nzw0301** [comment]
hi, 

I think `ask and tell` interface can do similar way:
https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/009_ask_and_tell.html#batch-optimization.

**Comment by alexis-intellegens** [comment]
Thanks @nzw0301 this looks perfect, closing issue.
