### ISSUE TITLE
KeyError: 'validation-0_rmse'

### ISSUE THREAD

**Issue by pn12** [optuna/optuna#2921]
On using the below code, I am unable to fetch results from pruner callback with metric "validation_0-rmse", the below works fine when xgb.fit is used, 

I tried using "eval-rmse", it gives inaccurate results .

Can anybody suggest the metric to be used in Pruner?

The code will have to use xgb.train since instance weights are required in Model.

Thanks

```python
def objective(
    trial,
    X=train_data,
    y=target,
    random_state=22,
    n_splits=3,
    
    n_jobs=1,
    ):
  xgbparams ={
    'booster '    : 'gbtree',       
    'objective'   : 'reg:squarederror',
    'eval_metric' : 'rmse',
    "n_estimators": trial.suggest_int("n_estimators", 30, 6000),

    "max_depth": trial.suggest_int("max_depth", 3, 14),
    "learning_rate": trial.suggest_loguniform("learning_rate", 0.0001, 0.9),
    "eta" : trial.suggest_uniform("eta", 0.0001, 0.6),
    "min_child_weight": trial.suggest_loguniform("min_child_weight", 1, 7),

    # "subsample": trial.suggest_loguniform("subsample", 0.5, 0.9),
    # "colsample_bytree": trial.suggest_loguniform("colsample_bytree", 0.5, 0.95),
    # "colsample_bylevel": trial.suggest_loguniform("colsample_bylevel", 0.5, 0.95),
    # "colsample_bynode": trial.suggest_loguniform("colsample_bynode", 0.5, 0.95),

    "reg_alpha": trial.suggest_uniform("reg_alpha", 1, 20.0),
    "reg_lambda": trial.suggest_uniform("reg_lambda", 1, 25.0),
    "gamma": trial.suggest_int("gamma", 1, 50),

    "seed": trial.suggest_int('seed',1,10000),
    "early_stopping_rounds" : 15,
   }
  pruning_callback = XGBoostPruningCallback(trial, "validation-0_rmse")
  kf = KFold(
        n_splits=n_splits, shuffle=True, random_state=random_state
    )
  X_values = X.values
  y_values = y
  y_pred = np.zeros_like(y_values)
  for train_index, test_index in kf.split(X_values,y_values):
    X_A, X_B = X_values[train_index, :], X_values[test_index, :]
    y_A, y_B = y_values[train_index], y_values[test_index]

    train_weights, val_weights=1/y_A,1/y_B

    train_dataset  = xgb.DMatrix(X_A,label=y_A)
    val_dataset  = xgb.DMatrix(X_B,label=y_B)
    watchlist = [(train_dataset, 'train'), (val_dataset, 'eval')]

    model = xgb.train(params=xgbparams,
                      dtrain=train_dataset,
                      evals=watchlist,
                      callbacks=[pruning_callback],
                      early_stopping_rounds = 15,
                      verbose_eval=None
                      
                      )
    y_pred[test_index] += model.predict(val_dataset)
  
  return np.sqrt(mean_squared_error(y_values, y_pred))

sampler = optuna.samplers.TPESampler(seed=124, multivariate=True)
study = optuna.create_study(direction="minimize", sampler=sampler)
study.optimize(objective, n_trials=5,)
```

**Comment by nzw0301** [comment]
I suppose that `eval-rmse` is correct according to [Optuna example](https://github.com/optuna/optuna-examples/blob/main/xgboost/xgboost_integration.py). 

Since the code is not reproducible, I'm not sure but the usage of the callback is supposed to be strange. Please make sure the callback is called once at each step in each trial. In the code, the callback can be called `n_splits` times at each step via `xgb.train`. 

Technically, we can use the callback for K-fold cross-validation, but I think it works on only the first split as we expected. I believe that optuna shows some warning messages like `The reported value is ignored because this `step` SOME_NUMBER  is already reported.`

**Comment by pn12** [comment]
Using eval-rmse gives inaccurate results, the values are incomparably high.

Callback on k-fold did not gave any warning message, but using callback for only once will be possible without k-fold only, I believe.

**Comment by nzw0301** [comment]
Please feel free to reopen the issue if you follow the issue template and the code without k-fold does not work as you expected.

**Comment by pn12** [comment]
@nzw0301 - Why the issue has been closed? Without k-fold, I get the similar inaccurate results, while the same code works correctly with model.fit (I mentioned this above as well)

**Comment by pn12** [comment]
@nzw0301 - Additionally, k-fold working is fine with pruner, similar codes can be found on multiple webpages online as well plus the optimizer results with k-fold pruner gives matched results when run independently on the dataset.

**Comment by nzw0301** [comment]
I'm afraid that we cannot investigate the issue if the code is not reproducible. 

Could you seriously follow the issue template?
