### ISSUE TITLE
How to avoid repeating enqueued trials in parallel setting?

### ISSUE THREAD

**Issue by stepthom** [optuna/optuna#2925]
I have a situation in which each trial takes a significant amount of time (~60 minutes) to compute. I will run many processes (~30) in parallel (using PostgreSQL storage). I plan to run 1000s of trials in total.

I would like to manually enqueue a  large number (~100) of trials with fixed parameters (via [`enqueue_trial`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.enqueue_trial))  before the normal `optimize` function is called.

Is there a way to enqueue the trials such that each trial is only executed once; i.e., not re-exected by each parallel processes? AFAIK (and some simple experiments have confirmed), `enqueue_trial` will always enqueue the trial, no matter if another process has already run a trial with the same parameters, or is already planning to run a trial with those parameters. The effect is that the different processes won't "know" what has been enqueued by other processes, so each process will blindly execute all of the enqueued trials itself, leading to lots of redundant work and wasted time.

**Comment by himkt** [comment]
Hello @stepthom, how about separating queuing process from optimizing (means that it avoids to enqueue in parallel processes). It looks like following:

## `prepare_study.py`

```python
import optuna


study_name = "example-study"  # Unique identifier of the study.
storage_name = "sqlite:///{}.db".format(study_name)


study = optuna.create_study(study_name=study_name, storage=storage_name)
study.enqueue_trial({"x": 0, "y": 0})
study.enqueue_trial({"x": 0, "y": 0})
study.enqueue_trial({"x": 0, "y": 0})
```

## `optimize.py`

```python
import optuna


study_name = "example-study"  # Unique identifier of the study.
storage_name = "sqlite:///{}.db".format(study_name)


def objective(trial):
    x = trial.suggest_float("x", -10, 10)
    print("x: ", x)
    return (x - 2) ** 2


study = optuna.create_study(study_name=study_name, storage=storage_name, load_if_exists=True)
study.optimize(objective, n_trials=3)
```

```sh
# it executes once on the specific shell
python prepare_study.py  # only executed once

# multiple terminals run this command (parallel execution)
python optimize.py
```

**Comment by stepthom** [comment]
@himkt This works perfectly. Thank you very much! 👍
