### ISSUE TITLE
Defining constraints/feasible regions

### ISSUE THREAD

**Issue by alexis-intellegens** [optuna/optuna#2927]
I can't seem to find much regarding methods/tricks to set multiparameter constraints.

Eg let's say my space is:

x1 <= 100
25< x2 <= 75
x1 + x2 <= 100

How would you go about "encoding" this? Would you simply give back high penalties when outside the feasible region (such as x1 = 50, x2 = 51) or would you prune the trials? or are there more elegant approaches?

**Comment by nzw0301** [comment]
I suggest using samplers that have `constraints_func` such as [`NSGAIISampler`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.samplers.NSGAIISampler.html).

**Comment by alexis-intellegens** [comment]
Thanks that looks interesting, do you know of a simple example such as the one I proposed?

**Comment by toshihikoyanase** [comment]
Hello @alexis-intellegens , we can see the [usage of the `constraints_func` of `BoTorchSampler`](https://github.com/optuna/optuna-examples/blob/main/multi_objective/botorch_simple.py) in the official optuna example repository.

**Comment by alexis-intellegens** [comment]
Thanks @toshihikoyanase , are there any plans for further developing constraints for samplers such as CmaEs?

**Comment by toshihikoyanase** [comment]
@alexis-intellegens Currently, we don't have any plans to implement constraints handling in `CmaEsSampler`. This is mainly because Optuna uses https://github.com/CyberAgentAILab/cmaes as an implementation of the CMA-ES algorithm, but it does not support constrained optimization.

**Comment by alexis-intellegens** [comment]
Thanks.
