### ISSUE TITLE
Simplify the after_trial arguments

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#2936]
## Motivation
Currently, `CachedStorage` is implemented on the assumption that trials in the complete state will not be updated in the future. And, due to that restriction, trials in the complete state cannot be updated.

Currently, due to the restriction that the trial in the complete state can not be updated, it is possible to avoid race condition when multiple workers edit one trial at the same time, and Cached Storage is also implemented on the restriction. However, due to the restriction, it is not possible to update the trial in the complete state.

Due to the above restriction, before putting a trial in the complete state, `FrozenTrial` and state, values are specified separately as arguments of after_trial like [optuna/study/study.py#L657](https://github.com/optuna/optuna/blob/master/optuna/study/study.py#L657). If possible, we want to get rid of state and values from the arguments, and pass only FrozenTrial to after_trial.

## Description

The following can be considered as the main countermeasures.

* We will not work on it.
* Set the state and values into FrozenTrial and then pass it to after_trial
* Add attribute/column or define another state which means that the state is complete and the values are committed but they can be modified at that stage.
* Give a time stamp so that trials can be modified after their completion, and update cache as needed. ref: [PR: # 1405](https://www.google.com/url?q=https://github.com/optuna/optuna/pull/1405&sa=D&source=editors&ust=1632035563915000&usg=AOvVaw1jskgV_GTsmLI5-TKHWALv)

The solution will be decided in consideration of the following points from the above countermeasures. Also, the changes have been merged.

* Cost-effectiveness to simplify after_trial arguments
* Use cases for rewriting a complete trial other than this use case
* Pros / cons of each countermeasure

## TODOs
- [ ] Make a consensus for the solution in this issue
- [ ] Implement the above solution

**Comment by keisuke-umezawa** [comment]
## Current conclusion
Only for simplifying the argument of `after_trial`, it is too heavy to implement `another state` or `editable trials after completion`.  The current decision will be that `We will not work on it`. But, if we will have any requests in #3251 for `editable trials after completion`, we may work on it together with this issue.

**Comment by HideakiImamura** [comment]
Since there was no particular community input on this item, we will not be working on this item, at least not in V3 as well as #3251.
