### ISSUE TITLE
Make a consistent policy for instantiation of storage classes and publicization of private storage accompanying it

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#2942]
blocked by https://github.com/optuna/optuna/issues/2938

## Motivation

Currently, `CachedStorage` and `InMemoryStorage` are private to users, and it is not expected that users will instantiate them directly using their constructors. However, the handling of instances is inconsistent in the following points:

* `RDBStorage` and `RedisStorage` are public and are expected to be instantiated by users. Otherwise, these two classes cannot specify their functionality by the string argument.
* Since `trial.storage` is public, we can access any instance of storage via the public API.

It is necessary to determine a consistent policy for instantiation of the all storage classes, and to determine their accesses (public/private) of `CachedStorage` and `InMemoryStorage` based on it.

## Description

The policy will be decided in consideration of the following points. Also, the changes have been merged.
* Consistent policy for instantiation of the all storage classes
* Based on that, their accesses (public/private) of `CachedStorage` and `InMemoryStorage` have been decided.

## TODOs
- [x] Decide consistent policy for instantiation of the all storage classes
- [x] Their accesses (public/private) of `CachedStorage` and `InMemoryStorage` have been decided.
- [x] Implementation

**Comment by himkt** [comment]
Although the consistent policy was not set, we met the conclusion that `CacheStorage` would not be made public in https://github.com/optuna/optuna/issues/2938. Based on the discussion, all the tasks listed in this issue are finished or unfocused, I think.

@keisuke-umezawa Is there still any item left for completing this issue?

**Comment by keisuke-umezawa** [comment]
@himkt 
You are right! But, to close this issue, I need to summarize the situation beforehand.

**Comment by HideakiImamura** [comment]
@keisuke-umezawa Could you share the current status of this issue?

**Comment by keisuke-umezawa** [comment]
## Current conclusions (Need further discussion)
### Decide consistent policy for instantiation of the all storage classes.
- If users need to specify functionality of a storage by the string argument, they should be public. e.g.
    - RDBStorage
    - RedisStorage
-  Otherwise, they should be private, since users do not need to deal with an instance of a storage directly. e.g.
    - InMemoryStorage
    - CachedStorage

### Their accesses (public/private) of CachedStorage and InMemoryStorage have been decided.
- For CachedStorage, as described in the above section and https://github.com/optuna/optuna/issues/2938#issuecomment-1035986042, we do not need to make it public in the moment.
- For InMemoryStorage, as described in the above section, we do not need to make it public in the moment.

**Comment by keisuke-umezawa** [comment]
@HideakiImamura 
I summarized the current conclusions. If other committers agree on it, let's close this issue.

**Comment by HideakiImamura** [comment]
Thanks for the summarization. I think this Issue is fine to close. Please let me do that.
