### ISSUE TITLE
Change the default independent_sampler of CmaEsSampler

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#2951]
## Motivation

`CmaEsSampler` can sample numbers, but not category values. Currently, when trying to sample from a categorical distribution, the sampler specified in `independent_sampler` will be called instead, and `RandomSampler` will be called with the default setting. If a more appropriate `independent_sampler` is specified by default, it may be possible to recommend `CmaEsSampler` for problems involving category values.

## Description
Appropriate independent_sampler is specified by default from the following points of view:

- Execution speed
- Convergence speed and stability validated by the benchmark tool `kurobako`

**Comment by HideakiImamura** [comment]
We have decided to postpone this task after V3.
