### ISSUE TITLE
How to use PartialFixedSampler to vary one parameter at a time?

### ISSUE THREAD

**Issue by stepthom** [optuna/optuna#2952]
Let's say I have a "baseline" set of parameters that I prefer/like:

```python
baseline = {
  "x": 4,
  "y": 5.6,
  "z": 22,
}
```

Now, I'd like to try many specific values of each parameter, such as:

```python
search= {
  "x": [0, 3, 4, 16, 50],
  "y": [0, 1.4, 5.6, 9.9, 10.0],
  "z": [12, 22, 200, 9000],
}
```

How can I vary one parameter at a time while holding the others constant to their baseline value, and do so in turn for all parameters of interest? For example, I'd like to try all 5 `x` values in `search` while keeping `y` and `z` constant to their `baseline` values (i.e., 5.6 and 22); then all 5 `y` values while holding `x` and `z` constant; and then finally all 4 `z` values while keeping `x` and `y` constant. So in total, there would be only5 + 5 + 4 = 14 trials.

How can this be achieved, especially in a distributed setting?

It seems like PartialFixedSampler is close to what I want, but it will fix one parameter while varying the rest; while I want to vary one parameter while fixing the rest, in turn.

Note that the above is just a simplified example. In my actual case, I have 12 parameters that each can take on between 5 and 50 specific values. So using a GridSearch is infeasible as it would result in billions and billions of trials. RandomSearch is an option but it still would be a thousands of trials before many of the points I'd like to have samples actually are. I've tried the other samplers as well but they will also tend to focus around a smaller subset of the values.

The only option I can think of is to write some code that loops through the `search` and `baseline` structs and manually constructs and enqueues combinations them into the study via `enqueue_trial`, as shown below. However, before I did that, I wanted to check if this functionality already existing in Optuna somehow.

```python
for k, vs in search.items():
    for v in vs:
        params = baseline.copy()
        params.update({k: v})
        print(params)
        study.enqueue_trial(params)
```

**Comment by nzw0301** [comment]
Hi, sorry for the delayed response.  As you said, `enqueue_trial` is supposed to be an appropriate way.
