### ISSUE TITLE
Indicate *why* trial was pruned

### ISSUE THREAD

**Issue by cowwoc** [optuna/optuna#2954]
## Description

It's not always clear why a trial gets pruned.

If a study contains multiple pruners (https://github.com/optuna/optuna/issues/2042#issuecomment-731515468) then it's not clear which pruner decided to prune.

Even if you only have one pruner, "Trial 1 was pruned by EarlyStopping at epoch 2 because val_loss did not improve by 0.0 within 3 epochs" would be more helpful than the current message which reads "Trial 1 pruned. Trial was pruned at epoch 2."

**Comment by HideakiImamura** [comment]
How about looking `optuna.visualization.plot_intermediate_values`?

**Comment by cowwoc** [comment]
@HideakiImamura Honestly I find it difficult to make heads and tails out of that graph. There are thousands of overlapping trials that get pruned early on and I can't tell why necessarily one was allowed to run longer than the other.

I usually scroll through the output console (or look at it passively in real-time) and when I notice that a trial got pruned I have no idea why. I could always go back after-the-fact to investigate but it would be better to be told the reason instead of trying to guess by looking at the plot.

**Comment by cowwoc** [comment]
On a separate note, I find many of Optuna's visualizations very useful. One of them helped me figure out how to best tweak the range of the parameters to get better results.

I'm sure `optuna.visualization.plot_intermediate_values` could be very useful too but it needs extra tooling to make it useful with thousands of overlapping lines. Adding a filtering capability (show me trial X, Y, Z) similar to what TensorBoard offers would be a great start. I'd still like to get a textual explanation of why pruning took place but the graph definitely has its place as well.
