### ISSUE TITLE
Stabilize `create_trial`

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#2956]
## Motivation

In https://github.com/optuna/optuna/issues/2955, we plan to release stabilized versions of `add_trial` and `add_trials` in Optuna v3. When we decide to stabilize them, we also stabilize `create_trial` as well.

## Description

- [x] Remove the experimental decoration from the `create_trial`

## Note

✅ There is a request that allows users to use `create_trial` without `distributions` parameter. However, Optuna assumes that all trials have `distributions` specified, and it would be difficult and expensive to change the design. Therefore, we considered this request but would not to work on.

**Comment by nzw0301** [comment]
Let me confirm how to resolve this issue. Can we resolve this by just removing `experimental` decorator of `create_trial`?

**Comment by himkt** [comment]
Yes, exactly. We are ready to simply remove the experimental decoration.

**Comment by HideakiImamura** [comment]
Let me close this issue since #3196 has been merged.
