### ISSUE TITLE
[RFC] Show progress bar based on `timeout`

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#2958]
## Motivation

The current [`study.optimize`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize) shows the progress bar when we specify the number of trials. We can show the progress bar based on the `timeout` value as well.

Note that before implementing this feature, we need to decide the priority of `n_trials` and `timeout`. When we specify both values as not `None` values, there are two ways to show the progress bar. 

Moreover, we need to discuss the case when both `None`. I suppose not showing the progress bar makes sense when both are `None`.

## Description

- Show progress bar using `timeout` value.
- Add test by following https://github.com/optuna/optuna/pull/2900

## Additional context (optional)

We might need to support the `n_jobs!=1` case depending on https://github.com/optuna/optuna/issues/2957.

**Comment by xadrianzetx** [comment]
> When we specify both values as not None values, there are two ways to show the progress bar.

We could always show `n_trials` early on, and check after first iteration (on nth, depending on precision we want) if completing all trials will take longer than `timeout`. If so, we would switch progbar from trials left to time left.

> Moreover, we need to discuss the case when both None. I suppose not showing the progress bar makes sense when both are None.

Sounds reasonable.

I'll open a PR on this if you have capacity to review it.

**Comment by nzw0301** [comment]
Thank you for your comment! 

Let me summarise candidates if both `n_trials` and `timeout` are not `None`:

1. prioritise `n_trials`
2. prioritise `timeout`
3. during the first trial, use `n_trials` (or maybe `timeout`). After the first trial, decide which to choose `n_trials` or `timeout` for the progress bar.
4. (more accurate version of 3) during the first trial, use `n_trials` (or maybe `timeout`). After _each_ trial, decide which to choose `n_trials` or `timeout` for the progress bar.

**Comment by xadrianzetx** [comment]
IMO +1 to the last candidate. Informative and will work well when trial execution times are uneven.

**Comment by nzw0301** [comment]
Me too! I'll ask other committers about this.

**Comment by nzw0301** [comment]
@toshihikoyanase suggested using only `n_trials`: the first candidate. A user wants to perform optimisation `n_trials` times ideally but, to avoid taking too much to perform optimisation, he/she specifies `timeout` at the same time. Indeed, personally, I saw such a setting in a machine learning paper, so his suggestion is supposed to be natural.

So how about implementing candidate 1 at first? If the optuna community prefers the last candidates to the first one or sends feedback to us, we can change the logic. 

Thanks, @toshihikoyanase for your comment.

**Comment by xadrianzetx** [comment]
Sure, I'll prioritize `n_trials` then!
