### ISSUE TITLE
LightGBMTunerCV Doesn't Support Custom folds (cv)

### ISSUE THREAD

**Issue by docmarionum1** [optuna/optuna#2960]
When I try running `LightGBMTunerCV` with an iterator for `folds` it passes the first trial (Trial 0) and then fails the second trial (Trial 1). This is similar to #1710 (which is now closed) except that #1710 mentions this error on Trial 0 instead of 1.

## Expected behavior

I expect it to run without error in the same manner as if I didn't pass the `folds` parameter.

## Environment

- Optuna version: 2.9.1
- Python version: 3.7.12
- OS: Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic
- (Optional) Other libraries and their versions: 
  - I'm running on colab.
  - `lightgbm==3.2.1`

## Error messages, stack traces, or logs

```
feature_fraction, val_score: 0.038508:  14%|#4        | 1/7 [00:22<02:13, 22.19s/it][I 2021-09-27 13:46:01,691] Trial 0 finished with value: 0.038507561915105994 and parameters: {'feature_fraction': 0.5}. Best is trial 0 with value: 0.038507561915105994.


feature_fraction, val_score: 0.038508:  14%|#4        | 1/7 [00:22<02:13, 22.19s/it]/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py:532: UserWarning:

Found `early_stopping` in params. Will use it instead of argument

[W 2021-09-27 13:46:05,049] Trial 1 failed because of the following error: ValueError('For early stopping, at least one dataset and eval metric is required for evaluation')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "/usr/local/lib/python3.7/dist-packages/optuna/integration/_lightgbm_tuner/optimize.py", line 320, in __call__
    cv_results = lgb.cv(self.lgbm_params, train_set, **self.lgbm_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/lightgbm/engine.py", line 601, in cv
    evaluation_result_list=res))
  File "/usr/local/lib/python3.7/dist-packages/lightgbm/callback.py", line 215, in _callback
    _init(env)
  File "/usr/local/lib/python3.7/dist-packages/lightgbm/callback.py", line 186, in _init
    raise ValueError('For early stopping, '
ValueError: For early stopping, at least one dataset and eval metric is required for evaluation
```

## Reproducible examples (optional)

```python
import optuna.integration.lightgbm as lgb
import numpy as np
from sklearn.model_selection import GroupKFold

X = np.arange(100).reshape(-1, 1)
y = X.flatten() >= 50
group = X.flatten() % 2 == 0

train_data = lgb.Dataset(X, y)

params = {
    'objective': 'binary',
    'early_stopping': 1
}

gkf = GroupKFold(2)

tuner = lgb.LightGBMTunerCV(
    params, 
    train_data,
    folds=gkf.split(X, y, group), 
)

tuner.run()
```

**Comment by nzw0301** [comment]
I think the value of `folds` looks strange when I see our example: https://github.com/optuna/optuna-examples/blob/main/lightgbm/lightgbm_tuner_cv.py#L25. In addition, by following https://github.com/microsoft/LightGBM/issues/2319#issuecomment-520176426, the code looks like

```python
import optuna.integration.lightgbm as lgb
import numpy as np
from sklearn.model_selection import GroupKFold


X = np.arange(100).reshape(-1, 1)
y = X.flatten() >= 50
group = np.array([sum(X.flatten() % 2 == 0), sum(X.flatten() % 2 != 0)])

train_data = lgb.Dataset(X, y, group=group)

params = {
    "objective": "binary",
}

gkf = GroupKFold(2)

tuner = lgb.LightGBMTunerCV(
    params, 
    train_data,
    folds=gkf, 
)

tuner.run()
```

**Comment by docmarionum1** [comment]
Thanks, that seems to work. 

I also figured out what was going wrong with my original code.

I expected passing `gkf.split(X, y, group)` to work because it works with `lightgbm.cv` directly. It accepts `folds`=`generator or iterator of (train_idx, test_idx) tuples` which that code returns.

But since this parameter gets reused for each trial, the generator is already exhausted after the first trial. The fix is to pass `folds=list(gkf.split(X, y, group))`.

**Comment by nzw0301** [comment]
Thank you for sharing your investigation. I agree with you.
