### ISSUE TITLE
What does "# trials" mean in slice map?

### ISSUE THREAD

**Issue by cowwoc** [optuna/optuna#2967]
I'm having a hard time understanding the slice plot visualization.

I see the value of the parameter on the x-axis, the value of the objective score on the y-axis but what does "# Trials" (on the right-hand-side) mean in the context of this plot.

Does a darker circle color (higher # trials value) denote that a lot of trials shared the exact same parameter value? Does that imply that the value is "promised" and tends to lead to better objective scores?

If my goal is to minimize the objective score and I see multiple circles close to a y-value of 0, why would I favor circles with a darker color than circles with a lighter color?

**Comment by nzw0301** [comment]
In my understanding, `#trials` indicates the trial's id according to [the matpliblib implementation](https://github.com/optuna/optuna/blob/master/optuna/visualization/matplotlib/_slice.py#L179).

**Comment by nzw0301** [comment]
Honestly, I feel you. Definitely, there is room to improve this, for example, documentation to clarify the meaning of colourmap.

**Comment by fsmosca** [comment]
![image](https://user-images.githubusercontent.com/22366935/136478835-d415cdd4-ba45-4e31-9376-33d1f180d537.png)

I believe #Trials is trial number, 0, 1, 2, 3 ... As the color gets darker in the above example (direction=maximize) the trial number gets bigger.

> If my goal is to minimize the objective score and I see multiple circles close to a y-value of 0, why would I favor circles with a darker color than circles with a lighter color?

If your objective function is deterministic (returns same objective value for repeated param values) for example,
```
trial: 1
param1: 4
param2: 8
value: 1

trial: 12
param1: 4
param2: 8
value: 1
```
then it does not matter if the color is lighter or darker.

However if your objective function is stochastic or nondeterministic (returns different objective value for repeated param values) for example,
```
trial: 8
param1: 8
param2: 2
value: 4

trial: 44
param1: 8
param2: 2
value: 6
```
Then I prefer trial 44 or the darker one.

Even better take the mean of the value in the two trials to get the effective objective value.
```
mean_value = (4+6)/2 or 5
```

An example stochastic objective function that I had. Trial 58 and 96 have the same param values but different objective values, to get a clear picture of the objective value I recorded the value mean and count of trials.
```
 trial  value  params_Pp2  params_Pp6     state  value_mean  trial_cnt
    58  338.0           8           4  COMPLETE       213.5          2
    96   89.0           8           4  COMPLETE       213.5          2
    45   89.0           8           3  COMPLETE       164.5          6
    56  338.0           8           3  COMPLETE       164.5          6
    89   89.0           8           3  COMPLETE       164.5          6
   144  191.0           8           3  COMPLETE       164.5          6
   148  191.0           8           3  COMPLETE       164.5          6
   160   89.0           8           3  COMPLETE       164.5          6
```
In the eyes of the optimizer the best is 338, but to me it is only 213.5 for (8/4) and 164.5 for (8/3)

**Comment by cowwoc** [comment]
Fair enough. It sounds like we have (at least) two distinct use-cases. Maybe we should have a "mode" parameter or two separate visualizations. For the deterministic case, I just the visualization to help me quickly identify the best range of parameters. For the non-deterministic case, maybe it would be helpful to automatically calculate `value_mean` or whatever custom metric you have in mind and get that plotted directly on the graph so you don't have to run the numbers by yourself after-the-fact.
