### ISSUE TITLE
View multiple studies in dashboard

### ISSUE THREAD

**Issue by MannyKayy** [optuna/optuna#297]
Currently, you have to pass the study name to the dashboard cli when the dashboard is launched.
e.g. "example-study":
`optuna dashboard --storage "sqlite:///example.db" --study "example-study"`

It would be helpful if the study cli argument  was optional and we could select and view different studies within the database via the dashboard.

Thanks,

**Comment by g-votte** [comment]
@MannyKayy  

Thanks a lot for your feedback!
I agree it’s more helpful if we can track multiple studies in a single dashboard process.

Actually, we’ve been working on dashboard enhancement and considering to add multi-study feature as part of that.
As it’ll still take some time before release, please be patient for a while.

**Comment by sile** [comment]
@dwiel I think [`optuna.study.get_all_study_summaries`](https://optuna.readthedocs.io/en/stable/reference/study.html#optuna.study.get_all_study_summaries) function can be used for such purpose.
