### ISSUE TITLE
loading study from relative path overwrites db object even if load_if_exists=True

### ISSUE THREAD

**Issue by VMBoehm** [optuna/optuna#2972]
Hello,

I'm trying to load a study from a saved database object which is located in a different folder than the script I use to load it. I noticed that if I pass the relative path as study name, the database object gets overwritten despite the 'load_if_exists=True' flag. This must either be a bug or the way I'm referencing the database object is not the way I'm supposed to. In any case, the behavior seems counterintuitive.
Thanks in advance  for your feedback!

Example: This overwrites example-study.db located in '../study_folder/' and creates a new db object in that folder.

study_name = "../study_folder/example-study"   # relative path to saved study
storage_name = "sqlite:///{}.db".format(study_name)
study = optuna.create_study(study_name=study_name, storage=storage_name, load_if_exists=True) # creates new db object in ../study_folder/ and overwrites old one

I'm using optuna version '2.9.1'

Please let me know if you need any more information to track this down.

**Comment by VMBoehm** [comment]
Adding to this: If I create the study in the first place with a relative path, it works. But I created the study with a script in '../study_folder' with:

study_name = ".example-study" # relative path to saved study
storage_name = "sqlite:///{}.db".format(study_name)
study = optuna.create_study(study_name=study_name, storage=storage_name, load_if_exists=True) # creates new db object in ../study_folder/ and overwrites old one

So it all comes down to the question of: How can I load a study that was created in a different folder? I need to use the absolute path both in creation and loading?

**Comment by fsmosca** [comment]
Try something like this.

```python
import logging
import sys

import optuna


def objective(trial):
    x = trial.suggest_float("x", -10, 10)
    return (x - 2) ** 2


# Add stream handler of stdout to show the messages
optuna.logging.get_logger("optuna").addHandler(logging.StreamHandler(sys.stdout))
study_name = "example-study"  # Unique identifier of the study.
subfolder_name = 'studies'
storage_name = f"sqlite:///{subfolder_name}/{study_name}.db"

study = optuna.create_study(study_name=study_name, storage=storage_name, load_if_exists=True)
study.optimize(objective, n_trials=3)
```
