### ISSUE TITLE
[RFC] Document policy of unit tests

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#2974]
## Motivation

Thanks to the development community, Optuna is growing continuously. Along with the growth of the code base, the test code is increasing as well. [`CONTRIBUTION.md`](https://github.com/optuna/optuna/blob/master/CONTRIBUTING.md#unit-tests) mentions the necessity of test code, but it doesn't explain how we test the code. The lack of a test policy will increase the maintenance costs of the tests.

### Explain test policy in the developer guide

The test policy should be explained in the documents for developers. If the policy can be simple, we can explain it in [`CONTRIBUTION.md`](https://github.com/optuna/optuna/blob/master/CONTRIBUTING.md#unit-tests).

The policy is completely open for discussion, and the following is just examples to promote the discussion:
- Employ parametrized tests if multiple tests functions have the same input arguments.
- Exclude tests using benchmark functions of black-box optimization from unit tests.
- Prioritize the tests using public APIs over those using private APIs if both covers changes.

### Apply test policy to existing tests

The tests for the core components of Optuna including `Study`, `Trial`, `Storage`, `Sampler`, and `Pruner` should be revised based on the test policy. The actual changes will be discussed after fixing the policy.

**Comment by toshihikoyanase** [comment]
c.f., https://github.com/optuna/optuna/pull/1987#discussion_r523723461
(http://xunitpatterns.com/Conditional%20Test%20Logic.html)

**Comment by g-votte** [comment]
Here is the initial version of Optuna Test Guidelines. Please feel free to post any feedback or suggestion.
https://github.com/optuna/optuna/wiki/Test-Guidelines

We'll continue to fix existing tests based on the guidelines above.

**Comment by HideakiImamura** [comment]
We have created the Optuna Test Guidelines in Optuna V3, and fixed some tests. Let me remove the v3 label from here.

**Comment by HideakiImamura** [comment]
@g-votte Can we close this issue?

**Comment by g-votte** [comment]
Sure, let's close.
