### ISSUE TITLE
Document exceptions (2)

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#2978]
## Motivation

There is room for improvement in the behavior and specifications of exception / error.

## Description

As long as it is Python, it is impossible to comprehensively consolidate exception / error as a specification. The mechanism that can be changed continuously is considered important. So address the following:

- [x] Clarify our policy to document exception / error
- [x] Exception / error as a specification, mainly enumerates exception handling
- [x] Remove documenting exception / error that is not a specification #3429 
- [x] Correct behavior if necessary, guarantee coverage and behavior by unit test
- [x] Add or remove new classes as needed

(edited by @himkt)

**Comment by himkt** [comment]
Albeit it is almost the same as the items listed by @hvy but let me update tasks more concretely like following:

- Update documentation to clarify undocumented exception: #3310
- Update docstring to enumerates exception handling that many users can encounter
  - it's very expensive to check all APIs in Optuna. We focus on the most core feature of Optuna: trial, study, storage
- Add unittests to replicate exceptions listed in docstrings
- (Add or remove classes as needed)

After completing these tasks we will close this issue. Please correct/comment if I misunderstand or mistake something.

**Comment by himkt** [comment]
After reading other software libraries' guideline, we found that we have to use `raises` section more carefully. The following documentations mention about documenting exceptions. NumPy documentation says that `This section (raise section) should be used judiciously, i.e., only for errors that are non-obvious or have a large chance of getting raised`.

- NumPy documentation says: https://numpydoc.readthedocs.io/en/latest/format.html#raises
- Google style guide: https://google.github.io/styleguide/pyguide.html#doc-function-raises

It would be better to reconsider our approach. This task is also related to #1618. Now I think the tasks can be boiled down to:

- Clarify our policy. We currently follow Google style docstring format. But IMO this focuses on the syntax and there is room for discussion on practice (e.g. what exceptions should be documented).
- Check current docstrings and modify if it violates the policy

**Comment by himkt** [comment]
Before | After
-- | --
<img width="955" alt="Screen Shot 2022-03-14 at 11 04 22" src="https://user-images.githubusercontent.com/5164000/158093440-bff7ee0e-e748-4aff-b46a-ce317222a2ce.png"> | <img width="1083" alt="Screen Shot 2022-03-14 at 11 14 58" src="https://user-images.githubusercontent.com/5164000/158093364-3071c928-6113-4cba-a71d-1ba2d75be68e.png">

I prototyped the documentation for https://github.com/optuna/optuna/wiki/Coding-Style-Conventions#docstrings.

**Comment by himkt** [comment]
Now we updated our coding style convention: https://github.com/optuna/optuna/wiki/Coding-Style-Conventions/3ff0fb4b68435d3aac26d88e24af32854186f56d#exceptions.

It explain when/what to document exceptions. We basically don't document exceptions that are related to validation, instead document what values are expected in `Args` section. I'll send a PR to remove mentions of exceptions that violate the policy.

**Comment by himkt** [comment]
After cleaning docstrings, we will review each exceptions documented in them are tested correctly.

**Comment by HideakiImamura** [comment]
@himkt Thanks for the cleaning! By the way, you have submitted #3480. Do you have any idea that which tests should be improved for test coverage according to the current exception convention? It is good to list up them beforehans.

**Comment by himkt** [comment]
@HideakiImamura I've updated the description of #3480 to make a list of methods. 🙋

**Comment by HideakiImamura** [comment]
@himkt Thanks for the listing up! I have been merged #3480. Do you have any idea to improve the tests? If nothing, can we close this issue?

**Comment by himkt** [comment]
> Do you have any idea to improve the tests?

For the scope of the issue, I think we finished all required items and we can close the issue now. 🌆
