### ISSUE TITLE
Tried to import 'plotly' but failed

### ISSUE THREAD

**Issue by Greco1899** [optuna/optuna#2985]
## Expected behavior
Plot of param importances of optimized study.

## Environment

- Optuna version: 2.9.1
- Python version: 3.8.5
- OS: Windows 10
- Plotly: 5.3.1

## Error messages, stack traces, or logs

```
ImportError: Tried to import 'plotly' but failed. Please make sure that the package is installed correctly to use this feature. Actual error: No module named 'plotly'.
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\Anaconda3\lib\site-packages\optuna\visualization\_plotly_imports.py in <module>
      6 with try_import() as _imports:  # NOQA
----> 7     import plotly  # NOQA
      8     from plotly import __version__ as plotly_version

ModuleNotFoundError: No module named 'plotly'

The above exception was the direct cause of the following exception:

ImportError                               Traceback (most recent call last)
<ipython-input-46-ec7b157c78f5> in <module>
----> 1 optuna.visualization.plot_param_importances(study)

~\Anaconda3\lib\site-packages\optuna\visualization\_param_importances.py in plot_param_importances(study, evaluator, params, target, target_name)
     93     """
     94 
---> 95     _imports.check()
     96     _check_plot_args(study, target, target_name)
     97 

~\Anaconda3\lib\site-packages\optuna\_imports.py in check(self)
     84         if self._deferred is not None:
     85             exc_value, message = self._deferred
---> 86             raise ImportError(message) from exc_value
     87 
     88 

ImportError: Tried to import 'plotly' but failed. Please make sure that the package is installed correctly to use this feature. Actual error: No module named 'plotly'.
```

## Steps to reproduce

1. Create objective, optimize study
2. Run optuna.visualization.plot_param_importances(study)

## Additional context (optional)

This issue here https://github.com/optuna/optuna/issues/1339 has been closed but others have continued reporting similar issues.

**Comment by nzw0301** [comment]
Can you use plolty directly not via optuna?

**Comment by fsmosca** [comment]
I use the following for visualization.

```
pip install plotly
pip install scikit-learn
pip install kaleido
```

Perhaps using matplotlib is simpler with `optuna.visualization.matplotlib.plot_param_importances(study)` and only need matplotlib. I have not tried it yet and I don't know what is the difference between matplotlib and plotly along with scikit-learn and kaleido.

**Comment by Greco1899** [comment]
> Can you use plolty directly not via optuna?

Yes I can.



> I use the following for visualization.
> 
> ```
> pip install plotly
> pip install scikit-learn
> pip install kaleido
> ```
> 
> Perhaps using matplotlib is simpler with `optuna.visualization.matplotlib.plot_param_importances(study)` and only need matplotlib. I have not tried it yet and I don't know what is the difference between matplotlib and plotly plus scikit-learn plus kaleido.

Thanks for the suggestion, plotting directly with matplotlib works for me.

**Comment by Greco1899** [comment]
> > ~\Anaconda3\lib\site-packages\optuna\visualization_plotly_imports.py in 
> > pip install plotly
> 
> I guess you used the Anaconda environment and you installed plotly with pip. I heard that such a combination could be a cause of import errors.
> 
> How about installing the plotly with conda as well?
> 
> ```
> $conda install -c plotly plotly
> $conda install -c conda-forge optuna
> ```

Thanks, I have it working now! I installed plotly with conda and also reinstalled using pip.

**Comment by euneestella** [comment]
I still have same issue after reinstall plotly with conda. 
Importing plotly and checking version works well with `import plotly` and `plotly.__version__`

**Comment by muzitache** [comment]
> I still have same issue after reinstall plotly with conda. Importing plotly and checking version works well with `import plotly` and `plotly.__version__`

so I have been applying these fixes but didn't work, turns out i needed to restart my system. This fixed my issue.

**Comment by cj2001** [comment]
Bump!

Same problem here...

**Comment by Bendrox** [comment]
same issue here

**Comment by Serendipity31** [comment]
I'm also having this issue. I have plotly installed. I can import is just fine. I'm using a virtual environment where all packages and modules have been installed using pip. 

I get this error:  File "C:\Users\usr\...1\Lib\site-packages\optuna\_imports.py", line 89, in check     raise ImportError(message) from exc_value ImportError: Tried to import 'plotly' but failed. Please make sure that the package is installed correctly to use this feature. Actual error: No module named 'plotly'.

Environment Details:
- Windows 10 Enterprise
- Plotly version 5.17.0
- Optuna version: 3.4.0

**Comment by thawn** [comment]
I had the same problem. Reinstalling plotly with mamba helped.

**Comment by manos-msdn** [comment]
I had the same issue in a mixed environment conda/uv, I think it was caused because conda was installing version 5.x of plotly, so I removed that and installed 6.x using uv, now it works, hope this helps others in future
