### ISSUE TITLE
Implement `matplotlib.plot_optimization_history` with multiple studies 

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3020]
## Motivation
As a part of https://github.com/optuna/optuna/issues/2959.

By https://github.com/optuna/optuna/pull/2807,  
- [x] `plot_optimization_history` have accepted multiple studies as `study` arguments (https://github.com/optuna/optuna/pull/3062)
- [ ] introduced `error_bar` argument. 

For consistency with Plotly backend, we would like to use the same feature with the Matplotlib backend.

## Description

Implement similar logic introduced by https://github.com/optuna/optuna/pull/2807.

**Comment by nzw0301** [comment]
Thanks to #3062, `matplotlib.plot_optimization_history` will be able to take multiple studies.

To resolve this issue, we need to introduce `error_bar` option by following https://github.com/optuna/optuna/pull/2807.

**Comment by HideakiImamura** [comment]
Let me close this issue since #3122 has been merged.
