### ISSUE TITLE
[RFC] Add `Trial.intermediate_values`

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#3030]
## Motivation

This feature request is inspired by [this question in SO](https://stackoverflow.com/questions/69641832/optuna-returns-the-last-value-not-the-best-one-for-one-trial).

`Trial` instances can report intermediate values but cannot retrieve the reported values. This limitation may sometimes be a cause of verbose objective functions. If the `Trial` class provides the `intermediate_values` property, users can simplify the objective functions as follows:

Current:
```python
def objective(trial):
    ...
    accuracies = []
    for i in range(N_ITERATIONS):
        accuracy = n_correct / N_VALID_EXAMPLES
        accuracies.append(accuracy)
        trial.report(accuracy, i)
    return max(accuracies)
```

Proposal:
```python
def objective(trial):
    ...
    for i in range(N_ITERATIONS):
        accuracy = n_correct / N_VALID_EXAMPLES
        trial.report(accuracy, i)
    return max(trial.intermediate_values)
```

## Description

Add `intermediate_values` property to the `Trial` class. The change itself will be simple. For example, we can get the intermediate values from `FrozenTrial` instances.

```python
    @property
    def intermediate_values(self) -> Dict[int, float]:
        """Return intermediate objective values.

        Returns:
            A dictionary with intermediate objective values of the trial.
        """

        return self.study._storage.get_trial(self._trial_id).intermediate_values
```

But the change may be controversial. For example, this may affect the design of Storage since this change will introduce a new pattern of data access.

Also, this issue may be related to #2849 and #2977. In the PRs, multiple processes handle intermediate values of a single trial.

**Comment by elisa-aleman** [comment]
I found this from trying to use the intermediate values for a moving average, I too agree it would be good to implement, especially since the study._storage.get_trial(x) returns the trial where x = trial.number+1, which was confusing at first.

**Comment by HideakiImamura** [comment]
We would like to resolve this issue after removing the cached storage, which is ongoing in the committers.
