### ISSUE TITLE
Update CLI tutorial

### ISSUE THREAD

**Issue by not522** [optuna/optuna#3032]
The current CLI tutorial uses deprecated features. https://optuna.readthedocs.io/en/v2.10.0/tutorial/20_recipes/004_cli.html

New features of CLI have been introduced into master. I recommend rewriting the tutorial using the ask-and-tell interface.

**Comment by hvy** [comment]
Reopening as this is still an issue.

**Comment by himkt** [comment]
@hppRC is now working on this topic. 👍

**Comment by himkt** [comment]
I talked with @hppRC and we decide to free the assignment. If someone is interested in writing a new tutorial, please feel free to comment here!

**Comment by divyanshugit** [comment]
Hi, @himkt I would love to write the tutorial. Can you please give me some tips that can help me out with getting started!

**Comment by himkt** [comment]
Thank you for your interest @divyanshugit!

The current tutorial show the usage of `optuna create_study` and `optuna study optimize`. But `optuna study optimize` was deprecated in v2.2.0 and Optuna provides other CLI command such as `optuna ask` and `optuna tell`. We want to update our CLI tutorial to use `ask-and-tell` interface. And I think it's good starting point to rewrite the tutorial with CLI `ask-and-tell`.
