### ISSUE TITLE
Add test to ensure LightGBMTuner's default arguments and LightGBM's arguments consistent

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3037]
## Motivation

Users suppose that LightGBMTuners follow the original methods' default arguments. To automatically detect the updates of the original methods, it would be great to add a test to check the Optuna's method are consistent with the original one.

## Description

Please add the test that ensures the default argument values are the same as the LightGBM's corresponding value to [`lightgbm_tuner_tests/test_optimize.py`](https://github.com/optuna/optuna/blob/master/tests/integration_tests/lightgbm_tuner_tests/test_optimize.py). More concretely, the following combination 

- [`LightGBMTuner`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTuner.html#optuna-integration-lightgbm-lightgbmtuner) and [`lightgbm.train`](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.train.html)
- [`LightGBMTunerCV`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.lightgbm.LightGBMTunerCV.html#optuna.integration.lightgbm.LightGBMTunerCV) and [`lightgbm.cv`](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.cv.html)

**Comment by abatomunkuev** [comment]
Hello! I have tried to run the testing script using the command 
```
pytest tests/integration_tests/lightgbm_tuner_tests/test_optimize.py
```
And ran into this issue.
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/55283735/139528889-4b3dfe3b-67c1-4c24-ae9a-76f14fe7aa29.png">

Could you help me resolve this issue? 
What I have done:
1. Created virtual environment 
2. Installed Optuna using `pip install -e .`
3. Run the command `pytest tests/integration_tests/lightgbm_tuner_tests/test_optimize.py`

**Comment by nzw0301** [comment]
could you install `colorlog` by using `pip install colorlog`. By the way, it would be helpful to share the output as text rather than a screenshot.

**Comment by abatomunkuev** [comment]
@nzw0301  My issue has been resolved. I have built the Docker Image. Now I am starting working on the issue!

**Comment by nzw0301** [comment]
Brilliant! I'm looking forward to reviewing your PR!
