### ISSUE TITLE
Replace #trials with `trial number`

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3042]
## Motivation

In a few visualisation methods, Optuna uses `#Trials` to represent trial id. For example, the colour bar on https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.plot_slice.html.

Personally, `#Trials` seems confusing. If the number of trials increases, I may misunderstand that `#Trials` indicates the duplicated parameter combination. Indeed, https://github.com/optuna/optuna/issues/2967 asks the meaning of `#Trials`.

## Description

~I propose using `trial id` instead of `#Trials` in `plot_slice`, `plot_pareto_front`, and `plot_optimization_history`. But I'd like to know the users and dev-member opinions before creating the PR.~

I propose using `Trial Number` instead of `#Trials` in `plot_slice`, `plot_pareto_front`, and `plot_optimization_history`

**Comment by himkt** [comment]
Let me re-open it. I agree with discussions that `#trials` could be replaced with `trial id`.

**Comment by himkt** [comment]
Asked other developers for opinions and got agreement to change `#trials` with `trial number`. Let me remove the label `needs-discussion` and add `contribution-welcome` + `good first issue`.

**Comment by nzw0301** [comment]
Thanks. I renamed the issue title and description for clarification.

**Comment by dubey-anshuman** [comment]
Hi, seems like an easy fix! I would be happy to deal with this issue!
