### ISSUE TITLE
Can't reproduce results when tuning more than one job

### ISSUE THREAD

**Issue by ualiangzhang** [optuna/optuna#3045]
When n_jobs in a study is set to be greater than one, the results cannot be reproduced after tuning based on PyTorch, but there is no problem when n_jobs=1.

Even if I added the following code to the objective function to eliminate the influence of random parameters, it does not work.

    env.seed(seed)
    np.random.seed(seed)
    random.seed(seed)

    th.manual_seed(seed)
    th.cuda.manual_seed(seed)
    th.cuda.manual_seed_all(seed)
    th.backends.cudnn.benchmark = False
    th.backends.cudnn.deterministic = True

#
- Optuna version: 2.8.0
- Python version: 3.6.5
- PyTorch version: 1.9.0
- GPU: NVDIA V100S
- OS: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-centos-7.9.2009-Core

**Comment by sitnarf** [comment]
> Hi, @nzw0301
> 
> After several days of trying, I believe I have found a solution. Perhaps, that is not perfect. I am here to give a Toy Example to illustrate how it works. In addition, I also tried this method on our RL tuning task, which can be reproduced now when using a GPU and four processes for parallel tuning.
> 
> This is not a complicated method and can be definitely further optimized. I hope that my code will inspire the official team to provide a simple and more efficient solution as soon as possible.
> 
> Thank you again, @nzw0301 and the Optuna team!
> 
> ```python
> import math
> import multiprocessing
> import optuna
> from optuna.trial import TrialState
> from joblib import dump, load
> import time as t
> from multiprocessing import Process, Queue, set_start_method
> import os
> 
> 
> def objective(trial):
>     # x = trial.suggest_float("x", -10, 10)
>     x = trial.suggest_categorical("x", [-10 + 0.1 * j for j in range(200)])
> 
>     tuned_params = trial.study.user_attrs['tuned_params']
>     if trial.params in tuned_params:
>         raise optuna.exceptions.TrialPruned()
>     else:
>         tuned_params.append(trial.params)
>         trial.study.set_user_attr('tuned_params', tuned_params)
> 
>     t.sleep(1)
>     return (x - 2) ** 2
> 
> 
> def tune(que, num_trials):
>     for _ in range(num_trials):
>         print(multiprocessing.current_process())
>         study = que.get()
>         study.optimize(objective, n_trials=1)
>         que.put(study)
>         dump(study, study.study_name + '.pkl')
> 
> 
> if __name__ == "__main__":
>     try:
>         set_start_method('spawn')
>     except RuntimeError:
>         pass
>     num_proc = 4
>     num_trials = 50
>     single_num_trials = math.floor(num_trials / num_proc)
>     tuning_name = 'study1'
>     if os.path.isfile(tuning_name + '.pkl'):
>         study = load(tuning_name + '.pkl')
>     else:
>         study = optuna.create_study(study_name=tuning_name, direction="maximize",
>                                     sampler=optuna.samplers.TPESampler(seed=0))
>         study.set_user_attr('tuned_params', [])
> 
>     dump(study, tuning_name + '.pkl')
>     q = Queue()
>     q.put(study)
> 
>     processes = [Process(target=tune, args=(q, single_num_trials)) for _ in range(num_proc)]
>     for i in range(num_proc):
>         processes[i].start()
>     for i in range(num_proc):
>         processes[i].join()
> 
>     try:
>         study = q.get()
>     except:
>         pass
> 
>     pruned_trials = study.get_trials(deepcopy=False, states=[TrialState.PRUNED])
>     complete_trials = study.get_trials(deepcopy=False, states=[TrialState.COMPLETE])
> 
>     print("Study statistics: ")
>     print("  Number of finished trials: ", len(study.trials))
>     print("  Number of pruned trials: ", len(pruned_trials))
>     print("  Number of complete trials: ", len(complete_trials))
> 
>     print("Best trial:")
>     trial = study.best_trial
> 
>     print("  Value: ", trial.value)
> 
>     print("  Params: ")
>     for key, value in trial.params.items():
>         print("    {}: {}".format(key, value))
> ```

@ualiangzhang Hey, this solution is effectively sequential, right? The study object will be used only in one process and the rest will be waiting. Thanks. :)

**Comment by ualiangzhang** [comment]
@sitnarf Yeah, I think so. I expect that the official team will provide us with a simple interface that runs in parallel in the near future.
