### ISSUE TITLE
Storage slowing down execution

### ISSUE THREAD

**Issue by tguegan** [optuna/optuna#3048]
Hi,

I have some troubles to make Optuna runs in parallel, and even in sequential but with a local storage. My test code is really simple:

```python
import optuna

def objectif(trial):
    x = trial.suggest_float("x", -10., 10.)
    y = trial.suggest_float("y", -10., 10.)

    return (x - 5)**2 + (y + 4)**2

study = optuna.create_study(direction = "minimize", study_name = "TestOptuna",\
                            load_if_exists = True)
study.optimize(objectif, n_trials = 1000)
```

Executing the previous code takes : 8,83s. Now if I add some local storage with :

```python
study = optuna.create_study(direction = "minimize", study_name = "TestOptuna",\
                            load_if_exists = True, storage = "mysql://root:#password@localhost/TestOptuna")
```

The execution takes : 2min6,6s. Same problem with sqlite.

Any idea from where the problem is coming from?
Thank you for helping me!

- Optuna version: 2.9.1
- Python version: 3.8.11
- OS: Linux-5.11.0-38-generic-x86_64-with-glibc2.17

**Comment by not522** [comment]
Here is the speed benchmark result. https://github.com/optuna/optuna/runs/4062350310?check_suite_focus=true#step:6:17
The slowing down ratio (`inmemory, random, 1000` v.s. `sqlite, random, 1000`) is about x50 in the GitHub Actions' environment.

For future development, please let me know your request? 1000 trials in 1 second?

**Comment by tguegan** [comment]
> Here is the speed benchmark result. https://github.com/optuna/optuna/runs/4062350310?check_suite_focus=true#step:6:17 The slowing down ratio (`inmemory, random, 1000` v.s. `sqlite, random, 1000`) is about x50 in the GitHub Actions' environment.
> 
> For future development, please let me know your request? 1000 trials in 1 second?

The best option would be to have the possibility to run an `inmemory` study in parallel. With this kind of option, one could easily optimize an objective function that runs fast (~ under 1s). Which is, for now, not possible due to the limitation of hard drive storage!

**Comment by nzw0301** [comment]
How about using `n_jobs!=1` to perform thread-based parallel optimisation? if it does not work due to GIL of python,  https://github.com/optuna/optuna/issues/3045#issuecomment-953954766 provides a process-based parallelisation example.

**Comment by tanweer-mahdi** [comment]
Hi, 

Is there any progress in this issue? I think this is one the strongest features of Optuna. Improving read/write time to the DB would definitely be a huge gain!

**Comment by jackandrews** [comment]
You can see throughout optuna/storages/_rdb/storage.py `with _create_scoped_session(self.scoped_session) as session` is being used whenever DB state is being mutated. Therefore each operation under the scoped_session is going to generate a DB commit, which is incredibly inefficient.

**Comment by skeenan** [comment]
+ 1 
I've also discovered this issue. Google search led me to this thread. 

Can confirm that using RDMS storage causes a 5x slow down in the performance of my experiments. This issue is real, and should be reopened.

**Comment by antonioalegria** [comment]
Hi, I'm seeing the same issue. In particular, going from local sqlite storage to a remote Postgres makes things much slower, which is a shame. I don't see why the storage should cause that much overhead, I am sure it is possible to optimize things.

**Comment by nzw0301** [comment]
@antonioalegria Optuna is an OSS; you can send a pull request if you're sure the storage can be optimised. 

Best regards,

**Comment by antonioalegria** [comment]
That is fair. Apologies if it came out sounding if you hadn't done what you could to make it efficient, I didn't mean it like that. In any case, it's a good point.
