### ISSUE TITLE
Trial time completion increases x10 with PostgreSQL

### ISSUE THREAD

**Issue by jmakov** [optuna/optuna#3053]
Starting a study on a local cluster, the trials complete in about 0.5s (the objective function has a constant runtime). At about 80k trials one trial takes about 5s to complete.

## Expected behavior
As number of trials increases the trials shouldn't take longer to complete. Is there perhaps an index missing in SQL tables?

## Environment
- Optuna version:  2.10.0
- Python version: 3.7.10
- OS: Ubuntu 21.10 (Linux-5.13.0-20-generic-x86_64-with-debian-11.0)
- (Optional) Other libraries and their versions:
PostgreSQL 12
## Error messages, stack traces, or logs

```
from the trials table:
trial_id, number, stuy_id, state, datetime_start, datetime_complete
541,540,1,COMPLETE,2021-10-28 15:44:26.864200,2021-10-28 15:44:27.202030  # took about 0.5s to complete
vs
83535,83534,1,COMPLETE,2021-10-28 17:35:33.607027,2021-10-28 17:35:38.514746  # took 5s to complete
```

## Steps to reproduce

1. prepare an objective function that always evaluates under 1s
2. run study with about 100k trials
3. observe how long a trial takes when the study reaches 10k trials, 50k trials and 100k trials (trials DB table)

**Comment by not522** [comment]
The random sampling performs in constant time. But other Optuna's feature requires the non-constant computation for each trial. See also the speed benchmark results. https://github.com/optuna/optuna/runs/4062350310?check_suite_focus=true#step:6:17

**Comment by jmakov** [comment]
Closing the issue since this is obviously expected.
