### ISSUE TITLE
Make distributed optimisation reproducible 

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3056]
## Motivation

Optuna's optimisation is reproducible if the optimisation is performed sequentially as in the FAQ page https://optuna.readthedocs.io/en/stable/faq.html#how-can-i-obtain-reproducible-optimization-results. 
In other words, distributed optimisation, `n_jobs!=1` and process-based parallelisation are not reproducible.

However, reproducibility is a highly demanded feature nowadays especially, in research https://arxiv.org/abs/2003.12206. Indeed, Optuna repo sometimes receivess such a feature request, for example, https://github.com/optuna/optuna/issues/3045.

## Description

For `n_jobs != 1` case, we might ensure that trials completed sequentially by introducing a flag to make optimisation reproducible. Of course, there are several disadvantages, for example, one of the parallelised trials takes too long time to complete the trial, such a trial becomes a bottleneck.

## Additional context (optional)

- https://github.com/optuna/optuna/issues/2937
- https://github.com/optuna/optuna/issues/2862

**Comment by smortezah** [comment]
Any progress on this?

**Comment by nzw0301** [comment]
No.

**Comment by davidhaan** [comment]
I have noticed optuna is not reproducible using pytorch if job = -1. Is this issue related and if so has it been fixed?

**Comment by nzw0301** [comment]
> Is this issue related and

Yes.

>  has it been fixed?

Unfortunately, not.
