### ISSUE TITLE
Add missing sampler and pruner classes to a tutorial page

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3072]
[Efficient Optimization Algorithms](https://optuna.readthedocs.io/en/latest/tutorial/10_key_features/003_efficient_optimization_algorithms.html) tutorial provides lists of samplers/pruners implemented in Optuna. However a few classes are not on the list. It would be great to mention them comprehensively from the tutorial pages for Optuna users. 

More concretely, please add the following entries to the tutorial page.

## Samplers

- `optuna.samplers.PartialFixedSampler`
- `optuna.samplers.NSGAIISampler`

## Pruners
- `optuna.pruners.PatientPruner`
- `optuna.pruners.PercentilePruner`

**Comment by l-e-e-l-a** [comment]
hi. would like to work on this.

**Comment by nzw0301** [comment]
@l-e-e-l-a Awesome! We're looking forward to reviewing your PR!

**Comment by sidshrivastav** [comment]
Hey @nzw0301 Please find the PR, Can I update the `tutorial/10_key_features/003_efficient_optimization_algorithms.py`, documented as part where we have added samplers is multiline and other are single line comment, which doesn't look uniform?

**Comment by nzw0301** [comment]
@sidshrivastav I'm afraid that @l-e-e-l-a has been working on this issue as he said, https://github.com/optuna/optuna/issues/3072#issuecomment-956379727...

**Comment by sidshrivastav** [comment]
> @sidshrivastav I'm afraid that @l-e-e-l-a has been working on this issue as he said, https://github.com/optuna/optuna/issues/3072#issuecomment-956379727...
> 

No problem.

**Comment by nzw0301** [comment]
> Can I update the tutorial/10_key_features/003_efficient_optimization_algorithms.py, documented as part where we have added samplers is multiline and other are single line comment, which doesn't look uniform?

You cannot do that because I suppose it does not work in my understanding as we expected.

**Comment by nzw0301** [comment]
So I won't review #3076 at this moment. Howver, if @l-e-e-l-a allowed you to take over this issue from him, I'd like to review it. Thank you for your understanding!

**Comment by l-e-e-l-a** [comment]
@nzw0301 thanku for being patient with me. have made the necessary changes and opened a pull request. hope to be quick from next time :)
