### ISSUE TITLE
How to show (non-rounded) real value in trials_dataframe?

### ISSUE THREAD

**Issue by hcvazquez** [optuna/optuna#3075]
I'm new with optuna. When I print study.trials_dataframe() the value of trials is rounded to 1 decimal.

![image](https://user-images.githubusercontent.com/16074870/139760251-025232ed-d7bc-4795-b645-7e6b3b483f4f.png)

It doesn't seem like a display problem because when I get the values ​​from the dataframe I get them rounded as well.

![image](https://user-images.githubusercontent.com/16074870/139760896-30b5a628-65a2-4bfb-ad1d-07296db3905d.png)

Is there any way to show the real value?

**Comment by nzw0301** [comment]
Hi, I'm afraid that I could not reproduce the output by using the following example based on documentation

```python
# https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.trials_dataframe

import optuna
import pandas


def objective(trial):
    x = trial.suggest_float("x", -1, 1)
    return x ** 2


study = optuna.create_study()
study.optimize(objective, n_trials=3)

# Create a dataframe from the study.
df = study.trials_dataframe()
print(df)
df.sort_values(by="value", ascending=True).value.values
```


Could you double-check that your objective function returned a rounded value or not?

**Comment by hcvazquez** [comment]
The objective function returns values ​​very close to rounded values, like 0.199999996. Then the values are rounded. This reproduce it in my machine:

```python
import optuna
import pandas

def objective(trial):
    return 0.199999996

study = optuna.create_study()
study.optimize(objective, n_trials=3)

# Create a dataframe from the study.
study.trials_dataframe().value.values
```

**Comment by nzw0301** [comment]
Thank you for sharing the code. I think the root issue comes from numpy not optuna in the given example. `numpy` has a parameter to print float value that can be changed by [`set_printoptions`](https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html). So calling `np.set_printoptions(precision=9)` before `study.trials_dataframe().value.values` shows desired float values.


For the pandas case given in the first comment, again the root issue comes from pandas, not optuna. Similarly to numpy case, pandas has a format for float value. To change the default format, I might use `pandas.options.display.float_format = "{:,.9f}".format`.

**Comment by hcvazquez** [comment]
Yes, you're right @nzw0301 . Thanks!
