### ISSUE TITLE
Display trial.user_attrs in pareto_front() when hovering over results

### ISSUE THREAD

**Issue by kasparthommen** [optuna/optuna#3081]
## Motivation
I often attach supplementary or debug information to trials using `trial.set_user_attr()`. It would be great if this information were displayed in the `pareto_front()` figures when hovering over trial dots, e.g.

```json
{
  "number": 0,
  "values": [
    -1094225.1109115006,
    0.9941898317597861,
    28362000.0
  ],
  "params": {
    "alpha": 3.5,
    "lambda": 17.5
  }
  "user_attrs": {                          <-- show user_attrs dict if filled
    "trial_date": "2021-11-04",
    "execution_time_millis": 13845,
    "some_debug_info": "foobar"
  }
}
```

I have created a corresponding PR: https://github.com/optuna/optuna/pull/3082

**Comment by nzw0301** [comment]
I reckon this PR has been resolved by the issue author thanks to #3082. Thanks! Let me close this.
