### ISSUE TITLE
`trial.report` and support for multi-objective optimization

### ISSUE THREAD

**Issue by Yard1** [optuna/optuna#3100]
Hey, I'm a developer of Ray Tune. We are using the `trial.report` method to pass objective values back to Optuna from our trainables. We have had a few users [ask](https://github.com/ray-project/ray/issues/18027) for multi-objective support for Optuna in Ray Tune, but I have seen that this is not yet possible with `trial.report`. Is there any ETA for this feature? I would be happy to submit a PR with some guidiance.

**Comment by himkt** [comment]
Hello @Yard1, thank you for raising the issue and using Optuna! As you said, we might need some discussion for the interface of multi-objective optimization.

On the other hand, I'm wondering if invoking `trial.report` could be removed from the codebase. Intermediate values reported by `trial.report` are mainly used for pruning but `OptunaSearch` disables pruing by always specifying `NopPruner` ([ref. OptunaSearch](https://github.com/ray-project/ray/blob/3e6ba5d6d2b6790e51de51511ecb4ea6d1ff36b3/python/ray/tune/suggest/optuna.py#L281)). I think Ray passes objective values using `study.tell` and it looks enough for the communication between Ray and Optuna ([ref. OptunaSearch](https://github.com/ray-project/ray/blob/3e6ba5d6d2b6790e51de51511ecb4ea6d1ff36b3/python/ray/tune/suggest/optuna.py#L400).

I'm not familiar with Ray internal so please correct me if I have missed something (e.g. using intermediates stored in Optuna storage for something in Ray).

**Comment by Yard1** [comment]
Hey, thanks for the response! I will see if removing the report call has any negative impact. You are correct in your assessment, and now that I look at it, I agree that just `tell` should be sufficient. Will get back to you on that!

**Comment by Yard1** [comment]
Hey, @himkt, thanks a lot. I was able to add the necessary functionality in https://github.com/ray-project/ray/pull/20489. Thanks!
