### ISSUE TITLE
how to measure the time of one study trial and avoid OOM?

### ISSUE THREAD

**Issue by showkeyjar** [optuna/optuna#3102]
## Motivation

I want find a strategy to avoid long time cost and OOM when use optuna.

## Description

I use optuna to find xgboost best hyper parameters, 

but I found when the tree is big and deep It usually waste time for search.

so I want to know if optuna can measure the time cost and memory of one trial?

if the time is too much of one trial, or memory is too big, 

then I think it can stop and no need to try the bigger parameter trials

## Alternatives (optional)

or if I can set a timeout parameter of one trial, if timeout, then skip this trial?

or if I can check the system memory usage, if memory exhaust，then skip this trial?

**Comment by himkt** [comment]
Hello @showkeyjar, https://github.com/optuna/optuna/issues/2969 might be related. In Optuna, you can penalize a large model or try constrained optimization to make Optuna less suggest a parameter to create a huge model.

**Comment by showkeyjar** [comment]
@himkt thanks for your reply, I use those strategies to my project, but it sames useless.

the time also waste for big search, and OOM still happen and can not be catched

**Comment by himkt** [comment]
@showkeyjar 

> the time also waste for big search

Hmm, sorry to hear that. You have to implement a method to estimate memory usage based on hyperparameters...
(it is out of Optuna's scope)

> OOM still happen and can not be catched

You can specify exceptions that you don't want to stop an optimization.
https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize

```python
import optuna


def objective(trial):
    x = trial.suggest_float("x", -1, 1)
    return x ** 2


study = optuna.create_study()
study.optimize(objective, n_trials=3, catch=(SomeMemoryException,))
```

**Comment by showkeyjar** [comment]
ok, I'll have a try.

**Comment by showkeyjar** [comment]
I found that 'timeout' parameter is good to use.

catch some MemoryException is not working well, 

because when memory has exhausted, linux will kill processes, and the program will crash

whatever use 'try catch' or not.
