### ISSUE TITLE
Initialize new search with known observations

### ISSUE THREAD

**Issue by BugsBuggy** [optuna/optuna#3104]
Hello,
I wondered whether Optuna supports starting a search based on previous trials that are not run in Optuna. I.e. I know some configurations and their associated scores and want to initialize a new search based on those trials.

It is clear to me that we can save the study and reuse it, e.g. with a different sampler. But how to inject the known observations into the study in the first place?

**Comment by himkt** [comment]
Hello @BugsBuggy, how about using `add_trial` to append completed trials to the study.

- create_trial: https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.create_trial.html#optuna.trial.create_trial
- add_trial: https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html?highlight=enqueue_trial#optuna.study.Study.add_trial

**Comment by BugsBuggy** [comment]
Great, exactly what I was looking for!
