### ISSUE TITLE
optuna.visualization.plot_optimization_history(study) in Spyder

### ISSUE THREAD

**Issue by borisRa** [optuna/optuna#3110]
Hi,

How can I see the visualization outputs from **Spyder** ?
For example after this command `optuna.visualization.plot_optimization_history(study)` , no plots are appearing .

Thanks,
Boris

**Comment by nzw0301** [comment]
Could you try this https://stackoverflow.com/questions/35315726/plotly-how-to-display-charts-in-spyder ?
