### ISSUE TITLE
Remove flush update functionality from _CachedStorage

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#3112]
## Motivation

_CachedStorage is designed to store multiple [updates](https://github.com/optuna/optuna/blob/master/optuna/storages/_cached_storage.py#L44) and commit them at once by [_flush_trial](https://github.com/optuna/optuna/blob/master/optuna/storages/_cached_storage.py#L417). However, due to the change of the design, _CachedStorage currently only stores some updates in the [set_trial_values](https://github.com/optuna/optuna/blob/master/optuna/storages/_cached_storage.py#L292-L301), and does not in the other methods. It means that we no longer need the flush update functionality in _CachedStorage.

## Description

Remove flush update functionality from _CachedStorage:

- [self.updates](https://github.com/optuna/optuna/blob/master/optuna/storages/_cached_storage.py#L44)
- Flush update implementation in each method e.g. https://github.com/optuna/optuna/blob/master/optuna/storages/_cached_storage.py#L198-L215
- [_flush_trial](https://github.com/optuna/optuna/blob/master/optuna/storages/_cached_storage.py#L417)
- [_get_updates](https://github.com/optuna/optuna/blob/master/optuna/storages/_cached_storage.py#L362)
- [_update_trial](https://github.com/optuna/optuna/blob/c4ebc0394f3996720b8cd0829edfa8630d1b99c1/optuna/storages/_rdb/storage.py#L624)

## TODOs
- [ ] Remove flush update functionality from _CachedStorage
- [ ] Compare the speed benchmark between master and this branch

## Additional context (optional)

- By resolving the issue, 
    - we can reduce requirements for storages to be wrapped by _CachedStorage.
    - Also, we can get rid of some lines of code from  _CachedStorage.

**Comment by HideakiImamura** [comment]
@keisuke-umezawa Is this issue completed by #3120?

**Comment by keisuke-umezawa** [comment]
Yes!
