### ISSUE TITLE
Preemptible instances support of `optuna tell`.

### ISSUE THREAD

**Issue by ytsmiling** [optuna/optuna#3130]
## Motivation

When using optuna ask&tell on preemptible instances, `optuna tell` can raise `RuntimeError` on preemption because the trial can be already in one of `finished state` after preemption.

```shell
... # Some codes
optuna tell --storage $OPTUNA_STORAGE --study-name mystudy --trial-number 0 --values 1.0  # error in the second run
# <- preemption in the first run
... # Other codes
```

## Description

Return a different exit code when the trial is already in a `finished state` so that users can distinguish errors caused by preemption and others (e.g., connection error to DB).

## Alternatives

* Check the trial's state and values first and avoid calling `study.tell()` when the requested (state, values) are identical to the current value of the trial.
  * Concern: Comparison of values can be problematic due to precision issues of numerical values.
* Guide users to write python script and use `study.tell` + `try-catch` on preemptible instances. (I'm currently using this.)

## Additional context

I'm not quite sure a common way to handle this kind of situation and love to hear others' voice.

**Comment by hvy** [comment]
Do you think it's common to then branch the post-tell logic depending on the error code here? We could also as an additional alternative add an option like `--skip-if-told`, which would be similar to `optuna create-study`'s `--skip-if-exists`.

**Comment by ytsmiling** [comment]
> We could also as an additional alternative add an option like `--skip-if-told`, which would be similar to `optuna create-study`'s `--skip-if-exists`.

Thanks for the reply. This option sounds more consistent and clear.

**Comment by hvy** [comment]
It should be easy to implement, let me work on that.

**Comment by hvy** [comment]
Created a PR https://github.com/optuna/optuna/pull/3131. Renamed the option to `--skip-if-finished` and aligned the logic to use `TrialState.if_finished()` for the condition.

**Comment by ytsmiling** [comment]
Thank you for creating the PR! Let me take look.
