### ISSUE TITLE
NSGA-II crossover parameter follow up tasks

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#3133]
## Motivation

A `crossover` parameter is to be added to the NSGA-II sampler as seen in https://github.com/optuna/optuna/pull/2903. This PR expects a follow up PR that addresses the following https://github.com/optuna/optuna/pull/2903#issuecomment-964736529. 

- [x] Make crossover functions as Python classes for maintainability.
- [ ] Add UNDX-m implementation.
- [ ] Add tests to align other samplers' tests (if necessary)

as well support for `{Int,Float}Distribution`, two recently introduced new distributions..

## Description

Address the tasks described under motivation.

**Comment by xadrianzetx** [comment]
> Make crossover functions as Python classes for maintainability.

I'll work on refactoring those in near future.

**Comment by g-votte** [comment]
Since this issue has been open for a long time, let me close once. Feel free to reopen upon necessity.
