### ISSUE TITLE
In lightgbm_tuner_simple.py example early stopping is not working properly.

### ISSUE THREAD

**Issue by tyama711** [optuna/optuna#3145]
In lightgbm_tuner_simple.py example, early stopping is not working properly as follows.
For example, I got the following log by execute lightghtgbm_tuner_simple.py.
```
# First trial
[1]	valid_0's binary_logloss: 0.581604	valid_1's binary_logloss: 0.587863
...
[43]	valid_0's binary_logloss: 0.0236828	valid_1's binary_logloss: 0.145822
...
[143]	valid_0's binary_logloss: 4.13863e-05	valid_1's binary_logloss: 0.265754
Early stopping, best iteration is:
[43]	valid_0's binary_logloss: 0.0236828	valid_1's binary_logloss: 0.145822
# Early stopping works fine in first trial.

# Second trial
[1]	valid_0's binary_logloss: 0.580784	valid_1's binary_logloss: 0.586189
[2]	valid_0's binary_logloss: 0.514544	valid_1's binary_logloss: 0.524775
...
[43]	valid_0's binary_logloss: 0.0207709	valid_1's binary_logloss: 0.149757
...
[143]	valid_0's binary_logloss: 3.01071e-05	valid_1's binary_logloss: 0.318618
Early stopping, best iteration is:
[43]	valid_0's binary_logloss: 0.0236828	valid_1's binary_logloss: 0.145822
# Early stopping does not work correctly in second trial. It seems to the result of the first trial.
```
I think this case is because early_stopping() function creates a closure and variables in the closure are shared between each trials.
If I use early_stopping_rounds parameter instead of early_stopping callback, early stopping works properly even though the following warning is displayed.
```
UserWarning: 'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
  _log_warning("'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. "
```

## Environment

- Optuna version: 2.10.0
- Python version: 3.8.18
- OS: Ubuntu 20.04.2

**Comment by nzw0301** [comment]
I suppose `lightgbm.callback.early_stopping` stores the values used in the early stopping algorithm according to the [its source code](https://lightgbm.readthedocs.io/en/latest/_modules/lightgbm/callback.html#early_stopping). But the current implementation reuses the callback among trials as the issue creator reported. I think we need to create a patch that resets the callback after each trial somehow.

**Comment by nzw0301** [comment]
I investigated this a little bit. `lightgbm.callback.early_stopping` returns a function accessing local variables defined in `lightgbm.callback.early_stopping`, so `copy.deepcopy` does not work.

**Comment by nzw0301** [comment]
I suppose https://github.com/microsoft/LightGBM/pull/4868 resolves this issue.

**Comment by nzw0301** [comment]
LightGBM 3.3.2 does not include the change. I need to wait for the fix.

**Comment by pseudotensor** [comment]
Using code changes in https://github.com/optuna/optuna/issues/3646 and latest master optuna/lightgbm, it seems to be working.  For exactly the same user code/data/etc. I don't see the dragged-out iterations far beyond the best score anymore.
