### ISSUE TITLE
`Studt.tell` with `skip_if_finished`

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#3146]
## Motivation

Keep the `Study.tell` API consistent with `optuna tell` CLI.

## Description

Add a `skip_if_finished: bool` option to `Studt.tell`, similar to `optuna tell` the CLI subcommand, that allows `Study.tell` to become a NOOP instead of raising an error in case e.g. a trial is reported twice.

See https://github.com/optuna/optuna/pull/3131.

**Comment by xadrianzetx** [comment]
I'm happy to implement it.

**Comment by hvy** [comment]
That'd be great, and I'd be happy to review.
