### ISSUE TITLE
`suggest_uniform` for large number of parameters is slow

### ISSUE THREAD

**Issue by shiba24** [optuna/optuna#3151]
Hello Optuna team - thank you for creating this great library. I'm one of heavy user.

## Summary

I have a question regarding the speed of `suggest_uniform` function (the actual problematic part is `set_trial_param` ).
tldr, `trial.suggest_uniform` gets really slow when the number of parameters are large.

### Environment

- Optuna version: 2.10.0
- Python version: 3.9.7
- OS: M1 Mac Book Pro (2020), macOS-12.0.1-arm64-arm-64bit

### Steps to reproduce

Here is my script. I am putting `n_param` as a variable so that I can change it for investigation.

```python
from src import utils # my code - please ignore

import optuna

n_param = 100000

def sphere(**kwargs):
    val = 0
    for x in kwargs.values():
        val += x ** 2
    return val

@utils.profile(
    output_file=f"result{n_param}.prof", sort_by="cumulative", lines_to_print=300, strip_dirs=True
)
def func(trial):
    xs = {f'x{d}': trial.suggest_uniform(f'x{d}', -10, 10) for d in range(n_param)}
    return sphere(**xs)

study = optuna.create_study(direction="minimize")
study.optimize(func, n_trials=1)
```

Note: The `utils.profile()` is my custom profiler decorator to investigate the root cause of this problem. I'm not sharing the code detail here but you'll see the profile result later.

### Experiment result

I've tested the above script with
- n_param = 1
- n_param = 1000
- n_param = 100000

Here are the profiles.

#### n_param = 1

```
         161 function calls in 0.000 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.000    0.000 optuna_test.py:14(func)
        1    0.000    0.000    0.000    0.000 optuna_test.py:18(<dictcomp>)
        1    0.000    0.000    0.000    0.000 _trial.py:180(suggest_uniform)
        1    0.000    0.000    0.000    0.000 _trial.py:699(_suggest)
        1    0.000    0.000    0.000    0.000 sampler.py:397(sample_independent)
        1    0.000    0.000    0.000    0.000 _random.py:61(sample_independent)
        1    0.000    0.000    0.000    0.000 {method 'uniform' of 'numpy.random.mtrand.RandomState' objects}
        1    0.000    0.000    0.000    0.000 _transform.py:64(__init__)
        1    0.000    0.000    0.000    0.000 _in_memory.py:246(set_trial_param)
        1    0.000    0.000    0.000    0.000 _transform.py:162(_transform_search_space)
        3    0.000    0.000    0.000    0.000 copy.py:66(copy)

```

#### n_param = 1000

```
         149012 function calls in 0.051 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    0.051    0.051 optuna_test.py:14(func)
        1    0.000    0.000    0.051    0.051 optuna_test.py:18(<dictcomp>)
     1000    0.003    0.000    0.050    0.000 _trial.py:180(suggest_uniform)
     1000    0.002    0.000    0.044    0.000 _trial.py:699(_suggest)
     1000    0.001    0.000    0.027    0.000 sampler.py:397(sample_independent)
     1000    0.001    0.000    0.021    0.000 _random.py:61(sample_independent)
     1000    0.003    0.000    0.013    0.000 _in_memory.py:246(set_trial_param)
     1000    0.001    0.000    0.009    0.000 _transform.py:64(__init__)
     1000    0.003    0.000    0.009    0.000 _transform.py:162(_transform_search_space)
     3000    0.002    0.000    0.008    0.000 copy.py:66(copy)

```

#### n_param = 100000

```
         14900012 function calls in 206.881 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.012    0.012  206.881  206.881 optuna_test.py:14(func)
        1    0.240    0.240  206.864  206.864 optuna_test.py:18(<dictcomp>)
   100000   91.553    0.001  206.624    0.002 _trial.py:180(suggest_uniform)
   100000    0.402    0.000  114.020    0.001 _trial.py:699(_suggest)
   100000    0.856    0.000  106.677    0.001 _in_memory.py:246(set_trial_param)
   300000    0.319    0.000  105.388    0.000 copy.py:66(copy)
   200000  104.544    0.001  104.544    0.001 {method 'copy' of 'dict' objects}
   100000    0.233    0.000    6.465    0.000 sampler.py:397(sample_independent)
   100000    0.242    0.000    4.920    0.000 _random.py:61(sample_independent)
   100000    1.121    0.000    2.092    0.000 {method 'uniform' of 'numpy.random.mtrand.RandomState' objects}
```

And I don't think the performance of the `suggest_unform` is linear as per n_param - which is slightly counter intuitive to me (although I don't know the details of `suggest_` functions, so it could be wrong). **Especially `set_trial_param` takes less than 1 ms when n_params = 1, 13 ms when n_params = 1000, and more than 100 sec for n_params = 100000.**

### Drill-down of the cause

I think, the `copy.copy`s of the dictionary is the root cause.  [This](https://github.com/optuna/optuna/blob/master/optuna/storages/_in_memory.py#L270-L274) part is Optuna code of the problem.

In the `n_param = 100000` result, we have `100000` times `set_trial_param` calls which invokes `300000` times `copy.copy`, which includes `200000` of dict copy (and `100000` times of list copy). But the dict is the problem here. you see the `{method 'copy' of 'dict' objects}` consumes most of the processing time in `_suggest` function.

I think the copy of dictionary in python is a bit tricky. you can find some stackoverflows and articles around it (for example, [this](https://stackoverflow.com/questions/5861498/fast-way-to-copy-dictionary-in-python) - but there must more detials and articles about that I believe)

So here are my questions;

- Could anyone double-check the behavior and my investigation? I want to make sure that I'm not into the wrong direction.

- Is there alternative way of the copies to improve the speed? (i.e. even using `dict.copy()` instead of `copy.copy` could improve the speed, according to the stackoverflow linke that I shared above?) Or, suppose we know the actual data structure of the `trial` object, do we really need to use `copy.copy` function, which is generic -- is designed to copy any dict object? Or is it something that we can't improve?

## Miscellaneous

- Not tested other `suggest_*` functions, but I'd assume the same problem may exist.

- I understand such large n_param is not something Optuna's popular usecase. I just found the could-be root cause and that seems a bit more generic than I thought, so I posted here.

- If you want to reproduce exact my script above, I can share my `utils.profile` as well.

Thank you!

**Comment by not522** [comment]
Thank you for your investigation. `copy.copy` is introduced by #1139 for thread safety. It guarantees that obtained trials will not be changed by other threads.
It actually needs O(n_trials^2) computations. I'm not sure it will be problem in real use cases.

**Comment by not522** [comment]
> Thank you for your quick reply.
Yes, I understand it's not common use-case, but I do need it for some ablation study of my current project.

Thank you for your feedback! It helps to set priority of this issue.

> You meant O(n_param ^ 2) ?

Ooops, yes, O(n_param^2).

> And, do you have any plan to take a look into this in near future?

Currently we have no plan to resolve this issue, but v3 issue #2943 is a chance to discuss it.

**Comment by shiba24** [comment]
Understood, thank you for the info.
Please let me know if there's anything that I could help on this issue from my side :)

**Comment by not522** [comment]
Inheriting `InMemoryStorage` will be a workaround for this problem. Following code dramatically reduces the running time.

```python
class MyInMemoryStorage(optuna.storages.InMemoryStorage):
    def set_trial_param(
        self,
        trial_id: int,
        param_name: str,
        param_value_internal: float,
        distribution: optuna.distributions.BaseDistribution,
    ) -> None:

        with self._lock:
            trial = self._get_trial(trial_id)

            self.check_trial_is_updatable(trial_id, trial.state)

            study_id = self._trial_id_to_study_id_and_number[trial_id][0]
            # Check param distribution compatibility with previous trial(s).
            if param_name in self._studies[study_id].param_distribution:
                distributions.check_distribution_compatibility(
                    self._studies[study_id].param_distribution[param_name], distribution
                )

            # Set param distribution.
            self._studies[study_id].param_distribution[param_name] = distribution

            # Set param.
            # trial = copy.copy(trial)
            # trial.params = copy.copy(trial.params)
            trial.params[param_name] = distribution.to_external_repr(param_value_internal)
            # trial.distributions = copy.copy(trial.distributions)
            trial.distributions[param_name] = distribution
            # self._set_trial(trial_id, trial)

study = optuna.create_study(storage=MyInMemoryStorage())
```

Please note it will cause some trouble with multi-threading, i.e., `n_jobs` in `study.optimize`.

**Comment by shiba24** [comment]
@not522 Thank you for your suggestion! I confirmed it worked well in my use-case for now :))
