### ISSUE TITLE
Can you guarantee Optuna to use default parameters as a trial?

### ISSUE THREAD

**Issue by rydevera3** [optuna/optuna#3152]
Hello all,

First of I am a big fan of Optuna. I have a simple question. When I am running Optuna is there a way to guarantee we use the default parameters as one of the trials? Or would you have to run a single separate model and add it to the study? I have not been able to find anything concrete on this question. Thank you 🙂

**Comment by not522** [comment]
Yes, you can specify the parameters using [`enqueue_trial`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.enqueue_trial).

**Comment by rydevera3** [comment]
@not522 thank you!
