### ISSUE TITLE
Optuna takes hours to start new trial: The time to start a trial increases with every new trial of the study

### ISSUE THREAD

**Issue by SEMPAI-MBT** [optuna/optuna#3153]
Hello everyone, 

we are using the MOTPE algorithm with 9 objectives and while the first 100 trials are started nearly instantly, around the 200th trial a simple trial.suggest() at the beginning of the new trial takes around 1.5 hours.

```python
    def objFct(self, trial):
        
        clear_output(wait=True)
        
        MDL.testGPU()
        print ("\n")
        
        trial_time = TicToc()
        trial_time.tic()
        print ("select config based on history")
        hp_complexity_ordered = trial.suggest_int('complexity', 0, 7) ### this is where it gets complicated
        print("1")
```
-> it takes an hour to print "1".

is this already known for MOTPE or more general multi-objective optimization with Optuna? Is that possibly a very hard search for the next suggestion?
We needed quite a while to optimize the NN in pytorch for a speedup and now unfortunately Optuna brings us in troubles :-)

If this is not known and also no solution at hand, are there other variants for MO optimization that are preferred? (e.g. Ray-Tune?)

Thank you so much for your help in a research project

**Comment by not522** [comment]
Yes, "many" objective optimization in Optuna takes a long time to suggest parameters. These algorithms require exponential time of the number of objectives. I'm not sure how many objectives can be efficiently executed, but four or more may be difficult.

**Comment by nzw0301** [comment]
I think the question was answered two months ago and no updates since it. Let me close this issue once. However, please feel free to re-open by sharing more information.
