### ISSUE TITLE
NSGAIISampler not suited for multiprocessing / joblib?

### ISSUE THREAD

**Issue by cryptocoinserver** [optuna/optuna#3162]
I tried using multiprocessing / joblib with optunas NSGAIISampler.

It works as far as the trials run on multiple cpus. They all run on the same parameter set though. 
Did I do something wrong there or is the NSGAIISampler just not suited for parallel optimization?

Thank you.

**Comment by cryptocoinserver** [comment]
This is my Joblib code: https://github.com/cryptocoinserver/jesse-optuna/blob/master/jesse_optuna/JoblilbStudy.py
Thanks to the community member, that posted it here!

**Comment by sile** [comment]
I'm not sure but you might need to call `Sampler.reseed_rng()` for each joblib worker as [optuna/study/_optimize.py#L141](https://github.com/optuna/optuna/blob/f1cf51df6f945820a3d5fcc687c96d2c3587e366/optuna/study/_optimize.py#L141) does when `n_jobs > 1`. Without the call, all sampler instances among workers could use the same random seed.

**Comment by sile** [comment]
Looking at your code (`Joblib Study`), I feel that my comment above is irrelevant.
For your question, I think that `NSGAIISampler` can work with joblib as I frequently use the sampler with distributed optimization (8 or more workers).

If you can share an example code to reproduce the problem, we will investigate it in more detail.

**Comment by cryptocoinserver** [comment]
You are a genius! `study.sampler.reseed_rng()` worked. 
```
    def _optimize_study(self, func, n_trials, **optimize_parameters):
        study_parameters = copy.copy(self.study_parameters)
        study_parameters["study_name"] = self.study.study_name
        study_parameters["load_if_exists"] = True
        study = optuna.create_study(**study_parameters)
        study.sampler.reseed_rng()
        study.optimize(func, n_trials=n_trials, **optimize_parameters, catch=(Exception,))
```

**Comment by sile** [comment]
🎉
