### ISSUE TITLE
How to re-route logging from stderr to stdout on Ubuntu

### ISSUE THREAD

**Issue by eafpres** [optuna/optuna#3164]
I'm using Optuna 2.10.0 on Ubuntu 20.04
The logging info seems to go to stderr
I would like it to go to stdout
I can see how to disable the default handler
But I'm unclear on how to change it to to go stdout

## Information for reproducibility (optional)

```
import optuna
from optuna.samplers import TPESampler
from joblib import Parallel, delayed
...

def optimize_xgboost(n_trials, ... , study_name):
#
    study = optuna.load_study(study_name = study_name,
                              storage = 'sqlite:///' + study_name + '.db')
    study.optimize(lambda trial:
           train_xgboost(trial, ..., study),
           n_trials = n_trials, timeout = None)

r = ((Parallel(n_jobs = -1, backend = 'threading')
      ([delayed(optimize_xgboost)(trials_per_thread, ... , study_name)
        for _ in range(parallel_threads)])))
```
### Environment

optuna 2.10.0
python 3.8
Ubuntu 20.04

**Comment by nzw0301** [comment]
Since your code is not reproducible, but [this redirect](https://stackoverflow.com/a/49747258/2406562) might resolve it.

**Comment by eafpres** [comment]
I will try the redirect methods.

**Comment by eafpres** [comment]
I confirm this solution allows me to accomplish what I needed
