### ISSUE TITLE
test_contour Plotly and Matplotlib generate different figures

### ISSUE THREAD

**Issue by belldandyxtq** [optuna/optuna#3189]
contour is tested with both [plotly](https://github.com/optuna/optuna/blob/master/tests/visualization_tests/test_contour.py) and [matplotlib](https://github.com/optuna/optuna/blob/master/tests/visualization_tests/matplotlib_tests/test_contour.py). However, the two tests generate two totally different figures, with different number of dots.
![matplotlib1](https://user-images.githubusercontent.com/5637270/146667864-48215549-4c66-4c3d-8fad-2cc7cb366fa3.png)
![plotly](https://user-images.githubusercontent.com/5637270/146667865-4e7aa236-c8b8-4988-a848-08918bd51b13.png)

## Expected behavior
Two similar figures

## Environment
$ python -c 'import optuna; print(optuna.__version__)'

3.0.0a1.dev
$ python -c 'import platform; print(platform.python_version())'
3.6.9
$ python -c 'import platform; print(platform.platform())'
Linux-5.4.0-56-generic-x86_64-with-Ubuntu-18.04-bionic

## How to reproduce
1. Use the following path to save the figure
```
diff --git a/tests/visualization_tests/matplotlib_tests/test_contour.py b/tests/visualization_tests/matplotlib_tests/test_contour.py
index dd641fd4..6f49c07a 100644
--- a/tests/visualization_tests/matplotlib_tests/test_contour.py
+++ b/tests/visualization_tests/matplotlib_tests/test_contour.py
@@ -10,6 +10,7 @@ from optuna.trial import Trial
 from optuna.visualization.matplotlib import plot_contour
 from optuna.visualization.matplotlib._contour import _create_zmap
 from optuna.visualization.matplotlib._contour import _interpolate_zmap
+import matplotlib.pyplot as plt


 def test_create_zmap() -> None:
@@ -105,6 +106,7 @@ def test_plot_contour(params: Optional[List[str]]) -> None:
             assert len(figure.get_lines()) == 0
         elif len(params) == 2:
             assert len(figure.get_lines()) == 0
+            plt.savefig("matplotlib.png")
     elif params is None:
         assert figure.shape == (len(study.best_params), len(study.best_params))
         for i in range(len(study.best_params)):
diff --git a/tests/visualization_tests/test_contour.py b/tests/visualization_tests/test_contour.py
index a7b5c6e5..0aca776b 100644
--- a/tests/visualization_tests/test_contour.py
+++ b/tests/visualization_tests/test_contour.py
@@ -90,6 +90,7 @@ def test_plot_contour(params: Optional[List[str]]) -> None:
             assert figure.data[1]["y"] == (2.0, 1.0)
             assert figure.layout["xaxis"]["range"] == (0.925, 2.575)
             assert figure.layout["yaxis"]["range"] == (-0.1, 2.1)
+            figure.write_image("plotly.png")
     else:
         # TODO(crcrpar): Add more checks. Currently this only checks the number of data.
         n_params = len(params) if params is not None else 4
```
2. run pytest `visualization_tests$ pytest test_contour.py matplotlib_tests/test_contour.py`

**Comment by belldandyxtq** [comment]
A part of https://github.com/optuna/optuna/issues/2959

**Comment by HideakiImamura** [comment]
Thanks for rising an issue. This is due to the difference between the tests of plotly and that of matplotlib. Could you fix the test at first?

**Comment by belldandyxtq** [comment]
Sure, this is the fix https://github.com/optuna/optuna/pull/3192

**Comment by HideakiImamura** [comment]
Let me close this issue since #3192 has been  merged.
