### ISSUE TITLE
Make tests of Plotly and Matplotlib backends consistent

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3208]
## Motivation

This is a sub-issue of https://github.com/optuna/optuna/issues/2959.

Tests cases are inconsistent between two visualisation backends: Plotly or Matplotlib. This inconsistency might cause an expected bug. In addition, we find it difficult to maintain asymmetric tests.

## Description

Please unify the test cases between both functions. For example, if either test file does not perform a test that has been done by the other, please add a test case. Note that the missing test case might be function level or fine-grained level.

**Comment by HideakiImamura** [comment]
Let me close this issue since we have completed all of these items and released Optuna v3.0!!! Thank you all for your contributions!!!
