### ISSUE TITLE
Unify the test style among test files of the same visualization backend

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3209]
## Motivation

This is a sub-issue of #2959.

Thanks to optuna community, visualization tests have been improving. However, in some test cases, optuna's codebase is using different methods. For example, 

- `figure.get_lines` versus `figure.findobj(Pathcollection)` in matplotlib's tests.
- `np.array_eqaul` vs `assert_almost_equal`

This inconsistency might cause an unexpected bug. In addition, we find it difficult to maintain asymmetric tests.

## Description

Please unify the used methods among the test files of the same visualization backend rather than using different methods to do the same thing.

## Additional context (optional)

This PR should be resolved after resolving https://github.com/optuna/optuna/issues/3208.

**Comment by HideakiImamura** [comment]
Let me close this issue since we have completed all of these items and released Optuna v3.0!!! Thank you all for your contributions!!!
