### ISSUE TITLE
A question on GridSampler 

### ISSUE THREAD

**Issue by fsmosca** [optuna/optuna#3211]
In the example code below taken from [docs](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.samplers.GridSampler.html),

```python
import optuna


def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_int("y", -100, 100)
    return x ** 2 + y ** 2


search_space = {"x": [-50, 0, 50], "y": [-99, 0, 99]}
study = optuna.create_study(sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)
```

I know that "x" can take values from -100 to 100, but what is `-50, 0 and 50` in the search_space `{"x": [-50, 0, 50], ...]}`?

**Comment by not522** [comment]
The document says `GridSampler does not take care of a parameter’s quantization specified by discrete suggest methods but just samples one of values specified in the search space`. `GridSampler` ignores the arguments of the suggest methods and uses the values of `search_space`.

**Comment by fsmosca** [comment]
So in that example respecting the suggest_type(), the search_space should have been:
```python
search_space = {"x": list(range(-100, 101)), "y": list(range(-100, 101))}
```
Is that right?

**Comment by fsmosca** [comment]
I did saw that note but it is close to the second example. I now understand that the parameter value will be in a list format.

In the example it uses `trial.suggest_float()` while in the search space it uses an integer. This added to my confusion as well. I would like to suggest to improve this example by the following code. Also search space is now according to the suggest_type() limits.

I believe the example should be presented to be as simple and consistent as much as possible and not to make it looks like the search space is the boss and trial suggest is not.

```python
import optuna


def objective(trial):
    x = trial.suggest_int("x", -100, 100)
    y = trial.suggest_int("y", -100, 100)
    return x ** 2 + y ** 2


search_space = {"x": list(range(-100, 101)), "y": list(range(-100, 101))}
study = optuna.create_study(sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)
```

At the top of this example there is:
`With GridSampler, the trials suggest all combinations of parameters in the given search space during the study.`

I would like to suggest to change the tense to future.

`With GridSampler, the trials will suggest all combinations of parameters in the given search space in the study.`
