### ISSUE TITLE
A high level question on HPO

### ISSUE THREAD

**Issue by guanqun-yang** [optuna/optuna#3214]
I am trying to train a text classifier on some custom datasets.

I tried to use `optuna` with `transformers` through `trainer.hyperparameter_search()`. It is **extremely useful** (thank you for the great tool!) and gives me a substantial improvement: an accuracy from 70% to more than 85%.

But as my dataset is huge (several GBs), the runtime for HPO is long. So now I have two choices

1. Keep the data unchanged and use small number of trials (this is what I do now). But due to long runtime, the number of trials could only be like 10.
2. Subsample the data to manageable size and choose a larger number of trials (for example, a few hundred).

I am wondering which option is the correct one and potentially gives me even better results.

**Comment by nzw0301** [comment]
1. Clearly, this is the ideal way. Pruners might be useful to make optimisation faster. Note that the default sampler, TPE, is actually doing a random search for the first `n_startup_trials = 10` trials. 
2. The optimal hyperparameters can be changed when the number of samples decreases compared to the whole dataset.

**Comment by nzw0301** [comment]
I believe that I've answered the question, so let me close this issue once. But please feel free to re-open this issue if you have a still question on this topic or suggestions to improve optuna.

Best regards,
