### ISSUE TITLE
Parallelization Depreceated

### ISSUE THREAD

**Issue by ThomasWolf0701** [optuna/optuna#3220]
As 2.7 seems to have deprecated n_jobs how to do parallelization now, what to do now ?

So far i have been using:
```python
study = optuna.create_study(sampler=sampler,storage='sqlite:///example_loky.db')

with parallel_backend('loky'):
    study.optimize(cat_objective, n_trials=niter, n_jobs=njobs_optuna,gc_after_trial=True)
```

So far this worked well. The tutorial offers a new solution but this literally suggest to manually open multiple terminals.
This is not really feasible in an automized setting where everything is handled from within Python. Also there are multiple preprocessing steps also in the scripts not just model training.

Would it be possible to choose a process based backend for paralellization ?
From my understanding loky uses forking on Linux instead of thread based paralleization ?

I´ve been using mlr3 in R so far and parallelization was pretty easy without setting up a database or starting multiple terminals. Even for bayesian optimization. While Optuna is really amazing, parallelization seem overly complicated and changing all the time.

**Comment by nzw0301** [comment]
As in https://github.com/optuna/optuna/issues/2937, Optuna plans to re-introduce the `n_jobs` option. So you can use this as the latest stable optuna.

**Comment by nzw0301** [comment]
I suppose the issue creator looks happy with my answer, so let me close this issue. Please feel free to re-open to ask the further question on `n_jobs`.
