### ISSUE TITLE
Why do you refer to p(x|y) as likelihood?

### ISSUE THREAD

**Issue by takassh** [optuna/optuna#3224]
Hi, I'm a student at Waseda University.
I'm majoring in machine learning and Bayesian.
I have a question about "likelihood"

this line writes `log_likelihoods_`, but I think this is `log_posterior_` since P(x|y) is `posterior probability`.
https://github.com/optuna/optuna/blob/8ee931a77343f64e7ba270f0d37d7bb611dbe221/optuna/samplers/_tpe/sampler.py#L388
<img width="271" alt="スクリーンショット 2022-01-11 18 13 08" src="https://user-images.githubusercontent.com/52235899/148914113-d50aa32f-bce6-4e61-a481-87f2b39fb87b.png">

I think y is the data and x is the parameter, and therefore I think that is `posterior probability`.
Or, we may replace it with just `density` according to https://papers.nips.cc/paper/2011/file/86e8f7ab32cfd12577bc2619bc635690-Paper.pdf

If I'm wrong, please correct me, thank you!

**Comment by himkt** [comment]
@HideakiImamura Do you have any comments? (I mentioned as you are the author)

**Comment by HideakiImamura** [comment]
Thank you for raising an interesting question @takassh. To be honest, I don't think the current use of the word "likelihood" is that wrong. Let me explain more about this below.

The `p(x|y)` represents a statistical model of `x` (data) given `y` (data) and other parameters. In detail, `p(x|y)` is `p(x|y, \theta, D_n)` where `\theta` is a vector of hyperpamrameters and `D_n` is the set of observations `{(x_i, y_i)}_{i=1}^n`. Therefore, it is not likelihood. In my understanding, "likelihood" is a joint probability of data given parameters. Here it should be `p(x, y | \theta, D_n)`.

On the other hand, I think it is OK to use "likehood" for `l(x)` and `g(x)` in which `y` is marginalized. Here, `l(x) = p(x | \theta, D_n)` and `g(x)` is the same. It is a joint probability of data `x` given parameters. 

Therefore, in Optuna and the original TPE implementation (known as `Hyperopt`), the word of "likehood" is used for `l(x)` and `g(x)`.

**Comment by takassh** [comment]
@HideakiImamura 
Thank you for detail, and I'm honored with this opportunity.
I may misunderstand about `x`.

Based on you, `\theta` is selected as the next candidate hyperpamrameters, while I thought `x` had that role.
I noticed `x` is just data.

Thus, is it correct understanding that this expression is missing `\theta`? (If we write detail.)
<img width="495" alt="スクリーンショット 2022-01-28 16 50 06" src="https://user-images.githubusercontent.com/52235899/151507831-559f9769-7139-4d06-b3c8-f0548b8cfafb.png">
(This expression is present in section 4.2 of the above paper.)

According to your opinion, `\theta` which minimizes `\frac{g(x|\theta)}{l(x|\theta)}` should be selected as the next candidates.

**Comment by HideakiImamura** [comment]
Here, we don't use the maximum likelihood estimation. In the Bayesian optimization history, the next candidate is selected from the maximization of the utility function (called acquisition function). The maximum likelihood principle cannot be applied.

Note that `\theta` is the hyperparameter of the TPE (Bayesian optimization). In other words, it is not the hyperparameter which users want to select. It is kind to represent `\theta` as the "hyperhyperparameter`.

**Comment by takassh** [comment]
@HideakiImamura 
Oh, sorry I'm confused.
I know Optuna uses Bayesian optimization, but I may miss something.

I have two questions.

1.  Just to confirm, Is `l(x) = p(x | \theta, D_n)` and `g(x)` not the evidence?
If `\theta` is the hyperparameter (so called "hypothesis"), I think `p(Data|\theta)` is the evidence.

2. I think EI is acquisition function. Therefore, we optimize `\frac{g(x|\theta)}{l(x|\theta)}` which approximate EI in every iterations of the Bayesian optimization history.  Is this incorrect?

**Comment by HideakiImamura** [comment]
Sorry for the late reply.

1. No, `l(x)` and `g(x)` are not evidence. As far as I know, the model evidence is never used in the context of Bayesian optimization. This is because in the mainstream of Bayesian optimization, the objective function is modeled nonparametrically. In many research and practical applications, maximum likelihood estimation or MCMC is used for hyperparameter optimization in Bayesian optimization. (I don't think any hyperparameter optimization using the model evidence has been done, as far as I know.)
2. Yes, EI is an acquisition function. The maximization of EI with TPE is equivalent to the maximization of `\frac{g(x|\theta)}{l(x|\theta)}`. See the original TPE paper for more details.

**Comment by takassh** [comment]
@HideakiImamura 
Thank you very much.
After I asked you, I organized my thoughts and I read source code again.


finally, I understand

> I think it is OK to use "likehood" for l(x) and g(x) in which y is marginalized.

as you said before.

thank you for your kind!

**Comment by nzw0301** [comment]
@takassh could I close this issue?

**Comment by takassh** [comment]
@nzw0301 
Yes, please
