### ISSUE TITLE
Add unimplemented plot functions to `optuna.visualization.matplotlib`

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3225]
## Motivation

Optuna visualization module has two visualizations backend: Plotly and Matplotlib. For consistency, visualization methods should be implemented not depending on the backend. Due to development's history, `optuna.visualization.matplotlib` does not a few visualization functions that are implemented in Plotly backend.

## Description

Please implement the following functions

- [x] https://github.com/optuna/optuna/pull/2807, please see also https://github.com/optuna/optuna/issues/3020
- [x] https://github.com/optuna/optuna/issues/3116
- [x] Many objective optimization support of https://github.com/optuna/optuna/issues/2973

## Additional context (optional)

This is a sub-issue of https://github.com/optuna/optuna/issues/2959 to stabilise the visualisation module of Optuna.

**Comment by HideakiImamura** [comment]
Note that we need to work on the many objective optimization support of `plot_pareto_front` in https://github.com/optuna/optuna/issues/2973. I edited the issue description.

**Comment by toshihikoyanase** [comment]
>  the many objective optimization support of `plot_pareto_front`

The `target` attribute enables uses to select objectives to plot from many (>3) objectives. The `matplotlib` function has it, but the `plotly` function doesn't.

So, I guess the rest of the task is to implement the `target` argument to the `plotly` function.

**Comment by HideakiImamura** [comment]
Let me close this issue since we have finished all of this tasks.
