### ISSUE TITLE
'int' object has no attribute 'suggest_loguniform'

### ISSUE THREAD

**Issue by manza-ari** [optuna/optuna#3241]
### Expected behavior

I am unable to resolve this error 

### Environment

- Optuna version: 2.10.0
- Python version: 3.8
- OS: Ubuntu 
- (Optional) Other libraries and their versions: Pytorch 

### Error messages, stack traces, or logs

```shell
'int' object has no attribute 'suggest_loguniform'
```

### Steps to reproduce

```python
def objective(trial):
    #optimizer_target = optim.SGD(net.parameters(), lr=args.lr, momentum=0.9, weight_decay=5e-4)
    #optimizer_loss = optim.SGD(loss_pred_module.parameters(), lr=args.lr, momentum=0.9, weight_decay=5e-4)
    
    #optimizer = optuna.trial.suggest_categorical("optimizer", ["Adam", "RMSprop", "SGD"])
    #lr = optuna.trial.suggest_loguniform("lr", 1e-5, 1e-1, log=True)

    params = {
              'learning_rate': trial.suggest_loguniform('learning_rate', 1e-5, 1e-1),
              'optimizer': trial.suggest_categorical("optimizer", ["Adam", "RMSprop", "SGD"]),
              }
    optimizer_target = getattr(optim, params['optimizer'])(net.parameters(), lr = params['lr'], momentum=0.9, weight_decay=5e-4)
    optimizer_loss = getattr(optim, params['optimizer'])(loss_pred_module.parameters(), lr = params['lr'], momentum=0.9, weight_decay=5e-4)

     # Generate the optimizers.
    
    model = net
    accuracy = model.test(trial)
    
    return accuracy 
```

**Comment by nzw0301** [comment]
I think the `objective` function takes `trial` as `int` object. Could you check the trial is really optuna's trial, not int object.

**Comment by manza-ari** [comment]
okay so I removed the above error by doing the following changes in the main 

study = optuna.create_study(direction="maximize")
    study.optimize(lambda trial:objective(trial), timeout=600)
now there is another erorr which I am unable to resolve 

File "main.py", line 85, in objective
    'learning_rate': trial.suggest_loguniform('learning_rate', 1e-5, 1e-1),
AttributeError: 'int' object has no attribute 'suggest_loguniform'

**Comment by nzw0301** [comment]
Could  you try to replace

```python
study.optimize(lambda trial:objective(trial), timeout=600)
```
with 
```python
study.optimize(objective, timeout=600)
```
?

Ref: https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize

**Comment by manza-ari** [comment]
okay done thank you!

how about this error  

'learning_rate': trial.suggest_loguniform('learning_rate', 1e-5, 1e-1),
AttributeError: 'int' object has no attribute 'suggest_loguniform'

**Comment by nzw0301** [comment]
Could you share minimal reproducible codes with us?

**Comment by manza-ari** [comment]
#dataset and class


parser = argparse.ArgumentParser(description='PyTorch CIFAR10 Training')
#parser.add_argument('--lr', default=0.1, type=float, help='learning rate')
parser.add_argument('--resume', '-r', action='store_true', help='resume from checkpoint')
args = parser.parse_args()

device = 'cuda' if torch.cuda.is_available() else 'cpu'
best_acc = 0  # best test accuracy
start_epoch = 0  # start from epoch 0 or last checkpoint epoch

print('==> Preparing data..')
transform_train = transforms.Compose([
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])

transform_test = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
])

trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform_train)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=128, shuffle=True, num_workers=2)

testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform_test)
testloader = torch.utils.data.DataLoader(testset, batch_size=100, shuffle=False, num_workers=2)

classes = ('plane', 'car', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck')

print('==> Building model..')

net = resnet.ResNet18()
net = net.to(device)

loss_pred_module = LPM.loss_prediction_module()
loss_pred_module = loss_pred_module.to(device)

if device == 'cuda':
    net = torch.nn.DataParallel(net)
    loss_pred_module = torch.nn.DataParallel(loss_pred_module)
    cudnn.benchmark = True

if args.resume:
    # Load checkpoint.
    print('==> Resuming from checkpoint..')
    assert os.path.isdir('checkpoint'), 'Error: no checkpoint directory found!'
    checkpoint = torch.load('./checkpoint/ckpt.pth')
    net.load_state_dict(checkpoint['net'])
    best_acc = checkpoint['acc']
    start_epoch = checkpoint['epoch']

criterion = nn.CrossEntropyLoss(reduction='none')
loss_pred_criterion = MarginRankingLoss_learning_loss()

**Comment by manza-ari** [comment]
#Objective Function 
def objective(trial):
    #optimizer_target = optim.SGD(net.parameters(), lr=args.lr, momentum=0.9, weight_decay=5e-4)
    #optimizer_loss = optim.SGD(loss_pred_module.parameters(), lr=args.lr, momentum=0.9, weight_decay=5e-4)
    
    #optimizer = optuna.trial.suggest_categorical("optimizer", ["Adam", "RMSprop", "SGD"])
    #lr = optuna.trial.suggest_loguniform("lr", 1e-5, 1e-1, log=True)

    params = {
              'learning_rate': trial.suggest_loguniform('learning_rate', 1e-5, 1e-1),
              'optimizer': trial.suggest_categorical("optimizer", ["Adam", "RMSprop", "SGD"]),
              }
    optimizer_target = getattr(optim, params['optimizer'])(net.parameters(), lr = params['lr'], momentum=0.9, weight_decay=5e-4)
    optimizer_loss = getattr(optim, params['optimizer'])(loss_pred_module.parameters(), lr = params['lr'], momentum=0.9, weight_decay=5e-4)

     # Generate the optimizers.
    
    model = net
    accuracy = model.test(trial)
    
    return accuracy

**Comment by manza-ari** [comment]
# Training and Test Functions 


def train(epoch):
    print('\nEpoch: %d' % epoch)
    net.train()
    loss_pred_module.train()
    train_loss = 0
    correct = 0
    total = 0
    for batch_idx, (inputs, targets) in enumerate(trainloader):
        inputs, targets = inputs.to(device), targets.to(device)
        
        objective(trial = 100)
        object = objective()
        object.optimizer_target.zero_grad()
        object.optimizer_loss.zero_grad()
        
        outputs, loss_pred = net(inputs)
        loss = criterion(outputs, targets)
        loss_pred = loss_pred_module(loss_pred)
        loss_prediction_loss = loss_pred_criterion(loss_pred, loss)
        target_loss = loss.mean()
        if epoch < 120:
            loss = loss_prediction_loss + target_loss 
            loss.backward()
            objective.optimizer_target.step()
            objective.optimizer_loss.step()
        else:
            loss = target_loss
            loss.backward()
            objective.optimizer_target.step()

        train_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

        progress_bar(batch_idx, len(trainloader), 'Loss: %.3f | Acc: %.3f%% (%d/%d)'
            % (train_loss/(batch_idx+1), 100.*correct/total, correct, total))

def test(epoch):
    global best_acc
    net.eval()
    test_loss = 0
    correct = 0
    total = 0
    with torch.no_grad():
        for batch_idx, (inputs, targets) in enumerate(testloader):
            inputs, targets = inputs.to(device), targets.to(device)
            outputs, loss_pred = net(inputs)
            loss = criterion(outputs, targets)
            loss = loss.mean()
            test_loss += loss.item()
            _, predicted = outputs.max(1)
            total += targets.size(0)
            correct += predicted.eq(targets).sum().item()

            progress_bar(batch_idx, len(testloader), 'Loss: %.3f | Acc: %.3f%% (%d/%d)'
                % (test_loss/(batch_idx+1), 100.*correct/total, correct, total))

    # Save checkpoint.
    acc = 100.*correct/total
    if acc > best_acc:
        print('Saving..')
        state = {
            'net': net.state_dict(),
            'acc': acc,
            'epoch': epoch,
        }
        if not os.path.isdir('checkpoint'):
            os.mkdir('checkpoint')
        torch.save(state, './checkpoint/ckpt.pth')
        best_acc = acc


for epoch in range(start_epoch, start_epoch+200):
    train(epoch)
    test(epoch)

**Comment by manza-ari** [comment]
if __name__ == "__main__":

    study = optuna.create_study(direction="maximize")
    study.optimize(objective, timeout=600)

    pruned_trials = study.get_trials(deepcopy=False, states=[TrialState.PRUNED])
    complete_trials = study.get_trials(deepcopy=False, states=[TrialState.COMPLETE])

    print("Study statistics: ")
    print("  Number of finished trials: ", len(study.trials))
    print("  Number of pruned trials: ", len(pruned_trials))
    print("  Number of complete trials: ", len(complete_trials))

    print("Best trial:")
    trial = study.self.best_trial

    print("  Value: ", trial.value)

    print("  Params: ")
    for key, value in trial.params.items():
        print("    {}: {}".format(key, value))

    plot_objective_function = optuna.visualization.plot_intermediate_values(study)
    plot_objective_function.show()

    plot_history = optuna.visualization.plot_optimization_history(study)
    plot_history.show()

    important_hyper = optuna.visualization.plot_pareto_front(study)
    important_hyper.show()

**Comment by manza-ari** [comment]
I am trying Optuna for following project on Github 

https://github.com/seominseok0429/Learning-Loss-for-Active-Learning-Pytorch/blob/master/main.py

My Objective function is 

def objective(trial):
    #optimizer_target = optim.SGD(net.parameters(), lr=args.lr, momentum=0.9, weight_decay=5e-4)
    #optimizer_loss = optim.SGD(loss_pred_module.parameters(), lr=args.lr, momentum=0.9, weight_decay=5e-4)
    
    #optimizer = optuna.trial.suggest_categorical("optimizer", ["Adam", "RMSprop", "SGD"])
    #lr = optuna.trial.suggest_loguniform("lr", 1e-5, 1e-1, log=True)

    params = {
              'learning_rate': trial.suggest_loguniform('learning_rate', 1e-5, 1e-1),
              'optimizer': trial.suggest_categorical("optimizer", ["Adam", "RMSprop", "SGD"]),
              }
    optimizer_target = getattr(optim, params['optimizer'])(net.parameters(), lr = params['lr'], momentum=0.9, weight_decay=5e-4)
    optimizer_loss = getattr(optim, params['optimizer'])(loss_pred_module.parameters(), lr = params['lr'], momentum=0.9, weight_decay=5e-4)

     # Generate the optimizers.
    
    model = net
    accuracy = model.test(trial)
    
    return accuracy 

The main is 

if __name__ == "__main__":

    study = optuna.create_study(direction="maximize")
    study.optimize(objective, timeout=600)

    pruned_trials = study.get_trials(deepcopy=False, states=[TrialState.PRUNED])
    complete_trials = study.get_trials(deepcopy=False, states=[TrialState.COMPLETE])

    print("Study statistics: ")
    print("  Number of finished trials: ", len(study.trials))
    print("  Number of pruned trials: ", len(pruned_trials))
    print("  Number of complete trials: ", len(complete_trials))

    print("Best trial:")
    trial = study.self.best_trial

    print("  Value: ", trial.value)

    print("  Params: ")
    for key, value in trial.params.items():
        print("    {}: {}".format(key, value))

    plot_objective_function = optuna.visualization.plot_intermediate_values(study)
    plot_objective_function.show()

    plot_history = optuna.visualization.plot_optimization_history(study)
    plot_history.show()

    important_hyper = optuna.visualization.plot_pareto_front(study)
    important_hyper.show()

**Comment by nzw0301** [comment]
Thanks. The code looks fine. i think the code should work by applying ttps://github.com/optuna/optuna/issues/3241#issuecomment-1017304018.

**Comment by manza-ari** [comment]
No, it is not working. it is giving me the following error after the change you recommended 

'learning_rate': trial.suggest_loguniform('learning_rate', 1e-5, 1e-1),
AttributeError: 'int' object has no attribute 'suggest_loguniform'

**Comment by nzw0301** [comment]
Please do not pass `int` to `objective` function as `trial`.

My suggestion was `study.optimize(objective, timeout=600)`, not `objective(trial = 100)`.

**Comment by manza-ari** [comment]
File "main.py", line 85, in objective
    'learning_rate': trial.suggest_loguniform('learning_rate', 1e-5, 1e-1),
AttributeError: 'int' object has no attribute 'suggest_loguniform'

in train() function there are two variables that were producing errors because of the objective function I have introduced above so I edited them given below. Now when I call objective function they create different errors 

def train(epoch):
    print('\nEpoch: %d' % epoch)
    net.train()
    loss_pred_module.train()
    train_loss = 0
    correct = 0
    total = 0
    for batch_idx, (inputs, targets) in enumerate(trainloader):
        inputs, targets = inputs.to(device), targets.to(device)
        
        objective(epoch)
        object = objective()
        object.optimizer_target.zero_grad()
        object.optimizer_loss.zero_grad()
        
        outputs, loss_pred = net(inputs)
        loss = criterion(outputs, targets)
        loss_pred = loss_pred_module(loss_pred)
        loss_prediction_loss = loss_pred_criterion(loss_pred, loss)
        target_loss = loss.mean()
        if epoch < 120:
            loss = loss_prediction_loss + target_loss 
            loss.backward()
            objective.optimizer_target.step()
            objective.optimizer_loss.step()
        else:
            loss = target_loss
            loss.backward()
            objective.optimizer_target.step()

        train_loss += loss.item()
        _, predicted = outputs.max(1)
        total += targets.size(0)
        correct += predicted.eq(targets).sum().item()

        progress_bar(batch_idx, len(trainloader), 'Loss: %.3f | Acc: %.3f%% (%d/%d)'
            % (train_loss/(batch_idx+1), 100.*correct/total, correct, total))

**Comment by nzw0301** [comment]
The following part looks strange. Again, `objective` should take a trial instance, not `int`, in the code, `epoch`. 

```python
        objective(epoch)
        object = objective()
        object.optimizer_target.zero_grad()
        object.optimizer_loss.zero_grad()

```

**Comment by nzw0301** [comment]
I believe that I've answered the question and we could not give a further comment to solve the issue. Let me close this issue. I think [Optuna tutorial](https://optuna.readthedocs.io/en/stable/tutorial/index.html) gives a concrete usage and explains the concepts of Optuna's API to apply Optuna the project.
