### ISSUE TITLE
[RFC] Make trials editable after they are finished

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#3251]
### Motivation

Since this issue is an RFC, any opinions/comments are welcome.

Now, we cannot edit the information of trials, such as `params`, `values`, `intermediate_values`, or `user_attrs`, after they are finished. While this specification leads to simplicity in implementation and clarity of behavior in distributed environments, it often leads to inconvenient situations. Now, we would like to discuss whether to change the trials editable after they are finished. This change in the specification should be done carefully, as it will affect various features that form the core of Optuna. Also, its implementation will be complex and challenging. We will make this change in Optuna V3 when we have enough use cases to justify the cost.

We have the following situations where we want to edit the trials after they are finished.
- The arguments of `BaseSampler.after_trial` is complicated and hard to understand. See https://github.com/optuna/optuna/issues/2936 for more details.

### Description

The flow will be as follows.
- Keep the call for use cases for this feature open until the end of April 2022.
- In May 2022, discuss the need for the feature based on the use cases gathered.
- If it is determined that the feature is necessary, implement it.

**Comment by keisuke-umezawa** [comment]
@HideakiImamura 
I think this issue itself is out of the scope of v3 roadmap. How about removing v3 tag?

**Comment by HideakiImamura** [comment]
@keisuke-umezawa Thanks for the suggestion. For now, this issue is labeled V3 because it may be tackled within V3. The current plan is to remove the V3 label from this issue if no requests are received for this issue by the end of April. For #2936, whether to remove the V3 label as well or close the issue itself is a matter for discussion.

**Comment by HideakiImamura** [comment]
Since there was no particular community input on this item, we will not be working on this item, at least not in V3.

**Comment by blazespinnaker** [comment]
I think a bigger issue is likely performance issues with large number of trials, which are turning into a bit of a blocker.  

I'm moving trial user_attrs out into study user_attr, prefixed by trial numbers.  It might be useful to add this to the callback documentation, though I do recognize now that FrozenTrial should already hint at this.

**Comment by blazespinnaker** [comment]
I think a bigger issue is likely performance issues with large number of trials, which are turning into a bit of a blocker.

I'm moving trial user_attrs out into study user_attr, prefixed by trial numbers. It might be useful to add this to the callback documentation, though I do recognize now that FrozenTrial should already hint at this.
