### ISSUE TITLE
integrate with Lightning ecosystem CI

### ISSUE THREAD

**Issue by Borda** [optuna/optuna#3254]
### Motivation

Hello and happy that you show integration with PL!! :tada: 
Just wondering if you already heard about quite the new **Pytorch Lightning (PL) ecosystem CI** where we would like to invite you to... You can check out our blog post about it: [Stay Ahead of Breaking Changes with the New Lightning Ecosystem CI](https://devblog.pytorchlightning.ai/stay-ahead-of-breaking-changes-with-the-new-lightning-ecosystem-ci-b7e1cf78a6c7) :zap: 
We already have joined integration between PL and your framework, so we would like to level it up. At this moment, we are running tests with your latest version, but it may accidentally happen that your next version will be incompatible with our next release version... :confused:  But here we have a solution - ecosystem CI with testing both - your and our latest development head we can find it very early and prevent releasing eventually bad version... :+1: 

### Description

**What is needed to do?**
- have some tests, including PL integration
- add config to ecosystem CI - https://github.com/PyTorchLightning/ecosystem-ci

**What will you get?**
- scheduled nightly testing configured development/stable heads
- slack notification if something went wrong
- testing also on multi-GPU machine

**Comment by himkt** [comment]
Hello @Borda 👋, thank you for inviting us to the nice project!

We've already run tests for the latest stable PL in this repo (optuna) and [optuna-examples](https://github.com/optuna/optuna-examples) daily. Our CIs all run (daily) with our nightly and PL to monitor and fix when some troubles occur. I think this is for the same reason as ecosystem CI so I agree with the idea of it!.

However, we are now focusing on the development of the next major version of the library, so we may not afford to investigate when some problem occurs on ecosystem CI (over our daily CI). So, after our milestone is settled, we'd like to investigate adding our tests on ecosystem CI.

Again, thank you so much for inviting us, and thank you for maintaining the amazing library!

**Comment by Borda** [comment]
> Our CIs all run (daily) with our nightly and PL to monitor and fix when some troubles occur. I think this is for the same reason as ecosystem CI so I agree with the idea of it!

yes, that is the same, so in such a case you are already doing a great job! The small diff is that the EcoCI is kind of visible for both sides (I d not mean that your CI is close but no one from PL team is watching it regularly)
As if something breaks it is not necessary your issue, and in such case, you need to ping us... on the other hand with this "middle ground" both sides are notified that something is happening and you also reduce noise in your checks on PRs...

> However, we are now focusing on the development of the next major version of the library, so we may not afford to investigate

sure, fully understand and appreciate your transparency :rabbit: 

> So, after our milestone is settled, we'd like to investigate adding our tests on ecosystem CI.

Thank you. In addition I would highlight that with EcoCI you would get also multi-GPU testing out of the box :]

**Comment by himkt** [comment]
I close this issue for now. Thank you @Borda for letting us the interesting project!
