### ISSUE TITLE
Resuming Study

### ISSUE THREAD

**Issue by f3n1Xx** [optuna/optuna#3255]
### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

I am confused, why is resuming a study is starting with same set of parameters? I ran a study for 30 trials with db, I resumed the study (load_if_it_exists), it's running the same set of parameters again for next 30 trials....doesn't that defeat the purpose?

I wanted to resume the study to give it more time to explore parameters, if it will run the same parameters again, then why am I wasting time?

### Error messages, stack traces, or logs

```shell
No error message.
```

### Steps to reproduce

1. Just run
2. any
3. study
```python
storage_name = "sqlite:///{}.db".format(study_name)
seed = 137
num_variables = 11
n_startup_trials = 11 * num_variables - 1
sampler = optuna.samplers.MOTPESampler(
    n_startup_trials=n_startup_trials, n_ehvi_candidates=24, seed=seed
)
study = optuna.create_study(study_name=study_name, storage=storage_name,directions=["minimize", "maximize"] ,sampler=sampler, load_if_exists=True)
```

**Comment by f3n1Xx** [comment]
There is a possible solution, when the parameter sets are not repeating.

if don't include the sampler, but then wouldn't the sampler be defaulted?

**Comment by nzw0301** [comment]
Let me explain why this happens as follows:

For the first `n_startup_trials` trials, parameters are randomly generated. When resuming the optimisation during random search with the same random seed, the suggested parameters are exactly the same as the first n trials, where n is the number of evaluated trials on the RDB. This is why not specifying the sampler resolves the issue because we random search is performed with a different random seed value.

**Comment by f3n1Xx** [comment]
I sort of figured this, also found that I was making a mistake with number of variables thinking it was number of parameters. 

So I corrected it with, setting number of variables to 2 (maximise and minimise), and running the optimization for at least 21 runs, after which parameters don't repeat. So the startup trials are generating parameters based on seed value, that's why they were repeating, and since, I had number of variables set to 11, it was taking so long to finish up the startup for the optimiser.

I am still running the optimization, if I see intended results then I'll close the issue.

**Comment by PhillipMaire** [comment]
Could someone elaborate on the solution here? Is there an example of how to properly resume an optuna study in such a way that it is identical to a study that was never stopped in the first place?  so like 
study_1 = (set seed) run 10 trials --> (use same seed) run 10 more trials 
study_2 =  (set seed) run 20 trials 

study_1==study_2, or results are approximately equal

is it all as simple as not setting a sampler when resuming the study and obviously setting `load_if_exists=True`. In this way you may not be able to reproduce results as I outline above, but will this method ensure that a continuous of the progress made so far? thank you for your help!
