### ISSUE TITLE
More control over how GridSampler prioritizes configurations after search space is exhausted

### ISSUE THREAD

**Issue by cschell** [optuna/optuna#3256]
### Motivation

I run jobs on a cluster performing trials using GridSampler. These jobs can be evicted at any time, which causes these trials to get the state "Fail" in the database. The jobs will restart eventually to pick up a new trial (I'm not attempting to restart previous runs/trails). I need to make sure, that configurations of "failed" trials are not "forgotten".

### Description

The current behaviour of `GridSampler` suggesting a configuration for a new trial is as follows:

1. [pick a configuration that has not been visited yet](https://github.com/optuna/optuna/blob/master/optuna/samplers/_grid.py#L137)
    1. get a list of all configurations that are "[finished](https://github.com/optuna/optuna/blob/854c44ff4ba7238059d69641e32b44f3dbd587e8/optuna/trial/_state.py#L31)" (i.e., "not running" and "not waiting") or "running"
    2. pick a configuration that is not in that list
2. if there are no such unvisited configurations left, ignore the state of each configuration and just pick one from [_all_ configurations](https://github.com/optuna/optuna/blob/master/optuna/samplers/_grid.py#L151); also, issue a warning that "_`GridSampler` is re-evaluating a configuration because the grid has been exhausted._"

It would be great for my purposes to tell `GridSampler` for the second step what configuration-states are allowed to be re-run. I propose a parameter `allow_rerun: List[TrialState]` that allows to specify that:

a.  `GridSampler(search_space={...}, allow_rerun=None)` => could be the default, which just does not change the current behaviour: if search space is exhausted, consider all configurations equally
b.  `GridSampler(search_space={...}, allow_rerun=[TrialState.FAIL])` => if search space is exhausted, only rerun configurations that are Failed and exit if none are left (so the search doesn't run endlessly)
c.  `GridSampler(search_space={...}, allow_rerun=[TrialState.FAIL, TrialState.PRUNED])` => if search space is exhausted, only rerun configurations that are either Failed or Pruned
d.  `GridSampler(search_space={...}, allow_rerun=[])` => if search space is exhausted, just exit

Altogether, this allows me to make sure that all configurations will be evaluated.

I can work on a PR for that, but first I would like to make sure this is something you approve of.

**Comment by himkt** [comment]
Hello @cschell, thank you for raising the issue.

> These jobs can be evicted at any time, which causes these trials to get the state "Fail" in the database

I'm curious why these trials are `FAIL` because I just thought these are left on the storage with statuses `RUNNING`.
We provide a trial restart mechanism called heartbeat and I'm wondering if it would fit your use case.
https://optuna.readthedocs.io/en/latest/faq.html#can-i-monitor-trials-and-make-them-failed-automatically-when-they-are-killed-unexpectedly

Heartbeat is a mechanism for stale trials (trials that are left on the storage with state `RUNNING`).
If you manually make trials' states `FAIL` to stop trials gracefully when you receive an interruption notice, I'm wondering if [enqueue_trial](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.enqueue_trial) helps you.

I'd like to be careful to introduce `allow_rerun` to `GridSampler` because rerunning failed/pruned trials doesn't depend on the specific sampler (users may want to rerun them with other samplers such as `RandomSampler`). And I think (hope) utilities such as heartbeat or enqueue_trial would be options for you.

**Comment by cschell** [comment]
> I'm curious why these trials are FAIL because I just thought these are left on the storage with statuses RUNNING.

oh, you are right, I run an occasional script to mark stale trials as failed and I should definitely have a look into heartbeat!

I think using `enqueue_trial` may be a possible workaround, but this feels a bit hacky. When I understand this correctly I would need a script that checks if there are failed trials that haven't been rerun yet and then enqueue new trials with these configurations.

Another solution I can think of would be to delete failed trials, but as far as I understand it this is not supported by Optuna.

> I'd like to be careful to introduce allow_rerun to GridSampler because rerunning failed/pruned trials doesn't depend on the specific sampler (users may want to rerun them with other samplers such as RandomSampler).

I'm not sure if I can follow your concern here, in contrast to `GridSampler` the other samplers truly ignore failed trials, right? I just realize that this is the actual root issue for me here, that `GridSampler` doesn't ignore failed trials and instead takes them into account when choosing a new configuration.

**Comment by himkt** [comment]
> I think using enqueue_trial may be a possible workaround, but this feels a bit hacky

I agree with you. heartbeat and `RetryFailedTrialCallback` were designed to be a solution for the case.
I hope it helps you.

> I'm not sure if I can follow your concern here, in contrast to GridSampler the other samplers truly ignore failed trials, right? I just realize that this is the actual root issue for me here, that GridSampler doesn't ignore failed trials and instead takes them into account when choosing a new configuration.

Samplers other than `GridSampler` don't search exhaustively on the space and they could suggest the same configuration multiple times. In this point of view, users could retry failed configuration without any option like `allow_rerun`. But they would want to explicitly rerun such configurations, so I think your proposal would not be unique to `GridSampler`.

As you pointed out, GridSampler doesn't take care of the status of trials. But I prefer to rerun them outside sampler (e.g. heartbeat) to keep a mechanism of sampler simple.

**Comment by cschell** [comment]
Unfortunately `RetryFailedTrialCallback` has no effect for me, killed trials just don't get requeued, I'm not exactly sure why yet.

> But I prefer to rerun them outside sampler (e.g. heartbeat) to keep a mechanism of sampler simple.

Ok, I guess this is a design decision then, fair enough. My solution is now to use a [custom `GridSampler`](https://gist.github.com/cschell/f4d2de50c9f34fddf38acef4b070ea92) that basically only changes [one line](https://gist.github.com/cschell/f4d2de50c9f34fddf38acef4b070ea92#file-custom_grid_sampler-py-L23) in `_get_unvisited_grid_ids` to ignore failed trials – this ends up doing exactly what I want `GridSampler` to do.

I'm closing the issue then, thanks for the help!

**Comment by himkt** [comment]
> My solution is now to use a custom GridSampler that basically only changes one line in _get_unvisited_grid_ids to ignore failed trials 

:+1:

> Unfortunately RetryFailedTrialCallback has no effect for me, killed trials just don't get requeued, I'm not exactly sure why yet.

Sorry to hear that...
I'd like to make sure one thing, do you create a storage with `heartbeat_interval`?

```python
import optuna
from optuna.storages import RetryFailedTrialCallback

storage = optuna.storages.RDBStorage(
    url="sqlite:///:memory:",
    heartbeat_interval=60,  # it is required
    grace_period=120,
    failed_trial_callback=RetryFailedTrialCallback(max_retry=3),
)

study = optuna.create_study(storage=storage)
```

**Comment by cschell** [comment]
yes, that's what I did, it also told me in the log that `RetryFailedTrialCallback` is still experimental, so it gets at least initialized. I'm using Postgres-DB though, but I don't think that's the issue.

**Comment by himkt** [comment]
Hmm... If you could create a minimum reproducible code, I'd really like to be shared. (I'll test with PostgreSQL)
Sorry, but anyway, thank you so much for trying!

**Comment by cschell** [comment]
I guess this has something to do with Hydra's `OptunaSweeper` that I'm using. When I'm running trials in a standalone script using the same database, it's working fine...

**Comment by cschell** [comment]
Yes, I think this is because they don't use `optimize` but the `ask` and `tell` interface, [see here](https://github.com/facebookresearch/hydra/blob/a8e247d3b01d04c21ee1b2220737c60b24664221/plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/_impl.py#L201). A quick test confirms that `ask` doesn't trigger the heartbeat mechanism.

**Comment by himkt** [comment]
Thank you @cschell for adding your contexts, and now I think I understand your situation.
As you pointed out, heartbeat doesn't work with ask-and-tell for now, and users couldn't notice it without going through the codebase. Optuna will show a warning for the case in #3273.

Your workaround (using `GridSampler` with the patch) looks like the most reasonable solution for now.
