### ISSUE TITLE
Make `show_progress_bar` tests simpler

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3257]
### Motivation

The following table originally created in https://github.com/optuna/optuna/pull/3138#discussion_r790035789 may suggest that we can reduce the number of test functions and simplify the test logic.

| show_progress_bar | n_trials | timeout | n_jobs | covered by |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| False | None | None | 1 | test_optimize_without_progbar_no_constraints |
| False | None | None | not 1 | test_optimize_without_progbar_no_constraints |
| False | None | not None | 1 | test_optimize_without_progbar_timeout |
| False | None | not None | not 1 | test_optimize_without_progbar_timeout |
| False | not None | None | 1 | test_optimize_without_progbar |
| False | not None | None | not 1 | test_optimize_without_progbar |
| False | not None | not None | 1 | test_optimize_without_progbar_n_trials_prioritized |
| False | not None | not None | not 1 | test_optimize_without_progbar_n_trials_prioritized |
| True | None | None | 1 | test_optimize_progbar_no_constraints |
| True | None | None | not 1 | test_optimize_progbar_no_constraints |
| True | None | not None | 1 | test_optimize_with_progbar_timeout |
| True | None | not None | not 1 | test_optimize_with_progbar_parallel_timeout |
| True | not None | None | 1 | test_optimize_with_progbar |
| True | not None | None | not 1 | test_optimize_with_progbar |
| True | not None | not None | 1 | test_optimize_progbar_n_trials_prioritized |
| True | not None | not None | not 1 | test_optimize_progbar_n_trials_prioritized |

### Description

Simplify the test functions for `show_progresss_bar` by using `pytest.mark.parametrize`.

----

_Originally posted by @toshihikoyanase in https://github.com/optuna/optuna/issues/3138#issuecomment-1019806850_

**Comment by BasLaa** [comment]
Hi,

I'd like to work on this to get my feet wet in contributing to Optuna

**Comment by nzw0301** [comment]
@BasLaa Awesome! I'm looking forward to seeing your PR!

**Comment by BasLaa** [comment]
Just to be sure, I've been reading through the other issues mentioned, and we're talking about `show_progress_bar` in `optimize`, right?

**Comment by BasLaa** [comment]
After some further research, there are these tests which can be improved:

We have `test_optimize_with_progbar_timeout` and `test_optimize_with_progbar_timeout_formats`, which achieve the same goal, only `test_optimize_with_progbar_timeout` has just one timeout case, whereas `test_optimize_with_progbar_timeout_formats` tests 5 different (very long) timeout cases. So, what we can do is remove `test_optimize_with_progbar_timeout` and add its case to `test_optimize_with_progbar_timeout_formats`, or simply keep `test_optimize_with_progbar_timeout`, which only tests one case, but I do not necessarily see too much harm in that.
Then there is `Test_optimize_with_progbar_parallel_timeout`, which we can then merge with the test we keep using pytest.mark.parametrize. 

Let me know what you think.

**Comment by nzw0301** [comment]
> Just to be sure, I've been reading through the other issues mentioned, and we're talking about `show_progress_bar` in optimize, right?

Yes, you are right.

> To still cover all possibilities, how would you like to see it done instead?
> Was that the simplification you are looking for?

Yes, I was. But if some test cases should be included, please feel free to add tests.

**Comment by nzw0301** [comment]
> I do not necessarily see too much harm in that.

Thank you for your investigation. Indeed, the aim of these test functions are supposed to be the same, but merging these functions might make the logic a little bit complicated.

> `test_optimize_with_progbar_parallel_timeout`

Sounds nice!



Then there is Test_optimize_with_progbar_parallel_timeout, which we can then merge with the test we keep using pytest.mark.parametrize.

**Comment by BasLaa** [comment]
@nzw0301 

I believe it is not worthwhile to merge the two functions `test_optimize_with_progbar_parallel_timeout` and `test_optimize_with_progbar_timeout`, because it would make the logic difficult. Combining them would mean using `@pytest.mark.parametrize("n_jobs", [1, 2])`.
However, the progress bar isn't supported for n_jobs = 2, so the two tests are fundamentally different. `test_optimize_with_progbar_timeout` checks if the progress bar works, and `test_optimize_with_progbar_parallel_timeout` checks whether it gives the right warning when n_jobs > 1. 
I can combine them into one if you like, but I think just placing them right under each other makes it clearer.
Sorry for the wait, had some stuff going on.

**Comment by BasLaa** [comment]
Yes, what I would change though is set test_optimize_with_progbar_timeout and test_optimize_with_progbar_parallel_timeout next to eachother in the test file, no actual implications but just for clarity. I will do that and send a PR.

**Comment by nzw0301** [comment]
Awesome! I agree with your idea to change the definition order for readability.

**Comment by nzw0301** [comment]
The readability of the test has been improved by https://github.com/optuna/optuna/pull/3280. Let me close this.
