### ISSUE TITLE
Improve CONTRIBUTING.md for the first time contributors to run unit tests

### ISSUE THREAD

**Issue by keisuke-umezawa** [optuna/optuna#3259]
### What is an issue?

# Issues
- To run unit tests locally, the current [CONTRIBUTING.md](https://github.com/optuna/optuna/blob/master/CONTRIBUTING.md#unit-tests) says that we need to run `pip install ".[tests]"` and `pip install ".[testing]"`. However, to successfully install `pip install ".[testing]"`, we need to install [many dependencies](https://github.com/optuna/optuna/blob/master/setup.py#L93-L125) and often fail to install them in local machines.

# Solutions
- [x] Divide the `Unit Tests` section into `Unit Tests` and `Integration Tests`, so that  contributors will only run `pip install ".[tests]"` for `Unit Tests`.
    - [x] Complete the [todo](https://github.com/optuna/optuna/blob/master/.github/workflows/tests.yml#L69-L73)
    - [x] Divide the `Unit Tests` section into `Unit Tests` and `Integration Tests`
    - [x] And afterwords, we can remove `[testing]` configuration.
- [ ] Provide documentation to run unit tests on the docker.

**Comment by soma2000-lang** [comment]
@Please assignme this.I would like to work on this

**Comment by nzw0301** [comment]
Note this looks detailed https://github.com/optuna/optuna/issues/3184.

**Comment by nzw0301** [comment]
@soma2000-lang Awesome. I think removing duplicated dependencies from `testing` in `setup.py` as a pull request is the first step to resolve this issue.

**Comment by nzw0301** [comment]
@soma2000-lang let me clarify the situation. Are you working on this?

**Comment by soma2000-lang** [comment]
Yes

**Comment by Alnusjaponica** [comment]
It seems this is already solved in #3517

**Comment by keisuke-umezawa** [comment]
@Alnusjaponica Yes. we can close this issue.
