### ISSUE TITLE
Is Optunan only usable with `ddp_spawn` (pytorch lightning) or can it also be used with `strategy='ddp'`? 

### ISSUE THREAD

**Issue by saneim** [optuna/optuna#3281]
### Environment

- Optuna version: 2.0.10 / 3.0.0a0
- Python version: 3.8.10
- OS: Linux-5.4.0-91-generic-x86_64-with-glibc2.10
- Pytorch Lightning: 1.5.9

### Error messages, stack traces, or logs

```shell
https://github.com/optuna/optuna-examples/blob/main/pytorch/pytorch_lightning_ddp.py. 
Optuna Version 2.10.0 + strategy='ddp' 
--> 
DeadlockDetectedExceptions pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 1
RuntimeError: replicas[0][0] in this process with sizes [42, 784] appears not to match sizes of the same param in process 0.
Optuna Version 3.0.0-a0
-->
AttributeError: 'Trainer' object has no attribute 'accelerator_connector'
```

### Steps to reproduce

Hello everyone, 

I want to use optuna in combination with pytorch lightning and the ddp strategy. To test this out, I used the sample code from https://github.com/optuna/optuna-examples/blob/main/pytorch/pytorch_lightning_ddp.py.
With optuna version 2.10.0 the code works. 
However, not ddp but ddp_spawn is used as strategy [Output: You requested multiple GPUs but did not specify a backend, e.g. `Trainer(strategy="dp"|"ddp"|"ddp2")`]. Setting `strategy="ddp_spawn"` for you.)].
If I set strategy='ddp' in the trainer, I get a RuntimeError  [RuntimeError: replicas[0][0] in this process with sizes [42, 784] appears not to match sizes of the same param in process 0.] and DeadlockDetectedExceptions [pytorch_lightning.utilities.exceptions.DeadlockDetectedException: DeadLock detected from rank: 1]. 
Since only the documentation of Optuna v3.0.0-a0 mentions DDP for Pytroch lightning (https://optuna.readthedocs.io/en/v3.0.0a0/reference/generated/optuna.integration.PyTorchLightningPruningCallback.html), I tried this version too.
There I already get an error with the original code [AttributeError: 'Trainer' object has no attribute 'accelerator_connector']. 
Is Optunan only usable with ddp_spawn or can it also be used with strategy='ddp'. If yes, how?

**Comment by nzw0301** [comment]
We've tested distributed training only with `ddp_cpu` because we do not have CIs with multiple GPUs. Hence `ddp`  is not supported. Note that the original author of this callback tested it with `ddp_spawn`, so it might work as we expect.

**Comment by Akshay1-6180** [comment]
@nzw0301 optuna is now usuable for ddp right based on this https://github.com/optuna/optuna/pull/4384 or are we still supposed to use ddp_spawn
