### ISSUE TITLE
report for pruning based on timestamps instead of steps

### ISSUE THREAD

**Issue by UntotaufUrlaub** [optuna/optuna#3290]
Hi,
is there a good way to use pruning based on timestamps instead of steps?
Am I correct that the standard pruners like the Median pruners only compare the values at the exact step?
Timestamps are most likely not exactly the same so the standard prunes wont find anything to compare too.
I tack my training progress based on time instead of steps as HP config with very big NN trains much slower and I am not only interested in getting the most out of each step but reaching a good state in reasonable time.

(Please let me know if this question is better suited in the feature section)

Kind regards.

**Comment by nzw0301** [comment]
Hi, #2873 might be related.

**Comment by UntotaufUrlaub** [comment]
Hi @nzw0301,
thanks for the reply! Yeah it's related :) I posted my further thoughts there.
