### ISSUE TITLE
Enum not supported in Choice?

### ISSUE THREAD

**Issue by arisliang** [optuna/optuna#3291]
### Environment

- Optuna version: 2.10.0
- Python version: 3.9.7
- OS: Windows-10-10.0.19044-SP0
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
Optuna doesn't seem to support Enum as a choice for persistent storage. Not sure

> optuna\distributions.py:427: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains Color.RED which is of type Color.
```

### Steps to reproduce

```python
from enum import Enum
class Color(Enum):
     RED = 1
     GREEN = 2
     BLUE = 3

import optuna
def objective(trial: optuna.Trial):
    color = trial.suggest_categorical('color', [Color.RED, Color.GREEN, Color.BLUE])
    return 0

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=10)
```

**Comment by nzw0301** [comment]
Yes, `Enum` is not supported as in the warning message because `Enum` is not JSON serialisable. If you really want to do that, inheriting `int` might be a solution: 

```python
class Color(int, Enum):
     RED = 1
     GREEN = 2
     BLUE = 3
```

Reference: https://stackoverflow.com/a/67781329/2406562

**Comment by arisliang** [comment]
Thanks for the explanation and possible solution.
