### ISSUE TITLE
Tuple not supported in Choice?

### ISSUE THREAD

**Issue by arisliang** [optuna/optuna#3292]
### Environment

Optuna version: 2.10.0
Python version: 3.9.7
OS: Windows-10-10.0.19044-SP0

### Error messages, stack traces, or logs

```shell
>optuna\distributions.py:427: UserWarning: Choices for a categorical distribution should be a tuple of None, bool, int, float and str for persistent storage but contains (1, 2) which is of type tuple.
```

### Steps to reproduce

Understood that enum is not supported by Choice in #3291, but is tuple not supported by Choice as well. Tuple should be json serializable, is it?

```python
# python code

import optuna

def objective(trial: optuna.Trial):
    color = trial.suggest_categorical('color', [(1, 2), (1, 3)])
    return 0

study = optuna.create_study(direction='maximize')
study.optimize(objective, n_trials=10)
```

**Comment by himkt** [comment]
It is not the error but the warning. You can use tuple as a choice of categorical distribution at your risk.

However, a sequence such as list or tuple is not guaranteed to be JSON-serializable. It could contain some object that is not JSON-serializable. This is why we strongly recommend to use `None`, bool, int, float, and str. Please refer to [the documentation](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.distributions.CategoricalDistribution.html#optuna.distributions.CategoricalDistribution).

You can use categorical distribution such that each element is an index for a tuple object (ref. https://github.com/optuna/optuna/issues/3093#issuecomment-968075749). And other related discussions can be seen in: https://github.com/optuna/optuna/issues/905, https://github.com/optuna/optuna/issues/2341

**Comment by arisliang** [comment]
It looks like tuple is immutable, but not json serilizable. Thanks for the answer and links to existing issues.
