### ISSUE TITLE
Optimizing Multiple Models?

### ISSUE THREAD

**Issue by rydevera3** [optuna/optuna#3297]
### Environment

- Optuna version: 2.10.0
- Python version: 3.6.8
- OS: `Darwin-19.6.0-x86_64-i386-64bit`

Hey all!

I just have a really simple question. In the `hyperopt` package you can set up the search space to incorporate multiple models & their individual parameters.

```python
space = hp.choice('classifiers', [
    {
    'model':KNeighborsClassifier(),
    'params':{
        'model__n_neighbors': hp.choice('knc.n_neighbors', range(2,10)),
        'model__algorithm': hp.choice('knc.algorithm',
                                      ['auto', 'ball_tree', 'kd_tree']),
        'model__metric': hp.choice('knc.metric', ['chebyshev', 'minkowski'])
    }
    },
    {
    'model':SVC(),
    'params':{
        'model__C': hp.choice('C', np.arange(0.005,1.0,0.01)),
        'model__kernel': hp.choice('kernel',['linear', 'rbf', 'sigmoid']),
        'model__degree':hp.choice('degree',[2,3,4]),
        'model__gamma': hp.uniform('gamma',0.001,1000)
    }
    },

    {
    'model': LogisticRegression(verbose=0),
    'params': {
        'model__penalty': hp.choice('lr.penalty', ['none', 'l2']),
        'model__C': hp.choice('lr.C', np.arange(0.005,1.0,0.01))

    }
    },
        {
    'model': XGBClassifier(eval_metric='logloss', verbosity=0),
    'params': {
        'model__max_depth' : hp.choice('xgb.max_depth',
                                       range(5, 30, 1)),
        'model__learning_rate' : hp.quniform('xgb.learning_rate',
                                             0.01, 0.5, 0.01),
        'model__n_estimators' : hp.choice('xgb.n_estimators',
                                          range(5, 50, 1)),
        'model__reg_lambda' : hp.uniform ('xgb.reg_lambda', 0,1),
        'model__reg_alpha' : hp.uniform ('xgb.reg_alpha', 0,1)
    }
    },
    {
        'model': QuadraticDiscriminantAnalysis(), # Default params
        'params': {}
    }
])
```

Does `optuna` have something similar? It is not clear to me from the documentation. Thank you!

### Error messages, stack traces, or logs

```shell
No messages, stack traces or logs
```

### Steps to reproduce

No reproducible steps

**Comment by himkt** [comment]
I'm not sure I fully understand your question but you can add a branch looks like following:
https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/002_configurations.html#defining-parameter-spaces

**Comment by rydevera3** [comment]
Hey @himkt yes that is exactly what I was looking for thank you. What the question was was if there was a way to only specify the search space like above without having to create those if / else statements like `hyperopt` but I see that it has to be done within the objective. Me & some colleagues have streamlined the process of searching multiple models I wonder if it would be useful if we could help add this as a new feature.

**Comment by himkt** [comment]
> Me & some colleagues have streamlined the process of searching multiple models I wonder if it would be useful if we could help add this as a new feature.

Looks interesting but I don't imagine your idea yet. How does the interface/sample code look like? :eyes:

**Comment by rydevera3** [comment]
@himkt awesome let me circle in my colleague @peterhadlaw and we will provide the syntax / API that we created 🙂

**Comment by peterhadlaw** [comment]
Hello @himkt here is a brief summary:

## API / Syntax

The summary of the API is to pass in a list of tuples to 
`OptunaSearchCV` (which we've named `OptunaMultiSearchCV` here):

```
model_search_spaces = [
    (<instatiated model 1>, <search space for model 1>),
    (<instatiated model 2>, <search space for model 2>),
    (<instatiated model 3>, <search space for model 3>),
    # and so on...
]

opt = OptunaMultiSearchCV(model_search_spaces)
```

Full example below: 


```python3
# Instantiate LGBM Model...
lgbm_model = LGBMRegressionModel()
# ... and define search space
lgbm_search_space = {
    'learning_rate': optuna.distributions.CategoricalDistribution([0.1, 0.05]),
    'num_leaves': optuna.distributions.CategoricalDistribution(
        _NUM_LEAVES_SEARCH_VALUES
    ),
    'lambda_l1': optuna.distributions.DiscreteUniformDistribution(
        low=0.0, high=10.0, q=0.5,
    ),
    'lambda_l2': optuna.distributions.DiscreteUniformDistribution(
        low=0.0, high=10.0, q=0.5,
    ),
}

# Instantiate ETS Model...
ets_model = ETSModel()
# ... and define search space
ets_search_space = {
    'seasonal_periods': optuna.distributions.IntUniformDistribution(
        low=2, high=12, step=1
    ),
    'damped_trend': optuna.distributions.CategoricalDistribution([True, False]),
    'error': optuna.distributions.CategoricalDistribution(['add']),
}

model_search_spaces = [
    (lgbm_model, lgbm_search_space),
    (ets_model, ets_search_space)
]

opt = optimization.OptunaMultiSearchCV(model_search_spaces)
opt.fit(X_train, y_train)

opt.best_estimator_  # -> ETSModel(damped_trend=True, seasonal_periods=9)
opt.best_params_  # -> {'seasonal_periods': 9, 'damped_trend': True, 'error': 'add', 'trend': 'add', 'seasonal': 'add'}
opt.study_.best_params  # -> {'estimator_index': 0, '~*~v12.v2.time_series.models:ETSModel--ETSModel()~*~seasonal_periods': 9, '~*~v12.v2.time_series.models:ETSModel--ETSModel()~*~damped_trend': True, '~*~v12.v2.time_series.models:ETSModel--ETSModel()~*~error': 'add', '~*~v12.v2.time_series.models:ETSModel--ETSModel()~*~trend': 'add', '~*~v12.v2.time_series.models:ETSModel--ETSModel()~*~seasonal': 'add', 'target_transformer_index': 0}

opt.predict(X_test) # and so on...

```

## Features


- **Handles multiple instances of the same model**

```python3
ets_model = ETSModel()  # NOTE: ETSModel
ets_search_space = {
    'seasonal_periods': optuna.distributions.IntUniformDistribution(
        low=2, high=12, step=1
    ),
    'damped_trend': optuna.distributions.CategoricalDistribution([True, False]),
    'error': optuna.distributions.CategoricalDistribution(['add']),
}

secondary_ets_model = ETSModel(damped_trend=False)  # NOTE: Also ETSModel, just different instance params
secondary_ets_search_space = {
    'seasonal_periods': optuna.distributions.IntUniformDistribution(
        low=2, high=12, step=1
    ),
    'error': optuna.distributions.CategoricalDistribution(['add']),
}

model_search_spaces = [
    (ets_model, ets_search_space),
    (secondary_ets_model, secondary_ets_search_space),
]

```

- **Handles models with the same parameter name**

Normally Optuna will complain if the same parameter name is used with
different distributions.

```
first_model = Model()
first_search_space = {
    'seasonal_periods': optuna.distributions.IntUniformDistribution(
        low=2, high=12, step=1
    ),
}  # NOTE: seasonal_periods = IntUniformDistribution

second_model = OtherModel()
second_search_space = {
    'seasonal_periods': optuna.distributions.CategoricalDistribution(
        ['summer', 'winter']
    ),
}  # NOTE: seasonal_periods = CategoricalDistribution

model_search_spaces = [
    (first_model, first_search_space),
    (second_model, second_search_space),
]
```

Also even putting the issue of different distributions named as the same parameter aside...

If two models share the same parameter name and distribution (including type of distribution),
the models should each have a full and separate evaluation of the search space for themselves.

Otherwise one model could be tried with one parameter and removing that from the search space
might deny the other model from trying the same parameter value which might be optimal for it.


This is done through very thorough namespacing (see code sample above):  \
`~*~v12.v2.time_series.models:ETSModel--ETSModel()~*~seasonal_periods`

**Comment by himkt** [comment]
Sorry for the late reply @rydevera3 @peterhadlaw. Thank you for sharing the idea.
It makes sense for API design and looks convenient.

However, I'm wondering if it is expensive to implement this feature. `OptunaSearchCV` is implemented that assumes the type of classifier is unchanged during optimization. It means that we cannot reuse `OptunaSearchCV` to implement `OptunaMultiSearchCV`, as a classifier would change at each trial. So it beyonds a simple wrapping, I think. Are you interested in prototyping and implementing as the module (if we find it reasonable to implement as an Optuna citizen)?

@toshihikoyanase @hvy @HideakiImamura
I also want other developers' opinion. Please comment if there is some comment/advise for it.

**Comment by peterhadlaw** [comment]
Hello @himkt (no problem at all for "late" replies 😊 ...not late at all).

---

**We have implemented `OptunaMultiSearchCV` and began using it in our codebase.**

Initially copying `OptunaSearchCV`  and building upon it. In short, to share the same code between `OptunaSearchCV` and `OptunaMultiSearchCV`, I could imagine something like this:

1) `OptunaMultiSearchCV` becomes the main foundation class which supports variable `N` different classifiers and search spaces
2) `OptunaSearchCV` maintains the same signature as before, except that instead it now becomes a lighter wrapper around `OptunaMultiSearchCV`
   - `opt.best_estimator_`, `opt.best_params_` and a lot of properties remain untouched / unchanged
   - The simplest way to describe the change is you pass in a single (non-list) `estimator` and `param_distribution` into `OptunaSearchCV` (which is what it is right now)... and `OptunaSearchCV` will internally wrap those into a tuple, into a list and forward it along to `OptunaMultiSearchCV`.
   
   ```python3
   class OptunaSearchCV(OptunaMultiSearchCV):
       def __init__(estimator, param_distribution, *args, **kwargs):
           return super([(estimator, param_distribution)], *args, **kwargs)

   # OptunaSearchCV maintains the same signature...
   opt = OptunaSearchCV(my_estimator, my_param_distribution, *args, **kwargs)
   ```
   
   _With the above code, practically `OptunaSearchCV` remains unchanged for it's original use case._

**Comment by rydevera3** [comment]
@himk just bumping this up 🙂

**Comment by himkt** [comment]
@rydevera3 I discussed this with team members. I'm sorry but we would like to be careful to introduce this feature to Optuna. The main reason is that `OptunaMultiSearchCV` may introduce an implicit categorical distribution over estimators. If the additional distribution is introduced inside a module, the user may who is not familiar with the module internal may be confused. Additionally, `OptunaSearchCV` was introduced in the early history of Optuna. Now there is a API `Study.tell` whose has `fixed_distribution` parameter that is similar to `param_distributions` in `OptunaSearchCV`. It needs to discuss what to do with this interface in the future before extending it.

@toshihikoyanase Please add a comment or correct me if I have missed some points.

**Comment by rydevera3** [comment]
Hey @himkt okay thank you for letting us know. I know multiple model optimization is quite popular. Please let us know when you do plan to implement this feature we would like to be a part of it if possible 🤝. @peterhadlaw
