### ISSUE TITLE
Is it possible to serialize a FrozenTrial to JSON?

### ISSUE THREAD

**Issue by kuelumbus** [optuna/optuna#3299]
### Environment

```python
from optuna.trial import create_trial
from optuna.distributions import CategoricalDistribution
from optuna.distributions import UniformDistribution
import json
frozen_trial = create_trial(
                params={"x": 1.0, "y": 0},
                distributions={
                    "x": UniformDistribution(0, 10),
                    "y": CategoricalDistribution([-1, 0, 1]),
                },
                value=5.0,
            )
json.dumps(frozen_trial)
```
This raises an error.

Serializability would be helpful for saving Tensorflow models
```python
import tensorflow as tf
class MyModel(tf.keras.Model):
    def __init__(self, trial: Trial):
        super().__init__()
        self.trial = trial
        n_dense = trial.suggest_int("n_dense", 10, 100)
        self.dense = tf.keras.layers.Dense(n_dense)

    def call(self, x):
        return self.dense(x)

    def get_config(self):
        # How to do this? 
        config = {trial': self.trial}
        return config

    @classmethod
    def from_config(cls, config):
        # And this?
        return cls(**config)
```

`MyModel(study.best_trial).save('export')` raises an error (`Unable to serialize FrozenTrial(number=..., ..,)`) because json has no way to serialize/deserialize the FrozenTrail.

### Error messages, stack traces, or logs

```shell
Nothing here
```

### Steps to reproduce

Nothing here

**Comment by himkt** [comment]
Hello @kuelumbus, we don't want to make `trial` object serializable because it contains a various states such as `study`. Please use `storage` to save/load a trial.

https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html#sphx-glr-tutorial-20-recipes-001-rdb-py

And, do you have to separate the parameter sampling and the model construction? Does ask-and-tell interface help you?

```python
import optuna
import tensorflow as tf


class MyModel(tf.keras.Model):
    def __init__(self, n_dense: int):
        super().__init__()
        self.dense = tf.keras.layers.Dense(n_dense)

    def call(self, x):
        return self.dense(x)


study = optuna.create_study()
trial = study.ask()  # create a trial
n_dense = trial.suggest_int("n_dense", 10, 100)
model = MyModel.from_config(n_dense)

loss = train(model)  # some training
model.save(path)  # some saving procedure

study.tell(trial, loss)  # report result to Optuna
```

**Comment by himkt** [comment]
We don't have a plan to make `FrozenTrial` JSON serializable as well, because we recommended save/load trials through `storage`. I want to know your use-case more in detail.

> make the TFKerasPruningCallback work.

I see. So using `study.optimize` would be simpler.

I think you want to do two types of things:

- optimize your model hyperparameters
- create a model with the best parameters you got during the optimization

Is it right? The following comments are based on this use-case, so please let me know if your use-case is different.

In Optuna, saving/loading trials can be done in storage, and it's not recommended to use serialize them on your hand.

`model.py`:

```python
class MyModel(tf.keras.Model):
    def __init__(self, n_dense: int):
        ....
```

`optimize.py`:

```python
def objective(trial: Trial) -> float:
    n_dense = trial.suggest_int("n_dense", 10, 100)
    model = MyModel(n_dense)

    lr = trial.suggest_float("lr", ...)
    opt = ....
    model.compile(optimizer=opt, loss="mse")

    cb = ...
    callbacks = [
        cb...,
        ...,
        TFKerasPruningCallback(trial, "val_loss"),
    ]

    history = model.fit(
        x=self.data["train"],
        validation_data=self.data["val"],
        epochs=400,
        callbacks=callbacks,
        verbose=True if best_model else False,
    )

    return history.history["val_loss"][-1]


study = optuna.create_study(storage="sqlite:///optuna.db", study_name="optuna")
study.optimize(objective, n_trials=...)
```

`train_with_best.py`:

```python
from ... import MyModel


study = optuna.load_study(storage="sqlite:///optuna.db", study_name="optuna")
best_trial = study.best_trial
model = MyModel(best_trial.n_dense)
cb = tfk.callbacks
callbacks = [
    cb.ReduceLROnPlateau(
        factor=0.9, monitor="val_loss", verbose=True if best_model else False
    ),
    cb.EarlyStopping(monitor="val_loss", patience=40),
]
pp = Path(...)
...
mc = cb.ModelCheckpoint(pp, verbose=1, save_best_only=True)
callbacks.append(mc)
...

history = model.fit(
    x=self.data["train"],
    validation_data=self.data["val"],
    epochs=400,
    callbacks=callbacks,
    verbose=True if best_model else False,
)
```

Also, you can merge the above scripts into one:

```python
class MyModel(tf.keras.Model):
    def __init__(self, n_dense: int):
        ....
```

`all_in_one.py`:

```python
def objective(trial: Trial) -> float:
    n_dense = trial.suggest_int("n_dense", 10, 100)
    model = MyModel(n_dense)

    lr = trial.suggest_float("lr", ...)
    opt = ....
    model.compile(optimizer=opt, loss="mse")

    cb = ...
    callbacks = [
        cb...,
        ...,
        TFKerasPruningCallback(trial, "val_loss"),
    ]

    history = model.fit(
        x=self.data["train"],
        validation_data=self.data["val"],
        epochs=400,
        callbacks=callbacks,
        verbose=True if best_model else False,
    )

    return history.history["val_loss"][-1]


study = optuna.create_study(storage="sqlite:///optuna.db", study_name="optuna")
study.optimize(objective, n_trials=...)

best_trial = study.best_trial
model = MyModel(best_trial.n_dense)
cb = tfk.callbacks
callbacks = [
    cb.ReduceLROnPlateau(
        factor=0.9, monitor="val_loss", verbose=True if best_model else False
    ),
    cb.EarlyStopping(monitor="val_loss", patience=40),
]
pp = Path(...)
...
mc = cb.ModelCheckpoint(pp, verbose=1, save_best_only=True)
callbacks.append(mc)
...

history = model.fit(
    x=self.data["train"],
    validation_data=self.data["val"],
    epochs=400,
    callbacks=callbacks,
    verbose=True if best_model else False,
)
```


The point is that we don't want you to save/load `FrozenTrial` directly and use `storage` (`study`) for the purpose. Also it is notable that it separates optimization step and training (with best trial) step.

@kuelumbus Does it help you? Please correct me if I misunderstand your use-case.

**Comment by kuelumbus** [comment]
You are right about what I want to do. 

Your example is how my first attempt looked and won't run long. `TFKerasPruningCallback` raises `exceptions.TrialPruned`  if pruned that you need to catch with `try` ... `except`, otherwise it will cancel your run.  I was quite surprised that it's coded like this. The `try`-`exception` construction makes the code look messy. `study.optimize` nicely handles all the exceptions and also prints logging info which is very helpful (even necessary for me).

https://github.com/optuna/optuna/blob/b348db8be2994ef05e282409ec0cae42f671e05a/optuna/integration/tfkeras.py#L51-L62

I am not sure what's the best solution to this. Keras-tuner solves this by making the hyperparameter object serializable to JSON. (`get_config` and `from_config` methods). If you don't want to do this (which I still don't understand why), maybe refactoring the optimize function helps. `ask`, `tell` and `finish` (or so). `finish` would do all the exception and printing stuff. But this is not an easy task.

**Comment by himkt** [comment]
Do you want to use `TFKerasPruningCallback` after optimization? The following section (retraining using the optimization result) doesn't use `TFKerasPruningCallback` because it trains a model with best parameters and the training should be stopped only by early stopping. It doesn't raises `TrialPruned`.

```python
best_trial = study.best_trial
model = MyModel(best_trial.n_dense)
cb = tfk.callbacks
callbacks = [
    cb.ReduceLROnPlateau(
        factor=0.9, monitor="val_loss", verbose=True if best_model else False
    ),
    cb.EarlyStopping(monitor="val_loss", patience=40),
]
pp = Path(...)
...
mc = cb.ModelCheckpoint(pp, verbose=1, save_best_only=True)
callbacks.append(mc)
...

history = model.fit(
    x=self.data["train"],
    validation_data=self.data["val"],
    epochs=400,
    callbacks=callbacks,
    verbose=True if best_model else False,
)
```

**Comment by kuelumbus** [comment]
I am kind of using it in both cases but the callback shouldn't do anything in the case of training the final model with the FrozenTrial because `should_prune` is always `False` for FrozenTrials.  The `optimize.py` file (objective function) you show above will not work because you need to catch the `TrialPruned` exception.

**Comment by kuelumbus** [comment]
Oh my bad. I didn't see that you wrapped everything in the optimize function. Let me try your example tomorrow.

**Comment by himkt** [comment]
> using it in both cases but the callback shouldn't do anything in the case of training the final model with the FrozenTrial because should_prune is always False for FrozenTrials

It would be better not to utilize this behavior and be simpler to separate them.

> I didn't see that you wrapped everything in the optimize function

Yeah, my example is abstracted as follows:

```python
def objective(trial: Trial):
    # model optimization
    model = MyModel(trial.suggest_int(...))  # suggest parameter
    history = model.fit(callback=[TFKerasPruningCallback(), ...])  # use TFKerasCallback
    return history["val_loss"][-1]  # metric


study = create_study()
study.optimize(objective)


# ==== finish optimization and start retraining ====


best_trial = study.best_trial
model = MyModel(best_trial.parameter)  # use best parameter
model.fit(callbacks=[...])  # does not contain TFKerasPruningCallback
```

**Comment by kuelumbus** [comment]
This works now as expected and the code is much cleaner. Thanks for your help.
