### ISSUE TITLE
Create a concept for data drift and allow parameters to be trained with an evolving data set

### ISSUE THREAD

**Issue by Fish-Soup** [optuna/optuna#3306]
### Motivation

Often with real life problems we have constantly updating/growing data sets. This can present us with a design problems. 

Firstly when the data is updated, its possible the the new ideal hyper-parameters could be very similar or different. We could continue to use the same study, allowing us to quickly arrive at reasonable hyper-parameters. But as the data evolves the hyper-parameters should drift, keeping all the old trials for old data will stop this happening efficiently. Its also possible the 'best' parameters are chosen from significantly older dataset that it no longer relevant.

This leads to another design issue, should I refit every time I get new data or should I let the hyper-parameter fitting continue for longer to find the ideal solution.

There is a way to get the best of both worlds, 
1. Use trials from old data sets to inform the ideal parameters of new datasets
2. Whilst allowing the parameters to evolve away from old ideal parameters.

### Description

I have achieved the above in optuna but it is quite clunky, and I feel this is a generic enough issue that it would be ideal to include it in the package. The process I am using is as follows, create a study and extract the sampler. I use the partial fixed sampler to force the data view_from to stay the same for a given optimization. 
A callback is used to quit the study when new data is available and que best trial excluding the view_from parameter. The study is then restarted with fresh data and a new view_from set in the partial sampler.

```python
import optuna
import numpy as np
import pandas as pd
from typing import Tuple
from sklearn.linear_model import Ridge
from functools import partial


def get_view_from() -> int:
    """some function that gets current data view_from"""


def get_data() -> Tuple[pd.DataFrame, pd.Series]:
    """some function that gets data"""


def get_view_from_and_data() -> Tuple[int, pd.DataFrame, pd.Series]:
    view_from = get_view_from()
    X, y = get_data()
    return view_from, X, y


def get_filtered_study(study: optuna.Study, view_from=None):
    """
    gets a study but just from 1 given view from, this is clunky would be better
    if study had a function to get best params at a given view_from
    """
    trials = [t for t in study.trials if t.state.name == 'COMPLETE' and t.params["view_from"] == view_from]
    filterred_study = optuna.create_study(directions=study.directions)
    filterred_study.add_trials(trials)
    return filterred_study


def objective(trial: optuna.trial, X, y):
    view_from = trial.suggest_int("view_from", low=0, high=np.inf)
    model = Ridge(alpha=trial.suggest_float("alpha", low=0, high=100))
    model.fit(X, y)
    """ do the rest of the optimization"""

study = optuna.create_study()
initial_sampler = study.sampler

# get fit data
view_from, X, y = get_view_from_and_data()
study.sampler = \
    optuna.samplers.PartialFixedSampler(fixed_params=dict(view_from=view_from), base_sampler=initial_sampler)
study.optimize(partial(objective, X=X, y=y), n_trials=1000)


# que best study for new data
params = get_filtered_study(study, view_from).best_params  # this best trial has to b
_ = params.pop("view_from")
study.enqueue_trial(params)


# get updated fit data
view_from, X, y = get_view_from_and_data()
study.sampler = \
    optuna.samplers.PartialFixedSampler(fixed_params=dict(view_from=view_from), base_sampler=initial_sampler)
study.optimize(partial(objective, X=X, y=y), n_trials=1000)


```
This could be extended with a call back class that takes the function that generates the timestamp of the data. This way the fit could be wrapped in a While True and would update its data each time the fit data updated.

```python
class StopAndQue:
    def __init__(self, get_data_view_from: Callable):
        self.get_data_view_from = get_data_view_from
        
    def __call__(self, trial: optuna.Trial, study: optuna.Study):
        if trial.params["view_from"] < self.get_data_view_from():
            best_trial = get_filtered_study(study, trial.params["view_from"])
            params = best_trial.params  # this best trial has to b
            _ = params.pop("view_from")
            study.enqueue_trial(params)
            study.stop()
            
        

while True:
    view_from, X, y = get_view_from_and_data()
    study.sampler = \
        optuna.samplers.PartialFixedSampler(fixed_params=dict(view_from=view_from), base_sampler=initial_sampler)

    study.optimize(partial(objective, X=X, y=y), n_trials=1000000000, callbacks=[StopAndQue(get_view_from)])
```

Not sure if all the above should be implemented, but the very least the concept of a view_from that can be passed at optimization, that fixes the partial fixed sampler under the hood. So we would write

```
view_from, X, y = get_view_from_and_data()
study.optimize(partial(objective, X=X, y=y), n_trials=1000, view_from=view_from)

```

and all the accessing etc of view_from is done under the hood. In addition study should have 

```
best_trial_at_view_from = study.get_best_trial(view_from=view_from)
```

**Comment by Fish-Soup** [comment]
Any thoughts on above? i'm not against doing this myself if its something people might want.

**Comment by nzw0301** [comment]
It sounds similar functionality provided by [`CmaEsSampler`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.samplers.CmaEsSampler.html)'s `source_trials` in high-level idea. 

Honestly, I'm not sure Optuna should provide such functionality as callback because 
1. it can be done with several lines as you demonstrated 
2. souhds a little bit specific scenario that users can handle
3. I don't know if the approach is well-grounded in a black-box optimisation context.
