### ISSUE TITLE
Alternative ways of providing a storage url to the CLI

### ISSUE THREAD

**Issue by niklasmohrin** [optuna/optuna#3307]
### Motivation

We are using optuna on a shared server where everyone can see everyone else's running processes though tools like `ps` or `htop`. This includes the full command used to spawn the process, which in turn includes the value passed as the `--storage` parameter, containing login credentials for the database. Only a small number of people should have access to the database used to store optuna studies, since it contains sensitive data.

Running studies from within our Python project works fine by loading the secret database connection url from a file and passing that to the provided library functions, but (as far as I can tell) optuna's command line interfaces only allow passing the storage url in the process `argv`.

In particular, this also applies to `optuna-dashboard`, for which I couldn't find a library interface to work around this issue. Still, I believe the request applies to the project as a whole.

### Description

The best outcome would of course be, that this option already exists and I just couldn't find it in the documentation - the "feature" would then be to better highlight the option, for example in the output of `optuna --help`.

Otherwise, there are three approaches that I can think of:

1. Add support for specifying the storage through an environment variable, for example `OPTUNA_STORAGE_URL`. This is the easiest option, since it would just need a simple branch in the `_check_storage_url` function in `cli.py`.
2. Add a configuration file for either all arguments, or just credentials. The path to this file would be specified with a new command line argument such as `--config`, `--storage-config`, `--credential-file`, ...
3. Allow passing the storage url by stdin. The `storage` argument could allow `-` as a value which would result in reading the storage url from stdin. This is probably the most flexible interface for users, since they can easily pipe environment variables, files, or whatever fits their needs into the optuna process. On the other hand, this approach is not valid if any other functionality needs stdin, and even if not, I would find the interface rather dirty and inelegant.

Personally, I think the environment variable would be the most intuitive and conventional solution.

### Alternatives (optional)

For the time being, I will probably run a modified checkout of `optuna-dashboard` that will read the storage url from a local file.

**Comment by himkt** [comment]
Thank you for opening the issue @niklasmohrin. We'd like to be careful to introduce a config file or environment variable based on the following history/concerns:

> Add a configuration file for either all arguments

The configuration file existed in the early of Optuna and it was removed in https://github.com/optuna/optuna/pull/653. This removal was to simplify the way to set up storage configuration (+ historical reason to move to Optuna CLI interface). It was complicated that there are two ways to specify storage, we want to keep it simple.

> Add support for specifying the storage through an environment variable

We also want to be careful with the same reason. Optuna writes stuff to storage. Users might mistake storage by allowing both environment variables and `--storage` option. Please consider using Python script as you noted when you use storage with credentials.

On the other hand, I'm wondering optuna-dashboard could have an option of the environment variable. AFAIK, optuna-dashboard assumes users to launch a dashboard by CLI. And it is mainly read-only (at least, it doesn't write anything with launching), which means that it has a lower risk of mistaking storage (as I understand, please correct me if I'm wrong). I'd like to hear an opinion by @c-bata for the topic on optuna-dashboard side.

**Comment by c-bata** [comment]
Thank you for your suggestion 👍 

I also would like to be careful to introduce a configuration file or environment variable to optuna-dashboard. Although the risk of mistaking storage is lower than Optuna, it makes optuna-dashboard more complicated as well. And I'd say there are benefits to have consistency with Optuna. For now, you can launch optuna-dashboard from the Python code if you need to hide your credentials from the output of `ps` and `htop`.

```python
import optuna
from optuna_dashboard.app import create_app

if __name__ == "__main__":
    study = optuna.load_study(...)  # your credentials here.
    app = create_app(study.storage)
    app.run(...)
```

Also, if you have security concerns, you may possibly consider more secure solutions in the system level (e.g. Isolate [PID namespaces](https://www.toptal.com/linux/separation-anxiety-isolating-your-system-with-linux-namespaces)).

**Comment by niklasmohrin** [comment]
Great, thank you! Closing :)
