### ISSUE TITLE
OPTUNA Visualization

### ISSUE THREAD

**Issue by manza-ari** [optuna/optuna#3313]
### What is an issue?

Can I make the following visualizations (Figures 6 and 7) shown in this paper using OPTUNA?

 [https://reader.elsevier.com/reader/sd/pii/S0169743921001222?token=17140BF9F07FDECA1B6F208B340D8C3881795E76E5DF4257735AB9E3F3716FE2A2C15898FD86715A49976144847C4191&originRegion=us-east-1&originCreation=20220215021650](url)

If Yes kindly share the documentation link for such graphs

**Comment by himkt** [comment]
Hi @manza-ari, I think slice plot and optimization history plot are equivalent to fig6 and fig7 respectively.

- https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_slice.html#optuna.visualization.plot_slice
  - https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.matplotlib.plot_optimization_history.html#optuna.visualization.matplotlib.plot_optimization_history
- https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_optimization_history.html#optuna.visualization.plot_optimization_history
  - matplotlib: https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.matplotlib.plot_slice.html#optuna.visualization.matplotlib.plot_slice

**Comment by himkt** [comment]
Let me close the issue @manza-ari, please feel free to reopen if you need. 🙋
