### ISSUE TITLE
Can Optuna be used as a tool for Evolutionary Multi-objective Optimization, like Pymoo?

### ISSUE THREAD

**Issue by da2la** [optuna/optuna#3326]
### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Description

Can Optuna be used as a tool for Evolutionary Multi-objective Optimization, like Pymoo?
Can NSGA-II, MODE and other algorithm be used to replace the default TPE, GP, CMA-ES?

### Error messages, stack traces, or logs

```shell
Just a question.
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by himkt** [comment]
Hello @da2la, you can use NSGA-II sampler for multi-objective optimization as an evolutionary algorithm in Optuna.
