### ISSUE TITLE
Do pruning algorithms assume that intermediate values should be decreasing with steps?

### ISSUE THREAD

**Issue by hbredin** [optuna/optuna#3331]
### Environment

- Optuna version: 2.3.0
- Python version: 3.8.0
- OS: Out[6]: 'Linux-4.18.0-193.70.1.el8_2.x86_64-x86_64-with-glibc2.10'

### Description

I am using optuna to optimize speaker diarization pipelines in [pyannote.audio](https://github.com/pyannote/pyannote-audio).

Each trial more or less follows this pseudo-code:

```python
pipeline.instantiate(suggested_params)
objective = []
for file in training_set:
   output = pipeline(file)
   o = objective_function(file, output)
   objective.append(o)
return sum(objective) / len(objective)  # average over all files
```

Because the training set may contain a large number of files, I am considering pruning as a way to speed up the process:

```python
pipeline.instantiate(suggested_params)
objective = []
for f, file in enumerate(training_set):
   output = pipeline(file)
   o = objective_function(file, output)
   objective.append(o)

   # report average up to file f
   intermediate_value = sum(objective) / len(objective)
   trial.report(intermediate_value, f)
   if trial.should_prune():
      raise optuna.TrialPruned

return sum(objective) / len(objective)
```

Since some files may be more difficult than others, there is no guarantee that the sequence of intermediate values within a trial is decreasing. Only the final averaged value is of interest.

For instance, with a training set containing 4 files, one trial may result in the following sequence of intermediate values:

 file       |  objective      | intermediate_value | comment
-----|------|----------------------|-----
file1 | 10 | 10  | average over file1
file2 | 20 | 15  | average over file1 and file2
file3 | 30 | 20  | average over file1, file2, and file3
file4 | 15 | 18.75  | average over the whole training set returned by the trial (= the objective function we try to minimize)

Since file3 is intrisically more difficult to process than other files, this would be the case for all trials.

My question is: is that a problem if the sequence of intermediate values is not decreasing?

My understanding is that pruning is done by comparing intermediate values for a given step so this should not be a problem. But, after reading some Github issues here and there, I am not that confident after all.
I thought I'd ask directly at the source :-)

### Error messages, stack traces, or logs

```shell
Not applicable
```

### Steps to reproduce

Not applicable

**Comment by UntotaufUrlaub** [comment]
Hi,
I am also new, but I got it the same way as you. Only the values at the given step are compared. At least for Medianpruner, others might be different.
