### ISSUE TITLE
Keyboard interruption handling

### ISSUE THREAD

**Issue by CorentinNeovision** [optuna/optuna#3336]
### Motivation

At the moment, if a study is launched and then manually interrupted (with control-C), then the current trial is killed without updating the study database. This leaves a trial with the status RUNNING in the database which will never be cleaned.

I implemented a simple solution which would change that behaviour in the case of sequential execution (it doesn't change anything in case of parallel optimization, if n_jobs > 1), by setting the Trial to the FAIL state in database. I want to know if you would like that I open a pull request to add this change.

### Description

I implemented a simple handling which allow to handle a `KeyboardInterrupt` in `optuna.study._optimize._run_trial`. As a consequence, now if a study is interrupted by a `KeyboardInterrupt`, you get an additional warning log in addition to the `KeyboardInterrupt` stacktrace, which would look like this:
`[W 2022-02-25 11:05:17,337] Trial 15 failed because of the following error: KeyboardInterrupt()`
And the database stores properly that the Trial status is FAIL

**Comment by himkt** [comment]
Hi @CorentinNeovision, I'd like to be careful to introduce as it would needs some discussion.
(the motivation behind that is to keep exception handling slim as possible)

Instead, how about catching logic in your objective function?

```python
import time

import optuna


def objective(trial: optuna.trial.Trial) -> float:
    v = trial.suggest_float("v", 0, 10)
    try:
        time.sleep(1)
    except KeyboardInterrupt:
        trial.set_user_attr("reason", "keyboard interrupt")  # if you need
        return float("nan")

    return v


study = optuna.create_study()
study.optimize(objective, n_trials=10)
print(study.trials_dataframe())
```

### log

```sh
> python main.py                                                                                                                                       2022-02-26 00:48:56
[I 2022-02-26 00:48:58,439] A new study created in memory with name: no-name-ac8f8396-21bd-4a16-82dd-0538ca7c7499
/Users/himkt/work/github.com/himkt/optuna/optuna/trial/_trial.py:169: FutureWarning: UniformDistribution has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use :class:`~optuna.distributions.FloatDistribution` instead.
  distribution = UniformDistribution(low=low, high=high)
[I 2022-02-26 00:48:59,446] Trial 0 finished with value: 1.6357764656636398 and parameters: {'v': 1.6357764656636398}. Best is trial 0 with value: 1.6357764656636398.
[I 2022-02-26 00:49:00,454] Trial 1 finished with value: 6.147546873579451 and parameters: {'v': 6.147546873579451}. Best is trial 0 with value: 1.6357764656636398.
^C[W 2022-02-26 00:49:00,920] Trial 2 failed because of the following error: The objective function returned nan.
^C[W 2022-02-26 00:49:01,403] Trial 3 failed because of the following error: The objective function returned nan.
^C[W 2022-02-26 00:49:01,784] Trial 4 failed because of the following error: The objective function returned nan.
[I 2022-02-26 00:49:02,792] Trial 5 finished with value: 4.9854746345592 and parameters: {'v': 4.9854746345592}. Best is trial 0 with value: 1.6357764656636398.
^C[W 2022-02-26 00:49:03,234] Trial 6 failed because of the following error: The objective function returned nan.
^C[W 2022-02-26 00:49:03,542] Trial 7 failed because of the following error: The objective function returned nan.
[I 2022-02-26 00:49:04,551] Trial 8 finished with value: 0.3826490595646792 and parameters: {'v': 0.3826490595646792}. Best is trial 8 with value: 0.3826490595646792.
[I 2022-02-26 00:49:05,555] Trial 9 finished with value: 6.29832330222659 and parameters: {'v': 6.29832330222659}. Best is trial 8 with value: 0.3826490595646792.
   number     value             datetime_start          datetime_complete               duration  params_v   user_attrs_reason     state
0       0  1.635776 2022-02-26 00:48:58.440147 2022-02-26 00:48:59.446076 0 days 00:00:01.005929  1.635776                 NaN  COMPLETE
1       1  6.147547 2022-02-26 00:48:59.446807 2022-02-26 00:49:00.453052 0 days 00:00:01.006245  6.147547                 NaN  COMPLETE
2       2       NaN 2022-02-26 00:49:00.455840 2022-02-26 00:49:00.919862 0 days 00:00:00.464022  8.255275  keyboard interrupt      FAIL
3       3       NaN 2022-02-26 00:49:00.920670 2022-02-26 00:49:01.402122 0 days 00:00:00.481452  0.815584  keyboard interrupt      FAIL
4       4       NaN 2022-02-26 00:49:01.403956 2022-02-26 00:49:01.783936 0 days 00:00:00.379980  5.697639  keyboard interrupt      FAIL
5       5  4.985475 2022-02-26 00:49:01.784594 2022-02-26 00:49:02.790971 0 days 00:00:01.006377  4.985475                 NaN  COMPLETE
6       6       NaN 2022-02-26 00:49:02.793616 2022-02-26 00:49:03.234425 0 days 00:00:00.440809  4.599570  keyboard interrupt      FAIL
7       7       NaN 2022-02-26 00:49:03.235294 2022-02-26 00:49:03.542038 0 days 00:00:00.306744  1.578273  keyboard interrupt      FAIL
8       8  0.382649 2022-02-26 00:49:03.544353 2022-02-26 00:49:04.550792 0 days 00:00:01.006439  0.382649                 NaN  COMPLETE
9       9  6.298323 2022-02-26 00:49:04.552756 2022-02-26 00:49:05.555138 0 days 00:00:01.002382  6.298323                 NaN  COMPLETE
```

**Comment by CorentinNeovision** [comment]
Thanks for your reply!

Yes that would works if you need to only kill a some specifics `Trial` without killing the whole optimization, with the bonus addition of documenting in the database the reason of the failure.
However if you want to interrupt the whole optimization (which is what you would want to do if you didn't set a `n_trials` or  `timeout` ), that wouldn't work. You could either reraise the `KeyboardInterrupt` , but then it wouldn't be handled and the same infinite RUNNING state would happen, or you could reraise another `Exception`, but then it would be handled and wouldn't cause the optimization to stop.

My proposal is more about what is expected and/or documented as the default behaviour in case of interruption, and indeed I understand that would need to be discussed.

At the moment, the [optimize documentation ](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize) doesn't precise what is exactly the behaviour in case of interruption, only that the the study will stop to create new `Trial`.

So really this is your choice, feel free to close this issue or to ask me to send a pull request. In any case, it could be a good idea to describe the behaviour in case of interruption in the documentation.

Concerning the exception handling, it only consists in adding theses 3 lines in `optuna.study._optimize._run_trial`
```python
    except KeyboardInterrupt as e:
        state = TrialState.FAIL
        func_err = e

```
just before the following existing lines, already handling any `Exception` that could occurs within the objective function.
```python
    except Exception as e:
        state = TrialState.FAIL
        func_err = e
        func_err_fail_exc_info = sys.exc_info()

```
and then all the rest of the logic (adding the log, registering the state to the storage, etc...) is processed by the same functions that already process an exception raised in the objective function, so that shouldn't add too much complexity to the exception handling.

**Comment by himkt** [comment]
@CorentinNeovision 

I'm really sorry for the late response. I learned that `KeyboardInterrupt` is the special exception (not a subclass of `Exception`, taught by @sile) and now I feel it looks solid to catch it in optimization.

> it only consists in adding theses 3 lines in optuna.study._optimize._run_trial

We may need to change the type annotation for `func_err` as well to make mypy happy. If you are still willing to help us to work on it (again, sorry for the late reply), I'd like to review your PR!

**Comment by CorentinNeovision** [comment]
Thanks for your response! I made a pull request  #3374
I think the documentation could be improved, I tried to add a little more info but I couldn't find how to detail the status of interrupted Trials without being overly specific. If there is somewhere better in the doc than the `n_trials` and `timeout` doc to explain what kind of interruption leads to what status for the Trial, for sequential or parallel optimization, I'd be happy to do it.

**Comment by CorentinNeovision** [comment]
All new discussions are now on the pull-request

**Comment by rsnitsch** [comment]
Thank you for the suggestion and the pull request. I suffered from stale but "Running" trials as well.

For the time being I use this workaround:

```
class StoppedByKeyboardInterrupt(Exception):
    pass

class Objective(object):
    def __call__(self, trial: optuna.Trial):
        try:
            return self.call(trial)
        except KeyboardInterrupt:
            # Convert to normal exception so that the trial state will correctly be set to FAILED by optuna.
            # See also: https://github.com/optuna/optuna/issues/3336.
            trial.set_user_attr("note", "Stopped by KeyboardInterrupt")
            raise StoppedByKeyboardInterrupt()

    def call(self, trial: optuna.Trial):
        # The actual trial execution code...
        # ...
```
