### ISSUE TITLE
Plotting Graphs on remote server

### ISSUE THREAD

**Issue by manza-ari** [optuna/optuna#3350]
### What is an issue?

I am using optuna for the optimization of my model. As I am working on a computer vision problem I copied my code on the remote server for using multiple GPUs but I don't know how to see my graphs. My OPTUNA is code is following

**Comment by nzw0301** [comment]
Please see the following pages depending on your backend of visualisation library.

- Plotly: https://plotly.com/python/static-image-export/
- Matplot;ib: https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html

**Comment by manza-ari** [comment]
In matplotlib there is a function save.fig() which is working fine for plot_optimization_history() but not working for plot_slice() 
Is there any way to save the popup of graphs? Actually, my code is working fine on my computer but the issue is regarding the ssh server which I am using for my experiment

**Comment by manza-ari** [comment]
showing like this

![history](https://user-images.githubusercontent.com/33715985/156486372-377485e2-0936-47b0-acc3-88a2aabecddb.png)

**Comment by nzw0301** [comment]
If you call `plt.show()` before calling the function to save the figure such as `plt.savefig("history.png")`, the saved plot is empty.  I would like to repeat my previous comment again:
> Note that if you post an issue, please carefully follow the issue template to give minimal reproducible codes to us. Otherwise, it is really hard to investigate the issue.
