### ISSUE TITLE
Does the trial in Optuna support stop/resume feature?

### ISSUE THREAD

**Issue by yuanjames** [optuna/optuna#3351]
### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Description

I plan to stop a trial during the training and collect the feedback of a group of trials, then resume some trials. Is it possible to do this?

### Error messages, stack traces, or logs

```shell
.
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by himkt** [comment]
Hi @yuanjames, sorry for the vague answer on gitter. I asked other developers and let me answer the question again.

Stopping/resuming a study is not supported in Optuna. The paper of Optuna (https://arxiv.org/pdf/1907.10902.pdf) said:

> In order to avoid having to record massive number of checkpointed configurations(snapshots), our implementation does not allow repechage

Optuna doesn't assume an objective function to be resumable. If Optuna makes users to use some specific library, it would be possible to make a trial resumable using some checkpointing APIs in the library, but, Optuna is a library agnostic and so it is very hard to do.

**Comment by yuanjames** [comment]
Thanks
