### ISSUE TITLE
Control number of trials for plot functions

### ISSUE THREAD

**Issue by tomaszG247** [optuna/optuna#3358]
### Motivation

Plots such as plot_parallel_coordinate are unreadable with more than a few 10s of trials. Could add control over the number of trials shown. Presumably we would normally want to show the best trials

### Description

add parameter to plot function to control # of trials

**Comment by nzw0301** [comment]
As a workaround, I suggest creating a new study by extracting trials by using[`study.add_trials`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.add_trials).

**Comment by nzw0301** [comment]
I believe that my previous answer addresses your question. Let me close this issue. But please feel free to ask the question if you still have a question.
