### ISSUE TITLE
When does multivariate TPESampler fallback to independent sampling

### ISSUE THREAD

**Issue by UntotaufUrlaub** [optuna/optuna#3363]
Hi,

### Description

a few of my HPs are sampled independently in some / most of the trials even though I'm using multivariate=True. I want to fix that, but could not find any documentation what circumstances could lead to such behavior.
Could anybody please point me to the right resource or explain when the fallback is used.

### Error messages, stack traces, or logs

```shell
The parameter 'num_parallel_envs' in trial#12 is sampled independently instead of being sampled by multivariate TPE sampler. (optimization performance may be degraded). You can suppress this warning by setting `warn_independent_sampling` to `False` in the constructor of `TPESampler`, if this independent sampling is intended behavior.
```

kind regards

**Comment by himkt** [comment]
For example, multivariate option doesn't work when you define a dynamic search space (ref. https://github.com/optuna/optuna/issues/3325#issuecomment-1049727414). Currently this behavior is not documented and I think it would be better to appear in our documentation.

If you don't use a dynamic search space, I want to see it.

**Comment by UntotaufUrlaub** [comment]
Many thanks for your answer and the link!

As far as I am not mistaken the ranges of my hyper parameters should not change within one study. But I have some optional parameters which are only present in some studies. Is this also considered dynamic?
In #3325 it doesn't sound like optional parameters are an issue as long as the range is fixed.

For example there is one hyper parameter 'Layer_mode' which can choose between CNN and NN.
Then the next HP is selected from 'layer_size_{Layer_mode}' because CNN has the small range of a kernel and NN can have a bigger fully connected layer.
So for each trial only one of this is present. There range does not change.
In my logs it seems that both are sampled independently at times.

Is this also considered dynamic (otherwise I might have a bug in my ranges, but it doesn't look like it)?
