### ISSUE TITLE
Database description is incompatible with Oracle DB

### ISSUE THREAD

**Issue by aribault** [optuna/optuna#3365]
### Expected behavior

Tried to create an Optuna study with an Oracle DB storage.
Expected the tables to be created and the study to be added to the studies table.

### Environment

- Optuna version: 2.10.0, also reproduced with 3.0.0a2
- Python version: 3.8.8
- OS: Windows 10 x64

### Error messages, stack traces, or logs

```shell
sqlalchemy.exc.IntegrityError: (cx_Oracle.IntegrityError) ORA-01400: cannot insert NULL into ("SCHEMA"."STUDIES"."STUDY_ID")
[SQL: INSERT INTO studies (study_name) VALUES (:study_name) RETURNING studies.study_id INTO :ret_0]
[parameters: {'study_name': 'study_1', 'ret_0': <cx_Oracle.Var of type DB_TYPE_VARCHAR with value [[], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []]>}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

### Steps to reproduce

Create a study using an Oracle DB as storage.

```python
import optuna
oracle_cstr = 'oracle://...'
study = optuna.create_study(storage=oracle_cstr, study_name='my_study')
```

### Additional context (optional)

The issue stems from the fact that Oracle has no default autoincrementing behavior for integer primary keys such as studies.study_id and others, as described in [sql alchemy documentation](https://docs.sqlalchemy.org/en/14/dialects/oracle.html#auto-increment-behavior). 

As explained in the linked page above, the fix could be to change in models.py the respective id declarations such as

```python
study_id = Column(Integer, primary_key=True)
```
into either
```python
study_id = Column(Integer, Identity(), primary_key=True)
```
or 
```python
study_id = Column(Integer, Sequence("id_seq"), primary_key=True)
```
depending on whether compatibility with Oracle < 12 is desirable or not.

**Comment by HideakiImamura** [comment]
It would be great that anyone conduct a survey about this. If `RDBStorage` can support this with few lines, it should be fixed. Otherwise, we can implement other storage class or publish other software to support Oracle DB.

**Comment by dycw** [comment]
I would love to see this in. I'm currently using a locally patched version to get this working. Fiddling with `sqlite` is just a little suboptimal.
