### ISSUE TITLE
Unify the appearance among plot functions in the same backend

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3375]
### Motivation

Sub-issue of https://github.com/optuna/optuna/issues/2959.

### Description

The main targets are as follows (thank you @HideakiImamura for organising this!)

- [x] the position of figure title 
- [ ] the text size 
- [x] the position of Legend
- [x] Use the same colour maps
    - [x] Plotly: use the same colour map of [`plot_contour`](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_contour.html#optuna.visualization.plot_contour) as [`plot_parallel_coordinate`](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_parallel_coordinate.html) -- #3376 
    - [x] Matplotlib: same as Plotly
- [x] Use dense colour to represent better trials, 
- [x] Red-coloured point represents the best trials, the others are blue.

**Comment by nzw0301** [comment]
We might need to investigate text size. Another approach is to add a test to check font size, but I'm not sure this is a good approach.

**Comment by HideakiImamura** [comment]
As commented in https://github.com/optuna/optuna/pull/3504#issuecomment-1125624908, we (me, @nzw0301, and @keisuke-umezawa) have discussed the policy of aligning font size, and concluded that we don't have to do so. 

Let me close this issue since all tasks have completed.
