### ISSUE TITLE
Does SMAC sampling methods using random forest to model the surrogate exists in Optuna ?

### ISSUE THREAD

**Issue by Aboussejra** [optuna/optuna#3377]
### Environment

- Optuna version: 2.10
- Python version: 3.9.6
- OS: POP OS 21.04
- (Optional) Other libraries and their versions:

### Description

I saw I can use TPE, genetic algorithms, Random and grid search for sampling hyperparameters. I would like to try methods based on random forest to build the surrogate (Which are often called SMAC in the Litterature, see SMAC page 27 https://arxiv.org/pdf/2007.15745.pdf for example). I saw I can use BoTorchSampler to try gaussian processes sampling, yet I did not find a way to use random forest modeled surrogates for sampling. If it is not possible with Optuna, may you give me advice on how to use with another library, I did not found any :(.
Thank you in advance !

### Error messages, stack traces, or logs

```shell
Nothing to quote here
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by nzw0301** [comment]
Have you tried https://github.com/automl/SMAC3?
