### ISSUE TITLE
The optuna process seems stuck, the terminal does not print any information.

### ISSUE THREAD

**Issue by pengzhangzhi** [optuna/optuna#3379]
### Expected behavior

I follow your official doc to start a distributed hyper-param search program as shown in the code. 

```python
reproducibility()
    # Add stream handler of stdout to show the messages
    optuna.logging.get_logger("optuna").addHandler(logging.StreamHandler(sys.stdout))

    study = optuna.create_study(direction="minimize",
                                sampler=optuna.samplers.TPESampler(),
                                pruner=optuna.pruners.MedianPruner(),
                                study_name='distributed-example', 
                                storage='sqlite:///example.db', 
                                load_if_exists=True)
    study.optimize(objective, n_trials=200,n_jobs=-1)

    pruned_trials = study.get_trials(deepcopy=False, states=[TrialState.PRUNED])
    complete_trials = study.get_trials(deepcopy=False, states=[TrialState.COMPLETE])

    print("Study statistics: ")
    print("  Number of finished trials: ", len(study.trials))
    print("  Number of pruned trials: ", len(pruned_trials))
    print("  Number of complete trials: ", len(complete_trials))

    print("Best trial:")
    trial = study.best_trial

    print("  Value: ", trial.value)

    print("  Params: ")
    for key, value in trial.params.items():
        print("    {}: {}".format(key, value))
    
    
    if optuna.visualization.is_available:
        optuna.visualization.plot_contour(study)
        plt.savefig("plot_contour.pdf")
        optuna.visualization.plot_edf(study)
        
        optuna.visualization.plot_optimization_history(study)
        plt.savefig("plot_optimization_history.pdf")
        
        optuna.visualization.plot_parallel_coordinate(study)
        plt.savefig("plot_parallel_coordinate.pdf")
        
        optuna.visualization.plot_param_importances(study)
        plt.savefig("plot_param_importances.pdf")
        
        optuna.visualization.plot_pareto_front(study)
        plt.savefig("plot_pareto_front.pdf")
        
        optuna.visualization.plot_slice(study)
        plt.savefig("plot_slice.pdf")
        
```

This program runs for two days functionally. I can see the printed information from the terminal. But today, I found the terminal is struck.
```
================================================================
Total params: 1,559,616
Trainable params: 1,559,616
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 48.00
Forward/backward pass size (MB): 30.47
Params size (MB): 5.95
Estimated Total Size (MB): 84.42
----------------------------------------------------------------
                                                                                                 ^[[B^[[B^[[B^[[B^[[B






  0%|                                                                    | 0/139 [00:00<?, ?it/s]

```
I hypothesis  it is because the process is too heavy to execute.  
I then check out the sys info with `nvidia-smi`, `top` , and `free -h`.
The results shows that the linux system is not in a very bad condition.
```
(pytorch_p38) ubuntu@ip-172-31-14-60:~/spatial-temporal-transformer$ free -h
              total        used        free      shared  buff/cache   available
Mem:            30G         24G        1.4G        1.3G        4.7G        4.3G
Swap:            0B          0B          0B
```

```
top - 04:28:51 up 3 days,  1:43,  1 user,  load average: 1.08, 1.04, 1.00
Tasks: 241 total,   1 running, 172 sleeping,   0 stopped,   0 zombie
%Cpu(s):  8.1 us,  5.5 sy,  0.0 ni, 86.5 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 32408368 total,  1421828 free, 26056316 used,  4930224 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  4535800 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                 
 7979 ubuntu    20   0 45.467g 0.015t 1.393g S 100.0 50.8   5723:27 python                                                                                                                  
  986 ubuntu    20   0  970060  75236  34092 S   1.7  0.2   0:29.08 node                                                                                                                    
 2286 mysql     20   0 1489576 167180   3292 S   0.3  0.5   2:00.20 mysqld                                                                                                                  
32299 ubuntu    20   0  943440  66120  31796 S   0.3  0.2   0:03.53 node                                                                                                                    
    1 root      20   0  225476   5424   2868 S   0.0  0.0   0:03.70 systemd                                                                                                                 
    2 root      20   0       0      0      0 S   0.0  0.0   0:00.02 kthreadd                                                                                                                
    3 root       0 -20       0      0      0 I   0.0  0.0   0:00.00 rcu_gp             
```
```
(pytorch_p38) ubuntu@ip-172-31-14-60:~/spatial-temporal-transformer$ nvidia-smi
Sun Mar 13 04:29:22 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.47.03    Driver Version: 510.47.03    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            On   | 00000000:00:1E.0 Off |                    0 |
| N/A   31C    P0    27W /  70W |  12701MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      7979      C   python                          12697MiB |
+-----------------------------------------------------------------------------+
```

I do not know if this process is still running or not. What should I do about it? Can I have my searched hyper-parameters back? (I already have the database file, but I do not know how to find the best hyperparameters based on sql operations).  Do you all have any idea? Any suggestions would much appreciated!

### Environment

- Optuna version:
- Python version: 
- OS: ubuntu
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
not necessary.
```

### Steps to reproduce

1. not necessary.
2.
3.
```python
# python code
```

**Comment by pengzhangzhi** [comment]
For your information, I use a Linux tool: screen to help close and resume a terminal without killing the running process. My linux machine is amazon EC2.

**Comment by himkt** [comment]
Sorry but it's difficult to investigate given information...
Any minimum reproducible code could be helpful.

Two questions:

- I found `"distributed"` in your study name. Does the example assume there are multiple GPUs (i.e. some DDP-related logic exists in the codebase)? A process could be stuck with the wrong usage of DDP. Although I'm not sure if it is because your environment has a single GPU.
- Does the training go well without Optuna? I think this problem is happening outside Optuna... We can see the process is consuming CPU and I'm wondering if some procedure (e.g. preprocessing) is working on and it's very heavy.

**Comment by pengzhangzhi** [comment]
> Sorry but it's difficult to investigate given information... Any minimum reproducible code could be helpful.
> 
> Two questions:
> 
> * I found `"distributed"` in your study name. Does the example assume there are multiple GPUs (i.e. some DDP-related logic exists in the codebase)? A process could be stuck with the wrong usage of DDP. Although I'm not sure if it is because your environment has a single GPU.
> * Does the training go well without Optuna? I think this problem is happening outside Optuna... We can see the process is consuming CPU and I'm wondering if some procedure (e.g. preprocessing) is working on and it's very heavy.

The name is just copyied from the official doc.  I do only have one GPU. And I did not expicitly enable multi-GPU and I do not know the detail if the optuna does it for me. 
For the second question, I did not run any additional program as you can tell from the output of `top`. Sorry I do not understand  what does "minimum reproducible code " exactly refers to. The posted code already descrbe how I use the optuna. What more details do your want to know? The optuna process has been running for like two days. Today is the thrid day and I found this issue.  It works very well on the previous days. So I do not think it is because the training code has any problem. If so, the program would break at the first place. I conjuncture that the problem may lie in the system.  What additional information do you need? I will be more than happy to provide.

**Comment by pengzhangzhi** [comment]
I have another question. The searched hyper-parameter data is stored in the database. I do find many tables in it. If I terminate the session and re-run the program, can I make it continue its optimization plan?

**Comment by pengzhangzhi** [comment]
From the database, I found the process stopped running about a day ago.
```
1,0,1,RUNNING,2022-03-10 03:29:15.221648,
2,1,1,COMPLETE,2022-03-10 03:29:15.230486,2022-03-10 03:31:44.636932
3,2,1,RUNNING,2022-03-10 03:29:15.250608,
4,3,1,RUNNING,2022-03-10 03:29:15.265766,
5,4,1,COMPLETE,2022-03-10 03:29:15.281056,2022-03-10 17:25:49.202560
6,5,1,COMPLETE,2022-03-10 03:29:15.297238,2022-03-10 03:31:15.242228
7,6,1,RUNNING,2022-03-10 03:29:15.297775,
8,7,1,COMPLETE,2022-03-10 03:29:15.324075,2022-03-10 03:31:15.177419
9,8,1,COMPLETE,2022-03-10 03:31:15.305254,2022-03-11 03:22:22.907711
10,9,1,RUNNING,2022-03-10 03:31:15.305874,
11,10,1,RUNNING,2022-03-10 03:31:44.778977,
12,11,1,RUNNING,2022-03-10 17:25:49.228167,
13,12,1,COMPLETE,2022-03-11 03:22:22.931291,2022-03-11 09:40:48.368503
14,13,1,COMPLETE,2022-03-11 09:40:48.396193,2022-03-11 11:03:10.060282
15,14,1,COMPLETE,2022-03-11 11:03:10.083038,2022-03-11 18:41:07.310270
16,15,1,COMPLETE,2022-03-11 18:41:07.334023,2022-03-12 00:51:12.196382
17,16,1,COMPLETE,2022-03-12 00:51:12.218344,2022-03-12 11:51:33.980139
18,17,1,COMPLETE,2022-03-12 11:51:34.003403,2022-03-12 15:09:41.487886
19,18,1,RUNNING,2022-03-12 15:09:41.514405,
```

**Comment by himkt** [comment]
> The posted code already descrbe how I use the optuna

I want to run the code on my environment as well. Without knowing the inside `objective`, we cannot investigate anything.

> If I terminate the session and re-run the program, can I make it continue its optimization plan?

You can resume optimization ([tutorial](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html#sphx-glr-tutorial-20-recipes-001-rdb-py)). If you want to re-run unterminated trials, it needs to manually [enqueue](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.enqueue_trial).

> I found the process stopped running about a day ago

I'm curious there are other trials with running state. Other trials were stopped yourself, on error, or got stuck as well?

**Comment by chpironi** [comment]
I have the same issue. After several iterations of optimization, I start getting the following error:
`<env_dir>/lib/python3.8/site-packages/optuna/samplers/_tpe/parzen_estimator.py:188: RuntimeWarning: divide by zero encountered in true_divide
  coefficient = 1 / z / p_accept`
I've added some breakpoints and ran the debugger on parzen_estimator.py and sampler.py and I see that at some point,
`log_likelihoods_above = mpe_above.log_pdf(samples_below)`
gets all inf values. 
I believe this is used to sample some pdfs and that's where the whole thing gets stuck in some infinite loops. I haven't investigaed further, but I believe there are some edge cases that the TPESampler is not handling properly

**Comment by nzw0301** [comment]
Hi, @chpironi could you share minimal reproducible codes with us?

**Comment by pengzhangzhi** [comment]
> curious there are other trials with running state. Other trials were stopped yourself, on error, or got stuck as well?

Sorry for such a late response. I have figured out this problem, which turned out to be a system error. Due to the large batch size I used, the process struck and stop running. My solution is to stop and re-run them with a few processes each time.
