### ISSUE TITLE
Handle with the outliner in visualization module

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3382]
### Motivation

Sub-issue of #2959

Some visualisation methods cannot deal with a trial including inf/nan as an objective or intermediate value. For `inf` value, we would like to remove such trials before showing the plot. In addition, we would like to print warning messages like `trial 0 is skipped because its objective value is inf`.

### Description

I think we can address this issue by the following steps:

## 1. Implement a filter utility function to remove trails whose objective values are `inf` in https://github.com/optuna/optuna/blob/master/optuna/visualization/_utils.py.

Resolved by https://github.com/optuna/optuna/pull/3395

### `optuna.visualization.plot_contour`

<img width="981" alt="Screenshot 2022-03-14 at 20 25 54" src="https://user-images.githubusercontent.com/7121753/158162815-c3a7184d-a2bd-4cce-997a-ff4779013343.png">

Fixed by https://github.com/optuna/optuna/pull/3451.

~Current: If the objective value is `inf`, the plot looks strange.~
~Expected: The trial should be removed from the plot.~

### `optuna.visualization.plot_edf`

Fixed by https://github.com/optuna/optuna/pull/3435.

~Current: No lines~
~Expected: edf plot should be shown. A trial whose objective is `inf` should be removed.~

### `optuna.visualization.plot_parallel_coordinate`

<img width="965" alt="Screenshot 2022-03-14 at 20 29 48" src="https://user-images.githubusercontent.com/7121753/158163336-2f9df5ee-2c7a-48f5-8ead-fa279a575610.png">

Current: Objective value's axis looks strange.
Expected: All lines should be within the plot.

### `optuna.visualization.plot_param_importances`

Fixed by https://github.com/optuna/optuna/pull/3500.

~Current: No bars~
~Expected: Importance plot should be shown.~

~Note that if this problem comes from the algorithm to compute importance score, it should be also fixed.~

### `optuna.visualization.matplotlib.plot_contour`

Fixed by https://github.com/optuna/optuna/pull/3451.

<img width="484" alt="Screenshot 2022-03-14 at 20 33 42" src="https://user-images.githubusercontent.com/7121753/158163820-67910037-4ed8-460b-84f4-0b622da9114b.png">

Current: No contour lines
Expected: contour lines should be shown correctly.

### `optuna.visualization.matplotlib.plot_edf`

Fixed by https://github.com/optuna/optuna/pull/3435.

~Current: No lines~
~Expected: edf plot should be shown. A trial whose objective is `inf` should be removed.~

### `optuna.visualization.matplotlib.plot_parallel_coordinate`

Current: `ValueError: Axis limits cannot be NaN or Inf`
Expected: Plotted correctly

### `optuna.visualization.matplotlib.plot_param_importances`

Fixed by https://github.com/optuna/optuna/pull/3500.

~Current: No bars~
~Expected: Importance plot should be shown.~

~Note that if this problem comes from the algorithm to compute importance score, it should be also fixed.~

### Alternatives (optional)

All figures above are generated by running https://gist.github.com/HideakiImamura/67a150dec5774a18732527875774a9fe that @HideakiImamura created. This notebook will be helpful to resolve this issue.

**Comment by xadrianzetx** [comment]
I have time to work on this next week.

**Comment by divyanshugit** [comment]
@xadrianzetx @nzw0301 What are the things left in this issue? If anything is left then I would love to work on it.

**Comment by nzw0301** [comment]
> All lines should be within the plot.

Well, as shown in the figure, many lines connected with the leftmost vertical line for objective value are not in the figure. We expect all lines are in the figure, not outside the figure.

> How can I see my changes in the local (I mean how should I install the optuna for it)?

I'm not sure what you mean by this question. As in https://github.com/optuna/optuna/blob/master/CONTRIBUTING.md, we create a new branch from the current branch and run the tests... 

We expect a similar change by the related PRs (#3435 or #3451) and shall confirm the example by running the notebook provided in the issue description.

**Comment by divyanshugit** [comment]
> > All lines should be within the plot.
> 
> Well, as shown in the figure, many lines connected with the leftmost vertical line for objective value are not in the figure. We expect all lines are in the figure, not outside the figure.
> 
> > How can I see my changes in the local (I mean how should I install the optuna for it)?
> 
> I'm not sure what you mean by this question.
> 
> 

Got it Thanks and sorry for the stupid the question.

**Comment by nzw0301** [comment]
Oh, you don't need to say sorry! Asking unclear points before implementation is important 👍🏻

**Comment by himkt** [comment]
@takoika is now working on `plot_param_importance`.
