### ISSUE TITLE
Is there exists a method for user to initialize a start point for the sampler(or study)?

### ISSUE THREAD

**Issue by yhhu99** [optuna/optuna#3388]
### Motivation

A good start point can make the exploration of the search space much more faster, so how can I set a start point when I optimize a study?

### Description

I wonder if there exists a method for user to initialize a start point for the sampler(or study), so that it would converge faster?
For example , if I can set a good population for the NSGAII sampler as a initial population, it can converge very fast and get a good result.

**Comment by himkt** [comment]
Hi @yhhu99, how about using `enqueue_trial`? Please refer to our tutorial:

https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/008_specify_params.html#sphx-glr-tutorial-20-recipes-008-specify-params-py

**Comment by yhhu99** [comment]
> Hi @yhhu99, how about using `enqueue_trial`? Please refer to our tutorial:
> 
> https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/008_specify_params.html#sphx-glr-tutorial-20-recipes-008-specify-params-py

Thanks for your kind help! It is useful to me.
