### ISSUE TITLE
LightGBM Tuner - loss/evaluation function parameter tuning

### ISSUE THREAD

**Issue by sh0gg0th** [optuna/optuna#3390]
### Description

Using the traditional `study.optimize` interface, I define my eval function with a tunable classification threshold inside the `objective` function as follows:

```python
def objective(trial):
    threshold = trial.suggest_float("threshold", 0.1, 0.9)
    
    def f1_wrapper(y_pred, y_true):
        y_true = y_true.label
        y_pred = np.where(y_pred < threshold, 0, 1)
        return 'f1', f1_score(y_true, y_pred), True

    ...
```
Is there a way I can achieve the same functionality with the `optuna.integration.lightgbm.train` interface? Perhaps there's a minimal working example somewhere?

**Comment by sh0gg0th** [comment]
Still relevant.

**Comment by nzw0301** [comment]
> Perhaps there's a minimal working example somewhere?

I'm afraid that optuna does not have such an example.

> Is there a way I can achieve the same functionality with the `optuna.integration.lightgbm.train` interface?

No, we can pass a custom objective function as `fobj` as in https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.train.html. According to the docs, it takes only actual targets and predicted targets; it does not take `threshold`.

**Comment by sh0gg0th** [comment]
Thanks @nzw0301, guess I'll stick with my current approach then.
