### ISSUE TITLE
Improve the `Re-use the best values` tutorial page

### ISSUE THREAD

**Issue by divyanshugit** [optuna/optuna#3397]
### What is an issue?

There are some minor issues on the Re-use the best values tutorial page.

## Description
- [x] On the [Re-use the best values](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/010_reuse_best_trial.html) page, We should update the title as `re-use the best parameters` instead of `re-use the best values`. As the best value means the best objective value in most of the Optuna references.
- [ ] Mention `Study.best_trials` on the page for multi-objective optimization.

Context: https://github.com/optuna/optuna/pull/3396#pullrequestreview-917028874

**Comment by toshihikoyanase** [comment]
Let me re-open this PR since we still have an open task.

**Comment by nzw0301** [comment]
I'm afraid that I could not understand the expected change in the rest task in this issue..

@toshihikoyanase Can you elaborate on the motivation?

**Comment by divyanshugit** [comment]
@nzw0301  I think, we haven't mentioned `Study.best_trials` in any of the tutorials section and It can be displayed in Multi-objective optimization.

**Comment by nzw0301** [comment]
No, in my understanding, `Study.best_trials` has been mentioned in `Re-use the best trial` tutorial thanks to https://github.com/optuna/optuna/pull/3398.

**Comment by divyanshugit** [comment]
Yeah, you're right. In the `Re-use the best trial` tutorial we just mentioned that the `Study.best_trials`  is demonstrated in `Multi-objective Optimization with Optuna`. But we don't have any reference for `Study.best_trials` on the page.

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for pointing it out.

> `Study.best_trials` has been mentioned in `Re-use the best trial tutorial` thanks to https://github.com/optuna/optuna/pull/3398.

That makes sense. We should stick to the `Re-use the best values` tutorial page as the issue title mentioned.
I created an issue (https://github.com/optuna/optuna/issues/3421) on the update of the multi-objective optimization tutorial. 

So, I agree to close this issue.

**Comment by nzw0301** [comment]
@toshihikoyanase Awesome! Thank you for your clarification here and on issue #3421.
