### ISSUE TITLE
Adding constraint to optimization

### ISSUE THREAD

**Issue by marcushilliard** [optuna/optuna#3399]
### Environment

- Optuna version: 2.10.0
- Python version: 3.7
- OS: Mac 12.3

### Description

I am trying to add a constraint to my optimization where the sum of the suggested floats will need to be equal to a scaler value. Can this be done using the callback function? I currently have this set up as a multi-objective problem, but the issue is that I have to run 10,000 trials before reproducible results are obtained.

### Error messages, stack traces, or logs

```shell
No error messages
```

### Steps to reproduce

```python
def define_budget(trial, inputVal=inputVal, inputDat=inputDat, budget=budget, inputNumCol=inputNumCol):
    inputValArr = np.zeros((1,len(inputVal)))
    # Month
    inputValArr[:,23] = pd.to_datetime(inputDat).month
    # DOW
    inputValArr[:,24] = pd.to_datetime(inputDat).dayofweek
    # DOY
    inputValArr[:,25] = pd.to_datetime(inputDat).dayofyear
    # Quarter
    inputValArr[:,26] = pd.to_datetime(inputDat).quarter
    # fracDOY
    inputValArr[:,27] = pd.to_datetime(inputDat).dayofyear/365

    sugVarArr = np.zeros((1,23))

    for i in range(0,23):
        sugVarArr[:,i] = trial.suggest_categorical(inputNumCol[i], [True, False])
    for i in range(0,23):
        if sugVarArr[:,i] == True:
            inputValArr[:,i] = trial.suggest_float('x_'+str(i), inputVal['MinVals'][i], inputVal['MaxVals'][i])
        else:
            inputValArr[:,i] = 1.0

    budgetTMP = np.sum(inputValArr[:,0:23])

    return (budgetTMP-budget)**2, inputValArr

def eval_model(inputValArr):
    X_arr = X_scaler.transform(inputValArr)
    I_arr = Y_Inflow_scaler.inverse_transform(automlInflow.predict(X_arr).reshape(-1, 1))
    O_arr = Y_Outflow_scaler.inverse_transform(automlOutflow.predict(X_arr).reshape(-1, 1))
    N_arr = I_arr[0][0] - O_arr[0][0]
    return N_arr

def objective(trial):
    error, inputValArr = define_budget(trial)
    N_arr = eval_model(inputValArr)
    return error, N_arr

sampler = optuna.samplers.NSGAIISampler()

study = optuna.create_study(directions=["minimize", "maximize"], sampler=sampler, study_name="optuna-experiment")
study.optimize(objective, n_trials=10000, show_progress_bar=True)
```

**Comment by himkt** [comment]
> Can this be done using the callback function?

You can add constraints to the optimization by using `constraints_func` (note that `constraints_func` is not a hard constraint so some trials could violate constraint).

Example: https://github.com/optuna/optuna-examples/blob/main/multi_objective/botorch_simple.py

Constrained optimization is available on [`BoTorchSampler`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.BoTorchSampler.html#optuna.integration.BoTorchSampler) and [`NSGAIISampler`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.samplers.NSGAIISampler.html#optuna.samplers.NSGAIISampler).

For other samplers, we have to fail a trial whose a couple of parameters violates a constraint manually.

**Comment by nzw0301** [comment]
FYI https://optuna.readthedocs.io/en/v3.0.0-a2/faq.html#how-can-i-optimize-a-model-with-some-constraints is a faq section for constraint optimisation.

**Comment by alexisdrakopoulos** [comment]
Has there been any further progress on constraints? The option of ignoring candidates that violate constraints or applying penalties doesn't scale nicely when the feasible region is quite small due to many constraints
