### ISSUE TITLE
How ro reduce the suggection of repeated paramters by NSAGII Sampler

### ISSUE THREAD

**Issue by Zhang-Tongdi** [optuna/optuna#3400]
### Environment

- Optuna version:v3.0.0-a2, v2.9.1
- Python version:3.8
- OS:Ubuntu 20.04
- (Optional) Other libraries and their versions:None

### Description

We used Optuna to optimize a multi-objective problem which the cost function is very expensive to evaluate. We used the NSAGII Sampler and we found that it would suggest the same parameters in different trails, so we made a simple test (see and run the code in the folder named _benchemark_) and found that the same parameters keeps appearing in a high frequency. We also used to default settings of Optuna for multi-objective optimization and this problem is still be there, but the same paramters suggest by the method seems less frequent than NSGAII. The question is what causes such phnomenon.  Due to the high cost of evaluation of cost function, we want to reduce the suggection of repeated paramters and improve the sampling efficiency to get a better results. How can I to solve this problem.
The attach files include the benchmark and the practical results of my work. In practic work, we get 500 trails due to the expensive cost function and the detail settings can be found in the _main.py_. We can also found that the Pareto front obtained by NSAGII Sampler is worse than the results obtained by default settings of Optuna for multi-objective optimization. What is the reason for this results and how to improve the optimization results by NSGAII sampler. It should be note that v3.0.0-a2 was used when the sampler is NSGAII Sampler and v2.9.1 was for default settings of Optuna for multi-objective optimization.
Thanks!
[benchmark_and_practic_results.zip](https://github.com/optuna/optuna/files/8329560/benchmark_and_practic_results.zip)

### Error messages, stack traces, or logs

```shell
200
180
a = 562.1298400594555, b = 703.1352790497681
 1
a = -327.714839110351, b = 501.9696193505906
 1
a = 300.5829926369581, b = -232.008702830836
 1
a = 77.0147352421775, b = -629.0447335614735
 1
a = 46.09755204292833, b = 246.78326508540704
 1
a = 439.73492018675233, b = -449.6146511926315
 1
a = -303.3262098153375, b = -448.8490648544456
 1
a = 493.83244977275854, b = -39.07744973273259
 1
a = 822.1358409882923, b = 500.5008208267561
 1
a = -20.20675349737462, b = -22.364727812322712
 1
a = -32.73977094139764, b = -230.30677716628384
 1
a = 303.62172983364735, b = 518.6912861648109
 1
a = -181.33542242656995, b = 103.5311264553734
 1
a = -449.6189402567725, b = -100.41997642464003
 1
a = 245.25203158417185, b = -169.40679748950265
 1
a = -44.35752286266688, b = -201.89958030638786
 1
['a = 562.1298400594555, b = 703.1352790497681\n', 'a = -327.714839110351, b = 501.9696193505906\n', 'a = 300.5829926369581, b = -232.008702830836\n', 'a = -20.20675349737462, b = -22.364727812322712\n', 'a = 77.0147352421775, b = -629.0447335614735\n', 'a = 46.09755204292833, b = 246.78326508540704\n', 'a = 439.73492018675233, b = -449.6146511926315\n', 'a = -303.3262098153375, b = -448.8490648544456\n', 'a = 493.83244977275854, b = -39.07744973273259\n', 'a = 822.1358409882923, b = 500.5008208267561\n', 'a = -181.33542242656995, b = 103.5311264553734\n', 'a = 245.25203158417185, b = -169.40679748950265\n', 'a = -32.73977094139764, b = -230.30677716628384\n', 'a = 303.62172983364735, b = 518.6912861648109\n', 'a = -44.35752286266688, b = -201.89958030638786\n', 'a = -449.6189402567725, b = -100.41997642464003\n']
```

### Steps to reproduce

1.cd /benchmark_and_practic_results/benchmark
2. python benchmark
3. python stat.py
[benchmark_and_practic_results.zip](https://github.com/optuna/optuna/files/8329605/benchmark_and_practic_results.zip)

**Comment by nzw0301** [comment]
We can not open the zip file to reproduce the results for security concerns.  Could you create a public repo?

**Comment by Zhang-Tongdi** [comment]
The repository has been created and you can get the code in  @[https://github.com/Zhang-Tongdi/Optuna_test.git](url). Thanks!
