### ISSUE TITLE
[Request for Comments] Gitter vs GitHub Discussions for interactive interaction

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3404]
### Motivation

We've currently used [Gitter](https://gitter.im/optuna/optuna) for an interactive chat with developers and users https://github.com/optuna/optuna. Recently (?), GitHub offers [GitHub discussions](https://docs.github.com/en/discussions) that provide forum functionality. I suppose we might be able to replace Gitter with Github discussions because the dev-members mainly use gitter for release announcements or answering a question. I would like to hear the opinion of Optuna community. Ideally, we will have more interaction to improve Optuna by introducing it.

Any comments or feedback are welcome!

### Description

N/A

**Comment by divyanshugit** [comment]
IMO, GitHub discussion will be better than gitter as both have almost same functionalities. 
I'm thinking, Can we create a `Discord Server` for Optuna where we can host biweekly/monthly dev calls and it offers a lot more features in comparison to GitHub discussions/gitter!!

**Comment by nzw0301** [comment]
@divyanshugit thank you for your comments.

> Can we create a Discord Server for Optuna where we can host biweekly/monthly dev calls and it offers a lot more features in comparison to GitHub discussions/gitter!!

Do you mean you would like to have a regular opportunity to discuss with dev members?

**Comment by divyanshugit** [comment]
> Do you mean you would like to have a regular opportunity to discuss with dev members? In addition, could you elaborate what is the purpose of such a call?

As you said, It will give a regular opportunity to discuss with dev members. In addition to this, 
- We can keep the track of development through these calls.
- Guide/help new members with getting started and speed up the development.
- In return of above, we will attract new members to join the community.

**Comment by nzw0301** [comment]
Thank you for your clarification.

Let me ask one more thing: Could you share a concrete example of such a call? Repo name will be enough.

**Comment by divyanshugit** [comment]
In my knowledge, [Layer5](https://github.com/layer5io) and [OpenMined](https://github.com/OpenMined) are two orgs that does the above thing.

**Comment by nzw0301** [comment]
Thank you for sharing them. IMHO, Optuna dev members (around 10 people) are much less than Layer5, OpenMined, and Manim (# member is supposed to be over 100). So I suppose such a regular public meeting is quite difficult in the near future. Anyway, thank you for your feedback.

**Comment by divyanshugit** [comment]
Got it. Anyway, I'm looking forward to see these things in Optuna as well🤞🏻

**Comment by HideakiImamura** [comment]
Currently, GitHub discussions are open. Can I close this issue?

**Comment by HideakiImamura** [comment]
Let me close this issue. Please feel free to reopen this if you have any concerns.
