### ISSUE TITLE
The values of best_index_ and trial number do not match 

### ISSUE THREAD

**Issue by jckkvs** [optuna/optuna#3409]
### Expected behavior

I thought I could use best_index_ to find out which Trial reached the optimal solution. However, in reality, the value of best_index_ and the Trial number do not match.

I think it's because I got the idxmin of trials_dataframe, but is this behavior as the developer expected?

Also, what code should I write to know how many times it takes to reach the optimal solution? 

### Environment

- Optuna version:2.10.0
- Python version:3.7.11
- OS:windows10
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
Trial 59 finished with value: 0.07631298446927186 and parameters: {'min_child_weight': 9.419714797838857, 'subsample': 0.03818720585744753, 'learning_rate': 0.039630972438226164, 'max_depth': 8}. Best is trial 55 with value: 0.46498958997038853.

print(searchcv.best_index_)
> best_index_ 46

```

### Steps to reproduce

```python
    X, y  = load_diabetes(return_X_y=True)
    estimator = xgb.XGBRegressor()
    param_distribution = {
        "min_child_weight": UniformDistribution(0.1, 10),
        "subsample": UniformDistribution(0, 1.0),
        "learning_rate": LogUniformDistribution(1e-3, 5e-1),
        "max_depth": IntUniformDistribution(3, 15),
    }
    OpSearchCV = OptunaSearchCV(estimator, param_distribution ,n_trials=60)
    OpSearchCV.fit(X,y)
    print('best_index_', OpSearchCV.best_index_)
```

_No response_

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by nzw0301** [comment]
I think you are right. At least it should return ` df["value"].idxmax()`, not ` df["value"].idxmin()` because `OptunaSearchCV`'s objective direction is always `"maximize"`.

**Comment by nzw0301** [comment]
> Also, what code should I write to know how many times it takes to reach the optimal solution?

How about this?

```python
import optuna
from sklearn.datasets import load_iris
from sklearn.svm import SVC
import numpy as np

np.random.seed(11)
clf = SVC(gamma="auto")
param_distributions = {"C": optuna.distributions.LogUniformDistribution(1e-10, 1e10)}
optuna_search = optuna.integration.OptunaSearchCV(clf, param_distributions, n_trials=100)
X, y = load_iris(return_X_y=True)
optuna_search.fit(X, y)

sum([t.value == optuna_search.best_score_ for t in optuna_search.study_.get_trials()])
```

The last line is counting how many times the best score appears in the study.

**Comment by jckkvs** [comment]
Thanks.

I have confirmed that the code in # 3410 works correctly.
Also, thank you for the code below.

sum ([t.value == optuna_search.best_score_ for t in optuna_search.study_.get_trials ()])
