### ISSUE TITLE
Support latest PyTorch lightning

### ISSUE THREAD

**Issue by himkt** [optuna/optuna#3418]
### Expected behavior

Optuna works with the latest PyTorch-Lightning (1.6.0).

### Environment

- Optuna version: 3.0.0b0.dev
- Python version: 
- OS: Independent
- (Optional) Other libraries and their versions: PyTorch-Lightning 1.6.0

### Error messages, stack traces, or logs

```shell
tests/integration_tests/test_pytorch_lightning.py:158: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
optuna/study/study.py:399: in optimize
    _optimize(
optuna/study/_optimize.py:68: in _optimize
    _optimize_sequential(
optuna/study/_optimize.py:162: in _optimize_sequential
    trial = _run_trial(study, func, catch)
optuna/study/_optimize.py:262: in _run_trial
    raise func_err
optuna/study/_optimize.py:211: in _run_trial
    value_or_values = func(trial)
tests/integration_tests/test_pytorch_lightning.py:143: in objective
    trainer = pl.Trainer(
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/utilities/argparse.py:339: in insert_env_defaults
    return fn(self, **kwargs)
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:561: in __init__
    self._call_callback_hooks("on_init_start")
/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py:1617: in _call_callback_hooks
    fn(self, *args, **kwargs)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <optuna.integration.pytorch_lightning.PyTorchLightningPruningCallback object at 0x7f892c1c5730>
trainer = <pytorch_lightning.trainer.trainer.Trainer object at 0x7f892c1c5040>

    def on_init_start(self, trainer: Trainer) -> None:
>       self.is_ddp_backend = trainer._accelerator_connector.distributed_backend is not None
E       AttributeError: 'AcceleratorConnector' object has no attribute 'distributed_backend'

optuna/integration/pytorch_lightning.py:60: AttributeError
```

https://github.com/optuna/optuna/runs/5745775785?check_suite_focus=true

```
tests/integration_tests/test_pytorch_lightning.py:6: in <module>
    import pytorch_lightning as pl
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/__init__.py:30: in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py:26: in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/callbacks/pruning.py:31: in <module>
    from pytorch_lightning.core.lightning import LightningModule
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/core/__init__.py:16: in <module>
    from pytorch_lightning.core.lightning import LightningModule
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py:40: in <module>
    from pytorch_lightning.loggers import LightningLoggerBase
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/loggers/__init__.py:18: in <module>
    from pytorch_lightning.loggers.tensorboard import TensorBoardLogger
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/pytorch_lightning/loggers/tensorboard.py:26: in <module>
    from torch.utils.tensorboard import SummaryWriter
../../../hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:4: in <module>
    LooseVersion = distutils.version.LooseVersion
E   AttributeError: module 'distutils' has no attribute 'version'
```

https://github.com/optuna/optuna/runs/5745734509?check_suite_focus=true

### Steps to reproduce

See our CI failures.

### Additional context (optional)

It may be the simplest way to support PyTorch v1.11.0 (https://github.com/PyTorchLightning/pytorch-lightning/issues/12324).

🔗 https://github.com/optuna/optuna/pull/3417

**Comment by nzw0301** [comment]
I ran pytests related to pytorch on my local machine. The following integration tests failed.

- fastai: the latest fastai requires torch<1.11,>=1.7.0
- allelnlp: `Fatal Python error: Aborte` 🤔 
- pytorch-lightning: as described in this issue, we need to update our callback

**Comment by nzw0301** [comment]
Let's summarise the current candidates:
- Reimplement this feature using `Strategy`: see also https://github.com/optuna/optuna/pull/3431#issuecomment-1087290722
- Update the implementation as in https://github.com/optuna/optuna/pull/3431. The approach is similar to CatboosCallabck.
- try to approach shared by ptl developer in https://github.com/PyTorchLightning/pytorch-lightning/discussions/12569

**Comment by contramundum53** [comment]
This seems to be solved in #3510. We will close this issue.

**Comment by nzw0301** [comment]
I'm afraid not. As in https://github.com/optuna/optuna/blob/master/setup.py#L109, Optuna doesn't support the latest stable version: `1.6.*`.

**Comment by nzw0301** [comment]
Sorry, I mentioned the wrong line. It should have been https://github.com/optuna/optuna/blob/fd575d04cebae8b471e72aa890e4a4cb052aa083/.github/workflows/tests-integration.yml#L79.

**Comment by hrzn** [comment]
@nzw0301 would be happy to have a look if I find a bit of time. Did you narrow down to some preferred way of solving the problem?

**Comment by nzw0301** [comment]
@hrzn Yes, https://github.com/optuna/optuna/pull/3431 was my attempt to resolve the PL so it might be helpful.

**Comment by g-votte** [comment]
This issue is still open for contribution.

The goal is to remove [this line](https://github.com/optuna/optuna/blob/594858fd3f43fbb713f411a47ff264b08b8d2337/.github/workflows/tests-integration.yml#L63) in the CI setting, after fixing the test failures.

**Comment by toshihikoyanase** [comment]
@higucheese is kindly working on this issue now.
The current latest version of pytorch lightning is [1.8.0.post1](https://github.com/Lightning-AI/lightning/releases/tag/1.8.0.post1).

**Comment by nzw0301** [comment]
If users want to use single process training with recent PyTorch-lightning, the older callback might work fine: define `PyTorchLightningPruningCallback` in https://github.com/optuna/optuna-examples/issues/166#issuecomment-1403112861 instead of `optuna.integration.PyTorchLightningPruningCallback` might be a workaround.
