### ISSUE TITLE
how to set the 'target' in multi-objective optimization

### ISSUE THREAD

**Issue by pistachio-xin** [optuna/optuna#3423]
### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Description

when I run the code 'optuna.visualization.matplotlib.plot_parallel_coordinate(study)' , meet the error:
If the `study` is being used for multi-objective optimization, please specify the `target`.

So, I want to consult you how to set the target, Can give me a example?
Thank you very much!

### Error messages, stack traces, or logs

```shell
If the `study` is being used for multi-objective optimization, please specify the `target`.
```

### Steps to reproduce

1.import optuna
2.algo = optuna.samplers.TPESampler(n_startup_trials = 10, n_ei_candidates = 24)

3.study = optuna.create_study(sampler = algo, directions=["minimize", "maximize"])
4.study.optimize(objective, n_trials=300, timeout=300)

**Comment by nzw0301** [comment]
For example,
```python
optuna.visualization.plot_parallel_coordinate(
    study, target=lambda t: t.values[0], target_name="objective_0"
)
```
https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/002_multi_objective.html

**Comment by himkt** [comment]
It beyonds the topic of this issue, I suspect the current latest branch doesn't work with multi-objective optimization.

In `_get_parallel_coordinate_plot` check a direction by the following code, but `study.direction` is not available in multi-objective optimization. If my understand is correct, I'll create a tracking issue.

https://github.com/optuna/optuna/blob/7886c35cc62a4ee937e5e6dfca20b8e5afd5bbe3/optuna/visualization/_parallel_coordinate.py#L101

```python
from typing import Tuple

import optuna


def objective(trial: optuna.Trial) -> Tuple[float, float]:
    return trial.suggest_float("v1", 0, 10), trial.suggest_float("v2", 0, 10)


def target(t: optuna.trial.FrozenTrial) -> float:
    return t.values[0]


study = optuna.create_study(directions=["minimize", "maximize"])
study.optimize(objective, n_trials=50)


fig = optuna.visualization.plot_parallel_coordinate(study, target=target)
fig.show()
```

**Comment by pistachio-xin** [comment]
Hi@himkt @nzw0301,
 Thanks for your help, I run right for this issue and got the right figure.
For the issue from @himkt,  In my test code, I can saw the function of optimization direction in the  multi-objective optimization problems, but maybe I didn't understand your means.

**Comment by nzw0301** [comment]
@pistachio-xin Awesome. Thank you for letting us know that!

**Comment by himkt** [comment]
@pistachio-xin Sorry for confusing you, the problem I mentioned happens only on the master branch of Optuna and it doesn't happen on our published versions of Optuna. You don't need to take care of it. :+1:
