### ISSUE TITLE
Explain when colormap is reversed

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3433]
The colormaps of `plot_contour` and `plot_paralell_coordinate` are reversed depending on its optimisation direction and `target` argument. It would be great to explain this rule in their documentation.

See https://github.com/optuna/optuna/pull/3424 for the concrete rule.

_Originally posted by @nzw0301 in https://github.com/optuna/optuna/pull/3424#discussion_r840738425_

**Comment by divyanshugit** [comment]
@nzw0301 Can you please tell me what exactly needs to be done on this issue to resolve it?

**Comment by nzw0301** [comment]
Add an explanation when the colormap is reversed to somewhere on the following pages:

- https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.plot_contour.html
- https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.plot_parallel_coordinate.html
- https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.matplotlib.plot_contour.html
- https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.matplotlib.plot_parallel_coordinate.html

**Comment by jcob-sikorski** [comment]
Could you elaborate more about the rule to explain? I need more info what's the rule.

**Comment by nzw0301** [comment]
I believe that https://github.com/optuna/optuna/blob/0964da28442996931e9a6e967b586649bc357ce3/optuna/visualization/_utils.py#L174 is informative enough.

**Comment by HideakiImamura** [comment]
Thanks @nzw0301 to explain the rule. So, the rule is "The colormap is reversed when the `target` argument is not None or the objective function of the study is a minimization problem."

This issue is still an open, so anyone can submit the PR to resolve this issue.
