### ISSUE TITLE
`ConvergenceWarning` displayed in Ask-and-Tell Interface tutorial

### ISSUE THREAD

**Issue by xadrianzetx** [optuna/optuna#3439]
### What is an issue?

The warning in [this](https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/009_ask_and_tell.html#apply-optuna-to-an-existing-optimization-problem-with-minimum-modifications) section can be muted as it's not related.
![Screenshot from 2022-04-03 14-15-30](https://user-images.githubusercontent.com/37713008/161427656-7141d50d-23a0-42d6-9a66-e07950c6b5ad.png)

**Comment by toshihikoyanase** [comment]
We can see the warning in the [latest document](https://optuna.readthedocs.io/en/latest/tutorial/20_recipes/009_ask_and_tell.html). Please keep it open.
