### ISSUE TITLE
Optuna Best Model

### ISSUE THREAD

**Issue by rm17tink** [optuna/optuna#3445]
### Environment

Environment
Optuna version: 2.10.0
Python version: 3.6
OS: Windows 10
(Optional) Other libraries and their versions: lightgbm = 3.3.2

### Description

I am trying to use lightgbm best params to and best model save to then use on a subset of the data(e.g. top 50 features from first model optuna tuning.  However I cant use best_booster.fit() as the N_features is greater than what I am passing. What can I do to use the first model on the second model?  thanks

Also is there a way for me to extract the train_auc  from inside the objective run?  right now I am only reporting the valid_auc

### Error messages, stack traces, or logs

```shell
ValueError: Number of features of the model must match the input. Model n_features_ is 830 and input n_features is 50
```

### Steps to reproduce

1. Run first model then second to get auc for train
2. find top 50 features
3. Run new model on said 50 features only : 
```
best_booster.fit(X_train,y_train
       ,eval_set=[(X_valid,y_valid)]
                 ,eval_names=['Valid']
                 ,eval_metric = 'auc' # New 
                 ,verbose=False
                 ,early_stopping_rounds=1000 
                )
```

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?
