### ISSUE TITLE
 trial._suggest supports GridSampler

### ISSUE THREAD

**Issue by jieru-hu** [optuna/optuna#3453]
### Motivation

Hi I am working on adding GridSampler to Hydra's Optuna Sweeper. This is my PR in progress https://github.com/facebookresearch/hydra/pull/2132

I noticed that GridSampler seems to have different interfaces from the other Samplers. For example:
`trial._suggest` does not work with a GridSampler.

I'm wondering if this could be supported? If not, is there any work around for this? 

If not possible, we can still hard code some of the logic in the Sweeper to support this, but thought I'd ask the experts here to see if there's a more elegant solution to this. Happy to provide more context if needed. Thanks in advance!

### Description

See above

**Comment by jieru-hu** [comment]
cc @toshihikoyanase any suggestion?

**Comment by toshihikoyanase** [comment]
Thank you for your hard work to improve the Optuna sweeper of Hydra!

Before going into the design discussion of the sampler,  I have a question about your motivation to introduce Optuna's grid sampler to the sweeper.
In my understanding, Hydra supports grid search by default, for example,  by the `--multirun` option. Could you tell me why you add Optuna's one, please?

**Comment by nzw0301** [comment]
FYI: issue on hydra repo https://github.com/facebookresearch/hydra/issues/1815

**Comment by toshihikoyanase** [comment]
> One of the motivating factors of using GridSampler is to leverage the distributed use case Optuna supports

That makes sense. Thank you for your explanation.

I briefly checked the error reported in https://github.com/facebookresearch/hydra/pull/2132 and found that `trial._suggest` got unexpected type of the value for the second argument, i.e., `list` instead of a `BaseDistribution`.

This is due to the change in `create_optuna_distribution_from_override` since it returns a list of choice when `grid=True`. I have not tried yet, but can we simply remove the changes in the function?

https://github.com/facebookresearch/hydra/blob/16235aff52aa9db3de66a34fc39c1321c76f3945/plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/_impl.py#L71-L79

**Comment by jieru-hu** [comment]
Yes I tried that as well - if we remove the wrapping, it won't even pass initilizing the gridSampler
```
 % python /Users/jieru/workspace/hydra/plugins/hydra_optuna_sweeper/example/sphere.py -m
Traceback (most recent call last):
  File "/Users/jieru/workspace/hydra/hydra/_internal/utils.py", line 213, in run_and_report
    return func()
  File "/Users/jieru/workspace/hydra/hydra/_internal/utils.py", line 461, in <lambda>
    lambda: hydra.multirun(
  File "/Users/jieru/workspace/hydra/hydra/_internal/hydra.py", line 162, in multirun
    ret = sweeper.sweep(arguments=task_overrides)
  File "/Users/jieru/workspace/hydra/plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/optuna_sweeper.py", line 50, in sweep
    return self.sweeper.sweep(arguments)
  File "/Users/jieru/workspace/hydra/plugins/hydra_optuna_sweeper/hydra_plugins/hydra_optuna_sweeper/_impl.py", line 240, in sweep
    self.sampler = self.sampler(search_space)
  File "/Users/jieru/miniconda3/envs/hydra39/lib/python3.9/site-packages/optuna/samplers/_grid.py", line 101, in __init__
    for value in param_values:
TypeError: 'DiscreteUniformDistribution' object is not iterable

```
see https://github.com/facebookresearch/hydra/commit/4b87cec8fb2ffc88f73ebdfd1de8666c969df255

**Comment by jieru-hu** [comment]
@toshihikoyanase  - any change there's any update here? Is it possible to support this from the optuna side?

**Comment by toshihikoyanase** [comment]
Thank you for your kind ping. I'll join the troubleshooting.

**Comment by jieru-hu** [comment]
thank you @toshihikoyanase - really appreciate it. I wanted to see if there's any chance this can be supported on the optuna side. If that's not possible, we can work around the API on the Hydra. I want to bring it up with the team since it seems like an inconsistency in the API.

**Comment by jieru-hu** [comment]
closing, I've decided to implement this on the Hydra sweeper side.
