### ISSUE TITLE
Using Optuna Sampler and Pruner with another tool that trains

### ISSUE THREAD

**Issue by Aboussejra** [optuna/optuna#3456]
### Environment

- Optuna version: 2.10.0
-  Python version: 3.9.6
-  Latest- OS: POP OS 21.04
- (Optional) Other libraries and their versions:

### Description

I would like to be able to use optuna with another complete tool (compiled in C++) my company uses to train deep learning algorithms, this tool reads XML files to know with which parameters it should train the program.
My question is, do you think I can use Optuna is some kind of way with a wrapper like that: 
```python
def objective(trial):
    model = Net(trial, CLASSES)
    optimizer_name = trial.suggest_categorical(
        "optimizer", ["Adam", "NAdam", "Adamax", "RMSprop", "SGD"]
    )
    lr = trial.suggest_float("lr", 1e-7, 1e-2, log=True)
    batch_size = trial.suggest_int("batch_size", 32, 128)
    optimizer = getattr(optim, optimizer_name)(model.parameters(), lr=lr)
     Write those parameters to an XML file:
     Call external code to train model with this XML file, it would write somehwere i can read the results at each epoch
     Each time epoch is finished in external code:
       Get accuracy, epoch in python
        trial.report(accuracy, epoch)
        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()
    return accuracy
```

Using those kind of things with TPE Sampler and ASHA/Hyperband Pruner would be the best.
My company thinks optuna is really good, but given our current software stack and all, we would need to delegate training to an external C++ code, what do you think about it ? Is it doable?

### Error messages, stack traces, or logs

```shell
No logs to display
```

### Steps to reproduce

No steps to reproduce, that is just a question

**Comment by himkt** [comment]
> do you think I can use Optuna is some kind of way with a wrapper like that

Yes, you can optimize an objective function running an external process like your example.

**Comment by himkt** [comment]
Let me close this issue as I believe I answered your question.

**Comment by DeLaRiva** [comment]
Hi,
is it somehow possible to convert/wrap Optuna to C++ code?
"Basically" I would only need the .create_study() and optimize() with the TPESampler so I wonder how I could let it work on C++.

Finally, I would like to run it on a µC.
