### ISSUE TITLE
Choose a trial and overwrite the info the same way in study.best_  

### ISSUE THREAD

**Issue by rm17tink** [optuna/optuna#3461]
I dont mean to open this up again... but is there a way for me to choose a trial and repurpose the info the same way i call study.best_

I ran the dataframe and prefer trial 1 instead of the best trial. Id like to replace all the info with trial 1 and save that as the best. Is it possibe so that I can then access the below code the same way? 

```

print(f"\tBest Value (auc): {study.best_value:.5f}")
print(f"\tBest Trial Number: {study.best_trial.number}")
print(f"\tNumber of features in Model: {best_booster.n_features_in_} ") 
print(f"\tBest params:")
for key, value in study.best_params.items():
    print(f"\t\t{key}: {value}")
```

_Originally posted by @rm17tink in https://github.com/optuna/optuna/issues/3446#issuecomment-1093353397_

**Comment by himkt** [comment]
@rm17tink How about the following? It looks that lightgbm

```python
trial_number = 0  # trial number if you want to use. trial number can be seen in the dataframe (`study.trials_dataframe`)

target_trial = [trial for trial in study.trials if trial.number == trial_number][0]

for key, value in target_trial.params.items():
    print(f"\t\t{key}: {value}")

for key, value in target_trial.user_attrs.items():
    print(f"\t\t{key}: {value}")
```

**Comment by himkt** [comment]
> Maybe I can just save every booster?

I'm not sure I understand your comment correctly, but I think yes. You can save a model in an objective function and save its path into trial user attribute.

After that, we can restore the model from the path to the saved model.

**Comment by nzw0301** [comment]
I believe the original question was addressed by the comments above. Let me close this issue.
