### ISSUE TITLE
Are there plans to add new samplers (e.g. TuRBO)?

### ISSUE THREAD

**Issue by Yura52** [optuna/optuna#3467]
### Motivation

Undoubtedly, Optuna offers great user experience, it is a very convenient library for hyperparameter optimization! That said, some recent work (like [this one](https://arxiv.org/abs/2104.10201)) indicates that there may be better alternatives to the default TPE sampler. While I personally do not want Optuna to become a collection of all existing optimization algorithms, I wonder if there are new stable and recognised methods that can be added to Optuna to provide better performance for users.

### Description

For example, TuRBO looks like a good candidate, since many teams (including Optuna developers) used it the competition mentioned above.

**Comment by Yura52** [comment]
Hey @hvy !

Sorry for bothering. Do you have any plans or ideas regarding this question?

**Comment by Yura52** [comment]
Hi @HideakiImamura  ! What do you think about this issue?

**Comment by HideakiImamura** [comment]
Thanks for raising an issue. Currently, we have no resource to consider and add new sampler, but it would be great to submit a PR to implement that. I will review the PR if you submit it.
