### ISSUE TITLE
`--verbose` and `--quiet` option in CLI is not working

### ISSUE THREAD

**Issue by not522** [optuna/optuna#3485]
### Expected behavior

`--verbose` and `--quiet` options in CLI should change the logging level of the Optuna's logger.

### Environment

- Optuna version: 3.0.0b1.dev
- Python version: 3.8.2
- OS: macOS-10.16-x86_64-i386-64bit
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
See steps to reproduce.
```

### Steps to reproduce

```sh
~/optuna$ optuna create-study --storage sqlite:///test.db --study-name test-study -q
[I 2022-04-22 20:36:11,192] A new study created in RDB with name: test-study
test-study
```

The INFO level logging message should be suppressed by `-q`.

**Comment by hvy** [comment]
@nyanhi is working on debugging this issue.
