### ISSUE TITLE
`TrialState.is_finished` has no document

### ISSUE THREAD

**Issue by not522** [optuna/optuna#3487]
### What is an issue?

`TrialState.is_finished` has no explanation in the document.

**Comment by HideakiImamura** [comment]
The document of `TrialState.is_finished` should be placed at [here](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.trial.TrialState.html). The code of `TrialState.is_finished` is [here](https://github.com/optuna/optuna/blob/master/optuna/trial/_state.py). It is easy enough to understand the behavior, so please add the documentation of it by reading its code.
