### ISSUE TITLE
`Edit on GitHub` links in many reference pages do not work

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#3494]
## Issue description

This issue was originally reported by @fukatani.

When I clicked the `Edit on GitHub` in some [reference page](https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.plot_pareto_front.html), I got 404 errors.

![image](https://user-images.githubusercontent.com/3255979/164953873-8b5abdbe-8bf3-4080-ba3c-4537dc11742b.png)

This is because rst files are dynamically generated in CI jobs, and they are not in the github repository. So, I think the links seems to be noise for readers.

## Expected behavior

Remove `Edit on GitHub` links from the reference pages.

## Changes

The source link can be disabled by the [html_show_sourcelink](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-html_show_sourcelink) option in `config.py`. In my environment, it removed the `Edit on GitHub` links but preserved the source links near the method names.

![image](https://user-images.githubusercontent.com/3255979/164953669-ae5ee073-4699-48d5-99c7-890dab7fd056.png)

## Alternative approach

The [`display_github` option in `html_context`](https://docs.readthedocs.io/en/stable/guides/edit-source-links-sphinx.html) is also related to this issue, but `View page source` links are shown instead of `Edit on GitHub` links. The destination of the link is rst file that contains only a list of methods or functions.  It may confuse the developers who want to edit the content of the reference, so I think we can simply remove the links.

![image](https://user-images.githubusercontent.com/3255979/164954017-9b830e14-c596-4854-b010-e7dc0e6329fe.png)

**Comment by gurmatsinghsour** [comment]
Hey, I would like to work on this, would you mind sharing with me your time to explain this issue as I'm new to this.

**Comment by gurmatsinghsour** [comment]
Hey sorry for the late response as I was busy giving my semester exams. I don't have any problems as of now since I need to understand the project and the issue then I can start working on it

**Comment by toshihikoyanase** [comment]
@cfkazu resolved this issue in #3777.
