### ISSUE TITLE
Make `optuna.samplers.nsgaii` part more informative

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3512]
### What is an issue?

We make `optuna.samplers.nsgaii` (see the screenshot below or [documentation](https://optuna.readthedocs.io/en/latest/reference/samplers/index.html)) more informative to guess what APIs are explained on the linked page.

<img width="985" alt="Screenshot 2022-04-26 at 0 59 54" src="https://user-images.githubusercontent.com/7121753/165127702-2df0774e-f77a-4235-bad0-c262ceb92393.png">

**Comment by HideakiImamura** [comment]
I think it is sufficient to add a `note` section above the `optuna.samplers.nsgaii` part like that above the following `optuna.visdualization.matplotlib` section. https://optuna.readthedocs.io/en/latest/reference/visualization/index.html
