### ISSUE TITLE
Allow OptunaSearchCV to accept callbacks

### ISSUE THREAD

**Issue by AlexisMignon** [optuna/optuna#3519]
### Motivation

Allowing `OptunaSearchCV` to accept callbacks could allow for instance to use `MLFlow` callbacks with sklearn models.

### Description

It would consist in adding a `callback` parameter to the constructor and pass its content to `study.optimize` in the `OptunaSearchCV.fit` method.

**Comment by nzw0301** [comment]
Thank you for creating the feature request and sending the pull request! I suppose that we can also add the other arguments of `study.optimize` such as `show_progress_bar`.

**Comment by AlexisMignon** [comment]
Do you suggest that I add also this option or should it be a new issue / PR ?

**Comment by nzw0301** [comment]
Either is fine. Since the PR is motivated by using `callbacks` according to the issue description, not to make the arguments between `OptunaSearchCV ` and `study.optimize` consistent, the current PR looks enough and easy to review for Optuna's team.
