### ISSUE TITLE
How much startup trials are needed for TPE Sampler

### ISSUE THREAD

**Issue by Aboussejra** [optuna/optuna#3523]
### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Description

I am asking myself how much startup trials are needed for TPE Sampler to perform well ? I am currently running experiments on this issue to see if running study with only few startup trials could work as well.

### Error messages, stack traces, or logs

```shell
Nothing needed
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by not522** [comment]
As far as I know, it depends on your task. If the optimization problem has many local minima and the initial solution highly controls the optimization, I recommend trying a large number of start-up trials, e.g., `n_startup_trials=100`.

**Comment by nzw0301** [comment]
I believe the original question was addressed by the comment above. Let me close this issue.
