### ISSUE TITLE
Why `GridSampler` requires the search space values to be among `str`, `int`, `float`, `bool` or `None`?

### ISSUE THREAD

**Issue by fxmarty** [optuna/optuna#3534]
### Environment

- Optuna version: 2.10.0
- Python version: 3.9.12
- OS: Linux-5.15.0-27-generic-x86_64-with-glibc2.35

### Description

Hello,

`GridSampler` is the only sampler to have a check so that the provided values must be either `str`, `int`, `float`, `bool` or `None`.

See the check here: https://github.com/optuna/optuna/blob/c3382c170f3804f6ab12599e9c2244dbfe0fa2e1/optuna/samplers/_grid.py#L209-L218

Called in the `__init__` of `GridSampler`: https://github.com/optuna/optuna/blob/c3382c170f3804f6ab12599e9c2244dbfe0fa2e1/optuna/samplers/_grid.py#L102-L106

Why is this check necessary? I would like to be able to provide lists as possible values but with this check it is not possible. For example this fails:

```python
search_space = {"example": [["foo"], ["foo", "bar"]]}

study = optuna.create_study(directions=["maximize"], sampler=optuna.samplers.GridSampler(search_space),)

self.study.optimize(objective, n_trials=100, timeout=600)
```

As a workaround, I could use a structure so that my lists are mapped to integers, but this is rather hacky and unelegant. If possible, I would like to find an other solution.

Thanks!

### Error messages, stack traces, or logs

```shell
ValueError: example contains a value with the type of <class 'list'>, which is not supported by `GridSampler`. Please make sure a value is `str`, `int`, `float`, `bool` or `None`.
```

### Steps to reproduce

The code is incomplete, but basically:
```python
search_space = {"example": [["foo"], ["foo", "bar"]]}

study = optuna.create_study(directions=["maximize"], sampler=optuna.samplers.GridSampler(search_space),)

self.study.optimize(objective, n_trials=100, timeout=600)
```

**Comment by nzw0301** [comment]
Thank you for asking the question. I suppose the specified typos are the same as supported types by [`CategoricalDistribution`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.distributions.CategoricalDistribution.html). I'm not sure why grid search sampler raises value error rather than showing warning message as in `CategoricalDistribution`.

> As a workaround, I could use a structure so that my lists are mapped to integers, but this is rather hacky and unelegant. If possible, I would like to find an other solution.

Anyway, this approach is actually common practice when we use unsupported types in categorical distribution.

**Comment by fxmarty** [comment]
I see. I took this approach then. Feel free to close. Thank you!

**Comment by nzw0301** [comment]
Thanks!
