### ISSUE TITLE
[RFC] Use modern random value generator

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3548]
### Motivation

Optuna uses a random value generator internally in samplers or tests. Since [numpy 1.17.0](https://numpy.org/devdocs/release/1.17.0-notes.html), which was released July 2019, `numpy.random.RandomState` has used the [legacy random value generator](https://numpy.org/doc/stable/reference/random/legacy.html). Instead, numpy provides a better [random generator](https://numpy.org/doc/stable/reference/random/generator.html).

### Description

I'm wondering if we could replace the `numpy.random.RandomState` with the new random value generator. We might be able to just replace `numpy.random.RandomState` with `numpy.random.default_rng`.

**Comment by contramundum53** [comment]
I think we can make this issue contribution-welcome.
We may need to care about the dependency on numpy 1.17.
We could simply return `numpy.random.RandomState` when there is no `numpy.random.default_rng`.

**Comment by HideakiImamura** [comment]
We have decided not to proceed this task until the minimal Optuna is broken with numpy < 1.17. This is for users in clusters, for example, who cannot easily upgrade software versions.

**Comment by contramundum53** [comment]
How about writing a condition?
I don't think we have any schedules to drop `numpy < 1.17` in the foreseeable future, and yet it's better for us to follow a good rng practice where it's available.
