### ISSUE TITLE
Cannot import name 'ParamSpec' from 'typing_extensions'

### ISSUE THREAD

**Issue by claraMarti** [optuna/optuna#3558]
I am working from Azure Databricks. I have installed Optuna's library without any problem, but when I import it, I get this error.

> `cannot import name 'ParamSpec' from 'typing_extensions' (/databricks/python/lib/python3.8/site-packages/typing_extensions.py)` 

How can I solve it?

**Comment by blazespinnaker** [comment]
I ran into the same problem when upgrading to rc 3.0 and had to upgrade the typing-extensions.  Would it be a good idea to specify a dependency version for the library?

**Comment by nzw0301** [comment]
@blazespinnaker Thank you for sharing your experience!
