### ISSUE TITLE
`constant_liar=True` does not work in multi-objective `TPESampler`

### ISSUE THREAD

**Issue by knshnb** [optuna/optuna#3565]
### What is an issue?

In multi-objective `TPESampler`, running trials are skipped even when `constant_liar=True`. I think we should at least mention this in the document and should probably give a warning.
Also, it seems that constant_liar can be easily supported in the multi-objective case by setting `inf` or `-inf` to each objective.

- [x] Add to the document
- [ ] Raise a warning if `constant_liar=True` is set for multi-objective optimization
- [ ] Support `constant_liar=True` for multi-objective optimization
https://github.com/optuna/optuna/blob/595e731cd150f60a9ca9ea89f135dc95d35ac83b/optuna/samplers/_tpe/sampler.py#L617-L618

**Comment by HideakiImamura** [comment]
We should add a document for this in this issue.

Making the `constant_liar` option available in the multi-objective optimization is a future work.

**Comment by knshnb** [comment]
To support this feature, we might need to be careful with #3676 and #3677, which are inf-related issues with multi-objective `TPESampler`.

**Comment by knshnb** [comment]
I updated the issue description. The second task is also contribution-welcome!

**Comment by not522** [comment]
This issue has been resolved by #5021. Thank you for your contributions.
