### ISSUE TITLE
Introduce `ParamSpec` to decorators in Optuna for type inference

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#3572]
### Motivation

The [`convert_positional_args` decorator](https://github.com/optuna/optuna/blob/217e5efa4e7ae4050068e5b7f3b493e5f5bcac14/optuna/_convert_positional_args.py#L12-L36) employs `typing_extensions.ParamSpec` to enable code suggestion of recent code editors.

On the other hand, we cannot see the code suggestion for experimental functions and deprecated functions, since the `@experimental` and `@deprecated` do not use `ParamSpec`.

According to the [following comment](https://github.com/optuna/optuna/pull/3270#issuecomment-1030524516) by @higucheese , `ParamSpec` is a built-in functionality of Python 3.10 and sounds reasonable to apply it to other decorators.
> I have introduced `ParamSpec` which is officially available in typing since version 3.10 (so typing_extensions is necessary now) and that helps to infer the arguments of the outer function from the arguments of the inner function.

### Description

Please apply `typing_extensions.ParamSpec` to decorators defined in Optuna.

- [x] `optuna/_experimental.py` [`@experimental`](https://github.com/optuna/optuna/blob/217e5efa4e7ae4050068e5b7f3b493e5f5bcac14/optuna/_experimental.py#L34)
- [x] `optuna/_deprecated.py` [`@deprecated`](https://github.com/optuna/optuna/blob/217e5efa4e7ae4050068e5b7f3b493e5f5bcac14/optuna/_deprecated.py#L44-L49)

Please check the `optuna/_convert_positional_args.py` to learn how to use `ParamSpec`.

https://github.com/optuna/optuna/blob/217e5efa4e7ae4050068e5b7f3b493e5f5bcac14/optuna/_convert_positional_args.py#L9-L36

**Comment by HideakiImamura** [comment]
This issue is resolved in #3575. Let me close this issue.
