### ISSUE TITLE
Make NASBench301 available in the benchmark

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3582]
### Motivation

Sub-task of https://github.com/optuna/optuna/issues/3245. We would like to use nasbench 301 benchmark.

The goal is to make NAS bench 301, which is available in NASLib, available to Optuna benchmark scripts; Optuna benchmark scripts already have NAS bench 201 available and should be able to run it in a similar fashion.

### Description

As the title

**Comment by nzw0301** [comment]
I'm investigating how to use this benchmark in the CI in this repo.

In my understanding, we only need a dataset provided by https://github.com/automl/NASLib that contains network architecture (tuple of tuples of two int values), train losses (list of float), validation accuracies (list of float), and runtime (float).

However, [the officially mentioned API](https://github.com/crwhite14/nasbench301) by naslib tries to load  `models`, which is supposed to be some model file used in the Nasbench301 research paper. Hence, we might not need to use this API.

**Comment by contramundum53** [comment]
@nzw0301 We can directly use `dataset_api` in `naslib`. That is what I did with NasBench201.

**Comment by nzw0301** [comment]
In my understanding, it requires the models because [this part](https://github.com/automl/NASLib/blob/1dd550774821799405e9a8295d4d7638e49983dc/naslib/utils/get_dataset_api.py#L55-L93), which is called via `naslib.utils.dataset_api` to load naslib301, explicitly load the model file.

**Comment by contramundum53** [comment]
I see, it seems that NASBench301 is implemented in a different way from NASBench201. It might be better not to use `naslib`.

**Comment by nzw0301** [comment]
Let me unassign myself once from this issue because Nasbench301 search space is a little bit complicated; it takes time to move forward this PR.

**Comment by HideakiImamura** [comment]
Let me remove the v3 label since this is out-of-scope of v3.
