### ISSUE TITLE
Add a `skip_if_exists` option to `Study.enqueue_trial`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#3616]
### Motivation

Currently, `Study.enqueue_trial` does not support a `skip_if_exists` option, so it is possible to unintentionally add duplicate trials with the same parameters to the `Study`. For example, in a clustered environment, where processes are often preempted, it is often the case that the parameters of a previously running trial are enqueued back into the study when the process is restarted. In such cases, it is undesirable to repeatedly insert the same parameters.

This PR suggests to add a `skip_if_exists` option to `Study.enqueue_trial`.

### Description

Please add a `skip_if_exists` option to `Study.enqueue_trial`. This option has a value of `bool`. If `Study.enqueue_trial(params, skip_if_exists=True)` and the `Study` already includes the trial with given `params`, the trial is not enqueued (skipped).

Thr `np.isclose` may be used to determine the identity of `params` and parameters of existing trials.

**Comment by xadrianzetx** [comment]
Happy to take that one.
