### ISSUE TITLE
Move `optuna.testing.integration.DeterministicPruner` to `optuna.testing.pruner`

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#3617]
### What is an issue?

The `optuna.testing.integration.DeterministicPruner` is only used in the tests of `optuna.integration`, but it can widely used in the tests of other modules. It is natural to place it in the `optuna.testing.pruner`.

**Comment by not522** [comment]
> The `optuna.testing.integration.DeterministicPruner` is only used in the tests of `optuna.integration`, but it can widely used in the tests of other modules. 

`DeterministicPruner` is already used in `tests/trial_tests/test_trial.py`.

**Comment by toshihikoyanase** [comment]
I'm curious why the sub-modules in `optuna.testing` (e.g., `optuna.testing.distribution` and `optuna.testing.sampler`) are singular while the submodules in `optuna` (e.g., `optuna.distributions` and `optuna.samplers`) are plural.

c.f., https://github.com/optuna/optuna/pull/3638#discussion_r890159623
