### ISSUE TITLE
early stopping with custom metric uses metric from previous optuna study trials 

### ISSUE THREAD

**Issue by PhillipMaire** [optuna/optuna#3625]
### Expected behavior

I expect it to early stop for each optuna trial based on only that trial 
### Issue

for each OPTUNA trial, using a custom metric. if for example early stopping is triggered in trial 1, all subsequent trials will use that metric for stopping even though the metric was not achieved in that trial. I know this is a poor explanation but see the colab note book and the following examples. 
from the nootbook 
touch_count_errors is my custom metric programed to return set numbers here to show the issue, where higher is better
I selected early stopping of 2, again to show the issue 
i set the metric to saturate at 1 for trial 2, and never go above this

Yay the following works as expected!!
    [1]	valid_0's auc: 0.955269	valid_0's touch_count_errors: 0.999
    _Training until validation scores don't improve for 2 rounds_
    **[2]	valid_0's auc: 0.954545	valid_0's touch_count_errors: 1**
    [3]	valid_0's auc: 0.961054	valid_0's touch_count_errors: 0.002
    [4]	valid_0's auc: 0.979132	valid_0's touch_count_errors: 0.003
    _Early stopping, best iteration is:_
    **[2]	valid_0's auc: 0.954545	valid_0's touch_count_errors: 1**

But this one uses the previous **valid_0's touch_count_errors: 1** to early stop even though it was not saturated here for AUC or touch_count_errors
    [1]	valid_0's auc: 0.956921	valid_0's touch_count_errors: 0.004
    [2]	valid_0's auc: 0.964566	valid_0's touch_count_errors: 0.005
    [3]	valid_0's auc: 0.977583	valid_0's touch_count_errors: 0.006
    [4]	valid_0's auc: 0.976343	valid_0's touch_count_errors: 0.007
    _Early stopping, best iteration is:_
    [2]	valid_0's auc: 0.954545	valid_0's touch_count_errors: 1

same for this one and all following
    [1]	valid_0's auc: 0.958368	valid_0's touch_count_errors: 0.008
    [2]	valid_0's auc: 0.971384	valid_0's touch_count_errors: 0.009
    [3]	valid_0's auc: 0.973967	valid_0's touch_count_errors: 0.01
    [4]	valid_0's auc: 0.980888	valid_0's touch_count_errors: 0.011
    _Early stopping, best iteration is:_
    [2]	valid_0's auc: 0.954545	valid_0's touch_count_errors: 1

 
![image](https://user-images.githubusercontent.com/19584564/171913747-8c052585-7042-4506-828a-e0db73c9fe38.png)

### Environment

google colab (and for my data using on a windows machine but issue occurs in both so troubleshooting in colab for consistency) 

- Optuna version:2.10.0
- Python version:3.7.13
- OS:Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic

### Error messages, stack traces, or logs

```shell
None, it's a bug not an error
```

### Steps to reproduce

here is a link to a fully contained example on colab 
https://colab.research.google.com/drive/1LigmaNSoK_FFi1BYTwhaDHZEBiLZskz0#scrollTo=0wP3rzPiYr0t

### Additional context (optional)
edit: I am not sure if this is the case for other metrics, it may actually have nothing to do with the custom metric and does this for all metrics, although to test this I would be harder because we would have to design our data in a certain way to test it. 

thank you all for your help!!

**Comment by nzw0301** [comment]
This is not the optuna's bug and looks duplicated issue with https://github.com/optuna/optuna/issues/3145. We need to wait for the next stable of lightgbm to fix it.

**Comment by PhillipMaire** [comment]
ok thanks for the response. so what is the current behavior does it save the same model over and over again if the best model was the first one (as in my example)?  is there a patch that someone had implemented that is working at all or is optuna and grid search just not an option with light GBM as of now? 

on a side note, I suppose my notebook could be useful for testing to ensure that the fix works with custom metrics once an official fix is implemented.

**Comment by PhillipMaire** [comment]
I updated the colab notebook [here](https://colab.research.google.com/drive/1LigmaNSoK_FFi1BYTwhaDHZEBiLZskz0#scrollTo=_zh0M35Tw7pK). I installed the light GBM package from their git master which according to one of the collaborators [should contain the fix ](https://github.com/microsoft/LightGBM/pull/4868#issuecomment-1146719140)but now I get an error with OPTUNA `TypeError: train() got an unexpected keyword argument 'fobj'` which I do not get when I import lgb from lightgbm. (see notebook, I labeled them as sections for clarity)

**Comment by nzw0301** [comment]
Thank you for sharing your investigation! In my understanding, one easy way is to use `early_stopping_rounds`, instead of `early_stopping ` callback.

**Comment by PhillipMaire** [comment]
OMG i didn't even read the full post, thank you so much for responding or I would have missed that!

**Comment by PhillipMaire** [comment]
yep that works great here is a corresponding plot to demonstrate that it works 
![image](https://user-images.githubusercontent.com/19584564/172237594-8842e1c4-5a80-4622-8d83-6e2de2364c6e.png)
