### ISSUE TITLE
Multivariate TPESampler gives the same hyperparameter when multiprocessing 

### ISSUE THREAD

**Issue by eugeborzone** [optuna/optuna#3626]
### Environment

- Optuna version: 2.10
- Python version: 3.9.7
- OS: Windows 10

### Description

The TPESsamples (multivariate=True) is giving to me the same hyperparameters in the 8 parallel process. 
Its dont happen whith other samplers. 

### Error messages, stack traces, or logs

```shell
It´s not give an error message
```

### Steps to reproduce

```python
def define_model(trial):
...
    return model, layers


def objective(trial):
    ...
    return cv_mse

sampler = optuna.samplers.TPESampler(multivariate=True)

study = optuna.load_study(study_name=study_name, storage=f"sqlite:///{study_name}.db",sampler=sampler)


if __name__ == '__main__':
    procesos = []
    for n in range(8):
        proceso = Process(target=study.optimize, args=(objective, ))
        procesos.append(proceso)
    for proceso in procesos:
        proceso.start()
        sleep(4)

    for proceso in procesos:
        proceso.join()

```

**Comment by keisuke-umezawa** [comment]
Thank you for the question!

As you ran this optimization with 8 process, at the beginning of the optimization, there are no results of trials, and the `TPESampler` sampler suggests the same hyper parameters 8 times.

For the feature to suggest different parameters even if the study has the same results of trials, we call it as `Batch Optimization`. `TPESampler` sampler naturally does not have Batch Optimization` feature, but by using tricky solution, `constant_liar option`, it can generate different parameters.

Could you try to use `constant_liar=True` for `TPESampler`?

**Comment by eugeborzone** [comment]
Keisuke-umezawa tanks for the answer. In my next experimentg `constant_liar` option. 
The experiment commented in the question was already started by a grid serch, and then i change to `TPESampler`.
In any case, thank you very much.
