### ISSUE TITLE
No input sanitization in `enqueue_trial`

### ISSUE THREAD

**Issue by xadrianzetx** [optuna/optuna#3630]
### Expected behavior

While working on #3629 I found that passing param value of different type than suggested in objective function to `enqueue_trial` causes undefined behavior, depending on type of value passed and expected distribution. So for example:

* Enqueuing `{"x": "foo"}` but using `FloatDistribution` or `IntDistribution` for `x` in objective function causes optimization to crash with cryptic tracebacks.
* Enqueuing `{"x": 1}` but using `FloatDistribution` for `x` results in silent cast to float.
* Enqueuing `{"x": 1.1}` but using `IntDistribution` for `x` results in warning message and cast to int.

I'd expect either one of following behaviors:
1. Optimization fails with nice message informing user that incorrect param values were enqueued (including expected and actual distributions). 
2. Optimization continues, but trial with incorrect params is marked as failed with warning message.

This might be a bit nit-picky, but `enqueue_trial` allows user to fix suggestions to just about anything, and in large enough codebase I'd say its fairly easy to mistakenly switch two differently typed parameters, in which case current tracebacks (if any) are a bit confusing.

### Environment

- Optuna version: 3.0.0b1.dev
- Python version: 3.8.10
- OS: Ubuntu 20.04.4 LTS
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
Traceback (most recent call last):
  File "uhoh.py", line 7, in <module>
    trial.suggest_float("x", 1, 10)  # uh-oh!
  File "/home/adrian/code/optuna/env/lib/python3.8/site-packages/optuna/trial/_trial.py", line 156, in suggest_float
    return self._suggest(name, distribution)
  File "/home/adrian/code/optuna/env/lib/python3.8/site-packages/optuna/trial/_trial.py", line 587, in _suggest
    if self._is_fixed_param(name, distribution):
  File "/home/adrian/code/optuna/env/lib/python3.8/site-packages/optuna/trial/_trial.py", line 616, in _is_fixed_param
    contained = distribution._contains(param_value_in_internal_repr)
  File "/home/adrian/code/optuna/env/lib/python3.8/site-packages/optuna/distributions.py", line 183, in _contains
    return self.low <= value <= self.high
TypeError: '<=' not supported between instances of 'float' and 'str'
```

### Steps to reproduce

```python
import optuna
study = optuna.create_study()
study.enqueue_trial({"x": "foo"})
# Some time later in objective function...
trial = study.ask()
trial.suggest_float("x", 1, 10)  # uh-oh!
```

**Comment by not522** [comment]
I think this problem occurs not only with `enqueue_trial` but also with user-defined samplers. As far as I know, there is no explicit checking for suggested parameters.

https://github.com/optuna/optuna/blob/294f6a90538c208bb07c333dcfe29323a2da219b/optuna/trial/_trial.py#L575-L602

**Comment by xadrianzetx** [comment]
There are some input checks in `FrozenTrial`, since i guess it's expected that instance of this class can be created by user (via `create_trial` API).
https://github.com/optuna/optuna/blob/294f6a90538c208bb07c333dcfe29323a2da219b/optuna/trial/_frozen.py#L294-L328

However for `enqueue_trial` those checks are bypassed since we might not know correct distribution at this point, and as you pointed out `Trial` does not double check later on.

**Comment by HideakiImamura** [comment]
I think the option 1 is good, since it is user-friendly. We should add a check about this.
