### ISSUE TITLE
Add explanation to restore sampler when calling `Study.tell`

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#3640]
## Background

Optuna has the Ask-and-Tell interface, which enables users to call `Study.ask` and `Study.tell` in different processes. 

In such use-cases, users may need additional setup before calling `Study.tell`. For instance, users need to restore the sampler used in `Study.ask` when they work on constrained optimization using `NSGAIISampler` or `BoTorchSampler`. This is because `constraints_func` is called in `Sampler.after_trial`, and `Sampler.after_trial` is called in `Study.tell`.

The [tutorial](https://optuna.readthedocs.io/en/latest/tutorial/20_recipes/009_ask_and_tell.html#sphx-glr-tutorial-20-recipes-009-ask-and-tell-py) has three examples, but they use `Study.ask` and `Study.tell` in the same processes and none of them use `constraints_func`.

## Changes

Explain that users need to restore sampler before `Study.tell` if they call `Study.ask` and `Study.tell` in different processes and they use the `constraint_func` arguments of samplers.

I'm not sure but we can add a new example to the [tutorial](https://optuna.readthedocs.io/en/latest/tutorial/20_recipes/009_ask_and_tell.html#sphx-glr-tutorial-20-recipes-009-ask-and-tell-py).

**Comment by vangarp** [comment]
I am also looking for a way of doing this. What I want to do is 
1. ask the study for a trial, get the parameter suggestions
2. use the parameter suggestions to run some trial (this trial completes later in a different process and it's value is stored in some database)
3. the next time I want to be able to "fill" the study (maybe using add_trial) with the results from the previous trial and ask for a new recommendation using study.ask

Currently I get the same value everytime if the seed used for the sampler is the same as if the sampler does not know that I have added a trial to the study using add_trial and sampler runs from the start again.

**Comment by nzw0301** [comment]
I suppose https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html might be a more appropriate place to describe restoring sampler because we need to restore `sampler` instance even though the usual `study.optimize` case. For example,

```python
import numpy as np
import pickle
import optuna


def objective(trial):
    
    x = trial.suggest_float("x", -15, 30)
    print(f"trial number {trial.number}, x: {x}")

    return x


sampler = optuna.samplers.TPESampler(
    seed=0,
)

study = optuna.create_study(
    direction="minimize",
    sampler=sampler,
    study_name="example-study",
    storage="sqlite:///example_rdb.db",
    load_if_exists=True,
)

study.optimize(objective, n_trials=1)

# Assume we exit this study and reload the study from RDB to continue optimisation.
# Hence, the following part simulates the loading the existing study and continues optimisation.

sampler = optuna.samplers.TPESampler(
    seed=0,
)

study = optuna.create_study(
    direction="minimize",
    sampler=sampler,
    study_name="example-study",
    storage="sqlite:///example_rdb.db",
    load_if_exists=True,
)

study.optimize(objective, n_trials=1)
```

### Outputs:

```
trial number 0, x: 9.696607676729613
trial number 1, x: 9.696607676729613
```

The suggested parameter are the same between the two trials because they use the exact same sampler including random state.

**Comment by nzw0301** [comment]
Should we add more explanation? I suppose #3992 mentions the shared issue with the original motivation at least; we could close this issue if the issue is enough.

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for completing https://github.com/optuna/optuna/pull/3992. In addition to that, I'd like to notify users of constrained optimization.

The following FAQ entry explains how to handle constraints, but it does not explain how to resume constrained optimization. I'd like to add a note that explains `sampler` of `optuna.load_study` should have the same `constraints_func` as the original study's sampler since storage does not persist such information, including `constraints_func` of the sampler.

It may sound obvious, but I saw some users failed to resume constrained optimization.
So, I think it is worth it for users to add this explanation 

https://optuna.readthedocs.io/en/latest/faq.html#how-can-i-optimize-a-model-with-some-constraints
