### ISSUE TITLE
Referencing same trial on different files

### ISSUE THREAD

**Issue by bernardohenz** [optuna/optuna#3644]
### Environment

- Optuna version: 2.10.0
- Python version: 3.9.7
- OS: Ubuntu Focal

### Description

Hey,

I'm trying to use optuna for hyperparameter tuning of 2 models that are later combined (ensemble) for evaluation.
Thus, I have 3 scripts:
- `train_model_A.py`
- `train_model_B.py`
- `evaluate_ensemble.py`

Both trainings run in parallel (on K8s), and I would like to `trial.suggest...` on each one of them.

How can I reference the **same trial** on all these scripts? 

I've found how to load an existing study, is there a similar method for `load_trial`? 
I've tried to use `study.get_trials()`, but this only returns `FrozenTrials`, and I cannot use the trial for suggesting new parameters.

### Error messages, stack traces, or logs

```shell
ValueError: The value of the parameter 'lr' is not found. Please set it at the construction of the FrozenTrial object.
```

### Steps to reproduce

```python
# Pre-training script
import optuna

study = optuna.create_study(
     study_name='ensemble_study',
     storage='....',
     load_if_exists=True,
)

trial = study.ask()

```

```python
# Head of training scripts
import optuna

study = optuna.create_study(
     study_name='ensemble_study',
     storage='....',
     load_if_exists=True,
)

trial = study.get_trials()[0]

lr = trial.suggest_float('lr',0.0001,0.005)

# continue training script...
```

**Comment by keisuke-umezawa** [comment]
Optuna does not expect such a use case, but let me think about ad-hoc solutons.

### Option 1
At first, run `train_model_A.py` and you can get a series of trials. You will enqueue the parameters of the series of trials.

```
# Head of training scripts
import optuna

study = optuna.create_study(
     study_name='study1',
     storage='....',
     load_if_exists=True,
)

new_study = optuna.create_study(
     study_name='study2',
     storage='....',
)

for trial in study.get_trials():
    new_study.enqueue_trial(trial.params)
```

Option2
Get params from the study, and kick training in the sub processes.

```
import optuna

study = optuna.create_study(
     study_name='ensemble_study',
     storage='....',
     load_if_exists=True,
)

trial = study.ask()

# kick sub-process to run different training
```

I have not fully understand your use case, but how about those solutions?
