### ISSUE TITLE
Rerun failed study trial

### ISSUE THREAD

**Issue by isaacncz** [optuna/optuna#3655]
### Environment

- Optuna version:2.10.0
- Python version:3.8.10
- OS:Linux-5.13.0-48-generic-x86_64-with-glibc2.29
- (Optional) Other libraries and their versions: sb3 v1.5.0

### Description

I would like to ask whether the if the state of the trial failed, will the hyperparameters be revisited in the future trial? 
![image](https://user-images.githubusercontent.com/49158607/173071676-794c3687-c2e6-4944-8865-11b225c8b052.png)
Another question will be, some of the trial failed in the middle, but still remain in running state. Why is that happening and will the hyperparameters be revisited?

### Error messages, stack traces, or logs

```shell
-
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by nzw0301** [comment]
To the first question: [`optuna.storages.RetryFailedTrialCallback`](https://optuna.readthedocs.io/en/latest/reference/generated/optuna.storages.RetryFailedTrialCallback.html) might be helpful to re-run the failed trials.

**Comment by nzw0301** [comment]
Please use https://github.com/optuna/optuna/discussions rather than asking the question in the closed issue.
