### ISSUE TITLE
cost-loss search

### ISSUE THREAD

**Issue by pseudotensor** [optuna/optuna#3656]
### Motivation

https://arxiv.org/abs/2005.01571

### Description

I notice many times optuna chooses (even at very first) a very expensive hyperparameter, like max_depth=20 if it happens to be in the range.  This strategy seems poor and only seems to be done to prime the BO with the boundaries.

It would be better to take an approach like FLAML.

Is this possible in Optuna today?

**Comment by HideakiImamura** [comment]
It would be nice for discussion if anyone send a PR.
