### ISSUE TITLE
Add best score reporting into progress bar

### ISSUE THREAD

**Issue by Rexhaif** [optuna/optuna#3661]
### Motivation

It becomes quite inconvenient to scroll through hundreds of optuna run logs in jupyter notebook to find what is the current best score(s). At the same time, progress bar always stays on  top of the output cell, and it would be easy to track current best score via progress bar description line. Also, it is already implemented in LightGBM integration: https://github.com/optuna/optuna/blob/2d6c15ee68065132070862b66de14894f35294ad/optuna/integration/_lightgbm_tuner/optimize.py#L205

### Description

Add the current best score(s) reporting to the progress bar's description or postfix string, when the progress bar is used.

### Alternatives (optional)

1. Look at the run logs, provided by optuna.
2. Save optimization runs info into some persistent storage - SQLite, Redis, RDBMS and track best scores via optuna-dashboard
3. Track scores by using MLFlow/WandB integration

**Comment by david1542** [comment]
Hi, I [created a PR](https://github.com/optuna/optuna/pull/4093) that tries to address this issue. It looks like this now:
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/9879252/197252448-3adad1e0-1f92-4fd9-bb1c-27d25b4d7d2b.png">

At the moment, it is shown by default. Maybe we can add a new flag that controls this behaviour. Can someone from the maintainers take a look? 🙏
