### ISSUE TITLE
Infinite loop in `TPESampler`

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#3670]
### Expected behavior

`TPESampler` should work with `n_startup_trials=1` when we apply it to multi-objective optimization problem.

### Environment

- Optuna version: 3.0.0rc0.dev
- Python version: 3.8.10
- OS: ubuntu 20.04 (on WSL2)
- (Optional) Other libraries and their versions: N/A

### Error messages, stack traces, or logs

```shell
The optimization stalled during the second trial of a study as follows:


[I 2022-06-14 22:05:14,674] A new study created in memory with name: no-name-b71eae7e-a922-42bf-a232-e096a8dbdeb7
[I 2022-06-14 22:05:14,675] Trial 0 finished with values: [-0.2716466405358364, -1.5373243468897773] and parameters: {'x': -0.2716466405358364, 'y': -1.5373243468897773}. 
/home/yanase/pfn/code/optuna-review/optuna/samplers/_tpe/sampler.py:585: RuntimeWarning: invalid value encountered in true_divide
  vecs = (vecs - lb) / (ub - lb)


When I hit `Ctrl + C`, the script stopped at the nondomination rank-based selection of the TPESampler.

```console
Traceback (most recent call last):
  File "/home/yanase/pfn/code/optuna-review/optuna/study/_optimize.py", line 196, in _run_trial
    value_or_values = func(trial)
...
  File "/home/yanase/pfn/code/optuna-review/optuna/samplers/_tpe/sampler.py", line 447, in sample_independent
    indices_below, indices_above = _split_observation_pairs(scores, self._gamma(n), violations)
  File "/home/yanase/pfn/code/optuna-review/optuna/samplers/_tpe/sampler.py", line 778, in _split_observation_pairs
    length = indices[nondomination_ranks == i].shape[0]
```

The corresponding code is shown below:
https://github.com/optuna/optuna/blob/d3c53e053a18341405cdfc9587d4525fdce7494d/optuna/samplers/_tpe/sampler.py#L774-L781

When the study has only a single trial, the default gamma function returns `1`, and the `n_below=1`. So the condition of the while loop at L777 is always `True`. So, the optimization process was trapped in the while loop.

On the other hand, the single objective TPE can select `below` even if we set `n_startup_trials=1`. I'm not sure, but we can fix the multi-objective logic by referring to the single objective one.

### Steps to reproduce

1. Execute the following python script.

```python
import optuna

def objective(trial):
    x = trial.suggest_float("x", -10, 10)
    y = trial.suggest_float("y", -10, 10)
    return x, y

study = optuna.create_study(
    directions=["maximize", "maximize"],
    sampler=optuna.samplers.TPESampler(n_startup_trials=1),
)
study.optimize(objective, n_trials=10)
for trial in study.best_trials:
    print(trial.values)
```

**Comment by not522** [comment]
I found this issue also occurs with `n_startup_trials=0`.

**Comment by g-votte** [comment]
@29Takuya is working on this issue

**Comment by g-votte** [comment]
@29Takuya is no longer working on this issue due to lack of time. So, this issue is still open.

Contributions are welcomed!

**Comment by gasin** [comment]
As described in https://github.com/optuna/optuna/issues/3670#issue-1270798465, the `while` block can loop infinitely if `n_below == len(lvals)`.

I don't know neither Nondomination rank-based selection nor HSSP-based selection, but it seems simply rewriting
https://github.com/optuna/optuna/blob/62b6aaede2fcb23cd640cfbf0462b2c38b3df479/optuna/samplers/_tpe/sampler.py#L751
to
```
while last_idx < n_below and last_idx + sum(nondomination_ranks == i) < n_below:
```
resolves the problem.
If `last_idx == n_below`, the `while` loop should not continue because there are already enough elements in `indices_below`.
