### ISSUE TITLE
Allow passing-in the list of Trials for the contour plot

### ISSUE THREAD

**Issue by stestagg** [optuna/optuna#3688]
### Motivation

I have a study with ~1,200 trials and 10 parameters, and am trying to view the results as a contour plot.  I do like seeing all the parameters in one matrix.

Unfortunately, the plotly generated HTML is ~70mb large and vs code and browsers really hate opening it.

### Description

It would be lovely to be able to pass in the list of trials to use for the scatter overlay, allowing users to pass-in best_trials, or some other subset list.

### Alternatives (optional)

Alternately, an option to disable the scatter overlays entirely would be nice.

**Comment by nzw0301** [comment]
Hi, one workaround is to use [`Study.add_trials`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.add_trials): 

1. extract a sub-set of trials from the original study that contains many completed trials.
2. Add the extracted trials by calling `add_trials` to a new study as in the example code of [`Study.add_trials`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.add_trials)
3. Call contour plot with the new study.

**Comment by nzw0301** [comment]
I believe that my previous comment was a simplest solution, let me close this issue.
