### ISSUE TITLE
Contour plot color scale different from other visualizations

### ISSUE THREAD

**Issue by connorbrinton** [optuna/optuna#3692]
### Expected behavior

Optuna's [parallel coordinate](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_parallel_coordinate.html), [slice](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_slice.html) and [pareto front visualizations](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_pareto_front.html) all use Plotly's `plotly.colors.sequential.Blues` color scale, which looks like this:
![Screen Shot 2022-06-17 at 11 44 33 AM](https://user-images.githubusercontent.com/1848731/174332200-f06d70b2-2db5-4545-9d64-2ee3b59ac6ee.png)

Optuna's [contour plot visualization](https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_contour.html) attempts to use this same color scale in the code, but the actual produced result does not seem to use the same color scale:
![Screen Shot 2022-06-17 at 11 46 08 AM](https://user-images.githubusercontent.com/1848731/174332432-639b43aa-c3ad-4bb9-b42d-bc810a5e31cd.png)

The rendered color scale is reversed compared to the standard color scale, and has a much more saturated blue tone. This makes it a bit difficult to understand the contour plot, since the meaning of the colors is the opposite as in the parallel coordinate plot.

### Environment

- Optuna version: 2.10.1
- Python version: 3.8.12
- OS: macOS 12.4
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
N/A
```

### Steps to reproduce

I was able to reproduce the issue using the code snippets in Optuna's documentation here:
https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_contour.html

I've also reproduced this using some other code that I haven't cleaned up enough to share here. My code uses around 7 parameters, and still results in the same problem, so [both branches of this `if/else` block seem to have the same issue](https://github.com/optuna/optuna/blob/946437a099db6fcad30ba738a82030c3b3d685e7/optuna/visualization/_contour.py#L151-L218)

### Additional context (optional)

Currently Optuna seems to [correctly set the color scale on individual contour plots](https://github.com/optuna/optuna/blob/946437a099db6fcad30ba738a82030c3b3d685e7/optuna/visualization/_contour.py#L285-L296), then [attempts to use the color scale of the first rendered contour plot for the entire figure](https://github.com/optuna/optuna/blob/946437a099db6fcad30ba738a82030c3b3d685e7/optuna/visualization/_contour.py#L194-L196). [This Plotly issue](https://github.com/plotly/plotly.py/issues/1858) seems to indicate that it might be possible to set the color scale layout/figure-wide [using `layout.coloraxis`](https://github.com/plotly/plotly.py/issues/1858#issuecomment-549050530) or [`fig.update_coloraxes(...)`](https://github.com/plotly/plotly.py/issues/1858#issuecomment-888626427). I'm sure there's a reason Optuna does things the way it does currently though, so there's probably an unusual interaction with Plotly that I'm not aware of 😅

By the way, this is actually my first time using Optuna and it's been a fantastic experience! Thanks for maintaining it! 😄

**Comment by nzw0301** [comment]
Hi, thank you for creating the detailed issue. Fortunately, this bug has been fixed in the master branch by https://github.com/optuna/optuna/pull/3376. We can confirm that on the documentation with the latest version: https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.plot_contour.html.

**Comment by connorbrinton** [comment]
Ah, perfect, thank you! 😄 🎉 Sorry for the noise! 😅
