### ISSUE TITLE
Type-Checking for the objective function

### ISSUE THREAD

**Issue by valentindoering** [optuna/optuna#3699]
### Motivation

<img width="889" alt="Screenshot 2022-06-20 at 15 52 58" src="https://user-images.githubusercontent.com/54007786/174617322-a3d59f44-3020-4af8-a35e-f63abcd81404.png">
This is the error, if you accidentally return a string in the  provided objective function. A type assertion would have saved me 2h hours of debugging.

(number of values - 18 - was the length of the string, the number was very confusing)

### Description

please add type, assertions, nice error descriptions to the optuna API.

**Comment by nzw0301** [comment]
@valentindoering If you have any suggestions to improve the logging message (#3868) or another approach, please let us know!
