### ISSUE TITLE
create a study with history

### ISSUE THREAD

**Issue by sjiang2018** [optuna/optuna#3713]
### Don't use GitHub Issues to ask support questions.

Is there a way to create a study with bunch of tried (parameter, value) points?

**Comment by nzw0301** [comment]
Please do not use github issue for asking the question by following the issue template.
Yes, I suppose either `enqueue_trial` or `add_trials` on https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study is what you want.
