### ISSUE TITLE
Consider other performance metrics than the pareto front plot for multi-objective benchmark

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#3716]
### Motivation

Recently, we have introduced the multi-objective benchmark suite in Optuna. The current performance metric is only the pareto font plot. It is difficult to judge the performance from the picture. We would like to know other quantitative performance metrics.

The current pareto front plot looks like this.
![zdt3-tpesampler-e27ba2cf7d6e48fd5a5e66950810cccd25aa56a7b573838262bd4d41e56db831](https://user-images.githubusercontent.com/38826298/175458742-9dec0c2c-880a-43a2-ae38-55bf20f20c89.png)

### Description

The example of other performance metrics are as follows. See the [survey paper](http://www.optimization-online.org/DB_FILE/2018/10/6887.pdf) for more details.
- The number of trials v.s. the achieved best hypervolume.
- The number of trials v.s. the achieved best delta index.
- The number of trials v.s. the achieved best number of points on the pareto front.

These are examples, so we may adopt other metrics. We have the following requirements for our performance metrics.
- Each metric should be the function whose input is the sequence of trials and output is one dimensional float value.
- Each metric should be plotted in a similar format to the [optimization history](https://optuna.readthedocs.io/en/latest/reference/visualization/generated/optuna.visualization.plot_optimization_history.html#optuna.visualization.plot_optimization_history).

**Comment by not522** [comment]
Ref: #4748 and related PRs introduced `plot_hypervolume_history `.
