### ISSUE TITLE
Seemingly unnecessary assert in `_calc_crowding_distance`

### ISSUE THREAD

**Issue by knshnb** [optuna/optuna#3723]
### What is an issue?

There are several assertations that seem to be unnecessary from their types (`FrozenTrial.values` is `Optional[List[float]]`) in `NSGAIISampler`. 

https://github.com/optuna/optuna/blob/7f40f9b458ca8946cc7458c8224fdbbbf36e4097/optuna/samplers/nsgaii/_sampler.py#L419-L420
https://github.com/optuna/optuna/blob/7f40f9b458ca8946cc7458c8224fdbbbf36e4097/optuna/samplers/nsgaii/_sampler.py#L432-L433

**Comment by nzw0301** [comment]
Let me confirm the condition to resolve this issue. To resolve this issue, we remove the `assert` lines, right?

**Comment by nzw0301** [comment]
Thank you for your reply! Indeed, these `assert`'s were introcued by [the PR](https://github.com/optuna/optuna/pull/1163/files#diff-14f2865f988b384b170ba36d1acb204b36f4b1c4ba470526f5bd22ed82f34a15R262-R263) of the implementing nsga2 sampler, I'm also not sure that...

**Comment by knshnb** [comment]
Let me close this issue because it is implicitly resolved by https://github.com/optuna/optuna/pull/3743.
