### ISSUE TITLE
Raise `ValueError` on `nan` values in constraints

### ISSUE THREAD

**Issue by contramundum53** [optuna/optuna#3746]
### Expected behavior

We should raise `ValueError` in samplers whenever `nan` is found in constraints.
We could check for `nan` in `after_trial` function.

* [x] NSGA-II #3740 
* [ ] TPE
* [ ] botorch

**Comment by c-bata** [comment]
@contramundum53 Do you think we can add the `contribution-welcome` label? If other contributors can work on this issue, could you please add the label?

**Comment by contramundum53** [comment]
Actually, if #3740 is merged all of the above will be solved, so I don't think we need `contribution-welcome`.
