### ISSUE TITLE
Add line to Pareto front for multi-objective optimisation

### ISSUE THREAD

**Issue by JAEarly** [optuna/optuna#3747]
### Motivation

Currently, for the Pareto plots, the dominating points are not connected, only shown in another colour. Adding a line connecting the dominating points would make it clearer which points are on the front and which are not. I find it especially hard to distinguish between dominating and non-dominating points for the extreme lights and darks of the marker colour gradients. 

### Description

This would be a relatively minor change to add a line connecting the points on the Pareto front.

I had a quick look at making these changes locally. Below are examples in 2D and 3D. I'm happy to open a PR if this is accepted as being a good idea.

![image](https://user-images.githubusercontent.com/7620667/176888141-2ed1e2c2-ad36-45ac-86d7-ae367c7855f8.png)

![image](https://user-images.githubusercontent.com/7620667/176888151-0cf13a99-bc35-4a25-9be3-a1ce4642ec1d.png)

**Comment by nzw0301** [comment]
Thank you for proposing the feature and sharing the expected results! Personally, the proposed feature looks useful.

**Comment by JAEarly** [comment]
I've created a PR: #3749

**Comment by y0z** [comment]
Hi. Thank you for your useful proposal.
I leave a brief comment that may be helpful.
This is not mandatory but can be our future work.

In this case, I think that showing [an attainment surface](https://eden.dei.uc.pt/~cmfonsec/fonseca-ppsn1996-reprint.pdf) (i.e., the connection of the front of all dominated areas) is better than simple linear interpolation.
The former is a more popular way in the community and it never contains (imaginary) points that are not dominated by the incumbent nondominated objective vectors.

[2d example](https://www.researchgate.net/figure/Attainment-curve-and-hypervolume-in-a-bi-objective-space-with-both-objectives-being_fig4_271936836)
![Attainment-curve-and-hypervolume-in-a-bi-objective-space-with-both-objectives-being](https://user-images.githubusercontent.com/30489874/176998063-c45d8bf2-7b93-4f0c-a0e8-b7974d7a150e.png)
and [3d examples](https://www.cs.bham.ac.uk/~jdk/plot_attainments/).

The concept of the attainment surface can also be extended to multiple runs to assess an optimization algorithm performance (e.g., https://mlopez-ibanez.github.io/eaf/) though I'm not familiar with the implementation details of 3d-case and multiple runs.
