### ISSUE TITLE
Optuna doesn't work with Keras on Google Colab 

### ISSUE THREAD

**Issue by danielemingolla** [optuna/optuna#3751]
### Expected behavior

Hello, although I seem to have written the objective function correctly, the moment I run Optuna to perform the various tests, the program returns a message warning me that a new study has been created. After that the execution continues infinitely.
I do not understand whether this is a bug or I am doing something wrong.
Thank you very much.

### Environment

- Optuna version:2.10.1
- Python version:3.7.13
- OS:Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
- Others library: Keras 2.8.0

### Error messages, stack traces, or logs

```shell
[I 2022-07-02 12:50:06,728] A new study created in memory with name: no-name-34ce2095-cec7-4db5-9798-501aafe451c1
```

### Steps to reproduce

```python
def objective(trial, n_steps_in = n_steps_in, n_features = n_features, n_steps_out = n_steps_out,
              X_train = X_train, y_train = y_train, X_test = X_test, y_test = y_test):

    lr = trial.suggest_float("lr", 1e-4, 1e-1, log=True)
    optz = keras.optimizers.Adam(lr=lr)

    first_units = trial.suggest_int("units", 5, 10, step=2)
    model = Sequential()
    model.add(LSTM(units = first_units, activation='tanh', input_shape=(n_steps_in, n_features)))

    rate = trial.suggest_float("rate", 1e-2, 0.2, log=True)
    model.add(Dropout(rate = rate))
    model.add(RepeatVector(n_steps_out))

    second_units = trial.suggest_int("units", 5, 10, step=2)
    model.add(LSTM(units = second_units, activation='tanh', return_sequences=True))

    activation = trial.suggest_categorical("activation", ["relu", "tanh"])
    model.add(Dense(n_features, activation=activation))

    model.compile(optimizer=optz, loss='mae', metrics='mae')
    model.fit(X_train, y_train, validation_split=0.33, batch_size = 32, epochs=1000, verbose=0)

    mae = model.evaluate(X_test, y_test)[1]

    return mae
```

Then execute:

```python
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=100, timeout = 180, n_jobs = -1, show_progress_bar=1)
```

### Additional context (optional)

I'm currently using Google Colab

**Comment by himkt** [comment]
`create_study` always creates a new study. If you want to simply resume the study,
invoke `study.optimize` without re-creating a new study.

```python
study = optuna.create_study(direction="minimize")

study.optimize(objective, n_trials=100, timeout = 180, n_jobs = -1, show_progress_bar=1)

# something....

# resume
study.optimize(objective, n_trials=100, timeout = 180, n_jobs = -1, show_progress_bar=1)
```

If you want to resume the study after terminating the colab kernel, please persistent it using `RDBStorage` or `RedisStorage`. You can see the tutorial for that (https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html#sphx-glr-tutorial-20-recipes-001-rdb-py).
