### ISSUE TITLE
optuna.visualization.plot_intermediate_values(study) returns an empty plot (with no data)

### ISSUE THREAD

**Issue by AraceliAL** [optuna/optuna#3759]
### Don't use GitHub Issues to ask support questions.

Good afternoon!
I just wanted to ask if anyone knows how could I have an `intermediate_values` plot with no data (see the attached figure)

I have no problems with the other plots such as the `plot_optimization_history`
![Captura de pantalla 2022-07-06 a les 13 38 48](https://user-images.githubusercontent.com/11374937/177542201-894c4686-91db-4a04-8a39-db73241a2908.png)

Thanks a lot and sorry for the inconvenience!

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by nzw0301** [comment]
Thanks. `plot_intermediate_values` shows a trial's intermediate values that are stored by calling [`trial.report`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.report) method. So the current trials don't have intermediate values, the plot generates an empty plot.
