### ISSUE TITLE
Resolve deprecated warnings of LightGBM in integration tests

### ISSUE THREAD

**Issue by takuya29** [optuna/optuna#3771]
### Motivation

As mentioned in https://github.com/optuna/optuna/issues/3013 and https://github.com/optuna/optuna-examples/issues/62, some of LightGBM arguments are deprecated since v3.3.0. I found several warnings still remains in integration tests. I think it would be nice to resolve them.

### Description

According to the CI results of the latest `master` branch (https://github.com/optuna/optuna/commit/60d04b2408e6fa2d0192f28c867aea4276ee1add), we have the following two types of deprecated warnings.

#### Use of `verbose_eval` argument
```
tests/integration_tests/test_lightgbm.py: 19 warnings
  'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
```
Example:
https://github.com/optuna/optuna/blob/60d04b2408e6fa2d0192f28c867aea4276ee1add/tests/integration_tests/test_lightgbm.py#L174-L192

#### Use of `early_stopping_rounds` argument
```
tests/integration_tests/lightgbm_tuner_tests/test_optimize.py::TestLightGBMTuner::test_tune_num_leaves_negative_max_depth
tests/integration_tests/lightgbm_tuner_tests/test_optimize.py::TestLightGBMTuner::test_tune_best_score_reproducibility
tests/integration_tests/lightgbm_tuner_tests/test_optimize.py::TestLightGBMTunerCV::test_tune_best_score_reproducibility
  'early_stopping_rounds' argument is deprecated and will be removed in a future release of LightGBM. Pass 'early_stopping()' callback via 'callbacks' argument instead.
```

Example:
https://github.com/optuna/optuna/blob/60d04b2408e6fa2d0192f28c867aea4276ee1add/tests/integration_tests/lightgbm_tuner_tests/test_optimize.py#L300-L308

### Alternatives (optional)

As warning messages say, we need to replace `verbose_eval` and `early_stopping_rounds` with callbacks.
cf.) https://github.com/optuna/optuna-examples/pull/64

**Comment by 29Takuya** [comment]
FYI: (Thank you @nzw0301!) 

> In the current latest stable of lightgbm, the `early_stopping_rounds` argument and `early_stopping` callback are not the same functionality unintendedly. Specifically, the latter one has a bug, which has been fixed by https://github.com/microsoft/LightGBM/pull/4868. Indeed, the same failed test case for reproducibility has been observed in 
 https://github.com/optuna/optuna/pull/3191 too.
> 
> I think we need to wait for the next release of lightgbm that includes the patch to fix the `early_stopping` callback. In addition, we need to update Optuna's code too according to https://github.com/optuna/optuna/issues/3646.

_Originally posted by @nzw0301 in https://github.com/optuna/optuna/issues/3772#issuecomment-1178795722_

**Comment by 29Takuya** [comment]
I closed #3772 since it was almost identical to #3191.

**Comment by pavlexander** [comment]
I set the

```py
    gbm = lgb.train(
        params,
        train_ds,
        valid_sets=test_ds,
        callbacks=[log_evaluation(2)]
    )
```

but get the warning anyways

> UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "

**Comment by Alnusjaponica** [comment]
It seems the the recommended way to use early stopping is also discussed at   https://github.com/microsoft/LightGBM/issues/5196.
