### ISSUE TITLE
Provide call back to print trial params when objective function returned nan

### ISSUE THREAD

**Issue by eromoe** [optuna/optuna#3779]
### Motivation

We may want to know why objective function returned nan  with what params .

### Description

While runing a study , I would got several 
```
[W 2022-07-11 14:25:17,841] Trial 2 failed, because the objective function returned nan.
```
This is confused .  I think optuna should give the detail infomation or provide a way to .

**Comment by nzw0301** [comment]
To show the warming message, optuna can only use returned value. However, returning `nan` value as an objective value depends on the definition of `objective` function that users define. For example, some machine learning model has `nan` weights or users explicitly returns nan as an exceptional case on their objective functions. So it sounds difficult to give details information, I suppose.

**Comment by nzw0301** [comment]
Sorry, your suggestion was to print params, not giving the reason. In that case, it sounds useful, indeed.

**Comment by nzw0301** [comment]
Since core dev members are busy preparing to release the forthcoming optuna 3.0 for a while, could you create a prototype PR? I think we do not need to implement a callback. Like a complete trial, we might show suggested parameters.

**Comment by nzw0301** [comment]
hi @eromoe 
Since core dev members are busy preparing to release the forthcoming optuna 3.0 for a while, could you create a prototype PR? I think we do not need to implement a callback. Like a complete trial, we might show suggested parameters.

**Comment by nzw0301** [comment]
Let me close this issue since #3857 has resolved this issue.
