### ISSUE TITLE
Same result in parallel nodes

### ISSUE THREAD

**Issue by ooghry** [optuna/optuna#3790]
### Expected behavior

I'm using optuna with XGBoost on two different Google Colab that connect to the same MySql server, and I expect every node to calculate different trail steps. But they show the same result. I mean, I'm using `early_stopping_rounds=50`, two nodes show the same result for the 50 calculations.

### Environment

- Optuna version: 2.10.1
- Python version: 3.7
- OS: Google Colab
- (Optional) Other libraries and their versions: XGBoost: 1.6.1

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by ooghry** [comment]
@nzw0301 Could you please check these two notebooks.
[notebook1](https://colab.research.google.com/drive/1rkWtDyjTo9X35eeCXIxAXJWPsVQ3IXgY?usp=sharing#scrollTo=A2kPAjkwb5Pm)   [notebook2](https://colab.research.google.com/drive/15AoD7GXVJli6IGXymV9fUWIioGcqtwnN)

**Comment by nzw0301** [comment]
Thanks. This is not the bug. The reason for this behaviour is to fix the random seed of TPE sampler. I think trial 6 on notebook 2 had been suggested before notebook 1's trial 3 was completed. To avoid this, I'd suggest using a different random seed among processes or not fixing the random seed. As mentioned in a [FAQ section](https://optuna.readthedocs.io/en/stable/faq.html#how-can-i-obtain-reproducible-optimization-results), it's not easy to guarantee reproducibility with distributed optimisation setting.
