### ISSUE TITLE
Flag to re-init wandb when a new trial is started

### ISSUE THREAD

**Issue by vballoli** [optuna/optuna#3817]
### Motivation

In the following code, `study.optimize(objective, n_trials=10, callback=[wandbc])`, the callback is not "reset" in some sense, in this case wandb is not re-initialized to track the new trial. Can a flag be added to `reset_on_new_trial` to the wandb callback.  Happy to work on it if approved.

### Description

Either Wandb callback can be reset or the `optimize` method can have a boolean attribute when True, resets the callback.

**Comment by xadrianzetx** [comment]
Which Optuna version are you using? `3.0.0b1` [introduced `as_multirun` argument](https://optuna.readthedocs.io/en/v3.0.0-b1/reference/generated/optuna.integration.WeightsAndBiasesCallback.html), which creates new w&b run for each trial.

**Comment by vballoli** [comment]
I'm using an older version, somehow missed these docs. Thanks a lot @xadrianzetx , closing this now.
