### ISSUE TITLE
Difference between `trial.number` and `trial._trial_id`

### ISSUE THREAD

**Issue by FabianSchuetze** [optuna/optuna#3824]
### Don't use GitHub Issues to ask support questions.

Thanks for the wonderful work! 

What is the difference between `trial._trial_id` and `trial._trial_id` and which one is used to fill the `trial_id` field in the database logs?

**Comment by nzw0301** [comment]
Could you use https://github.com/optuna/optuna/discussions instead of issue to ask the question?
