### ISSUE TITLE
Colorbar in coordinate plot for multi objectives

### ISSUE THREAD

**Issue by DeLaRiva** [optuna/optuna#3829]
### Expected behavior

When e.g. using two variables from which one has to be maximized and the other one to be minimized I'd expect that this is reflected by the colorbar (in the parallel coordinate plot).

### Environment

- Optuna version: 
- Python version: Python 3.9.7
- OS: Windows10
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
These are the code lines. The dose has to be maximized and the filament to be minimized:

       sampler = optuna.integration.BoTorchSampler(
                                                    n_startup_trials = 15
                                                    )

        study = optuna.create_study(
                                     directions = ["maximize", "minimize"]
                                    , sampler = sampler
                                    )
```

### Steps to reproduce

![newplot (5)](https://user-images.githubusercontent.com/29283287/181705711-7f5791ac-8054-4b09-a792-d352e8707c7d.png)
![newplot (4)](https://user-images.githubusercontent.com/29283287/181705735-23a78c56-30b4-45d0-9c92-4f323fc86837.png)

### Additional context (optional)

As you can see, I'd expect that the colors for the traces for the higher Doses dominate over the lower ones.
For the filament it looks nice and correctly as one would like to see the traces with the lowest filament values.

**Comment by nzw0301** [comment]
This is not the bug https://github.com/optuna/optuna/issues/3433

**Comment by DeLaRiva** [comment]
> This is not the bug #3433

Sorry, I'm not so familiar with github (structures). What do you mean by it is not this particular bug?
As far as I can see in the thread you are relating to, this issue/bug/request is still open?

Did you close this one here because it is already addressed?

**Comment by DeLaRiva** [comment]
> Technically, we cannot decide the colourmap when the `target` argument is not `None`. So the reported behaviour is not a bug, which is described in #3422. Concretely,
> 
> > "The colormap is reversed when the target argument is not `None` or the objective function of the study is a minimization problem."
> 
> This was why I closed this issue.

Ok, thanks. May I further ask? 
Shouldn't it be, sorry, no offense, be simple when checking the array of the directions and allocating reverse/inverse colorbars accordingly?
More precise, e.g. in my case the directions are ["maximize", "minimize"] so this array could be used with arg[0] for regular colorbar and arg[1] for an inverse colorbar? 
But there is probably a reason why this rather simple workaround has not been used, yet.

Is there an issue with plotly?

**Comment by nzw0301** [comment]
Well, as we can see the implementation, the `target` cannot interact with other `study` attributes, such as `directions`; we cannot decide whether or not to reverse the colourmap when the target is not `None`.

If you are unhappy with the default colourmap, you can change the colourmap for both backends since these plot methods return editable figure-ish objects.

**Comment by nzw0301** [comment]
Example:

```python
import optuna

def objective(trial):
    x = trial.suggest_uniform('x', -100, 100)
    y = trial.suggest_categorical('y', [-1, 0, 1])
    return x ** 2 + y, y

study = optuna.create_study(directions=["maximize", "minimize"])
study.optimize(objective, n_trials=20)

fig = optuna.visualization.plot_parallel_coordinate(study, target=lambda t: t.values[0])

# flip the colourbar
fig.data[0].line.reversescale = not fig.data[0].line.reversescale
fig
```

**Comment by DeLaRiva** [comment]
Thank you!
