### ISSUE TITLE
hyperparameter for the Random method

### ISSUE THREAD

**Issue by manza-ari** [optuna/optuna#3856]
### What is an issue?

Hi, 
I want to find the optimal hyperparameter for the Random method(Image-Classification) for the image dataset(CIFAR10, CIFAR100, ImageNet). The issue is when I train my model with OPTUNA the accuracy for CIFAR100 show only 50% though without OPTUNA accuracy is higher. I wonder if I am reading the graph incorrectly or if my code has some issue. I have trained this model for so many days for 500 OPTUNA-trials 
![FailedOPTUNASliceRandom](https://user-images.githubusercontent.com/33715985/183243425-22f6f217-6585-4c35-88f0-e23d50e173bf.png)

**Comment by nzw0301** [comment]
Could you kindly transfer this issue to https://github.com/optuna/optuna/discussions? Optuna repo does not use github issue for a question as in https://github.com/optuna/optuna#communication. Thank you for your understanding.
