### ISSUE TITLE
Dynamic parameter range changes break visualizations

### ISSUE THREAD

**Issue by leo-hstone** [optuna/optuna#3889]
### Expected behavior

I use optuna to optimize filter time constants `s` for a data preprocessing pipeline.
```python
s0 = trial.suggest_int("s0", 1, 40000)
s1 = trial.suggest_int("s1", s0, 40000)
s2 = trial.suggest_int("s2", s1, 40000)
```
I know, that the optimal parameters for my sample dataset are somehow distributed like this: `[600, 7000, 20000]`. The order of the values does not matter (`[600, 7000, 20000]` produces the same score as `[7000, 600, 20000]`). Therefore I limited the search space for s1 and s2. 

This does break the visualizations e.g. `plot_param_importance` shows only s0. The optuna dashboard shows a single dropdown item for every trial in the slice plot parameters. 

I am also wondering how the optimizer handles the dynamic distribution changes? Is it a good idea to limit the search space like this? 

### Environment

- Optuna version: 2.10.1
- Python version: 3.8.10
- OS: Linux-5.4.0-122-generic-x86_64-with-glibc2.29

### Error messages, stack traces, or logs

![image](https://user-images.githubusercontent.com/62036826/184504426-76f36dfe-3e94-4325-b6b0-bcb8634ff0c3.png)

### Steps to reproduce

1. Copy above code snippet.
2. Run simple optimization on dummy function.
3. Plot visualizatins / open dashboard.

**Comment by nzw0301** [comment]
I think this issue is duplicated with https://github.com/optuna/optuna/issues/1856#issuecomment-703935388, let me close this issue.
