### ISSUE TITLE
Failing assertion left in 'unreachable line' breaks HyperbandPruner

### ISSUE THREAD

**Issue by mirekphd** [optuna/optuna#3891]
### Expected behavior

Handle the error gracefully. For instance, remove the assertion and instead let `_get_bracket_id` return zero (most frequently returned value of `bracket_id`). 

Alternatively, introduce a debug flag to make assertions conditional and avoid breaking production scripts. Another idea: use error logging instead of assertions.

### Environment

- Optuna version: 2.10.1
- Python version: 3.8.13
- OS: Linux-3.10.0-957.27.2.el7.x86_64-x86_64-with-glibc2.10

### Error messages, stack traces, or logs

```shell
[W 2022-08-14 19:20:29,481] Trial 119 failed because of the following error: AssertionError('This line should be unreachable.')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/optuna/study/_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)
  File "<readacted>.py", line 964, in __call__
    cv_results_dict = custom_cv_fun(
  File "<readacted>.py", line 261, in custom_cv_fun
    model.fit(X_train,
  File "/opt/conda/lib/python3.8/site-packages/lightgbm/sklearn.py", line 818, in fit
    super().fit(X, y, sample_weight=sample_weight, init_score=init_score,
  File "/opt/conda/lib/python3.8/site-packages/lightgbm/sklearn.py", line 683, in fit
    self._Booster = train(params, train_set,
  File "/opt/conda/lib/python3.8/site-packages/lightgbm/engine.py", line 259, in train
    cb(callback.CallbackEnv(model=booster,
  File "/opt/conda/lib/python3.8/site-packages/optuna/integration/lightgbm.py", line 110, in __call__
    if self._trial.should_prune():
  File "/opt/conda/lib/python3.8/site-packages/optuna/trial/_trial.py", line 629, in should_prune
    return self.study.pruner.prune(self.study, trial)
  File "/opt/conda/lib/python3.8/site-packages/optuna/pruners/_hyperband.py", line 177, in prune
    return self._pruners[bracket_id].prune(bracket_study, trial)
  File "/opt/conda/lib/python3.8/site-packages/optuna/pruners/_successive_halving.py", line 192, in prune
    trials = study.get_trials(deepcopy=False)
  File "/opt/conda/lib/python3.8/site-packages/optuna/pruners/_hyperband.py", line 307, in get_trials
    return [t for t in trials if pruner._get_bracket_id(self, t) == self._bracket_id]
  File "/opt/conda/lib/python3.8/site-packages/optuna/pruners/_hyperband.py", line 307, in <listcomp>
    return [t for t in trials if pruner._get_bracket_id(self, t) == self._bracket_id]
  File "/opt/conda/lib/python3.8/site-packages/optuna/pruners/_hyperband.py", line 260, in _get_bracket_id
    assert False, "This line should be unreachable."
AssertionError: This line should be unreachable.
Traceback (most recent call last):
  File "<readacted>.py", line 1706, in <module>
    study.optimize(func=objective_func,
  File "/opt/conda/lib/python3.8/site-packages/optuna/study/study.py", line 400, in optimize
    _optimize(
  File "/opt/conda/lib/python3.8/site-packages/optuna/study/_optimize.py", line 106, in _optimize
    f.result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.8/site-packages/optuna/study/_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "/opt/conda/lib/python3.8/site-packages/optuna/study/_optimize.py", line 240, in _run_trial
    study.tell(trial, values=values, state=state)
  File "/opt/conda/lib/python3.8/site-packages/optuna/study/study.py", line 656, in tell
    study = pruners._filter_study(self, frozen_trial)
  File "/opt/conda/lib/python3.8/site-packages/optuna/pruners/__init__.py", line 34, in _filter_study
    return pruner._create_bracket_study(study, pruner._get_bracket_id(study, trial))
  File "/opt/conda/lib/python3.8/site-packages/optuna/pruners/_hyperband.py", line 260, in _get_bracket_id
    assert False, "This line should be unreachable."
AssertionError: This line should be unreachable.
```

### Steps to reproduce

While this bug is frequent (and persistent - once happens, it repeats on many subsequent calls to `_get_bracket_id`) and has been present for at least a year, it is not deterministic (does not occur in every study) and thus may be hard to reproduce by Optuna developers.

Simulating it is certainly possible and so was catching it in our production data. To catch it and handle gracefully I added a conditional breakpoint just before the "unreachable line" assertion in `_get_bracket_id` and executed several times the script that optimizes several LightGBM regressor hyperparameters (and uses HyperbandPruner and TPESampler).

```python
    def _get_bracket_id(
        self, study: "optuna.study.Study", trial: "optuna.trial.FrozenTrial"
    ) -> int:
        """Compute the index of bracket for a trial of ``trial_number``.

        The index of a bracket is noted as :math:`s` in
        `Hyperband paper <http://www.jmlr.org/papers/volume18/16-558/16-558.pdf>`_.
        """

[..]

        for bracket_id in range(self._n_brackets):
            n -= self._trial_allocation_budgets[bracket_id]
            if n < 0:
                print(f"DEBUG: returning bracket_id={bracket_id} for n={n}") # line added by mirekphd
                return bracket_id

        # import pdb # line added by mirekphd
        # pdb.set_trace() # line added by mirekphd
        # assert False, "This line should be unreachable." # line commented out by mirekphd
        print("\nDEBUG: WARNING: returning 0 after unreachable line assertion failed\n") # line added by mirekphd
        return 0 # line added by mirekphd
```

**Comment by nzw0301** [comment]
Hi thank you for reporting the bug. Could you share the minimal code even though the bug was not reproducible? Otherwise, fixing the bug will be difficult.

**Comment by mirekphd** [comment]
Lack of reproducibility on your own does not imply lack of solutions, @nzw0301, in fact we have at least 3:

1) Conduct a though experiment and imagine a situation when `n>0` for all `_n_brackets` so that the `return bracked_id` line is never reached. I can also provide you with the state of any other variable you like, since I can reproduce it very reliably (on private company data).

2) If you prefer to debug on your own, replace assertion with a breakpoint (like I did in the added commented lines above) and run some studies on simulated data. For added realism you may use public but realistic data from Kaggle, like Allstate claims severity data - that would be closes to our data that triggers these problems.

3) Wait for reproduction by someone else on public data, but in the meantime apply a quick patch that does not require reproducing the error by you: replacing the assertion with the function returning 0 (see 3 last lines of code above). I verified this patch is sufficient to get the same correct results from "bad" studies (i.e. those that would hit the assertion multiple times if left uncommented).  

> Could you share the minimal code even though the bug was not reproducible? Otherwise, fixing the bug will be difficult.

**Comment by nzw0301** [comment]
Thank you for your explanation. I relaised that `HyperbandPruner` is not deterministic somehow, so I understand the difficulty to guarantee reproducibility. Could you share the arguments of study, sampler, and pruner? In addition, did you use [distributed optimisation](https://optuna.readthedocs.io/en/v2.1.0/tutorial/004_distributed.html)?

**Comment by nzw0301** [comment]
Sorry, I realised we could guarantee the reproducible result of `HyperbandPruner`. So I suppose the reported behaviour should be reproducible by fixing `study_name`; [the random seed of sampler](https://optuna.readthedocs.io/en/stable/faq.html#how-can-i-obtain-reproducible-optimization-results) and other libraries; and `PYTHONHASHSEED` at least on your local machine.

**Comment by mirekphd** [comment]
OK, let me try another approach to reach out to you (I'm still hopeful). I have a question: what in the scenario described below is so terribly bad and unacceptable that it warrants breaking execution of potentially _very_ long-running studies?

> 1. imagine a situation when `n>=0` for all `_n_brackets` so that the `return bracked_id` line is never reached.

(I generously assume that the assertion that breaks execution in such situations was left in the code on purpose rather than by accident and omission, as a leftover from some long forgotten debugging session...)

**Comment by doctorcolossus** [comment]
I too reached this "unreachable" line.
