### ISSUE TITLE
Process Timeout to filter out failed/killed tasks

### ISSUE THREAD

**Issue by vballoli** [optuna/optuna#3895]
### Motivation

In order to identify tasks that were killed due to unforeseen system issues, adding a process timeout for a study can help identify tasks that are assumed running but have failed due to SIGKILL, KeyboardException, etc.  This would provide an easy way to handle all sort of errors post running experiments and save some time/resources.

### Description

In order to identify tasks that were killed due to unforeseen system issues, adding a process timeout for a study can help identify tasks that are assumed running but have failed due to SIGKILL, KeyboardException, etc.  This would provide an easy way to handle all sort of errors post running experiments and save some time/resources.

**Comment by not522** [comment]
I think `heartbeat` is what you want. Please see this example. https://github.com/optuna/optuna-examples/blob/bdd974c90f5d73a1be0fb00ccd928953b001ccd0/pytorch/pytorch_checkpoint.py

**Comment by vballoli** [comment]
Yep, this and grace period with some manual tuning helps solve my issue. Thanks a lot! @not522
