### ISSUE TITLE
Print `study.user_attr` by `optuna studies` command

### ISSUE THREAD

**Issue by blazespinnaker** [optuna/optuna#3899]
### Motivation

Using the cli to query studies for their user_attr would be quite useful.  There doesn't seem to be a way to do this, though there does seem to be a way to set a user_attr from the cli

### Description

optuna studies could have a longform option, with format json/yaml/table; or a new option, optuna study --study-name could be added.

**Comment by nzw0301** [comment]
Thank you for sharing the feature request!  You're right. The current `optuna studies` command doesn't show `study.user_attr`. The example is as follows:
 
```shell
STUDY_NAME=`optuna create-study --storage sqlite:///example.db`
optuna study optimize foo.py objective --n-trials=20 --storage sqlite:///example.db --study-name $STUDY_NAME
optuna study set-user-attr --key key --value value --study-name $STUDY_NAME --storage sqlite:///example.db

optuna studies --storage sqlite:///example.db -f yaml
- datetime_start: '2022-08-18 00:46:20'
  direction:
  - MINIMIZE
  n_trials: 20
  name: no-name-903cc7fb-34b5-45ff-b2f7-be1e0eea2dea
```


```python
# foo.py

def objective(trial):
    x = trial.suggest_float('x', -10, 10)
    return (x - 2) ** 2
```

If we implement this feature request, we add a few lines to https://github.com/optuna/optuna/blob/3247030717413b5097db10a26afca67322c91973/optuna/cli.py#L382-L387.


--- 

> optuna studies could have a longform option, with format json/yaml/table

I think the command already has the option as demonstrated above :)

**Comment by blazespinnaker** [comment]
ah, got it, yeah optuna studies shows a different help, which is why i missed it.

Do you think there should be an option, like --show-user-attrs?  or what would be a good option?  I'll take a stab at a pr with some further guidance.

**Comment by nzw0301** [comment]
> Do you think there should be an option, like `--show-user-attrs`? or what would be a good option? I'll take a stab at a pr with some further guidance.

I don't think so because similar command, `optuna trials`, shows the `user_attrs` by default.

**Comment by blazespinnaker** [comment]
My concern might be that if we do it by default it will make the table view mostly unreadable.  Currently it's quite clean, at least for single objective trials.

**Comment by nzw0301** [comment]
That concern is also applicable to `optuna trials`, so we might need to hear the other dev members' or community's opinions. Hence how about separating the concerns from the original motivation to reduce the complexity of forthcoming implementation; Firstly, we will implement the feature where `optuna studies` shows `user_attrs` by default as a PR. Secondly, introducing a new option as you proposed (more generally specify printed or hidden columns) after discussion.

**Comment by nzw0301** [comment]
@blazespinnaker Let me confirm that you're working on this issue. If not, I'd like to add the label `contribution-welcome` to this issue.

**Comment by blazespinnaker** [comment]
That's fine.  I was also hoping for some more discussion.

**Comment by g-votte** [comment]
Let me confirm the current target of this issue. We’ll work on BOTH of the following changes; correct?

- Changing the output format of `optuna studies` so that `user_attrs` by default.
- Add new options to hide a part of output.

My concern is that they might cause a long-running discussion among developers, which is burdensome for a first-time contributor. Historycaly, the current output format has been carefully adjusted to make the output width reasonable.

**Comment by nzw0301** [comment]
@g-votte thank you for your comment. I thought it would be great to work on 

> Changing the output format of `optuna studies` so that `user_attrs` by default.

at least for consistency with `optuna trials` and the current width of the output of `optuna studies` is not too long compared with `optuna trials`.  So a first-time contributor would be able to work on adding this feature as a PR without discussion and we could create another issue to discuss the options. 

However, if we also care about the second one:

> Add new options to hide a part of output.

at the same time, it would require discussion among developers, so this issue is not for the first-time contributor.

**Comment by g-votte** [comment]
@nzw0301 
Thanks for your clarification. This direction looks good to me.

> at least for consistency with optuna trials and the current width of the output of optuna studies is not too long compared with optuna trials.

So, let's target to make this change in this issue: `Changing the output format of optuna studies so that user_attrs by default.`

**Comment by nzw0301** [comment]
@blazespinnaker can you send a PR? As summarised in https://github.com/optuna/optuna/issues/3899#issuecomment-1243350188, the issue has no-discussion to send a PR.

**Comment by nzw0301** [comment]
> Does this mean the PR should include a show user attr flag? 

No, it doesn't. Adding a flag is unnecessary for the PR.

**Comment by gonzaload** [comment]
I will like to work on this one, implementing as default behaviour as described in [comment](https://github.com/optuna/optuna/issues/3899#issuecomment-1243350188)
