### ISSUE TITLE
Add the specification of the behavior of `n_startup_trials` for `constant_liar` option

### ISSUE THREAD

**Issue by not522** [optuna/optuna#3908]
The `n_startup_trials`' document says, "The random sampling is used instead of the TPE algorithm until the given number of trials finish in the same study.", but it is inconsistent with ~~`group=True`~~ or `constant_liar=True`. We need to specify the behavior for these options.

**Comment by hvy** [comment]
@not522 do you mind elaborating a bit on what must be discussed given it's labeled `needs-discussion` ?

**Comment by not522** [comment]
I notice that `group=True` does not affect the behavior of `n_startup_trials`. 🙇

As far as I know, we do not have a concrete specification of `n_startup_trials` for the `constant_liar` option. We need to discuss the behavior.
The document says, "The random sampling is used instead of the TPE algorithm until the given number of trials finish in the same study."
The current default behavior is to count how many trials involving the interested parameter have been completed.
The behavior with `constant_liar=True` seems to be buggy. `TPESampler` counts `RUNNING` trials as finished.

**Comment by hvy** [comment]
Ah, thanks for the explanation. Given the documentation, it sounds like bugs but that needs to be fixed. 
But you mean that it might be more intuitive to keep the current behavior with `constant_liar` and update the documentation to clarify this? 🤔

**Comment by not522** [comment]
Maybe we need to fix it, but I'm not sure which one is better. We need to benchmark with the `constant_liar` option.
