### ISSUE TITLE
Enable logging by-study vs global

### ISSUE THREAD

**Issue by eafpres** [optuna/optuna#3925]
### Motivation

I have a use case where I call a study from within the optimization function of another study.  In the call within the function, I would like to turn logging off, but not for the outer study.  Now, since optuna.logging.set_verbosity() seems global, changing it in the inner study affects the outer study.

### Description

Create a functionality like study.logging.set_verbosity()

**Comment by nzw0301** [comment]
Hi, could you give some minimal examples not to misunderstand the situation?
