### ISSUE TITLE
N_trials on parallel optimization runs n_trials per pod and not in total

### ISSUE THREAD

**Issue by Ohadkaiser** [optuna/optuna#3938]
### Expected behavior

When running the optimize function in optuna on distributed pods in parallel, the expected behavior is that the pods will synchronize on the number of trial and the total amount will be the number set with the parameters n_trials.
Currently, n_trials define the number of trials per pod. 

### Environment

- Optuna version: 2.10.0
- Python version: 3.7
- OS: Linux 
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
.
```

### Steps to reproduce

.

**Comment by Ohadkaiser** [comment]
The change that need be done is the following.

In _optimize_sequential function we need to check if study.storage.get_n_trials if smaller than n_trials instead of i_trial

**Comment by nzw0301** [comment]
I suppose it is not the bug as in https://github.com/optuna/optuna/issues/3518.

**Comment by Ohadkaiser** [comment]
> I suppose it is not the bug as in #3518.

That you for your response!
I will suggest a solution to #3518 as I see fit.
