### ISSUE TITLE
plot_param_importances taking too long to run/show plot

### ISSUE THREAD

**Issue by Freemanlabs** [optuna/optuna#3962]
### Expected behavior

When I try to visualize the important parameters from a (saved) study, it takes forever. I don't get to see the plot due to the large runtime. 
I notice it works (with same amount of data) with n_trial = 10. But when I do the actual optimization with n_trial=100, it runs for forever.

I expect a parameter importance plot (very quickly)

### Environment

- Optuna version: 2.10.1
- Python version: 3.8.13
- OS: OS:Linux-5.15.0-46-generic-x86_64-with-glibc2.17
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
No error. It just runs for forever.
```

### Steps to reproduce

1. Create a study and save the artifacts
2. Load the saved artifacts/study
3. Visualize the parameter importance of the study.
```python
study = joblib.load(result)
fig = optuna.visualization.plot_param_importances(study)
fig.show()
```

**Comment by Freemanlabs** [comment]
@nzw0301 I shared the code initially under "Steps to reproduce".

However, using the faster fanova, I get a memory error.
```
MemoryError: Unable to allocate 1.00 PiB for an array with shape (140737488355328,) and data type float64
```

How do I get past this?

**Comment by nzw0301** [comment]
> I shared the code initially under "Steps to reproduce".
It's not reproducible, I'm afraid.

**Comment by Freemanlabs** [comment]
> It's not reproducible, I'm afraid.

There's no way you will be able to reproduce the code without the saved study ('result' as shown in the code).
Please see link to the saved study (.pkl)

https://drive.google.com/file/d/1_zCsWfa8df8Ej16FZ2M-ee06xgslxht-/view?usp=sharing

**Comment by nzw0301** [comment]
I'm afraid that we could not download the compressed pickle file because the pickle is not secure as mentioned in https://docs.python.org/3/library/pickle.html. Could you create a code without loading the pickle file that you made for data?

**Comment by nzw0301** [comment]
I suppose your study contains too many parameters too, so another approach is to reduce trials from the study for visualisation by using https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.add_trials.
