### ISSUE TITLE
No info about multi-objective optimization

### ISSUE THREAD

**Issue by mavillan** [optuna/optuna#3963]
### What is an issue?

Hi all,

I have checked all the documentation and I cannot find any information about the inner mechanism of multi-objective optimization. I think it would be very helpful to document what exactly Optuna does when you give multiple objectives for optimization.

**Comment by not522** [comment]
I'm not sure what you want, following documents may help you.
* Tutorial: https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/002_multi_objective.html
* `NSGAIISampler` (default sampler for multi-objective optimization): https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.NSGAIISampler.html
