### ISSUE TITLE
Avoid PyTorch version mismatch between BoTorch and Optuna.

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#3988]
### Motivation

BoTorch used in [the integration module of Optuna](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.BoTorchSampler.html) has dropped Python 3.7 support since its version 0.8.0 ~0.9.0~. With this change, the PyTorch version specified by Optuna will not match the version specified by BoTorch in the future with the current `setup.py` and Python 3.7.

### Description

Optuna cares about backward compatibility and older python for users; Optuna won't stop supporting BoTorch with Python 3.7. 

A possible solution is to make some branches depending on the Python version for BoTorch module. 

### Alternatives (optional)

We might decompose the current too large `"integration"` section in `setup.py` into smaller ones somehow, which requires consensus among the contributors.

**Comment by nzw0301** [comment]
Similarly, Allennlp is under maintenance, which might not support PyTorch>=1.12.0 anymore as specified at https://github.com/allenai/allennlp/blob/b2eb036e06fbf4e293abb126552aaabc3df91aa1/requirements.txt#L4.

**Comment by contramundum53** [comment]
Why did we fix PyTorch version to 1.11? If we could remove that constraint, maybe we could resolve this problem?

**Comment by nzw0301** [comment]
> Why did we fix PyTorch version to 1.11? 

I don't know 🤔
