### ISSUE TITLE
Visualize a subset of study

### ISSUE THREAD

**Issue by xuzijian629** [optuna/optuna#4012]
### Motivation

I'm trying contour visualization.
Sometimes, there are several outliers and the details near the best objective is not visualized well.

![](https://github.com/xuzijian629/tekito/blob/main/%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88%202022-09-21%209.21.01.png?raw=true)

So, I would like to visualize a subset of whole study so that I can see the gradients near the best solution.

### Description

Basically, it would be helpful if we can use something like

```python
optuna.visualization.plot_contour(study, xlim=(1, 1e6))
```

, or the colormap scales dynamically as we update ranges in html visualization.

### Alternatives (optional)

I also thought
```python
optuna.visualization.plot_contour(study, clip_objective=45e9)
```
(only plot data whose objective is at most 45e9) is useful, but this may incorrectly visualize the gradients, thus it's not proper.

Maybe we can still visualize the whole data, but adjust color scales for data near optimal. In this case,
```python
optuna.visualization.plot_contour(study, color_scale=(25e9, 40e9))
```
will be perfect.

**Comment by not522** [comment]
Thank you for your feedback! I recommend `add_trials` as workaround.

```python
study_for_visualization = optuna.create_study()
study_for_visualization.add_trials(filter(lambda trial: trial.value < 45e9, study.trials))
optuna.visualization.plot_contour(study_for_visualization)
```

**Comment by xuzijian629** [comment]
Thanks, that sounds really nice!
Please close this if you think there is no need to implement new features.

**Comment by not522** [comment]
Let me close this issue. I think combining basic features would be better to keep the visualization interface simple.
