### ISSUE TITLE
Support for qNoisyExpectedHypervolumeImprovement acquisition function from Botorch

### ISSUE THREAD

**Issue by saugatkandel** [optuna/optuna#4014]
### Motivation

The Botorch/Ax documentation seems to suggest that the qNEHVI acquisition function  performs better than the qEHVI acquisition function. 
See for example:

"For batch optimization (or in noisy settings), we strongly recommend using 𝑞NEHVI rather than 𝑞EHVI [1] because it is far more efficient than 𝑞EHVI and mathematically equivalent in the noiseless setting."
in 
https://botorch.org/tutorials/constrained_multi_objective_bo

I tried both for my application, and I also found that qNEHVI performed better than qEHVI. 

Modifying the Botorch integration in optuna to also include the qNEHVI acquisition function could be an easy but nice feature in optuna.

### Description

This should be a simple change to 
https://github.com/optuna/optuna/blob/master/optuna/integration/botorch.py.

I would suggest modifying 
```python
from botorch.acquisition.multi_objective.monte_carlo import qExpectedHypervolumeImprovement
```
to 

```python
from botorch.acquisition.multi_objective.monte_carlo import qExpectedHypervolumeImprovement, qNoisyExpectedHypervolumeImprovement
```

And adding a function (slightly modified version of qehvi_candidates_func):
```python

def qnehvi_candidates_func(
    train_x: "torch.Tensor",
    train_obj: "torch.Tensor",
    train_con: Optional["torch.Tensor"],
    bounds: "torch.Tensor",
) -> "torch.Tensor":
    """Quasi MC-based batch Expected Noisy Hypervolume Improvement (qnehvi).

    [some documentation]
    """

    n_objectives = train_obj.size(-1)

    if train_con is not None:
        train_y = torch.cat([train_obj, train_con], dim=-1)

        is_feas = (train_con <= 0).all(dim=-1)
        train_obj_feas = train_obj[is_feas]

        constraints = []
        n_constraints = train_con.size(1)

        for i in range(n_constraints):
            constraints.append(lambda Z, i=i: Z[..., -n_constraints + i])
        additional_qnehvi_kwargs = {
            "objective": IdentityMCMultiOutputObjective(outcomes=list(range(n_objectives))),
            "constraints": constraints,
        }
    else:
        train_y = train_obj

        train_obj_feas = train_obj

        additional_qnehvi_kwargs = {}

    train_x = normalize(train_x, bounds=bounds)

    model = SingleTaskGP(train_x, train_y, outcome_transform=Standardize(m=train_y.shape[-1]))
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_model(mll)

    # Approximate box decomposition similar to Ax when the number of objectives is large.
    # https://github.com/facebook/Ax/blob/master/ax/models/torch/botorch_moo_defaults
    if n_objectives > 2:
        alpha = 10 ** (-8 + n_objectives)
    else:
        alpha = 0.0

    ref_point = train_obj.min(dim=0).values - 1e-8

    #partitioning = NondominatedPartitioning(ref_point=ref_point, Y=train_obj_feas, alpha=alpha)

    ref_point_list = ref_point.tolist()

    acqf = qNoisyExpectedHypervolumeImprovement(
        model=model,
        ref_point=ref_point_list,
        X_baseline=train_x,
        #partitioning=partitioning,
        prune_baseline=True,
        sampler=SobolQMCNormalSampler(num_samples=256),
        **additional_qnehvi_kwargs,
    )

    standard_bounds = torch.zeros_like(bounds)
    standard_bounds[1] = 1

    candidates, _ = optimize_acqf(
        acq_function=acqf,
        bounds=standard_bounds,
        q=1,
        num_restarts=20,
        raw_samples=1024,
        options={"batch_limit": 5, "maxiter": 200, "nonnegative": True},
        sequential=True,
    )

    candidates = unnormalize(candidates.detach(), bounds=bounds)

    return candidates
```

I set `prune_baseline=True` for my work, but there should probably be a parameter for that in the Botorch sampler API.

Just this worked quite well in my application.

**Comment by not522** [comment]
Thanks for the information. It sounds interesting! If you have time, would you make it a PR?

@hvy Could you tell me how you chose the default `candidates_func`?

**Comment by hvy** [comment]
Hm, I followed BoTorch's official tutorial, but the suggestion about the noisy variant was not mentioned back then. See https://github.com/pytorch/botorch/pull/978 which updates the tutorial with qNEHVI and that it was merged after the introduction of this sampler. 

Sounds good to introduce a new `candidates_func` and perhaps reconsider the default. I haven't gone over the differences yet so cannot tell for sure but we're now also acting differently from `Ax`

>  Given a MultiObjective, Ax will default to the 𝑞NEHVI acquisiton function. 

https://botorch.org/tutorials/constrained_multi_objective_bo

Also worth pointing out that this sampler is still experimental.

**Comment by saugatkandel** [comment]
> Thanks for the information. It sounds interesting! If you have time, would you make it a PR?
> 
> @hvy Could you tell me how you chose the default `candidates_func`?

I am not confident enough in my understanding of these toolsets to make a full PR. I will let the people with more know-how decide if and when to incorporate this.

**Comment by g-votte** [comment]
@eukaryo will work on this issue.

**Comment by eukaryo** [comment]
Let me to close this issue.
