### ISSUE TITLE
Improve tests for heartbeat

### ISSUE THREAD

**Issue by not522** [optuna/optuna#4026]
### Motivation

Current tests for heartbeat are inadequate. We need to add lacking patterns.

### Description

[test_heartbeat.py](https://github.com/optuna/optuna/blob/e8abeec7d58b64b207bd7606056311d20de0241f/tests/storages_tests/test_heartbeat.py) lacks the following patterns.

- Test that `fail_stale_trials` does not change the trial state if the trial is not stale.
- Test that `fail_stale_trials` does not change the trial state if `record_heartbeat` is never called.

**Comment by cross32768** [comment]
Can I take this issue?

**Comment by g-votte** [comment]
@cross32768
Please go ahead!

**Comment by g-votte** [comment]
Closing as #4055 fixed this issue.
