### ISSUE TITLE
Improve tests for `Study.tell`

### ISSUE THREAD

**Issue by not522** [optuna/optuna#4027]
### Motivation

`Study.tell` supports being called from a process other than the one that calls `ask`, but this feature is not tested except with the command line interface.

### Description

Add tests calling from another process in [test_study.py](https://github.com/optuna/optuna/blob/e8abeec7d58b64b207bd7606056311d20de0241f/tests/study_tests/test_study.py). It can be written using `subprocess`.

**Comment by Abelarm** [comment]
Hi @not522,

I could take this if is it ok for you.

**Comment by not522** [comment]
Of course. Please go ahead.
