### ISSUE TITLE
Is it possible to access the base estimator of a sampler 

### ISSUE THREAD

**Issue by ggjj11** [optuna/optuna#4047]
E.g. when defining a sampler like this:

```
from optuna.integration import SkoptSampler

sampler = SkoptSampler(skopt_kwargs={'base_estimator':'`GP',
                                     'n_random_starts':10,
                                     'acq_func':'EI',
                                     'acq_func_kwargs': {'xi':0.02}})
study = optuna.create_study(sampler=sampler, direction="minimize")
study.add_trial(...some_historic_data params = X, value = y)....)
study.add_trial(...some_historic_data params=X, value = y)
study.add_trial(...some_historic_data params=X, value = y)

...
study.ask(search_space)

```

Is it possible to get the base_estimator from skopt?

If I understand skopts gp_minimize (https://scikit-optimize.github.io/stable/modules/generated/skopt.gp_minimize.html ) correctly, it would return `models`. I looked at the docu and the code of optuna and could not find how I could access those models after I invoked the above code.

Accessing the base estimator is very important in many applications and would facilitate a lot of further steps. If it is not possible yet, could it be implemented?

PS: I am a bit confused: skopt uses negative expected improvement (which I want to minimize for maximizing my expected improvement) and I myself have the goal to maximize y. What should I pass to optuna with the direction argument? maximize or minimize? The documentation could be more clear here in the skopt integration part.

**Comment by toshihikoyanase** [comment]
@ggjj11 Thank you for your question and your feature request.

> Is it possible to get the base_estimator from skopt?

Currently, we cannot get the raw optimizer of `skopt` including `base_estimator`. It is newly created as a private variable in `sample_relative`, and `sample_relative` is called before trials are passed to objective functions.

https://github.com/optuna/optuna/blob/f6af65d0e46f74b5499a9e9d49881b564f45ef67/optuna/integration/skopt.py#L180-L186

> If it is not possible yet, could it be implemented?

`SkoptSampler` is designed to be used in parallel optimization, and I couldn't find straightforward ways to implement the feature. As a workaround for sequential optimization, how about create a subclass to keep `optimizer` in the `sample_relative` method?

```python
class MySkoptSampler(SkoptSampler):
    def sample_relative(
        self,
        study: Study,
        trial: FrozenTrial,
        search_space: Dict[str, distributions.BaseDistribution],
    ) -> Dict[str, Any]:

        self._raise_error_if_multi_objective(study)

        if len(search_space) == 0:
            return {}

        complete_trials = self._get_trials(study)
        if len(complete_trials) < self._n_startup_trials:
            return {}

        self.optimizer = _Optimizer(search_space, self._skopt_kwargs)
        if self._rng is not None:
            optimizer._optimizer.rng = self._rng
        optimizer.tell(study, complete_trials)
        params = optimizer.ask()
        self._rng = optimizer._optimizer.rng
        return params
```

Then, you can get the `skopt.Optimizer` instance as follows:

```python
sampler = MySkoptSampler()
study = optuna.create_study(sampler=sampler)
study.optimize(...)
skopt_optimizer = study.sampler.optimizer._optimizer
```

> What should I pass to optuna with the direction argument?

In optuna, directions of optimization (i.e., minimize or maximize) is handled by `Study` objects, not `Sampler` objects. The samplers switches the logic depending on the directions in the studies. So, please set `direction="maximize"` to `optuna.create_study` if you want to `maximize` the objective function.
