### ISSUE TITLE
The plot and report of Bayesmark scripts are inconsistent

### ISSUE THREAD

**Issue by knshnb** [optuna/optuna#4066]
### Expected behavior

Consistent results in the plots and `report.md`.

### Environment

GitHub Actions: https://github.com/optuna/optuna/blob/1a520bd5daa9ff0af09fb060464bb157f8af891b/.github/workflows/performance-benchmarks-bayesmark.yml

### Error messages, stack traces, or logs

```shell
https://github.com/optuna/optuna/actions/runs/3143078497

(See Additional context)
```

### Steps to reproduce

Run `Actions -> Performance benchmarks with bayesmark` with the default arguments.

### Additional context (optional)

The values in the plots and `report.md` seem to be inconsistent.
Example:
![image](https://user-images.githubusercontent.com/23695091/195053993-9fa16f86-25d8-4252-ad53-bc2f7ddff925.png)
![image](https://user-images.githubusercontent.com/23695091/195054314-8daf8e63-94bf-4615-a6f9-6221b5b59dbe.png)

**Comment by knshnb** [comment]
@xadrianzetx I'm not sure if this is a bug or expected behavior, but would you mind checking this when you have time?

**Comment by xadrianzetx** [comment]
Best value is calculated as an average of smallest generalization errors across repeated study runs. What we see on the plot is an average of generalization error at particular iteration across repeated study runs. Looking back at kurobako, _I think_ this is a bug, as values on plot should represent `Best value` metric up to a specific iteration (what would be the metric value if we took all trials that ran so far), not averaged generalization error at specific iteration. If you think this makes sense @knshnb, I probably can fix these plots in the next few days (or faster if this blocks anybody).

**Comment by knshnb** [comment]
Thank you so much for the quick response!
You mean what we see on the current plot is the previous best of average generalization errors at each iteration (because the value seems to be monotonically decreasing)? I also think that the average of the previous bests makes more sense. That schedule is totally fine and I would pretty much appreciate it if you could fix them 👍
