### ISSUE TITLE
MLflowCallback error when using n_jobs > 1

### ISSUE THREAD

**Issue by raulcarlomagno** [optuna/optuna#4088]
### Expected behavior

be able to use more than one job and at the same time log it in mlflow

### Environment

- Optuna version: 3.0.3
- Python version: 3.9.7
- OS: Linux-4.14.35-1902.8.4.el7uek.x86_64-x86_64-with-glibc2.31
- MLFlow version:  1.29.0

### Error messages, stack traces, or logs

```shell
Exception: Run with UUID 13a5f691281742d1a9d6b6f98c43203a is already active. To start a new run, first end the current run with mlflow.end_run(). To start a nested run, call start_run with nested=True
```

### Steps to reproduce

trying to use multiprocessing i get 

i know it is an mlflow issue, but there are some fixes to do when interacting with the mlflow api to support multiprocessing
so, some changes to MLflowCallback should be done

potential fixes
https://github.com/mlflow/mlflow/issues/3592
https://github.com/mlflow/mlflow/issues/1420

i tried even using:
`
    mlflow_kwargs={
        'nested': False
    }
`
but this raises duplication data and errors in mlflow

i also tried with
`
from joblib import parallel_backend
with parallel_backend('multiprocessing'):`
during study.optimize()

**Comment by toshihikoyanase** [comment]
Could you share the minimum reproducible code, please?

**Comment by nzw0301** [comment]
FYI: @toshihikoyanase 

```python
import optuna
import mlflow
from optuna.integration.mlflow import MLflowCallback

mlflc = MLflowCallback(
    metric_name="my metric score",
)


def objective(trial):
    x = trial.suggest_float("x", -10, 10)
    mlflow.log_param("power", 2)
    mlflow.log_metric("base of metric", x - 2)

    return (x - 2) ** 2


study = optuna.create_study(study_name="my_other_study")
study.optimize(objective, n_trials=100, callbacks=[mlflc], n_jobs=4)
```

**Comment by toshihikoyanase** [comment]
@nzw0301 Thank you for providing the reproducible code. The provided code causes the same error without `n_jobs=4`. I may miss something, but I guess the cause of the error may not be related to the parallelization.

```python
import optuna
import mlflow
from optuna.integration.mlflow import MLflowCallback

mlflc = MLflowCallback(
    metric_name="my metric score",
)


def objective(trial):
    x = trial.suggest_float("x", -10, 10)
    mlflow.log_param("power", 2)
    mlflow.log_metric("base of metric", x - 2)

    return (x - 2) ** 2


study = optuna.create_study(study_name="my_other_study")
study.optimize(objective, n_trials=100, callbacks=[mlflc])
```

Without `mlflow.log_param` and `mlflow.log_metric`, the code without `n_jobs=4` finished successfully while the code with `n_jobs=4` failed with the following error.

```console
mlflow.exceptions.MlflowException: Changing param values is not allowed. Param with key='x' was already logged with value='-1.4760283430008698' for run ID='b21577ccc7b94137a18aeb019526c023'. Attempted logging new value '-4.902930734265949'.
```

I guess the mlflow integration has multiple issues related to your reproducible code.

**Comment by nzw0301** [comment]
@toshihikoyanase Thank you for your comment. Sorry for confusing you by sharing the wrong code. The reproducible code should be as follows:


```python
import optuna
from optuna.integration.mlflow import MLflowCallback


def objective(trial):
    x = trial.suggest_float("x", -10, 10)
    return (x - 2) ** 2


mlflc = MLflowCallback(
#     tracking_uri=YOUR_TRACKING_URI,
    metric_name="my metric score",
)

study = optuna.create_study(study_name="my_study")
study.optimize(objective, n_trials=10, callbacks=[mlflc], n_jobs=4)
```

This code is almost the same as https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.MLflowCallback.html.

**Comment by HideakiImamura** [comment]
@gen740 is working on this issue.

**Comment by gen740** [comment]
Optuna uses [mlflow fluent tracking API](https://mlflow.org/docs/latest/python_api/mlflow.html#mlflow.start_run), which is not threadsafe.

> The fluent tracking API is not currently threadsafe.

This bug is caused by race-condition of `mlflow.start_run()`.
