### ISSUE TITLE
Can optuna support for many-objective optimazaion?

### ISSUE THREAD

**Issue by yuzizbk** [optuna/optuna#4089]
### Don't use GitHub Issues to ask support questions.

Hi, can optuna support many-objective optimazaion? For example, if I have five objective, what sampler can I use? Expect your answer, thank you.

**Comment by c-bata** [comment]
Please use GitHub Discussions for questions.

> Hi, can optuna support many-objective optimazaion? For example, if I have five objective, what sampler can I use? Expect your answer, thank you.

Please check [this table](https://optuna.readthedocs.io/en/latest/reference/samplers/index.html) to know which sampler supports multi-objective optimization.
