### ISSUE TITLE
`None` categorical not visible on Slice plot

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#4108]
### Expected behavior

I have a categorical like this: `trial.suggest_categorical("class_weight", ["balanced", None])`

The slice plot shows the "balanced" value but not the `None` value.
I could write a workaround by using `"None"` as a string and then convert it to `None`
but I thing it could be nice if the real `None` is ploted.

See sceenshot:

<img width="234" alt="image" src="https://user-images.githubusercontent.com/229382/199188383-981f256d-0b66-4a1c-be40-68ecd6ae4528.png">

### Environment

- Optuna version:3.0.3
- Python version:3.9.13
- OS:Linux-5.10.0-17-amd64-x86_64-with-glibc2.31

### Error messages, stack traces, or logs

```shell
see screenshot
```

### Steps to reproduce

see description above

**Comment by nzw0301** [comment]
Thank you for reporting this but. I can reproduce this bug with the following code.

```python
import optuna


def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    trial.suggest_categorical("y", ["hoge", None])
    return x ** 2


sampler = optuna.samplers.TPESampler(seed=3)
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=2)

fig = optuna.visualization.plot_slice(study)
fig.show()
```

Note that this bug doesn't happen with matplotlib version; it correctly shows `None`.
