### ISSUE TITLE
Add a function that decides the likely-best parameter from the trials executed so far

### ISSUE THREAD

**Issue by contramundum53** [optuna/optuna#4124]
### Motivation

Currently, Optuna only has the interface for returning the trial that resulted in the best value after the study is over. This is not good when the objective function is noisy and the number of trials are small, since a bad parameter can result in the best value by chance. Instead, we should use some algorithm to decide the parameter that would most likely yield the best result in the evaluation run.

### Description

Each black-box optimization algorithm usually has some natural way to do that. Examples include:
* For GP, the natural way would be returning the parameter with highest expected value in the surrogate GP model.
* For TPE, the natural way would be returning the parameter with highest probability density in "below" distribution.
* For CMA-ES, the natural way would be returning the mean value of the normal distribution.

Although these algorithms are inspired by each sampler, these algorithms can be used independently from the sampler. Thus, we could implement these algorithms as free-standing functions.

### Alternatives (optional)

Alternatively, we could add a function in applicable samplers.

**Comment by shindannin** [comment]
I strongly support this idea. In environments with limited computational resources, we can't afford to perform extensive calculations to remove noise from noisy functions. Therefore, having functionality like this would be helpful.
Additionally, if internal features like CMA-ES sample are already available, implementation would be relatively straightforward.
