### ISSUE TITLE
Update the versions of official/third-party actions in CI

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#4165]
### Motivation

Optuna uses several official actions of GitHub Actions in CI. The versions of those official actions have not been updated since those were created and remain out of date. Now, it may be a good time to consider updating those versions to the latest versions.

### Suggestion

For each of the following official/third-party actions, do the following two works.
- Investigate the impact of updating the version. Please list pros/cons.
- Submit a PR to change to update the version.

List:
- [x] actions/checkout@v2 -> v3 #4206 
- [x] actions/setup-python@v2 -> v4 
- [x] actions/cache@v2 -> v3 #4207 
- [x] actions/stale@v5 -> v6 #4208 
- [x] actions/upload-artifact@v2 -> v3
- [x] actions/labeler@v2 -> v4
- [x] codecov/codecov-action@v1 -> v3
- [x] pypa/gh-action-pypi-publish@v1.1.0 -> v1 (Use the latest version of v1.x)

**Comment by Alnusjaponica** [comment]
I am working on this issue.

**Comment by HideakiImamura** [comment]
Which ones do you working on? Each action should be updated in separate PRs.

**Comment by Alnusjaponica** [comment]
Thanks for your comment. I start from actions/checkout.

**Comment by Kaushik-Iyer** [comment]
Can I work on updating some of these actions? @Alnusjaponica @HideakiImamura

**Comment by Alnusjaponica** [comment]
Sure! Currently, I am not working on the rest of 5 actions. Thank you for your corporation. @Kaushik-Iyer

**Comment by Kaushik-Iyer** [comment]
@HideakiImamura for updating setup-python from v2 to v4, should I be updating the python versions too (from 3.8 to 3.10)?

**Comment by HideakiImamura** [comment]
No, you should not update the python version.

**Comment by contramundum53** [comment]
All tasks are done. Let me close this issue.
