### ISSUE TITLE
add study.best_trials_constrained to get the pareto front of only best feasible trials 

### ISSUE THREAD

**Issue by okaikov** [optuna/optuna#4180]
### Motivation

Currently study.best_trials return the pareto front of all completed trials.
It make sense to add a functionality of getting the best feasible trials

### Description

see above

**Comment by Alnusjaponica** [comment]
JFYI, Optuna already has functionality to confirm feasibility when visualizing the results from v3.0.0. If you just want to visualize the results, you may be able to use it.

https://optuna.readthedocs.io/en/stable/reference/visualization/generated/optuna.visualization.plot_pareto_front.html#optuna.visualization.plot_pareto_front

**Comment by okaikov** [comment]
Yes, I'm aware that the requested functionality exists when visualizing the pareto front.
I need to use the functionality not for visualizing, but for some other logic/function, so it make sense to decouple it from the visualizing module.

**Comment by Alnusjaponica** [comment]
Thank you for the suggestion. I see your point.
For now, the following workaround based on the part of optuna.visualization.plot_pareto_front(), where feasibility of each trial is checked, might solve your problem  (for more details, see [here](https://github.com/optuna/optuna/blob/c446c9c4074b9cde837df5a932dc8ab02a54cda2/optuna/visualization/_pareto_front.py#:~:text=if%20constraints_func%20is,feasible%20trials.%22)).

```
# Define constraints_func() as what optuna.visualization.plot_pareto_front accepts as a paremeter.

new_study = optuna.create_study(directions=study.directions)
feasible_trials = []
for trial in study.get_trials(deepcopy=False, states=(TrialState.COMPLETE,)):
    if all(map(lambda x: x <= 0.0, constraints_func(trial))):
        feasible_trials.append(trial)
new_study.add_trials(feasible_trials)
new_study.best_trials
```
