### ISSUE TITLE
PyTorchLightningPruningCallback integration should continue past traint.fit() and complete the objective function

### ISSUE THREAD

**Issue by daniel-a-diaz** [optuna/optuna#4203]
### Motivation

When using the `PyTorchLightningPruningCallback` integration, it looks like pruned trials return directly from `trainer.fit()` or something so that any code afterwards within the objective function doesn't run.

### Description

I would like that when pruning occurs with the `PyTorchLightningPruningCallback` integration, the code continues right where it left off after `train.fit()` and completes the rest of the objective function.

### Alternatives (optional)

The alternative is to simply use Pytorch Lightning's `EarlyStopping`.

**Comment by Alnusjaponica** [comment]
Callback function terminates the objective function from `train.fit()` by raising `optuna.TrialPruned()`, so replacing `trainer.fit()` with the following block might solve your problem.
```
try:
    trainer.fit()
exept:
    # copy of the code after trainer.fit() in objective function
    raise optuna.TrialPruned()
```

**Comment by Alnusjaponica** [comment]
I think the workaround above resolves your problem so I'll close this issue. Please feel free to re-open if you have any additional problem.
