### ISSUE TITLE
Suggest not sharing pickle file to report bug or question

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#4210]
### Motivation

When we ask users to share minimal reproducible code, especially for a bug report, users sometimes share data formatted by `pickle`. Since `pickle` is known as an insecure module (ref: https://docs.python.org/3/library/pickle.html), we probably cannot open such data files and ask them to share alternative formats such as sklearn's toy dataset or MNIST. For much smoother communication between bug-reporter and contributors, it would be great to clarify that we cannot open the insecure formatted file.

### Description

Mention not sharing pickle data in issue templates or contribution guide.

**Comment by toshihikoyanase** [comment]
Agree.

> Mention not sharing pickle data in issue templates or contribution guide.

How about mentioning it in the [issue template of bug report](https://github.com/optuna/optuna/blob/5a1f74f5abb57633363ca9dfe98a12b2c32f40e3/.github/ISSUE_TEMPLATE/bug-report.yml
)? The [contribution guide](https://github.com/optuna/optuna/blob/master/CONTRIBUTING.md#contribution-guidelines) does not explain the reproducibility, but the issue template does.

**Comment by nzw0301** [comment]
Lovely. Thanks!
