### ISSUE TITLE
Does BOHB's surrogate model take into acocunt the budget in Optuna?

### ISSUE THREAD

**Issue by kstoneriv3** [optuna/optuna#4211]
### BOHB's surrogate model

In the [BOHB paper](https://arxiv.org/pdf/1807.01774.pdf), the surrogate model for the Bayesian optimization has form `y = g(x, b)`. (Here, `y`, `x`, and `b` are the objective value, the hyperparameter, and the budget respectively.) However, Optuna's implementation of BOHB (i.e. `TPESampler` + `HyperbandPruner` or `BoTorchSampler` + `HyperbandPruner`) seems to use simpler surrogate model `y = g(x)`, which does not depend on budget `b`. As far as I can see, it is retrieving all trials in the storage whose states are either `TrialState.COMPLETE` or `TrialState.PRUNED` at [optuna/samplers/_tpe/sampler.py#L586](https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L586) and using them in the same manner afterwards. 

IMO, ignoring the dependence of `b` results in giving too much credit to the pruned observations and it may result in underestimating the hyperparameters which are in the neighborhood of the pruned hyperparameters. So it would be great if anyone can explain the current surrogate models of BOHB in Optuna.

**Comment by gen740** [comment]
As you mentioned, TPESampler does not take into account budget b, currently.

**Comment by gen740** [comment]
Since the optuna TPESampler is under refactoring, it will be a bit messy. But if you don't mind, how about creating a prototype?

**Comment by kstoneriv3** [comment]
> Do you know if BoTorchSampler considers the budget?

Now I figured out that BoTorch does not use pruned trials but why is it the case? I assume we can similarly include pruned trials for the construction of the surrogate model and similarly conduct BOHB as the current TPE. (I am wondering why BoTorch does not use pruned trials right now.) In the original paper of BOHB, they do not exclude the possibility of using GP-based BO -- they used the TPE because of the implementational simplicity and stability at the time when it was written.

> But if you don't mind, how about creating a prototype?

I might try to implement it and benchmark it with kurobako at some point but I am too busy to do it right now. Anyone motivated to try it is encouraged to do it without asking me.
