### ISSUE TITLE
Documentation warnings with Sphinx `nitpicky`

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#4213]
### What is an issue?

Building the documentation using [Sphinx's `nitpicky`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-nitpicky), we can observe several warnings.
At a quick glance, there are several types of different errors

a. Typos in references, e.g. `user_attrs` expected but `user_attr`
b. Referenced target is missing documentation, e.g. `FrozenTrial.suggest_float`
c. Reference to API's in other libraries, such as `numpy` or `torch`

a. should be straight forward to fix. b. and c might need discussions. As for b., we need to ensure that it's actually a public API that should be documented, as for c. we might want to agree on some policy what libraries to include and test to make sure it works. C.f. https://github.com/optuna/optuna/blob/master/docs/source/conf.py and https://docs.readthedocs.io/en/stable/guides/intersphinx.html

#### Repro

1. Add the `-n` (`nitpicky=True`) option in `docs/Makefile`

```diff
diff --git a/docs/Makefile b/docs/Makefile
index 4bdf05f33..579749286 100644
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -2,7 +2,7 @@
 #

 # You can set these variables from the command line.
-SPHINXOPTS    = -W --keep-going
+SPHINXOPTS    = -W --keep-going -n
 SPHINXBUILD   = sphinx-build
 SPHINXPROJ    = Optuna
 SOURCEDIR     = source
```

2. Build the documentation and observe the warnings.

```console
$ pip install -e '.[document]'
$ cd docs
$ make html
# Notice list of warnings.
```

3. (Optional) Debug/check references in the build.

```console
$ open build/html/index.html
```

#### Note

I'd like to hear opinions from other developers about using `-n` in the CI. Using it would make the process (e.g. reviewing) easier.

**Comment by c-bata** [comment]
@nzw0301 Can we resolve all documentation warnings in #4287?

**Comment by nzw0301** [comment]
@c-bata  No, #4287 only reduces warnings related to

> a. Typos in references, e.g. user_attrs expected but user_attr

in https://github.com/optuna/optuna/issues/4213#issue-1468901223

So b and c are not resolved yet.

**Comment by c-bata** [comment]
I see! Thank you for letting me know.

**Comment by nzw0301** [comment]
According to the issue description, supposedly b and c need some policy or discussion among core developers.

For a smooth discussion about c, I've sent #4290 to check the built docs.

**Comment by toshihikoyanase** [comment]
The possible follow-up tasks for #4290 are as follows:
- `torch.distributed.ProcessGroup` is not linked to the pytorch document https://github.com/optuna/optuna/pull/4290#discussion_r1095256156
- `pd.Dataframe` is not linked to the pandas document https://github.com/optuna/optuna/pull/4290#discussion_r1095257014

**Comment by HideakiImamura** [comment]
Let me close this issue since I have split the remaining problems in three issues.

**Comment by hvy** [comment]
Many thanks. Seems easier to tackle now that tasks are more concretized. 🙇
