### ISSUE TITLE
Make samplers more verbose about the state of the optimization

### ISSUE THREAD

**Issue by simpsus** [optuna/optuna#4241]
### Motivation

I would love to peek inside the sampler while the study runs and perhaps gain insides what I can do in terms of search space to enhance the experiment.

### Description

Currently the only debug shown on the command line is the score and parameter values of a trial when it is finished.
I would love to see the sampler tell me something about its internal state and why it chose the values it has chosen for the next trial. On the example of NSGAIISampler, there is a population and there is a new individual generated. Things I would love to see:

- How the new individual fits into the population. What is the fitness difference to the pareto front? Did the new individual not even make the cut? If it did, what were the values of the individual purged from the population?
- How the next individual is constructed. What was the crossover result? Which parameter got mutated? To what?

Of course what makes sense for a sampler to report varies greatly.

### Alternatives (optional)

A user can piggyback the implementation to include the debug statements. they do not change the behaviour, they just tell whats going on. Of course the user then has to a) custom fork the installation and b) understand the sampler and its code in enough detail to know where to put the debug.

### Additional context (optional)

How I run my studies I would love if I could pass a logger instance to the sampler (why not the study?) and that logger instance would be used for the output.

**Comment by gen740** [comment]
Thank you for your nice feature request!
I'm afraid of that, but we are not willing to provide that feature.

If you want to visualize the internal state of the sampler, please fork optuna and implement it individually. FYI, there is a similar issue #3945, and there TPE sampler's visualization was implemented.

**Comment by simpsus** [comment]
Thank you for the feedback.
FWIW this is not about visualization. The linked issue is about sampler performance as well, but I would put my feature request as more basic. I simply want to know what the sampler it is doing so I can help it do it better. 

Let's be honest, a fork is not going to happen.

**Comment by simpsus** [comment]
closing as not planned
