### ISSUE TITLE
Avoid to use `verbose_eval` argument in LightGBM tuner.

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#4248]
### Motivation

`verbose_eval` argument is deprecated in LightGBM.

<img width="1549" alt="Screenshot 2022-12-16 9 57 44" src="https://user-images.githubusercontent.com/5564044/207998007-b7aa8898-7abe-4a72-87c5-a4ea67d16734.png">

https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/005_visualization.html#sphx-glr-tutorial-10-key-features-005-visualization-py

### Suggestion

> 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.

As the above deprecation message shows, we need to use `log_evaluation()` callback instead.

**Comment by eromoe** [comment]
+1, same problem

**Comment by nzw0301** [comment]
@eromoe Thank you for sharing the link! To be clear, the issue described in https://github.com/microsoft/LightGBM/issues/5241 has been resolved; you can disable the evaluation log correctly. The corresponding PR to this issue would affect only docstring.
