### ISSUE TITLE
"number" with FixedTrial might be useful

### ISSUE THREAD

**Issue by caprest** [optuna/optuna#426]
When testing optuna objective, `FixedTrial` are suggested to be used.
And, when saving machine learning models, `Trial.number` are suggested to be used to identify the trial.
However, `FixedTrial` don't have `number`/`trial_id` feature which prevents testing of objective.
Thus adding mock function of `number` might be helpful for testing.

**Comment by sile** [comment]
Thank you for your request.
We agree with your opinion and would like to add `number` method (property) to `BaseTrial` and `FixedTrial` classes.
(Conversely, `trial_id` property will be removed from `Trial` class in the future because the direct access to the ID by users is deprecated.)

**Comment by sile** [comment]
I added "contribution-welcome" label to this issue.
