### ISSUE TITLE
Allow the storage of any arbitary objects returned from tuning function

### ISSUE THREAD

**Issue by AnotherSamWilson** [optuna/optuna#4324]
### Motivation

Right now, Optuna expects only optimization metrics to be returned from the tuning function. However, for compute-intensive models that take several hours / days, it would be very advantageous to be able to save other objects as they are created, so they do not need to be re-created or serialized.

It looks like hyperopt has a similar capability:
https://stackoverflow.com/questions/54273199/how-to-save-the-best-hyperopt-optimized-keras-models-and-its-weights

### Description

In my internal pipelines, I have created a wrapper around Optuna that returns a dict of the following structure:
```
ret = {
    'metrics': (loss_1, loss_2)
    'model': model
    'cv_preds': cv_preds
}
```

The items in 'metrics' are optimized over, and have corresponding `direction(s)`, all other elements in the dict are stored. From there I can access these elements in my wrapper. Forgive me if this is already a feature - I searched for a while and couldn't figure out how to do this.

**Comment by not522** [comment]
I guess `trial.set_user_atter` is what you want. https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.Trial.html#optuna.trial.Trial.set_user_attr

**Comment by AnotherSamWilson** [comment]
Ahhh that is a much better solution (for me) than the one proposed in the docs:
https://optuna.readthedocs.io/en/stable/faq.html#how-to-save-machine-learning-models-trained-in-objective-functions

Wondering if `trial.set_user_atter` should be recommended in the docs instead of serialization. I guess it depends on the situation. Either way, it would probably be good to mention.
