### ISSUE TITLE
Allow using the original scientific functions from SciPy

### ISSUE THREAD

**Issue by Yura52** [optuna/optuna#4351]
### Motivation

In many practical scenarios:
- having scipy installed is a common thing for data science workflow
- scipy is imported by other packages anyway

### Description

In such cases, I would like Optuna to use the original implementations of scientific functions instead of custom reimplementations introduced in 3.1.0. Is it possible to add such a feature?

It could look something like this:

```
import optuna
optuna.use_scipy()
```

**Comment by nzw0301** [comment]
Could you explain why you would like to use scipy for TPE?
