### ISSUE TITLE
Enrich CLI documentation

### ISSUE THREAD

**Issue by cross32768** [optuna/optuna#4354]
### What is an issue?

In optuna v3.0.0, `optuna.cli` page has rich documentation: https://optuna.readthedocs.io/en/v3.0.0/reference/cli.html .
However, in optuna v3.1.0, `optuna.cli` page only has induction to `optuna help` command: https://optuna.readthedocs.io/en/stable/reference/cli.html .

This is a side effect of removing dependency to cliff in PR https://github.com/optuna/optuna/pull/4100 .
I propose to enrich CLI documentation again.

I consider to write CLI documentation by hand and create PR.

**Comment by gen740** [comment]
There is a nice [sphinx extension](https://sphinx-argparse.readthedocs.io/en/latest/).
