### ISSUE TITLE
Fix mypy errors when using SQLAlchemy v2.0.0.

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#4365]
### Motivation

Due to the 2nd major release of SQLAlchemy, mypy checks are failed. We added the version constraint at https://github.com/optuna/optuna/pull/4364 to avoid other PRs being blocked from merging.

### Suggestion

Fix mypy errors when using `SQLAlchemy==2.0.0` and remove a version constraint added at https://github.com/optuna/optuna/pull/4364/files.

### Additional context (optional)

See https://docs.sqlalchemy.org/en/14/changelog/migration_20.html for details.

**Comment by nielsuit227** [comment]
Could this be the reason for mypy to get stuck or am I experiencing a different issue?

e.g.
```
LOG:  Processing 4 queued fresh SCCs
LOG:  Processing SCC singleton (optuna.samplers._tpe._erf) as inherently stale --> does not finish
```

**Comment by nzw0301** [comment]
@nielsuit227 I couldn't reproduce it, so it is probably a different issue. 

```
- mypy: 0.991
- mypy-extensions: 0.4.3
- optuna: 3.1.0 and latest 
```

**Comment by nielsuit227** [comment]
Running the same versions, on Python 3.10.8. Problem occurs on the following minimal reproducable sample:
```python
import optuna

z = optuna.samplers.TPESampler()
```

**Comment by gen740** [comment]
Sqlalchemy does provide some [plugin](https://docs.sqlalchemy.org/en/20/orm/extensions/mypy.html) for better type checking. I suggest using (and modifying code with) this.

**Comment by Alnusjaponica** [comment]
@gen740 I afraid the the document you linked says the plugin is deprecated in SQLAlchemy 2.0.
> The SQLAlchemy Mypy plugin, while it has technically never left the “alpha” stage, should now be considered as deprecated in SQLAlchemy 2.0, even though it is still necessary for full Mypy support when using SQLAlchemy 1.4.
