### ISSUE TITLE
The suggest_uniform function may return -inf.

### ISSUE THREAD

**Issue by take0212** [optuna/optuna#4369]
### Expected behavior

The suggest_uniform function may return -inf.

### Environment

- Optuna version: 2.10.0
- Python version: 3.7
- OS: Windows 10
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

My code outputs [debug] or [error] lines.
sample1)

```shell
[debug]val1 : -27.920559913837096
[debug]val2 : range : -30.0 - -27.920559913837096
D:\****\lib\site-packages\optuna\samplers\_tpe\parzen_estimator.py:189: RuntimeWarning: invalid value encountered in add
  log_pdf = -0.5 * mahalanobis ** 2 + np.log(coefficient)
D:\****\lib\site-packages\optuna\samplers\_tpe\sampler.py:459: RuntimeWarning: invalid value encountered in subtract
  score = log_l - log_g
[error]val2 : -inf
```

sample2)

```shell
[debug]val1 : -29.24202198902026
[debug]val2 : range : -30.0 - -29.24202198902026
D:\****\lib\site-packages\optuna\samplers\_tpe\parzen_estimator.py:189: RuntimeWarning:

invalid value encountered in add

D:\****\lib\site-packages\optuna\samplers\_tpe\sampler.py:459: RuntimeWarning:

invalid value encountered in subtract

[error]val2 : -inf
```

### Steps to reproduce

Search two variables val1 and val2.

val1 is searched in the range from -30.0 to 30.0.
val2 is searched in the range from -30.0 to val1.

```python
val1 = trial.suggest_uniform('val1', -30.0, 30.0)
val2 = trial.suggest_uniform('val2', -30.0, val1)
```

If the suggestion of val1 is close to -30, val2 will be searched in the range from -30 to -30+delta.
In this case, optuna may suggest -inf.

### Additional context (optional)

Has the following problem already been known and fixed in the latest version?
I searched through the posts and found many posts about inf or -inf.
But I didn't find the problem.

Even if it has already been fixed in the latest version, is there any way to resolve it in version 2?

Since -inf is not expected for the value of val2, I replaced it with val1 and continued to execute.

But -inf was stored in the database (sqlite).
Subsequent trials may terminate with the error.

**error message**
```
Traceback (most recent call last):

...

  File "D:\****\lib\site-packages\optuna\study\study.py", line 409, in optimize
    show_progress_bar=show_progress_bar,
  File "D:\****\lib\site-packages\optuna\study\_optimize.py", line 76, in _optimize
    progress_bar=progress_bar,
  File "D:\****\lib\site-packages\optuna\study\_optimize.py", line 163, in _optimize_sequential
    trial = _run_trial(study, func, catch)
  File "D:\****\lib\site-packages\optuna\study\_optimize.py", line 264, in _run_trial
    raise func_err
  File "D:\****\lib\site-packages\optuna\study\_optimize.py", line 213, in _run_trial
    value_or_values = func(trial)

...

    val = trial.suggest_uniform(key, range[0], range[1])
  File "D:\****\lib\site-packages\optuna\trial\_trial.py", line 237, in suggest_uniform
    return self._suggest(name, distribution)
  File "D:\****\lib\site-packages\optuna\trial\_trial.py", line 720, in _suggest
    study, trial, name, distribution
  File "D:\****\lib\site-packages\optuna\samplers\_tpe\sampler.py", line 442, in sample_independent
    samples_below = mpe_below.sample(self._rng, self._n_ei_candidates)
  File "D:\****\lib\site-packages\optuna\samplers\_tpe\parzen_estimator.py", line 134, in sample
    random_state=rng,
  File "D:\****\lib\site-packages\scipy\stats\_distn_infrastructure.py", line 962, in rvs
    raise ValueError("Domain error in arguments.")
ValueError: Domain error in arguments.
```

I implemented the following codes, but it failed to update the database.

**code**
```Python
if val2 is float('-inf'):
    trial.params['val2'] = val1 # val2 cannot be updated.
    trial.storage._studies[next(iter(trial.storage._studies))].trials[trial.number].params['val2'] = val1 # val2 was updated. but actually database wasn't updated.
```

**log**

My code outputs [debug] or [error] lines.
sample1)

```
[debug]val1 : -27.920559913837096
[debug]val2 : range : -30.0 - -27.920559913837096
D:\****\lib\site-packages\optuna\samplers\_tpe\parzen_estimator.py:189: RuntimeWarning: invalid value encountered in add
  log_pdf = -0.5 * mahalanobis ** 2 + np.log(coefficient)
D:\****\lib\site-packages\optuna\samplers\_tpe\sampler.py:459: RuntimeWarning: invalid value encountered in subtract
  score = log_l - log_g
[error]val2 : -inf
[error]fixed val2 : -inf -> -27.920559913837096
[debug]trial.storage._studies[1].trials[264].params['val2'] : -27.920559913837096
[debug]trial.params['val2'] : -27.920559913837096
[debug]val2 : -27.920559913837096
```

sample2)

```
[debug]val1 : -29.24202198902026
[debug]val2 : range : -30.0 - -29.24202198902026
D:\****\lib\site-packages\optuna\samplers\_tpe\parzen_estimator.py:189: RuntimeWarning:

invalid value encountered in add

D:\****\lib\site-packages\optuna\samplers\_tpe\sampler.py:459: RuntimeWarning:

invalid value encountered in subtract

[error]val2 : -inf
[error]fixed val2 : -inf -> -29.24202198902026
[debug]trial.storage._studies[1].trials[277].params['val2'] : -29.24202198902026
[debug]trial.params['val2'] : -29.24202198902026
[debug]val2 : -29.24202198902026
```

**Comment by contramundum53** [comment]
Thanks for the bug report!
This bug doesn't reproduce in the master branch. Indeed, there had been some numerical instability issues with `TPESampler`, and it is now fixed in #3985.
As for the recovery, unfortunately you cannot update parameters once it is sampled. For existing trials, you could create a new study and copy all trials to fix `-inf` params (similarly to https://stackoverflow.com/questions/74907041/how-can-i-change-an-optunas-trial-result/74919486#74919486), but unfortunately it would be hard to avoid this problem in new trials without backporting #3985 to optuna 2.

**Comment by contramundum53** [comment]
If anyone came up with any idea to work around this bug in old Optuna's, sharing that workaround would be very appreciated!

**Comment by take0212** [comment]
Thank you very much for your prompt reply.
Thank you for the information that the bug has been fixed in the latest version.
I was not easily aware that #4105 was related to the bug.

I'll consider to upgrade to version 3.1.
Is there a list of upward incompatibilities from version 2 to version 3 anywhere?

I understand that the upgrade is the appropriate solution.
But I am concerned that if my code references unofficial optuna variables, the upgrade may cause problems.

In my experience, I can believe that upgrading to version 3.1 or higher is essential if the search scope becomes significantly narrower.

**Comment by nzw0301** [comment]
@take0212 https://github.com/optuna/optuna/discussions/3930

**Comment by take0212** [comment]
@nzw0301
Thanks for the information.
I will send the result of the verification once I upgrade.

**Comment by take0212** [comment]
I have upgraded optuna to version 3.1.0.
I did not have to modify any code to upgrade.
The bug has not recurred now.
Thank you for your support.
