### ISSUE TITLE
Long time running test of MySQL storage with server

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#4371]
### Expected behavior

Finish the test of `Tests (Storage with server)` with MySQL in several minutes. 

### Environment

- Optuna version: 22e57eba9cf1f352800b99d8d6c8a23c47bad239
- Python version: 3.9, 3.11 (as long as I see)
- OS: Ubuntu 22.0.4 in GitHub Actions
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
https://github.com/optuna/optuna/actions/runs/4039069661
```

### Steps to reproduce

Run a CI job `Test (Storage with server)`

**Comment by c-bata** [comment]
Fixed at #4386 and #4402.
