### ISSUE TITLE
Output installed packages in CIs

### ISSUE THREAD

**Issue by not522** [optuna/optuna#4396]
### Motivation

When debugging CI fails, the installed package versions are important information. This feature will introduce for Tests CI by #4381. This issue tracks remaining CIs.

- [ ] Checks (Integration)
- [x] Checks
- [x] Coverage
- [ ] Build Docker Image
- [x] ~Labeler~
- [x] mac-tests
- [ ] Performance benchmarks with bayesmark
- [ ] Performance Benchmarks with kurobako
- [ ] Performance Benchmarks with kurobako for multi-objective optimization
- [ ] Performance Benchmarks with NASLib
- [ ] Publish distributions to PyPI or TestPyPI
- [ ] Reviewdog
- [ ] Speed benchmarks
- [ ] Sphinx
- [x] ~stale~
- [ ] Tests (Integration)
- [ ] Tests (MPI)
- [ ] Tests (Storage with server)
- [ ] Tests with minimum versions
- [x] Tests

### Suggestion

See #4381 for expected implementation.

**Comment by Kaushik-Iyer** [comment]
Should I try to work on this issue?

**Comment by Kaushik-Iyer** [comment]
I am trying to do all the remaining tasks together

**Comment by Alnusjaponica** [comment]
I think #4445 wiped out the remaining tasks in is this issue

**Comment by not522** [comment]
I agree. Thank you for your contributions!
