### ISSUE TITLE
Mypy stuck on TPE sampler 

### ISSUE THREAD

**Issue by nielsuit227** [optuna/optuna#4404]
### Expected behavior

When running mypy on any script that imports optuna, mypy gets stuck (see logs below).

To reproduce:
```python
import optuna
```

Environment
MacOS Ventura 13.0.1
Python 3.10.8
Optuna 3.1.0
Mypy 0.991

### Environment

MacOS Ventura 13.0.1
Python 3.10.8
Optuna 3.1.0
Mypy 0.991

### Error messages, stack traces, or logs

```shell
LOG:  Metadata fresh for psycopg2._psycopg: file /opt/homebrew/Caskroom/miniforge/base/envs/amplo/lib/python3.10/site-packages/psycopg2-stubs/_psycopg.pyi
LOG:  Metadata fresh for psycopg2._ipaddress: file /opt/homebrew/Caskroom/miniforge/base/envs/amplo/lib/python3.10/site-packages/psycopg2-stubs/_ipaddress.pyi
LOG:  Metadata fresh for psycopg2._json: file /opt/homebrew/Caskroom/miniforge/base/envs/amplo/lib/python3.10/site-packages/psycopg2-stubs/_json.pyi
LOG:  Metadata fresh for psycopg2._range: file /opt/homebrew/Caskroom/miniforge/base/envs/amplo/lib/python3.10/site-packages/psycopg2-stubs/_range.pyi
LOG:  Could not load cache for sqlalchemy.connectors: sqlalchemy/connectors/__init__.meta.json
LOG:  Metadata not found for sqlalchemy.connectors
LOG:  Parsing /opt/homebrew/Caskroom/miniforge/base/envs/amplo/lib/python3.10/site-packages/sqlalchemy/connectors/__init__.py (sqlalchemy.connectors)
LOG:  Metadata fresh for psycopg2.sql: file /opt/homebrew/Caskroom/miniforge/base/envs/amplo/lib/python3.10/site-packages/psycopg2-stubs/sql.pyi
LOG:  Loaded graph with 673 nodes (1.277 sec)
LOG:  Found 228 SCCs; largest has 121 nodes
LOG:  Processing 168 queued fresh SCCs
LOG:  Processing SCC singleton (optuna.samplers._tpe._erf) as inherently stale
```

### Steps to reproduce

1. Install python, mypy, optuna
2. Run following code
```python
import optuna
```
3. Run mypy `mypy script.py -v`

### Additional context (optional)

Not sure if this belongs here or over at mypy, happy to close if you feel it belongs at mypy.

**Comment by not522** [comment]
I reproduce this error using NumPy 1.23.1. When I update NumPy to 1.23.2, mypy finishes successfully. I'm investigating what the difference is between the versions.

**Comment by not522** [comment]
I'm not confident, but NumPy's PR may have fixed the bug. Could you try the latest NumPy as a hotfix?
I'll try to support previous versions of NumPy.

**Comment by not522** [comment]
I wrote an issue for upstream. https://github.com/python/mypy/issues/14978
Thank you for your bug report!
