### ISSUE TITLE
Add a new index to the trials table

### ISSUE THREAD

**Issue by Ilevk** [optuna/optuna#4444]
### Motivation

I experienced bottleneck in using postgresql rdbstorage. 
may experience this problem if you access more than 100 sessions simultaneously. 
during training, rdb's cpu usage was maintained at 100%. (aws rds db.t4g.small)

### Description

A bottleneck occurs because an index is not created on the study_id of the trials table when rdbstorage is initialized. 

It seems that this is where the bottleneck occurs.
https://github.com/optuna/optuna/blob/ac169ea1c269dd1257816fd283736c1c467010e5/optuna/storages/_rdb/models.py#L345

by creating an index on study_id, the bottleneck was resolved (cpu util 100% -> 20~30%). 

can i contribute to this?

### Additional context (optional)

Decreased cpu usage, increased iops right after adding index

<img width="871" alt="cpu" src="https://user-images.githubusercontent.com/26380468/220133395-1c75407c-ca3c-4f55-9ea9-ae40e20edad6.png">

<img width="876" alt="iops" src="https://user-images.githubusercontent.com/26380468/220133449-ee268ab2-1a61-44be-a6e7-838bff1b0ba9.png">

**Comment by cross32768** [comment]
Thank you for finding the issue. Sure, your contribution is welcome.
