### ISSUE TITLE
Some tests assume that `datetime.now` is monotonic

### ISSUE THREAD

**Issue by gspr** [optuna/optuna#4455]
### Expected behavior

Even if `t_0 = datetime.now()` is executed first and `t_1 = datetime.now()` is executed later, one cannot assume that `t_0 < t_1`. This assumption seems to be used in various tests, e.g. `tests/storages_test/test_storages.py`:

```
assert all(
    time_before_creation < t.datetime_start < time_after_creation
    for t in trials
    if t._trial_id == trial_id and t.datetime_start is not None
)
```

Since the times involved are seemingly(?) set using `datetime.now`, and the clock used for that function is free to move backwards, this assertion can fail without anything being wrong with the tested code. 

Expected behavior would be that the test code does not fail due to behavior that is within specification.

### Environment

- Optuna version: 3.1.0
- Python version: 3.11.1
- OS: Linux-6.1.0-3-amd64-x86_64-with-glibc2.36

### Steps to reproduce

1. Run one of the affected tests.
2. Have the system clock run backwards between the call to `datetime.now()` that sets `time_before_creation` and the one that sets `time_after_creation`.
3. Observe a falsely failing test.

**Comment by cross32768** [comment]
By PR https://github.com/optuna/optuna/pull/4457,  a workaround with `time.sleep()` is considered to solve this problem.

**Comment by cross32768** [comment]
We would like to unify the place of discussion and would be happy to continue [here](https://github.com/optuna/optuna/issues/4460).

**Comment by gspr** [comment]
> By PR #4457, a workaround with `time.sleep()` is considered to solve this problem.

I would not say that it solves the problem. Rather, it works around a faulty assumption. As far as test code goes, that's not the end of the world. I'm more worried about the presence of similar assumptions in non-test code. But as you say, #4460 is the correct place to discuss that.

**Comment by not522** [comment]
@gspr Hi, thank you for your suggestion! Yes, as you pointed out, #4457 is not the solution, and the tests can fail if the system clock is modified.

I understand the current test is imperfect, but I want to keep it because of its simplicity. Of course, we cannot assume that `datetime.now` is monotone, which can cause the test to fail. However, the unit test is a development tool, and simplicity is also essential.

We already assume many things, e.g., the memory is enough, the process has permission to write files on storage, cosmic rays do not flip bits, etc. Even with these assumptions, the unit test works because these failures are rare or can be avoided by a developer.

I think the monotonicity of the clock can be one of these assumptions. Sometimes this assumption is broken, but it is not frequent.

The implementation of Optuna is a different problem from the tests. For example, `assert datetime_start <= datetime_complete` must not be in the implementation, but it is reasonable in the tests because of the above reason. Let's discuss it on #4460.

----

I expect non-monotonicity is not the cause of #4453 (I think the cause is that `time_before_creation` can be equal to `t.datetime_start`). Because the modification of the clock only occasionally occurs as far as I know. If my expectation is not true, please let me know.

**Comment by gspr** [comment]
> @gspr Hi, thank you for your suggestion! Yes, as you pointed out, #4457 is not the solution, and the tests can fail if the system clock is modified.
> 
> I understand the current test is imperfect, but I want to keep it because of its simplicity. Of course, we cannot assume that `datetime.now` is monotone, which can cause the test to fail. However, the unit test is a development tool, and simplicity is also essential.

Fair enough regarding the tests.

> We already assume many things, e.g., the memory is enough, the process has permission to write files on storage, cosmic rays do not flip bits, etc. Even with these assumptions, the unit test works because these failures are rare or can be avoided by a developer.

I disagree with the comparison with sufficient memory, permissions and bit flips. One can in principle tell the user "you need this much memory to run", "you need these permissions to those files". These are _reasonable_ requests. "Your system's wall time may never move backwards" is an _unreasonable_ request, as such an event is part of normal operations of system wall time – surely running Optuna shouldn't entail disabling NTP and kicking every other user with admin rights out of the system? (Cosmic ray bit flips are understood by everyone to be outside of the scope of responsibility of the software running in anything but life-critical systems.)

> I think the monotonicity of the clock can be one of these assumptions. Sometimes this assumption is broken, but it is not frequent.

I disagree. Nothing in the specification about the timekeeping device used says anything about how frequently time may or may not change backwards.

> The implementation of Optuna is a different problem from the tests. For example, `assert datetime_start <= datetime_complete` must not be in the implementation, but it is reasonable in the tests because of the above reason. Let's discuss it on #4460.

Agree.

> I expect non-monotonicity is not the cause of #4453 (I think the cause is that `time_before_creation` can be equal to `t.datetime_start`). Because the modification of the clock only occasionally occurs as far as I know. If my expectation is not true, please let me know.

Agree. I'm sorry for mixing up unrelated topics in these bugreports. I filed #4453 before seeing the other issues. I will try my best to keep these topics separate :-)

**Comment by not522** [comment]
Generally, there is no guarantee that tests are always passed, and specification is not a requirement of tests. For example, when `assert datetime_start <= datetime_complete` fails, it possibly reflects some bugs in the code. Of course, the specification says it can be `False` even for correct implementation, but it is a reasonable indicator of bug hunting. In this mean, testing `assert datetime_start <= datetime_complete` is helpful for developing.

**Comment by gspr** [comment]
Naoto Mizuno ***@***.***> writes:

> Generally, there is no guarantee that tests are always passed, and
> specification is not a requirement of tests.

Of course. But false positives like this (in the sense of falsely
failing when the code being tested works as intended) are bad and
diminish the value of the tests. A test that fails for seemingly random
reasons is one that is often ignored with "oh, that one again, let's
just skip it".

> For example, when assert datetime_start <= datetime_complete fails, it
> possibly reflects some bugs in the code. Of course, the specification
> says it can be False even for correct implementation, but it is a
> reasonable indicator of bug hunting.

I disagree. To me, it's a red herring – completely unrelated to the
Optuna code that is being tested. It's similar to
`if datetime.now().month == 2: assert(datetime.now().day <= 28)`
in that it adds a test that is (1) not testing anything code from or
assumption of Optuna, and (2) can fail under conditions that are within
normal operating specifications.

> In this mean, testing assert datetime_start <= datetime_complete is
> helpful for developing.

Of course, it's your codebase, so you are the one to decide what is
helpful for development :-)

But out of curiosity: How is it helpful?

**Comment by not522** [comment]
Fragile tests are not good, but in practice, the tests need to depend on unstable things, e.g., the unhealthy status of GitHub Actions, unstable network connection, and servers distributing datasets down. They are bad, but they do not spoil the test's usefulness.

Ah, I mean `assert trial.datetime_start <= trial.datetime_complete`. It's a reasonable indicator that these times are correctly recorded.

----

(below is maybe off-topic)
Generally, many things do not have specifications. For example, many of the math functions of NumPy have no requirements for accuracy, but nobody expects `numpy.sin(0) == 0.1` because it must be a sine function. We can write tests assuming that NumPy's math functions have good accuracy; nevertheless, it is undocumented and not specified.

**Comment by gspr** [comment]
Naoto Mizuno ***@***.***> writes:

> Fragile tests are not good, but in practice, the tests need to depend on unstable things, e.g., the unhealthy
> status of GitHub Actions, unstable network connection, and servers distributing datasets down. They are
> bad, but they do not spoil the test's usefulness.
>
> Ah, I mean assert trial.datetime_start <= trial.datetime_complete. It's a reasonable indicator
> that these times are correctly recorded.

Again: Why do you want *wall time* points to be "correctly ordered" when
any sensible, working, correct trial run may have either of:

 * trial.datetime_start < trial.datetime_complete
 * trial.datetime_start == trial.datetime_complete
 * trial.datetime_start > trial.datetime_complete

All of these potential orderings are "correct" if we talk about wall
time. The reasonable indicator that you're looking for is checking
*monotonic* time.

> Generally, many things do not have specifications.

Indeed. And then one shouldn't pretend that they do, nor should one make
tests that assume that they do. *Especially* not when there's a very
similar thing that *does* have the desired specifications, i.e. the
monotonic timekeeping facilities readily available in Python's standard
library!

> For example, many of the math functions of NumPy have no requirements for accuracy,

I don't know about "many", but *a lot* of them *do* have requirements:
https://ieeexplore.ieee.org/document/4610935

> but nobody expects numpy.sin(0) == 0.1 because it must be a sine function.

Sure, the mathematical definition of the sine function *for real
numbers* tells us that we can assume that sin(0) != 0.1. But since we're
talking about floating point numbers with finite precision here, we are
*not* doing computations on real numbers. We are doing computations on a
finite subset of the reals. In order to make sure that our assumptions
also hold in that setting, we must look at the specifications for the
setting. We know that NumPy uses the underlying C functions for
trigonometry, and we know that those are IEEE-754 compliant. Granted,
the standard does not *require* trigonometric functions to exist, but we
do know that our trigonometric functions follow the recommendation of
said standard. Therefore we know that the output of sin(0) is "correctly
rounded" (a technical term in the standard, essentially meaning it is
rounded to the nearest real value that is exactly representable). The
standard moreover tells us that the real number 0 is exactly
representable. The real number 0.1 is not exctly representable, but its
nearest representable real number is strictly greater than zero (it's
somewhere like one-billionth greater than 0.1 if I remember
correctly). Therefore we know that sin(0) != 0.1 holds also within this
finite precision system.

This is not by good fortune or by handwaving. It's by careful
standards-compliance.

> We can write tests assuming that NumPy's math functions have good
> accuracy; nevertheless, it is undocumented and not specified.

Simply not true. I would highly recommend

 https://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by not522** [comment]
Hmm, do you have any idea to check if these times are correctly recorded? If so, it is good to discuss improving tests by your way.

----

Oh, the sinc function is not a good example. (About ten years ago, I confirmed the sinc function actually has an error, but it may be improved.)
But how about `scipy.special` or `scipy.stats`? They include errors and Optuna tests with them (https://github.com/optuna/optuna/blob/master/tests/samplers_tests/tpe_tests/test_truncnorm.py). Is this ridiculous?

**Comment by gspr** [comment]
> Hmm, do you have any idea to check if these times are correctly recorded? If so, it is good to discuss improving tests by your way.

I would suggest something [like this](https://github.com/optuna/optuna/issues/4460#issuecomment-1443331759). I haven't contributed concrete code to solve the problem because I don't know how deeply engrained the wall times are in Optuna's on-disk files, and wouldn't wanna mess up something with regards to those.

> Oh, the sinc function is not a good example. (About ten years ago, I confirmed the sinc function actually has an error, but it may be improved.) But how about `scipy.special` or `scipy.stats`? They include errors and Optuna tests with them (https://github.com/optuna/optuna/blob/master/tests/samplers_tests/tpe_tests/test_truncnorm.py). Is this ridiculous?

I am not sufficiently well-versed in the details of `scipy.special` and `scipy.stats` to answer this, sorry.

**Comment by not522** [comment]
I cannot imagine that your approach works in the tests. For example, how to find the following bug?

```python
# datetime.utcnow() is wrong.
# datetime.now() or datetime.now(timezone.utc) is correct.
trial.datetime_start = datetime.datetime.utcnow()
```

More simply, how to test the following function?

```python
def get_current_datetime():
    return datetime.datetime.utcnow()
```

The behavior of this function is
```
>>> datetime.datetime.now()
datetime.datetime(2023, 3, 2, 9, 48, 49, 536968)
>>> get_current_datetime()
datetime.datetime(2023, 3, 2, 0, 48, 50, 482972)
>>> datetime.datetime.now()
datetime.datetime(2023, 3, 2, 9, 48, 51, 335047)
```

**Comment by gspr** [comment]
On March 2, 2023 1:49:55 AM GMT+01:00, Naoto Mizuno ***@***.***> wrote:
>I cannot imagine that your approach works in the tests. For example, how to find the following bug?
>
># datetime.utcnow() is wrong.

What does it mean for this function to be "wrong"? 

Do you mean that it returns something that isn't a valid datetime object? Ok, test for that (although it seems to me like that test is out of Optuna's scope, and rather in the scope of Python's own tests).

Or do you mean that it returns a datetime object that doesn't correctly represent the current date and time? This seems to imply that you want to test the computer's clock, and that definitely seems out of scope for Optuna (it's a daunting task to which entire software projects are devoted).

>More simply, how to test the following function?
>
>def get_current_datetime():
>    return datetime.datetime.utcnow()

That depends entirely on what properties you want this function to have! Reading from context, it seems like you want it to have at least the following two (but correct me if I'm wrong):

PROPERTY 1: The function returns, up to discretization error and some precision, the current wall clock time.

PROPERTY 2: A call to the function will return a value greater than or equal to that returned from an earlier call.

You cannot have both these properties, because wall time inherently does not have PROPERTY 2.

I therefore suggest you use two different timekeeping facilities: one like yours for when you want PROPERTY 1 (like when displaying wall times to a human user), and one that uses Python's monotonic clock functions whenever you need PROPERTY 2 (like for time ordering and the computation of durations and timeouts).

>The behavior of this function is
>>>> datetime.datetime.now()
>datetime.datetime(2023, 3, 2, 9, 48, 49, 536968)
>>>> get_current_datetime()
>datetime.datetime(2023, 3, 2, 0, 48, 50, 482972)
>>>> datetime.datetime.now()
>datetime.datetime(2023, 3, 2, 9, 48, 51, 335047)

This is an *example* of said function's behavior. An example is not sufficient to describe the behavior that you desire.

**Comment by not522** [comment]
OK, could you show an example test of PROPERTY 1?

**Comment by gspr** [comment]
>OK, could you show an example test of PROPERTY 1?

I don't think I can. I imagine it would require a quite complicated setup external to Optuna – at least an NTP client that is well-synchronized, or an atomic clock, or a GPS receiver with good view of the sky (and in the latter two cases also a human that certifies that leap seconds and similar have been accounted for, perhaps by human correspondence with the correct authority).

Luckily, it's out of scope for Optuna to be testing PROPERTY 1. All you (should) want a clock with PROPERTY 1 for is purely informational messages to the human user. You can then leave the assurance/testing of PROPERTY 1 up to the human user. It is not unreasonable to tell the user "if you want the logs to accurately reflect wall time, your system clock must be set correctly". In fact, even non-technical users probably implicitly accept this assumption every day. They don't expect the time displayed on the computer to be correct if the clock isn't set correctly.

**Comment by not522** [comment]
> Luckily, it's out of scope for Optuna to be testing PROPERTY 1. All you (should) want a clock with PROPERTY 1 for is purely informational messages to the human user. You can then leave the assurance/testing of PROPERTY 1 up to the human user. It is not unreasonable to tell the user "if you want the logs to accurately reflect wall time, your system clock must be set correctly". In fact, even non-technical users probably implicitly accept this assumption every day. They don't expect the time displayed on the computer to be correct if the clock isn't set correctly.


No, Optuna needs to test this property. Otherwise, we cannot say, "if you want the logs to accurately reflect wall time, your system clock must be set correctly". Without testing, even if the user's clock is correct, the time logged could be wrong by a buggy implementation.

**Comment by gspr** [comment]
> > Luckily, it's out of scope for Optuna to be testing PROPERTY 1. All you (should) want a clock with PROPERTY 1 for is purely informational messages to the human user. You can then leave the assurance/testing of PROPERTY 1 up to the human user. It is not unreasonable to tell the user "if you want the logs to accurately reflect wall time, your system clock must be set correctly". In fact, even non-technical users probably implicitly accept this assumption every day. They don't expect the time displayed on the computer to be correct if the clock isn't set correctly.
> 
> No, Optuna needs to test this property. Otherwise, we cannot say, "if you want the logs to accurately reflect wall time, your system clock must be set correctly". Without testing, even if the user's clock is correct, the time logged could be wrong by a buggy implementation.

By the same logic, you would be testing all manners of things that are completely outside the scope of Optuna. "In order to view output text, the user should select a different font color from the background color, otherwise they won't be able to see anything" – a completely reasonable requirement to put on the user, but by the same logic something that you would ideally want to go out and test, I presume? You're in for a *lot* of work!

But by all means, if you want to test the clocks of the user, I won't stop you :-)  But I would again emphasize the **huge importance of not testing for properties that a given mechanism isn't specified to have** (like you're currently doing when testing monotonicity of the wall clock). *That* is plain wrong, not just a bad choice.

**Comment by not522** [comment]
No, this test checks Optuna's implementation, not the user's setting. The document says `trial.datetime_start` is "Datetime where the Trial started". We need to test it.

**Comment by gspr** [comment]
> No, this test checks Optuna's implementation, not the user's setting. The document says `trial.datetime_start` is "Datetime where the Trial started". We need to test it.

Maybe I've misunderstood something, but `trial.datetime_start` is to a value returned by `datetime.now()`, is it not?

**Comment by not522** [comment]
It is not a specification. Currently, we implement it with `datetime.now`. But we can change it anytime because it is not a specification. The test should check the change is not buggy.
And, we possibly set the value at wrong timing, for example, "Datetime where the _Study_ started".

**Comment by gspr** [comment]
> It is not a specification. Currently, we implement it with datetime.now

OK, then what properties are you demanding that it has? This must be clear before you decide to test those properties!

>  But we can change it anytime because it is not a specification. The test should check the change is not buggy.

To make sense of what it would mean for "the change to be buggy", one needs to understand what properties are desired in the first place (i.e. to "not be buggy"). If we're talking about PROPERTY 1, then your current implementation is reasonable. However, any test of this property holding immediately becomes a test of whether `datetime.now` has the property. *That's* gonna be a daunting task, and I personally think you're gonna be biting over way too much if you start testing such properties of the underlying system. It's a reasonable requirement to just push onto the user. But by all means, if you want to do all that testing, go ahead (but the way you're doing it now is not correct – and doing it correctly would be a huge task).

>  And, we possibly set the value at wrong timing, for example, "Datetime where the Study started".

OK. But then the correct value has to be stored somewhere, and you just test for equality. This doesn't require any tests for the time being *correct*! That's vastly different from checking that the time was correctly *stored* and *not mixed up with other times*. Those things are good to be testing indeed, but are a completely different from testing whether the time itself is "correct".

**Comment by not522** [comment]
> OK, then what properties are you demanding that it has? This must be clear before you decide to test those properties!

I think your PROPERTY 1 is enough. It is not the same as Optuna's document. But users expect this property.

> To make sense of what it would mean for "the change to be buggy", one needs to understand what properties are desired in the first place (i.e. to "not be buggy"). If we're talking about PROPERTY 1, then your current implementation is reasonable. However, any test of this property holding immediately becomes a test of whether datetime.now has the property. That's gonna be a daunting task, and I personally think you're gonna be biting over way too much if you start testing such properties of the underlying system. It's a reasonable requirement to just push onto the user. But by all means, if you want to do all that testing, go ahead (but the way you're doing it now is not correct – and doing it correctly would be a huge task).

We can assume `datetime.now` is correct. But we cannot assume `trial.datetime_start` is correct.

> OK. But then the correct value has to be stored somewhere, and you just test for equality. This doesn't require any tests for the time being correct! That's vastly different from checking that the time was correctly stored and not mixed up with other times. Those things are good to be testing indeed, but are a completely different from testing whether the time itself is "correct".

I cannot understand what you want to say. Do you mean you can write some tests for this kind bug?

**Comment by gspr** [comment]
> > OK, then what properties are you demanding that it has? This must be clear before you decide to test those properties!
> 
> I think your PROPERTY 1 is enough. It is not the same as Optuna's document. But users expect this property.

Yeah, it is – as long as you don't use it to compute durations (as you currently do in several places in the code, but that's a separate issue, namely #4460 ).

> > To make sense of what it would mean for "the change to be buggy", one needs to understand what properties are desired in the first place (i.e. to "not be buggy"). If we're talking about PROPERTY 1, then your current implementation is reasonable. However, any test of this property holding immediately becomes a test of whether datetime.now has the property. That's gonna be a daunting task, and I personally think you're gonna be biting over way too much if you start testing such properties of the underlying system. It's a reasonable requirement to just push onto the user. But by all means, if you want to do all that testing, go ahead (but the way you're doing it now is not correct – and doing it correctly would be a huge task).
> 
> We can assume `datetime.now` is correct. But we cannot assume `trial.datetime_start` is correct.

OK. But I do not see how the tests that this bug report is about ensure that `trial.datetime_start` is correct either.

> > OK. But then the correct value has to be stored somewhere, and you just test for equality. This doesn't require any tests for the time being correct! That's vastly different from checking that the time was correctly stored and not mixed up with other times. Those things are good to be testing indeed, but are a completely different from testing whether the time itself is "correct".
> 
> I cannot understand what you want to say. Do you mean you can write some tests for this kind bug?

I don't know that I can. I'm just saying that there's a huge difference between "checking that the time is 'correct'" and "checking that it hasn't been mixed up with other times". The former is a gigantic task that I highly recommend that you do not attempt. That doesn't mean that I'm saying that you should test the latter – just that it makes a lot more sense than to test the former.

**Comment by not522** [comment]
OK, if you hit upon a good idea, please show it to me.

**Comment by gspr** [comment]
> OK, if you hit upon a good idea, please show it to me. I would like to see a concrete test.

Sure. But it's unlikely that I will. And at any rate: that's a different issue than #4455 (and the far more important #4460).
