### ISSUE TITLE
Code assumes `datetime.now` is monotonic

### ISSUE THREAD

**Issue by gspr** [optuna/optuna#4460]
### Expected behavior

Snippets like

```
time_start = datetime.datetime.now()
[…]
elapsed_seconds = (datetime.datetime.now() - time_start).total_seconds()
if elapsed_seconds >= timeout:
```
from optuna/study/_optimize.py worry me. The time reported by `datetime.now` is *not monotonic*. This means that there is no guarantee that `elapsed_seconds` is not negative. If `elapsed_seconds` is negative, timeouts will never occur.

The expected behavior is for elapsed time to be computed using monotonic timing facilities (for example [`time.monotonic_ns`](https://docs.python.org/3/library/time.html#time.monotonic_ns), because elapsed time is not something that depends on whatever the system calendar and clock are set to. It should only depend on the actual time elapsed, which is tracked by a monotonic clock.

### Environment

- Optuna version: 3.1.0
- Python version: 3.11.1
- OS: Linux-6.1.0-3-amd64-x86_64-with-glibc2.36

### Steps to reproduce

1. Use a positive timeout.
2. Move the system clock backwards between the two calls to `datetime.now` above.
3. Observe no timeout occurring.

### Additional context (optional)

I do not know how deeply engrained this use of "wall time" is in Optuna, but its use in computing timeouts is not appropriate. Nor is it appropriate to demand the kind of ordering of "wall" time points in tests (see #4455 and #4453).

**Comment by cross32768** [comment]
Thank you for pointing this out. We understand that this can be a problem when the system clock is intentionally rolled back. However, this seems to be a very special case. Could you think of a situation where this would be a problem if the user used Optuna in a normal way?

**Comment by gspr** [comment]
> However, this seems to be a very special case. 

Not at all. There is nothing in the specification of `datetime.now` or the backing "wall time" clock that guarantees that it never moves backwards between consecutive calls. It's not something you can rely on at all.

> Could you think of a situation where this would be a problem if the user used Optuna in a normal way?

The system administrator of a the system where a user runs Optuna can decide to set the clock backwards. Or the NTP daemon (or other timekeeping service) may decide to set the clock backwards. The latter can for example happen due to a hardware clock running fast (something that happens all the time), or due to the hardware clock having been set erroneously into the future by mistake at some point. All of these are within-spec operations that one must assume can happen, and do happen.

The correct way to handle this is to use monotonic timekeeping facilities, readily available on Python's standard library, whenever things involve measuring the time from one point in the code execution to another. This will give you the desired guarantees.

I'm happy to help with suggesting changes to the code, but I don't feel that I fully understand the way Optuna keeps track of time points when saving and loading trials.

**Comment by cross32768** [comment]
Thank you for your insightful comment. I understood that this is not such a special case problem, but a big problem depending on the environment. We would like to discuss this within the maintainer.

**Comment by gspr** [comment]
> Thank you for your insightful comment. I understood that this is not such a special case problem, but a big problem depending on the environment. We would like to discuss this within the maintainer.

Wonderful! In broad outlines, I'd suggest the following: Whenever you store time points where they are meant to be represented as a time and date for a human to read, use `datetime.now` as now. But whenever you need to compute durations based on those timepoints, then *also* store a monotonic time (from e.g. [`time.monotonic_ns`](https://docs.python.org/3/library/time.html#time.monotonic_ns) for use in the duration computation.

It is, for example, completely reasonable to report to a human something like
```
Trial start: 2023-02-24 10:12:05
Trial end: 2023-02-24 10:13:05
Trial duration: 25 minutes
```
even though the start and end times don't look like they're 25 minutes apart. The start and end times are whatever the wall clock showed at the start and at the end. The duration of the trial may well have been 25 minutes, and at some point someone set the clock back 24 minutes.
