### ISSUE TITLE
suggestion for "tell" without "suggest"

### ISSUE THREAD

**Issue by wen-zheng** [optuna/optuna#4467]
### Motivation

the current state/paradigm of optuna is:
1. suggest a parameter, then record its id
2. tell an objective value corresponding to this parameter (with its id) (or report a set of intermediate objective values with this id)

while this paradigm has some limits, for example, if I collect a set of trials from other hyper-tune systems not optuna, I cannot tell them to optuna directly (one indirect way is to write them to RDB in the same way that optuna uses)
,

### Description

as a system designer or user, I think the limit caused by "tell must after ask" can be removed because some use cases are possible (even common) as I pointed out above. 

### Alternatives (optional)

for RDB-cases implementation, one reasonable/efficient way to implement this feature is to write non-asked trials to RDB/internal storage in the same way that optuna uses currently. I think it is not difficult to implement non-RDB cases to use a similar method.

**Comment by wen-zheng** [comment]
if you think my proposal is reasonable, I can help to implement this feature

**Comment by nzw0301** [comment]
> if I collect a set of trials from other hyper-tune systems not optuna, I cannot tell them to optuna directly (one indirect way is to write them to RDB in the same way that optuna uses)

In fact, we can do that by using [`add_trials`](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.add_trials). So I'm not sure the necessity of the proposed feature.

**Comment by wen-zheng** [comment]
oh, I missed this api, thanks
