### ISSUE TITLE
Isolation of optuna integration modules.

### ISSUE THREAD

**Issue by gen740** [optuna/optuna#4484]
# Isolation of optuna integration modules.

Optuna is now isolating optuna.integration module to [optuna-integration](https://github.com/optuna/optuna-integration.git).
The following is a list of integration modules and their priorities.

| Status  | Module            | Priority             | Note              |
| ------- | ----------------- | -------------------- | ----------------- |
| Done| AllenNLP          | high                 | #4579|
| Done| BoTorch           | low |#5230|
| Done| Catalyst          | high                 | #4644|
| Done| CatBoost          | high                 |#5198|
| Done| Chainer           | high                 | #4497 </br> #4370 |
| Done| Dask              | low |#5222|
| Done| fast.ai           | high                 | #5120|
| Done| Keras             | high                 | #4558|
| Done| LightGBM          | low |   #5249  |
| Done| MLflow            | high                 |#5246|
| Done| Weights & Biases  | high                 |#5237|
| Done| MXNet             | high                 | #4790|
| Done| pycma             | high                 | #5236|
| Done| PyTorch(ignite)   | high                 | #5213|
| Done| PyTorch(lightning)| high                 | #5213|
| Done| PyTorch(ddp)      | high                 |  #5213|
| Done| scikit-learn      | low |  #5225|
| Done| scikit-optimize   | high                 |#5234|
| Done| SHAP              | low | #4791|
| Done| skorch            | high                 | #4663|
| Done| TensorBoard       | high                 | #5161|
| Done| TensorFlow        | high                 | #4666|
| Done| tf.keras          | high                 | #4662|
| Done| XGBoost           | high                 |  #5239|

**Do not migrate low-priority module** because it will have some complex dependencies on tests and others. (Migration of low-priority modules would be done by Committers.)

# Migration procedure
Following is the transfer procedure, please follow these instructions

## On the Optuna Integration side:
1. Clone the optuna-integration forked repository
`git clone git@github.com:{YOUR-FOR}/optuna-integration.git`
1. Add the Optuna master branch to the local upstream.
`git remote add upstream https://github.com/optuna/optuna.git`
1. Create the new working branch
`git checkout -b YOUR-BRANCH-NAME`.
1. Check out the relevant file for integration purposes.
`git fetch upstream` and `git checkout upstream/master -- <path/to/file>`
    - The desired files are as follows
        - `optuna/integration/<module>`
        - `tests/integration_tests/<module>`
    - Move the file paths from `optuna/integration/<module>` to `optuna_integration/<module>` and `tests/integration_tests/<module>` to `tests/<module>`.
    - Create a commit for each file, with a commit message that reads
      > "Fetched from https://github.com/optuna/optuna/commit/<commit-hash\>".
    - `<commit-hash>` can be obtained using `git rev-list upstream/master -- <path/to/file> | head -n 1`.
1. In the desired files, replace `optuna._imports` with `optuna_integration._imports`.
1. Update the required dependencies in pyproject.toml. Especially, please add the corresponding third party library in the `all` section of the pyproject.toml.
1. Modify the CI workflow file if necessary. Check the Optuna's CI workflow file of integration, i.e., `.github/workflows/tests-integration.yml`. If you find the any specific treatment for the modified integration, please add it to the optuna-integration's CI workflow file, i.e., `.github/workflows/tests.yml`. 
1. Update the imports in tests to use `optuna_integration` instead of `optuna.integration`.
1. Add the new module to `docs/source/reference/index.rst` (from [here](https://github.com/optuna/optuna/blob/master/docs/source/reference/integration.rst)).
1. Add the new module to the relevant section in `README.md`.
1. Change all `optuna.integration` sentences to `optuna_integration` (if they exist).

## On the Optuna side:

1. Import the package that was migrated from optuna_integration and pass its contents to `__all__` magic variable.
    - For example.
```python
from optuna_integration.chainer import ChainerPruningExtension


__all__ = ["ChainerPruningExtension"]
```
1. Remove the relevant files from `test/integration` and related imports from `test/integration/test_integration.py`.
1. Remove any relevant tests from `pytest tests -m "integration" --ignore` in `.github/workflows/tests-integration.yml`.
1. Remove the relevant documentation from `docs/source/reference/integration.rst`.
1. Remove the integration dependencies from `setup.py` and `pyproject.toml`, taking care not to remove dependencies that are still needed.
    - **Do not remove** the relevant imports from `_import_structure` variable in `optuna/integration/__init__.py`, as this would render the `from optuna.integration import ...` idiom unusable.
1. Transfer any relevant issues from Optuna to Optuna Integration.
1. Request that the author of any relevant PRs transfer them from Optuna to Optuna Integration.

**These changes should be merged into `optuna-integration` at first, then merged into `optuna`.**

## On the Optuna exmaple side:
1. Change the corresponding integration's ci yaml to install `optuna-integration`.

**Comment by toshihikoyanase** [comment]
I'm interested in isolation of `tf.keras`!

**Comment by GR-Menon** [comment]
Interested in isolation of fast.ai module

**Comment by sousu4** [comment]
It seems like there hasn't been much activity, so I'm considering working on the fast.ai module.

**Comment by HideakiImamura** [comment]
Great. Please go ahead.

**Comment by HideakiImamura** [comment]
I have updated the list. There are several integrations with high priority. If anyone has a motivation of this issue, please work on this.

**Comment by buruzaemon** [comment]
I learned about Optuna being the default hyperparameter_search backed in transformers.Trainer, and I am very impressed! I would like to help out by working on XGBoost bit of this migration, if no one else is doing so.
