### ISSUE TITLE
Allow optuna to know relationships between variables.

### ISSUE THREAD

**Issue by qzyu999** [optuna/optuna#4486]
### Motivation

Trying to optimize a function where each argument is sorted. That is, x1 > x2, x2 > x3, etc.

### Description

Allow optuna to know the relationship between variables. e.g., one is larger than the other.

**Comment by nzw0301** [comment]
Do you know any concrete algorithms (ideally described in reviewed papers) for such cases?

**Comment by contramundum53** [comment]
If the number of variables are not too many, one workaround is to `add_trial` all permutations with same value.

**Comment by contramundum53** [comment]
Actually, for multivariate TPE, supporting this feature is pretty simple: we simply need to sort variables internally.
However, it may be somewhat difficult to define an easy-to-use interface for it.
@qzyu999 Can you come up with a nice interface?
