### ISSUE TITLE
Allow early stopping in individual trials for reinforcement learning with Stable Baselines 3

### ISSUE THREAD

**Issue by Anth0rx** [optuna/optuna#4487]
### Motivation

Stopping trials early saves computational ressources and time. If an RL agent does not improve its rewards it makes sense to complete the trial, optimize the parameters and give it a new try.

### Description

In optunas example on RL it implements a [`TrialEvalCallback`](https://github.com/optuna/optuna-examples/blob/main/rl/sb3_simple.py#L78) class which inherits from stable-baselines3's  [`EvalCallback`](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/callbacks.py#L326) class.

Passing the `callback_after_eval` argument with [`StopTrainingOnNoModelImprovement`](https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/callbacks.py#L620) in the `super().__init__()` block does not stop the trial early, letting it run for the whole `N_TIMESTEPS`.

**Comment by nzw0301** [comment]
I'm not sure, but the issue is about optuna's RL example, not optuna feature.

**Comment by Anth0rx** [comment]
Should this issue be better placed in [optuna-examples](https://github.com/optuna/optuna-examples)?

**Comment by nzw0301** [comment]
I think https://github.com/optuna/optuna/discussions would be more appropriate.

**Comment by Anth0rx** [comment]
Okay, thanks. Closing in favor of discussion #4495
