### ISSUE TITLE
Support PyTorch 1.13

### ISSUE THREAD

**Issue by HideakiImamura** [optuna/optuna#4501]
### Motivation

Currently, PyTorch integration modules in Optuna rely on the PyTorch 1.11, but the latest PyTorch version is 1.13. I suggest to support PyTorch 1.13 in Optuna.

### Description

What we need to do is as follows.
- [ ] PyTorch DDP integration
- [ ] PyTorch-Ignite integration
- [ ] PyTorch-Lightning integration

**Comment by nzw0301** [comment]
FYI: allennlp might not support PyTorch 1.13.1; at least the installation failed in https://github.com/optuna/optuna/pull/4504.

**Comment by nzw0301** [comment]
FYI: PyTorch 2.0 has been released, https://pytorch.org/get-started/pytorch-2.0/.

**Comment by nzw0301** [comment]
Can we close this issue? PyTorch-Lightning integration support will be resolved via https://github.com/optuna/optuna/issues/4524.
