### ISSUE TITLE
Add tutorial for `JournalFileStorage`

### ISSUE THREAD

**Issue by contramundum53** [optuna/optuna#4502]
### What is an issue?

`JournalFileStorage` is easy to use (probably the easiest option for casual distributed optimization, and also for using `optuna-dashboard`), but it does not have any dedicated tutorial yet. 

We could add an entry under https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/index.html# that describes how `JournalFileStorage` can be used.

**Comment by not522** [comment]
Let me close this issue since it has been solved by #4980. Please feel free to reopen it if you have any remaining tasks.
