### ISSUE TITLE
FixedTrial can have an attached Study

### ISSUE THREAD

**Issue by lebigot** [optuna/optuna#4543]
### Motivation

Code can refer to a Trial's Study object. Logging the Study name is an example use case (where the model logs details in a place that includes the trial's study name).

Now, such code works when sending trials from a Study to the model, but not a FixedTrial.

### Description

The feature would allow the user to attach a Study to a FixedTrial.

The interface could be something as simple as `FixedTrial(…, study: Study)`.

### Alternatives (optional)

There are a couple of alternatives:

1. Every time we feed a FixedTrial to a model, we temporarily remove any reference to FixedTrial.study.name in it, and then put it back.
2. Better but not satisfactory: we monkey-patch `FixedTrial` and force `trial.study = optuna.create_study()`. This is more verbose, uses more memory (the `FixedTrial` is not freed, unlike in `loss(FixedTrial(…))`) and is potentially brittle (what if a `study` attribute is set in a future version of the module?).

**Comment by cross32768** [comment]
Thank you for your comment. As you said, it may be possible to refer to `Study` from `FixedTrial`, but it is not easy to change the design of Optuna for that purpose. Therefore, our basic policy is that we would like users  to apply workarounds like the one you mentioned as much as possible.

**Comment by lebigot** [comment]
Thank you for the feedback.

Now, out of curiosity, what is the difficulty with adding a `study` attribute to `FixedTrial`? I would naively had thought that it only meant adding one line in the initialization function (`self.study = study`).

**Comment by lebigot** [comment]
Can we leave this issue open? As it stands, it is not solved, right?

**Comment by contramundum53** [comment]
Thank you for creating the issue. 

> Now, out of curiosity, what is the difficulty with adding a study attribute to FixedTrial?

My personal opinion is that 
1. _requiring_ a study argument here is not good. This affects the widest usage to simply give a set of parameters to `FixedTrial`.
2. adding an optional `study` argument is not so much better than monkey-patching `FixedTrial`, because a `Trial` would have `study: Study` while a `FixedTrial` would have `study: Study | None` anyways. Compared to adding such a field, we might as well keep the object simpler.

**Comment by contramundum53** [comment]
But indeed it might be nice to have an official optional `study` argument. Let us consider this again when there are more people who want this feature.

**Comment by contramundum53** [comment]
By the way, even if we add `study` attribute some day, I personally don't think we will be breaking the code
```
fixed_trial.study = some_study
```
