### ISSUE TITLE
setting a user_attr on a study with a cvbooster from lgbm unrolls it to its constituent boosters

### ISSUE THREAD

**Issue by nitinmnsn** [optuna/optuna#4544]
### Expected behavior

When a ```cvbooster``` which is returned by the ```lightgbm.cv``` in case you set ```return_cvbooster``` to ```True``` is stored as a user attribute of the optuna study then it automagically unrolls to the list of its component booster objects. The ```cvbooster``` lightgbm object should be returned as is when requested back from the ```user_attrs```

### Environment

- Optuna version: 3.1.0
- Python version: 3.10.9
- OS: ubuntu 22.10
- lightgbm: 3.3.5

### Error messages, stack traces, or logs

```shell
NA
```

### Steps to reproduce

```
import pandas as pd
import numpy as np
import optuna
import lightgbm
from sklearn.datasets import make_classification

#creating dummy data
data = make_classification(n_samples = 12_000, n_features = 100, n_informative = 100, n_redundant = 0, 
                           flip_y=0.05,n_clusters_per_class=5,class_sep = 0.5)

#setting dummy column names
dt = pd.DataFrame(data[0],columns = [str(i) for i in range(data[0].shape[1])])
yt = pd.Series(data[1])

train_data = lightgbm.Dataset(dt,
                              label = yt)
#This is what it is
lgc = lightgbm.cv(params = {'n_estimators': 10, 'verbose':-1},train_set = train_data, return_cvbooster=True)
print(lgc['cvbooster']) 

#output : <lightgbm.engine.CVBooster object at 0x7f8f1a6bc460>


#This is what it becomes
_os = optuna.create_study(study_name = 'sample1')
_os.set_user_attr('cvb', lgc['cvbooster'])
print(_os.user_attrs) 

#output : {'cvb': [<lightgbm.basic.Booster object at 0x7f8f1a5b5270>, <lightgbm.basic.Booster object at 0x7f8f1a5b59c0>, <lightgbm.basic.Booster object at 0x7f8f1a5b5300>, <lightgbm.basic.Booster object at 0x7f8f1a380610>, <lightgbm.basic.Booster object at 0x7f8f1a3830a0>]}

```

**Comment by nzw0301** [comment]
I'm not sure this is a bug, but `copy.deepcopy` used in `study.user_attrs` transforms cvbooster into a list of boosters.

As a workaround, we can access `cvbooster` with `_os._storage._studies[0].user_attrs["cvb"]`.
