### ISSUE TITLE
Ability to add a note to a Study (through code)

### ISSUE THREAD

**Issue by lebigot** [optuna/optuna#4548]
### Motivation

The Optuna web interface allows a note to be attached to a study (when recorded in a database, at least). This is very useful for documenting key details about the study (changes made to the model…).

### Description

A note could be attached to a study, for example with `optuna.create_study(…, note=…)`.

The note would be accessible through `study.note`.

### Alternatives (optional)

I haven't been able to find any programatic alternative to adding a note to a study (besides going to the web interface).

**Comment by nzw0301** [comment]
How about https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.set_user_attr?

**Comment by lebigot** [comment]
That's a good point, thanks.

It's not ideal, because the result doesn't appear in the right place in the web interface (the dedicated Notes space) and the display is not as nice, but at least some information can be saved.

**Comment by not522** [comment]
Thank you for your feedback! I think what you are looking for is `optuna_dashboard.save_note`.

```python
import optuna
import optuna_dashboard

study = optuna.create_study(study_name="test", storage="sqlite:///test.db")
optuna_dashboard.save_note(study, "You can note it here!")
```

----

@c-bata Is it expected that users use `save_note`? Or is it an internal function?

**Comment by c-bata** [comment]
Yes, it is expected that users use `save_note` directly, not an internal function.

However, currently, notes can only be viewed on the web UI. I will provide a Python API like `get_note` in the next optuna-dashboard release.

**Comment by lebigot** [comment]
This is very useful, thanks a lot!

Maybe you already have this in mind, but I would suggest that the setting and getting the note be doable through a `Study` directly (with `optuna_dashboard` using this interface). In fact:

1. A note is logically attached to a study (and not to a dashboard).
2. A `Study` could have a note attached without having to add 2 lines as in the example above.

`study.set_note()` and `study.get_note()` would work, but so would the more pythonic following API:

1. `optuna.create_study(…, note=…)`
2. `study.note = …`
3. `print(study.note)`

`note` would be a Python `property`.

**Comment by c-bata** [comment]
Thank you for your feedback.

Since the Study class is a core component of Optuna, adding new methods and properties should be carefully considered. Providing note functionality from Optuna causes cross-referencing between Optuna and Optuna Dashboard. It would increase the complexity. It may reduce the two lines of Python code as you said, but it does not seem to be an advantage over these concerns.

Let me close this issue. Thank you again :100:

**Comment by lebigot** [comment]
Out of curiosity, I would love to understand why such precautions should be taken: I can't see this even with my 40 years of continuous practice of programming. :)

In the present case, adding an attribute to a `Study`, which is by definition not used anywhere yet, seems perfectly harmless to me.

Also, putting things where they logically belong actually _decreases_ complexity, in my eyes (a Study doesn't need a dashboard but can have a note attached, so any note should be attached to it or the logic of the code will not be obvious).

Just my 2 cents. :)

**Comment by not522** [comment]
We design Optuna to simplify core features and combine them to meet users' needs (like the Unix philosophy). So, `Study` has `user_attrs` and `system_attrs`, and `optuna_dashboard` uses them for the note.

**Comment by c-bata** [comment]
We believe that the interdependence of Optuna and Optuna Dashboard will increase complexity. We might consider porting the note functionality from Optuna Dashboard to Optuna, but this note functionality includes many features specific to Optuna Dashboard, including Markdown and Artifact support.

Also, the note functionality has been recently introduced. We are open to the possibility of removing it or introducing breaking changes in the future. We cannot easily introduce breaking changes to the Study class, which is a core component of Optuna.
