### ISSUE TITLE
Support NVIDIA H100 with pytorch-2.0

### ISSUE THREAD

**Issue by junjihashimoto** [optuna/optuna#4552]
### Motivation

Update pytorch version from 1.11 to 2.0 to support NVIDIA H100.

### Description

Supporting NVIDIA H100 requires cudatoolkit 11.8 or higher version.
https://docs.nvidia.com/deploy/cuda-compatibility/index.html

![image](https://user-images.githubusercontent.com/2469618/228143691-a362254f-d4c9-4b26-897c-96b466434164.png)

pytorch version 2.0 or higher is required, because cudatoolkit 11.8 is used from pytorch-2.
https://download.pytorch.org/whl/torch/

### Additional context (optional)

[allennlp](https://github.com/allenai/allennlp) becomes EOL.
https://github.com/optuna/optuna/pull/4504
Therefore we should remove allennlp's codes or replace it with something.

**Comment by nzw0301** [comment]
This issue is related to https://github.com/optuna/optuna/issues/4501

**Comment by nzw0301** [comment]
@junjihashimoto In my understanding, PyTorch 2.0 works with Optuna, so you don't need to wait for Optuna release if you can do ` --force-reinstall` for  PyTorch 2.0.
