### ISSUE TITLE
Update Dask integration to support `distributed>=2023.3.2`

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#4553]
### Motivation

`tests/integration/test_dask.py` failed after `distributed==2023.3.2` was released. Currently, #4545 pinned `distributed<=2023.3.2` in some CI settings to avoid the error.

The error message was as follows:

```console
FAILED tests/integration_tests/test_dask.py::test_study_optimize[inmemory] - assert 0 == 10                            
FAILED tests/integration_tests/test_dask.py::test_study_optimize[sqlite] - assert 0 == 10                              
FAILED tests/integration_tests/test_dask.py::test_study_direction_best_value[maximize] - KeyError: 'value'             
FAILED tests/integration_tests/test_dask.py::test_study_direction_best_value[minimize] - KeyError: 'value' 
```

I'm not familiar with Dask, but I guess we need to update the Dask integration to support the latest distributed.

### Description

1. Investigate the cause of the CI errors
2. Update the Dask integration or its corresponding test cases

**Comment by jrbourbeau** [comment]
@toshihikoyanase I took a pass at resolving this issue over in https://github.com/optuna/optuna/pull/4589. FWIW you (and other `optuna` maintainers) should feel free to ping me on any Dask-related breakages like this. I'll make sure that either I, or another Dask maintainer, helps provide guidance or a fix directly

**Comment by toshihikoyanase** [comment]
@jrbourbeau Thank you for your k

**Comment by toshihikoyanase** [comment]
@jrbourbeau Thank you always for your support. I'll make sure to mention you next time.
