### ISSUE TITLE
Adding pruning for multi-objective optimization

### ISSUE THREAD

**Issue by gitpeblo** [optuna/optuna#4563]
### Motivation

Optuna's constraints are only "soft" constraints.  That means that feasible solutions must be screened after the optimization has terminated.  

This may acceptable if the constraints are simple and few, but when they become numerous and complex (e.g. conditional --- see example below) they may dynamically restrict the search space severely.  The net result is that a disproportionate amount of trials have to be rejected in post-processing.  In some of my experiments I got to reject up to 99% of the trials!

### Description

One trick to avoid this post-processing is to prune the trials violating the constraints, so that at least the execution becomes faster and one can safely sample more points to compensate for the rejected trials.

The way to do this is to create a "ConstraintPruner" based on the `BasePruner` class, along these lines:

```
from optuna.pruners import BasePruner

class ConstraintPruner(BasePruner):
    def __init__(self, ...):
        pass
        
    def prune(self, study: "optuna.study.Study", trial: "optuna.trial.FrozenTrial") -> bool:
        
        conditions = []
        # list of booleans tracking which conditions have been satisfied
                
        # Assessing constraint 1:     
        conditions.append( trial.params['A'] >= trial.params['B'] )
        
        # Assessing constraint 2:     
        if trial.params['C'] == 'foo':
            conditions.append( trial.params['D'] <= trial.params['E'] )

        apply_pruning = not all(conditions)
        # does the current trial satisfy all constraints?        
        
        return apply_pruning

def objective_(...):     

    # Hard constraints via Pruner -------------------------------
    #   This is not supported for multi-objective optimization.
    if trial.should_prune():
        raise optuna.TrialPruned()    
    #-------------------------------------------------------------------------

    #   ... 

    return obj1, obj2
    # return a 2-valued objective
```

However, `trial.should_prune()` is not supported multi-objective optimization (I am using the TPE sampler, coudn't make the BoTorch work).

### Alternatives (optional)

I wonder whether it is possible to enable `trial.should_prune()` for multi-objective optimization.

**Comment by nzw0301** [comment]
Duplicated with https://github.com/optuna/optuna/issues/3450
