### ISSUE TITLE
Allow pruning in multi-objective optimization to implement hard constraints

### ISSUE THREAD

**Issue by gitpeblo** [optuna/optuna#4578]
### Motivation

To my knowledge, the only way to enforce **hard** constraints in multi-objective cases is to run the optimization, and --- only in post-processing --- remove the parameter suggestions that violated the constraints.

This is however not viable in case:
- there are many, restrictive constraints
- there are dynamical constraints e.g. of the type:
```
    if params['A'] > 10:
        c2 = params['B'] - params['C']
```

This is because one may end up with _way too many_ rejections.  In one of my optimizations, for example, I end up rejecting 95% of the cases. 
So the implication is that one has to schedule way more trials, hence making the computation much slower.

### Description

Optuna constraints are "**soft**" (i.e. they might be violated).  One could implement "**hard**" constraints via a "ConstraintPruner" based on the ``BasePruner`` class:

```
class ConstraintPruner(BasePruner):
    def __init__(...):
        ...
        
    def prune(self, study: "optuna.study.Study", trial: "optuna.trial.FrozenTrial") -> bool:
        
        conditions = []
        # list of booleans tracking which conditions have been satisfied
                
        conditions.append( params['A'] >= params['B'] )

        if params['A'] > 10:
             conditions.append( params['B'] <= params['C'])

        return not all(conditions) 
```
... and then calling the pruning inside the objective:
```
def objective_(trial, ...):     
    ...
    trial.should_prune()`
    ...

pruner = ConstraintPruner(...)
# defining pruner to reject configurations that violate constraints

study = optuna.create_study(directions=["minimize","minimize"], sampler=sampler, pruner=pruner)
```

This actually works fantastically for the single-objective optimization, but not for the multi-objective optimization shown above.
Specifically, the command that fails is the method: `trial.should_prune()`.

NOTE: `trial.should_prune()` fails when using the `TPE` sampler, I didn't manage to make the `BoTorch` sampler work, so no idea if the trick works with that.

### Alternatives (optional)

It would be enough to implement pruning for multi-objective optimizations.

Sure, one still has to schedule many more trials to compensate for the pruned ones, but at least the optimization is **much faster** (because the pruning happens _before_ suggesting the next configuration).

**Comment by nzw0301** [comment]
Duplicated with https://github.com/optuna/optuna/issues/3450
