### ISSUE TITLE
optuna.visualization.plot_param_importances ValueError

### ISSUE THREAD

**Issue by TTK95** [optuna/optuna#4583]
### Expected behavior

When I try the visualization function, it returns a ValueError

```
import optuna


def objective(trial):
    x = trial.suggest_int("x", 0, 2)
    y = trial.suggest_float("y", -1.0, 1.0)
    z = trial.suggest_float("z", 0.0, 1.5)
    return x ** 2 + y ** 3 - z ** 4


sampler = optuna.samplers.RandomSampler(seed=10)
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=100)

fig = optuna.visualization.plot_param_importances(study)
fig.show()
```

### Environment

- Optuna version: 2.10.1
- Python version: 3.10.4
- OS: Ubuntu 22.04.2 LTS
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 1.
```

### Steps to reproduce

1. try example code from docs
2. Error
```python
```
import optuna

def objective(trial):
    x = trial.suggest_int("x", 0, 2)
    y = trial.suggest_float("y", -1.0, 1.0)
    z = trial.suggest_float("z", 0.0, 1.5)
    return x ** 2 + y ** 3 - z ** 4

sampler = optuna.samplers.RandomSampler(seed=10)
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=100)

fig = optuna.visualization.plot_param_importances(study)
fig.show()
```
```

**Comment by TTK95** [comment]
I just switched from the default FanovaImportanceEvaluator to the MeanDecreaseImpurityImportanceEvaluator and it worked fine with it. But still, the default evaluator needs a fix please.

**Comment by nzw0301** [comment]
Could you try the same code with the latest Optuna? Optuna 2.10.1 is a little bit old.

**Comment by TTK95** [comment]
If I use the latest Optuna, I cant use the PyTorchLightningPruningCallback with Lightning 2.0.0. I found this working version and would like to use it until the latest Optuna version fixed this other issue.

**Comment by nzw0301** [comment]
Hmm. Please re-open the issue if the problem happens with the latest Optuna since this repo does not develop Optuna 2.x anymore.
