### ISSUE TITLE
Drop Python 3.7 Support

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#4586]
### Motivation

The end of life of python 3.7 is coming soon. Specifically, the date is `27 Jun 2023` according to https://endoflife.date/python. 

A few critical dependencies, such as Numpy and PyTorch, have already dropped support python 3.7, so at least the integration module requiring PyTorch would not work soon. 

### Description

I'd like to know the opinions from core-team's decision, so please replace this field to clarify the tasks to resolve this issue.

### Alternatives (optional)

- https://github.com/optuna/optuna/issues/3021
- https://github.com/optuna/optuna/issues/4484

**Comment by not522** [comment]
Thank you for your notification. For now, we continue to support Python 3.7 and do not force users to upgrade their Python. When it becomes a barrier to development, we will consider stopping support.

**Comment by c-bata** [comment]
We internally discussed this topic again and decided to run integration tests with Python 3.7 (refs #4784).
