### ISSUE TITLE
Leaked semaphore error causes optimize to quit

### ISSUE THREAD

**Issue by beyarkay** [optuna/optuna#4587]
### Expected behavior

Every now and again I get an error like:

```
Assertion failed: (tensor.NumElements() > 0), function mpsGraphTensorDataFromTensor, file mtl_ops_common.cc, line 411.
zsh: abort      python3 src/train.py
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

But it occurs erratically when I'm trying to optimise hyperparameters. I'm using Keras for my models, and pretty much have the recommended setup as per the docs:

```py
def main():
    study = optuna.create_study(
        direction="minimize",
        storage="sqlite:///db.sqlite3",
    )
    study.optimize(objective, n_trials=30)

def objective(trial):
    X_trn, X_val, y_trn, y_val = get_data()
    model = make_tensorflow_model(trial)
    model.fit(X_trn, y_trn)
    final_loss = model.history.history["loss"][-1]
    return final_loss

if __name__ == "__main__":
    main()
```

Here are the full logs: https://pastebin.com/d6npA1cK

### Environment

- Optuna version:3.1.0
- Python version:3.10.5
- OS:macOS-12.4-arm64-arm-64bit

### Error messages, stack traces, or logs

```shell
$ python3 src/train.py
[I 2023-04-07 11:51:43,964] A new study created in RDB with name: no-name-4efd55ee-70af-4ef8-a1ad-ad7349325ed6
...
[I 2023-04-07 12:09:34,868] Trial 25 finished with value: 0.08366470783948898 and parameters: {'batch_size': 64, 'learning_rate': 0.00026031489475980655, 'nodes_per_layer.1': 150, 'nodes_per_layer.2': 160}. Best is trial 25 with value: 0.08366470783948898.
2023-04-07 12:09:36.220599: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2023-04-07 12:09:36.240073: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Epoch 1/5
2023-04-07 12:09:49.211857: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
Assertion failed: (tensor.NumElements() > 0), function mpsGraphTensorDataFromTensor, file mtl_ops_common.cc, line 411.
zsh: abort      python3 src/train.py
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

full logs: https://pastebin.com/d6npA1cK
```

### Steps to reproduce

I'm not entirely sure how to reproduce this bug, but I'm getting it pretty frequently so I'm hoping it's a known issue and fixing it isn't too tricky?

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by beyarkay** [comment]
I'm attempting to reproduce the bug using a Colab notebook, I'll post here when I succeed.

**Comment by beyarkay** [comment]
Still struggling with reproducing the bug consistently, but I now think it might have to do with the size of my dataset. Additionally, I'm passing all my data (training and validation) through as a closure like so:

```py
    ...
    study.optimize(
        lambda trial: objective(trial, X_trn, y_trn, X_val, y_val)
    )


def objective(trial, X_trn, y_trn, X_val, y_val):
    ...
```

So I'm wondering if something funky is happening there, with the closure having to keep the data in memory (although it's not _that_ big, only about 50MB). I'll keep trying to get an actual example.

**Comment by beyarkay** [comment]
I'm unable to create a MWE which recreates the error, although I still have it happening to me just about every time I try to use optuna.

For now, I've managed to work around it by wrapping `study.optimize` in a for loop:

```py
n_trials = 10
for i in range(n_trials):
    study.optimize(
        lambda trial: objective_nn(trial, X_trn, y_trn, X_val, y_val),
        n_trials=1,
        gc_after_trial=True,
    )
```

And this seems to *hide* the error, at the very least.

**Comment by nzw0301** [comment]
Thanks. I suppose this might come from tensorflow, not optuna. For example, https://stackoverflow.com/questions/69026229/keras-tensorflow-suspected-memory-leak. `clear_session` might resolve the issue as in https://github.com/optuna/optuna-examples/blob/main/keras/keras_simple.py#L39.

**Comment by beyarkay** [comment]
Thanks! That worked perfectly. And I see that it's in the [keras example](https://github.com/optuna/optuna-examples/blob/main/keras/keras_simple.py#L39) as you mentioned, although not in the [keras code-examples docs](https://optuna.org/#code_examples).


Where is the source code for the website https://optuna.org/#code_examples? I'd like to submit a PR which adds a note about `clear_session`, what it does, and why it's necessary.

**Comment by nzw0301** [comment]
Glad to hear that! Thank you for your offer. The website's source code seems private, so we (including me) cannot send a pull request...

**Comment by beyarkay** [comment]
Pity. Okay, well I'll close this off as complete. Thanks for your help!
