### ISSUE TITLE
GridSampler suggests the same parameters multiple times for n_jobs > 1

### ISSUE THREAD

**Issue by davidpomerenke** [optuna/optuna#4627]
### Expected behavior

GridSampler should suggest each combination of parameters only once. When I have 8 parameter combinations and run 8 trials, all of them should be run.

This works for n_jobs=1, but does not consistently work for n_jobs > 1.

### Environment

- Optuna version: 3.1.1
- Python version: 3.10.9
- OS: MacOS 13.3.1 with Apple M1 chip
- (Optional) Other libraries and their versions:

### Problem description

The suggested parameter combinations appear to be random, also for the GridSampler.
When using just 2 parameters with 2 categorical values, the GridSampler will often suggest all correct 4 combinations, but occasionally it will repeat one of them, so that another one is omitted when only running 4 trials.
When more parameter combinations, it happens more often that at least one trial is repeated / omitted.

### Steps to reproduce

The following script will iterate through many random seeds, and for some of them, the set of suggested parameters will be smaller than the set of existing combinations, even though the number of trials is equal to the number of existing combinations.

The random seeds for which this behavior occurs are not consistent. This suggests that there is a hidden source of randomness that should either be removed or also be controlled by the seed.

```python
import optuna

def objective(trial):
    param_a = trial.suggest_categorical("param_a", [1, 2])
    param_b = trial.suggest_categorical("param_b", [3, 4])
    param_c = trial.suggest_categorical("param_c", [5, 6])
    return 0

search_space = dict(
    param_a=[1, 2],
    param_b=[3, 4],
    param_c=[5, 6],
)

optuna.logging.set_verbosity(optuna.logging.WARNING)

for seed in range(100):
    study = optuna.create_study(
        sampler=optuna.samplers.GridSampler(search_space, seed=seed)
    )

    study.optimize(
        objective,
        n_trials=8,
        n_jobs=8
    )
    n_unique_params = len(set([tuple(s.params.items()) for s in study.trials]))
    if n_unique_params != 8:
        print(f"{seed=} {n_unique_params=}")
        # print([s.params for s in study.trials])
```

The output for me is:

```
seed=1 n_unique_params=6
seed=17 n_unique_params=7
seed=18 n_unique_params=6
seed=21 n_unique_params=6
seed=23 n_unique_params=7
seed=27 n_unique_params=6
seed=33 n_unique_params=7
seed=36 n_unique_params=6
seed=39 n_unique_params=6
seed=47 n_unique_params=7
seed=52 n_unique_params=6
seed=53 n_unique_params=7
seed=56 n_unique_params=7
seed=57 n_unique_params=7
seed=59 n_unique_params=5
seed=67 n_unique_params=7
seed=70 n_unique_params=7
seed=80 n_unique_params=7
seed=85 n_unique_params=6
seed=86 n_unique_params=7
seed=89 n_unique_params=5
seed=90 n_unique_params=6
seed=91 n_unique_params=7
seed=94 n_unique_params=5
seed=99 n_unique_params=5
```

### Additional context (optional)

https://github.com/optuna/optuna/issues/2021 is possibly related, but is about samplers that should actually use randomness to some extent, while GridSampler should probably not.

**Comment by davidpomerenke** [comment]
I just figured there is also [BruteForceSampler](https://optuna.readthedocs.io/en/v3.1.0-b0/reference/samplers/generated/optuna.samplers.BruteForceSampler.html), for which this is not an issue and which is more suitable for my use case anyway!

Maybe it would be helpful to put a disambiguation into the documentation sites of both GridSampler and BruteForceSampler, and put a link to each other there.

**Comment by nzw0301** [comment]
Thank you for your suggestion In fact, the docs have already mentioned the grid-sampler's conflict behaviour, https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.GridSampler.html, so it would be great to suggest `BruteForceSampler` in the note of grid-sampler.
