### ISSUE TITLE
Option to change the name of a study.

### ISSUE THREAD

**Issue by seanswyi** [optuna/optuna#4639]
### Motivation

Sometimes I create studies with names that I want to change later without deleting everything. It would be nice to be able to do this. If there was a reason why this wasn't implemented, please let me know since I'm not 100% familiar with the framework yet.

### Description

Something like `optuna.study.update_study_name(study_name, storage)` to change everything.

**Comment by lashdk** [comment]
Couldn't find anything for renaming study without deleting and then creating new study with updated name. Let me know if the below workout works.

def update_study_name(
    *,
    from_study_name: str,
    storage: Union[str, storages.BaseStorage],
    to_study_name: Optional[str] = None,
) -> None:

    """Update study name in storage.

    The direction(s) of the objective(s) in the study, trials, user attributes and system
    attributes are preseved.

    .. note::
        :func:`~optuna.update_study_name` renames a study even if the optimization is working on.
        It means users will get a renamed study that contains a trial that is not finished.
        optuna.update_study_name uses optuna.copy_study and optuna.delete_study to update the study name.
        First optuna.copy_study is called with from_storage=storage and to_storage=storage and then 
        optune.delete_study is called with study_name=from_study_name and storage=storage.

    Example:

        .. testsetup::

            import os

            if os.path.exists("example.db"):
                raise RuntimeError("'example.db' already exists. Please remove it.")
            
        .. testcode::

            import optuna


            def objective(trial):
                x = trial.suggest_float("x", -10, 10)
                return (x - 2) ** 2


            study = optuna.create_study(
                study_name="example-study",
                storage="sqlite:///example.db",
            )
            study.optimize(objective, n_trials=3)

            optuna.update_study_name(
                from_study_name="example-study",
                storage="sqlite:///example.db",
                to_study_name="example-study-new-name",
            )

            study = optuna.load_study(
                study_name=example-study-new-name,
                storage="sqlite:///example.db",
            )

        .. testcleanup::

            os.remove("example.db")
         

    Args:
        from_study_name:
            Name of study.
        storage:
            Source database URL such as ``sqlite:///example.db``. Please see also the
            documentation of :func:`~optuna.study.create_study` for further details.
        to_study_name:
            New name of the study.

    Raises:
        :class:`~optuna.exceptions.DuplicatedStudyError`:
            If a study with a conflicting name already exists in the destination storage.

    """


    copy_study(from_study_name=from_study_name,from_storage=storage,
               to_storage=storage,to_study_name=to_study_name)
    
    delete_study(study_name=from_study_name,storage=storage)

**Comment by nzw0301** [comment]
It looks almost the same as https://optuna.readthedocs.io/en/stable/reference/generated/optuna.copy_study.html?

**Comment by lashdk** [comment]
I looked into this deeper and found this as an solution.   We will have add some kind of setter for the underlying storage objects (RDBStorage/ InMemoryStorage). Do you think doing this is worthwhile. I have checked this with In Memory study and RDBStorage study.


`def update_study_name(
        self, study_id: int, new_study_name: Optional[str] = None
    ) -> None:
 
        with _create_scoped_session(self.scoped_session,True) as session:      
            study = models.StudyModel.find_or_raise_by_id(study_id, session)
            old_study_name = study.study_name
            study.study_name = new_study_name
           
            _logger.info("Study name in RDBS changed from {} to {}".format(old_study_name,new_study_name))

`
