### ISSUE TITLE
Conditional slice/contour

### ISSUE THREAD

**Issue by vad0** [optuna/optuna#4645]
### Motivation

Current visualization options include slice and contour plots, which allow to look at the  objective as a function of given parameters. All other parameters can take any other values on these charts. However, this approach makes charts too noisy. It would be good to be able to plot variables A and B conditional on variables C=C0, D=D0, etc. It will allow to look at objective function in the vicinity of argmaximum. Or to have a feature flag F={F0, F1} and look at Objective(X|F=F0) and Objective(X|F=F1) separately.

### Description

Current visualization options include slice and contour plots, which allow to look at the  objective as a function of given parameters. All other parameters can take any other values on these charts. However, this approach makes charts too noisy. It would be good to be able to plot variables A and B conditional on variables C=C0, D=D0, etc. It will allow to look at objective function in the vicinity of argmaximum. Or to have a feature flag F={F0, F1} and look at Objective(X|F=F0) and Objective(X|F=F1) separately. If F is continuous variable, then I would like to specify a range for it to be able to look at Objective(X|F>=F0 && F<=F1). It can be done either 1) by filtering all observations which don't meet the given filter or 2) by using all observations to fit the Gaussian model, but plot contour after conditioning it on selected variable F.

### Alternatives (optional)

One can manually run separate studies with fixed parameters F=F0 and F=F1 and look at the corresponding slices Objective(X|F=F0) and Objective(X|F=F1). But his is inconvenient, especially if there are several categorical variables.

**Comment by nzw0301** [comment]
Thank you for your feedback. Conditional plots can be done by using a few Optuna API calls as follows:

```python
import optuna


def objective(trial):
    x = trial.suggest_float("x", -100, 100)
    y = trial.suggest_categorical("y", [-1, 0, 1])
    return x ** 2 + y


sampler = optuna.samplers.TPESampler(seed=10)
study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=20)

for conditional_y in [-1, 0, 1]:
    
    trials = [t for t in study.trials if t.params["y"] == conditional_y]
    conditional_study = optuna.create_study()
    conditional_study.add_trials(trials)

    fig = optuna.visualization.plot_slice(conditional_study, params=["x"])
    fig.show()
```

I believe that this is simpler than `Alternative` you describe.

**Comment by vad0** [comment]
Yes, makes sense, thank you.
