### ISSUE TITLE
Why Optuna's suggest categorical params are not logged and shown in the UI?

### ISSUE THREAD

**Issue by mikolajkania** [optuna/optuna#4648]
### Expected behavior

Hello guys, I have a burning question. I am running Optuna with wandb and values from _suggest_categorical_ are not logged and shown in the UI.

### Environment

- Optuna version: 3.1.0
- Python version: 3.10.8
- OS: WSL on Windows
- (Optional) Other libraries and their versions: wandb==0.13.10

### Error messages, stack traces, or logs

```shell
_Selected runs are not logging media for the key binary, but instead are logging values of type number.
If binary is never supposed to be a media type, please delete this panel and create the proper panel type manually._
```

### Steps to reproduce

Let take this as an example. Binary won't be visible, but min_df - will be:
![obraz](https://user-images.githubusercontent.com/14984193/235795364-91a63c02-e0a1-4867-b69d-3430e8b85337.png)

For binary I am getting such mesage:
![obraz](https://user-images.githubusercontent.com/14984193/235795477-c89ad15b-4fcf-4281-ab65-245ab425a6b9.png)

It happens with every _suggest_categorical_ parameter I tried (both string and bool) and it is very annoying, as values like binary for sklean vectorizers is a big tuning option. How to fix that?

Example code:

```
def objective(trial):
    params = {
        'vectorizer': {
            'name': 'tfidf',
            'params': {
                'binary': trial.suggest_categorical('binary', [True, False]),
                'min_df': trial.suggest_int('min_df', low=0, high=100, step=5)
            }
        }
    }

    X_train, X_val, _, y_train, y_val, _ = loading(split_train_val=True)
    vectorizer, X_train_vec, X_val_vec, _ = vectorization(params, X_train, X_val=X_val)
    model = training(params, X_train_vec, y_train)
    _, val_f1_score = evaluate(model, X_val_vec, y_val)
    return val_f1_score

def run(config: dict = None, params: dict = None) -> None:
    wandbc = WeightsAndBiasesCallback(metric_name='val_f1')
    print('Starting optuna...')
    study = optuna.create_study(direction='maximize')
    study.optimize(objective, n_trials=3, callbacks=[wandbc])

```

### Additional context (optional)

I can ommit this issue by custom code in the objective method:

```
trial_params = dict(trial.params)
wandb.log(data={"vec_binary": int(trial_params['binary'] == True)}, step=trial.number)
```
I need to manually replace it with ints. It is a pitty, as I can find string names on many charts.

**Comment by nzw0301** [comment]
> suggest categorical params are not logged

Actually, the variables are stored in the wandb at least my wandb UI. As you reported, the visualisation doesn't show correctly, but it would be the wandb issue, not Optuna. So let me close this issue.
