### ISSUE TITLE
condtional objective function

### ISSUE THREAD

**Issue by saeedadnan** [optuna/optuna#465]
First of all, a nice and easy to implement library. Thanks.
I tried to use optuna for hyperparameters optimization but my objective function has a condition like as under
def ojective(trial):
pinrw = ...
picp =...
if picp>a and pinrw <b
cwc = ....
return cwc

so my objective function needs to be calculated only if the condition is met. otherwiswe go for next trial.
so how to deal with this.

**Comment by saeedadnan** [comment]
i used a code like shown below:

define objective (trial):
    k_dis = trial.suggest_uniform('k_dis', 0.0, 5.0)
    l_dis = trial.suggest_uniform('l_dis', 0.0, 5.0)
    k_bound = trial.suggest_uniform('k_bound', 0.0, 5.0)
    l_bound = trial.suggest_uniform('l_bound', 0.0, 5.0) 

    picp = .....
    pinrw = .....


    if picp_train >= 0.8 and pinrw_train < 0.18: 
        cwc_train = fc.CWC_proposed(predict_bound_train, Y_train)
    else:
        print("error = ")
    return  cwc_train
study = optuna.create_study()
study.optimize(objective, n_trials=100)


it gives error

UnboundLocalError: local variable 'cwc_train' referenced before assignment

**Comment by toshihikoyanase** [comment]
Thank you for your question.
Your example code seems to be a kind of constrained problems. In that case, you can return very large values or raise `TrialPruned()` if the constraint is not satisfied.

(1) return large values to notify such parameters are bad solutions (if you want to maximize the objective value, please return small values like `-float(‘nan’)`).

```python
if picp_train >= 0.8 and pinrw_train < 0.18: 
    cwc_train = fc.CWC_proposed(predict_bound_train, Y_train)
    return cwc_train
return float('inf')
```

(2) raise TrialPruned to ignore such parameters. Note that the default sampler (TPESampler) has a mechanism to avoid to sample such parameters again:
```python
if picp_train >= 0.8 and pinrw_train < 0.18: 
    cwc_train = fc.CWC_proposed(predict_bound_train, Y_train)
   return cwc_train
raise TrialPruned()
```

**Comment by saeedadnan** [comment]
Thanks for a quick response,

this is my first optimization task, I am a Ph.D. scholar and I am looking
forward to optimizing the model for best results. So i get really motivated
reading about the Trial Pruned feature of optuna. But to my experience, it
is not working for me. I did as per your suggestion. But it didn't work. I
am showing you some screenshots of the different ways I tried in this
direction.

About the first method of returning a higher value so that optuna try to
optimize it. (The image named error1 belongs to this). It keeps giving the
best value as inf even after 26 trials and keeps repeating the same
parameters.

About the second case of raising Trial Pruned. I read the Optuna documents,
but get a little confused as I don't have much experience, sorry about that
i am new to deep learning. Anyways i tried whatever I read.
There were some confusions,
1. There was some theory on step. I wasn't able to understand that when we
have already given n_trials then what is the significance of step in the
middle of the training.
2. Pruning callbacks. I read about Median callbacks. so I thought that I
can mix your two suggestions, that I can give a higher value for the
unwanted case and use a Median callback so that after some trials it start
pruning the incepted bad results. That too didn't work.
3. I simply raised Trial Pruned(). It keeps giving Trial Pruned not defined.

I have attached the relevant images. The images with name tags untitled
belong to my efforts with pruning.


Let me explain my aim in detail so that you can help in a better way. My
model is to predict intervals for wind forecasts. So after some LSTM and
dense layers it gives two values for the interval bounds. Then with those
four parameters it check whether the value lies in the bound. if not,
adjustments in the bound are done based on those parameters.

Hoping for some suggestions

Thanks and Regards

**Comment by sile** [comment]
Thank you for your detailed explanation, but I cannot find your screenshots (there are no images or URLs in your comment).

> 3. I simply raised Trial Pruned(). It keeps giving Trial Pruned not defined.

The full path of `TrialPruned` is  [`optuna.structs.TrialPruned`](https://optuna.readthedocs.io/en/stable/reference/structs.html#optuna.structs.TrialPruned), so you can raise the exception as follows:
```python
raise optuna.structs.TrialPruned()
```
or 
```python
from optuna.structs import TrialPruned

raise TrialPruned()
```

**Comment by toshihikoyanase** [comment]
Thank you for sharing detailed information. As @sile mentioned, I also cannot find your images. But I think I can find some clues to solve the problem.

> About the first method of returning a higher value so that optuna try to optimize it.
> It keeps giving the best value as inf even after 26 trials 

At the beginning of optimization, randomness greatly affects the optimization performance of Optuna. So, it may be difficult for Optuna to find feasible solutions (i.e., parameters which satisfies the bound) with a small number of trials like 20 or 30. You may be able to find feasible solutions if you increase the number of trials.
 
And also, I created a workaround that may accelerate the optimization. The idea is to use the difference between the metric value and the threshold as a penalty.  Using the penalty values, Optuna can find which parameters are better even if all of them are infeasible (i.e., pruned trials).

```
def objective_penalty(trial):
    # This is just a toy problem. I assume that all metrics (i.e., picp_train, pinrw_train and cwc_train)
    # are directly sampled by Trial.suggest_unifrom() for simplicity.
    picp_train = trial.suggest_uniform('picp', 0, 1)
    pinrw_train = trial.suggest_uniform('pinrw', 0, 1)
    
    if picp_train >= 0.8 and pinrw_train < 0.18: 
        cwc_train = trial.suggest_uniform('cwc', 0, 1)
        return cwc_train

    # Calculate the penalty.
    penalty = 0
    if picp_train < 0.8:
        penalty += 0.8 - picp_train
    if pinrw_train >= 0.18:
        penalty += pinrw_train - 0.18
    trial.report(penalty, 0)
    
    # Prune trial to notify that the parameters are infeasible.
    raise optuna.structs.TrialPruned()
```

I made a comparison, and it shows that the workaround may increase the probability of successful studies (i.e., the study which has at least one feasible trial) by about 40 percentage points compared with the objective function that simply raises `TrialPruned` without the penalty. 

![image](https://user-images.githubusercontent.com/3255979/62413155-6f6f2900-b647-11e9-94f3-9898db840779.png)

For further details, please take a look at the following notebook:
https://colab.research.google.com/drive/1NrSgJ7r6r1e5aiTJz4Nh7e1GOMwS90el#scrollTo=QqYHVS13CR_g

I hope the workaround will help you solve the problem.

**Comment by saeedadnan** [comment]
Good Morning,

Thanks for making efforts to help me out. I tried your suggestions, but
it's not working. I tried three times by reducing the constraints even then
it reports no trial completed. Every time I run for 100 trials.

So, I suppose that this is due to my inexperience in deep learning.  I
believe there might be some problem with my metrics definition. I am
sharing you my code with a belief that you might suggest me a method to
define a new metrics so that I may even don't require to prune the trials.

The basic idea is to predict wind forecasting intervals. I took a BLSTM
model in the framework of LUBE model. It predicts two bounds. Then I define
a distance evaluate layer to check the distance between the center of bound
and the true value and then try to adjust the bound based on that. The
hyperparameters I am trying to optimize are related to those two layers '
distance layer' and 'bound layer'

I have attached the files. File Named
'lstm_interval_loss_constructed_predict' is my original code which I run 10
times for taking an average.
File named 'lstm_interval_loss_Optuna_Optimization' is the code i modified
to optimize the hyperparameters.

Thanks and Regards

**Comment by toshihikoyanase** [comment]
> I have attached the files.

I'm sorry but I cannot find your files again.
I'm not sure, but I think you replied to the issue via email, and the attached files were removed during the conversion process from the email to the GitHub issue.

If so, could you use [GitHub Web UI](https://github.com/pfnet/optuna/issues/465) to reply to this message, please? Please refer to [this page](https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests) to attach files to the issue via Web UI.

**Comment by toshihikoyanase** [comment]
Let me close this issue since there are no activities for several months. Feel free to reopen or create a new issue if you have any problems.
