### ISSUE TITLE
Allow reporting for multi-objective studies

### ISSUE THREAD

**Issue by raquelhortab** [optuna/optuna#4650]
### Motivation

I'm using optuna-dashboard, which is a really useful tool and I really think it'd be very useful to be able to use the report function even if we are running a multi-objective study. 
Even if it does not work for pruners but only for visualising the value(s) on the dashboard.

### Description

We would be able to report intermediate values at the end of each epoch so plots can be created

### Alternatives (optional)

Even if it is too difficult to implement multi-objective pruners, this could be useful even if it was only to be able to display plots of the process

**Comment by nzw0301** [comment]
Thank you for your feature request. It sounds duplicated with https://github.com/optuna/optuna/issues/3450.

**Comment by raquelhortab** [comment]
you are right! sorry
