### ISSUE TITLE
PQ enum type `TrialValueType` is not comparable with `varchar`

### ISSUE THREAD

**Issue by daskol** [optuna/optuna#4653]
### Expected behavior

With PostgreSQL 14/15 RDBS as a storage backend, it is impossible to perform hyperparameter optimization. The issue is that `optuna` uses enum types which should be explicitely casted to `varchars`.

### Environment

Failed on PQ 14/15.

### Error messages, stack traces, or logs

```shell
sqlalchemy.exc.ProgrammingError: (psycopg.errors.UndefinedFunction) operator does not exist: trialvaluetype = character varying
LINE 3: ...$3::INTEGER ORDER BY CASE trial_values.value_type WHEN $4::V...
                                                             ^
HINT:  No operator matches the given name and argument types. You might need to add explicit type casts.
[SQL: SELECT trials.trial_id AS trials_trial_id, trials.number AS trials_number, trials.study_id AS trials_study_id, trials.state AS trials_state, trials.datetime_start AS trials_datetime_start, trials.datetime_complete AS trials_datetime_complete 
FROM trials JOIN trial_values ON trials.trial_id = trial_values.trial_id 
WHERE trials.study_id = %(study_id_1)s::INTEGER AND trials.state = %(state_1)s AND trial_values.objective = %(objective_1)s::INTEGER ORDER BY CASE trial_values.value_type WHEN %(param_1)s::VARCHAR THEN %(param_2)s::INTEGER WHEN %(param_3)s::VARCHAR THEN %(param_4)s::INTEGER WHEN %(param_5)s::VARCHAR THEN %(param_6)s::INTEGER END ASC, trial_values.value ASC 
 LIMIT %(param_7)s::INTEGER]
[parameters: {'study_id_1': 1, 'state_1': 'COMPLETE', 'objective_1': 0, 'param_1': 'INF_NEG', 'param_2': -1, 'param_3': 'FINITE', 'param_4': 0, 'param_5': 'INF_POS', 'param_6': 1, 'param_7': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
```

### Steps to reproduce

Just use PostgreSQL 14/15 instead of 10 as in your CI.

### Additional context (optional)

It is worth to note that `optuna` overrides a db driver exception with something senseless.

```
optuna.exceptions.StorageInternalError: An exception is raised during the commit. This typically happens due to invalid data in the commit, e.g. exceeding max length. 
```

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by daskol** [comment]
Sorry, but no. I've spent half a day to find work around or solve the issue. It seems that fix introduced in #4422 does not work for newer PSQL. The bug was introduced in v3.1.1. In branch v3.1.0 everything works fine. It seems that other versions (e.g. v3.0.6) are buggy as well. This is kind of floating bug with keeping #4420 in mind.

**Comment by c-bata** [comment]
@daskol Thank you for your report!

I tried to reproduce the problem with PostgreSQL v15.2, but found no issues.

```
$ docker run -d --rm --platform linux/amd64 -p 5432:5432 -e POSTGRES_USER=root -e POSTGRES_PASSWORD=root -e POSTGRES_DB=optuna --name optuna-postgres postgres:15
$ cat example.py
import optuna

def objective(trial: optuna.Trial) -> float:
    x = trial.suggest_float("x", -10, 10)
    return x ** 2

if __name__ == '__main__':
    study = optuna.create_study(storage="postgresql+psycopg2://root:root@127.0.0.1/optuna")
    study.optimize(objective, n_trials=100)
    print(study.best_trial)

$ python example.py
[I 2023-05-08 10:08:48,713] A new study created in RDB with name: no-name-9928f092-7af3-4482-923c-30755b3ebcec
[I 2023-05-08 10:08:48,808] Trial 0 finished with value: 42.396053677841124 and parameters: {'x': -6.51122520558467}. Best is trial 0 with value: 42.396053677841124.
[I 2023-05-08 10:08:48,849] Trial 1 finished with value: 1.0035347584146774 and parameters: {'x': 1.001765820146943}. Best is trial 1 with value: 1.0035347584146774.
[I 2023-05-08 10:08:48,891] Trial 2 finished with value: 0.38741646241748234 and parameters: {'x': -0.6224278772817637}. Best is trial 2 with value: 0.38741646241748234.
[I 2023-05-08 10:08:48,931] Trial 3 finished with value: 75.59820724281214 and parameters: {'x': -8.69472295376984}. Best is trial 2 with value: 0.38741646241748234.
...

$ docker exec -it fa674cd13cdf bash
root@fa674cd13cdf:/# psql optuna
psql (15.2 (Debian 15.2-1.pgdg110+1))
Type "help" for help.

optuna=# select * from studies;
 study_id |                  study_name
----------+----------------------------------------------
        1 | no-name-9928f092-7af3-4482-923c-30755b3ebcec
(1 row)

optuna=# select * from trials;
 trial_id | number | study_id |  state   |       datetime_start       |     datetime_complete
----------+--------+----------+----------+----------------------------+----------------------------
        1 |      0 |        1 | COMPLETE | 2023-05-08 10:08:48.731837 | 2023-05-08 10:08:48.770278
        2 |      1 |        1 | COMPLETE | 2023-05-08 10:08:48.81335  | 2023-05-08 10:08:48.830148
       46 |     45 |        1 | COMPLETE | 2023-05-08 10:08:50.725233 | 2023-05-08 10:08:50.745521
        3 |      2 |        1 | COMPLETE | 2023-05-08 10:08:48.855296 | 2023-05-08 10:08:48.872277
        4 |      3 |        1 | COMPLETE | 2023-05-08 10:08:48.896755 | 2023-05-08 10:08:48.912588
       89 |     88 |        1 | COMPLETE | 2023-05-08 10:08:52.707945 | 2023-05-08 10:08:52.729369
...
```

If you could provide more detailed information or conditions, we might be able to fix the issue.

**Comment by daskol** [comment]
@c-bata The issue is still here in 3.3.0. It fails with other drivers e.g `pg8000` or `psycopg`. From my perspective it is a bit strange that only one pq driver is used in CI since it thought that enum issues with pq is common knowledge.

Spent too much time again. :disappointed:

**Comment by alex1712** [comment]
Just as info I had the same issue when using psycopg 3, I switched to psycopg2 and it worked

**Comment by fajardoramz** [comment]
Hi! I was having this same issue and could fix it by changing the type of column `value_type` using:

`ALTER TABLE trial_values ALTER COLUMN value_type TYPE VARCHAR;`

My setup has the following versions:

PostgreSQL 13.11 on x86_64-redhat-linux-gnu
The scikit-learn version is 1.3.1.
The xgboost version is 2.1.4.
The optuna version is 4.2.0.
The psycopg version is 3.2.4.

**Comment by qiuxiaomu** [comment]
> Hi! I was having this same issue and could fix it by changing the type of column `value_type` using:
> 
> `ALTER TABLE trial_values ALTER COLUMN value_type TYPE VARCHAR;`
> 
> My setup has the following versions:
> 
> PostgreSQL 13.11 on x86_64-redhat-linux-gnu scikit-learn 1.3.1. xgboost 2.1.4. optuna 4.2.0. psycopg 3.2.4.

I am getting the same error again with optuna 4.2.1, this is fairly certain now that optuna hasn't been hooked up with psycopg3 just yet. The line of code you suggest above may probably be part of the optuna upgrade code they need to put in to work with psycopg3. 

I've seen that optuna'x examples are either sqlite or mysql, no offense but are we here at optuna suggesting that probably MySql/SQLite would just work better?
