### ISSUE TITLE
Remove `trial._study_id` and use `trial.study._study_id` instead.

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#4678]
### Motivation

As described in the following TODO comment, `trial._study_id` is a bit redundant since `trial` has `study` attribute.
https://github.com/optuna/optuna/blob/5f10ae499e07ac9a298334d00a1418d13fa66482/optuna/trial/_trial.py#L54-L55

### Suggestion

Remove `trial._study_id` and use `trial.study._study_id` instead.

**Comment by rishabsinghh** [comment]
Hi, i would like to start working on this issue
