### ISSUE TITLE
Add a warning for a progress bar not being displayed

### ISSUE THREAD

**Issue by knshnb** [optuna/optuna#4679]
### Motivation

When we call `study.optimize(..., n_trials=None, timeout=None, show_progress_bar=True)`, a progress bar is not displayed.

### Description

We should raise a warning for not displaying the progress bar when `n_trials=None` and `timeout=None`.

**Comment by rishabsinghh** [comment]
Hey, i would like to start working on this issue. Could you please assign this to me?

**Comment by knshnb** [comment]
Sure, please!

**Comment by HideakiImamura** [comment]
This is resolved in #4728 by @rishabsinghh.
