### ISSUE TITLE
Remove experimental label from `_ProgressBar`

### ISSUE THREAD

**Issue by knshnb** [optuna/optuna#4683]
### Motivation

Several issues related to `_ProgressBar` have been already addressed (ref: https://github.com/optuna/optuna/issues/2892, https://github.com/optuna/optuna/issues/2957, https://github.com/optuna/optuna/issues/2958). Now we can remove the experimental label from `_ProgressBar`.

### Suggestion

Remove the `@experimental_func` decorator from `_ProgressBar`. Also, `_init_valid` method can be removed as explained in [TODO comment](https://github.com/optuna/optuna/blob/806448420863606c113aeb2e33457acf022be066/optuna/progress_bar.py#L57C28-L58).

**Comment by tungbq** [comment]
@knshnb Can I pick up this task?

**Comment by knshnb** [comment]
@tungbq Sure, of course!
