### ISSUE TITLE
Remove the version constraint on `fakeredis`

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#4688]
### Motivation

Remove the version constraint on fakeredis, which is introduced in https://github.com/optuna/optuna/pull/4637.

### Suggestion

I guess `fakeredis` introduced a regression bug in v2.11.1 and fixed in v2.11.2.
Please check the release note of fakeredis and updated a version constraints on fakeredis like `pip install fakeredis!=2.11.1".
https://github.com/cunla/fakeredis-py/releases

**Comment by gen740** [comment]
This issue was fixed in #4873.
