### ISSUE TITLE
Functions to plot pareto_front do not work when `constraint` is not set.

### ISSUE THREAD

**Issue by eukaryo** [optuna/optuna#4699]
### Expected behavior

I tried solving a multiobjective optimization problem and tried to illustrate pareto_front but encountered an error from optuna.

### Environment

- Optuna version: 3.1.1 and/or 3.2.0.dev
- Python version: 3.11
- OS: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.31
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
Traceback (most recent call last):
  File "/mnt/c/pythonprogram/optuna-nsga2-test.py", line 20, in <module>
    ax = optuna.visualization.matplotlib.plot_pareto_front(study)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/pythonprogram/venv-optuna3.1.1/lib/python3.11/site-packages/optuna/_experimental.py", line 75, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/pythonprogram/venv-optuna3.1.1/lib/python3.11/site-packages/optuna/visualization/matplotlib/_pareto_front.py", line 105, in plot_pareto_front
    info = _get_pareto_front_info(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/pythonprogram/venv-optuna3.1.1/lib/python3.11/site-packages/optuna/visualization/_pareto_front.py", line 248, in _get_pareto_front_info
    best_trials = study.best_trials
                  ^^^^^^^^^^^^^^^^^
AttributeError: 'MultiObjectiveStudy' object has no attribute 'best_trials'. Did you mean: 'get_trials'?
```

### Steps to reproduce

1. $ python3.11 -m venv venv && . venv/bin/activate
2. $ pip install optuna==3.1.1 matplotlib
3. exec the following code:
```python
import optuna


def objective(trial):
    x = trial.suggest_float("x", 0.0, 5.0)
    y = trial.suggest_float("y", 0.0, 3.0)
    v0 = 4 * x**2 + 4 * y**2
    v1 = (x - 5) ** 2 + (y - 5) ** 2
    return v0, v1


study = optuna.multi_objective.create_study(
    directions=["minimize", "minimize"],
    sampler=optuna.multi_objective.samplers.NSGAIIMultiObjectiveSampler(seed=1),
)

study.optimize(objective, n_trials=100)

print(f"optuna.__version__={optuna.__version__=}")
ax = optuna.visualization.matplotlib.plot_pareto_front(study)
ax.get_figure().savefig("pareto_front.png")

```

**Comment by nzw0301** [comment]
Thank you for reporting this issue! 

For `MultiObjectiveStudy`, I suppose Optuna asked us to use [`optuna.multi_objective.visualization.plot_pareto_front`](https://optuna.readthedocs.io/en/v3.0.0/reference/multi_objective/generated/optuna.multi_objective.visualization.plot_pareto_front.html#optuna-multi-objective-visualization-plot-pareto-front) rather than the corresponding methods in `optuna.visualization`. In addition the current visualization's tests under `optuna/tests/visualization_tests/` don't support `MultiObjectiveStudy` and `optuna.multi_objective` has been deprecated since v2.4.0, so I'm not sure about we need to address this issue.

**Comment by eukaryo** [comment]
Thank you for fast reply! I appreciate for letting me know that there are two functions for pareto_front. I feel, However, it seems unlikely that Optuna would ask users to use the deprecated one. (I am confused a bit)

**Comment by contramundum53** [comment]
The non-deprecated way to do multi-objective optimization is
```
study = optuna.create_study(
    directions=["minimize", "minimize"],
    sampler=optuna.samplers.NSGAIISampler(seed=1),
)
```

**Comment by eukaryo** [comment]
Thank you for your code! I understand that my reproducing code above is deprecated now, however, not obsoleted yet (announced to do in v4.0.0). So I still believe that (PR https://github.com/optuna/optuna/pull/4700) is worth considering now.

**Comment by eukaryo** [comment]
Contrary to my previous comment, I've come to understand that a policy of not investing in updates for deprecated features is a reasonable policy. I still believe that PR https://github.com/optuna/optuna/pull/4700 doesn't conflict with this policy and could be beneficial. However, I'd like your team to make the final decision on whether to merge or reject it. I'm going to close this issue now. Thank you for your feedback.
