### ISSUE TITLE
GridSampler crash due to memory consumption when search space is too big

### ISSUE THREAD

**Issue by okaikov** [optuna/optuna#4726]
### Expected behavior

GridSampler first "expand" the search space (self._all_grids), and then choose from it.
when the search space is big (I'm using 2**30) optuna crash due to memory consumption.
might want to implement "list(itertools.product(*self._search_space.values()))" with yield:
def list_product(*lists):
    for item in itertools.product(*lists):
        yield item

this can reduce the memory footprint.

### Environment

Optuna version:3.2.0
Python version:3.8.1

### Error messages, stack traces, or logs

```shell
job killed after reaching memory usage limit
```

### Steps to reproduce

search_space = {f"{i}": [0, 1] for i in range(0,30)}

**Comment by nzw0301** [comment]
According to the issue description, the setting (points in the grid search is $2^30$) has too large a search space, which cannot be searched by grid-search efficiently; the setting seems unrealistic. Even so, some memory efficiency is important aspect, so let me replace bug label with `code-fix`.

**Comment by okaikov** [comment]
unrealistic for HPO in general? or for grid search specifically?
in general, I ran much bigger optimization with more then 2^100 which were successful.

the motivation for this feature request is to run grid search as a fall back plan when regular algorithms (BO/genetic) fail to converge.

**Comment by nzw0301** [comment]
It depends on the problem, but In my experience, for HPO.

**Comment by maxLundin** [comment]
Hi! This problem cannot be solved just by using lazy evaluation of all grid parameters. Even if we do that, we still need to keep track of all trials, which are completed or running, to suggest other values. And this is impossible to do lazily.

**Comment by contramundum53** [comment]
> the motivation for this feature request is to run grid search as a fall back plan when regular algorithms (BO/genetic) fail to converge.
For this purpose, QMCSampler might be a better match. It generates uniform samples with much less trials.
If you really want to do grid search as a fallback (when GridSearch is realistic), you could use BruteForceSampler.

**Comment by contramundum53** [comment]
@okaikov I believe BruteForceSampler will do for your need, so I'll close this issue. Feel free to reopen this issue if it doesn't solve your problem!
