### ISSUE TITLE
Display best objective value in contour plot for a given param pair, not the value from the most recent trial

### ISSUE THREAD

**Issue by K-D-Gallagher** [optuna/optuna#4733]
### Motivation

I am optimizing 'learning rate', 'encoder', and 'dropout'. I happen to have 4 trails that all have encoder:resnet34 & dropout:0.1, each with a different learning rate:

![image](https://github.com/optuna/optuna/assets/87331101/b6fd0100-8035-4f47-81b8-b8e236e9a69f)

The contour plot of 'encoder' vs. 'dropout' is displaying the objective value from the most recent trial (71) for resnet34 & dropout 0.1, not the best value (from trail 21). Ironically, trial 21 is my best overall trial, which is why I'm frustrated this isn't being reflected in the contour plot

![image](https://github.com/optuna/optuna/assets/87331101/46d8a803-93e6-4e77-a87c-39fae1f5b7ab)

This issue was mentioned in a comment here, but never followed up on https://github.com/optuna/optuna/issues/2524#issuecomment-970780116

### Description

When running a study with >2 parameters that are categorical and/or have step values, it is likely that there will be multiple trials with same combo of values for some of those parameters - i.e. in my example, there are 4 trials with resnet34 and dropout 0.1, but with different learning rates. Currently, the contour plot displays the objective value from the most recent trial.

Feature request: when generating contour plots, display the **_best_** objective value for a given combo of parameters, not the objective value from the most recent trial.

### Alternatives (optional)

It seems the only real work around at the moment is filtering by the best N trials, such as seen here https://github.com/optuna/optuna/issues/1402

This does work for my current issue, but the problem with this is that there's no way to ensure that I'm seeing the best performance across the full parameter space unless I do this independently for each parameter pair

![image](https://github.com/optuna/optuna/assets/87331101/cf43ea1f-46b4-4337-a2f3-c1b31b05fd41)

**Comment by contramundum53** [comment]
Thanks for your feature suggestion! (and sorry for late reply 🙇‍♂️ )
I think this can be fixed by a relatively simple modification in https://github.com/optuna/optuna/blob/master/optuna/visualization/_contour.py#L209-L210 to retain the best trials. I'm not currently having enough time for this, but we welcome your contribution!
