### ISSUE TITLE
Sponsors

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#4736]
### Motivation

Users who enjoy using Optuna warmly propose donations to support Optuna's development, for example, https://github.com/optuna/optuna/discussions/4651. I also saw a similar post on Twitter (might not be serious) in Japanese too before. Currently, there is no way to do so. 

### Description

Could Optuna organisation provide a link to accept some financial support from users like https://www.buymeacoffee.com/ or https://github.com/sponsors?

### Alternatives (optional)

I imagine that the core team belonging to a private company @pfnet would have some difficulty accepting such a thing. But it would be great to offer alternative ways if possible...

**Comment by Alnusjaponica** [comment]
Now that Optuna started [GitHub Sponsors](https://github.com/sponsors/optuna).

**Comment by nzw0301** [comment]
Lovely. I hope this feature helps the core-dev team's productivity somehow to make optuna much more useful.
