### ISSUE TITLE
`optuna.terminator` with single value rather than `cross_validation_scores`

### ISSUE THREAD

**Issue by nzw0301** [optuna/optuna#4737]
### Motivation

I cannot still fully understand the terminator feature introduced recently, so this feature request might be nonsense; if so, sorry!

Using `cross_validation_scores` to use the terminator feature sounds really hard as a user since Optuna's objective function cannot deal with cross-validation with the pruning feature due to the implementation of `trial.report` that cannot be called `report` at the same time step. I imagine in some use cases single value (e.g., objective value or surrogate value) rather than cross-validated values is enough to stop the optimisation process. In fact, such a feature has been requested as in  https://github.com/optuna/optuna/issues/1001.

### Description

Rename `cross_validation_scores` with another name to accept a single value and implement the corresponding module for a single value.

**Comment by contramundum53** [comment]
This is possible by specifying [StaticErrorEvaluator](https://github.com/optuna/optuna/blob/master/optuna/terminator/erroreval.py#L109).
