### ISSUE TITLE
AssertionError: hypno and include must have same dtype

### ISSUE THREAD

**Issue by honeysleep** [optuna/optuna#4738]
### Don't use GitHub Issues to ask support questions.

`bandpower = yasa.bandpower(raw, hypno=hypno_up, include=(2, 3, 4))`

https://raphaelvallat.com/yasa/build/html/quickstart.html

I got up to EEG power in specific frequency bands in your tutorial, but after that I get this error. I'm using my data, not an example.

AssertionError                            Traceback (most recent call last)
[<ipython-input-39-e507cc5a45d5>](https://localhost:8080/#) in <cell line: 1>()
----> 1 bandpower = yasa.bandpower(raw, hypno=hypno_up, include=(0))

[/usr/local/lib/python3.10/dist-packages/yasa/spectral.py](https://localhost:8080/#) in bandpower(data, sf, ch_names, hypno, include, win_sec, relative, bandpass, bands, kwargs_welch)
    150         assert hypno.size == npts, "Hypno must have same size as data.shape[1]"
    151         assert include.size >= 1, "`include` must have at least one element."
--> 152         assert hypno.dtype.kind == include.dtype.kind, "hypno and include must have same dtype"
    153         assert np.in1d(
    154             hypno, include

**Comment by nzw0301** [comment]
The error message was from hypno, not Optuna

**Comment by PhD-GOAT** [comment]
Ah I asked another GitHub question. I didn't ask a question here, but I think there's a bug. Please delete it.
