### ISSUE TITLE
Add `qnevi_candidates_func` to the candidates_func of `optuna.integration.botorch`

### ISSUE THREAD

**Issue by kstoneriv3** [optuna/optuna#4739]
### Motivation

I would like to have yet another acquisition function implemented in the `optuna.integration.botorch`. So I'd like to discuss if it makes sense to support it, as we already have several candidatea functions implemented there.candidates

### Description

Right now, optuna supports `botorch.acquisitions.monte_carlo.qNoisyExpectedHypervolumeImprovement` but it does not support `botorch.acuiqision.monte_carlo.qNoisyExpectedImprovement` (the difference is about the absence of `Hypervolume`, which makes it multi-objective). This leads to an inconsistent offering of functionality as we do not have an API for noisy single-objective cases (ideally with batched optimization support). Additionally, though one may think that `qNoisyExpectedHypervolumeImprovement` should be able to handle a single-objective as its special case but it is not the case: https://github.com/pytorch/botorch/issues/1880

Therefore, I would like to implement `optuna.integration.botorch.qnevi_candidates_func` which wraps `botorch.acuiqision.monte_carlo.qNoisyExpectedImprovement`.

As `botorch.acuiqision.monte_carlo.LogNoisyExpectedImprovement` provides a more accurate acquisition function if we do not care about batched optimization, I can also implement this if there is an appetite for it as in #4667.

### Alternatives (optional)

There are a few options available:

1. Do not implement anything
2. Implement `qnevi_candidates_func` only
3. Implement `lognevi_candidates_func` only
4. Implement both `qnevi_candidates_func` and `lognevi_candidates_func`
5. Provide a more general API that can take a wider subset of `botorch.acquisition.*`

The last option would require a significant amount of change in the codebase so it would definitely require another standalone issue to discuss, but now that most of the candidates_funcs share very similar boilerplate code it may be time to consider such an option. If you are interested in the last option, I am happy to open another issue for it.

**Comment by contramundum53** [comment]
Hmm, I'm not sure whether I understand the functionality correctly by reading https://botorch.org/api/acquisition.html.
Am I correct to say that the `NoisyExpectedImprovement` is better than `ExpectedImprovement` in that it tries to estimate the right baseline, rather than using the "best trial so far" which may happen to be too good?

**Comment by contramundum53** [comment]
`lognevi_candidates_func` needs `FixedNoiseGP`, which is not available in Optuna (because we don't have a way to specify the noise).

**Comment by contramundum53** [comment]
I'm also interested in opening an interface for `botorch` (e.g. acquisition function, covariance module, warping, etc.)

**Comment by kstoneriv3** [comment]
> Am I correct to say that the NoisyExpectedImprovement is better than ExpectedImprovement in that it tries to estimate the right baseline, rather than using the "best trial so far" which may happen to be too good?

Yes, as far as I understand, that should be the case.

> lognevi_candidates_func needs FixedNoiseGP, which is not available in Optuna (because we don't have a way to specify the noise).

Thank you for pointing this out. I did not realize that they only support set of models:)

> I think adding qnevi_candidates_func is good.

Thanks, (I assume `qnei_candidates_func`, just to be clear). I will create a PR, if there is no objection here (probably within a few days...).

> I'm also personally interested in opening an interface for botorch objects (e.g. acquisition function, covariance module, warping, etc.)

Good to hear that! I will create another issue later then.

**Comment by contramundum53** [comment]
This is done. 🎉
