### ISSUE TITLE
Consider a cooperative algorithmic model for dask based parallelization

### ISSUE THREAD

**Issue by cherusk** [optuna/optuna#4754]
### Motivation

Reach a higher quality and speedup gain by supporting in addition to a independent MOEA model also a cooperative approach for parallelized MOEA algorithms. That is meant for distributed parallelization as of now already supported for the dask scheduler driven way.

Reference work explaining the potential boon.

[1] [El-Ghazali Talbi. A unified view of parallel multi-objective evolutionary algorithms. Journal of Parallel and Distributed Computing, 2019, 133, pp.349-358. ](https://hal.science/hal-02304734/document)

### Description

Currently the dask scheduler integration allows to spawn a large set of workers processing MOEAs in parallel, independently. That means, those parallelized study instances cannot exchange data about(communicate) their progress in a straightforward way with other study instances by leveraging optuna mechanisms, especially not dynamically after creation point in time.

Exchanging progress can be vital though to speed up and improve solution quality(pareto front outline) in parallel MOEAs runs.

A distributed and a global archive exists already for optuna studies on dask to some degree. Yet it's not well enough accessible and alterable to model a knowledge exchanging MOEA worker conveniently.

### Alternatives (optional)

One can integrate a communication logic inside optuna objective functions to model a knownledge exchange and consolidation across MOEA runs.

### Additional context (optional)

From [1] as cited in Motivation :arrow_up: 
![image](https://github.com/optuna/optuna/assets/10729954/ce74a396-a2a7-471c-a546-96d396a675e1)

Features is of relevance for project:
https://github.com/cherusk/godon

**Comment by HideakiImamura** [comment]
Currently, we committers are not very active in supporting new optimization algorithms from the Optuna formula. The interface for implementing a sampler is publicly available, so it would be helpful if users who wish to implement a particular algorithm could do so themselves. If you publish your algorithm on PyPI, you can mentions it from [this page](https://github.com/optuna/optuna-examples#external-projects-using-optuna) on optuna-examples.

**Comment by cherusk** [comment]
For clarification, this was less about implementing a new algorithm and more about having existing ones cooperate.
Might be important for people stumbling across this in future.
