### ISSUE TITLE
2 - stage log first - then transition to linear suggestions for continuous parameter distributions

### ISSUE THREAD

**Issue by david-thrower** [optuna/optuna#4767]
### Motivation

The motivation for this is handling of search spaces where the magnitude of the effect of a change in a given continuous parameter is unknown, complex, very broad, irregular, or has a massive feasible range and has a small step value that is significant in its effect. 

### Description

In suggest_float(), in addition to the existing logarithmic scale option and default linear scale option, provide an option that hybridizes these options as a 2 - stage range exploration. 

- This option would start by suggesting with a logscale sampler to estimate the  "approximate range" where the optimal value is likely to be in, 
- then once a configurable percentage of the number of the trials to be run have been suggested on a log scale sampling, subsequent samples will be sampled in a linear scale in a range close to the best value determined in the first step.

What I am thinking of is to suggest_float:

- To parameter: log, add an option: "hybrid"
- Add a parameter: transition: float: If set to 0.4, after 40% of (n_trials) have been sampled as logarithmic scale suggestions, subsequent suggestions will be sampled from a linear distribution in range (best parameter value so far +/- (max - min) * subrange) 
- Add an additional parameter: subrange: proportion of the original range that will be explored on a linear scale once the approximate range has been estimated via logarithmic sampling.

### Alternatives (optional)

I can't think of any.

### Additional context (optional)

N/A

**Comment by contramundum53** [comment]
Thanks for your suggestion!
In that case, what about using a log scale all the way to the end? I think switching to linear scale doesn't help much if, e.g., a "hybrid" range could turn into 0.1-0.5, 1-5 or 10-50.
