### ISSUE TITLE
Sampler pipeline enabling 2 samplers to be used, 1 for first few trials, another for ramaining trials

### ISSUE THREAD

**Issue by david-thrower** [optuna/optuna#4768]
### Motivation

What I propose is supporting an optimization pipeline using 2 samplers, where 1 sampler is used for the first few trials then a second is used thereafter, either to transition from course to fine tuning or to leverage different samplers to tune discrete | categorical | continuous | parameters based on whichever works best for different types of parameters.   

Situation 1 (Common situation):

- One sampler or list of samplers can quickly narrow down an approximate range or ranges where an optima is likely found. 
- Another sampler has better resolution for fine tuning an optima, but is much slower at eliminating space that is unlikely to contain an optima...  
- Ideally if a sampler like TPE is used, in the second stage, the sampler will make suggestions that consider the prior trials, but only suggestions in the range remaining will be counted and tried. 
- In any case, the user may instantiate 2 samplers, then instantiate a sampling pipeline object, which will become the argument for Study.optimize(...): 
A solution may look like:

```python3
SAMPLER1 = samplers.RandomSampler(seed=1234)
SAMPLER2  = samplers.TPEsampler(multivariate=True,group=True)
sampler = TuningPipeline(
    sampler1=SAMPLER1, 
    sampler_2 = SAMPLER2,
    space_to_consider_after_transition = 0.2 # Use the second tuner to explore the 20% of the original search space closest to the best found thus far ...    
    transition=0.4, # Transition after 50% of trials have run
    set_constant_in_later_trials=False, # Tune all parameters in the second stage
    consider_first_trials = True # Second sampler shall consider the prior samples when making suggestions  
    )


study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=20)

```

Situation 2 (More esoteric situation): 

In deep learning, particularly, in neural architecture search experiments, often these will involve a mix of discrete and continuous parameters, with complex inter-dependency in their distributions. For continuous params with very complex interdependent distributions or no understandable pattern CMA-ES is a great sampler. Unfortunately, CMA-ES does not handle integer / discrete parameters well and does not handle categorical values whatsoever. 

Most samplers that do handle discrete and categorical parameters have poor resolution for the continuous parameters in these, unless you run an inordinate number of trials, which is often infeasible, given the larger computational expense for each trial on this type of experiments. 

I haven't been able to test this yet, but I hypothesize that using a 2 - stage process whereby, we determine the ideal values for categorical and discrete parameters, using an algorithm like random search, Bayesian Gaussian, perhaps TPE, etc, then set these discrete / integer parameters constant to the optimal values found doing so, then optimize the continuous parameters using CMA-ES, we may be able to quickly obtain a good optima for both discrete and continuous params.

A solution to this may look like:

```python3
SAMPLER1 = samplers.RandomSampler(seed=1234)
SAMPLER2  = samplers.CmaEsSampler()
sampler = TuningPipeline(
    sampler1=SAMPLER1, 
    sampler_2 = SAMPLER2,
    space_to_consider_after_transition = 0.2 # Use the second tuner to explore the 20% of the original search space closest to the best found thus far ...    
    transition=0.5, # Transition after 40% of trials have run
    set_constant_in_later_trials=["categorical", "int"], # Tune only floating point values in second stage and use best values thus far for categorical and integer values.
    consider_first_trials = False # Second sampler shall not consider the prior samples when making suggestions  
    )

study = optuna.create_study(sampler=sampler)
study.optimize(objective, n_trials=20)


```

### Description

NA

**Comment by contramundum53** [comment]
Thanks for your suggestion!
For the specific examples given above, you can simply call `study.optimize` twice with different samplers, like
```
study = optuna.create_study(sampler=SAMPLER1)
study.optimize(objective, n_trials=n_trials_for_first_stage)
study.sampler = SAMPLER2
study.optimize(objective, n_trials=n_trials_for_second_stage)
```
This is the recommended usage of optuna when you want to have different stages of optimization.
If you want to finish the first stage based on some condition, you can provide a callback and call `study.stop()` inside it.
Also, if you want to fix some of the parameters in the second stage, you can use [PartialFixedSampler](https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.PartialFixedSampler.html).
Will these be enough for your situation?

**Comment by contramundum53** [comment]
Another situation is that you want to sample with SAMPLER1 and SAMPLER2 alternatively (or with a specified probability). In this case, I recommend you create two studies with a shared storage and study name, and provide different samplers for each study.

```
storage = optuna.storages.InMemoryStorage()
study1 = optuna.create_study(storage=storage, study_name="test_study", sampler=SAMPLER1)
study2 = optuna.load_study(storage=storage, study_name="test_study", sampler=SAMPLER2)
```
Then, you can sample from each study in whatever way you want by calling `ask` and `tell` method of each study.
