### ISSUE TITLE
Bayesian Gaussian process sampler

### ISSUE THREAD

**Issue by david-thrower** [optuna/optuna#4801]
### Motivation

 
TPE sampler is not the most effective for Deep learning and black box situations having a mix of continuous, discrete, and categorical hyperparameters to tune. There are other packages that support Bayesian Gaussian process, but they are not set up to parallelize like Optuna.

### Description

Described feature would be a sampler that samples via Gaussian process, once n initial trials are completed via random search.

### Alternatives (optional)

There are none that I am aware of.  

### Additional context (optional)

Most samplers that are effective for black box other than Bayesian Gaussian process are not able to optimize parameters of all 3 common data types: integers, floating point numbers, and categorical (e.g. which activation to use, or which optimizer to use in the objective to optimize its weights).

**Comment by contramundum53** [comment]
We have `optuna.integration.BoTorchSampler` that does Gaussian Process-based Bayesian optimization. This sampler is effective when all parameters are continuous, but we are having difficulty optimizing the acquisition function when the search space is discrete or mixed.
If you have any ideas for optimizing acquisition functions in a mixed search space, we appreciate your contribution!

**Comment by contramundum53** [comment]
Actually I personally also want to have a powerful GP implementation in Optuna, and we are using GP not only in sampler but also in `optuna.terminator` and the upcoming preferential optimization (currently under development). They all currently suffer from the same situation when the search space is mixed.

**Comment by contramundum53** [comment]
Now we have a `GPSampler` (Yay!) so we close this issue.

**Comment by carefree0910** [comment]
> Now we have a `GPSampler` capable for all parameter types (Yay!) so we close this issue. Note that our GPSampler is not currently designed to work well in a parallelized environment (You may find that different processes are evaluating almost the same parameters). Something like `constant_liar` in TPE won't come in v3.6, but If that becomes problematic, I think we might need to work on that.

Hi! First of all, thanks for the `GPSampler`!!

And now I exactly encountered exactly the same problem - I want to use `GPSampler` with `n_worker > 1` and found that duplicated params occurred here and there. 😢

Is something like `constant_liar` in TPE on the way? Or is there any other suggestions that I can follow? (Currently I'm using TPE with `multivariate=True` and `constant_liar=True` as a fallback)

Thanks in advance!
