### ISSUE TITLE
Support more automatic termination algorithms (`optuna.terminator`)

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#4818]
### Motivation

Optuna terminator was added in Optuna v3.2 to automatically terminate optimization based on a method proposed in the research paper "[Automatic Termination for Hyperparameter Optimization](https://www.amazon.science/publications/automatic-termination-for-hyperparameter-optimization)" [1].

Currently, the terminator only supports the regret-bound based method mentioned in the paper. However, the paper also describes some alternative approaches, such as EI and PI threshold-based methods, which are more convenient as they do not require cross-validation.

### Description

I suggest adding support for EI and PI threshold-based methods in the Optuna terminator. These methods are easy to use and would be useful for users who do not want to perform cross-validation. The [paper](https://www.amazon.science/publications/automatic-termination-for-hyperparameter-optimization) suggests using pre-defined thresholds for these methods and provides some examples.

> Threshold for Expected improvement (EI; Nguyen et al., 2017): stopping BO once EI drops below a pre-defined threshold. Choosing a threshold crucially depends on a problem at hand, e.g., values studied by the original paper result in too aggressive stopping across a range of our experiments. We thus extend it with a more finer grained grid resulting into {10−9, 10−13, 10−17}.

> Threshold for Probability of improvement (PI; Lorenz et al., 2016): stopping BO once PI drops below a pre-defined threshold. Similar to EI baseline, we tune the threshold and use {10−5, 10−9, 10−13}.

### Additional context (optional)

- The tracking issue of Optuna terminator https://github.com/optuna/optuna/issues/4398

**Comment by toshihikoyanase** [comment]
@smygw72 will work on a part of this PR regarding the Conv-i termination algorithm.

**Comment by smygw72** [comment]
I'm planning to implement a new evaluator named `ExpectedImprovement Evaluator` with `botorch.acquisition.analytic.ExpectedImprovement`.
