### ISSUE TITLE
Support constraint in `plot_intermediate_values`

### ISSUE THREAD

**Issue by hrntsm** [optuna/optuna#4830]
### Motivation

Make `plot_intermediate_values` plots support optimization with constraints

### Description

The values of the constraints are taken from _CONSTRAINTS_KEY in trial.system_attrs and applied to the results of the plot.
_CONSTRAINTS_KEY is located below, import and use it.
https://github.com/optuna/optuna/blob/master/optuna/samplers/_base.py#L202

Infeasible trials to be displayed in `#CCCCCC` color.

**Comment by adjeiv** [comment]
I would be interested to work on this feature - are we looking to determine whether each trial satisfies its constraints? Then if so, display the plot as normal, else display with the grey colour hex code?

I wonder for this and the other similar tasks whether having a util function that checks for the _CONSTRAINTS_KEY for a given Trial and determines feasibility would be useful.

**Comment by hrntsm** [comment]
Thank you for your interest. I think the color coding should be as you commented.
An example of an implementation is the PR #4793 . This is an implementation in history.

> I wonder for this and the other similar tasks whether having a util function that checks for the _CONSTRAINTS_KEY for a given Trial and determines feasibility would be useful.

It is not that long to write, so I don't think it is necessary to have it, but it would be of some length if the same thing is produced for all plots.
What do you think about this one, @c-bata ?

**Comment by hrntsm** [comment]
Thanks @adjeiv , close this issue
