### ISSUE TITLE
plot_param_importances works too slowly (flamegraph included)

### ISSUE THREAD

**Issue by ibobak** [optuna/optuna#4888]
### Expected behavior

Below is the screenshot on how slowly plot_param_importances is operating.  
I have only 978 trials in my study - not too much.

I've launched py-spy over the notebook kernel and I've got a flamegraph (attached below) which tells exactly which piece of code is slow: it is _fanova/tree.py, as I understand, implementation of this paper: http://proceedings.mlr.press/v32/hutter14.pdf

_get_marginalized_statistics takes most of the time, and it would be good if it could be speed up somehow. 
For me it looks like it can be parallelized inside.  I have 44 cores, and when this code is running, I see only one of them active.

![image](https://github.com/optuna/optuna/assets/8807043/9d5783ad-e59e-44fd-973a-4cf910143458)

on the SVG below press right mouse button, "Save link as",  download on your hard drive and open with Chrome to make it clickable:
![profile](https://github.com/optuna/optuna/assets/8807043/4849be4c-7dc7-4958-9b84-9a0bff486fa4)

### Environment

- Optuna version: 3.3.0
- Python version: Python 3.10.12
- OS: Linux monster 6.4.6-060406-generic #202307241739 SMP PREEMPT_DYNAMIC Mon Jul 24 17:46:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- (Optional) Other libraries and their versions:
full requirements.txt of the env which I am working with
```
# data manipulation
numpy==1.23.5
pandas==1.5.3
pandas_datareader==0.10.0
SQLAlchemy==1.4.49
pandasql==0.7.3
seaborn==0.12.2

# db
redshift_connector==2.0.911
apache-airflow==2.5.3
psycopg2-binary==2.9.7

# data science
tsfresh==0.20.1
xgboost==1.7.6
lightgbm==4.0.0
prophet==1.1.4
catboost==1.2
pymc==5.6.0
arviz==0.15.1
shap==0.42.1
optuna==3.3.0

# python
ipython==8.10.0
ipykernel==6.19.2
ipywidgets==7.6.5
ipynb-py-convert==0.4.6
notebook==6.5.2
jupyter_contrib_nbextensions==0.7.0
# these two are used to prevent problem with jupyter
jupyter_client==7.4.4
tornado==6.2

# infrastructure & security
keyring==23.4.0
mlflow==2.5.0
coloredlogs==15.0.1
tenacity==8.0.1
lazyprofiler==0.1.1

# aws
boto3==1.28.29
smart_open==6.3.0
```

### Error messages, stack traces, or logs

```shell
(flamegraph is attached above)
```

### Steps to reproduce

1. start experiment with 978 steps
2. run plot_param_importances and see how slow it is

**Comment by not522** [comment]
Thank you for your feedback! I recommend [optuna-fast-fanova](https://github.com/optuna/optuna-fast-fanova), which will help dramatically improve computation speed.

**Comment by ibobak** [comment]
yes, much faster.  22 seconds on 3K trials.
