### ISSUE TITLE
optimization for getting all the trials with all parameters

### ISSUE THREAD

**Issue by ibobak** [optuna/optuna#4890]
### Motivation

My goal was to get such a table with parameters and values:
![image](https://github.com/optuna/optuna/assets/8807043/496e6adb-8cfa-4c48-a1f1-0eea96cbf2c6)

Reason: your visualization routines are terribly slow, and I want to visualize everything on my own.

This piece of code
```
[{**study.trials[i].params, **{"value": study.trials[i].values[0]}} for i in range(len(study.trials))]
```
whose goal is to get the list of rows for such a table works for 1.5 hours. 

### Suggestion

Here is a piece of code to speed up fetching the results:
```
from sqlalchemy.sql import text

def read_trials(a_conn_string, a_study_name):
    engine = sqlalchemy.create_engine(a_conn_string)
    with engine.connect() as con:
        query = sqlalchemy.sql.text("""
            select p.trial_id, param_name as name, param_value as value
            from 
                trial_params p 
                inner join trials t on p.trial_id = t.trial_id 
                inner join studies s on t.study_id = s.study_id 
            where 
                s.study_name = :study_name
            union all
            select v.trial_id, 'value' as name, v.value 
            from 
                trial_values v    
                inner join trials t on v.trial_id = t.trial_id 
                inner join studies s on t.study_id = s.study_id 
            where 
                s.study_name = :study_name
        """)
        rs = con.execute(query, {"study_name": a_study_name})
        pdf_raw = pd.DataFrame(rs.all(), columns=["trial_id", "name", "value"])
        return pdf_raw.pivot_table(index="trial_id", columns="name", values="value")
        
pdf_trials = read_trials(conn_string, '20230828_162727_3')
```

It works in a second. It would be good if you place this accelerator somewhere into your product.  
(Sorry guys, but I have no time to make pull requests).

**Comment by not522** [comment]
Thank you for your suggestion.
Let me check your situation. How many trials have you made? Also, how long does `study.trials_dataframe()` take?

**Comment by ibobak** [comment]
It looks like this is my bad:  I did not notice the method study.trials_dataframe()  and re-invented the wheel first by iterating
```
[{**study.trials[i].params, **{"value": study.trials[i].values[0]}} for i in range(len(study.trials))]
```
and then by rewriting on SQL. 

Sorry for that.
