### ISSUE TITLE
Allow user-defined objective names in hyperparameter importance plots

### ISSUE THREAD

**Issue by xadrianzetx** [optuna/optuna#4895]
### Motivation

Support for multi-objective optimization has been added to hyperparameter importance plots in #4871. By default, objective names displayed in legend follow the pattern `Objective Value {n}`. To improve readability of the plots, it would be nice to let users define their own objective names to display. 

### Description

As discussed in https://github.com/optuna/optuna/pull/4871#discussion_r1292456529, both `optuna.visualization.plot_param_importances` and `optuna.visualization.matplotlib.plot_param_importances` APIs should be modified to allow passing custom objective names. APIs should accept:
* Strings like `"Custom objective name"`, which for multi-objective optimization will be suffixed with objective number.
* Sequences of strings like `["Objective foo", "Objective bar"]`, where each objective will be assigned a name from the collection.

**Comment by not522** [comment]
Hi! Thank you for your great suggestion!
Recently, we introduced the `metric_names` API for objective names. I think that it is suitable for `plot_param_importances`. (ref: #4383)

**Comment by xadrianzetx** [comment]
Oh, that's very cool. No need to modify existing `plot_param_importances` APIs then.

**Comment by xadrianzetx** [comment]
BTW @not522, do you think it's worth introducing a getter for metric names as well? Currently you have to [traverse quite far and know magic literals to retrieve them](https://github.com/optuna/optuna/blob/de870c0bdff01a0c188dedc688cd30f04b05a9b9/optuna/visualization/_pareto_front.py#L346-L348).

**Comment by not522** [comment]
Yes, I think it would be useful to introduce the getter. The reason we were cautious about implementing it at that time was that there were several API design options. (e.g., `create_study(..., directions={"loss": MINIMIZE, "duration": MINIMIZE})` or return dict in the objective function)
In my opinion, it would be good to add an attribute like `study.metric_names` as an experimental feature.
