### ISSUE TITLE
optuna.integration.XGBoostPruningCallback not working with XGBoost 2.0.0

### ISSUE THREAD

**Issue by vmkuhn** [optuna/optuna#4933]
### Expected behavior

optuna.integration.XGBoostPruningCallback should work without raising **TypeError("callback must be an instance of `TrainingCallback`.")** when using XGBoost 2.0.0

### Environment

- Optuna version: 3.3.0
- Python version: 3.10.12
- OS: OS:Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.35
- (Optional) Other libraries and their versions: xgboost 2.0.0

### Error messages, stack traces, or logs

```shell
TypeError("callback must be an instance of `TrainingCallback`.")
```

### Steps to reproduce

Add **optuna.integration.XGBoostPruningCallback** as callback to **xgboost.XGBRegressor** and call fit-method

### Additional context (optional)

The problem seems to be only the version check of xgboost in optuna.integration.XGBoostPruningCallback.

In line 14 the following check is performed:

```
use_callback_cls = xgboost_major_version >= 1 and xgboost_minor_version >= 3
```
This fails for XGBoost version 2.0.0 as the minor version is <3. Suggested solution is changing the version check to 

```
use_callback_cls = (xgboost_major_version >= 1 and xgboost_minor_version >= 3) or (xgboost_major_version >= 2 and xgboost_minor_version >= 0)
```
This solution worked for me.

**Comment by nzw0301** [comment]
Could you try the master branch version rather than 3.3? https://github.com/optuna/optuna/pull/4921 fixes the issue and it is not in the stable version.
