### ISSUE TITLE
pg8000 driver for postgresql databases has limits in default settings when using a study optimization

### ISSUE THREAD

**Issue by gituser789** [optuna/optuna#4936]
### Expected behavior

When running a postgresql-database with the `pg8000` DB API in the default settings like this
```
database_url = f"postgresql+pg8000://user:password@127.0.0.1:port/mydb"
```
the database runs into trouble loading a study with more than 32767 trials when performing e.g. a NSGAIII optimization.

There seems so be a limit in the DB API `pg8000`. Adapting the `Cursor.setinputsizes` in `pg8000` could solve the issue https://github.com/tlocke/pg8000/issues/120 (i did not verify this).

What solves the issue, is using another database API `psycopg2` in the default settings:
```
database_url = f"postgresql+psycopg2://user:password@127.0.0.1:port/mydb"
```
Due to optuna users like me are may no experts in setting up databases, it might be useful to fix this by optuna (if possible). Otherwise, a hint in the documentation would be nice. I can adapt the documentation and send a PR, but want to listen to your feedback first.

### Environment

- Optuna version: 3.3.0
- Python version: 3.11
- OS: debian 10 and Manjaro (current version of rolling release)

### Error messages, stack traces, or logs

```shell
struct.error: 'h' format requires -32768 <= number <= 32767
```
```


### Steps to reproduce

Perform a study with more than 32767 trials using the `PG8000` database API for the postgresql database
```
database_url = f"postgresql+pg8000://user:password@127.0.0.1:port/mydb"
```

### Additional context (optional)

_No response_

**Comment by HideakiImamura** [comment]
@gituser789 Does this problem still occur with the latest Optuna v3.4?
