### ISSUE TITLE
Support `TerminatorCallback` in `OptunaSearchCV`

### ISSUE THREAD

**Issue by Alnusjaponica** [optuna/optuna#4958]
### Motivation

OptunaSearchCV performs cross-validation, implying that it should theoretically be feasible to employ the TerminatorCallback with it.

### Description

Currently, it is possible to pass `TerminatorCallback` though `calback` argument of `OptunaSearchCV`. Therefore it suffice to properly report cv scores within the `fit()` function, i.e., call `report_cross_validation_scores()` after every time cv scores are obtained.

**Comment by adjeiv** [comment]
I'd like to work on this issue!

**Comment by Alnusjaponica** [comment]
This issue was resolved by #5098. Thanks @adjeiv

**Comment by Alnusjaponica** [comment]
This issue was resolved by https://github.com/optuna/optuna/pull/5098. Thanks @adjeiv
