### ISSUE TITLE
Add analytic `ExpectedHyperVolumeImprovement` candidate function to `BoTorchSampler`

### ISSUE THREAD

**Issue by contramundum53** [optuna/optuna#4960]
### Motivation

Straightforward extension of #4546 to multi-objective version.

Quasi-Monte Carlo acquisition functions are for difficult cases where analytic value is not available, e.g. batch suggestion or considering running trials. When analytic form is available, it is better to use it.

### Description

Add a candidate function that uses [botorch.acquisition.multi_objective.analytic.ExpectedHypervolumeImprovement](https://botorch.org/api/acquisition.html#botorch.acquisition.multi_objective.analytic.ExpectedHypervolumeImprovement)

**Comment by adjeiv** [comment]
@contramundum53 I'd be interested in working on this issue, if that's good with you!

**Comment by contramundum53** [comment]
@adjeiv Sure, thank you!
