### ISSUE TITLE
Make `logei_candidate_func` in `BoTorchSampler` support constraints

### ISSUE THREAD

**Issue by contramundum53** [optuna/optuna#4961]
### Motivation

Straightforward extension of #4546 for constrained objective functions.
Currently `logei_candidate_func` does not support constraints, because `botorch.acquisition.analytic.LogExpectedImprovement` does not take constraint argument. However, BoTorch has a separate class `botorch.acquisition.analytic.LogConstrainedExpectedImprovement` that specifically considers constraints, so we can use this acquisition function when the objective has constraints.

When this is done, the default candidate function for constrained objective function can be made to `logei_candidate_func`.

### Description

Use `botorch.acquisition.analytic.LogConstrainedExpectedImprovement` to support constraints in `logei_candidate_func`.

**Comment by sousu4** [comment]
I will work on this issue.
