### ISSUE TITLE
docstring for `optuna.artifacts.Boto3ArtifactStore` looks wrong

### ISSUE THREAD

**Issue by semiexp** [optuna/optuna#4963]
### What is an issue?

In the example code:

```
from optuna.artifact import upload_artifact
from optuna.artifact.boto3 import Boto3ArtifactStore
```

but `optuna.artifact` does not exist. I think this should be something like

```
from optuna.artifacts import Boto3ArtifactStore, upload_artifact
```

**Comment by Alnusjaponica** [comment]
IIRC, this was fixed by https://github.com/optuna/optuna/pull/4957.
Feel free to re-open this issue if I am wrong.
