### ISSUE TITLE
`formats.sh` does not handle `tutorial/`

### ISSUE THREAD

**Issue by semiexp** [optuna/optuna#4984]
### Expected behavior

`formats.sh` should format files under `tutorial/`

### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
(no formatting occurred but CI failed)
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

### Additional context (optional)

https://github.com/optuna/optuna/pull/4980

**Comment by sousu4** [comment]
I will work on this issue.

**Comment by HideakiImamura** [comment]
Let me close this issue since this was fixed in #5023.
