### ISSUE TITLE
BoTorchSampler `n_startup_trials` and minimum recommended budget

### ISSUE THREAD

**Issue by carlosg-m** [optuna/optuna#4989]
In the Optuna [sampler comparation table](https://optuna.readthedocs.io/en/stable/reference/samplers/index.html) it states that `BoTorchSampler` recommended budget is between 10 and 100 trials, however in the `BoTorchSampler` [documentation page](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.integration.BoTorchSampler.html) the `n_startup_trials` parameter is set to `10`. This means that if someone with a very expensive optimization problem uses BoTorch with only 10 trials, it is equivalent to performing a random search.

Should the default parameter `n_startup_trials` be changed to zero? What is the recommended value?

**Comment by nzw0301** [comment]
Thank you for creating the issue. Alternatively, it would be great to clarify whether or not `Recommended budgets (#trials)` include `n_startup_trials`.

**Comment by HideakiImamura** [comment]
I think we cannot set `n_startup_trials` to zero. It's good idea to clarify that `Recommended budgets (#trials)` includes `n_startup_trials`.

**Comment by Ashhar-24** [comment]
Hey, @HideakiImamura I would love to work on this issue. Can you please elaborate what should be done in this issue?

**Comment by HideakiImamura** [comment]
It would be great to add an expalnation about the budget in [the sampler comparison table](https://optuna.readthedocs.io/en/stable/reference/samplers/index.html). I mean we should note that the recommended budgets (#trials) includes the number of trials for initialization, i.e., `n_startup_trials` for each sampler.
