### ISSUE TITLE
Better raising an error or making n_below zero for more robust splits

### ISSUE THREAD

**Issue by nabenabe0928** [optuna/optuna#5020]
### Motivation

When spliting trials in TPESampler, n_below might be negative value [here](https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L606-L616).
The problem is that `sorted_trials[:n_below]` and `sorted_trials[n_below:]` may exhibit completely unexpected behavior when `n_below < 0`.

### Suggestion

To this end, I suppose that we should raise an error when we get `n_below < 0` during the process [here](https://github.com/optuna/optuna/blob/master/optuna/samplers/_tpe/sampler.py#L606-L616) or we should enforce `n_below >= 0` by using `max(n_below, 0)`.

In my opinion, the second solution is better as I assume that the order of adding trials to `samples_below` is sorted by priority.

It should look like the following after my modification:

```python
below_complete, above_complete = _split_complete_trials(complete_trials, study, n_below)
n_below = max(0, n_below - len(below_complete))
below_pruned, above_pruned = _split_pruned_trials(pruned_trials, study, n_below)
n_below = max(0, n_below - len(below_pruned))
below_infeasible, above_infeasible = _split_infeasible_trials(infeasible_trials, n_below)
```

**Comment by p1kit** [comment]
Can I pick this up ?

**Comment by HideakiImamura** [comment]
@p1kit Yes, please go ahead.

**Comment by p1kit** [comment]
Thanks @HideakiImamura , Can you please assign this to me. Will start working on it .
