### ISSUE TITLE
Fix typing of `_TreeNode` in `BruteForceSampler

### ISSUE THREAD

**Issue by contramundum53** [optuna/optuna#5034]
### Motivation

The key of https://github.com/optuna/optuna/blob/3fcbf8839c760916cc0cf38fb545f526d5efe85d/optuna/samplers/_brute_force.py#L36 could be typed `float` because only internal representations are stored in the tree.

### Suggestion

Change the type of `children` from `dict[Any, ...]` to `dict[float, ...]` and change other places accordingly.

**Comment by aanghelidi** [comment]
Hello @contramundum53 , I will work on this one  if it's ok for you.

**Comment by contramundum53** [comment]
Sure, thank you @aanghelidi !
