### ISSUE TITLE
Bring `_CachedStorage` into `RDBStorage`

### ISSUE THREAD

**Issue by contramundum53** [optuna/optuna#5035]
### Motivation

`_CachedStorage` is only used from `RDBStorage`. It can be moved into `RDBStorage`.

### Suggestion

Move `_CachedStorage` (https://github.com/optuna/optuna/blob/3fcbf8839c760916cc0cf38fb545f526d5efe85d/optuna/storages/_cached_storage.py#L38) into `RDBStorage`.

**Comment by BitVivek** [comment]
I want to work on it , I am new as contributer , can I start working on it ?

**Comment by contramundum53** [comment]
Of course, thank you!

**Comment by BitVivek** [comment]
I have a question regarding the integration of _CachedStorage into RDBStorage. With this integration, all methods would first check data from the cache memory before querying the RDBStorage.Currently, the _CachedStorage class is integrated with RDBStorage. However, considering the potential for changing storage mechanisms in the future, is it advisable to proceed with this integration?

**Comment by contramundum53** [comment]
Sorry, we are having some discussions about this issue and #5060 among the core develop members right now. The core dev members are concerned that putting _CachedStorage class inside RDBStorage resulted in a much longer _rdb.py file and may have resulted in a worse overall readability, so I think we might need to change the direction.
We are continuing our discussion, and will come back in a while.

**Comment by contramundum53** [comment]
It was my mistake to make this issue contribution-welcome. I'll add needs-discussion flag here.
