### ISSUE TITLE
Migrate from `threading.local` to `contextvars`

### ISSUE THREAD

**Issue by contramundum53** [optuna/optuna#5036]
### Motivation

https://github.com/optuna/optuna/blob/3fcbf8839c760916cc0cf38fb545f526d5efe85d/optuna/study/study.py#L56 uses `threading.local`, but `contextvars` can make the code more sophisticated (https://peps.python.org/pep-0567/#converting-code-that-uses-threading-local).

### Suggestion

Use `contextvars` instead of `threading.local`.

**Comment by sousu4** [comment]
I will work on this issue.

**Comment by SG5** [comment]
Hey @sousu4 I just saw your comment. I started working on this issue 3 days ago. Let me know if you want to pass it to me

**Comment by sousu4** [comment]
HEY @SG5 OK,  Please proceed.

**Comment by contramundum53** [comment]
After a discussion, we found a potential bug (discrepancy from the original design) in the original Study class. The original intention of the issue was to use contextvars to simplify the caching mechanism based on the original design (which looks impossible to do now without some breaking change in the current Study class), and we might need to investigate the potential bug first.

**Comment by contramundum53** [comment]
In the original design, we didn't allow the `Study` class to cache trials when the user directly used `ask` and `tell`. The cache is only for `optimize` function. In that case, we could create a new context for each optimize call.
