### ISSUE TITLE
Feature to determine whether `GridSampler` has exhausted the grid

### ISSUE THREAD

**Issue by Koen1999** [optuna/optuna#5052]
### Motivation

Currently, there is no good way in which we can determine whether the grid of `GridSampler` is exhausted when resuming a study.
While the method `_get_unvisited_grid_ids()` exists, it is a protected method and should not be used outside of the library.

### Description

I suggest adding a method called something like `is_exhausted()` that is public and simply returns `len(self._get_unvisited_grid_ids()) == 0`

### Alternatives (optional)

Alternatively, it may be useful to add keyword arguments to be passed to `GridSampler` that give more control over what happens if the grid is already exhausted. For example, one could add a keyword like `reevaluate_when_exhausted: bool`.

### Additional context (optional)

I encountered this suggestion when receiving the following warning: `GridSampler` is re-evaluating a configuration because the grid has been exhausted. This may happen due to a timing issue during distributed optimization or when re-running optimizations on already finished studies."

This issue further builds upon the discussion of https://github.com/optuna/optuna/issues/3256

**Comment by HideakiImamura** [comment]
Thanks for the PR. Nice idea. Let me add the contribution-welcome issue label.
