### ISSUE TITLE
Adapt `n_objectives > 2` to `n_objectives > 4` following the FaceBook Ax official implementation

### ISSUE THREAD

**Issue by nabenabe0928** [optuna/optuna#5087]
### Motivation

Since the official implementation [here](https://github.com/pytorch/botorch/blob/36d09a4297c2a0ff385077b7fcdd5a9d308e40cc/botorch/acquisition/multi_objective/utils.py#L46-L63) changed the default threshold for `n_objectives`, we should also change the number from 2 to 4.

### Suggestion

Change [here](https://github.com/optuna/optuna/pull/5065/files#diff-fb416f53f506e50d99de583a111470730758756ff9237bed4649f807491737aeL387) and [here](https://github.com/optuna/optuna/pull/5065/files#diff-fb416f53f506e50d99de583a111470730758756ff9237bed4649f807491737aeR536) to `n_objectives > 4` following [the official implementation](https://github.com/pytorch/botorch/blob/36d09a4297c2a0ff385077b7fcdd5a9d308e40cc/botorch/acquisition/multi_objective/utils.py#L46-L63).

**Comment by eukaryo** [comment]
Let me close this issue as it appears to be resolved. Please feel free to reopen if there are any remaining concerns.
