### ISSUE TITLE
Nested study

### ISSUE THREAD

**Issue by R-N** [optuna/optuna#5118]
### Motivation

Simultaneously optimizing a general hyperparameter set, such as activation functions, and dataset-specific hyperparameter set, such as hidden dimension size. Doing the search in parallel for different datasets.

### Description

I want to be able to simultaneously optimize a general hyperparameter set, such as activation functions or architectural options, and dataset-specific hyperparameter set, such as hidden dimension size. Doing the search in parallel for different datasets. 

### Alternatives (optional)

I can't simply nest study.optimize because it does its own loop. But maybe with the dataset-specific study as outer loop, wrapping the objective as partial with sampled parameters, then do the general study as inner loop with n=1, storing the value in an object to retrieve later for the outer loop. Or reversing the inner-outer study. Would that work? Does Optuna allow nesting study.optimize calls? This also means each study will be completely oblivious of each other. Is that fine?

As another alternative, I can add a prefix/suffix to the dataset-specific hyperparameters and conditionally sample them. However this means they can't be sampled multivariately. It will also clutter the study, specially when analyzed with Optuna Dashboard.

**Comment by R-N** [comment]
Or maybe what I need is just a function to "return" the objective value so I can just do the loop manually and "return" the value to the two studies.

**Comment by R-N** [comment]
Oh wow I just realized it exists now with study.ask and study.tell! Guess I'll just try this.

**Comment by R-N** [comment]
Oh I just realized the different datasets will have different objective value scale and distribution. This won't work unless it's handled, and I don't have any idea how or if it's even possible at all.

**Comment by contramundum53** [comment]
The optuna way to do that is to use conditional search space. `optuna.samplers.TPESampler` with `multivariate=True` option does handle each group of parameters in multivariate way.

**Comment by contramundum53** [comment]
As for optuna-dashboard support, there are issues like https://github.com/optuna/optuna-dashboard/issues/734.
