### ISSUE TITLE
Parallelize GPU without a database, just use the .txt file you save trials to.

### ISSUE THREAD

**Issue by luke-mcdermott-mi** [optuna/optuna#5125]
### Motivation

GPU parallelization is not simple. I cannot set up a sql database on my cluster as I do not have admin access, and there is no genuine reason why I should have to create a database to store simple information thats for search.

### Description

Instead of a database, just use a .txt file that holds the hyperparameters + any metrics you need. 

```
with open("./optuna_trials.txt", "a") as file:
        file.write(f"Trial {trial.number}, Mean Distance: {mean_distance}, BOPs: {bops}, Inference time: {inference_time}, Validation Loss: {validation_loss}, Param Count: {param_count}, Hyperparams: {trial.params}\n")
```
    
I use this to save my results. I can reload certain trials just by using trial.params. Why is not used to parallelize/sync GPUs?

**Comment by nzw0301** [comment]
Did you check https://optuna.readthedocs.io/en/latest/reference/generated/optuna.storages.JournalStorage.html?
