### ISSUE TITLE
Grid search reevaluates the same parameter combination in parallelization scenario 

### ISSUE THREAD

**Issue by WuYunfan** [optuna/optuna#5139]
### Expected behavior

The same parameter combination is reevaluated. 
However, in the source code I read, the same gird_id (corresponding to different parameter combinations) would not be reevaluated, if there are unvisited_grids.
<img width="800" alt="image" src="https://github.com/optuna/optuna/assets/31981885/7f211501-2f57-401a-839a-39a7cea60eaa">

### Environment

- Optuna version:3.4.0
- Python version:3.11.5
- OS:Linux-3.10.0-1160.95.1.el7.x86_64-x86_64-with-glibc2.17
- (Optional) Other libraries and their versions: 

### Error messages, stack traces, or logs
These are logs from two optuna process in parallelization scenario.
<img width="1694" alt="image" src="https://github.com/optuna/optuna/assets/31981885/7b23a503-4f52-40f3-b60c-e268874b6afa">
<img width="1686" alt="image" src="https://github.com/optuna/optuna/assets/31981885/abcf4cbc-4e5f-4a3e-b627-984b8566c6ce">

### Steps to reproduce

```
search_space = {'reg_u': [1.e1, 1.e2, 1.e3], 'alpha': [1.e-7, 1.e-6, 1.e-5],
                    's_l2': [1.e-3, 1.e-2, 1.e-1], 's_lr': [1.e-2, 1.e-1]}

optuna.logging.get_logger('optuna').addHandler(logging.StreamHandler(sys.stdout))
study_name = 'dpa2dl-tuning'

storage = optuna.storages.RDBStorage(url='sqlite:///../{}.db'.format(study_name),
                                         failed_trial_callback=optuna.storages.RetryFailedTrialCallback())

study = optuna.create_study(study_name=study_name, storage=storage, load_if_exists=True, direction='maximize',
                                sampler=optuna.samplers.GridSampler(search_space))

study.optimize(objective)
```

**Comment by nzw0301** [comment]
This is not a bug as mentioned in the grid-search page, see https://github.com/optuna/optuna/issues/4627 for details.
