### ISSUE TITLE
Add a guideline to setup RDB with Docker.

### ISSUE THREAD

**Issue by sile** [optuna/optuna#517]
Add this guideline to Optuna tutorial (as a part of distributed optimization section?).

**Comment by c-bata** [comment]
This comment might be helpful.
https://github.com/pfnet/optuna/pull/520#issuecomment-531459060

**Comment by sile** [comment]
@c-bata Thank you for your information! It seems useful.

**Comment by hvy** [comment]
I guess this is still an open issue.

For the record, we now have a [k8s directory under `examples`](https://github.com/optuna/optuna/tree/master/examples/kubernetes). We could create a similar directory for Docker.

**Comment by HideakiImamura** [comment]
It might be good to guide how to use https://github.com/himkt/optuna-e2e.

**Comment by HideakiImamura** [comment]
I hope you will write a Dockerfile with reference to https://github.com/himkt/optuna-e2e/blob/main/docker/optuna-300/Dockerfile and describe how to build and use the Dockerfile. I think https://github.com/himkt/optuna-e2e will be of great help to you on how to build and use it.

**Comment by g-votte** [comment]
Since this issue has been open for a long time, let me close once. Feel free to reopen upon necessity.
