### ISSUE TITLE
Passing float-castable str to `study.tell` raises an error

### ISSUE THREAD

**Issue by knshnb** [optuna/optuna#5175]
### Expected behavior

We should catch it correctly and make the trial `FAIL` instead of raising an error.

### Environment

- Optuna version: 3.5.0
- Python version: 3.9.6
- OS: macOS
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
[I 2024-01-04 14:01:53,511] A new study created in memory with name: no-name-2af3429a-171e-4d5c-ab32-32ead2065d79
Traceback (most recent call last):
  File "/Users/knshnb/pfn/optuna/issue.py", line 6, in <module>
    study.tell(trial, "2.2")
  File "/Users/knshnb/pfn/optuna/optuna/study/study.py", line 635, in tell
    return _tell_with_warning(
  File "/Users/knshnb/pfn/optuna/optuna/study/_tell.py", line 151, in _tell_with_warning
    values_conversion_failure_message = _check_values_are_feasible(study, values)
  File "/Users/knshnb/pfn/optuna/optuna/study/_tell.py", line 70, in _check_values_are_feasible
    if math.isnan(v):
TypeError: must be real number, not str
```

### Steps to reproduce

```python
import optuna


study = optuna.create_study()
trial = study.ask()
study.tell(trial, "2.2")
```

### Additional context (optional)

Tasks
- Check if the value is an instance of `numbers.Real` instead of checking it is castable to float
- Add test cases

**Comment by ryota717** [comment]
@knshnb Hi, i'm tackling this issue and is there any idea for testing?
a test like https://github.com/optuna/optuna/pull/5269/commits/f550d90b50f995992a1861589229459908bbea07#diff-2eae7c178876c67d218547f9b3b4fc142b361f02f776bcbad410df0e58fdf4d7R1311-R1313 occers mypy error.
https://github.com/optuna/optuna/actions/runs/8020379337/job/21910113006?pr=5269

**Comment by knshnb** [comment]
Hi, thanks for the contribution! I think you can ignore mypy for this test case like this:
https://github.com/optuna/optuna/blob/11721cc081ec290a5c16c09de57b5be06818a51b/tests/trial_tests/test_trial.py#L585

**Comment by ryota717** [comment]
I didn't know the workaround, great thanks for your reply!
