### ISSUE TITLE
ArangoDB as an optional DB.

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#5182]
### Motivation

Additionaly to those DB options that come with SQLAlchemy I would like to use ArangoDB as an option. This is because ArangoDB is accessable via HTTP and easy to secure with an reverse proxy and HTTPS. It causes no problem with company proxies that might only allow HTTP and HTTPS traffic.

### Description

see above

**Comment by not522** [comment]
Thank you for your suggestion!
Currently, we have no plan for additional DB support, but in my opinion, the implementation as 3rd party library is welcome.
I think that it can be implemented easily using the journal storage. It just needs to implement several methods. (Please see [`JournalRedisStorage`](https://github.com/optuna/optuna/blob/master/optuna/storages/_journal/redis.py).)

**Comment by PhilipMay** [comment]
Thanks @not522 
That looks easy.

Two questions:

Where would you suggest me to put this code? My own project or are there Optuna-contrib projects you would suggest?

Would you provide feedback and some guidance for me?

Thanks
Philip

**Comment by not522** [comment]
1. We welcome a PR submission to [optuna-integration](https://github.com/optuna/optuna-integration).
2. Yes!

I'm wondering if we need accounts or licenses to use ArangoDB. If we need them for testing or CI, it might be a little difficult to add the ArangoDB integration into optuna-integration.

**Comment by PhilipMay** [comment]
I have a private ArangoDB running on a docker. It is open source.
But I have no clue how to integrate this into a CI to be honest.

**Comment by not522** [comment]
Sorry for my late response. I'm not confident, but, it may be done like [`tests-storage.yml`](https://github.com/optuna/optuna/blob/master/.github/workflows/tests-storage.yml).
