### ISSUE TITLE
user attribute keep best

### ISSUE THREAD

**Issue by deadsoul44** [optuna/optuna#5183]
### Motivation

Usually we want to keep the best model from optimization. It is not straightforward to do this with the current api.

### Description

Add an option to keep a user attribute for only the best iteration. 
```
def objective(trial):
    gbm = ...
    trial.set_user_attr(key="best_booster", value=gbm, keep_best=True)
```

Best booster will only be available for the best trial.
This will work:
```
best_model=study.best_trial.user_attrs["best_booster"]
```
This won't:
```
best_model=study.trials[0].user_attrs["best_booster"]
```
This way we won't save all the unnecassry models and keep only the best.

**Comment by nzw0301** [comment]
How about using study attribute and callback as answered by https://stackoverflow.com/a/63365355/2406562?

**Comment by deadsoul44** [comment]
I also commented there. I couldn't understand the point of that answer. The purpose is not to save an object in memory for every trial.

**Comment by nzw0301** [comment]
See also the original answer https://stackoverflow.com/a/62164601/2406562. How about this?

**Comment by deadsoul44** [comment]
This one is a good solution. But, it requires defining a callback and global variables. Optuna can make this easier.

**Comment by nzw0301** [comment]
In my understanding, this feature will introduce additional computation over past trials to store the best trial's attribute and the [parallel optimisation](https://optuna.readthedocs.io/en/stable/tutorial/10_key_features/004_distributed.html) case is not trivial. As I shared, the callback and global variable approach seems simple workaround with the current API.

Thus I'm not sure this feature is worth implementing, but if you believe "Optuna can make this easier.", please feel free to send a pull request to move forward discussion. 

Best regards,
