### ISSUE TITLE
OptunaSearchCV support single split cv

### ISSUE THREAD

**Issue by dmitry-lesnik** [optuna/optuna#5196]
### Motivation

I want to be able to pass a simple cv split to the OptunaSearchCV, for instance
cv = [(idx_train, idx_test)]

### Description

At the moment and attempt to pass a single train/test split cv as a parameter to OptunaSearchCV results in exception thrown from report_cross_validation_scores() which requires the length of scores to be > 1

**Comment by nabenabe0928** [comment]
As Optuna integration modules have been migrated to `optuna-integration` and the same issue there is linked to this issue, I will close this issue.
