### ISSUE TITLE
BoTorch Dependency Not Installed with Optuna via pip

### ISSUE THREAD

**Issue by resnant** [optuna/optuna#5197]
### Expected behavior

When installing Optuna using the standard `pip install optuna` command, BoTorch, one of its dependencies, should be automatically installed along with Optuna. Currently, this is not the case, and users need to install BoTorch separately. 
The expected behavior is that Optuna's installation process includes the installation of all necessary dependencies, including BoTorch.

### Environment

- Optuna version:3.5.0
- Python version:3.11.5
- OS:Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.31 (Docker `continuumio/miniconda3:latest`)

### Error messages, stack traces, or logs

```shell
(base) root@aaf69946013a:/# python
Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from optuna_dashboard.preferential.samplers.gp import PreferentialGPSampler
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.11/site-packages/optuna_dashboard/preferential/samplers/gp.py", line 9, in <module>
    import botorch.acquisition.analytic
ModuleNotFoundError: No module named 'botorch'
```

### Steps to reproduce

1. `docker run --rm -it continuumio/miniconda3 bash`
2. `pip install optuna optuna-dashboard`
3. 
```python
from optuna_dashboard.preferential.samplers.gp import PreferentialGPSampler
```

**Comment by contramundum53** [comment]
@resnant 
Sorry, `botorch` is in the _optional_ dependency of `optuna`. Please install all optional dependencies with 
```
pip install optuna[optional]
```
or install dependency separately as it requires. (`BoTorchSampler` only requires `botorch`.)

We cannot make `botorch>=0.8.1` a mandatory dependency because `botorch` has large and strict child dependencies and many `optuna` users would fail to install `optuna` at all otherwise.

**Comment by contramundum53** [comment]
Maybe we should make the error message more readable, though.

**Comment by nabenabe0928** [comment]
Additional dependencies for `optuna-integration` can now installed via pip and I modified the error message so that users can easily notice.
With that, let me close this issue.
