### ISSUE TITLE
Add CI settings to check `optuna.visualization.matplotlib` module is available without `plotly`

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#5205]
### Motivation

Add CI settings to prevent bugs like https://github.com/optuna/optuna/pull/5133 

### Description

Add GitHub action workflow to trigger `pytest tests/visualization_tests/matplotlib_tests/` only when pull requests contain changes in `optuna/visualization/**.py`.

**Comment by nzw0301** [comment]
Let me close this issue because #5263 addressed this issue.
