### ISSUE TITLE
Reformat code to comply with the Black 2024 Code Style.

### ISSUE THREAD

**Issue by pkoz** [optuna/optuna#5208]
### Motivation

The [`black`](https://github.com/psf/black) library released [a new version](https://github.com/psf/black/releases/tag/24.1.0) that implements the 2024 stable style.

It breaks tests because the `black` dependency in `pyproject.toml` has no constraint on the version.

### Suggestion

- Quick fix: add the version constraint 

https://github.com/optuna/optuna/blob/073abfc520725688434b512212e910a395dd4f99/pyproject.toml#L53-L55

to:

```python
checking = [
    "black<24.0.0"
    "blackdoc",
```

- Actual fix: reformat about 30 lines of code to comply with the Black 2024 Code Style.

**Comment by nzw0301** [comment]
Thank you for reporting it. When I used the latest black I encountered the following issues: 

- https://github.com/psf/black/issues/4180
- https://github.com/psf/black/issues/4173

Thus the proposed hotfix sounds nice.
