### ISSUE TITLE
UnicodeDecodeError in optuna 3.5.0 with db.sqlite3 storage

### ISSUE THREAD

**Issue by HDembinski** [optuna/optuna#5248]
### Expected behavior

As newbie on optuna, I wrongly tried to use this call in the CLI, where `db.sqlite3` is a file on my drive in the same folder.
```
optuna --storage db.sqlite3 study-names
```

This call currently gives a complicated error message about a UnicodeDecodeError that does not indicate the true mistake; I should have used the full URL `sqlite:///db.sqlite3`. For me it is not obvious that I have to use this URL, and I expected this simpler call to work. I propose two solutions, with preference in that order:
1) For user convenience, make the call above work: optuna detects that db.sqlite3 is the path to a filename and handles this call correctly.
2) Optuna should detect that the storage is given without an URL prefix and complain with an error message that points the user towards this issue.

**Comment by nzw0301** [comment]
According to the first line of the log message, I suspect CLI reads the sqlite file as journal storage. Could you try either way

```zsh
optuna --storage sqlite:///db.sqlite3 study-names
```

or 

```zsh
optuna --storage db.sqlite3 --storage-class RDBStorage study-names
```

**Comment by HDembinski** [comment]
Thank you for the fix, the first line works. Still, I think this a UX bug. Please provide an error message for this case which points the user in the right direction or make the CLI smarter to handle the call `optuna --storage db.sqlite3 study-names` correctly. You should not expect that your users are familiar with the details of sqlite.

**Comment by nzw0301** [comment]
Thank you for your input. Could you update the title and description? Then I will re-open this issue and change the label to a more appropriate one.

**Comment by HDembinski** [comment]
Thanks, ok, done.
