### ISSUE TITLE
Feature Request: Multi-Objective Reporting and Pruning

### ISSUE THREAD

**Issue by bionicles** [optuna/optuna#5268]
### Motivation

I just switched from single to multi objective and thought more information would be helpful to prune but unfortunately it is unsupported on the reporting side and then the pruning side has nothing to build on. 

### Description

Idea: all objectives are multi-objective, even single objective ones, and all of these operate the same way the single objective case works, then there's no special case here, report can insert a row per objective, the pruner can always work on the hypervolume history of reports, which is just the history if it's single objective. The stupidest idea could be to just independently prune each objective the exact same way as before and then 

`return all(pruned_for_objective(name, trial) for name in objective_names)`
that could work to eliminate trials if and only if the pruner prunes them in each objective simultaneously, if the trials make progress on a subobjective, that keeps em alive

### Alternatives (optional)

I could make my own custom pruner and just use the intermediate values from my own database but then i need to decide how to make a multiobjective pruner! 

### Additional context (optional)

- [ ] test multiobjective reporting
- [ ] remove the conditional preventing multiobjective reporting
- [ ] report multi-objective data
- [ ] test multiobjective pruning
- [ ] map the pruner over the objective series columns and filter by 
e.g.
`pruned_trials_ser = trials_df[trials_df.map(pruner).all(axis='columns')]` 
( no progress on all objectives simultaneously )

**Comment by nzw0301** [comment]
Seems duplicated with #3450. The core team and I attempted to implement this but the PR was closed due  to https://github.com/optuna/optuna/issues/3450#issuecomment-1706109413.

**Comment by nabenabe0928** [comment]
I will close this PR because this PR relates to #3450 .
