### ISSUE TITLE
Pandas Package import is not reinforced

### ISSUE THREAD

**Issue by ashwinsnambiar** [optuna/optuna#5296]
### Expected behavior

While trying to use the study.trials_dataframe() functions, pandas dataframe object is returned. But since the setup.py doesn't have a requirement to install panda package, it causes an error. In optuna.study._dataframe.py file, there is a check to try importing pandas if available. There is no exception cause here. Should pandas be set as a requirement?

### Environment

- Optuna version:3.5.0
- Python version:3.10.13
- OS:Linux-5.15.0-94-generic-x86_64-with-glibc2.31
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
ImportError: Tried to import 'pandas' but failed. Please make sure that the package is installed correctly to use this feature. Actual error: No module named 'pandas'.
```

### Steps to reproduce

1.Run any study
```python
# python code
study.trials_dataframe().to_csv("study_results.csv")
```

**Comment by nzw0301** [comment]
`pandas` is an optional package as in 
https://github.com/optuna/optuna/blob/d132cd90e2eb3bf9d7e037ca342f0a1f693fa9bf/pyproject.toml#L83-L95.
