### ISSUE TITLE
OptGBM was released

### ISSUE THREAD

**Issue by Y-oHr-N** [optuna/optuna#534]
Hi there,

Today, I have released OptGBM.
https://github.com/Y-oHr-N/OptGBM

This package provides a scikit-learn compatible estimator that tunes the hyperparameters of LightGBM with Optuna.

If you like this package, please consider merging into Optuna. I hope this package will contribute to the development of Optuna.

Finally, #507 implements similar features, so I might be able to help you.

Thanks.

**Comment by smly** [comment]
Thank you for sharing us your nice package.
It seems well written and easy to use :+1:.
I think there are many things to consider: time-vs-performance, applicability of pruning, etc.
Let us consider how we can collaborate after releasing #507.

**Comment by smly** [comment]
Sorry for my late response.
As you mentioned, some features are duplicated with LightGBM Tuner. And merging the entire code of OptGBM might be confusing to users.

May I introduce your library as an Optuna usage example in our `examples/README.md`?
Thanks again for your contributions to the Optuna community!

**Comment by Y-oHr-N** [comment]
Sorry for the late reply.

> May I introduce your library as an Optuna usage example in our `examples/README.md`?

That is a good news for me.

We hope to discuss merging at the Optuna development sprint event on March 1. Current differences between LightGBMTuner and OptGBM that I know are as follows.
https://speakerdeck.com/yohrn/8th-place-solution-of-autowsl-2019?slide=14

**Comment by smly** [comment]
@Y-oHr-N, thanks for your comments! I'm looking forward to discussing OptGBM with you at the event.
Now that https://github.com/optuna/optuna/pull/896 is merged and OptGBM is listed in `examples/README.md`. Let me close this issue as resolved. Thanks again for your great work!

**Comment by Y-oHr-N** [comment]
Hi @smly,

I heard disappointing news that the event will be canceled.

So there are two things I want to check here.

1. Does the Optuna development team agree to merge OptGBM into Optuna?
2. If you agree, what are the topics we need to discuss, that is, what can be the obstacles to merging?

**Comment by smly** [comment]
@Y-oHr-N, I'm sorry that I cannot meet you at the dev sprint event.
Today, Optuna development members including me discussed integrating OptGBM into Optuna. In order to answer your question, we need to discuss many things with you, such as remaining development tasks, API, maintenance, and existing issues in OptGBM. If it's okay with you, let's schedule a video conference to discuss these things with us.

**Comment by Y-oHr-N** [comment]
@smly , OK. How do we communicate?

**Comment by smly** [comment]
How is Google Hangout? let me send a DM to you on Twitter.

**Comment by Y-oHr-N** [comment]
No problem. I'm waiting for a DM.
