### ISSUE TITLE
optuna create-study --storage $STORAGE_URL raises RuntimeError: The runtime optuna version 3.6.0 is no longer compatible with the table schema (set up by optuna 3.6.0). Please try updating optuna to the latest version by `$ pip install -U optuna`.

### ISSUE THREAD

**Issue by scls19fr** [optuna/optuna#5360]
Hello,

I'd like to try Optuna in Docker environment with mlflow.

I used a docker-compose file to install mlflow / mysql / minio inspired by https://github.com/Toumash/mlflow-docker

I'm trying to create a new study with optuna like so:

### Expected behavior

shouldn't raise such an error.

### Environment

```
# python3 -c 'import optuna; print(f"- Optuna version:{optuna.__version__}")'
- Optuna version:3.6.0
# python3 -c 'import platform; print(f"- Python version:{platform.python_version()}")'
- Python version:3.11.8
# python3 -c 'import platform; print(f"- OS:{platform.platform()}")'
- OS:Linux-6.1.0-18-cloud-amd64-x86_64-with-glibc2.36
```

### Error messages, stack traces, or logs

    RuntimeError: The runtime optuna version 3.6.0 is no longer compatible with the table schema (set up by optuna 3.6.0). Please try updating optuna to the latest version by $ pip install -U optuna

### Steps to reproduce

```
1. $ docker run --env-file .env --network web --entrypoint /bin/sh -it optuna/optuna:v3.6.0-py3.11
2. # STORAGE_URL="mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}"
4. # optuna create-study --storage $STORAGE_URL
Traceback (most recent call last):
  File "/usr/local/bin/optuna", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/workspaces/optuna/cli.py", line 1121, in main
    return args.handler(args)
           ^^^^^^^^^^^^^^^^^^
  File "/workspaces/optuna/cli.py", line 338, in take_action
    storage = _get_storage(parsed_args.storage, parsed_args.storage_class)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/optuna/cli.py", line 76, in _get_storage
    return RDBStorage(storage_url)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/optuna/storages/_rdb/storage.py", line 233, in __init__
    self._version_manager.check_table_schema_compatibility()
  File "/workspaces/optuna/storages/_rdb/storage.py", line 1107, in check_table_schema_compatibility
    raise RuntimeError(message)
RuntimeError: The runtime optuna version 3.6.0 is no longer compatible with the table schema (set up by optuna 3.6.0). Please try updating optuna to the latest version by `$ pip install -U optuna`
```

As it looked similar to #2812 I tried to watch content of `version_info` table and I'm getting

```
    # mysql --user=$MYSQL_USER --password $MYSQL_DATABASE
    Enter password: ...
    Reading table information for completion of table and column names
    You can turn off this feature to get a quicker startup with -A

    Welcome to the MySQL monitor.  Commands end with ; or \g.
    Your MySQL connection id is 24
    Server version: 8.3.0 MySQL Community Server - GPL

    Copyright (c) 2000, 2024, Oracle and/or its affiliates.

    Oracle is a registered trademark of Oracle Corporation and/or its
    affiliates. Other names may be trademarks of their respective
    owners.

    Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

    mysql> SELECT * FROM version_info;
    +-----------------+----------------+-----------------+
    | version_info_id | schema_version | library_version |
    +-----------------+----------------+-----------------+
    |               1 |             12 | 3.6.0           |
    +-----------------+----------------+-----------------+
    1 row in set (0.00 sec)
```

I also tried to `pip install -U optuna` but I'm still getting

    RuntimeError: The runtime optuna version 3.6.0 is no longer compatible with the table schema (set up by optuna 3.6.0)

Any idea?

**Comment by scls19fr** [comment]
I also tried the following command:

    # optuna storage upgrade --storage $STORAGE_URL

which raised a warning

    workspaces/optuna/cli.py:744: UserWarning: Your optuna version seems outdated against the storage version. Please try updating optuna to the latest version by `$ pip install -U optuna`.

and

    # optuna create-study --storage $STORAGE_URL

still raises same `RuntimeError`

**Comment by nzw0301** [comment]
Is there any tables in the database when you ran `optuna create-study`? Can you create a database from scratch?

**Comment by scls19fr** [comment]
There was some tables from mlflow.
I will try with a clean database and let you know.
Maybe using table prefix could help.

**Comment by scls19fr** [comment]
I can confirm that this problem doesn't occur with a separate database just for optuna.

**Comment by nzw0301** [comment]
Thanks. I think database for optuna should not contain MLFlow's schema.

**Comment by scls19fr** [comment]
With table prefix this kind of problem should probably be avoided. Maybe that's something which should be considered. Closing for now
