### ISSUE TITLE
Enhance `plot_parallel_coordinate()` by eliminating redundant for-loops

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#5409]
### Motivation

In parallel coordinate plot, `_is_log_scale()`, `_is_categorical()`, and `_is_numerical()` functions are invoked.

https://github.com/optuna/optuna/blob/fcffbeab86859c32c3c646947f4fd764860c922b/optuna/visualization/_parallel_coordinate.py#L213-L237

Each one of these functions iterates over the trials, which is clearly redundant.

https://github.com/optuna/optuna/blob/fcffbeab86859c32c3c646947f4fd764860c922b/optuna/visualization/_utils.py#L72-L98

### Suggestion

Making `plot_parallel_coorinate()` faster by removing wasted for-loop.

**Comment by kAIto47802** [comment]
I will take over [the PR](https://github.com/optuna/optuna/pull/5547) (I will checkout another branch from the branch created by @nzw301) and would like to solve this issue!

**Comment by kAIto47802** [comment]
This issue was resolved by

- #5587.

However, the additional issue

- #5571

related to this is still unresolved. (currently, I'm not working on this.)
