### ISSUE TITLE
Conda package not updated

### ISSUE THREAD

**Issue by jmakov** [optuna/optuna#5480]
### Expected behavior

Latest pypi published optuna vesion is 3.6.1 but latest conda package is 3.6.0

### Environment

- Optuna version:
- Python version:
- OS:
- (Optional) Other libraries and their versions:

### Error messages, stack traces, or logs

```shell
no logs
```

### Steps to reproduce

1.
2.
3.
```python
# python code
```

**Comment by nzw0301** [comment]
Thank you for reporting this. You're right according to https://anaconda.org/conda-forge/optuna, which says `3.6.0` is the latest version.

**Comment by not522** [comment]
Thank you for your report. The release process appears to be complete (https://github.com/conda-forge/optuna-feedstock/pull/64), but it has not been made public for some reason. We are investigating the cause.

**Comment by not522** [comment]
Optuna v3.6.1 is now available on https://anaconda.org/conda-forge/optuna. Sorry for the inconvenience.
