### ISSUE TITLE
GridSampler: Duplicates

### ISSUE THREAD

**Issue by ldv1** [optuna/optuna#5489]
### Expected behavior

I use the GridSampler.
In 3.2.0 it runs fine. I upgraded to 3.6.1, and now I see duplicates. If I run the code below 3 times, I might get x=0, then x=1, and then x=0 again. I hadn't such an issue with Optuna 3.2.0

```
import time
import optuna
import random
print(f"optuna: {optuna.__version__}")

def objective(trial: optuna.Trial):
    x = trial.suggest_int("x", -100, 100)
    print("Using parameters:", trial.params)
    time.sleep(20)
    return x**2

if __name__ == '__main__':
    search_space = { "x": [0, 1, 2] }
    sampler = optuna.samplers.GridSampler(search_space)
    storage = optuna.storages.RDBStorage(url="sqlite:////home/me/a.db", engine_kwargs={"connect_args": {"timeout": 100}})
    study = optuna.create_study(storage=storage,
                                sampler=sampler,
                                direction="minimize",
                                pruner=optuna.pruners.NopPruner(),
                                study_name="mystudy",
                                load_if_exists=True)
    study.optimize(objective, n_trials=3, n_jobs=1, callbacks=[optuna.study.MaxTrialsCallback(3, states=None)])
```

### Environment

- Optuna version:3.6.1
- Python version:3.11.4
- OS:Linux-5.14.21-150500.55.39-default-x86_64-with-glibc2.31

### Error messages, stack traces, or logs

```shell
python3 a.py&
[1] 4927
[I 2024-06-11 22:22:22,097] A new study created in RDB with name: mystudy
Using parameters: {'x': 0}

python3 a.py&
[2] 5026
[I 2024-06-11 22:22:26,466] Using an existing study with name 'mystudy' instead of creating a new one.
Using parameters: {'x': 1}

python3 a.py&
[3] 5117
[I 2024-06-11 22:22:31,327] Using an existing study with name 'mystudy' instead of creating a new one.
Using parameters: {'x': 0}
```

### Steps to reproduce

Run the code above.

**Comment by nzw0301** [comment]
Thank you for sharing the reproducible code! I think this is not a bug. As explained in https://optuna.readthedocs.io/en/stable/tutorial/20_recipes/001_rdb.html#resume-study, the sampler state is not stored in the storage.

**Comment by nzw0301** [comment]
Sorry, I misunderstood the issue description. I think the distributed optimisation is performed here. In this case,

As noted in https://optuna.readthedocs.io/en/stable/reference/samplers/generated/optuna.samplers.GridSampler.html

> A parameter configuration in the grid is not considered finished until its trial is finished. Therefore, during distributed optimization where trials run concurrently, different workers will occasionally suggest the same parameter configuration. The total number of actual trials may therefore exceed the size of the grid.

**Comment by nzw0301** [comment]
Hi, thank you for your clarification. I'm not sure but can you specify `seed` of `GridSampler` as a workaround? 

I suspect that https://github.com/optuna/optuna/blob/master/optuna/samplers/_grid.py#L126 is executed with different random seeds without specifying `seed` as a results, each process's grid sampler has different grid id to grid param mapping.

**Comment by ldv1** [comment]
Indeed, by fixing the seed, it works.
Big thanks for your help!
I will close this issue.
Nevertheless, it is surprising that it works fine with version 3.2.0 without setting the seed.
