### ISSUE TITLE
Expand the type of `callbacks` in `optimize` to `Iterable`

### ISSUE THREAD

**Issue by not522** [optuna/optuna#5509]
### Motivation

The type of `callbacks` in `optimize` is specified as `list`. But we can pass other `Iterable` types (e.g., `tuple`). https://optuna.readthedocs.io/en/stable/reference/generated/optuna.study.Study.html#optuna.study.Study.optimize

### Suggestion

Replace the type of `callbacks` in `optimize` from `list` to `collections.abc.Iterable`.

**Comment by karthikkurella** [comment]
@not522 , Can I open a new PR with the fix (including resolving CI runs) so as to include reviewers.

**Comment by kz4killua** [comment]
Hi. I have opened a PR #5542 resolving this issue. All CI checks run successfully.
