### ISSUE TITLE
Add scikit-image example.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#557]
Add an example code of [`scikit-image`](https://scikit-image.org/) under `examples/`.
As can be seen in [this post](https://stackoverflow.com/questions/58049246/how-to-tune-local-binary-pattern/58055243), scikit-image can be used as a feature extractor for image classification tasks, and it has some hyperparameters.

**Comment by sile** [comment]
Merged: https://github.com/optuna/optuna/pull/730
