### ISSUE TITLE
`report_cross_validation_scores()` in combination with `TerminatorCallback()`  needs `torch` dependency

### ISSUE THREAD

**Issue by thomasATbayer** [optuna/optuna#5616]
### Motivation

There is the really nice feature that allows the tuning to stop earlier if there has been no variance in the objective for some iterations. But this needs a torch dependency. This makes python environments quite huge (several GB) and also introduces a large number of extra packages.

### Description

So would be great if report_cross_validation_scores() in combination with TerminatorCallback() would run without a torch dependency.

**Comment by kAIto47802** [comment]
Are you trying to run in a Linux environment? If so, `pip install torch` will install torch for CUDA, which is much larger than the cpu version, while the cpu version is installed by default in MacOS and Windows. So specifying the cpu version and installing it may solve the problem, as the terminator only depends on the cpu version of the torch. You can do this by running
`pip install torch --index-url https://download.pytorch.org/whl/cpu`

**Comment by nabenabe0928** [comment]
@thomasATbayer 
Did the response by @kAIto47802 resolve your issue?
If so, I would like to close this issue.

**Comment by thomasATbayer** [comment]
> @thomasATbayer Did the response by @kAIto47802 resolve your issue? If so, I would like to close this issue.

Yes, many thanks for the help. That should solve the issue.
