### ISSUE TITLE
Multiobjective pruner

### ISSUE THREAD

**Issue by Xixaus** [optuna/optuna#5662]
### Don't use GitHub Issues to ask support questions.

Is there a pruner in Optuna for multi-objective optimization? If so, how can I use it? I'm seeking guidance on implementing a pruner that can simultaneously handle multiple objectives. Any examples or documentation would be greatly appreciated. Thanks!

**Comment by nzw0301** [comment]
Please see https://github.com/optuna/optuna/issues/3450
