### ISSUE TITLE
trial_id to reset to zero for every study

### ISSUE THREAD

**Issue by loewenm** [optuna/optuna#5697]
### Motivation

Usage of a single database to house multiple studies results in an ever increasing trial_id number. We'd like to see trial_id be specific to a particular study instead of to the entire database. 

In other words, why is the trial_id number shared across studies?

### Description

When using a single database to house multiple studies, the usage of study._trial_id results in an ever increasing trial_id value across studies.

For example: 
Suppose I have a study _ABC_ with 100 trials in it and then start a new study called _DEF_ with another 100 trials in it.
This will result in study _ABC_'s trial_id's ranging [0, 100) and study _DEF_'s trial_id's ranging [100, 200).

### Alternatives (optional)

Please have trial_id's as a property of each individual study instead of the entire database.

### Additional context (optional)

I am extracting the trial_id as a property of the trial via the following:

```
study = optuna.create_study(params)
study.optimize(lambda trial: optuna_objective(trial), n_trials=100)

def optuna_objective(trial, **kwargs):
    params = ModelConfig(
        batch_size=2 ** trial.suggest_int("batch_size", 4, 11),
    )

    valid_results = train_model(params, trial_id=trial._trial_id)   # <<< HERE!!! trial._trial_id

    return valid_results["objective"]
```

What's strange is that if I return the study's trials via 'study.trials_dataframe()', the correct (intended) trial_id's are displayed...

So, somewhere, someone has accounted for trial_id numbers being shared across studies, but didn't correct the root cause.

Edit: Or is there a better way to extract the trial_id of a study's trial during runtime that matches study.trials_dataframe()?

**Comment by nabenabe0928** [comment]
Did you check `trial.number`?
That's exactly what you want.

**Comment by loewenm** [comment]
Ah! Thank you for this.

Perhaps the naming convention should be consistent across documentation and parameters to reduce confusion in the future. A clear description of trial.number and trial._trial_id and how it's referenced in both Optuna and Optuna Dashboard would be helpful. I say this because nearly everything mentions what should be _trial.number_ as _trial_id_.
