### ISSUE TITLE
Missing trial parameter

### ISSUE THREAD

**Issue by rustamzh** [optuna/optuna#5721]
### Expected behavior

In a study with ~160 trials, only 47 trials have a parameter present, in all others it is missing in the database. The parameter is essential for running the model.

defined as

`d_rounds=trial.suggest_int("d_rounds", 1, 10)`

There are no if statements in the code.

After checking the parameter table, only value '2' is missing among sampled values.

Right now trials are present in all 4 states with the missing parameter.

### Environment

- Optuna version:4.0.0
- Python version:3.8.18
- OS:Linux-5.15.0-113-generic-x86_64-with-glibc2.10

### Error messages, stack traces, or logs

```shell
No errors
```

### Steps to reproduce

It can be hard reproduce due to randomness and lack of any errors

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us? https://stackoverflow.com/help/minimal-reproducible-example

**Comment by nzw0301** [comment]
Even though reproducing the results is difficult, we can't help you with the current issue description. Can you share the code even if it is not reproducible?

**Comment by nzw0301** [comment]
Cool! Then could you use a dummy data instead of your data? In addition sharing the command would be helpful. I think this issue looks more like question l. I'm going to convert to discussion.
