### ISSUE TITLE
Axis tick scale in `plot_contour` with Matplotlib backend

### ISSUE THREAD

**Issue by sulan** [optuna/optuna#5774]
### Expected behavior

When I plot with `optuna.visualization.matplotlib.plot_contour`, the horizontal and vertical ticks are set for each subfigure.

The subfigures on the diagonal are empty (as it should be), but the ticks are always scaled linearly. This is inconsistent with the off-diagonal subfigures in the corresponding columns/rows, where the axis ticks are logarithmic for logarithmic parameters.

This is only a problem (annoyance) in the first row and the last column, since the tick labels (which are rendered on the left and the bottom of the figure) do not correspond to the actual subfigures they should be describing.

### Environment

- Optuna version: 4.0.0
- Python version: 3.12.7
- OS: Linux-6.11.7-arch1-1-x86_64-with-glibc2.40
- (Optional) Other libraries and their versions:
    - Matplotlib: 3.9.2

### Error messages, stack traces, or logs

```shell
-
```

### Steps to reproduce

1. Create a study with at least 3 parameters that has logarithmic scale
2. Load and plot:

```python
import optuna
study = optuna.load_study(...)
import optuna.visualization.matplotlib as vis
vis.plot_contour(study)
import matplotlib.pyplot as plt
plt.show()
```

### Additional context (optional)

This bug does not appear with the Plotly backend.

**Comment by nzw0301** [comment]
Hi, could you share minimal reproducible codes with us?

**Comment by sulan** [comment]
Yes, sorry:

```python
import optuna
import matplotlib.pyplot as plt
import optuna.visualization.matplotlib as vis
    
def f(trial):
    trial.suggest_float('a', 1, 10, log=True)
    trial.suggest_float('b', 100, 1000, log=True)
    trial.suggest_float('c', 1000, 10_000, log=True)
    return 1.0
    
study = optuna.create_study()
study.optimize(f, n_trials=100)
vis.plot_contour(study)
plt.show()
```

**Comment by not522** [comment]
Thank you for your bug report.

The following early return seems to be the cause of this bug. We need to fix the logic of `_generate_contour_subplot`.

https://github.com/optuna/optuna/blob/101b1e81841d26ee3bae17268cb9e89679629a77/optuna/visualization/matplotlib/_contour.py#L275-L277

**Comment by sulan** [comment]
The log scale issue can be resolved by the following modification:

```python
    if len(info.xaxis.indices) < 2 or len(info.yaxis.indices) < 2:
        ax.label_outer()
        return None

    ax.set(xlabel=info.xaxis.name, ylabel=info.yaxis.name)
    ax.set_xlim(info.xaxis.range[0], info.xaxis.range[1])
    ax.set_ylim(info.yaxis.range[0], info.yaxis.range[1])
    ax.set_xscale('log' if info.xaxis.is_log else 'linear')
    ax.set_yscale('log' if info.yaxis.is_log else 'linear')

    if info.xaxis.name == info.yaxis.name:
        ax.label_outer()
        return None
```

But the problem is that it doesn't work with categorical either. If I understand correctly, the ticks for categorical plots are calculated in `_calculate_axis_data`, which is an inner function of `_calculate_griddata`. Would it make sense to extract that function so that it can be called in `_generate_contour_subplot` as well?
https://github.com/optuna/optuna/blob/77e5b8d2a9d9990fa394cbe8cc905017514e7e13/optuna/visualization/matplotlib/_contour.py#L203-L210

**Comment by not522** [comment]
> But the problem is that it doesn't work with categorical either. If I understand correctly, the ticks for categorical plots are calculated in _calculate_axis_data, which is an inner function of _calculate_griddata. Would it make sense to extract that function so that it can be called in _generate_contour_subplot as well?

It sounds good. `_calculate_griddata` seems complex and can be split into axis data calculation and plotting values.
