### ISSUE TITLE
Use `study.ask` in tests instead of `create_new_trial`

### ISSUE THREAD

**Issue by not522** [optuna/optuna#5804]
### Motivation

The tests sometimes use lengthy implementation to create new trials, `Trial(study, study._storage.create_new_trial(study._study_id))`, it can be replaced with `study.ask()`.

https://github.com/optuna/optuna/blob/4e4a7761b6cbb5e4dd6897f0846a6c33e72cceab/tests/trial_tests/test_trial.py#L41

### Suggestion

The codes are in the following file:

- [x] [trial_tests/test_trial.py](https://github.com/optuna/optuna/blob/master/tests/trial_tests/test_trial.py) @unKnownNG 
- [x] [pruners_tests/test_percentile.py](https://github.com/optuna/optuna/blob/master/tests/pruners_tests/test_percentile.py) @fusawa-yugo 
- [ ] [pruners_tests/test_successive_halving.py](https://github.com/optuna/optuna/blob/master/tests/pruners_tests/test_successive_halving.py)

**Comment by unKnownNG** [comment]
Hello,
I would like to take on this issue. I have referred to the issue, just simply changing `trial = Trial(study, study._storage.create_new_trial(study._study_id))` to `study.ask()` is enough??

**Comment by not522** [comment]
`study = create_study(storage=storage, sampler=sampler)` follows Optuna's usual manner. So, please leave it as it is.

**Comment by fusawa-yugo** [comment]
I'd like to take pruners_tests/test_percentile.py.
