### ISSUE TITLE
Hide methods and attributes derived from `Enum.IntEnum` from the `optuna.trial.TrialState` documentation.

### ISSUE THREAD

**Issue by y0z** [optuna/optuna#5830]
### What is an issue?

This issue is similar to https://github.com/optuna/optuna/issues/5829.

In the [optuna.trial.TrialState](https://optuna.readthedocs.io/en/stable/reference/generated/optuna.trial.TrialState.html) documentation, some methods and attributes derived from `Enum.IntEnum` are shown.
However, it is not helpful to users. Therefore, we want to hide the information about these elements from the doc.

<img width="814" alt="image" src="https://github.com/user-attachments/assets/60bccb0d-61ad-441c-87ea-9c2f2850a092">

**Comment by fusawa-yugo** [comment]
I'd like to take on the issue.

**Comment by y0z** [comment]
Based on the discussion at https://github.com/optuna/optuna/pull/5863, we cannot find a simple solution.
Therefore, I close this issue at the moment.
