### ISSUE TITLE
Apply lazy import for `optuna.dashboard`.

### ISSUE THREAD

**Issue by g-votte** [optuna/optuna#589]
Optuna always imports the dependencies of `optuna.dashboard` (e.g., `bokeh`), which makes unnecessary overhead in many use cases. Similar to #334, we can apply lazy import for them.

**Comment by sshkhr** [comment]
Hi @g-votte I am new to optuna and was looking to apply for the GP-BO-based sampler project for GSoC 2020. I think this could be a good first issue for me to get started. Is someone already working on this or else I'll send in a PR?

**Comment by g-votte** [comment]
@sshkhr 
Sure! Please go for it.

I think this is one of good-to-first issues to grasp how to make a PR.
After that, we can deep dive into implementing a sampler class.

**Comment by ytsmiling** [comment]
Hi, I'd like to work on this issue.
I think applying lazy-import for `optuna.dashboard` itself requires smaller changes than applying it for its dependencies (e.g., ```bokeh```, ```tornado```). 
Can I go in this direction?

**Comment by sile** [comment]
@ytsmiling Please give it a start!
However, if you (sshkhr) have already started to address this issue, please let us know. > @sshkhr

> I think applying lazy-import for `optuna.dashboard` itself requires smaller changes than applying it for its dependencies (e.g., `bokeh`, `tornado`).

Sounds good. I think that Optuna's `integration` modules also adapt that approach for lazy importing (c.f. [optuna/integration/\_\_init\_\_.py](https://github.com/optuna/optuna/blob/master/optuna/integration/__init__.py)).

**Comment by sshkhr** [comment]
Hi @ytsmiling please go ahead with the implementation. My schedule has been badly affected by COVID-19 and unfortunately, I won't be able to work on this anytime soon. I'd still love to contribute to optuna sometime in the future.
