### ISSUE TITLE
Visualization is not customizable

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#601]
The visualization APIs in Optuna are clean and minimalistic but does not offer customizations that could be useful such as 
- changing the plot title
- changing the colors

It might be worth discussion extending the APIs by e.g. introducing new parameters to the plot functions or expose the plotly data structures to the user in order to allow controlling the results.

**Comment by c-bata** [comment]
It seems to be resolved. #602 is also.

**Comment by smly** [comment]
Changing the plot title is now available using `Figure`'s  `update_layout()`.

I'm not sure if there's a way to change the colors using `Figure` object.

**Comment by hvy** [comment]
I'm not sure this is true for all different kinds of plots but you can e.g. change the colors in the (first subplot in a) scatter plot via `figure.data[0].marker['colorscale'] = 'Green'`, and then redraw using for instance `fig.show()`. It seems like a `Figure` is quite flexible.

**Comment by smly** [comment]
Great! Thanks for the useful info. Then I think this issue has been resolved.

**Comment by hvy** [comment]
Oh, thanks for the quick response. I think so too. It's simpler to solely rely on `plotly` for the customization, instead of separating the responsibility. It's always possible to extend the APIs if deemed necessary. Let me close this issue for now 🙂.
