### ISSUE TITLE
Visualization is always interactive

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#602]
Visualization requires the user to be interactive and does e.g. not allow writing the figures to images. If you run the optimization script on some server e.g. in the background, this could be useful.

It might be worth discussion extending the APIs by e.g. introducing new functions, parameters to save the figures or expose the plotly data structures to the user in order to allow controlling the results.

**Comment by c-bata** [comment]
A `write_image` method provided by Plotly might be enough for this issue.
https://plot.ly/python/static-image-export/

**Comment by smly** [comment]
Resolved by https://github.com/optuna/optuna/issues/601.

**Comment by hvy** [comment]
A nitpick and you're absolutely right that this issue is fixed but maybe you meant by https://github.com/optuna/optuna/pull/704 ? #601 is another issue that I noticed you just commented on. Thanks! 🙂

**Comment by smly** [comment]
Oops! Updated the comment. Thank you!
