### ISSUE TITLE
Axis labels of parallel coordinate plots overlap if the parameter names are long.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#612]
As you can see in the following image, axis labels overlap when parameter names are too long. I think we can solve this issue if we limit the maximum length of the labels and/or tilt the labels.

![newplot (39)](https://user-images.githubusercontent.com/3255979/66977250-19efd780-f0e0-11e9-87ba-a6616083da31.png)

**Conditions**
- Optuna version: 0.17.1
- Python version: 3.7.2
- OS: macOS 10.13

**Code to reproduce**

```python
import optuna

def objective(trial):
    x = trial.suggest_uniform('x' * 100, -10, 10)
    y = trial.suggest_uniform('y' * 100, -10, 10)
    return x - y

study = optuna.create_study()
study.optimize(objective, n_trials=20)

optuna.visualization.plot_parallel_coordinate(study)
```

**Comment by cafeal** [comment]
`go.Parcoords` have a parameter `labelangle` in `line` optsion here.
https://github.com/pfnet/optuna/blob/master/optuna/visualization.py#L435-L443

Though the title overlaps with feature names, it can improve this visualization like below (this is the case when `labelangle=30`)
![image](https://user-images.githubusercontent.com/6898958/67848031-3d3a6e00-fb47-11e9-8e97-cfde9ab02232.png)
