### ISSUE TITLE
`nbviewer.jupyter.org` reports 503 errors.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#617]
`nbviewer.jupyter.org` shows Optuna's example notebooks nicely, but it sometimes reports 503 errors as follows: `nbviewer: Error 503 No healthy backends`.
Does anyone have ideas for alternatives of `nbviewer.jupyter.org`.

**Comment by c-bata** [comment]
I think the one solution is to publish with sphinx documentation using nbsphinx.
https://nbsphinx.readthedocs.io/

**Comment by toshihikoyanase** [comment]
> nbsphinx

Sounds good! 
IMO,  `nbsphinx` is also applicable to the tutorials so that users can interact with the content easily.
Thank you for your information.

**Comment by toshihikoyanase** [comment]
Now that we have also hosted the notebook in Google Colab, we can replace `nbviewer.jupyter.org` with it. I'd like to create a PR and close this PR.
