### ISSUE TITLE
Add CI build for Python 3.8

### ISSUE THREAD

**Issue by smly** [optuna/optuna#623]
Fairly self-explanatory. [Python 3.8](https://docs.python.org/3/whatsnew/3.8.html) was released on Oct 14.

Checklist:

* [ ] Update build environment for `checks`, `codecov` and `document`.
* [ ] Add `tests-python38` circle CI job.

**Comment by hvy** [comment]
I just changed to label in this PR to the new `CI` label. Please let me know if it's unclear.

**Comment by sile** [comment]
Python3.8 has been added to the CI targets by https://github.com/optuna/optuna/pull/759.
