### ISSUE TITLE
Low test coverage in the visualization module.

### ISSUE THREAD

**Issue by g-votte** [optuna/optuna#626]
Many scenarios are not tested in the visualization module, and we should add test cases for them. For example, the following lines currently do not have any test cases despite that they seem testable.

https://github.com/pfnet/optuna/blob/0b8187b9c919773f38fb66ceb2a3cd9da543a874/optuna/visualization.py#L80-L83

https://github.com/pfnet/optuna/blob/0b8187b9c919773f38fb66ceb2a3cd9da543a874/optuna/visualization.py#L158-L159

https://github.com/pfnet/optuna/blob/0b8187b9c919773f38fb66ceb2a3cd9da543a874/optuna/visualization.py#L224-L226

https://github.com/pfnet/optuna/blob/0b8187b9c919773f38fb66ceb2a3cd9da543a874/optuna/visualization.py#L246-L271

https://github.com/pfnet/optuna/blob/0b8187b9c919773f38fb66ceb2a3cd9da543a874/optuna/visualization.py#L281-L283

https://github.com/pfnet/optuna/blob/0b8187b9c919773f38fb66ceb2a3cd9da543a874/optuna/visualization.py#L284-L286

https://github.com/pfnet/optuna/blob/0b8187b9c919773f38fb66ceb2a3cd9da543a874/optuna/visualization.py#L381-L383

https://github.com/pfnet/optuna/blob/0b8187b9c919773f38fb66ceb2a3cd9da543a874/optuna/visualization.py#L400-L403

**Comment by sile** [comment]
This issue has been resolved by https://github.com/optuna/optuna/pull/630.
