### ISSUE TITLE
Feature request: Simple brute force of parameter grid

### ISSUE THREAD

**Issue by roseaysina** [optuna/optuna#656]
Hola! 

As I understand from the docs, there is no any methods for trial that simply iteratively do through parameter grid.
The closest one is `suggest_discrete_uniform(name, low, high, q)`, but it samples values from the distribution.

What I need: simple brute force of such grids.
For example, for grid `(low=1, high=5, q=1)` it produces 5 trials with parameter values of `[1, 2, 3, 4, 5]` (exclusive or inclusive end). Or the same behaviour with `suggest_categorical(name, [1, 2, 3, 4, 5])`.

Details:
Why I need this: for heavy models I want to see the dependancy of target metrics on simple parameters which behaviour I can predict. For example, if `param=0` metrics will be low and if `param=1000` metrics should be high and I run study for 3-4 values of `param` and see that whether it's true or not. It is also useful when you don't know even the rough the boundaries of given parameter.

So the main reason is just to give Optuna predefined grid, run trials on its values and save results. No sampling, no pruning, just brute force controlled by user. 

Why `suggest_discrete_uniform` is not good for this: it _samples_ values, so for `(low=1, high=5, q=1)` I can have `[1, 2, 2, 5, 4]` (in general case not complete and with duplicates).

What I do now: several runs of mentioned `suggest_discrete_uniform` with proper boundaries (for value of 5 it will be `suggest_discrete_uniform(low=5, high=5, q=1)`, and so on for each value I need). Of course, I can just do this by myself but I don't want write another messy optimiser along with Optuna :)

One of the problems (I can see as a user) for this feature is that `n_trials` should be compatible with number of values in the resulting grid. 

If you think it's bad/not useful feature, please let me know before deleting the issue :)

Thanks!

**Comment by g-votte** [comment]
Hi @roseaysina ,

Thanks for your feature request!

We’ve got similar requests even from other users and been planning to implement `GridSearchSampler`, whose interface will be something like: 

```python
import optuna

def objective(trial):
    x = trial.suggest_uniform('x', -100, 100)
    y = trial.suggest_int('y', -100, 100)
    return x ** 2 + y ** 2

grid = {
    'x': [-50, 0, 50],
    'y': [-99, 0, 99]
}
study = optuna.create_study(sampler=GridSearchSampler(grid))
study.optimize(objective)
```

**Comment by roseaysina** [comment]
Hi @g-votte,

Thanks for reply! I am glad that there are another similar requests) 

The code snippet looks great. The only question is that for several parameters is it going to be cartesian product of corresponding grids (like all combinations)?
