### ISSUE TITLE
Support log scale axes in parallel coordinate plots.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#669]
The current parallel coordinate plot does not support log scale axes, and it is hard to analyze the results. For instance, in the following figure, `x` and `y` are sampled from `UniformDistribution` and `LogUniformDistribution`, respectively. Both parameters are randomly sampled, but the values of `y` gather around `0` while those of `x` are uniformly distributed.

![newplot (38)](https://user-images.githubusercontent.com/3255979/68287656-6cf8f100-00c6-11ea-9367-b71770d3c2b6.png)

According to this issue (https://github.com/plotly/plotly.js/issues/2292), plotly does not support log scale axes in parallel coordinate plots for now. If plotly supports it, please implement log scale axes in parallel coordinate plots.

**Comment by toshihikoyanase** [comment]
This is still an open issue.

**Comment by hvy** [comment]
Should we close this issue given that #2164 is merged? Cc. @himkt

**Comment by himkt** [comment]
Thank you @hvy. Yes we can close it now.
