### ISSUE TITLE
a method for deleting trials

### ISSUE THREAD

**Issue by dwiel** [optuna/optuna#685]
It should be possible to delete individual trials from studies.

## Motivation

There are many reasons you might want to remove a trial from a study. Some examples include:

- a trial has been determined to be invalid
- old trials are no longer relevant
- in an evolutionary search where trials represent individuals

**Comment by sile** [comment]
Thank you for your proposal!

We plan to introduce an API that allows users to change the state of a trial as follows:
```python
for trial in study.trials:
    if "the trial is invalid":
        # [New API]
        # Sets the state of the trials to `FAIL`.
        # Failed trials aren't considered when sampling new parameters.
        study.set_trial_state(trial, optuna.structs.TrialState.FAIL)
```

Does this API satisfy your requirements?

**Comment by dwiel** [comment]
Yeah I think that should do the trick, thanks!

**Comment by louisabraham** [comment]
Hi, great thread!

- Do you still consider adding this method?

- How are FAIL-ed trials handled by the samplers? Is is really equivalent to deleting the trials?

- I think I would still like to have a delete_trial method to clean a history

**Comment by sile** [comment]
@louisabraham Thank you for the questions!

> Do you still consider adding this method?

Yes. Although it's not the highest priority task, we would like to provide the API (`set_trial_state()`) in the future.

> How are FAIL-ed trials handled by the samplers? Is is really equivalent to deleting the trials?

As you wrote, all of the current built-in samplers just ignore failed trials when they sample new parameters. Thus, failed trials can be regarded as deleted in the samplers' perspective (it's implementation-dependent though).

> Maybe it should be documented.

Sounds good. BTW, if you're interested in contributing Optuna, a PR to update the documentation is welcome.

> I think it would still be useful to have a delete_trial method to clean a history but...

I absolutely agree with your opinion. #821 seems a reasonable alternative.

**Comment by HideakiImamura** [comment]
Hi all. 

The main objective of this Issue is to delete trials from a study. This is discussed in Issue #821. And the sub-objective to add the documentation around FAIL-ed trials is already addressed in PR #1214. So I will close this Issue.

If there are any problems, I will re-open this Issue.

**Comment by Markus28** [comment]
In my opinion this would still be a nice feature to have, especially for doing hotfixes to studies that are currently running. It's my understanding that I would currently have to stop the running study, create a new one, copy all old trials over, filter out the bad ones, then start the new study. Just marking some trials as failed would be much more convenient.

**Comment by senzeyu** [comment]
The proposed solution doesn't quite work for trials that are in the COMPLETE state. Why can't we change the states of obsolete trials if they are finished?

> Thank you for your proposal!
> 
> We plan to introduce an API that allows users to change the state of a trial as follows:
> 
> ```python
> for trial in study.trials:
>     if "the trial is invalid":
>         # [New API]
>         # Sets the state of the trials to `FAIL`.
>         # Failed trials aren't considered when sampling new parameters.
>         study.set_trial_state(trial, optuna.structs.TrialState.FAIL)
> ```
> 
> Does this API satisfy your requirements?

**Comment by Koowah** [comment]
Hello,

Has the API to achieve this been introduced ? Or is there any other way to delete trials ?

Thanks 😄

**Comment by sergeyleyko** [comment]
+100500

**Comment by nzw0301** [comment]
Hi, could you clarify your motivation to introducing this method rather than just upvoting. I think replacing trial state sounds enough.

**Comment by sergeyleyko** [comment]
Ok, so, here is the problematic flow:

**Comment by nzw0301** [comment]
Thanks. I tried writing such code, but I could not understand how to get step 6. Do you optimise it with `n_jobs != 1` or multi-process? I think you just need to enqueue the failed trial, not need to delete them.

```python
import optuna

# buggy objective.
def obj(t: optuna.Trial):
    if t.number == 2:
        return None
    return t.suggest_int("x", 0, 100)
    
study = optuna.create_study()
for i in range(5):
    study.enqueue_trial({"x": i})

study.optimize(obj, n_trials=3)

# fixed
def obj(t: optuna.Trial):
    return t.suggest_int("x", 0, 100)
study.optimize(obj, n_trials=2)

# add failed params.
study.enqueue_trial({"x": 2})
study.optimize(obj, n_trials=1)
```

**Comment by sergeyleyko** [comment]
Step 6 - start the tuning script again, enqueue all the trials again (hoping that at least 3-5 will be run)
Current Behavior: Optuna says that 4-5 already exists (at the enqueue time), and wont execute them.
Expected Behavior: it enqueue and executes trials 4-5 (skips 3 as it crashes)

**Comment by nzw0301** [comment]
Sorry, I cannot fully understand the situation; especially, `Current Behavior` sounds strange compared with the Optuna behaviour described in the previous code block. Could you share the minimal reproducible script?

**Comment by sergeyleyko** [comment]
Tried to create a reproducible code, that replicates the issue:
```

import optuna

def do(crash=False):
    # buggy objective.
    def obj(t: optuna.Trial):
        if t.number == 2 and crash:
            raise ValueError
        return t.suggest_int("x", 0, 100)

    study = optuna.create_study(storage='sqlite:///test.db',
                                study_name='test',
                                direction='maximize',
                                load_if_exists=True)
    for i in range(5):
        study.enqueue_trial({"x": i},
                            skip_if_exists=True)

    study.optimize(obj, n_trials=10)


if __name__ == '__main__':
    try:
        do(True)
    except:
        print('failed as expected')
    do(False)
```
But it works as expected, so don't bother, sorry, probably I missed something when faced with the problem. But adding the **delete** trial method doesn't look complicated anyway.

**Comment by eafpres** [comment]
I have run into this issue recently when a trial (or trials) created an anomalous result but I'd like to continue the optimization.  The anomaly is retrieved in best_trials so the optimizer thinks it is good.  

From reading this thread and some others it seems the API to set a trial to FAILED after COMPLETE was never implemented, and there is also no method to delete.  So is the recommended work-around to build a new study without the offending trials and use that?

**Comment by TuskActIV** [comment]
I managed to work around the issue this way:
```
        study = optuna.load_study(study_name=exp_config.name, storage=sqlite_uri)
        trials = study.get_trials(deepcopy=False)
        completed_trials = list(
            [
                trial
                for trial in trials
                if trial.state not in {optuna.trial.TrialState.RUNNING, optuna.trial.TrialState.WAITING}
            ]
        )
        if len(trials) != len(completed_trials):
            print(f"Some trials are not completed, will keep {len(completed_trials)} out of {len(trials)}")
            optuna.delete_study(study_name=exp_config.name, storage=sqlite_uri)
            study = optuna.create_study(
                study_name=exp_config.name,
                storage=sqlite_uri,
                load_if_exists=True,
                direction="minimize",
            )
```

**Comment by MLfreakPy** [comment]
Please re-open, the issue seems not resolved and is highly needed. Please correct me otherwise.

**Comment by profPlum** [comment]
@MLfreakPy And all others who reach this issue via google. This feature has already been implicitly implemented. Although it is not documented how to do it, you can do it like this:

```
import optuna
for trial in study.trials:
    if "the trial is invalid":
        # Sets the state of the trials to `FAIL`.
        # Failed trials aren't considered when sampling new parameters.
        study.tell(trial.number, state=optuna.trial.TrialState.FAIL)
```

This is very similar to the API originally suggested by @Sile, and it doesn't require that you have used the ask() interface earlier, it can be done as a post-processing step!

**Comment by leo-hstone** [comment]
Hi @profPlum may I add a note here also for future visitors. This can not be applied to completed trials:
```
ValueError: Cannot tell a COMPLETE trial.
```
So this is not an option to invalidate completed trials in hindsight (Version 4.5.0)
