### ISSUE TITLE
Discussion : Meta-learning  hyperparameters

### ISSUE THREAD

**Issue by arita37** [optuna/optuna#695]
Hello,

This is to start a fruitful discussion on Meta-Learning Hyper-parameters,
and potentially with well designed Optuna.

Problem :  
   Given a NNEt and a dataset, and optimal Hyper-parameters, 
    is there a way to learned some patterns about this Hype-parameters using various datasets ?
   (keep same Nnet).

   In the general case, different NNet and different datasets.

Some papers on that topics
https://arxiv.org/pdf/1911.02590.pdf

https://arxiv.org/abs/1712.06283

http://proceedings.mlr.press/v80/franceschi18a/franceschi18a.pdf

Some initial thoughts :  
   Research on the problem is still recent, 

   Experimental data (synthetic data) and a fixed Nnet would allow to test
   the distribution of optimal Hypers.

**Comment by arita37** [comment]
This is a good reference on Meta Learning for Hyper-parameter search :  
https://ml.informatik.uni-freiburg.de/papers/15-AAAI-MI-SMBO.pdf

Believe meta-learning will be key in Hyper-parameters at some point in the future....

**Comment by arita37** [comment]
Additional ressource on meta learning
and hyper parameter search :

https://arxiv.org/pdf/1712.06283.pdf

**Comment by toshihikoyanase** [comment]
Hi @arita37 
We have a development sprint on March 1 at Otemachi, Tokyo. I think it would be a good opportunity to discuss AutoML and Optuna. If you are interested in the event, please join it via 
https://optuna.connpass.com/event/163940/.

**Comment by arita37** [comment]
Hello,

Thanks for sharing, thats look interesting.
I have my small son to manage,
but I will try to join it.

Thanks

**Comment by toshihikoyanase** [comment]
@arita37 Oh! I see. Family comes first.
If possible, I'm looking forward to seeing you.

**Comment by arita37** [comment]
In any case,
Can we discuss over chat channel ?

I was busy by other topic 
but interest in this topic.

**Comment by toshihikoyanase** [comment]
> Here, some interface using optuna as Backend (!)
> https://github.com/arita37/mlmodels/blob/dev/mlmodels/optim.py

It supports the pruning feature. Cool!
Currently, it only use MedianPruner, but [HyperbandPruner](https://optuna.readthedocs.io/en/stable/reference/pruners.html#optuna.pruners.HyperbandPruner) is available since v1.1.0. The HyperbandPruner showed better performance than MedianPruner in [this benchmark result](https://gist.github.com/sile/18fc40dbc597d588aad7216443877f24). Please try it in your tasks if you have time.

**Comment by arita37** [comment]
Thanks, will check it
in mlmodels.

Role of mlmodels is to be framework agnostic
and various models and optimisers.


If you have some comments on mlmodels,
feeel free.

**Comment by arita37** [comment]
Google published a paper on meta-learning
meta-dataset :
https://github.com/google-research/meta-dataset


My hypothesis is
   Hyper-parameter is strongly related to meta-learning trough searching the transition distribution : 
   P(X—>Y)

where X and Y are 2 datasets.
In the case of hyper params, 
X and Y are same datasets with at different time
