### ISSUE TITLE
Use function annotation syntax for Type Hints.

### ISSUE THREAD

**Issue by c-bata** [optuna/optuna#711]
After dropping Python 2.7 support at #710, we can define type hints with function annotation syntax. 
~~Do you have a plan to update the coding style guideline?~~
https://github.com/optuna/optuna/wiki/Coding-Style-Conventions

## Progress

- [x] `optuna/integration/sklearn.py` (#1735)
- [x] `optuna/study.py` - assigned to harpy

## Note to the questioner

We still cannot use variable annotation syntax introduced by [PEP 526](https://www.python.org/dev/peps/pep-0526/) because we supports Python 3.5.

**Comment by hvy** [comment]
Thanks for bringing this up. There is a tracking issue now so let me just leave a reference. https://github.com/optuna/optuna/issues/713. I believe you are correct in that the coding style guideline should be updated.

**Comment by keisuke-umezawa** [comment]
@c-bata 
List of files grepped by `# type:`.

- [ ] setup
- [ ] optuna/visualization/parallel_coordinate
- [ ] optuna/visualization/slice
- [ ] optuna/visualization/intermediate_values
- [ ] optuna/visualization/optimization_history
- [ ] optuna/visualization/utils
- [ ] optuna/visualization/contour
- [ ] optuna/logging
- [ ] optuna/storages/rdb/models
- [ ] optuna/storages/rdb/storage
- [ ] optuna/storages/__init__
- [ ] optuna/storages/base
- [ ] optuna/storages/in_memory
- [ ] optuna/trial
- [ ] optuna/pruners/hyperband
- [ ] optuna/pruners/successive_halving
- [ ] optuna/pruners/nop
- [ ] optuna/pruners/median
- [ ] optuna/pruners/base
- [ ] optuna/pruners/percentile
- [ ] optuna/integration/cma
- [ ] optuna/integration/lightgbm
- [ ] optuna/integration/mxnet
- [ ] optuna/integration/chainermn
- [ ] optuna/integration/lightgbm_tuner/optimize
- [ ] optuna/integration/lightgbm_tuner/alias
- [ ] optuna/integration/lightgbm_tuner/__init__
- [ ] optuna/integration/lightgbm_tuner/sklearn
- [ ] optuna/integration/fastai
- [ ] optuna/integration/keras
- [ ] optuna/integration/__init__
- [ ] optuna/integration/pytorch_ignite
- [ ] optuna/integration/tensorflow
- [ ] optuna/integration/skopt
- [ ] optuna/integration/pytorch_lightning
- [ ] optuna/integration/xgboost
- [ ] optuna/integration/sklearn
- [ ] tests/pruners_tests/test_percentile
- [ ] tests/pruners_tests/test_median
- [ ] tests/pruners_tests/test_successive_halving
- [ ] tests/pruners_tests/test_nop
- [ ] tests/pruners_tests/test_hyperband
- [ ] tests/test_logging
- [ ] tests/integration_tests/test_skopt
- [ ] tests/integration_tests/test_pytorch_lightning
- [ ] tests/integration_tests/test_cma
- [ ] tests/integration_tests/test_lightgbm
- [ ] tests/integration_tests/test_chainermn
- [ ] tests/integration_tests/lightgbm_tuner_tests/test_optimize
- [ ] tests/integration_tests/lightgbm_tuner_tests/test_alias
- [ ] tests/integration_tests/test_pytorch_ignite
- [ ] tests/integration_tests/test_tensorflow
- [ ] tests/integration_tests/test_keras
- [ ] tests/integration_tests/test_mxnet
- [ ] tests/integration_tests/test_fastai
- [ ] tests/integration_tests/test_chainer
- [ ] tests/integration_tests/test_tfkeras
- [ ] tests/integration_tests/test_integration
- [ ] tests/integration_tests/test_xgboost
- [ ] tests/integration_tests/test_sklearn
- [ ] tests/integration_tests/test_sampler
- [ ] tests/test_dashboard
- [ ] tests/test_study
- [ ] tests/storages_tests/test_in_memory
- [ ] tests/storages_tests/test_storages
- [ ] tests/storages_tests/rdb_tests/test_storage
- [ ] tests/storages_tests/rdb_tests/test_models
- [ ] tests/samplers_tests/tpe_tests/test_parzen_estimator
- [ ] tests/samplers_tests/tpe_tests/test_sampler
- [ ] tests/samplers_tests/test_samplers
- [ ] tests/test_trial
- [ ] tests/test_structs
- [ ] tests/test_distributions
- [ ] tests/test_cli
- [ ] tests/visualization_tests/test_utils
- [ ] tests/visualization_tests/test_intermediate_plot
- [ ] tests/visualization_tests/test_parallel_coordinate
- [ ] tests/visualization_tests/test_slice
- [ ] tests/visualization_tests/test_contour
- [ ] tests/visualization_tests/test_optimization_history

**Comment by bigbird555** [comment]
Excuse me. I have a question about this issue.
You mean that someone needs to rewrite all the comments like #type hope -> fuga in all the above files into comments following Oputuna Specific Conventions of https://github.com/optuna/optuna/wiki/Coding-Style-Conventions ?

**Comment by bigbird555** [comment]
Also, it seems necessary to remove variable annotation syntax form all the above files. Am I right ?

**Comment by c-bata** [comment]
> You mean that someone needs to rewrite all the comments like #type hope -> fuga in all the above files into comments following Oputuna Specific Conventions of https://github.com/optuna/optuna/wiki/Coding-Style-Conventions ?

Yes.

> Also, it seems necessary to remove variable annotation syntax form all the above files. Am I right ?

No. Optuna still doesn't adopt variable annotation syntax because of the Python3.5 support. We need to keep a comment-based annotation style for variables.

**Comment by bigbird555** [comment]
So, in short, do you need functions like below in Optuna for now?

`def func(hoge, fuga) -> type
"""hoge is integer and fuga is float"""

    some procedure`

**Comment by c-bata** [comment]
More precisely, you need to specify the types of `hoge` and `fuga` like below.

```python
def func(hoge: type, fuga: type) -> type:
    """hoge is integer and fuga is float"""

    a = [] # type: List[int]
    # some procedure
```

**Comment by bigbird555** [comment]
I think I understood what you need.
Is it okay to submit PR to you when I correct them ?

**Comment by himkt** [comment]
I encountered the importing problem of `optuna.study.Study` (https://github.com/optuna/optuna/pull/963/files#discussion_r388350274).

We have to avoid directly importing of `Study` class because it causes a runtime error.
Although I'm not sure what is the best choice, I avoid an import error by [forward reference](https://www.python.org/dev/peps/pep-0484/#forward-references).

```python
def prune(self, study: 'optuna.study.Study', trial: FrozenTrial) -> bool:
    
    step = trial.last_step
```

**Comment by keisuke-umezawa** [comment]
@c-bata 
Like #734 , could you add [this list](https://github.com/optuna/optuna/issues/711#issuecomment-593362218) to the top of this issue, because it is easier to understand which we need to fix next.

**Comment by c-bata** [comment]
Sounds good 👍  I updated the description.

**Comment by harupy** [comment]
I'll briefly describe how to install and use `com2ann` which automatically translates type comments into type annotations. I tweaked [the original version](https://github.com/ilevkivskyi/com2ann) to prevent translating type comments on variables (variable annotations) which is not supported in Python 3.5.

How to install:

```
pip install git+https://github.com/harupy/com2ann.git@disable-variable-annotation
```

How to run:

```
com2ann path/to/file.py
```

What you need to do after running `com2ann`

- Remove `if type_checking.TYPE_CHECKING` (in some modules, it's still required to prevent a circular import)
- Sort imports order
- Remove unused import
- Run `black --line-length=99 --exclude=docs .` to format code

**Comment by HideakiImamura** [comment]
[FYI] I checked the entire current Optuna code to see what files still need to be worked on. I fixed the first description on this page. We still have a lot of tasks to work on for this Issue. We're waiting for your contribution!

**Comment by harupy** [comment]
I'll take `optuna/study.py`

**Comment by harupy** [comment]
Ran the script in https://github.com/optuna/optuna/issues/711#issuecomment-678722000 against the current master.

```
optuna/structs.py
optuna/study.py
optuna/integration/sklearn.py
```

**Comment by c-bata** [comment]
Thank you. I updated the description.

**Comment by hvy** [comment]
Finished?

**Comment by c-bata** [comment]
I executed @harupy's script at latest master branch, then found no modules.

```
$ python check_type_hints.py
$
```

Thank you all for your great contribution :tada:

**Comment by harupy** [comment]
A new script to detect type comments on variables (e.g. `foo = "foo"  # type: str`). Feel free to use this when python 3.5 support has been removed.

<details>
<summary>code</summary>
```python
import argparse
import ast
import os
import sys

from typing import Iterable


def iter_python_scripts(directory: str) -> Iterable[str]:
    """Yield all python scripts in the given directory"""
    for root, _, files in os.walk(directory):
        for f in files:
            if f.endswith(".py"):
                yield os.path.join(root, f)


def read_file(path: str) -> str:
    """Read a file and return its content"""
    with open(path, encoding="utf-8") as f:
        return f.read()


def iter_assignments(node: ast.AST) -> Iterable[ast.Assign]:
    """Yield all assign statements in the given node"""
    for n in ast.iter_child_nodes(node):
        if isinstance(n, ast.Assign):
            yield n
        yield from iter_assignments(n)


def has_type_comment(node: ast.AST) -> bool:
    """Return True if the given node has a type comment"""
    return hasattr(node, "type_comment") and node.type_comment is not None


def create_position_link(path: str, lineno: int, col_offset: int) -> str:
    """Create a link to the specified position"""
    return f"{path}:{lineno}:{col_offset}"


def parse_args() -> argparse.Namespace:
    """Parse arguments"""
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "-s",
        "--show-positions",
        action="store_true",
        help="show the positions of assignment statements containing a type comment",
    )
    return parser.parse_args()


def main() -> None:
    if sys.version_info[:2] < (3, 8):
        raise Exception(
            "This script throws in Python < 3.8 "
            "because `ast.parse` doesn't support the `type_comments` argument in Python < 3.8 "
            "See: https://docs.python.org/3/library/ast.html#ast.parse"
        )

    args = parse_args()

    for d in ["optuna", "tests"]:
        for path in iter_python_scripts(d):
            src = read_file(path)
            root = ast.parse(src, type_comments=True)

            type_commented = [a for a in iter_assignments(root) if has_type_comment(a)]

            if len(type_commented) == 0:
                continue

            if args.show_positions:
                print(
                    "\n".join(
                        create_position_link(path, t.lineno, t.col_offset) for t in type_commented
                    )
                )
            else:
                print(path)


if __name__ == "__main__":
    main()
```
</details>
