### ISSUE TITLE
Within a trial, distributions return same value even if called repeatedly

### ISSUE THREAD

**Issue by eafpres** [optuna/optuna#717]
I noticed when I created a study where the distributions are all suggest_discrete_uniform that duplicate trials can occur.
I  created logic to test for this and re-call the distributions until a unique trial is found or a retry limit is reached.
I found that within the while loop, the new calls to the distributions return the same values over and over.
Is this expected behavior?  I would like to be able to ensure unique trials or at least try to find unique trials.

Here is code to reproduce this:
```
import optuna
import pandas as pd
#
def timestamp(subsecond = False):
    """
    generates a timestamp as the date and time in seconds

    Returns
    -------
    ts, a string with the format
    YYYY-MM-DD_hh_mm_ss # for case where subsecond = False
    or
    YYYY-MM-DD-hh-mm-ss.nnnnnn # for case where subsecond = True
    """
    if 'dt' not in dir():
        import datetime as dt
    ts = str(dt.datetime.now()).replace(" ", "_").replace(":", "_")
    if not subsecond:
        ts = ts[0:ts.find('.')]
    return(ts)
#
def train_model(trial, var_1_range, var_2_range, study_name):
#
# tempporary dataframe to accumulate trials used searching for unique
# combination of the given parameters
# used only to save the data to a file for analysis
#    
    reviewed_trials = pd.DataFrame(columns = ('var_1', 'var_2'))
    print('checking for past runs\n', flush = True)
    completed = None
    count = None
    experiments = study.trials_dataframe()
#
# test if first trial (empty experiments dataframe)
#
    if not trial.number == 0:
        completed = \
            experiments.drop('system_attrs', axis = 1).loc[:, 'params']
        completed.to_csv(study_name + '_completed.csv')
#
# initialize the trail to a past trial
#
        proposed_trial = completed.loc[0, :]
        count = 0
#
# test for inclusion in the completed trials and loop until new one is found
# or until we exceed the max trails setting (here, 20)        
#
        while ((completed == proposed_trial).all(axis = 1).any() and
               count < 20):
            print('trying sample ', count, '\n', flush = True)
            count += 1
            var_1 = \
                int(trial.suggest_discrete_uniform('var_1',
                                                   var_1_range[0],
                                                   var_1_range[1],
                                                   var_1_range[2]))
            var_2 = \
                int(trial.suggest_discrete_uniform('var_2',
                                                   var_2_range[0],
                                                   var_2_range[1],
                                                   var_2_range[2]))
            proposed_trial = \
                pd.Series((var_1, var_2), index = ('var_1', 'var_2'))
            reviewed_trials =\
                reviewed_trials.append(proposed_trial, ignore_index = True)
#
# if first trial, just get the first random sample
#
    else:
        var_1 = \
            int(trial.suggest_discrete_uniform('var_1',
                                               var_1_range[0],
                                               var_1_range[1],
                                               var_1_range[2]))
        var_2 = \
            int(trial.suggest_discrete_uniform('var_2',
                                               var_2_range[0],
                                               var_2_range[1],
                                               var_2_range[2]))
        proposed_trial = \
            pd.Series((var_1, var_2), index = ('var_1', 'var_2'))
#
# save the set of reviewed trials for each trial completed
#            
    reviewed_trials.to_csv(timestamp() + 
                           str(trial.number).zfill(3) + 
                           '_reviewed_trials.csv')
#
# add the count to the study structure so we can inspect it
#    
    trial.set_user_attr('count', count)
#
# return a value so we don't get 'FAIL'
#    
    return 1.25
#
# create parameter ranges for the study
#    
var_1_range = [128, 384, 128]
var_2_range = [2, 5, 1]
n_trials = 10
study_name = 'debug_optuna_' + timestamp()
study = (optuna.create_study(study_name = study_name,
                             storage = 'sqlite:///' + study_name + '.db',
                             load_if_exists = False))
study.optimize(lambda trial:
               train_model(trial, var_1_range, var_2_range, study_name),
               n_trials = n_trials, timeout = None)
experiments = study.trials_dataframe()
experiments.to_csv(study_name + '_optuna_debug_experiments.csv')
completed = pd.read_csv(study_name + '_completed.csv').iloc[:, 1:7]
```

In the example, there are 12 possible trials.  I attempt to run 10.  If a trial is a duplicate, I use a while loop to re-call the distributions.  For debug purposes, I save all the attempted ones for each trial in a file tagged with the trial number.  I've attached the output of a run of this (debug_optuna_2019-11-18_11_10_48_optuna_debug_experiments.txt).  You can see that in the study results, index 3 and 4 were duplicated of ones already used.  

[debug_optuna_2019-11-18_11_10_48_optuna_debug_experiments.txt](https://github.com/optuna/optuna/files/3860105/debug_optuna_2019-11-18_11_10_48_optuna_debug_experiments.txt)

You can also see that the max attempts, in this case 20, were tried (i.e. the distributions were called 20 times).  I also attach those retries (2019-11-18_11_11_09003_reviewed_trials.csv and 2019-11-18_11_11_11004_reviewed_trials.csv).  You can see the distributions return the same result every time in the while loop (i.e. in both attached files, all 20 tries returned the same values). Therefore, my code accomplishes nothing.

I tried explicitly setting a random seed inside the while loop but that had no effect.

I attempted to modify trial.number wondering if you were using that somehow in the random generation, but I am unable to do that.

I reviewed your code and I don't see why this is happening.
 
[2019-11-18_11_11_09003_reviewed_trials.txt](https://github.com/optuna/optuna/files/3860106/2019-11-18_11_11_09003_reviewed_trials.txt)
[2019-11-18_11_11_11004_reviewed_trials.txt](https://github.com/optuna/optuna/files/3860107/2019-11-18_11_11_11004_reviewed_trials.txt)

**Comment by sile** [comment]
Thank you for your question and for sharing the runnable example code.

> I found that within the while loop, the new calls to the distributions return the same values over and over.
> Is this expected behavior?

Yes.
`trial.sugest_xxx()` always returns the same parameter value if it's called multiple times for a parameter within a trial (c.f. [optuna/trial.py#L490](https://github.com/optuna/optuna/blob/v0.19.0/optuna/trial.py#L490)).

>  I would like to be able to ensure unique trials

I think that the answer to the stackoverflow question ["How to sample parameters without duplicates in optuna?"](https://stackoverflow.com/questions/58820574/how-to-sample-parameters-without-duplicates-in-optuna) may help you.

**FYI** Although it hasn't been merged yet, Optuna dev team is going to implement a sampler that provides grid search based sampling (see #665 for the details).

**Comment by eafpres** [comment]
@sile Thank you for the update.  The grid search would be a partial solution; I would have cases where it isn't really a grid but some are discrete and others are continuous.  My current workaround is to build my own discrete sampler and use it, then test for duplicates and re-sample as needed.  I then have to add the params as user_attrs, but that is OK.  I'll definitely look at the grid search once it is merged.  
I'm not clear why the distributions are implemented this way.  However, based on your answer I am closing this.
Thank you again for the great tool and support.
