### ISSUE TITLE
MedianPruner does not have parameters interval_steps

### ISSUE THREAD

**Issue by eafpres** [optuna/optuna#723]
Here: [https://optuna.readthedocs.io/en/latest/reference/pruners.html] it says:

> Parameters: |   
n_startup_trials – Pruning is disabled until the given number of trials finish in the same study.  
n_warmup_steps – Pruning is disabled until the trial reaches the given number of step.  
interval_steps – Interval in number of steps between the pruning checks, offset by the warmup steps. If no value has been reported at the time of a pruning check, that particular check will be postponed until a value is reported.

However, when using the pruner,  an exception is thrown when attempting to pass the interval_steps arg.  

```
  File "<ipython-input-32-21cf49d7d347>", line 6, in <module>
    interval_steps = 10)))

TypeError: __init__() got an unexpected keyword argument 'interval_steps'
```

And the help text does not show the parameter:  

```
help(MedianPruner)
Help on class MedianPruner in module optuna.pruners.median:

class MedianPruner(optuna.pruners.percentile.PercentilePruner)
 |  Pruner using the median stopping rule.
 |  
 |  Prune if the trial's best intermediate result is worse than median of intermediate results of
 |  previous trials at the same step.
 |  
 |  Example:
 |  
 |      We minimize an objective function with the median stopping rule.
 |  
 |      .. code::
 |  
 |          >>> from optuna import create_study
 |          >>> from optuna.pruners import MedianPruner
 |          >>>
 |          >>> def objective(trial):
 |          >>>     ...
 |          >>>
 |          >>> study = create_study(pruner=MedianPruner())
 |          >>> study.optimize(objective)
 |  
 |  Args:
 |      n_startup_trials:
 |          Pruning is disabled until the given number of trials finish in the same study.
 |      n_warmup_steps:
 |          Pruning is disabled until the trial reaches the given number of step.
```

**Comment by sile** [comment]
Hi,

Which version of Optuna did you use?
The `interval_steps` parameter was introduced by [v0.19.0](https://github.com/optuna/optuna/releases/tag/v0.19.0) that was released three days ago. Therefore, if your Optuna version is older than v0.19.0, you need to update it to use the new feature.

**Comment by eafpres** [comment]
@sile:  Thank you!  I did not realize I was one version behind already!  I will update to 0.19.0.
