### ISSUE TITLE
[PROPOSAL] Adding a button on README that launches a live Jupyter notebook on Binder

### ISSUE THREAD

**Issue by harupy** [optuna/optuna#727]
## Motivation

It'd be nice if we could try `optuna` quick on the browser without any setup.

## Proposal

Add a button on README that launches a live Jupyter notebook on Binder where we can run a quick starter.

[![Binder](https://mybinder.org/badge_logo.svg)](https://mybinder.org/v2/gh/harupy/optuna/add-binder?filepath=examples%2Fquickstart.ipynb)

This button launches the notebook on my test branch (https://github.com/harupy/optuna/blob/add-binder/examples/quickstart.ipynb).

## What is Binder?
https://mybinder.org/

I'll open a PR if interested.

**Comment by harupy** [comment]
I'll close this.

**Comment by hvy** [comment]
Apologies for the late reply. This sounds like a great and I think that we should proceed with it, introducing an example notebook and a link in the README as you suggested. I'd like to discuss the details but would you like to maybe work on it?

**Comment by harupy** [comment]
@hvy Thanks for the reply. Yes, I'd like to work on this!

**Comment by hvy** [comment]
That's great. How about PR with the `examples/quickstart.ipynb` that you've already written and a badge to open the jupyter notebook in this [`Basic Concepts` subsection in the README](https://github.com/optuna/optuna#basic-concepts). As for the medium, I tried comparing a couple of platforms but am leaning towards Colab. It's straight forward to integrate (as seen in [this Optuna PR](https://github.com/optuna/optuna/pull/737)), established and quick to start executing. `optuna` must be installed in the notebook however. Please let me know what you think.

**Comment by harupy** [comment]
Sounds good. I agree with you about Colab.
