### ISSUE TITLE
Add `--pruning` option to `pytorch_lightning_simple.py`.

### ISSUE THREAD

**Issue by g-votte** [optuna/optuna#731]
Similar to [`pytorch_ignite_simple.py`](https://github.com/optuna/optuna/blob/master/examples/pytorch_ignite_simple.py), adding `--pruning` option to [`pytorch_lightning_simple.py`](https://github.com/optuna/optuna/blob/master/examples/pytorch_lightning_simple.py) would make the pruning feature more accessible for the PyTorch Lightning users.

**Comment by yutayamazaki** [comment]
@g-votte 
Can I work on this issue?

**Comment by g-votte** [comment]
@yutayamazaki 
Sure! Please go for it.

**Comment by hvy** [comment]
Closing as it was just fixed by https://github.com/optuna/optuna/pull/794.
