### ISSUE TITLE
Introduce default number of trials to visualization features.

### ISSUE THREAD

**Issue by g-votte** [optuna/optuna#732]
## Motivation

Visualization features are unstable with more than hundreds/thousands of trials. For example, the following program stoped working during visualization in my environment.

```python
def objective(trial):
    x = trial.suggest_uniform('x', 0, 1)
    y = trial.suggest_uniform('y', 0, 1)

    return x + y
    
study = optuna.create_study()
study.optimize(objective, n_trials=5000)
optuna.visualization.plot_contour(study)
```

## Description

Just plotting the latest trials would mitigate this problem. For example, we can add an optional `n_trials` argument to the plot functions so that they plot the latest 100 trials by default.

```python
def plot_intermediate_values(study, n_trials=100):
    ...  # Plot `n_trials` number of trials instead of all of them.
```

**Comment by dwiel** [comment]
One issue with only showing the latest trials is that sometimes the best trials are not all the most recent. Obviously if the algorithm is working well, the most recent trials tend to be the best, but they aren't always exclusively the best. There is no reason that loading thousands of records from postgres should take more than a second.

**Comment by grfreitas** [comment]
I want to give a sugestion here: the figures are generated by plotly with `go.Scatter`, if plotting the graph is the reason for the program stopping, one way to reduce the lag generated by it is by changing the call to `go.Scattergl`. It is capable of rendering more points with less lag.

**Comment by hvy** [comment]
This is still an open issue. Note that this only seems to be an issue for the contour plot (https://github.com/optuna/optuna/issues/733#issuecomment-655334709).

**Comment by michiboo** [comment]
@hvy  Hi sorry for the late response, I will try fix this conflict for this issue today.
