### ISSUE TITLE
Apply doctest to existing documents.

### ISSUE THREAD

**Issue by g-votte** [optuna/optuna#734]
Though we've introduced doctest in #702, many existing examples are still incompatible with doctest. This issue is to ~list up those examples and~ apply doctest to them.

Below are files to be fixed, listed up in https://github.com/optuna/optuna/issues/734#issuecomment-586678423. (Thanks @keisuke-umezawa for your consolidating the information!)

- [x] optuna/visualization/parallel_coordinate
- [x] optuna/visualization/slice
- [x] optuna/visualization/intermediate_values
- [x] optuna/visualization/optimization_history
- [x] optuna/visualization/contour
- [x] optuna/logging
- [x] optuna/storages/rdb/storage
- [x] optuna/trial
- [x] optuna/pruners/successive_halving
- [x] optuna/pruners/nop
- [x] optuna/pruners/median
- [x] optuna/pruners/percentile
- [x] optuna/integration/cma
- [x] optuna/integration/lightgbm
- [x] optuna/integration/mxnet
- [x] optuna/integration/chainermn
- [x] optuna/integration/fastai
- [x] optuna/integration/keras
- [x] optuna/integration/pytorch_ignite
- [x] optuna/integration/tensorflow
- [x] optuna/integration/sklearn
- [x] optuna/integration/skopt
- [x] optuna/integration/pytorch_lightning
- [x] optuna/integration/xgboost
- [x] optuna/integration/tfkeras
- [x] optuna/integration/chainer
- [x] ~optuna/structs~
  - see also [the discussion about `structs.py`](https://github.com/optuna/optuna/pull/958#discussion_r383844795)
- [x] optuna/samplers/tpe/sampler
- [x] optuna/samplers/random
- [x] optuna/exceptions

**Comment by nuka137** [comment]
@g-votte 

I'm interested in tackling this issue.
I think [optuna/trial.py](https://github.com/optuna/optuna/blob/master/optuna/trial.py#L161-L166) is one of the candidate.
Does this meet your intention?

**Comment by g-votte** [comment]
@nuka137 
Of course, and your contribution is greatly welcomed!

**Comment by nuka137** [comment]
@g-votte 

Created PR #882 .

P.S.
I also noticed `make doctest` raises below error in newest scikit-learn (0.22.1).
I think `_index_param_value` is removed in newest scikit-learn. (https://github.com/scikit-learn/scikit-learn/pull/15863/files)

```
    ImportError: scikit-learn is not available. Please install scikit-learn to use this feature. scikit-learn can be installed by executing `$ pip install scikit-learn>=0.19.0`. For further information, please refer to the installation guide of scikit-learn. (The actual import error is as follows: cannot import name '_index_param_value')
```

**Comment by g-votte** [comment]
@nuka137 
Cool! Let us take a look.

Regarding the scikit-learn problem, the version is limited as `<=0.22.0` in [`setup.py`](https://github.com/optuna/optuna/blob/master/setup.py#L70), just because `_index_param_value` has been removed as you mention.

#881 is addressing this issue.

**Comment by keisuke-umezawa** [comment]
I greped files which use `.. code ::`. I think it means wrong usage of doctest.

- [ ] optuna/visualization/parallel_coordinate
- [ ] optuna/visualization/slice
- [ ] optuna/visualization/intermediate_values
- [ ] optuna/visualization/optimization_history
- [ ] optuna/visualization/contour
- [ ] optuna/logging
- [ ] optuna/storages/rdb/storage
- [ ] optuna/trial
- [ ] optuna/pruners/successive_halving
- [ ] optuna/pruners/nop
- [ ] optuna/pruners/median
- [ ] optuna/pruners/percentile
- [ ] optuna/integration/cma
- [ ] optuna/integration/lightgbm
- [ ] optuna/integration/mxnet
- [ ] optuna/integration/chainermn
- [ ] optuna/integration/fastai
- [ ] optuna/integration/keras
- [ ] optuna/integration/pytorch_ignite
- [ ] optuna/integration/tensorflow
- [ ] optuna/integration/skopt
- [ ] optuna/integration/pytorch_lightning
- [ ] optuna/integration/xgboost
- [ ] optuna/integration/tfkeras
- [ ] optuna/integration/chainer
- [ ] optuna/structs
- [ ] optuna/samplers/tpe/sampler
- [ ] optuna/samplers/random
- [ ] optuna/exceptions

**Comment by hvy** [comment]
A related topic https://github.com/optuna/optuna/issues/933.

**Comment by keisuke-umezawa** [comment]
@g-votte 
Could you add the checklist in the [comment](https://github.com/optuna/optuna/issues/734#issuecomment-586678423) to top comment of this issue, because people can easily understand what they need to fix?

**Comment by g-votte** [comment]
@keisuke-umezawa 
Thank you very much for your listing up! I edited the comment.

**Comment by nuka137** [comment]
@g-votte @keisuke-umezawa 

Thanks for listing up!

`optuna/exceptions.py` (#958) and `optuna/trial.py` (#882)) are already merged.
Could you mark them as completed?
Also, doctest for `optuna/structs` is removed [in this discussion](https://github.com/optuna/optuna/pull/958#discussion_r383844795).

I will tackle `optuna/pruners/**` next. Thanks!

**Comment by g-votte** [comment]
@nuka137 
Thanks for your update. It's very helpful.

> I will tackle optuna/pruners/** next. Thanks!

Cool! Please go for it.

**Comment by keisuke-umezawa** [comment]
@g-votte #955 closed `optuna/visualization/parallel_coordinate`.

**Comment by keisuke-umezawa** [comment]
https://github.com/optuna/optuna/pull/973 will close `optuna/visualization/*`.

**Comment by nuka137** [comment]
@g-votte

`optuna/pruners/**` were merged (#964). Could you update these items as completed?

Next, I will check ` optuna/samplers/*` and `optuna/integration/skopt. Thanks!

**Comment by g-votte** [comment]
@keisuke-umezawa @nuka137 
I updated the list.
Thanks a lot for your continued contribution!

**Comment by nuka137** [comment]
@g-votte 

`optuna/samplers/*` and `optuna/integration/skopt` are already merged.
Could you mark them as completed status?

I'm considering to tackle `optuna/integration/tensorflow` next.
But, the example in `optuna/integration/tensorflow.py` will be similar to `examples/pruning/tensorflow_estimator_integration.py` if the example is simple.
I'm not sure this is a good way to introduce the example for doctest.

**Comment by g-votte** [comment]
@nuka137 
Thanks for your letting me know! (and sorry for making you update frequently..)
 
> But, the example in optuna/integration/tensorflow.py will be similar to examples/pruning/tensorflow_estimator_integration.py if the example is simple.

Good catch. Introducing almost the whole part of the example might be too much. I think one of options is to delete the docstring and put a reference to the example instead.

**Comment by nuka137** [comment]
@g-votte 

Thanks for your advice.

> delete the docstring and put a reference to the example instead

Good idea! I will do this.
BTW, I noticed there are other examples which can be applied in same way.
e.g.

* optuna/integration/lightgbm
* optuna/integration/pytorch_ignite
* optuna/integration/pytorch_lightning

At first, I will fix `optuna/integration/tensorflow.py` and `examples/pruning/tensorflow_estimator_integration.py `.
After that I will tackle more examples.

**Comment by nuka137** [comment]
@g-votte 

`optuna/integration/tensorflow.py` is merged.

I think we can apply this method to below files same way.
I will tackle this ASAP.

||Example|
|---|---|
|optuna/integration/lightgbm|https://github.com/optuna/optuna/blob/master/examples/pruning/lightgbm_integration.py|
|optuna/integration/mxnet|https://github.com/optuna/optuna/blob/master/examples/pruning/mxnet_integration.py|
|optuna/integration/chainermn|https://github.com/optuna/optuna/blob/master/examples/pruning/chainermn_integration.py|
|optuna/integration/fastai|https://github.com/optuna/optuna/blob/master/examples/fastai_simple.py|
|optuna/integration/keras|https://github.com/optuna/optuna/blob/master/examples/pruning/keras_integration.py|
|optuna/integration/pytorch_ignite|https://github.com/optuna/optuna/blob/master/examples/pytorch_ignite_simple.py|
|optuna/integration/pytorch_lightning|https://github.com/optuna/optuna/blob/master/examples/pytorch_lightning_simple.py|
|optuna/integration/xgboost|https://github.com/optuna/optuna/blob/master/examples/pruning/xgboost_integration.py|
|optuna/integration/tfkeras|https://github.com/optuna/optuna/blob/master/examples/pruning/tfkeras_integration.py|
|optuna/integration/chainer|https://github.com/optuna/optuna/blob/master/examples/pruning/chainer_integration.py|

BTW, I could not find code example in optuna/integration/sklearn.

**Comment by g-votte** [comment]
@nuka137 
> I think we can apply this method to below files same way.
> I will tackle this ASAP.

Cool! I also think we can take similar approaches for them.

> BTW, I could not find code example in optuna/integration/sklearn.

I think the example is [here](https://github.com/optuna/optuna/blob/master/optuna/integration/sklearn.py#L513-L528). Since this is relatively small, we could keep it inside the docs.

**Comment by nuka137** [comment]
@g-votte 

Thanks!
I created new request to fix these documentation.

**Comment by nuka137** [comment]
@g-votte 

Sorry for late response.
I created a PR (#1212) which will fix a doctest on optuna/storages/rdb/storage.py.
I think all doctests are fixed after merging this PR.

**Comment by nuka137** [comment]
@g-votte 

Thanks to many reviewers, all doctests listed in the head of this issue are fixed.
I think we can close this issue now.
What do you think?

**Comment by g-votte** [comment]
I see that all listed items are resolved; so, let me close this issue.

@nuka137 
Thanks again for your contribution. Great job!

**Comment by keisuke-umezawa** [comment]
Congratulations! I detached it from pinned items.
