### ISSUE TITLE
Optimization exponential with parameters?

### ISSUE THREAD

**Issue by Crissman** [optuna/optuna#748]
From here: https://github.com/optuna/optuna/blob/master/docs/source/tutorial/configurations.rst#note-on-the-number-of-parameters

> The difficulty of optimization increases roughly exponentially with regard to the number of parameters. That is, the number of necessary trials increases exponentially when you increase the number of parameters, so it is recommended to not add unimportant parameters.

I don't believe this is correct. If I have one parameter, and I need it within 1% of the optimal answer, on average less than 100 trials will be required. If I have 1,000 independent parameters, I should still need less than 100 trials.

Is there some reason the time would increase with parameter count?

**Comment by hvy** [comment]
Just an idea how it can be improved. Feel to ignore 🙂 

_For this type of hyperparameter or blackbox optimization in general, search space grows exponentially with the number of parameters. For instance, if we only have a single categorial parameters with 10 possible values, the size of the search space is 10. Increasing the number of parameters to 4, each with 10 possible values, we end up with a search space of :math:`4^10`, that is over a million configurations. Optuna implements [search space sampling algorithms](https://optuna.readthedocs.io/en/latest/reference/samplers.html) to efficiently explore this search space. For the best possible outcome however, it is sometimes important to be aware of this fact._

**Comment by Crissman** [comment]
Experimentation confirms that the original documentation is correct. Adding multiple parameters slows down the search speed. Will do more thinking about why this didn't match my intuition. Closing this issue.
