### ISSUE TITLE
study.best_trial takes minutes to load from postgres

### ISSUE THREAD

**Issue by dwiel** [optuna/optuna#760]
## Expected behavior

I have a study with a few thousand trials. It takes a few minutes to simply load the best trial. It looks like not only is this query happening in the application layer, but the number of queries executed is `O(n)` instead of `O(1)`.

## Environment

- Optuna version: 0.19.0
- Python version: 3.6.8
- OS: Ubuntu 18.04

## Steps to reproduce

1. Use postgres backend
2. Create a study with thousands of trials
3. In a new process, attempt to access the studies best_trial

It takes similar amounts of time to do things like get a data frame with all trial information, render visualizations, etc.

**Comment by hvy** [comment]
Thanks @dwiel for the report. 

This is actually a known issue. There's an ongoing PR addressing it https://github.com/optuna/optuna/pull/729. 

As for the visualization, there's a possible duplicate issue if you'd mind checking https://github.com/optuna/optuna/issues/732. Not sure if the creation of a data frame being slow is reported however. Could you elaborate on this slowdown and maybe create a separate issue for it?

**Comment by hvy** [comment]
A detail but I'm not sure this should be classified as a bug, rather a performance improvement (`enhancement`). It depends on how the problem manifests of course.

**Comment by dwiel** [comment]
Cool, yeah looks like #729 will fix this, thanks. I can change to enhancement, but my thought when filing this issue was that this is something should take milliseconds, not minutes, and there are many applications (mine included) where this difference is the difference between usable and unusable. We aren't talking a few percent speed up, we are talking 5 orders of magnitude difference. Either way I can close this as dup and open a new one of the enumeration of the dataframe as a separate issue.

**Comment by hvy** [comment]
The labeling isn't obvious and you obviously have a point so categorizing it as a bug might be fine. My point was basically that the current implementation and behavior was functioning as intended. Anyway, thanks for your quick action in updating the issue!

**Comment by dwiel** [comment]
For reference, new issues opened are #762 and #763

**Comment by dwiel** [comment]
also, I don't appear to be able to change labels, but labels on new issues are as requested.

**Comment by hvy** [comment]
Thanks for the issues following up. As for the labels, I'm now a bit concerned that the automatically added labels are limited because of the templates. It sounds like an issue in itself.
