### ISSUE TITLE
Optimize `get_all_study_summaries` for RDB storage

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#767]
There is room for improving the performance of [`get_all_study_summaries`](https://github.com/optuna/optuna/blob/master/optuna/storages/rdb/storage.py#L305) for the RDB storage.

## Motivation

Room for improving the performance.

## Description

Quite self explanatory by the above description, the existing [TODO comment](https://github.com/optuna/optuna/blob/master/optuna/storages/rdb/storage.py#L305) and the context provided below.

## Additional context (optional)

Please also see https://github.com/optuna/optuna/issues/762.

**Comment by keisuke-umezawa** [comment]
@hvy @ytsmiling Is it okay to close it?

**Comment by ytsmiling** [comment]
Yes, I think we can close this issue.
