### ISSUE TITLE
Key features should be properly documented

### ISSUE THREAD

**Issue by hvy** [optuna/optuna#782]
The key features of Optuna in the `README.md` https://github.com/optuna/optuna#key-features should be explained more in details, for instance in the documentation. Currently, the user have to refer to the paper.

**Comment by hvy** [comment]
@keisuke-umezawa do you have any ideas on this?

**Comment by keisuke-umezawa** [comment]
@hvy 

> The key features of Optuna in the README.md https://github.com/optuna/optuna#key-features should be explained more in details, for instance in the documentation. Currently, the user have to refer to the paper.

Yes, I agree with it. I will make a draft of it.

**Comment by hvy** [comment]
Thanks for the suggestion. Yes, that sounds like a good first approach forwarding. At least, readers are forwarded to concrete code.

**Comment by hvy** [comment]
Maybe we can close this ticket since I actually believe that the underlying initial problem is solved.

**Comment by keisuke-umezawa** [comment]
@hvy 
If we do not have any other key features, I think we can close this issue.

**Comment by keisuke-umezawa** [comment]
@hvy 
https://tech.preferred.jp/en/blog/optuna-v1/
Regarding this blog, we may add the following key features:

- Eager dynamic search spaces: Pythonic search spaces using Python conditionals and loops without the need for domain-specific languages (DSLs)
- Efficient sampling and pruning algorithms: State-of-the-art algorithms to efficiently explore large search spaces and prune unpromising trials to save computational resources
- Integrations: Modules for popular machine learning libraries such as PyTorch, TensorFlow, Keras, FastAI, scikit-learn, LightGBM, and XGBoost
- Visualizations: Customizable visualizations of optimizations with a single function call
- Distributed optimization: Optimizations that are parallelizable among threads or processes without having its code modified
- Lightweight: Simple installation with few requirements

**Comment by hvy** [comment]
Sorry for the delayed response and thanks for your suggestion. I'm curious what you think about the verbosity. I'm wondering if not sufficient to add "Python eager search spaces" to the existing bullets, keeping it simple. I find the above to be slightly too verbose and that it might instead have a negative effect on the reader.

**Comment by keisuke-umezawa** [comment]
Yes, I think so too. If we will update it, it is 5 or less for bullets.

**Comment by keisuke-umezawa** [comment]
@hvy 
Thank you for the discussion by hangout.

After the discussion, I would like to describe key features as follows:

- LIghtweight
   - Simple installation with few requirements.
- Efficient optimization algorithms
  - Adopt state-of-the-art algorithms for sampling hyper parameters and efficiently pruning unpromising trials
- Pythonic search spaces
  - Define search spaces using familiar Python syntax including conditionals and loops
- Easy parallelization
  - Scale studies to tens or hundreds or workers with little or no changes to the code
- Quick visualization
  - Inspect optimization histories from a variety of plotting functions

**Comment by keisuke-umezawa** [comment]
I will create a PR based on the above plan.

**Comment by hvy** [comment]
@crcrpar is working on improving the tutorials and to better match the key features. Let's keep this issue alive and close it once we're done with that.

**Comment by hvy** [comment]
Ongoing at https://github.com/optuna/optuna/pull/1722.

**Comment by hvy** [comment]
Let me close this issue since #1722 has been merged.
