### ISSUE TITLE
Trial suggest for same variable with different parameters should give error or raise exceptoion

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#797]
## Motivation
It is allowed to call `trial.suggest` multiple times for the same variable (`x` in this example) (see below). This always gives the same value (see assert below).

```Python
def objective(trial):
    x = trial.suggest_uniform('x', 0, 10)
    print(x)
    y = trial.suggest_uniform('x', 0, 10)
    print(y)
    assert x == y
    return (x - 2) ** 2
```

This is good because x might be needed multiple times in a loop (for cross validation for example).

But this here is also possible:

```Python
def objective(trial):
    x = trial.suggest_uniform('x', 0, 10)
    print(x)
    y = trial.suggest_uniform('x', -20, -10)
    print(y)
    assert x == y # assert is still true here
    return (x - 2) ** 2
```

This should not be allowed since `trial.suggest_uniform('x', 0, 10)` is in contradiction to `trial.suggest_uniform('x', -20, -10)`. The current implementation gives the same for y as the value for x was.

## Description

IMO this situation where one "suggest" is in contradiction to an other for the same variable should give a warning or raise an exception. This is because it is a hint for a programming error that might not get noticed otherwise.

What do you think? After a discussion I might contribute the change.

**Comment by sile** [comment]
Hi,

Thank you for your proposal.
I think your opinion is very reasonable, so I'd appreciate it if you could create a PR to address this issue.

> should give a warning or raise an exception.

Personally, I prefer a warning because it doesn't break backward compatibility (but it might be needed to discuss this choice with you and other developers on PR).

**Comment by PhilipMay** [comment]
Ok great. I will work on this.

**Comment by sile** [comment]
Thanks!

**Comment by PhilipMay** [comment]
Started the PR here: #867
