### ISSUE TITLE
Faster CmaEsSampler

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#798]
## Motivation

Current [`CmaEsSampler`](https://optuna.readthedocs.io/en/stable/reference/integration.html#optuna.integration.CmaEsSampler) retrieves and reports all trials to the CMA-ES logic in `cma` library at every trial. This implementation was employed to realize parallel optimization, but it makes the optimization slow especially when the study has thousands of trials.

IMO, an alternative implementation that reuses the reported trials is useful for such use cases.

## Description

I think we have several approaches as follows:
1) Each CMA-ES sampler manages its own optimization history and does not share it with other samplers. For example, if we have four parallel workers, four independent optimizations will be executed.
2) Use trial queue to store suggested trials. CMA-ES usually suggests multiple hyperparameter sets to be evaluated but only one of them are used in the current implementation. In the new implementation, those suggested sets are stored using trial queue to avoid re-sampling. This implementation requires #520 .

I think we need further discussion, so please let me know if you come up with design ideas.

**Comment by crcrpar** [comment]
I'm not sure, but I guess the changes, especially a `Trial`'s tentative attribute of `friend_trials` and new argument of `trials: List[FrozenTrial]` in `sample_independent` and `sample_relative` I made in #785 make the situation better somehow.

What do you think?

**Comment by c-bata** [comment]
The implementation of [this library](https://github.com/CyberAgent/cmaes) might help this issue.

> | trials/params | pycma's sampler | this library | this library *1 |
> | ------------- | --------------- | ------------ | ---------------- |
> |     100 / 10  |          6.000s |       1.315s |           0.677s |
> |     500 / 50  |      4m 52.008s |   1m 33.092s |           1.750s |
> |   1000 / 100  |     37m 41.617s |  13m 35.447s |           5.563s |
>
> In the setting of "this library *1", I run a benchmark with `ensure_constant_search_space=True`.
> You can use this option when all trials suggests the same search space.
> [This script](./benchmark/speed_problem.py) was run on my laptop so the times should not be taken precisely.
> And the times will be changed when running benchmark scripts with RDB storage.
> Even though, it is clear that this library is faster than Optuna's pycma sampler (with Optuna v1.0.0 and pycma v2.7.0).

https://github.com/CyberAgent/cmaes#execution-speed

**Comment by toshihikoyanase** [comment]
@c-bata 
Cool!! It must be useful for this issue. Thanks!

@crcrpar 
I'm really sorry for the late reply. You withdrew #805 but your new idea in #809 that uses bracket-specific studies seems to be useful for this issue especially for the first approach. Thank you for your suggestion.

**Comment by c-bata** [comment]
I found a solution for better performance withouut `ensure_constant_search_space=True`. I've just implemented, then the latest benchmark results are below:

![screenshot](https://user-images.githubusercontent.com/5564044/73533652-b2795000-4462-11ea-9811-5baf3bb370f8.png)
