### ISSUE TITLE
XGBoostPruningCallback is not compatible with xgboost cv()

### ISSUE THREAD

**Issue by algo-rythm** [optuna/optuna#810]
XGBoostPruningCallback is not compatible with xgboost cross validation function cv().

The Optuna pruner is expecting only two elements in each tuple of the evaluation_result_list, but XGBoost.cv is also providing a third element: the stddev of the metric across the cross-valdation folds.

## Expected behavior
No exception

## Environment
- Optuna version: 0.19.0
- Python version: Python 3.7.5
- OS: Windows 10

## Error messages, stack traces, or logs
File "C:\Users\me\.conda\envs\feature-tools-ve\lib\site-packages\optuna\integration\xgboost.py", line 50, in __call__
    current_score = dict(env.evaluation_result_list)[self.observation_key]
ValueError: dictionary update sequence element #0 has length 3; 2 is required

## Additional context (optional)
Here is a workaround callback:
```
def remove_std_from_evaluation_result_list(xgb_callback_env):
    """Custom XGBoost callback adapter to fix compatibility with Optuna pruner.
    The Optuna pruner is expecting only two elements in each tuple of the evaluation_result_list.
    It expects the observation_key and the evaluation metric only, but XGBoost is also providing
    a third element: the stddev of the metric across the cross-valdation folds.
    """
    # drop the 3rd element (stddev) from each evaluation_result_list item.
    erl_orig = xgb_callback_env.evaluation_result_list
    erl_no_std = [(observation_key, metric) for observation_key, metric, std in erl_orig]
    erl_orig.clear()
    erl_orig.extend(erl_no_std)

metrics = ["error", "logloss"]
pruning_callback = optuna.integration.XGBoostPruningCallback(trial, "test-logloss")
callbacks = [remove_std_from_evaluation_result_list, pruning_callback]
df_rounds = xgb.cv(params, dtrain, metrics=metrics, callbacks=callbacks)
```

**Comment by sile** [comment]
Thank you for reporting this issue. Honestly, when we implemented `XGBoostPruningCallback`, we weren't aware of the cv method. I think that it's worth to make `XGBoostPruningCallback` support `xgboost.cv()`. Let me label this issue as a contribution welcomed.

**Comment by yutayamazaki** [comment]
@sile 
Can I work on this issue? 
In [xgboost.callbacks](https://github.com/dmlc/xgboost/blob/master/python-package/xgboost/callback.py#L9), it detects the context('train' or 'cv') as shown below.

```python
def _get_callback_context(env):
    """return whether the current callback context is cv or train"""
    if env.model is not None and env.cvfolds is None:
        context = 'train'
    elif env.model is None and env.cvfolds is not None:
        context = 'cv'
    return context
```

**Comment by sile** [comment]
@yutayamazaki Sure! Please go for it.

**Comment by smly** [comment]
Resolved by https://github.com/optuna/optuna/pull/865.
