### ISSUE TITLE
How to handle CTRL-C during optimize?

### ISSUE THREAD

**Issue by algo-rythm** [optuna/optuna#811]
I'm trying print the best parameters and plot some visualizations after CTRL-C during optimization.  This is the code I tried, but it doesn't work:

```
    try:
        study.optimize(objective, n_trials=N_OPT_TRIALS, timeout=timeout)
    except KeyboardInterrupt:
        pass

    logging.info("study.best_params %s", str(study.best_params))
    optuna.visualization.plot_optimization_history(study)
    optuna.visualization.plot_contour(study)

```

What am I doing wrong?

**Comment by sile** [comment]
Hi,

What version of Optuna did you use?
Before v0.18.0, by default, any exceptions raised during optimization are caught by Optuna (related PR: https://github.com/optuna/optuna/pull/638). If you use Optuna v0.17.0 or earlier, you need to specify the `catch` argument with an empty tuple when calling `study.optimize()`.

**Comment by algo-rythm** [comment]
@sile Thank you for the prompt reply.

My environment:
```
Optuna 0.19.0
Python 3.7.5
OS Windows 10
```
CTRL-C causes this output:
```
forrtl: error (200): program aborting due to control-C event
Image              PC                Routine            Line        Source
libifcoremd.dll    00007FFF28483B58  Unknown               Unknown  Unknown
KERNELBASE.dll     00007FFF983C4053  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FFF9AC27974  Unknown               Unknown  Unknown
ntdll.dll          00007FFF9C2EA271  Unknown               Unknown  Unknown
QObject::~QObject: Timers cannot be stopped from another thread
```

What is the right way to stop the optimization on ctrl-c, but continue executing the post-optimization code?

**Comment by sile** [comment]
Thank you for the information.

In my environments (Ubuntu on WSL and Windows10), Ctrl-C can interrupt optimization and show the result without any special additional code (the following code is what I executed).
```python
import optuna
import time

def objective(trial):
    time.sleep(1)
    return trial.suggest_uniform('x', 0, 10)

study = optuna.create_study()
try:
    study.optimize(objective)  # Press CTRL+C to stop the optimization.
except KeyboardInterrupt:
    pass

print(study.best_trial)
```
Could you execute the above code and share the result?
If the execution fails, there might be a problem specific to your environment, not Optuna.

**Comment by algo-rythm** [comment]
Thank you for the code sample.  When I run your code, the CTRL-C is not caught and the print statement never executes.  Maybe you are right, it is something specific to my environment.

**Comment by sile** [comment]
**FYI** I found a StackOverflow post that seems similir to this problem: https://stackoverflow.com/questions/42653389/ctrl-c-causes-forrtl-error-200-rather-than-python-keyboardinterrupt-exception.

**Comment by algo-rythm** [comment]
@sile thank you for the StackOverflow link. I will have a look. I think the issue is not in Optuna itself.

**Comment by sile** [comment]
You're welcome :)

**Comment by g-votte** [comment]
Closing this issue. Please reopen it if you have any problem.
