### ISSUE TITLE
Pass arguments to callback

### ISSUE THREAD

**Issue by louisabraham** [optuna/optuna#813]
I would like to be able to give heavy objects computed in `optimize(trial)` as parameters to the `callback(study, trial)`.

## Motivation

I want to save predictions when I have an improvement, that is when `study.best_trial.number == trial.number`.

## Description

My `optimize(trial)` function performs cross-validation, and I would like to be able to reuse the fitted estimators to make my predictions.

The models are too heavy to be stored in `trial.user_attrs`.

## Propositions

I think there are 2 options:

- provide a field `callback_data` in `FrozenTrial` that can be set from `objective(trial)` with `trial.set_callback_data(value)` or `trial.set_callback_data(key, value)`

- allow `objective(trial)` to return more complex values, e.g. through an object `Result(value, *args, **kwargs)` that is then used on `callback(study, trial, *args, **kwargs)`

**Comment by g-votte** [comment]
Thanks a lot for your proposal!

I put an example of workaround below, where the callback and the objective are defined as classes.

I'd prefer to keep the Trial interface simpler rather than adding a new method, because the the callback and the objective can directly communicate each other.

What do you think?

### Workaround
```python
import optuna

class Callback(object):
    def __init__(self):
        self.callback_data = None

    def __call__(self, study, trial):
        do_something_with_model(self.callback_data)
        self.callback_data = None

    def set_data(self, data):
        self.callback_data = data

class Objective(object):
    def __init__(self, callback):
        self.callback = callback

    def __call__(self, trial):
        param = trial.suggest_uniform('param', -1, 1)
        model = train_model(param)
        self.callback.set_data(model)
        return evaluate_model(model)

callback = Callback()

study = optuna.create_study()
study.optimize(Objective(callback), n_trials=100, callbacks=[callback])
```

**Comment by louisabraham** [comment]
Thanks a lot, it's very clever! I think it's a good workaround.

**Comment by nlgranger** [comment]
FYI [`functools.partial`](https://docs.python.org/3/library/functools.html#functools.partial) might be a simpler and more idiomatic solution as well.

**Comment by louisabraham** [comment]
@nlgranger do you mean something like this?

``` python

def objective(storage, trial):
        param = trial.suggest_uniform('param', -1, 1)
        model = train_model(param)
        storage['model'] = model
        return evaluate_model(model)

def callback(storage, trial):
        do_something_with_model(storage["model"]

shared_storage = {}

study = optuna.create_study()
study.optimize(partial(objective, shared_storage), n_trials=100, callbacks=[partial(callback, shared_storage)])
```

Basically it works by using closures instead of objects. I don't know how it would behave in a multiprocessing setup though.

**Comment by nlgranger** [comment]
Contrary to a lambda function, the output of partial is picklable if its arguments are (the function is importable and the arguments are pickable).
