### ISSUE TITLE
What happens when providing multiple methods in the CLI?

### ISSUE THREAD

**Issue by louisabraham** [optuna/optuna#814]
Suppose I launch for the same study:

    optuna study optimize main.py objective_1 --storage sqlite:///trials.db --n-trials=100 --study $study_name

    optuna study optimize main.py objective_2 --storage sqlite:///trials.db --n-trials=100 --study $study_name

What happens? Are the values given by the two objectives compared together? Or are they optimized separately? I was not able to find the answer in the documentation.

**Comment by g-votte** [comment]
Hi,

That would be equivalent to the following Python code:

```python
study = optuna.load_study(storage='sqlite:///trials.db', study_name=study_name)
study.optimize(objective_1, n_trials=100)

study = optuna.load_study(storage='sqlite:///trials.db', study_name=study_name)
study.optimize(objective_2, n_trials=100)
```

When the studies refer the same storage and study name, the objective values are compared together sharing the history.

**Comment by louisabraham** [comment]
Hi, thank you for your helpful answer.

Maybe this should be clarified [there](https://optuna.readthedocs.io/en/latest/tutorial/cli.html). I'm willing to do the PR if you want.

**Comment by g-votte** [comment]
Cool! We'd greatly appreciate the PR.
