### ISSUE TITLE
database disk image is malformed

### ISSUE THREAD

**Issue by louisabraham** [optuna/optuna#815]
When launching multiple instances of `optuna study optimize` ~in rapid succession (but by hand)~, I get the following error: 

    [W 2019-12-26 08:12:45,772] Setting status of trial#13 as TrialState.FAIL because of the following error: DatabaseError('(sqlite3.DatabaseError) database disk image is malformed')

## Expected behavior

No error.

## Environment

- Optuna version: 0.19.0
- Python version: Python 3.7.4
- OS: CentOS Linux release 7.5.1804 (Core)

## Error messages, stack traces, or logs

https://pastebin.com/UPaiAm5t

## Steps to reproduce

Launch multiple instances of  `optuna study optimize` ~in rapid succession~.

## Additional context (optional)

I'm launching the tasks over LSF on a cluster with a shared file system.

**EDIT**: the tasks keep failing (even after executing some trials) so it probably isn't related to launching them in rapid succession.

**Comment by g-votte** [comment]
Thank your for reporting the issue.

If your SQLite file is put on NFS, you may need to use a server-based RDB (e.g., PostgreSQL) instead, because SQLite does not support multiple, simultaneous accesses on NFS.

See also:
https://www.sqlite.org/faq.html#q5

**Comment by louisabraham** [comment]
I think you are right about the reason of the issue.
You are also right about server-based RDB like PostgreSQL being a better choice.

However, it is complicated to setup a SQL server in my environment.

Apparently there is a way to use another locking mechanism, using `unix-dotfile` (https://stackoverflow.com/a/46161554/5133167)

According to the [documentation](https://www.sqlite.org/c3ref/open.html), the standard way to put this parameter in the URI is: `file:/home/fred/data.db?vfs=unix-dotfile`.

However, you use another URI format (`sqlite:///trials.db`). Could you tell me more about your URI format? Is it possible to use VFS with it?

**Comment by louisabraham** [comment]
I think you use the URI format from sqlalchemy (https://docs.sqlalchemy.org/en/13/core/engines.html#sqlalchemy.create_engine), thus adding `vfs=unix-dotfile` might work.

In any case it is not an issue of optuna. I'll keep you updated.

**Comment by louisabraham** [comment]
Wow, just using `--storage sqlite:///trials.db?vfs=unix-dotfile` totally solved my issue. This is just magic!

I propose to add it to the documentation!

**Comment by louisabraham** [comment]
So, according to the [sqlalchemy documentation](https://docs.sqlalchemy.org/en/13/dialects/sqlite.html#uri-connections), I was doing it wrong.

I think the correct way to use VFS is the following: `--storage 'sqlite:///file:trials.db?vfs=unix-dotfile&uri=true'`

Now I can sometimes see a `trials.db.lock` file appearing, so I don't know if it is using unix-dotfile. 

I'm pretty sure the `trials.db.lock` file doesn't appear without the vfs option, but at the same time it doesn't *look* like a dotfile.

**Comment by g-votte** [comment]
Thank you for trying your best for this problem.

As you mention, it's sometimes hard to deploy a server-based RDB on the user's environment. So, if there's any workaround to enable distributed optimization on SQLite & NFS, that’s should be documented.
