### ISSUE TITLE
sqlite3.OperationalError: database is locked

### ISSUE THREAD

**Issue by louisabraham** [optuna/optuna#820]
I'm deploying optuna on a single machine through a script that looks like this:

```
optuna create-study […]

for i in $(seq "$1")
do
    optuna study optimize […] &
done

wait

# (copy trials.db from scratch to shared storage)
[…]
```

I got some `sqlite3.OperationalError: database is locked` errors on start (on 7 processes out of 32).

I think that launching all processes at the same time causes them to make requests at the same time (*collide*). I'm lucky that my hyperparameters also control the computation time so that the processes have very low probability to *collide* after starting, but I guess this could also be a source of problems in other workflows that are massively parallel.

I believe this could be fixed by increasing the timeout of the sqlite3 backend. There should be an option to do that from the command line and the API of optuna.

## Alternatives

I added a sleep in my loop.

```
for i in $(seq "$1")
do
    optuna study optimize […] &
    sleep 5
done
```

**Comment by louisabraham** [comment]
Note: I was using sqlite3 as backend.

I think this feature can be implemented through the `connect_args` of [`sqlalchemy.create_engine`](https://docs.sqlalchemy.org/en/13/core/engines.html#engine-creation-api).

The parameter to set for [`sqlite3.connect`](https://docs.python.org/3/library/sqlite3.html#sqlite3.connect) is `timeout` (in seconds).

Another way to implement it would be to have the `optuna study optimize` command take a `n_jobs` parameter. Thus, it would handle a `multiprocessing.Pool` (which would be slightly more efficient than giving the same fixed number of jobs to every process when the computation time varies a lot). The advantage is that it would be possible to adapt the timeout linearly: `timeout = n_jobs * 5.0`.

**Comment by louisabraham** [comment]
I can confirm that I encounter the same issue with a single `optuna study optimize --n_jobs=32`.

I also notice that accessing the SQL database is quite slow, which might be the cause of the timeout.
My trials.db file is 2.7M and contains a single study with 1329 trials. Retrieving `study.best_trial` takes 76 seconds on *very* performant hardware, in the absence of other programs accessing the same database (and, anyway, sqlite supports concurrent read operations).

Hence, I think the problem might rather come from slow SQL queries rather than an insufficient timeout.

Also, I opened my trials.db file without issue using https://sqlitebrowser.org/ and I could reproduce the very long query time on my macOS laptop.
If you want to have a look at my `trials.db` file: https://send.firefox.com/download/c292fe3189875b3d/#pGdujaEMyYS8tXdLK4wETQ

**Comment by louisabraham** [comment]
Oh, the speed is probably increased by https://github.com/optuna/optuna/pull/729

**Comment by kuroko1t** [comment]
I ran into a similar problem when running optuna in 8 parallels using joblib. 

```
Traceback (most recent call last):                                                                                                                                                                          
  File "/home/walter/work/oanda/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context                                                                                 
    cursor, statement, parameters, context                                                                                                                                                                  
  File "/home/walter/work/oanda/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute                                                                                     
    cursor.execute(statement, parameters)                                                                                                                                                                   
sqlite3.OperationalError: database is locked 
```

**Comment by louisabraham** [comment]
@kuroko1t where did you use joblib?

**Comment by kuroko1t** [comment]
I parallelized  optimize function using joblib as follows. i think error frequency was low.

```python3
n_jobs=8
from joblib import Parallel, delayed
r = Parallel(n_jobs=n_jobs)( [delayed(study.optimize)(objective, n_trials=n_trials, callbacks=[mlflow_callback]) for i in range(n_jobs)] )
```

**Comment by Hoiy** [comment]
Received `sqlite3.OperationalError: database is locked` error with only 2 processes optimizing on the same study. Both processes stopped immediately due to this error. This happens rarely though.

**Comment by grafi-tt** [comment]
Probably Python routines are blocking transaction.  Each query itself is not so slow. 

@kuroko1t  @louisabraham Could you try this patch?

```
diff --git a/optuna/storages/rdb/storage.py b/optuna/storages/rdb/storage.py
index 6b41ab7a..95b100a6 100644
--- a/optuna/storages/rdb/storage.py
+++ b/optuna/storages/rdb/storage.py
@@ -701,15 +701,14 @@ class RDBStorage(BaseStorage):
         user_attributes = models.TrialUserAttributeModel.where_trial(trial, session)
         system_attributes = models.TrialSystemAttributeModel.where_trial(trial, session)
 
+        # Terminate transaction explicitly to avoid connection timeout during transaction.
+        self._commit(session)
+
         frozen_trial = self._merge_trials_orm(
             [trial], params, values, user_attributes, system_attributes
         )[0]
 
         self._finished_trials_cache.cache_trial_if_finished(frozen_trial)
-
-        # Terminate transaction explicitly to avoid connection timeout during transaction.
-        self._commit(session)
-
         return frozen_trial
 
     def get_all_trials(self, study_id, deepcopy=True):
@@ -764,12 +763,13 @@ class RDBStorage(BaseStorage):
         user_attributes = models.TrialUserAttributeModel.where_study(study, session)
         system_attributes = models.TrialSystemAttributeModel.where_study(study, session)
 
+        # Terminate transaction explicitly to avoid connection timeout during transaction.
+        self._commit(session)
+
         all_trials = self._merge_trials_orm(
             trials, params, values, user_attributes, system_attributes
         )
 
-        # Terminate transaction explicitly to avoid connection timeout during transaction.
-        self._commit(session)
         return all_trials
 
     def get_n_trials(self, study_id, state=None):
```

**Comment by ghannum** [comment]
Any updates on this? Optuna is amazing and I am working to deploy an optimizer across multiple machines. Unfortunately most of the processes are lost due to the DB locking. The jobs are long-running (hours), so I tried a 0-5min random sleep before each process starts and monkey-patched a 5min default connection timeout, but it hasn't helped.

**Comment by liori** [comment]
@ghannum, for me it helped to put the database file to /dev/shm (RAM-drive) — it doesn't need syncs, so it's faster. Now I can do 16 processes simultaneously and I see zero lock contention.

Also note that if you plan to run it on multiple machines, sqlite won't work properly anyway. When I tried distributed optimization, I used postgresql and it doesn't have this problem.

**Comment by seanbow** [comment]
I get this error extremely frequently, including when starting a new trial, when running across a large number of processes; my code to optimize has to look like 

```
while True:
    try:
        with joblib.parallel_backend("loky"):
            study.optimize(optuna_objective, n_trials=n_trials, n_jobs=n_jobs)
    except (sqlite3.OperationalError, sqlalchemy.exc.InvalidRequestError):
        pass
```

or I get basically nothing done until it crashes.

**Comment by microprediction** [comment]
I get a sqlite blocking error, possibly because of NFS?  
I'm following the instructions here: https://optuna.readthedocs.io/en/stable/tutorial/004_distributed.html

**Comment by Hoeze** [comment]
I guess setting `PRAGMA journal_mode=WAL;` once on database creation would solve this whole issue?

**Comment by louisabraham** [comment]
@Hoeze unfortunately no. WAL mode allows concurrent readers, not concurrent writers. I think the only real solution is to use a larger timeout parameter and make sure queries are optimized.

**Comment by hvy** [comment]
Let me close this issue since it hasn't been observed as frequently as before, that is within use cases suitable for SQLite such as not-too-high level of concurrency or with NFS where file locking is non-trivial (this may have been a result of https://github.com/optuna/optuna/pull/1628). If that'd not be the case, please feel free to reopen or comment if this is still an issue. For instance, if the timeout is a common pitfall, then we could possibly consider setting a large timeout by default, similar to how we set `pool_pre_ping` for MySQL RDBs in https://github.com/optuna/optuna/blob/release-v2.10.0/optuna/storages/_rdb/storage.py#L1134-L1149. And just for the record, rephrasing the documentation, we suggest actually using MySQL or other backends for distributed optimization if possible.
