### ISSUE TITLE
add trials to study / build study from trials

### ISSUE THREAD

**Issue by louisabraham** [optuna/optuna#821]
I would like to add trials to studies or artificially build a study from trials.

The second method might solve https://github.com/optuna/optuna/issues/685 as well

## Motivation

In some workflow, you might want to optimize different metrics that are computed from the same results.

For example, in classification problems, people hesitate to maximize the cross-entropy, the accuracy, the F1 score, etc…
Similarly, when doing k-fold cross-validation, people might want to optimize the average or the minimum of the fold scores.

In all these cases, it is very cheap to compute all the scores instead of just one, and this data could be provided to avoid cold start in other runs.

## Description

I think that providing an argument `trials` in `create_study` would be the most practical solution, as it avoids having to reindex a database.
It also solves https://github.com/optuna/optuna/issues/685 without having to actually delete trials because users will be able to recreate a study object with a clean list of trials.

**Comment by louisabraham** [comment]
I saw the related issue #745 that has the same motivation. Sorry for not searching more.

This feature could be implemented with `Study._append_trial`. I think that such a workaround would work for #685 as well.

**Comment by sile** [comment]
Thank you for your proposal!

Providing a feature to add trials to studies or build a study from trials sounds useful and, as you said, it could be implemented on top of `Study._append_trial()`.  Let me label this issue as a contribution welcomed.
I think that there are a lot of design choices to implement this feature (e.g., What is the best API to provide this feature? [a] "Adding `trials` option to `optuna.create_study` method", [b] "Creating a new function such as `optuna.build_study`", [c] "Adding a method such as `import_{trials|study}` to `Study` class", etc), but we could discuss the design on a draft (WIP) PR if someone creates it.

**Comment by hvy** [comment]
@louisabraham Two new experimental APIs were introduced in #1335, one for adding trials to a study and for creating arbitrary trials (this is a rather low-level API). They should address this issue. Have you taken a look at it? I'm wondering if we cannot close this issue as resolved.

**Comment by louisabraham** [comment]
Sure, it looks very much resolved. I'll play with them later. Thank you for your hard work!
