### ISSUE TITLE
Sampler restart

### ISSUE THREAD

**Issue by louisabraham** [optuna/optuna#823]
Include a restart feature in general or for specific samplers (like TPESampler)

## Motivation

Bayesian optimization can get stuck in local minima. After a consequent number of iterations, it will only try values that are close.

Restarting the optimization solves this issue.

## Description

Restarting the sampler (making it ignore the past) could work well. It is a technique already used by SAT solvers.

The simplest interface to propose this would be to restart the optimization after `n_restart` trials. Another would be `patience` that restarts the optimization after `patience` trials without improvement.

I think that it could be first implemented for `TPESampler` only (as it is currently the only sampler with memory).
Maybe it can be implemented later as a decorator for samplers in general.

**Comment by louisabraham** [comment]
Some material that support my claim:

- https://www.cs.toronto.edu/~hinton/csc2515/notes/gp_slides_fall08.pdf (which is about GP) says: *If    optimizing    hyper-parameters, (as    always)    random restarts or other tricks to avoid local optima are advised.*

**Comment by hvy** [comment]
Thanks @louisabraham for the request and also the reference material. I couldn't find similar features in other HPO frameworks but would you happen to have such references as well? I'm still curious how common or beneficial this would be to the general user considering the fact that similar restarts can be simulated by creating multiple studies. A side note for implementing restarts, we might need to be able to delete trials from storages in (e.g. https://github.com/optuna/optuna/issues/685) so prototyping might not be straight forward.

**Comment by louisabraham** [comment]
Thanks @hvy for your answer.

I don't think this feature has been implemented or even described and plan to write a paper to test it.

I think it's ok to keep the data in the storage. The "restart" can be implemented by ignoring some past trials based on their index (so it's more like a filter).

**Comment by hvy** [comment]
Looking forward to your paper. 👍  Do you have further ideas on how to implement it that you might be able to share? As for filtering past trials, we've actually recently merged an implementation of the [Hyperband pruner](https://github.com/optuna/optuna/pull/809) which defines its own [Study subclass](https://github.com/optuna/optuna/blob/master/optuna/pruners/hyperband.py#L144-L178) overriding `get_trials` to do precisely this. It might be a starting point.

**Comment by HideakiImamura** [comment]
Thanks for the suggestion! I think that restarting samplers is useful when the evaluation of the objective function is low costs, but less useful when the evaluation of the objective function is high costs, such as in neural network hyperparameter search. This functionality should be implemented with documentation about it.

**Comment by HideakiImamura** [comment]
The user should be able to change the sampling algorithm at will. This sampling algorithm is another one that the user should be able to choose from. However, since there has been no comment from anyone for a while, please let me close this issue for the moment. If more users want this feature, I'll open this issue up again for discussion.
