### ISSUE TITLE
How so I start new optuna run with known hyperparams?

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#834]
I have an "old" known dict with "good" hyperparams.
Now I want to start a new optuna run and want to "inject" the known hyperparams
so optuna uses / tests them once. How is this possible?

PS: Many thanks for your work and time for this great tool by the way.

**Comment by toshihikoyanase** [comment]
Thank you for your question.

I think it is similar to the issue #821. As mentioned in [this comment](https://github.com/optuna/optuna/issues/821#issuecomment-571380629), you can use `Study._append_trial()` to inject existing results into a study as a workaround.

I created a notebook to demonstrate the usage of `Study._append_trial()`, so please take a look at it. https://colab.research.google.com/drive/1QyB1smD4jLUi510M4GkM8fG7QBOlgEyE

**Comment by PhilipMay** [comment]
Thanks. :-)

**Comment by toshihikoyanase** [comment]
@PhilipMay 
I'm sorry but I shared the private URL of Colab example.
The correct URL is as follows:
https://colab.research.google.com/drive/1pDq4k4OOW0ZTilqqQIME0j_q_-8T4Ty-
