### ISSUE TITLE
Visualizations don't work in Jupyter Lab

### ISSUE THREAD

**Issue by srizvan** [optuna/optuna#837]
Visualizations don't work in Jupyter Lab. I see just empty (white) plots. In Jupyter Notebook everything is OK.

## Expected behavior

Visualizations should be available from Jupyter Lab.

## Environment

- Optuna version: 1.0.0
- Python version: 3.7.4
- OS: Ubuntu 18.04.3
- (Optional) Other libraries and their versions:
plotly==4.4.1
jupyterlab==1.2.4
jupyterlab-server==1.0.6

## Steps to reproduce

1. Create a study object. 
2. Run study.optimize
3. Plot any visualization.

## Reproducible examples (optional)

```python
optuna.visualization.plot_slice(study)
```
Or any other plot.
## Additional context (optional)

Screenshot of empty visualization:
![image](https://user-images.githubusercontent.com/3490922/72460097-d6873100-37d4-11ea-9433-62a4824622aa.png)
There is an error in the browser console:
![Screenshot from 2020-01-15 20-26-45](https://user-images.githubusercontent.com/3490922/72460658-e6ebdb80-37d5-11ea-9b0e-8077ad5eee90.png)
![Screenshot from 2020-01-15 20-27-13](https://user-images.githubusercontent.com/3490922/72460675-efdcad00-37d5-11ea-9283-4f70b860830d.png)

**Comment by harupy** [comment]
@srizvan Did you follow the steps stated [here](https://github.com/plotly/plotly.py#jupyterlab-support-python-35)?

**Comment by toshihikoyanase** [comment]
@srizvan Thank you for reporting the issue.
I reproduced your issue and found that the additional installation step suggested by @harupy solved it as follows:

![image](https://user-images.githubusercontent.com/3255979/72491134-7936c280-385c-11ea-9eab-643ae6ef150f.png)

@harupy Thank you for your information.

## Environment
- Optuna version: 1.0.0
- Python version: 3.7.2
- OS: macOS 10.13.6
- Other libraries and their versions:
  - plotly==4.4.1
  - jupyterlab==1.2.4
  - jupyterlab-server==1.0.6

**Comment by srizvan** [comment]
@harupy Yeah, that worked for me. Thank you.
I think, link to these additional steps should be provided in optuna docs in the "Installation" section.

**Comment by toshihikoyanase** [comment]
@srizvan Thank you for your feedback.
I created a PR (https://github.com/optuna/optuna/pull/843) to update the document for `JupyterLab` users to solve this issue. Please let me know if you have any comments.

**Comment by darkmatter2222** [comment]
Had the same issue, Then I had a build failed issue on Jupyterlab 3.0.4, Upgraded to Jupyterlab 3.0.10 according to this post, fixed it for me:
https://github.com/jupyterlab/jupyterlab-latex/issues/135
