### ISSUE TITLE
Add LightGBM Tuner example

### ISSUE THREAD

**Issue by smly** [optuna/optuna#846]
##  Motivation

Please add an example that shows the usage of [LightGBM Tuner](https://github.com/optuna/optuna/tree/master/optuna/integration/lightgbm_tuner). There is [an unofficial example code](https://gist.github.com/smly/367c53e855cdaeea35736f32876b7416) used for development, but it's not simple enough and not suitable as example code.

## Description

1. Create an example that shows the usage of LightGBM Tuner in `examples/`.
2. Update `examples/README.md` with mentions to the new example code.

**Comment by sile** [comment]
Added by https://github.com/optuna/optuna/pull/860.
