### ISSUE TITLE
please release to allow scipy >= 1.4.1

### ISSUE THREAD

**Issue by taxio** [optuna/optuna#859]
## Motivation
I want to install tensorflow v2.1 and optuna v1.0 using pip.

## Description
tensorflow v2.1.0 requires scipy v1.4.1, so we cannot install and lock (using pipenv) tf v2.1 and optuna v1.0.0.
https://github.com/tensorflow/tensorflow/commit/54daf3c5700897a6062313983933ca28e92c410d

It is fixed here, so please release it for use with pip.
https://github.com/optuna/optuna/commit/7c9461f63848b474990457c652dc3e684ffeb731#diff-2eeaed663bd0d25b7e608891384b7298
https://github.com/optuna/optuna/commit/ea4cc8db02ab16719132a134e1afafa86f7aa248#diff-2eeaed663bd0d25b7e608891384b7298

thanks.

**Comment by crcrpar** [comment]
I don't know much about pipenv, however, I could install Optuna master version via `pipenv install -e git+https://github.com/optuna/optuna.git#egg=optuna` after tf v2.1.0 installation.

So could you try it as a workaround?
Generated Pipfile and Pipfile.lock are available [here (gist)](https://gist.github.com/crcrpar/6622f7a5d391bd92ab9f561d47541c55).


Thanks.

**Comment by taxio** [comment]
Thank you, that solved my problem.
I will use this workaround until the next release.

Thanks.

**Comment by crcrpar** [comment]
My pleasure and thank you for using Optuna!

As the problem seems to be resolved, let me close this issue.
If you have further questions/problems, feel free to reopen 😃

**Comment by eafpres** [comment]
Hi--today I had to update my keras/tensorflow, and during that I got this:
ERROR: optuna 1.0.0 has requirement scipy<1.4.0, but you'll have scipy 1.4.1 which is incompatible.
I looked at the workaround above but apparently pipenv isn't for Windows systems.  Is there another workaround?

**Comment by sile** [comment]
@eafpres I'm not sure but you might be able to resolve the issue by updating optuna to [v1.1.0](https://github.com/optuna/optuna/releases/tag/v1.1.0). The version contains the patch https://github.com/optuna/optuna/pull/838, which relaxed scipy version restriction.
