### ISSUE TITLE
Using optuna with an existing argument parser without changing

### ISSUE THREAD

**Issue by victorhcm** [optuna/optuna#862]
It's not technically a issue with the documentation, just wanted to share in case someone finds it useful.

I already had an existing code, which handled argument parsing from command line using `argparse`. After I played with it a bit, I wanted to plug-in a hyperparameter tuning library to do a more thorough search. I wanted a way to change as little as possible of the existing code, while still making possible to use the argument parser and easy to maintain. 

A solution is to always parse `args` with the default values and after overwrite them with the `trials` parameters. Then, you can use it with either `args['lr']` or `args.lr`. Example:

```
def update_args_(args, params):
  """updates args in-place"""
  dargs = vars(args)
  dargs.update(params)


def main(trials=None):
  parser = argparse.ArgumentParser()
  parser.add_argument('--lr', type=float, default=0.01)
  args = parser.parse_args()
  if trials is not None:
    params = {'lr': trials.suggest_loguniform('lr', 1e-7, 1e2)
    update_args_(args, params)
  optimizer = optim.SGD(model.parameters(), lr=args.lr)
  
if __name__ == '__main__':
  study = optuna.create_study(direction='maximize')
  study.optimize(main, n_trials=10)
  #main()  # uncomment to run normaly
```

This way, you still keep both options. If you just want to disable `optuna` and run with `argparse`, just comment out `main` and remove the `study` lines. Or keep another file only for hyperparameter tuning.

Let me know what you think. I've just started using `optuna`, maybe there is an easier way.

**Comment by sile** [comment]
Thank you for sharing your knowledge!
It seems a good way to use `optuna` with existing scripts that use  `argparse` for parameter handling. I think this issue could help users who have a similar motivation to you.

**Comment by bagustris** [comment]
@sile @victorhcm 

Can we make optuna as command line argument too? In this way, if flag `--optional` is given, then run optimization (action=store_true); otherwise, run normal code.

```python
def update_args_(args, params):
  """updates args in-place"""
	dargs = vars(args)
  	dargs.update(params)


def main(args,trials=None):
  	if trials is not None:
   		params = {'lr': trials.suggest_loguniform('lr', 1e-7, 1e2)}
    	update_args_(args, params)
  		optimizer = optim.SGD(model.parameters(), lr=args.lr)
  
if __name__ == '__main__':
  	parser = argparse.ArgumentParser()
  	parser.add_argument('--lr', type=float, default=0.01)
  	parser.add_argument('--optuna', action=store_true)
	args = parser.parse_args()
 	if args.optuna: # run optimization 
  		study = optuna.create_study(direction='maximize')
  		study.optimize(main, n_trials=10)
	else:  
  		main(args)  # run normally
```
