### ISSUE TITLE
Update the TensorFlow Estimator example using v2 APIs.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#883]
## Motivation

Thanks to #868 and #871, the examples for TensorFlow Estimator works with tensorflow>=2.0.0. In the PRs, they use `tf.compat.v1` mainly to minimize the changes, but they will possibly be obsolete in the future. So, we'd like to update the examples before TensorFlow stops the support of v1 APIs.

## Description

Please update the following examples using v2 APIs of TensorFlow.
- [`examples/tensorflow_estimator_simple.py`](https://github.com/optuna/optuna/blob/master/examples/tensorflow_estimator_simple.py)
- [`examples/pruning/tensorflow_estimator_integration.py`](https://github.com/optuna/optuna/blob/master/examples/pruning/tensorflow_estimator_integration.py)

**Comment by nuka137** [comment]
@toshihikoyanase (cc: @arpitkh101)

I created PR which uses only v2 API. (#924)
This PR uses premade estimator API instead of API sets of `tf.compat`.
After I created PR, I noticed that @arpitkh101 already created PR which uses `tf.compat.v2`.
Should I rename this example to co-exist?
Thanks!
