### ISSUE TITLE
Order of reported intermediate values of a trial

### ISSUE THREAD

**Issue by DiegoAE** [optuna/optuna#886]
Does optuna guarantee to keep the reported order of  intermediate values regardless of the RDB used?
 
I'm using postgresql as DB backend, and when I try to plot the intermediate values using `plot_intermediate_values` I get strange plots (see attachment). The reason is related with the order in which the values are loaded for plotting. For instance, the orange trial in the upper part loads the dict of intermediate values for this trial as

{25000: -420.132089545027,
 30000: -461.073589166884,
 35000: -493.014014158327,
 40000: 85.453304063718,
 45000: 98.6072901902456,
 50000: 271.517424397106,
 55000: 614.05717144259,
 60000: 1102.79160252844,
 65000: 637.04922785821,
 70000: 92.5157460887142,
 75000: -512.314565530847,
 80000: 967.921720361361,
 85000: 856.174318172077,
 90000: 596.00633805556,
 95000: 698.093177913438,
 100000: 997.815513715976,
 0: -380.307031912816,
 5000: -390.387695584246,
 10000: -393.329570763645,
 15000: -412.837543059368,
 20000: -397.384081713904,
 105000: 813.094247561564,
 110000: 828.6297210501,
 115000: 537.85912622827,
 120000: 981.642618449514}

Clearly, the entries of the keys 0, 5000, 10000, 15000, 20000 are misplaced
![newplot](https://user-images.githubusercontent.com/2078348/73611672-61916500-45e4-11ea-8e07-18b8b7801a76.png)
.

**Comment by toshihikoyanase** [comment]
Thank you for reporting the issue.

It seems to be a bug of [`FrozenTrial`](https://optuna.readthedocs.io/en/stable/reference/structs.html#optuna.structs.FrozenTrial) and [`Storages`](https://optuna.readthedocs.io/en/stable/reference/storages.html), and I created a PR (i.e., https://github.com/optuna/optuna/pull/887) to fix it.

If the PR does not work in your environment, could you show us your environment in more detail? The information like Python version, PostgreSQL version, OS, objective function will be a great help of us.

**Comment by DiegoAE** [comment]
Thanks for the prompt fix @toshihikoyanase.
