### ISSUE TITLE
Is it possible to add suggest_discrete_int?

### ISSUE THREAD

**Issue by hayata-yamamoto** [optuna/optuna#888]
Hello, Developers, 
Is it possible to add `suggest_discrete_int` method to trial?

## Motivation

We want to make a grid somehow so that parameter search becomes more efficient and less time-consuming. 

## Description

Optuna already has a discrete_uniform method on optuna.Trial. It's quite useful, but some of the models require integer values as their arguments. For instance, XGBoost. Since n_estimator and max_depth must be an integer, it raises an error when I pass float values to these. 

Therefore, `trial.suggest_int` or `trial.suggest_categorical` are used so that I input the values I want. If optuna has a feature of throwing discrete integer, this operation could vanish.  

## Alternatives (optional)

From my perspectives, there are two options, 

1. To cast discrete_uniform output as an integer
2. To use suggest_categorical like `suggest_categorical('hoge', np.arange(0, 10, 2))`

**Comment by toshihikoyanase** [comment]
Hi @hayata-yamamoto,

Thank you for your request!
We have already received similar requests like https://github.com/optuna/optuna/issues/510 and are discussing the design of new APIs there. (The last comment was about four month ago, though.) I think the (b) API of [this comment](https://github.com/optuna/optuna/issues/510#issuecomment-536868317) is corresponding to your request.

> (b) [MODIFIED] Trial.suggest_int(name: str, low: int, high: int, q: Optional[int]) (
suggest_int(name, low, high, q=10) is equivalent to Trial.suggest_discret_int(name, low, high, q=10)

So, I think we can merge this issue into https://github.com/optuna/optuna/issues/510. If it's OK, please add your comments there and close this issue.

**Comment by hayata-yamamoto** [comment]
@toshihikoyanase 
Nice information! I'm sorry for bothering you! 

I'll close this issue
