### ISSUE TITLE
Add an example to use `XGBoostPruningCallback` with `xgboost.cv`.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#891]
## Description

Thanks to #865 , `XGBoostPruningCallback` works with `xgboost.cv` (i.e., the cross-validation feature of XGBoost). As suggested in [this comment](https://github.com/optuna/optuna/pull/865#pullrequestreview-352015224), please add a new example to `examples/pruning` in order to demonstrate how to use the pruning feature with the cross-validation.

Please note that `xgboost.cv` does not return booster while `xgboost.train` does. So, please design the appropriate objective values so that readers can imagine their use-cases.

**Comment by yutayamazaki** [comment]
@toshihikoyanase I will work on this issue.

**Comment by toshihikoyanase** [comment]
@yutayamazaki Thank you!

**Comment by toshihikoyanase** [comment]
Resolved by https://github.com/optuna/optuna/pull/907. Closing.
