### ISSUE TITLE
Question: Is it ok to open SQLite database file twice?

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#894]
While I do a training with:
``` python
study = optuna.create_study(
        direction='maximize', 
        study_name="training_01", 
        storage='sqlite:///data/training_01.db',
        load_if_exists=True,
        )
```

I want to open up an other notebook and read the data from the database like you describe here: https://optuna.readthedocs.io/en/stable/tutorial/rdb.html#experimental-history

The question is: is it ok to open the database file (SQLite) twice? 

Thanks
Philip

**Comment by sile** [comment]
Thank you for your question.

It's okay unless you place an SQLite database file on NFS. 
SQLite doesn't allow multiple applications to open the same database file on NFS simultaneously. If you are interested in the detail, please refer to [the SQLite official FAQ entry](https://www.sqlite.org/faq.html#q5).

**Comment by PhilipMay** [comment]
Awsome. Thanks!
