### ISSUE TITLE
[RFC] BatchTrial that suggests and evaluates multiple configuration sets at once.

### ISSUE THREAD

**Issue by toshihikoyanase** [optuna/optuna#895]
## Motivation

In training/inference of neural networks, data are usually processed using mini-batch to accelerate the data process using devices like GPUs. Thanks to the tensor computing frameworks including numpy and cupy, it is easy to write such batched functions for usual numerical optimization.

Currently, Optuna hardly benefits from such batched functions because it assumes each trial suggests only a single parameter value per parameter type.

## Description

This issue proposes `BatchTrial`. The suggest functions of `BatchedTrial` return multiple values for each type of parameter. The following code shows a simple use-case of `BatchTrial`.

```python
def objective(batched_trial):
    x = batched_trial.suggest_uniform('x', 0, 1)  # [0.1, 0.3, 0.9]
    y = x**2
    return y  # [0.01, 0.03, 0.09]
```

I create a prototype implementation in the [notebook](https://colab.research.google.com/drive/1yBDQcKt07n5pQeNmby-zv7uQ9mKoMTMS).

## Alternatives (optional)

We may be able to implement this feature as a helper function without modifying Optuna's core code.

## Additional context (optional)

This feature may relate to [this comment in Gitter](https://gitter.im/optuna/optuna?at=5e3835f158f02e34975e83ec).

**Comment by hvy** [comment]
Just to make it clear, this is the most recent PR https://github.com/optuna/optuna/pull/1729.

For the record, batch evaluation (not suggestion) is now possible using the ask and tell interface as discussed in https://github.com/optuna/optuna/issues/2387.
