### ISSUE TITLE
Hyperband Usage Documentation

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#906]
First many thanks for the new hyperband pruner.

I would like to request some more information on how to use it. I guess that it is necessary to tune the default parameters. Maybe you could provide some more information then just link to the papers. When should I set which parameter to what value?

The paper talks about an infinite horizon setting. Since I often do not set the number of iterations on optuna but stop it with KeyboardInterrupt is that relevant for me?

Many thanks
Philip

**Comment by PhilipMay** [comment]
Maybe you both could help with this? @crcrpar @arita37

**Comment by PhilipMay** [comment]
For example I am interested in the question on how to configure the Hyperband pruner when your trial needs 5 hours to fit and when you can only afford to calculate like 40 trials. And under which conditions is it useful to change the default parameters?

**Comment by keisuke-umezawa** [comment]
@PhilipMay I added explanations #972. How about it?

**Comment by PhilipMay** [comment]
@keisuke-umezawa Thanks! I will have a look into it and give feedback.

**Comment by PhilipMay** [comment]
@keisuke-umezawa What about applying the HyperbandPruner to a 5 or 7 fold cross validation?
In that situation I only have 5 or 7 steps. 
Is that possible / useful? Or do I need something with many steps?

**Comment by PhilipMay** [comment]
This is great! Thanks.
