### ISSUE TITLE
Clean running trials

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#913]
## Motivation

You do not have to specify the number of trials in `study.optimize`. Then you can stop the optimization with "KeyboardInterrupt". When your optuna is connected to a DB the trail you interruped will stay in status "running" for ever. I am not sure what this means for the optimizer but my guess is that it is not good when you restart the optimization. This is because optuna thinks that a 2nd process is running on the DB and has not ended.

## Description of the new feature

What about a new parameter in the `optuna.create_study` function called `clean_running` with `False`as default. When you set it to `True` it removes all running trials when opening the DB. If you set it to `True` the `load_if_exists` also has to be `True`.

## Alternatives (optional)

I don't know.

**Comment by PhilipMay** [comment]
I would really appreciate feedback on this. Maybe it is a cli feature. What do you think?

**Comment by sile** [comment]
Thank you for your proposal, and sorry for the delayed response.
I think that it's good to add a feature to clean such zombie trials. However, IMO, it feels a bit weird to add `clean_running` option to `optuna.create_study()` function. To keep `create_study` function simple, I prefer adding a didicated function (e.g., `optuna.study.clean_running_trials(study: Study)`) for this porpose. Once implemented the function, we could provide a CLI interface to call it if need.
What do you think of it?

**Comment by sile** [comment]
**FYI** As an alternative approach, it might be possible to add handling of "KeyboardInterrupt" signal (see also #485 ).

**Comment by hvy** [comment]
I personally find the `KeyboardInterrupt` signal handler approach to be cleaner, trying to reduce zombie trials in the first place. I guess  that it on the other hand requires quite a bit of work (incl. writing exhaustive tests). So, it could be tackled at a later time.

**Comment by chenghuzi** [comment]
Agree with @hvy , just started using Optuna and faced the same issue. So I made some experimental changes [here](https://github.com/chenghuzi/optuna/commit/da0590d45ccb5c159e883aa5d566fa3fe37f9d4b) in the storage part and it works. Just removed running trial records from the database.

But this causes another problem: in `in_memory.py` we cannot directly delete elements from `trials` as `get_trial` relies on the order of trials.

## One solution:
Change the type of `trials` to dict and remove elements would be safe. 
**Pros:**
Just change the method we create new trials would be ok.
**Cons:**
May influence other parts especially the test.

## Alternative:
Clean zombie trials in database through setting their states to `FAIL`.
**Pros:**
`storage` and `in_memory` will be consistent.
**Cons:**
May influence restarted optimization as we want to continue those trials.

Suggestions?

**Comment by sile** [comment]
@PhilipMay Do you still want this feature? By reviewing https://github.com/optuna/optuna/pull/1038, it turned out that it's not an easy task to tackle this issue considering distributed optimization, so if not important, I think that it might be better to close this issue.

**Comment by PhilipMay** [comment]
Closing it. Thanks for asking.

**Comment by sile** [comment]
Thank you for the swift response!
