### ISSUE TITLE
How to change schema in postgresql to store the study.

### ISSUE THREAD

**Issue by i-Hun** [optuna/optuna#961]
I put postgresql connection string into a`storage`argument in `create_study` method and got an error, since optuna trying to create new table in a public schema, which I can not access. Could someone help me and say how to change the schema to another one?

**Comment by toshihikoyanase** [comment]
Optuna uses [`sqlalchemy`](https://www.sqlalchemy.org/) to handle RDB access, and I think you can change the schema using [database URLs](https://docs.sqlalchemy.org/en/13/core/engines.html#database-urls). For example, if your schema is `myschema`, the URL will be as follows:

`postgres+psycopg2://username:password@localhost:32007/optuna?options=--search_path%3Dmyschema`

**Comment by toshihikoyanase** [comment]
@i-Hun 
Let me close this issue. Please feel free to re-open it or create new issues if you have further problems.

**Comment by qiuxiaomu** [comment]
You don't create new schema as the public schema is the default schema for any newly created database in `Postgresql`. What went wrong was that you didn't set up your privileges correctly at the outset.  The superuser needs to grant all privileges on the public schema in the new database specifically created for optuna (this is optional) to the new user (I recommend you create a new user for optuna). 

```
CREATE DATABASE EXAMPLE_DB;
CREATE USER EXAMPLE_USER WITH ENCRYPTED PASSWORD 'Sup3rS3cret';
GRANT ALL PRIVILEGES ON DATABASE EXAMPLE_DB TO EXAMPLE_USER;
\c EXAMPLE_DB postgres
# You are now connected to database "EXAMPLE_DB" as user "postgres".
GRANT ALL ON SCHEMA public TO EXAMPLE_USER;
```

This is a code snippet from [this answer on SO](https://stackoverflow.com/questions/67276391/why-am-i-getting-a-permission-denied-error-for-schema-public-on-pgadmin-4), this should be all that you need to set up the database in postgresql for optuna.

Note that if your database is local you need to ensure your user `optuna` can log in via password (md5) by setting relevant bit in pg_hba.conf (Linux only).
