### ISSUE TITLE
Exception/Method to exit a study.

### ISSUE THREAD

**Issue by g-votte** [optuna/optuna#966]
## Motivation

The motivation of this issue is to enable the user to customize the exit criterion of a study. We've already had similar request in #850 where the user want to give a performance threshold. In addition, this feature would improve the `GridSampler` so that the user do not have to specify `n_trials`, as discussed in https://github.com/optuna/optuna/pull/665#discussion_r361424127.

## Description
This feature can be implemented as `optuna.exceptions.StopStudy`, which is caught and handled by the study object so that it stop running even if the number of finished trials does not meet `n_trials`.

The following snippet shows one of use-cases. The exception can be raised either in an objective function or a callback. 

```python
import ...

def objective(trial):
    ...

def callback(study, trial):
    if trial.value < EXIT_THRESHOLD:
        raise StopStudy

study = optuna.create_study()
study.optimize(objective, callbacks=[callback])
```

To help `GridSampler` (and the other samplers) stop the study, we'd need to support raising the exception inside `infer_relative_search_space` and `sample_relative`, which we may need some more design discussion.

## Alternatives
Another option is to provide some method/function to stop a study. In my opinion, providing an exception is more consistent with the current Optuna design, since we already have `optuna.exceptions.TrialPruned`.

**Comment by VladSkripniuk** [comment]
Could you help me to understand what has to be done here? It looks like the code provided in the description solves the task. Here is an example:
```
import optuna
from optuna.exceptions import StopStudy

def objective(trial):
    x = trial.suggest_uniform('x', 0, 1)
    return x

EXIT_THRESHOLD = 0.5

def callback(study, trial):
    if trial.value < EXIT_THRESHOLD:
        raise StopStudy

study = optuna.create_study()
study.optimize(objective, callbacks=[callback])
```
which makes the study stop once the `EXIT_THRESHOLD = 0.5` is achieved:
```
[I 2020-03-05 21:12:08,942] Finished trial#0 resulted in value: 0.5258333026159131. Current best value is 0.5258333026159131 with parameters: {'x': 0.5258333026159131}.
[I 2020-03-05 21:12:08,991] Finished trial#1 resulted in value: 0.13087708031224587. Current best value is 0.13087708031224587 with parameters: {'x': 0.13087708031224587}.
Traceback (most recent call last):
  File "example_stop_study.py", line 15, in <module>
    study.optimize(objective, callbacks=[callback])
  File "/home/user/optuna_env/optuna/optuna/study.py", line 319, in optimize
    gc_after_trial, None)
  File "/home/user/optuna_env/optuna/optuna/study.py", line 597, in _optimize_sequential
    self._run_trial_and_callbacks(func, catch, callbacks, gc_after_trial)
  File "/home/user/optuna_env/optuna/optuna/study.py", line 631, in _run_trial_and_callbacks
    callback(self, frozen_trial)
  File "example_stop_study.py", line 12, in callback
    raise StopStudy
optuna.exceptions.StopStudy

```

**Comment by g-votte** [comment]
Hi @VladSkripniuk ,

Thanks a lot for your taking a look into this issue.

The expected behavior is catching the `StopStudy` inside the study object to safely get back from the `optimize` method, instead of terminating the script with the error.

It might be helpful to see how the study object handles `TrialPruned` raised in an objective function: https://github.com/optuna/optuna/blob/master/optuna/study.py#L649-L663

**Comment by VladSkripniuk** [comment]
Thank you @g-votte for clarifications! I added some code to catch the `StopStudy` inside the study object.

**Comment by hvy** [comment]
A PR is ongoing https://github.com/optuna/optuna/pull/1025.

**Comment by g-votte** [comment]
Let me close this issue, because #1025 has been merged.
