### ISSUE TITLE
Eval loop running twice in PyTorch ignite example?

### ISSUE THREAD

**Issue by leonweber** [optuna/optuna#970]
I am currently going through the example for the PyTorch ignite documentation. I am wondering why we need an ```evaluator``` and another ```pruning_evaluator``` that both run during evaluation. Isn't this a problem for expensive evaluation loops?

**Comment by leonweber** [comment]
Never mind. I just didn't read the code correctly. The pruning evaluator is run after each epoch, and the other evaluator is only used once after training has finished.

**Comment by hvy** [comment]
I suppose you mean this example https://github.com/optuna/optuna/blob/master/examples/pytorch_ignite_simple.py. You have a perfectly valid point and I think this example can be simplified in two ways.
1. Do no run `evaluator` in the callback. We don't have to run an expensive function just to print the training error.
1. Stick to one evaluator (that prunes as necessary).

Let me create a PR to fix the example/
