### ISSUE TITLE
Pruning `n_warmup_steps` documentation issue.

### ISSUE THREAD

**Issue by PhilipMay** [optuna/optuna#976]
The documentation of `n_warmup_steps` seems to be misleading. It sais:

> Pruning is disabled until the trial reaches the given number of step.

See here: https://github.com/optuna/optuna/blob/master/optuna/pruners/percentile.py#L86

But the code sais:
```
        n_warmup_steps = self._n_warmup_steps
        if step <= n_warmup_steps:
            return False
```

The correct documentation should say: "Pruning is disabled until the trial exceeds the given number of step."

What do you think? I can provide a PR if you want...

**Comment by toshihikoyanase** [comment]
@PhilipMay Good catch! Please go for it.

**Comment by PhilipMay** [comment]
PR on #980
